### ISSUE TITLE
Using strongly-typed hub like before

### ISSUE THREAD

**Issue by slotwinskim** [aspnet/AspNetCore#10195] opened 2019-05-12 20:17 UTC
### I try to use strongly-typed Hub like [here](https://github.com/jamiehumphries/SignalR.HubStrong). But I cannot see any example in SignalR Core.

Is this possible to create connection with HubConnectionBuilder.
```
var connection = new HubConnectionBuilder()
  .WithUrl("http://localhost:5000/ChatHub")
  // ???
  .Build();
```
And then tell server or client what are they able to do (communicate)?
```
var hub = hubConnection.CreateHubProxy<IChatHub>("ChatHub");
// ...
hub.MapClientMethods<IChatHubClient>(client);
```

**Comment by anurse** [comment] 2019-05-14 17:25
> But I cannot see any example in SignalR Core.

That would be a question for [the developers of SignalR.HubStrong](https://github.com/jamiehumphries/SignalR.HubStrong). That project isn't related to our team.

SignalR doesn't provide any built in feature to do this. We have https://github.com/aspnet/AspNetCore/issues/5278 tracking the idea for the future.

Closing this as a duplicate of https://github.com/aspnet/AspNetCore/issues/5278

**Closed by anurse** 2019-05-14 17:25 UTC
Labels: area-signalr
