### ISSUE TITLE
Test failure: _7_PublishIncremental

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3680] opened 2018-10-19 20:59 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=32874) with the following error:

```
  Expected: equivalent to < "angular.deps.json", "angular.dll", "angular.pdb", "angular.runtimeconfig.json", "Microsoft.CSharp.dll", "Microsoft.VisualBasic.dll", "Microsoft.Win32.Primitives.dll", "Microsoft.Win32.Registry.dll", "mscorlib.dll", "netstandard.dll"... >
  But was:  < "angular", "angular.deps.json", "angular.dll", "angular.pdb", "angular.runtimeconfig.json", "angular.Views.dll", "angular.Views.pdb", "appsettings.Development.json", "appsettings.json", "libclrjit.dylib"... >
  Extra (1): < "Microsoft.IdentityModel.JsonWebTokens.dll" >

```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-10-19 20:59
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-29 12:52
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 8 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) on release/2.2 at 12:38:50 PM:
- _7_PublishIncremental
- _7_PublishIncremental
- _7_PublishIncremental
- _7_PublishIncremental
- _7_PublishIncremental
- _7_PublishIncremental
- _7_PublishIncremental
- _7_PublishIncremental

**Comment by natemcmaster** [comment] 2018-10-29 15:50
Duplicate of https://github.com/aspnet/AspNetCore/issues/3686

**Closed by natemcmaster** 2018-10-29 15:50 UTC
Labels: Branch:release/2.2, test-failure
