### ISSUE TITLE
Disallow having  the same name of a component and page directive in Blazor

### ISSUE THREAD

**Issue by neven10** [aspnet/AspNetCore#9589] opened 2019-04-20 00:34 UTC
### Describe the bug

Server Side Blazor App

Having @ page' directive name, same as component name,  bricks app and VS.

### To Reproduce
1. Using this version 

Microsoft.NETCore.Platforms  3.0.0.preview4.19212.13
runtime.win-x64.Microsoft.NETCore.DotNetAppHost 3.0.0-preview4-27615-11
Visual Studio 16.1.0 Preview 1.0

2. Run this code 

```
@page "/apptest"

<AppTest></AppTest>
```
or 
`<apptest></apptest>` since it's not case sensitive

3.  Navigate to page

4.  IIS maxes all RAM very fast. No exception is thrown at all. App continues to work , barely.

**Comment by neven10** [comment] 2019-04-21 03:18
```
@page "/test"

<test></test>

@functions 
{
   protected override async Task OnInitAsync()
        {

          await Task.Delay(30);

        }
}

```
Set breakpoint on method and it will go on indefinitely when navigated to page.
So maybe issue some warning? It's not something obvious at first sight.

Also here's the end of dump when components start pilling up in memory.
```
00007ffb1da86040     4780       401142 System.String
00007ffb1da86588      259       544655 System.Byte[]
00007ffb1e458be0        2    125829408 Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiff[]
00007ffb1e478f88        2    143987760 System.Collections.Generic.Dictionary`2+Entry[[System.Int32, System.Private.CoreLib],[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components]][]
00007ffb1daa73f0  4418250    200740656 System.Int32[]
00007ffb1e1ce920  4417966    212062368 WebApplication2.Pages.test
00000239b59ab0f0   209655    247207184      Free
00007ffb1e456e40       22    251659152 Microsoft.AspNetCore.Components.RenderTree.RenderTreeEdit[]
00007ffb1e458028  4417980    282750720 Microsoft.AspNetCore.Components.RenderFragment
00007ffb1e478cc0  8835967    282750944 System.Collections.Generic.Stack`1[[System.Int32, System.Private.CoreLib]]
00007ffb1e456958  8835969    282751008 Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1[[Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame, Microsoft.AspNetCore.Components]]
00007ffb1e433980  4417984    353438720 Microsoft.AspNetCore.Components.Rendering.ComponentState
00007ffb1e475a28  8835968    424126464 Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder
00007ffb1e433f40  8835973   3207357560 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
Total 53251096 objects
```

**Comment by danroth27** [comment] 2019-04-22 18:05
Please also provide the file name for these components. It sounds like you have a component that recursively renders itself.

**Comment by SteveSandersonMS** [comment] 2019-04-23 09:02
I think Dan is correct that this is simply an infinite recursion. You have a component that renders itself without any limits. This is like having a C# class whose constructor instantiates another copy of itself.

Closing as not a bug, but if you feel we have misdiagnosed this, please post further details. Thanks!

**Closed by SteveSandersonMS** 2019-04-23 09:02 UTC
Labels: area-mvc, feature-Components
