### ISSUE TITLE
Upgrade master branch to netcoreapp3.0 TFM

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3648] opened 2018-10-17 18:26 UTC
_From @natemcmaster on Tuesday, July 3, 2018 3:20:30 PM_

We've already done this in a few places, but we should do it across the board in test projects.

_Copied from original issue: aspnet/Universe#1243_

**Comment by natemcmaster** [comment] 2018-11-30 01:04
Closing as a duplicate of #3754

**Closed by natemcmaster** 2018-11-30 01:04 UTC
Labels: area-infrastructure, task
