### ISSUE TITLE
In .csproj Link to wwwroot folder can not be open by https.

### ISSUE THREAD

**Issue by Honjoy** [aspnet/AspNetCore#14087] opened 2019-09-18 03:14 UTC
```xml
  <ItemGroup>
    <Content Include="..\Base\wwwroot\css\**\*.css" LinkBase="wwwroot\css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\css\**\*.map" LinkBase="wwwroot\css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\css\**\fonts\**" LinkBase="wwwroot\css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\js\**\*.js" LinkBase="wwwroot\js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Base\wwwroot\js\**\*.map" LinkBase="wwwroot\js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

I have file but https://localhost:5001/css/bootstrap/bootstrap.min.css report status 404

**Comment by pranavkm** [comment] 2019-09-18 16:08
/cc @Tratcher @javiercn 

Would static web assets help in this case?

**Comment by javiercn** [comment] 2019-09-18 18:04
@pranavkm No, and this is unsupported by design. When doing `dotnet run` no files get copied around. Using LinkBase won't work here. StaticWebAssets would work if they created an RCL for the assets, but that's kind of a hack. Static web assets doesn't support linked content for the same reason.

@Honjoy  what are you trying to achieve?

Closing this as by design. We can reopen if we determine we are missing a feature.

**Closed by javiercn** 2019-09-18 18:04 UTC
Labels: area-middleware

**Comment by Honjoy** [comment] 2019-09-20 02:15
I reorganize library include .js and .css and have some files write by myself. 
I hope in my case always link they files just like a template.
