### ISSUE TITLE
WebApplicationFactory will not resolve scoped services

### ISSUE THREAD

**Issue by ejsmith** [aspnet/AspNetCore#12079] opened 2019-07-11 01:46 UTC
### Describe the bug
I am using the `WebApplicationFactory` in my integration tests and it will not resolve any scoped dependencies saying that it can't resolve from the root. That makes sense except that this exact same scenario worked before when I was using the older `MvcWebApplicationBuilder` for my integration tests. I narrowed it down and have created a repro that shows that if I create a derived `WebApplicationFactory` and override the `CreateWebHostBuilder` method, but still use the exact same startup class it will work. I am even just calling the exact same `CreateWebHostBuilder` method from the web app and it works. I am not sure what is going on.

### To Reproduce
I have created a GitHub repository with a reproduction of this issue here:
https://github.com/ejsmith/testhost-issue

Here is what the tests look like:
```csharp
    public class HostingTests {
        [Fact]
        public void CanCreateScopedServiceUsingTestHostWithOverridenWebHostBuilder() {
            var factory = new MyAppFactory();
            var client = factory.CreateClient();
            var singleton = factory.Server.Host.Services.GetRequiredService<SingletonService>();
            Assert.NotNull(singleton);
            var transient = factory.Server.Host.Services.GetRequiredService<TransientService>();
            Assert.NotNull(transient);
            var scoped = factory.Server.Host.Services.GetRequiredService<ScopedService>();
            Assert.NotNull(scoped);
        }
        
        [Fact]
        public void CanCreateScopedServiceUsingTestHostWithWebHostBuilderFromWebProject() {
            var factory = new WebApplicationFactory<Startup>();
            var client = factory.CreateClient();
            var singleton = factory.Server.Host.Services.GetRequiredService<SingletonService>();
            Assert.NotNull(singleton);
            var transient = factory.Server.Host.Services.GetRequiredService<TransientService>();
            Assert.NotNull(transient);
            var scoped = factory.Server.Host.Services.GetRequiredService<ScopedService>();
            Assert.NotNull(scoped);
        }
    }

    public class MyAppFactory : WebApplicationFactory<Startup> {
        protected override IWebHostBuilder CreateWebHostBuilder() => 
            Program.CreateWebHostBuilder(new string[0]);
    }
```

The singleton and transient dependencies are resolved, but the scoped one blows up.

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment] 2019-07-11 17:57
Thanks for contacting us, @ejsmith.
@javiercn can we do something here in 3.1?

**Comment by niemyjski** [comment] 2019-07-11 18:30
This is a pretty messed up bug, would be nice to have this fixed in 2.x or even 3.0.

**Comment by niemyjski** [comment] 2019-07-11 18:32
I stepped through this and I don't see any differences in how this is called, The reflection is correct but it breaks it. I also noticed that if I take the test case where it's working and add a call to `Environment.SetEnvironmentVariable` it breaks it too...

**Comment by ejsmith** [comment] 2019-07-11 19:16
So it turns out that this boils down to the environment name that is configured. If you call `UseEnvironment(EnvironmentName.Production)` the scoped service works. But if you set it to UseEnvironment(EnvironmentName.Development)` the scoped service will not resolve saying that it can't resolve from the root container.

**Comment by javiercn** [comment] 2019-07-12 10:54
Hi @ejsmith thanks for reaching out and the detailed report and repro steps.

This behavior doesn't have anything to do with WebApplicationFactory and is simply the expected behavior of WebHost.CreateDefaultBuilder when running under the development environment.

What happens is that WebHost.CreateDefaultBuilder turns on scope validation in the service provider. https://github.com/aspnet/AspNetCore/blob/master/src/DefaultBuilder/src/WebHost.cs#L200

The exception being thrown in this case is correct, in other cases we don't do this validation by default for backward compatibility reasons (we introduced the feature in 2.1 I believe).

In any case, the code in the tests, while it works is not correct. The reason is that scoped services need to be requested within a scope, but that is not something that we check by default, so they end up being created in the root scope (which would make them effectively singletons).

If you need to create a scoped service in your tests (this is likely to perform some initialization, like initializing the database) then you need to request an IServiceScopeFactory and explicitly create a scope as shown below.
```
using (var scope = factory.Server.Host.Services.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
    var scoped = scope.ServiceProvider.GetRequiredService<ScopedService>();
    Assert.NotNull(scoped);
}
```

This is the correct approach to take. 

Hope this clarifies things.

I'm closing this as by design, as this is the expected behavior. Feel free to reach out if you have more questions.

**Closed** 2019-07-12 15:13 UTC
Labels: PRI: 2 - Preferred, area-mvc, bug
