### ISSUE TITLE
Prerendering server components with parameters is not supported

### ISSUE THREAD

**Issue by tstaa** [aspnet/AspNetCore#13721] opened 2019-09-05 16:49 UTC
I'm trying to use the component in my CSHTML view (existing MVC app):
`@(await Html.RenderComponentAsync<NewJobComponent>(RenderMode.ServerPrerendered,  new { Job = Model }))`

I understand why, but what's the alternative in order to pass anything to the component? Since I cannot do the following in my CSHTML file:
`<NewJobComponent Job="Model" />`

**Comment by mkArtakMSFT** [comment] 2019-09-06 16:41
Thanks for contacting us.
We currently have no support for this. We will park this issue in the backlog to collect more feedback from community.

**Comment by Dimexoid** [comment] 2019-09-06 21:25
The only way I've found for now is parsing URL like http://sitename/myparam=123
`@inject NavigationManager navMan;`
..
` protected override void OnParametersSet()
    {        
        var uri = new Uri(navMan.Uri);
        string test = Microsoft.AspNetCore.WebUtilities.QueryHelpers.ParseQuery(uri.Query).TryGetValue("myparam", out var type) ? type.First() : "";
    }`

**Comment by leMicin** [comment] 2019-09-06 23:16
This is a weird decision to me. We have a scenario where we plan to progressively transition our CMS application from MVC to use mostly Razor components. One of our use cases is a FormComponent that our CMS admins can configure with their own questions. When we call the RenderComponentAsync, I expect to have a way to tell my component which FormId I want to render. The majority of our use cases require the functionality of telling the component whatto render.
```
Html.RenderComponentAsync<FromComponent>(RenderMode.ServerPrerendered, new { FormGuid = content.ContentGuid })
```

**Comment by tomRedox** [comment] 2019-09-07 07:37
We have a similar situation to @leMicin:

We're swapping parts of an existing MVC app to Blazor components.   In many cases we have code on an a Razor Page or MVC page that looks like this:

```@(await Html.RenderComponentAsync<SOAllocationOverview>(RenderMode.Server, new {SaleId = Model.SaleId}))```

Where the SaleId was a parameter in the URL of the page.  I'm really grateful to @Dimexoid for the idea for retrieving that value in the component itself, but that limits the re-usability of the components as it is now reliant on existing in a page that has a URL with parameters with certain names.  The original approach seems cleaner to me.

Also, if we were creating components inside a loop on a Razor page we'd want to be able to pass the ID of the list item into the Blazor component.

What's the logic behind removing the option of passing in the model?

**Comment by leMicin** [comment] 2019-09-07 07:56
@tomRedox  They explained it on this issue : #12245 . There was a performance problem with the solution as it was. I can understand why the solution was not working. 

I wonder why the parameters can't be sent to the client with the Document, and when the client connects to the server, it passes the parameters to the server. This will make so the server does not use expensive CPU / Memory until the client successfully connects.

Removing it without offering an alternative will make it pretty much impossible for us to transition projects, which is sad because I was excited for Blazor.

**Comment by tomRedox** [comment] 2019-09-07 08:32
@leMicin ahhh.. thank you, I hadn't seen that.

For our use case where we have a low number of users with a system running on an intranet, I think we're pretty unlikely to encounter the issues mentioned in #12245.

I remember when React started getting traction in the enterprise, a lot of that was due to being able to introduce it into existing codebases.  It seems a real shame to limit that here, it seems like there must be some way to pass the values of the parameters without incurring the pre-rendering issues.

**Comment by mikoskinen** [comment] 2019-09-08 05:54
Ah, losing the option to pass parameters to components is a real shame. As others, we were using Blazor to progressively convert our existing Razor Pages application into a more dynamic experience.

**Comment by edgolub** [comment] 2019-09-10 19:09
I'm trying not to build an SPA, as blazor seems to force me to do. 

This feature would have been great for that purpose.

**Comment by Draphster** [comment] 2019-09-10 21:44
I'll throw my hat in with everyone else in the thread.  I was trying to use Blazor to create a more dynamic experience for my MVC application rather then investing in Angular/React.  That's severely hindered by removing the ability to pass in parameters.  I may be able to over come it with some additional coding on the Blazor component, but it lessens the separation of concerns of MVC and I thought one of the goals of Blazor was to work with existing Microsoft technologies, not forcing them into a new one.  Like @leMicin I was using this for a low usage internal intranet app, and I don't forsee the issues in #12245.

**Comment by tomRedox** [comment] 2019-09-11 07:29
Thinking about it a bit more, one potential answer here is to create an 'mvc wrapper' component for the component you're building.  The wrapper would then be responsible for either extracting values from the page's URL, or could use Blazor's JS Interop to retrieve data from the page and could then pass those values on to the actual Blazor component that does the work.  That would at least keep a reasonable separation of concerns and make testing easier.

**Comment by schmitch** [comment] 2019-09-18 08:00
actually this + the fact that `OnInitializedAsync` is called twice, makes blazor not that useful for many scenarios. I wanted to enhance one of our products with blazor but it's hard to do so, when we either can't support PreRendering or we need to have a performance offset by calling everything twice.

**Comment by tomRedox** [comment] 2019-09-18 09:11
@mkArtakMSFT now this has a milestone set, does that mean this feature will return on 5.0.0-preview1, or just that it's up for consideration at that time?  I'm wondering whether to design components on the assumption that we will ultimately be able to pass values to them via parameters in future?

**Comment by tstaa** [comment] 2019-09-18 16:25
This makes transition from MVC to Blazor very difficult.
And I think it should be considered at least for 3.1 instead of 5.0!

**Comment by mkArtakMSFT** [comment] 2019-09-24 15:56
@tomRedox assuming we will find a good solution here, yes, this will be part of 5.0.

**Comment by DrDave-M** [comment] 2019-09-25 14:01
I'd like to chime in and say I was very surprised to see this error... What is the point of a component that you can't pass a parameter to? If even just an Id value...
` @(await Html.RenderComponentAsync<PplComponent>(RenderMode.ServerPrerendered, new { Id = 1 }))`
I was very excited to use server side blazor to render complex forms and "wizards" in my MVC app, rather than using signalR and typescript. But this kinda stops that idea...

**Comment by tomRedox** [comment] 2019-09-25 14:14
@DrDave-M as I understand it the parameter feature hasn't been removed because it's thought to be unnecessary, it got pulled as part or [removing the facility for stateful pre-rendering](https://github.com/aspnet/AspNetCore/issues/12245#issuecomment-512651528).   

That change was made close to the final release date for Core 3, so I guess there wasn't time to give this further attention at that point.

I've tagged @rynowak into this conversation back on #12245 too.

**Comment by mkArtakMSFT** [comment] 2019-09-25 20:17
It seems there has been a lot of activity on this thread. We're going to try (not a promise) to bring this in 3.1 as part of https://github.com/aspnet/AspNetCore/issues/14433

**Closed by mkArtakMSFT** 2019-09-25 20:17 UTC
Labels: area-blazor, enhancement

**Comment by fireinthemountain** [comment] 2019-10-02 18:09
I was hoping to use Blazor in my applications. Sadly, I would use tutorial examples that use parameters, only to fail. The lack of ability to pass parameters from MVC views or razor pages is a deal killer for my organization.

**Comment by tomRedox** [comment] 2019-10-03 07:21
The code for passing parameters to prerendered server components has now been restored and will reappear in 3.1.  See #14433.

**Comment by ccit-spence** [comment] 2019-10-20 08:52
Should this work with `3.1.100-preview1-014459`?

**Comment by vitalragaz** [comment] 2019-10-20 08:58
Yes, works like a charm with preview1. But you can only phase non complex
objects.

ccit-spence <notifications@github.com> schrieb am So. 20. Okt. 2019 um
10:53:

**Comment by ccit-spence** [comment] 2019-10-21 00:22
I am still getting this using the CLI on a Mac.
`@(await Html.RenderComponentAsync<CommentInput>(RenderMode.ServerPrerendered, new { RelatedId = Model.Data.Id}))`
InvalidOperationException: Prerendering server components with parameters is not supported.

**Comment by mkArtakMSFT** [comment] 2019-10-21 04:26
@ccit-spence what's the SDK you're using? Most probably you've got something wrong in your setup.
If, however, you think you're running into an issue caused by the framework, please file a new issue and provide as much details as possible, so we can try to reproduce it.
