### ISSUE TITLE
Blazor Client-Side: JSRuntime calls from App.razor OnInitializeAsync when renderer started from task continuation causes deadlock

### ISSUE THREAD

**Issue by ApocDev** [aspnet/AspNetCore#11716] opened 2019-06-29 23:56 UTC
When running a task before the usual `CreateHostBuilder().Build().Run()` call in Program main (eg; `Task.CompletedTask.ContinueWith(_ => CreateHostBuilder(args).Build().Run());`) running conditional initialization logic in App.razor (or any other place that runs during initialization and makes a JSRuntime call) will hang the renderer, and seemingly also the browser.

### To Reproduce
1. Using Preview6 of client side
2. Change Program.Main to `Task.CompletedTask.ContinueWith(_ => CreateHostBuilder(args).Build().StartAsync());`
3. Replace App.razor with the following:

```
@using Microsoft.AspNetCore.Components
@if (IsFinishedLoading)
{
  <span>Page was loaded</span>
}
else
{
  <span>Initializing...</span>
}


@functions
{

  [Inject]
  IJSRuntime JS { get; set; }

  bool IsFinishedLoading { get; set; }

  protected override async Task OnInitAsync()
  {
    await JS.InvokeAsync<object>("console.log", "Test message");
    Console.WriteLine("Method invoked");
    IsFinishedLoading = true;
  }

}
```

### Expected behavior
The page should display "Page was loaded" and "Method invoked" should be in the console.

### Extra Info
If you remove the `Task.CompletedTask.ContinueWith(_ => CreateHostBuilder(args).Build().StartAsync());` from Program.Main and start the application as usual, this issue does not exist.

It seems like the InvokeAsync task gets hung somewhere, but I'm not sure how to deal with this issue.

**Comment by mkArtakMSFT** [comment] 2019-07-02 16:36
Thanks for contacting us, @ApocDev.
We're heads down working on finalizing the 3.0 release and will be able to get to this only after that.

**Comment by mkArtakMSFT** [comment] 2019-11-08 17:15
This is a dupe of https://github.com/aspnet/AspNetCore/issues/14340

**Closed by mkArtakMSFT** 2019-11-08 17:15 UTC
Labels: area-blazor, blazor-wasm, investigate
