### ISSUE TITLE
[Blazor] Attempting to navigate to URI with fragment causes Microsoft.AspNetCore.Components.NavigationException server-side

### ISSUE THREAD

**Issue by xperiandri** [aspnet/AspNetCore#14464] opened 2019-09-26 11:37 UTC
### Describe the bug
Attempting to navigate to address with fragment like `https://localhost:44317/product/abc#General-information` in server-side Blazor causes `Microsoft.AspNetCore.Components.NavigationException`

### To Reproduce
1. Using this version of ASP.NET Core 3.0 RTM
2. Create a page with a button that navigates to the same URI but with a fragment
``` C#
protected override void OnInitialized()
{
    var uri = new Uri(navigationManager.Uri);
    var fragment = uri.Fragment;
    if (fragment != "#fragment")
        navigationManager.NavigateTo(GenerateTabLink("#fragment"));
    else
        selectedTab = fragment;
}
private string GenerateTabLink(string tabFragment)
{
    var builder = new UriBuilder(new Uri(navigationManager.Uri, UriKind.RelativeOrAbsolute))
    {
        Fragment = tabFragment
    };
    return builder.ToString();
}
```
3. See error `Microsoft.AspNetCore.Components.NavigationException`

### Expected behavior
Component navigates to the same page with the added fragment

**Comment by xperiandri** [comment] 2019-09-26 11:51
Ah, I got it. `navigationManager.Uri` return URL without fragment. But URL in browser contains a fragment. This way navigation happens to the same URL.

**Comment by mkArtakMSFT** [comment] 2019-09-26 16:46
Thanks for contacting us, @xperiandri.
Can you please share a complete sample app (ideally as a GitHub repo) so that we can investigate it?

**Comment by kmuthukumar23** [comment] 2019-10-03 11:55
Hi @mkArtakMSFT 

I am also facing the same issue when using the Urihelper. 

I have switched to 'Release' mode, then it works perfectly. But i have no idea about how it is worked in 'Release' and not work in 'Debug' mode.

Any thoughts regard this?

**Comment by mkArtakMSFT** [comment] 2019-10-03 21:01
@kmuthukumar23 please provide a minimal repro project, so we can investigate this.

**Comment by kmuthukumar23** [comment] 2019-10-04 13:35
Hi @mkArtakMSFT 

Here is the Sample.

[navIssue.zip](https://github.com/aspnet/AspNetCore/files/3690748/navIssue.zip)

Steps to reproduce:

1. open the project in vs 2019 preview
2. Run it.
3. It will throws the following
![image](https://user-images.githubusercontent.com/31958591/66211424-b32eef00-e6d9-11e9-8fd3-2ed10f38f39a.png)

i have used vs 2019 16.4 preview 1 and .net core 3.0.100

**Comment by mkArtakMSFT** [comment] 2019-10-04 18:08
@javiercn is this something you have context about?

**Comment by javiercn** [comment] 2019-10-07 14:17
@kmuthukumar23 I can't repro this behavior with your repro. I'm using RTM bits, is there any special url you are using?

**Comment by kmuthukumar23** [comment] 2019-10-08 06:06
Hi @javiercn 

I have just set the initial loading URL in 'index.razor' by using 'UriHelper'. In default blazor app, it navigates to 'pages/index.razor'. Now i am override it to navigate to 'pages/counter.razor' by using 'UriHelper' in 'index.razor'.

**Comment by javiercn** [comment] 2019-10-08 07:01
That works for me without issue. I’m using RTM bits

**Comment by kmuthukumar23** [comment] 2019-10-10 04:52
Hi @javiercn 

I have attached video for this. Please check it.

https://drive.google.com/file/d/1-0MhbpapthHneN4GkTP1Br9XWidl38gZ/view?usp=sharing

**Comment by javiercn** [comment] 2019-10-10 10:46
@kmuthukumar23 That exception is expected, that's how the component signal that a redirection needs to happen.

You have first chance exceptions turned on, that's why you are seeing the debugger break on the exception. If you press F5 you'll see that you are correctly redirected to the /counter page and that it gets rendered successfully.

You can configure the debugger to avoid breaking on this exception as follows:
![image](https://user-images.githubusercontent.com/6995051/66562408-79624c00-eb10-11e9-91bf-66dba8251c53.png)

**Comment by javiercn** [comment] 2019-10-10 10:48
@kmuthukumar23 Thanks for the video showcasing your issue.

We've determined that this behavior is by design, follow the instructions above to avoid breaking on this exception type.

We are closing this issue as the behavior is by design and there's no further action to be taken here.

**Closed by javiercn** 2019-10-10 10:48 UTC
Labels: area-blazor, investigate, more-info-needed
