### ISSUE TITLE
Test failure: _4_BuildIncremental

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3881] opened 2018-11-05 13:50 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=39745) with the following error:

```
System.InvalidOperationException : Command dotnet new web --name web --output . --no-restore --debug:ephemeral-hive returned exit code 134

Getting ready...
The template "ASP.NET Core Empty" was created successfully.



```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-11-05 13:51
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-11-05 13:51
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 6 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=39745) on release/2.2 at 1:31:03 PM:
- _7_PublishIncremental
- _2_RestoreIncremental
- _1_Restore
- _8_Exec
- _3_Build
- _6_Publish

**Comment by natemcmaster** [comment] 2018-11-05 16:46
@Eilon @muratg this looks like a legitimate failure in 2.2 tests, but it appears to be a problem with the templating engine. Can we have someone from dotnet/templating take a look?

cc @seancpeters @vijayrkn

**Comment by muratg** [comment] 2018-11-05 17:20
cc @livarcocc FYI:  `dotnet new` failing on its own.

**Comment by Eilon** [comment] 2018-11-06 19:38
@mkArtakMSFT / @ryanbrandenburg - can you dig into this and see if we need to file a bug against the templating engine repo?

**Comment by seancpeters** [comment] 2018-11-09 20:30
This seems like an issue lower down the stack than in dotnet/templating. Exit code 134 on *nix is a SIGABRT, which is often caused by memory allocation / deallocation (calls to malloc() for examples). 

The merge with @JMarkP only happened yesterday, so wouldn't come into play for this error.

**Comment by ryanbrandenburg** [comment] 2018-11-09 20:50
Well, this isn't happening anymore and there's nothing we can do from our end to improve the logging so I'm going to close this out.

**Closed by ryanbrandenburg** 2018-11-09 20:50 UTC
Labels: Branch:release/2.2, test-failure
