### ISSUE TITLE
Server Side Blazor (Without Websocket) App crash bug

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#9875] opened 2019-04-30 22:42 UTC
Using the default Server Side Blazor, with Preview 4 I've found that after clicking several times on the Application's navigation menues suddendly the app stopped working showing in the console:

![Capture](https://user-images.githubusercontent.com/20750172/56997655-eeebe880-6b7e-11e9-9de3-c0c9c0959f1f.JPG)

After trying to duplicate this for some time I've found it's pretty random (some times taking hundreds of clicks to reproduce) so I ended up with this code, that makes the app break pretty fast:

```
@page "/"

@counter

@functions
{
    int counter = 0;

    protected override async Task OnAfterRenderAsync()
    {
        while (true)
        {
            counter++;
            await Task.Delay(50);
            StateHasChanged();
        }

        base.OnAfterRenderAsync();
    }
}

```

Just put this code in the Index page,  and let it run.... it should break before the counter hits 500...
Remember that this **ONLY happens with Websocket disabled**,  for this I had to publish it in my IIS, and websocket support disabled, using Windows 10.  This was reproduced in three different computers.

Please note that this happens in application's real usage too,  sometimes a couple of fast clicks triggers the bug. You don't have to use this extreme statehaschange refresh rate to trigger it.

Regards

**Comment by davidfowl** [comment] 2019-04-30 22:52
Are you running multiple application instances?

**Comment by chrdlx** [comment] 2019-04-30 22:57
No, just one.   I've found too that if I use websocket.... it crashes if I use several browser windows, which is what you call multiple application instances I guess?

So what I've found until now:

Without Websocket my code example fails with just 1 instance,  with Websocket enabled you have to use several instances to make it crash.

Regards

**Comment by chrdlx** [comment] 2019-04-30 22:57
Also, using Websocket, I don't see browser's console errors,  the counter just stops.

**Comment by redowl3** [comment] 2019-05-01 06:31
Is this after publishing to Azure or running locally?

**Comment by chrdlx** [comment] 2019-05-01 12:35
Nothing related to Azure,  it happens in IIS / IIS Express locally in the development machine,  also hosted in a server remotely.

**Comment by chrdlx** [comment] 2019-05-01 12:50
I just tried with the latest build Preview6-011674, exactly the same issue.

**Comment by redowl3** [comment] 2019-05-01 12:52
Weird it's working fine for us locally (on preview4) - we only see this issue on Azure, but thanks to your heads up of turning on websockets that seems to have sorted the Azure issue.

**Comment by chrdlx** [comment] 2019-05-01 12:55
> Weird it's working fine for us locally (on preview4) - we only see this issue on Azure, but thanks to your heads up of turning on websockets that seems to have sorted the Azure issue.

If you're using IIS Express for local tests don't forget that it has websocket support from default... did you try to host it locally in an IIS Server without websocket support?  
 I tried this in 3 different machines, with different OSes, and in all of them happens the same.

**Comment by danroth27** [comment] 2019-05-03 16:55
Closing as a duplicate of #9901.

**Closed by danroth27** 2019-05-03 16:55 UTC
Labels: area-mvc, feature-Components
