### ISSUE TITLE
"Add New Item" of Type "Razor Component" to a Razor Pages App

### ISSUE THREAD

**Issue by mrlife** [aspnet/AspNetCore#8031] opened 2019-02-28 16:58 UTC
### Describe the bug
Per this comment, we should be able to add a Razor Component file to a Razor Pages app that's using ASP.NET Core 3 preview.

https://github.com/aspnet/Docs/issues/10851#issuecomment-461937951

### To Reproduce
1. Create a Razor Pages app
2. Create a "Components" folder in the root
3. Right-click that folder and choose Add -> New Item
4. On the left, choose Web -> ASP.NET
5. There's no option with a name of "Razor Component" or a description that references that

### Expected behavior
In step 5, there would be an option for creating a Razor Component called "Razor Component"

### Screenshots
![screen shot 2019-02-28 at 11 57 05 am](https://user-images.githubusercontent.com/213164/53583672-0a6f4e80-3b50-11e9-92ba-8769615e2794.png)

**Comment by mrlife** [comment] 2019-03-07 15:53
Note that with a Razor Components app in Preview 4, a "Razor Component" item is not listed there either.

**Comment by mrlife** [comment] 2019-03-07 16:00
Note that with a Razor Components app in Preview 3, a "Razor Component" item is not listed there either.

**Comment by danroth27** [comment] 2019-04-02 17:01
Duplicate of #6357

**Closed by danroth27** 2019-04-02 17:01 UTC
Labels: area-mvc, feature-Components
