### ISSUE TITLE
Identity default Pages UI url generation not respecting routing in ASP.NET Core 2.2

### ISSUE THREAD

**Issue by achandlerwhite** [aspnet/AspNetCore#6471] opened 2019-01-08 05:40 UTC
I'm not sure if this is a Pages issue or just an issue in Identity default UI.

I am using ASP.NET Core 2.2 and Identity. I have changed the routing to the "Account" Pages via the following in my `ConfigureServices`:
```
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AddAreaFolderRouteModelConvention("Identity", "/Account", model =>
                    {
                        foreach(var selector in model.Selectors)
                        {
                            selector.AttributeRouteModel.Template =
                                AttributeRouteModel.CombineTemplates("{__tenant__}", selector.AttributeRouteModel.Template);
                        }
                    });
                });
```

The idea is to prefix the Pages routes with a url segment taking a parameter called `__tenant__`. This worked fine in 2.1.

In 2.2 the Identity pages are reachable at these correct route url, however the links and form actions generated within the pages are not using the routes. As a result the none of the link href or form actions work.

I have scaffolded out the pages in both 2.1 and 2.2 and both generate the links similar to:
`<a id="forgot-password" asp-page="./ForgotPassword">Forgot your password?</a>`

In 2.1 the correct href is generated. In 2.2 the result is an href attribute with no value.

Thanks!

**Comment by achandlerwhite** [comment] 2019-01-08 06:00
It appears this is related to #5055

**Comment by mkArtakMSFT** [comment] 2019-01-09 22:51
@javiercn, can you please confirm whether this is caused by the referenced issue and if so, close this in favor to that one? Thanks!

**Comment by javiercn** [comment] 2019-01-28 11:14
@JamesNK This seems like it's the case. So closing this in favor of that one.

**Closed by javiercn** 2019-01-28 11:14 UTC
Labels: area-mvc, investigate
