### ISSUE TITLE
Getting a "FileNotFoundException" when using "InProcess" mode for ANCM

### ISSUE THREAD

**Issue by TheBlueSky** [aspnet/AspNetCore#4507] opened 2018-12-07 15:43 UTC
### Description
I have an application that uses a file, let's call it `file.txt`, which is located in the application root; i.e., sitting next to `Program.cs` and `Startup.cs` files. The application uses this file in a middleware. Everything worked as expected under ASP.NET Core 2.0, 2.1, and 2.2 (I upgraded to 2.2 following [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio) document).

However, when I updated the project file to add `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`, I started getting a "file not found" error when I run the application under IIS Express (haven't tried IIS).

### To Reproduce
Steps to reproduce the behaviour:
1. Create a new "ASP.NET Core Web Application" using Visual Studio and choose "Empty" template.
2. Add a file called "File.txt" to your application root; i.e., next to `Program.cs` and `Startup.cs` files.
3. Modify `Configure()` method in `Startup.cs` file to replace `app.Run()` call with the code snippet below this list.
4. Open the `csproj` file and make sure `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` is present.
5. Make sure IIS Express is the selected option in the Run option in the toolbar.
6. Run the application. You'll get "Could not find file 'C:\Program Files\IIS Express\File.txt'".
7. Remove `AspNetCoreHostingModel`, downgrade to ASP.NET Core 2.1, or run on Kestrel then rebuild and run the application; the issue goes away.

```C#
app.Run(async (context) =>
{
    var text = await File.ReadAllTextAsync("File.txt");
    await context.Response.WriteAsync(text);
});
```

### Expected behaviour
The application should be able to find the file whether it is running under IIS or not, and whether it is running "In Process" or not.

### Additional context
From the Exception message, it seems like the application root directory isn't where the application is. I'm not sure if this is the intended behaviour or not. If this is the case, it seems to me that this is a breaking change that I did not find it documented.

**Comment by Tratcher** [comment] 2018-12-08 02:38
Duplicate of https://github.com/aspnet/AspNetCore/issues/4206

**Closed by Tratcher** 2018-12-08 02:38 UTC
