### ISSUE TITLE
Blazor scoped services are created twice per browser window

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#14903] opened 2019-10-10 20:58 UTC
#A clear and concise description of what the bug is.
When registering a service using `AddScoped(Type, Func<IServiceProvider, object>)` the instance is created twice.

### To Reproduce
1: Create a new ServerSide Blazor app
2: Add a new interface and class

```
public interface IFluxorStore {}
public class FluxorStore : IFluxorStore {}
```

3: Register this in `Startup.ConfigureServices`

```
public void ConfigureServices(IServiceCollection services)
{
	services.AddRazorPages();
	services.AddServerSideBlazor();
	services.AddSingleton<WeatherForecastService>();
	// Add the following line of code
	services.AddScoped(typeof(IFluxorStore), serviceProvider =>
	{
		var result = new FluxorStore();
		System.Diagnostics.Debug.WriteLine("Store created");
		return result;
	});
}
```

4: Inject the dependency in `App.Razor`

```
@inject IFluxorStore Store
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```

### Expected behavior
One instance of FluxorStore should be created per browser window when the app runs.

### Actual
The factory Func is executed twice per browser window.

**Comment by javiercn** [comment] 2019-10-11 10:43
@mrpmorris Thanks for contacting us.

Are you using prerendering? If so, your factory will be created once when the app gets prerendered and another time when the browser connects to the server and starts an interactive session.
* You can confirm this by switching off prerendering on _Host.cshtml

It can also be due to the browser eagerly fetching the page (many browsers do this when you type on the url). Using InPrivate/Incognito mode prevents that from happening.

**Comment by mrpmorris** [comment] 2019-10-13 13:59
Yes, it is the case that pre rendering is causing this. Can it be prevented?

**Comment by javiercn** [comment] 2019-10-14 12:04
@mrpmorris No if you want to keep prerendering your app, but why is it a problem for you?

As I mentioned before, prerendering needs to initialize your app, produce a render and serialize it into HTML, and then tear down the app after the first render.

Then when the client (browser) starts the app, it needs to start the app again so that the user can interact with it.

There is no way around this, but I would like to better understand what your issue is with having the service created twice, as the first one should disappear after the request is sent to the client.

I'm closing the issue as there's no action for us to take here, since this behavior is by design, but please feel free to go into details if you think you have an issue.

**Closed by javiercn** 2019-10-14 12:04 UTC
Labels: area-blazor, more-info-needed

**Comment by mrpmorris** [comment] 2019-10-15 13:31
Starting up the app at a specific page could involve having to call out to other services, which means the number of calls doubles.  The data a split second later might also be different - presumably the user would see old data which then changes to new data?

I understand it's by design, but it seems it would be a better design if the entire bootstrap process for the pre-render is the shared with the app so that this only happens once.

**Comment by Postlagerkarte** [comment] 2019-10-15 21:36
@mrpmorris :  I'm not sure how common your scenario is,  but you can always make use of the IsConnected property to handle cases like this.

**Comment by mrpmorris** [comment] 2019-10-16 06:02
I think this is going to be a common problem, because any app that grabs data from a service and displays it is going to get this double render glitch.

I don't think having to check IsConnected on every screen is the right approach.

**Comment by javiercn** [comment] 2019-10-16 06:57
@mrpmorris That is inherent to the nature of prerendering. It's the same across all SPA frameworks unless you serialize the state from the server into the client.

You can pass in the initial state to the component when you prerender it instead of fetching it from the server to avoid doing a double look up.

Keep in mind that it only happens the first time the customer visits the page (as its when it gets prerendered) and after that there are no double renders.

**Comment by mrpmorris** [comment] 2019-10-17 21:37
@javiecn
I think there is a misunderstanding. The state (ie services etc) doesn't get transferred to the client. It all stays on the server, the client state is only what the server renders.

**Comment by andy-davies** [comment] 2019-11-15 12:40
Just come across this after encountering a similar issue where I was getting different services for the same use. Is this a case of the documentation being wrong?

> In Blazor Server apps, a scoped service registration is scoped to the connection. For this reason, using scoped services is preferred for services that should be scoped to the current user

[https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.0](url)

To me therefore is seems that a scoped service is not scoped to the user and that multiple connections are happening.

**Comment by javiercn** [comment] 2019-11-15 13:27
Hi. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

@andy-davies If you are using prerendering the app will be instantiated twice, once for the prerender path and a separate time after the Browser tries to connect through the signalr connection. If you have follow up questions, please file a separate issue.
