### ISSUE TITLE
In ComponentHub.StartCircuit, prevent creating multiple circuits

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11841] opened 2019-07-03 11:21 UTC
From https://github.com/aspnet/AspNetCore/issues/11791

Currently, a badly-behaved client could call the `ComponentHub.StartCircuit` hub method and create as many circuits as they want from within a single connection. We should check whether the hub instance already has an associated circuit host, and if so, reject this.

Similarly, check the `ConnectCircuit` to verify we're doing the right thing if a bad client calls it multiple times. It looks like it's meant to be allowed to call this even if you're already connected (presumably because the client can't know for sure if a previous reconnect attempt succeeded just a moment ago), but can we more cleanly no-op in this case? Can we have a comment to say what's meant to happen if a client calls this unexpectedly?

**Comment by javiercn** [comment] 2019-07-03 12:14
My PR for connection Id tweaks already addressed this. Feel free to give this to me and I’ll take out the cookie part if necessary.

**Comment by mkArtakMSFT** [comment] 2019-07-17 16:45
Dupe of #12054

**Closed by mkArtakMSFT** 2019-07-17 16:45 UTC
Labels: PRI: 1 - Required, area-blazor, bug
