### ISSUE TITLE
Enable auto recompile of a Razor Class Library during development

### ISSUE THREAD

**Issue by FanrayMedia** [aspnet/AspNetCore#16703] opened 2019-10-31 17:55 UTC
### Is your feature request related to a problem? Please describe.
One of my pain point developing Asp.net Core apps is that the changes to the views inside a Razor Class Library is not automatically picked up. Here are the steps to produce my issue.

1. Use VS2019 and create one WebApp
2. Create a Razor Class Library with a Razor Page, say Page1.cshtml
3. Reference the RCL in the WebApp
4. Ctrl + F5 to launch the WebApp
5. Make a change to Page1.cshtml inside the RCL
6. Refresh the WebApp in your browser, and you will not see the change

### Describe the solution you'd like
Any changes made to a referenced Razor Class Libraries should automatically make the hosting WebApp recompile and let the developer see the change, instead of the developer having to make a change inside the hosting WebApp for the RCL change to be picked up. I can't imagine a RCL author having to recompile the proj himself on every change he/she makes in the RCL to see it in the browser.

### Additional context
I recorded a YouTube video to demo this https://youtu.be/Kyn-6Bt1WF8
Demo repo https://github.com/FanrayMedia/UnboxingNetCore3

**Comment by javiercn** [comment] 2019-11-01 11:19
@FanrayMedia thanks for contacting us.

We'll evaluate your feature request and come back to you. 

@pranavkm Is that something that enabling Runtime compilation would fix?

**Comment by soeleman** [comment] 2019-11-01 12:10
@FanrayMedia you can try using [dotnet-watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch).
From your sample; change the __WebAppRazor.csproj__
![WebAppRazor csproj](https://user-images.githubusercontent.com/309413/68023783-d5b52780-fcda-11e9-98e9-bdd00fc2b01b.png)
and for easier run [dotnet-watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch) add __launchSettings json__
![launchSettings json](https://user-images.githubusercontent.com/309413/68023811-ec5b7e80-fcda-11e9-81d4-f9002c4e70e7.png)

Alternative is using other watcher like [BrowserSync](https://browsersync.io/) or [Westwind.AspnetCore.LiveReload](https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload) from @RickStrahl

**Comment by pranavkm** [comment] 2019-11-01 15:07
@soeleman sounds like a pretty reasonable solution. The fix for VS issue is being tracked as part of this - https://github.com/dotnet/project-system/issues/3163 and it applies to rebuilding the project when VS notices changes to cs, cshtml or razor files in the referenced class library. 

If you specifically care about cshtml files, an alternative to @soeleman's suggestion might be to involve runtime compilation in the dev inner loop. The sample here demonstrates setting it up to perform runtime view compilation in the main app as well as the class library specifically in Debug builds - https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/Startup.cs#L32-L41.

**Comment by javiercn** [comment] 2019-11-01 15:21
Closing this issue as a duplicate of https://github.com/dotnet/project-system/issues/3163 which will be the one tracking the only changes needed and an alternative option has been provided.

**Closed by javiercn** 2019-11-01 15:21 UTC
Labels: area-mvc, duplicate, question

**Comment by FanrayMedia** [comment] 2019-11-01 15:52
@javiercn @soeleman @pranavkm thank you all for your input!  Razor Class Library with Razor Page worked. However, now I have the same issue with a Razor Class Library that has Razor Component. My repo code https://github.com/FanrayMedia/UnboxingNetCore3/blob/master/WebAppRazor/Startup.cs#L42-L58

Here I'm mimicking the sample and adding both Razor Class Libraries in my Startup.cs, one with Razor Page and the other the Razor Component.  The one with Razor Page works, but changes to Razor Component is not able to be picked up.

```c#
#if DEBUG
            if (env.IsDevelopment())
            {
                // list all my class libs I want to monitor
                string[] dirs = { "RazorClassLibRazorPage", "RazorClassLibRazorComponent" };

                builder.AddRazorRuntimeCompilation(options =>
                {
                    // add each to options file providers
                    foreach (var dir in dirs)
                    {
                        var libraryPath = Path.GetFullPath(Path.Combine(env.ContentRootPath, "..", dir));
                        options.FileProviders.Add(new PhysicalFileProvider(libraryPath));
                    }
                });
            }
#endif
```

**Comment by soeleman** [comment] 2019-11-01 23:17
@pranavkm thanks to point out the tracked issue [dotnet/project-system#3163](https://github.com/dotnet/project-system/issues/3163).

@FanrayMedia seem the extensions (_AddRazorRuntimeCompilation_) does not pick-up __.razor__ files.
The suspect is [FileProviderRazorProjectFileSystem.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Razor.RuntimeCompilation/src/FileProviderRazorProjectFileSystem.cs#L73-L78) since this class handle only __.cshtml__ file and did not see on other classes.
[RCL](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio) has mechanism when dealing with razor files (__.cshtml__ and __.razor__) as picture above.
![AssetsOnProject](https://user-images.githubusercontent.com/309413/68061404-4427d300-fd37-11e9-98fa-72ec49d501a5.png)
What we see on VS is the shadow of the file VS tracked. When we edit the file (__.cshtml__ and __.razor__) the VS does not think to 'reload' the project as they only see the file within _main project_.
That why we need 'watcher' either [dotnet-watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.0) or FileProvider to trigger the 'reload'.

**Comment by FanrayMedia** [comment] 2019-11-02 00:58
@soeleman thank you for the explanation, yeah it does look like `FileProviderRazorProjectFileSystem.cs` is handling only **.cshtml**, and it should handle **.razor** as well, is this something planned for next release?  I also tried your pictures above, but so far no luck. 

WebAppRazor.csproj

```xml
<ItemGroup Label="Global-Tool Watch">
    <Watch Include="..\RazorClassLibRazorComponent\**\*.razor" />
</ItemGroup>
```

launchSettings.json
```json
    "WebAppRazor Watch": {
      "commandName": "Executable",
      "executablePath": "dotnet.exe",
      "launchBrowser": true,
      "workingDirectory": "$(ProjectDir)",
      "commandLineArgs": "watch run",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

**Comment by soeleman** [comment] 2019-11-02 05:31
@FanrayMedia 
> is this something planned for next release?

hope so, may be already some where on branches.

Make sure you had [dotnet-watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch) then running on non-debug.

From console:
![dotnet-watch-run](https://user-images.githubusercontent.com/309413/68066570-7869b680-fd6c-11e9-8374-115ef6af041f.png)

From VS:
![dotnet-watch-run-vs](https://user-images.githubusercontent.com/309413/68066577-815a8800-fd6c-11e9-889c-2ac6a20ef01a.png)
Change to 'Watch' then __Ctrl+F5__

Modification of your sample
[UnboxingNetCore3.zip](https://github.com/aspnet/AspNetCore/files/3800165/UnboxingNetCore3.zip)

**Comment by FanrayMedia** [comment] 2019-11-02 12:44
Thank you @soeleman it works now! Although my browser did not launch itself even with
```json
"launchBrowser": true,
"launchUrl": "https://localhost:5001/"
```
is this an [unknown issue](https://github.com/dotnet/cli/issues/8487)?

**Comment by soeleman** [comment] 2019-11-02 19:30
@FanrayMedia 

> Although my browser did not launch itself

Yup, the commandName __Executable__ did not read that property.
but we can use the __cmd__ or other shell to running browser.
![launchSettings-Watch-Chrome](https://user-images.githubusercontent.com/309413/68075988-c66cd180-fde1-11e9-88c8-b9a52113c261.png)

> is this an [unknown issue](https://github.com/dotnet/cli/issues/8487)?

Think so.
