### ISSUE TITLE
Test failure: SuppressScope_False_CreatesNewScope

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3569] opened 2018-10-01 03:21 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=565939&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) with the following error:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Castle.DynamicProxy.ModuleScope.GetFromCache(CacheKey key)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.GetFromCache(CacheKey key)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__20_0()
   at Moq.PexProtector.Invoke(Action action)
   at Moq.Mock`1.InitializeInstance()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock.GetObject()
   at Moq.Mock.get_Object()
   at Moq.Mock`1.get_Object()
   at Moq.Mocks.CreateMocks[T]()+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[TElement](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at Moq.Mock.Of[T]()
   at Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensionsTest.<>c__DisplayClass29_0.<SuppressScope_False_CreatesNewScope>b__0(IServiceProvider s) in /_/test/Microsoft.Extensions.Http.Test/DependencyInjection/HttpClientFactoryServiceCollectionExtensionsTest.cs:line 786
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass3_0.<AddHttpMessageHandler>b__1(HttpMessageHandlerBuilder b) in /_/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs:line 132
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b) in /_/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs:line 194
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass2_0.<Configure>b__0(HttpMessageHandlerBuilder builder) in /_/src/Microsoft.Extensions.Http/Logging/LoggingHttpMessageHandlerBuilderFilter.cs:line 35
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name) in /_/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs:line 176
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1() in /_/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs:line 106
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name) in /_/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs:line 143
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name) in /_/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs:line 124
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass9_0`1.<AddTypedClient>b__0(IServiceProvider s) in /_/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs:line 326
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensionsTest.SuppressScope_False_CreatesNewScope() in /_/test/Microsoft.Extensions.Http.Test/DependencyInjection/HttpClientFactoryServ
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @Eilon (because the bot doesn't know who else to pick)

**Comment by Eilon** [comment] 2018-10-01 04:18
@dougbu / @rynowak - is this a dup of some test failure issue that we already had? This looks quite familiar to me.

**Comment by Eilon** [comment] 2018-10-01 15:54
The bot doesn't ignore things, but it doesn't open new issues for a given repo as long as the issue is already open. Plus, we should keep them open for tracking purposes.

**Comment by rynowak** [comment] 2018-10-01 17:15
Digging into this a little more, I'm not totally certain that this is the same issue. Have we opened an issue on them yet? I think we're seeing a failure mode that others aren't seeing because we're running tests on netcoreapp2.2 and netcoreapp3.0.

This code is invalid no matter what: https://github.com/castleproject/Core/blob/master/src/Castle.Core/Core/Internal/SynchronizedDictionary.cs#L125 A dictionary in .NET is not thread safe for concurrent readers + a single writer.

**Comment by rynowak** [comment] 2018-10-02 17:03
Opened https://github.com/castleproject/Core/issues/410

**Comment by rynowak** [comment] 2018-10-02 22:38
https://github.com/castleproject/Core/issues/410#issuecomment-426412236 FYI

So there's a newer version of Moq we could be using, and the author thinks we've fixed the issue.

**Comment by dougbu** [comment] 2018-10-03 01:51
So, create a feature branch that updates dependencies.props in Universe to Mock the latest, build it on the CI machine -- repeatedly, and see if anything breaks in the first 100 (pick a number) or so test runs?

**Comment by rynowak** [comment] 2018-10-12 20:18
This should be fixed by the Moq update

**Closed by rynowak** 2018-10-12 20:18 UTC
Labels: Branch:2.2, test-failure
