### ISSUE TITLE
InvalidOperationException: Unable to obtain configuration during Jwt Bearer Authentication with TestServer

### ISSUE THREAD

**Issue by smadurange** [aspnet/AspNetCore#7524] opened 2019-02-13 08:17 UTC
I'm using `Microsoft.AspNetCore.TestHost` version 2.2.0 and `Microsoft.NET.Test.Sdk` version 15.9.0. I'm using IdentityServer4 for OAuth2 provider for Jwt Bearer Authentication. The set up is working fine when deployed with real web servers. However, the issue occurs during integration tests using `TestServer`.

I have already registered `HttpMessageHandler` like:

```
private void InitializeServices<TStartup>(IServiceCollection services)
{
      var startupAssembly = typeof(TStartup).GetTypeInfo().Assembly;

      var applicationPartManager = new ApplicationPartManager();
      applicationPartManager.ApplicationParts.Add(new AssemblyPart(startupAssembly));
      applicationPartManager.FeatureProviders.Add(new ControllerFeatureProvider());
      applicationPartManager.FeatureProviders.Add(new ViewComponentFeatureProvider());

      services.AddSingleton(applicationPartManager);

      services.PostConfigure<IdentityServerAuthenticationOptions>(options =>
                                                                        {
                                                                            options.IntrospectionDiscoveryHandler = this.server.CreateHandler();
                                                                            options.IntrospectionBackChannelHandler = this.server.CreateHandler();
                                                                            options.JwtBackChannelHandler = this.server.CreateHandler();
                                                                        });
}
```

Where `this.server` is my test server. However, when I run my integration tests, I get the following error.

```
Result StackTrace:	
at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync() in C:\local\identity\server4\AccessTokenValidation\src\IdentityServer4.AccessTokenValidation\IdentityServerAuthenticationHandler.cs:line 61
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at xxx.ClientControllerTest.CreateNewClientAsync() in xxx.ClientControllerTest.cs:line 167
   at xxx.ClientControllerTest.CreateNewClientTest() in xxx\ControllerTests\ClientControllerTest.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Result Message:	
System.InvalidOperationException : IDX20803: Unable to obtain configuration from: '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'.
---- System.IO.IOException : IDX20804: Unable to retrieve document from: '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'.
-------- System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it
------------ System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it
```

**Comment by Eilon** [comment] 2019-02-13 19:35
@javiercn - do you have a sense of whether this is more of a TestServer thing or more of a Security thing? Just want to know where to route this issue to.

**Comment by javiercn** [comment] 2019-02-13 19:59
@Eilon This is a security/testserver thing. 
Seems like IS and the tested app are on the same app, so the problem is the handler can't normally get to the IS config because it's in memory.

Essentially the handler needs to be setup so that the config can get retrieved from the testserver. Something along the lines of:

```
public class LoopbackHandler : DelegatingHandler { }

var handler = new LoopbackHandler();
builder.ConfigureServices(services => services.ConfigureOptions<OpenIdConnectOptions>(o => {
  o.BackChannelHandler = new HttpClient(handler);
});

handler.InnerHandler = server.CreateHandler();
```

**Comment by smadurange** [comment] 2019-02-14 03:11
@javiercn I tried quite a number of variations of this and still not working. For example:

```
services.PostConfigure<OpenIdConnectOptions>(options =>
{
       var handler = new LoopBackHandler
       {
             InnerHandler = this.server.CreateHandler()
       };
       options.BackchannelHttpHandler = this.server.CreateHandler();
});
```

And,

```
services.PostConfigure<JwtBearerOptions>(o =>
{
      var handler = new LoopBackHandler
      {
            InnerHandler = this.server.CreateHandler()
       };
       o.BackchannelHttpHandler = handler;
});
```

Looks to me like the `ConfigurationManager` is trying to get metadata not from in-memory but through a network call. Am I overriding the wrong handler here?

**Comment by javiercn** [comment] 2019-02-14 08:22
@smadurange I've checked the code a bit. (It was a long time since I last did this).

I believe the only thing you need is the configuration, that you could set yourself statically for the test.
You would set that in the options.

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/ApiAuthorization.IdentityServer/src/Authentication/StaticConfigurationManager.cs

**Comment by smadurange** [comment] 2019-02-15 02:36
@javiercn Appreciate you trying to help. Hope you enjoyed going through the code :). I had tried this earlier and still didn't work. In any case, I gave it another try like below but still did not work.

```
services.PostConfigure<JwtBearerOptions>(o =>
{
       var handler = new LoopBackHandler
       {
              InnerHandler = this.server.CreateHandler()
       };

       using (var reader = new StreamReader("openid-configuration.json"))
       {
            var json = reader.ReadToEnd();

            o.Configuration = OpenIdConnectConfiguration.Create(json);
            o.BackchannelHttpHandler = handler;
       }
});
```
And: 
```
services.PostConfigure<OpenIdConnectOptions>(o =>
{
       var handler = new LoopBackHandler
       {
              InnerHandler = this.server.CreateHandler()
       };

       using (var reader = new StreamReader("openid-configuration.json"))
       {
            var json = reader.ReadToEnd();

            o.Configuration = OpenIdConnectConfiguration.Create(json);
            o.BackchannelHttpHandler = handler;
       }
});
```

I'm starting to wonder if it's because of the location where I'm setting up the options this is happening. Because any of the above attempts doesn't even make a dent in the test execution. I keep getting the exact same error...

I'm doing all this in the `TestFixture` class in `xUnit`. Order of execution is like:

```
var startupAssembly = typeof(TStartup).GetTypeInfo().Assembly;
var contentRoot = Utils.GetProjectPath(startupAssembly);
var webHostBuilder = new WebHostBuilder()
         .UseContentRoot(contentRoot)
         .ConfigureServices(this.InitializeServices<TStartup>)
         .UseEnvironment(this.environment)
         .UseConfiguration(new ConfigurationBuilder()
         .SetBasePath(contentRoot)
         .AddJsonFile($"appsettings.{this.environment}.json")
         .Build())
         .UseStartup(typeof(TStartup));

this.server = new TestServer(webHostBuilder )
            {
                BaseAddress = new Uri("http://localhost:5000")
            };
```

`InitializeServices` method body is:

```
var startupAssembly = typeof(TStartup).GetTypeInfo().Assembly;

var applicationPartManager = new ApplicationPartManager();
applicationPartManager.ApplicationParts.Add(new AssemblyPart(startupAssembly));
applicationPartManager.FeatureProviders.Add(new ControllerFeatureProvider());
applicationPartManager.FeatureProviders.Add(new ViewComponentFeatureProvider());

services.AddSingleton(applicationPartManager);

services.PostConfigure<JwtBearerOptions>(o =>
{
        var handler = new LoopBackHandler
        {
               InnerHandler = this.server.CreateHandler()
        };

        using (var reader = new StreamReader("openid-configuration.json"))
        {
               var json = reader.ReadToEnd();

               o.Configuration = OpenIdConnectConfiguration.Create(json);
               o.BackchannelHttpHandler = handler;
         }
});
```

**Comment by mkArtakMSFT** [comment] 2019-04-17 21:39
@javiercn is there any other suggestion we can provide here? If not, and if this is external let's close this issue, as there are some suggestions in the referenced issue in the `IdentityServer4` repo.

**Comment by javiercn** [comment] 2019-04-22 04:59
No. We can close this.

**Closed by javiercn** 2019-04-22 04:59 UTC
Labels: area-mvc, question
