### ISSUE TITLE
AddRazorRuntimeCompilation does not work with project razor libraries.

### ISSUE THREAD

**Issue by HolyOne** [aspnet/AspNetCore#17125] opened 2019-11-15 07:23 UTC
I use razor runtime compilation in my .net core 3 razor pages project. it works perfectly.
But runtime compilation does not work for pages under my razor libraries.

**Comment by javiercn** [comment] 2019-11-15 16:03
@HolyOne thanks for contacting us.

This issue is a dupe of https://github.com/dotnet/project-system/issues/3163 see https://github.com/aspnet/AspNetCore/issues/16703 for details on how to work around this.

**Closed** 2019-11-15 16:03 UTC
Labels: area-mvc, duplicate, question
