### ISSUE TITLE
@aspnet/signalr-protocol-msgpack NPM production build fails

### ISSUE THREAD

**Issue by StefanKoenigMUC** [aspnet/AspNetCore#6142] opened 2018-12-27 09:19 UTC
### Describe the bug
I'm using SignalR with message pack protocol, if i try to do a productin build of my NPM application, the following error is thrown:

`node_modules/@aspnet/signalr-protocol-msgpack/dist/esm/MessagePackHubProtocol.d.ts(16,5): error TS2416: Property 'parseMessages' in type 'MessagePackHubProtocol' is not assignable to the same property in base type 'IHubProtocol'.
  Type '(input: ArrayBuffer | Buffer, logger: ILogger) => HubMessage[]' is not assignable to type '(input: string | ArrayBuffer, logger: ILogger) => HubMessage[]'.
    Types of parameters 'input' and 'input' are incompatible.
      Type 'string | ArrayBuffer' is not assignable to type 'ArrayBuffer | Buffer'.
        Type 'string' is not assignable to type 'ArrayBuffer | Buffer'.`

### To Reproduce
package.json
 `    "@aspnet/signalr": "^1.1.0",
    "@aspnet/signalr-protocol-msgpack": "^1.1.0",`

### Expected behavior
No compilation error caused by  @aspnet/signalr-protocol-msgpack

Thanks in advance for your help!

**Comment by BrennanConroy** [comment] 2019-01-02 17:40
Dupe of https://github.com/aspnet/AspNetCore/issues/5400

Do you have a more specific repro? I have only been able to see this error with an app in VS, I would like to be able to hit this on the command line to make sure it wont happen again.

**Comment by accesssoftek** [comment] 2019-01-03 20:44
I may confitm that the issue exists
![image](https://user-images.githubusercontent.com/31446448/50660621-81a1bf80-0fb1-11e9-9404-b9559ffbed8d.png)

**Comment by BrennanConroy** [comment] 2019-01-03 20:47
Can you give me your environment details, like npm version etc.

**Comment by accesssoftek** [comment] 2019-01-03 20:49
![image](https://user-images.githubusercontent.com/31446448/50660833-34721d80-0fb2-11e9-9df8-d119948f37f3.png)

**Comment by accesssoftek** [comment] 2019-01-03 21:08
This is my package.config
[package.json.txt](https://github.com/aspnet/AspNetCore/files/2725317/package.json.txt)

**Comment by BrennanConroy** [comment] 2019-01-03 21:10
I have managed to repro it on the command line now, I had to make an angular app, node apps don't care about the "incompatibility".

**Comment by accesssoftek** [comment] 2019-01-03 21:14
Cool!

**Closed** 2019-01-07 19:18 UTC
Labels: area-signalr

**Comment by ChangAlanCL** [comment] 2019-02-27 00:27
I'm running into the same issue, 
angular v6.4.1
signalr v1.1.0
signalr-msgpck v1.1.0

is there a fix for this?

**Comment by BrennanConroy** [comment] 2019-02-27 01:04
Yes, v1.1.2 https://www.npmjs.com/package/@aspnet/signalr/v/1.1.2
