### ISSUE TITLE
German Umlaute not displayed in <a> Tag when using variable at href in Razor Components

### ISSUE THREAD

**Issue by uwefms** [aspnet/AspNetCore#7456] opened 2019-02-11 12:32 UTC
### Describe the bug
When using a var at href instead of a literal string the umlaute (äüöß) in the text to show is not displayed correctly

### To Reproduce
1. Using this version of ASP.NET Core
     3.0.100-preview-010184 [C:\Program Files\dotnet\sdk] in Visual Studio 2019 preview 2.2
2. Run this code 
   - in VS create a Blazor or RC project

   - in MainLayout.cshtml add:  

`@functions
{    
    string cLink = "https://docs.microsoft.com/en-us/aspnet/";
}`

replace
`<a href="https://docs.microsoft.com/en-us/aspnet/" target="_blank" class="ml-md-auto">About</a>`

with
`<a href=@cLink target="_blank" class="ml-md-auto">&auml;bout</a>`

The link reads: `&auml;bout`

### Expected behavior

The link should read: `äbout` 

If you replace the variable with the string in the anchor tag like

`<a href="https://docs.microsoft.com/en-us/aspnet/" target="_blank" class="ml-md-auto">&auml;bout</a>`

it is displaying correctly.

This was working in VS 17 and core 2.1

**Comment by sven5** [comment] 2019-02-11 13:24
A possible solution would be to encapsulate your link text with `MarkupString`

Example
`<a href=@cLink target="_blank" class="ml-md-auto">@(new MarkupString("&auml;bout"))</a>`

**Comment by uwefms** [comment] 2019-02-11 13:53
@sven5 
Thank you - works
    regards
       Uwe

**Comment by mkArtakMSFT** [comment] 2019-02-11 18:58
Thanks for contacting us, @uwefms.
@SteveSandersonMS, do we plan to handle this or the `MarkupString` approach suggested by @sven5 will be the way to go?

**Comment by SteveSandersonMS** [comment] 2019-02-11 19:02
Thanks for reporting this!

This is a known issue in the components compiler, which we plan to fix. Your existing markup looks fine and will work as expected once the issue is fixed. Long term, there won't be a need to use `MarkupString` for this case, though it is a good workaround in the short term.

Closing as duplicate of https://github.com/aspnet/AspNetCore/issues/7147

**Closed by SteveSandersonMS** 2019-02-11 19:02 UTC
Labels: 1 - Ready, PRI: 3 - Optional, area-mvc, feature-Components
