### ISSUE TITLE
ASP CORE 2.2 Web API XML Format not working

### ISSUE THREAD

**Issue by Phylum123** [aspnet/AspNetCore#13682] opened 2019-09-04 18:51 UTC
Hey guys, I wanted one of my controller actions in my core (2.2) web api to be able to reply in XML format as well as JSON. I read many articles online and nothing worked. In particular, the Microsoft DOCS article (https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2).

Following the above article, this is what I did:

1. I added the NUGET package:   `  <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Xml" Version="2.2.0" />`

2. I changed my Startup.cs:

 ```
       // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddMvc(options =>
                {
                    options.RespectBrowserAcceptHeader = true;
                })
               .AddXmlSerializerFormatters()
               .AddJsonOptions(options =>
                {
                    options.SerializerSettings.ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver();
                    options.SerializerSettings.Formatting = Formatting.Indented;
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.None;
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

//Other startup code
```
3. I added the [FormatFilter] attribute to the controller.

Here is the controller action code:
```
       [HttpGet("{hedgeId}")]
        [ProducesResponseType(typeof(Hedge), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> GetHedge(int hedgeId)
        {
            var hedge = await _hedgeRep.GetHedge(hedgeId).ConfigureAwait(false);

            return Ok(new { TestString = "Test", TestInt = 1 });
            //if (hedge != null)
            //    return Ok(hedge);

            //return NotFound();
        }
```

If I try the url with the query parameter "?format=xml" (Accept header is set to: application/xml) I get back a 406 error. If I remove the [FormatFilter] attribute, and try it again, it gives me back the proper answer, but in JSON. 

I am not sure why it is acting this way. Please let me know if you can help.

**Comment by pranavkm** [comment] 2019-09-05 03:19
Could you have a look at MVC"s output logs? Unlike JSON, `XmlSerializer` doesn't universally support serializing all data types. This would translate to a 406 in the response. The output logs should tell you if there's a reason `XmlSerializer` refused to serialize the type. It's usually something innocuous such as not having an empty constructor.

**Comment by Phylum123** [comment] 2019-09-06 17:58
If you look at the code, I tried to serialize a very simple anonymous object:
` return Ok(new { TestString = "Test", TestInt = 1 });`

Also, the actual object I want to serialize does have an empty constructor.

Where would I find these logs?

**Comment by pranavkm** [comment] 2019-09-06 18:08
Your application's logs. If you're in VS, this would be under `Output`:

![image](https://user-images.githubusercontent.com/174281/64450226-836ad800-d096-11e9-8162-fa5d75caeccf.png)

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2 has more details about application logging.

**Comment by Phylum123** [comment] 2019-09-06 18:10
I edited my answer above with the log entry. I thought you meant some kind of special log. Thanks :)

**Comment by pranavkm** [comment] 2019-09-06 19:10
```
warn: Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter[1]
      An error occurred while trying to create an XmlSerializer for the type '<>f__AnonymousType0`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
System.InvalidOperationException: <>f__AnonymousType0`2[System.String,System.Int32] cannot be serialized because it does not have a parameterless constructor.
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.CreateSerializer(Type type)
```

Here's what I get. You'll likely have to use a regular POCO type for serialization to work. Closing this since the behavior is by design.

**Closed by pranavkm** 2019-09-06 19:10 UTC
Labels: area-mvc, more-info-needed

**Comment by Phylum123** [comment] 2019-09-06 19:37
I am trying to use a regular POCO. The anonymous object was for testing. BOTH the anonymous object and the POCO produce the same errors. Please see the class definition below:

I ran it against the object below and have a more detailed error (I updated what we were logging), minus the part where it tells me what is really wrong ;).

Date: 2019-09-06 15:32:27.8011
         Server: L42CND6457J4T 
         Identity: 
         Logger: Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter
             Request URL: https://localhost/api/1/Hedge/GetHedge/618
             Browser: PostmanRuntime/7.16.3
             Message: An error occurred while trying to create an XmlSerializer for the type 'cm_mhedge_api.Data.Generated.Hedge'.
         
EXCEPTION:There was an error reflecting type 'cm_mhedge_api.Data.Generated.Hedge'.
                 XmlSerializerOutputFormatter.GetCachedSerializer => XmlSerializerOutputFormatter.CreateSerializer => LoggerExtensions.FailedToCreateXmlSerializer

```
 public partial class Hedge
    {
        public int HedgeId { get; set; } // HedgeId (Primary key)
        public DateTime? HedgeRunDateTime { get; set; } // HedgeRunDateTime
        public string Name { get; set; } // Name (length: 100)
        public int HedgeBookId { get; set; } // HedgeBookId
        public DateTime QueryDate { get; set; } // QueryDate
        public decimal PartialPrePaymentRate { get; set; } // PartialPrePaymentRate
        public decimal Volatility { get; set; } // Volatility
        public decimal MtgDiscountSpreadOverGoc { get; set; } // MtgDiscountSpreadOverGOC
        public decimal CommitmentProjectionBestRate { get; set; } // CommitmentProjectionBestRate
        public int CommitmentProjectionAmortization { get; set; } // CommitmentProjectionAmortization
        public decimal CommitmentProjection { get; set; } // CommitmentProjection
        public decimal CommitmentProjectionToday { get; set; } // CommitmentProjectionToday
        public decimal CommitmentProjectionRetentionRatio { get; set; } // CommitmentProjectionRetentionRatio
        public string CreatedByUser { get; set; } // CreatedByUser (length: 50)
        public int? BondInfoHeaderId { get; set; } // BondInfoHeaderId
        public DateTime? MarkedAsFinalDate { get; set; } // MarkedAsFinalDate
        public string MarkedAsFinalUser { get; set; } // MarkedAsFinalUser (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child DealValuations where [DealValuation].[HedgeId] point to this entity (FK_DealValuation_Hedge)
        /// </summary>
        public virtual ICollection<DealValuation> DealValuations { get; set; } // DealValuation.FK_DealValuation_Hedge

        /// <summary>
        /// Child ExcludedDeals where [ExcludedDeal].[HedgeId] point to this entity (FK_ExcludedDeal_Hedge)
        /// </summary>
        public virtual ICollection<ExcludedDeal> ExcludedDeals { get; set; } // ExcludedDeal.FK_ExcludedDeal_Hedge

        /// <summary>
        /// Child HedgeRatios where [HedgeRatio].[HedgeId] point to this entity (FK_HedgeRatio_Hedge)
        /// </summary>
        public virtual ICollection<HedgeRatio> HedgeRatios { get; set; } // HedgeRatio.FK_HedgeRatio_Hedge

        /// <summary>
        /// Child HedgeRuns where [HedgeRun].[HedgeId] point to this entity (FK_HedgeRun_Hedge)
        /// </summary>
        public virtual ICollection<HedgeRun> HedgeRuns { get; set; } // HedgeRun.FK_HedgeRun_Hedge

        /// <summary>
        /// Child IncludedDeals where [IncludedDeal].[HedgeId] point to this entity (FK_IncludedDeal_Hedge)
        /// </summary>
        public virtual ICollection<IncludedDeal> IncludedDeals { get; set; } // IncludedDeal.FK_IncludedDeal_Hedge

        /// <summary>
        /// Child LiquidationRates where [LiquidationRate].[HedgeId] point to this entity (FK_LiquidationRate_Hedge)
        /// </summary>
        public virtual ICollection<LiquidationRate> LiquidationRates { get; set; } // LiquidationRate.FK_LiquidationRate_Hedge

        /// <summary>
        /// Child ManualDeals where [ManualDeal].[HedgeId] point to this entity (FK_ManualDeal_Hedge)
        /// </summary>
        public virtual ICollection<ManualDeal> ManualDeals { get; set; } // ManualDeal.FK_ManualDeal_Hedge

        /// <summary>
        /// Child OtherAssets where [OtherAsset].[HedgeId] point to this entity (FK_OtherAsset_Hedge)
        /// </summary>
        public virtual ICollection<OtherAsset> OtherAssets { get; set; } // OtherAsset.FK_OtherAsset_Hedge

        /// <summary>
        /// Child RenewalDistributions where [RenewalDistribution].[HedgeId] point to this entity (FK_RenewalDistribution_Hedge)
        /// </summary>
        public virtual ICollection<RenewalDistribution> RenewalDistributions { get; set; } // RenewalDistribution.FK_RenewalDistribution_Hedge

        /// <summary>
        /// Child Sales where [Sale].[HedgeId] point to this entity (FK_Sale_Hedge)
        /// </summary>
        public virtual ICollection<Sale> Sales { get; set; } // Sale.FK_Sale_Hedge

        /// <summary>
        /// Child YieldCurves where [YieldCurve].[HedgeId] point to this entity (FK_YieldCurve_Hedge)
        /// </summary>
        public virtual ICollection<YieldCurve> YieldCurves { get; set; } // YieldCurve.FK_YieldCurve_Hedge

        // Foreign keys

        /// <summary>
        /// Parent BondInfoHeader pointed by [Hedge].([BondInfoHeaderId]) (FK_Hedge_BondInfoHeader)
        /// </summary>
        public virtual BondInfoHeader BondInfoHeader { get; set; } // FK_Hedge_BondInfoHeader

        /// <summary>
        /// Parent HedgeBook pointed by [Hedge].([HedgeBookId]) (FK_Hedge_HedgeBook)
        /// </summary>
        public virtual HedgeBook HedgeBook { get; set; } // FK_Hedge_HedgeBook

        public Hedge()
        {
            DealValuations = new HashSet<DealValuation>();
            ExcludedDeals = new HashSet<ExcludedDeal>();
            HedgeRatios = new HashSet<HedgeRatio>();
            HedgeRuns = new HashSet<HedgeRun>();
            IncludedDeals = new HashSet<IncludedDeal>();
            LiquidationRates = new HashSet<LiquidationRate>();
            ManualDeals = new HashSet<ManualDeal>();
            OtherAssets = new HashSet<OtherAsset>();
            RenewalDistributions = new HashSet<RenewalDistribution>();
            Sales = new HashSet<Sale>();
            YieldCurves = new HashSet<YieldCurve>();
            InitializePartial();
        }

        partial void InitializePartial();
    }
```

**Comment by Phylum123** [comment] 2019-09-06 19:45
I thought I was getting the stack trace, but it was not complete. The error does specify what is wrong. It is saying that it cannot serialize the ICollections. However, in this microsoft document regarding xml serializers it says that it can serialize them. Is this just an issue with this particular serializer?

https://docs.microsoft.com/en-us/dotnet/standard/serialization/introducing-xml-serialization

**Comment by pranavkm** [comment] 2019-09-06 19:59
According to https://stackoverflow.com/a/12432870, it does not support interface collections. You could try using the DataContractSerializer using `AddXmlDataContractSerializerFormatters`, but I'm not necessarily sure what it's serialization requirements are.
