### ISSUE TITLE
Blazor. Razor runtime compilation not works.

### ISSUE THREAD

**Issue by tauke1** [aspnet/AspNetCore#16915] opened 2019-11-08 07:57 UTC
### Describe the bug
Hello to everyone! As i said in title of this issue, razor runtime compilation not works for Blazor server app. 

### To Reproduce
1) Create Blazor App
2) Install Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation nuget package, version: 3.0.0
3) Add  ```services.AddRazorPages().AddRazorRuntimeCompilation();  ``` to Startup.cs on ConfigureServices function
4) Try to change razor views, the Blazor server will show old version of views, only recompilation of project would help

### Further technical details
- ASP.NET Core 3.0 version
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE: Visual Studio 2019 16.3.6 Enterprise edition

**Comment by javiercn** [comment] 2019-11-08 09:37
@tauke1 thanks for contacting us.

Razor runtime compilation is an MVC feature, not a supported Blazor feature. I'm closing this as it is by design.

**Closed by javiercn** 2019-11-08 09:37 UTC

**Comment by tauke1** [comment] 2019-11-08 09:47
It is so bad, because every fix in blazor page would require project rebuilding, blazor is still raw product
Thanks for the answer!
