### ISSUE TITLE
Implement ClipboardEventArgs

### ISSUE THREAD

**Issue by SnGmng** [aspnet/AspNetCore#17531] opened 2019-12-02 20:41 UTC
### Is your feature request related to a problem? Please describe.
I am trying to get the clipboard data but ClipboardEventArgs is empty/not implemented/not working.

### Describe the solution you'd like
Implement ClipboardEventArgs. The Clipboard api is supported in any major browser so compatibility shouldnt be a problem.

### Additional context
Location:
https://github.com/aspnet/AspNetCore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Components/Web/src/Web/ClipboardEventArgs.cs#L1-L18
ClipboardEvent:
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent

**Comment by pranavkm** [comment] 2019-12-03 01:06
Looks like a duplicate of https://github.com/aspnet/AspNetCore/issues/14133

**Comment by Postlagerkarte** [comment] 2019-12-03 15:31
Please consider a general review how to surface all EventArgs.

In #14792 I asked why DragEventArgs are only surfaced in read-only fashion even though those properties are writable. The answer was that they are writable only for internal purposes.  ( IMHO That is confusing )

Other people have raised issued concerning MouseEventArgs.

Basically, I would expect to be able to do all things with all surfaced EventArgs that I would be able to do in JS including full read and write access.

**Comment by mkArtakMSFT** [comment] 2019-12-03 17:51
Thanks for contacting us, @SnGmng.
As @pranavkm has pointed out, your ask is already being tracked in the referenced issue, so we'll close this issue.

@Postlagerkarte, your ask is somewhat different and we plan to address it as part of https://github.com/aspnet/AspNetCore/issues/17552

**Closed** 2019-12-04 17:25 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, enhancement
