### ISSUE TITLE
Self-closing tags not respected by Razor compiler

### ISSUE THREAD

**Issue by egil** [aspnet/AspNetCore#13793] opened 2019-09-07 09:25 UTC
### Describe the bug
When a self-closing html tag is added to a Razor file, it is rendered without the self-closing part. E.g. `<br />` is rendered as `<br>` by Blazor. Inspecting the generated `g.cs` file, we see that the call to `AddMarkupContent` indeed includes as string without the self-closing part from the source Razor file. 

Example .razor:

```cshtml
<area/><base/><br/><col/><embed/><hr/><img/><input/>
<link/><meta/><param/><source/><track/><wbr/>
```

Generated C#:
```csharp
protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
{
    __builder.AddMarkupContent(0, "<area><base><br><col><embed><hr><img><input>\r\n<link><meta><param><source><track><wbr>");
}
```

### To Reproduce
1. Create a `blazorserver` app using Preview-9
2. Add a self-closing tag to the Index.razor page, e.g. `<br />`
3. Compile and run project
4. See `br` tag in rendered html as `<br>`
5. See generated `obj\Debug\netcoreapp3.0\Razor\Pages\Index.razor.g.cs` contains code where self-closing bits are removed.

### Expected behavior
I expect the razor compiler to not alter the HTML code I write. If I want a self-closing tag like `<br>` I will write it as such, if I want it as `<br />` (xhtml compatible), then I should be allowed to get it.

### Additional context
```text
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by rynowak** [comment] 2019-09-10 16:42
We don't claim that Blazor preserves the original structure of the **text** you write in a document, only that it produces equivalent DOM elements in the browser. Is something functionally broken in this case?

**Comment by egil** [comment] 2019-09-10 16:49
The related bug reported on my testing library shows one case where this causes problems (I will be moving away from an XML based comparing library so this won't be an issue for me going forward), but it will prevent Blazor from producing XML compatible markup, and that might be a problem in other cases.

**Comment by mkArtakMSFT** [comment] 2019-09-11 16:37
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Closed by mkArtakMSFT** 2019-09-11 16:37 UTC
Labels: area-blazor

**Comment by egil** [comment] 2019-09-11 17:32
@mkArtakMSFT that's fair. Care to share what is behind that design decision? I would very much like to understand the framework better. Thanks.

**Comment by rynowak** [comment] 2019-09-11 17:56
The decision is simply that Blazor doesn't care about preserving the original text you typed in. We care about producing semantically equivalent DOM in the browser. `.cshtml`/MVC has these guarantees, and is has overhead in both the cost of building/testing the features and the runtime overhead of having extra bytes to deal with.

Blazor reserves the rights to do optimizations like removing whitespace nodes or minimizing constructs. 

We also based our parser output logic on HTML5 not XHTML. This is intentional on our part because HTML5 is more widely used and where the innovation is. In theory we could try to support multiple markup specs, but we haven't see any reasons why that would be justified.
