### ISSUE TITLE
Build from source fails

### ISSUE THREAD

**Issue by salslab** [aspnet/AspNetCore#6116] opened 2018-12-24 23:41 UTC
Trying to build from source but results in dlls not being found. I am following guidlines at https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md.

### Steps to reproduce the behavior:
I am using Window 10 Pro, latest code from master and Visual Studio 2017 Community.

1. ./eng/scripts/InstallVisualStudio.ps1 -Edition Community
2. git clone --recursive https://github.com/aspnet/AspNetCore
3. .\build.cmd
4. Shows several errors regarding not being able to copy several dlls under SOURCE_CODE_PATH\AspNetCore\src\Servers\IIS\src\AspNetCoreModuleV2\AspNetCore\bin\Debug

I noticed that the bin directory was not present. So I ran the below from Powershell:
1. .\build.ps1 -Native
2. .\build.ps1 -Managed

Building native generated the x64 dlls. After building Managed code the errors related to dlls under x64 were gone. However, the x86 dlls were not generated after building Native and result in errors when building Managed.

### Expected behavior
1. .\build.cmd should build the source without errors.
2. BuildFromSource.md says just run .\build.cmd to build the source. However, it appears that .\build.ps1 -Native needs to be run before .\build.cmd. If this is correct, BuildFromSource.md should be amended to state that first build Native then build Managed.

### Error messages
```
Build FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(
4551,5): error MSB3030: Could not copy the file "C:\data\source\GitHub\AspNetCore\src\Servers\IIS\src\AspNetCoreModuleV
2\AspNetCore\bin\Debug\Win32\aspnetcorev2.dll" because it was not found. [C:\data\source\GitHub\AspNetCore\src\Servers\
IIS\src\Microsoft.AspNetCore.Server.IntegrationTesting.IIS\Microsoft.AspNetCore.Server.IntegrationTesting.IIS.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(
4551,5): error MSB3030: Could not copy the file "C:\data\source\GitHub\AspNetCore\src\Servers\IIS\src\AspNetCoreModuleV
1\AspNetCore\bin\Debug\Win32\aspnetcore.dll" because it was not found. [C:\data\source\GitHub\AspNetCore\src\Servers\II
S\src\Microsoft.AspNetCore.Server.IntegrationTesting.IIS\Microsoft.AspNetCore.Server.IntegrationTesting.IIS.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(
4551,5): error MSB3030: Could not copy the file "C:\data\source\GitHub\AspNetCore\src\Servers\IIS\src\AspNetCoreModuleV
2\OutOfProcessRequestHandler\bin\Debug\x86\aspnetcorev2_outofprocess.dll" because it was not found. [C:\data\source\Git
Hub\AspNetCore\src\Servers\IIS\src\Microsoft.AspNetCore.Server.IntegrationTesting.IIS\Microsoft.AspNetCore.Server.Integ
rationTesting.IIS.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(
4551,5): error MSB3030: Could not copy the file "C:\data\source\GitHub\AspNetCore\src\Servers\IIS\src\AspNetCoreModuleV
2\InProcessRequestHandler\bin\Debug\x86\aspnetcorev2_inprocess.dll" because it was not found. [C:\data\source\GitHub\As
pNetCore\src\Servers\IIS\src\Microsoft.AspNetCore.Server.IIS\Microsoft.AspNetCore.Server.IIS.csproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:01:04.79
msbuild.exe failed with exit code: 1
At C:\Users\sal\.dotnet\buildtools\korebuild\3.0.0-build-20181214.1\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msbuild.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : msbuild.exe failed with exit code: 1
```

**Comment by natemcmaster** [comment] 2018-12-31 18:34
Closing as a duplicate of https://github.com/aspnet/AspNetCore/issues/6076

**Closed by natemcmaster** 2018-12-31 18:34 UTC
