### ISSUE TITLE
Blazor InputSelect does not support the type 'System.Int32'.

### ISSUE THREAD

**Issue by kardokh** [aspnet/AspNetCore#11181] opened 2019-06-13 13:37 UTC
I wanto post data to database the value of dropdown is int when i save show me below error

`blazor.server.js:15 [2019-06-13T13:31:50.629Z] Error: System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputSelect`1[System.Int32] does not support the type 'System.Int32'.
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.TryParseValueFromString(String value, T& result, String& validationErrorMessage)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1.set_CurrentValueAsString(String value)
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.<BuildRenderTree>b__4_0(String __value)
   at Microsoft.AspNetCore.Components.BindMethods.<>c__DisplayClass9_0.<SetValueHandler>b__0(UIEventArgs eventArgs)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Rendering.Renderer.GetErrorHandledTask(Task taskToHandle)`

[screenshot](https://drive.google.com/uc?export=view&id=1Sw1_sH8_-1Q8lsqy8kDMDm-00OX9MfR1)

**Comment by danroth27** [comment] 2019-06-14 16:46
Thanks for reporting this issue! We think this is a duplicate of #9716.

**Closed by danroth27** 2019-06-14 16:46 UTC
Labels: area-blazor

**Comment by koskila** [comment] 2019-09-13 12:19
Sorry to comment on an old thread - but I ran into the same issue with @lpm-nova and @kardokh, fixed it with @SteveSandersonMS's solution, but after updating to preview 9 it's not working for me anymore. Should it? Any tips on how to get around it?

Thanks!

**Comment by dharmaturtle** [comment] 2019-10-11 15:33
@SteveSandersonMS's code works for me on 3.0

**Comment by developersamim** [comment] 2019-10-12 13:05
@SteveSandersonMS this works for me
