### ISSUE TITLE
Session does not work with Redis when the client has HTTP keep-alives disabled

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2395] opened 2018-01-01 20:15 UTC
_From @tcuk on Thursday, November 30, 2017 8:11:17 AM_

Session state does not persist in Redis when the client has HTTP keep-alives *disabled* (i.e. rather than specifying HTTP header *connection: keep-alive*, the client specifies *connection: close*).

OS: Ubuntu 16.04 LTS
ASP.NET Core version: 2.0.3

Startup used to configure session:

```
using System;
using System.Net;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;

namespace Woo.Website
{
	public class Startup
	{
		public Startup(IHostingEnvironment env)
		{
			string hostname = Dns.GetHostName();

			var builder = new ConfigurationBuilder()
				.SetBasePath(env.ContentRootPath)
				.AddJsonFile("appsettings.json")
				.AddEnvironmentVariables();

			Configuration = builder.Build();

			HostingEnvironment = env;
		}

		public IConfigurationRoot Configuration { get; set; }

		public IHostingEnvironment HostingEnvironment { get; set; }

		public void ConfigureServices(IServiceCollection services)
		{
			services.AddMvc();

			services.AddDistributedRedisCache(options =>
			{
				options.Configuration = Configuration["redis:server"] + ":" + Configuration["redis:port"];
				options.InstanceName = Configuration["redis:instance"];
			});
			
			services.AddSession();
		}

		public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			app.UseDeveloperExceptionPage();

			app.UseForwardedHeaders();
			app.UseSession();
			app.UseMvc();
		}
	}
}
```

I discovered this when using nginx as a reverse proxy to Kestral. Using nginx as a reverse proxy it is easy to enable/disable HTTP keep-alives to reproduce the problem. My proxy config for nginx is:

server {
	listen 80;
	
	gzip on;
	gzip_proxied	no-cache no-store private expired auth;
	gzip_types
		text/plain
		text/css
		text/js
		text/xml
		text/javascript
		application/javascript
		application/x-javascript
		application/json
		application/xml
		application/rss+xml
		image/svg+xml;
	gzip_disable "MSIE [1-6]\.";
	gzip_vary on;

	location / {
		proxy_pass			http://aspnet_server;
		proxy_redirect		off;
		proxy_http_version	1.1;
		proxy_buffering		off;
		proxy_cache_bypass	$http_upgrade;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Connection keep-alive;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Host $host;
		proxy_set_header	X-Real-IP $remote_addr;
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header	X-Forwarded-Host $server_name;
		proxy_set_header	X-Forwarded-Proto $scheme;

	}

	location ~ /.well-known {
		alias /etc/letsencrypt/html/.well-known/$1;
		allow all;
	}

	rewrite ^/(.*)/$ /$1 permanent;
}

Changing the line *proxy_set_header Connection keep-alive* to *proxy_set_header Connection close* disables keep-alives and session state stops working.

I was using the latest nginx package for Ubuntu 16.04 LTS and ASP.NET Core 2.0.3 on Ubuntu 16.04 LTS. These instances were run as containers within docker.

_Copied from original issue: aspnet/Session#201_

**Comment by aspnet-hello** [comment] 2018-01-01 20:15
_From @Tratcher on Thursday, November 30, 2017 8:15:54 AM_

There shouldn't be any relation between session and keep-alives. Can you share the application logs for before and after?

**Comment by aspnet-hello** [comment] 2018-01-01 20:15
_From @tcuk on Thursday, November 30, 2017 9:03:30 AM_

To produce these logs I launched ASP.NET core behind my nginx reverse proxy, opened a new incognito browser window and requested the same URL three times via a URL pointing to nginx. I used a single session variable which was a counter being incremented. In the failure case the counter does not persist and remains at 1.

*Working case (Connection = keep-alive):*

```
Running aspnet
[?1h=Hosting environment: Production
Content root path: /dotnetapp
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://remove/  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Woo.Web.Controllers.HomepageController.Index (Woo.Web) with arguments ((n
ull)) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Woo.Web.Controllers.HomepageController.Index (Woo.Web) in 840.0717ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1111.6613ms 200 text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://remove/  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Woo.Web.Controllers.HomepageController.Index (Woo.Web) with arguments ((n
ull)) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Woo.Web.Controllers.HomepageController.Index (Woo.Web) in 4.0174ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7.6ms 200 text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://remove/  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Woo.Web.Controllers.HomepageController.Index (Woo.Web) with arguments ((n
ull)) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Woo.Web.Controllers.HomepageController.Index (Woo.Web) in 2.7991ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5.4859ms 200 text/plain; charset=utf-8
```

*Failure case (Connection = close):*

```
Running aspnet
[?1h=Hosting environment: Production
Content root path: /dotnetapp
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://remove/  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Woo.Web.Controllers.HomepageController.Index (Woo.Web) with arguments ((n
ull)) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Woo.Web.Controllers.HomepageController.Index (Woo.Web) in 881.3667ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Session.SessionMiddleware[10]
      Committing the session was canceled.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1162.6012ms 200 text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://remove/  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Woo.Web.Controllers.HomepageController.Index (Woo.Web) with arguments ((n
ull)) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Woo.Web.Controllers.HomepageController.Index (Woo.Web) in 3.7355ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Session.SessionMiddleware[10]
      Committing the session was canceled.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 6.014ms 200 text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://remove/  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Woo.Web.Controllers.HomepageController.Index (Woo.Web) with arguments ((n
ull)) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Woo.Web.Controllers.HomepageController.Index (Woo.Web) in 11.195ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Session.SessionMiddleware[10]
      Committing the session was canceled.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 12.8115ms 200 text/plain; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
```
     
My test controller:

```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using System;
using System.Collections.Generic;
using System.Text;

namespace Woo.Web.Controllers
{
	[Route("")]
	public class HomepageController : Controller
	{
		private const string CountKey = "Count";

		[Route("")]
		public IActionResult Index()
		{
			var counter = Counter++;
			
			return Content($"I have counted to {counter}. " + DateTime.Now + " / " + HttpContext.Session.Id + " / " + Request.Headers["Connection"]);
		}

		private int Counter
		{
			get
			{
				return HttpContext.Session.GetInt32(CountKey) ?? 1;
			}
			set
			{
				HttpContext.Session.SetInt32(CountKey, value);
			}
		}
	}
}
```

**Comment by aspnet-hello** [comment] 2018-01-01 20:15
_From @Tratcher on Thursday, November 30, 2017 9:33:19 AM_

Ah. The response has a content-length so the client can disconnect as soon as it gets the last byte, which is before the session gets committed. Kestrel's client disconnect notice triggers, which triggers RequestAborted, which prevents the session from being committed.

This appears to be an order of operations bug in Kestrel. The complete request has been received and the complete response has been sent so if the client disconnects then it's out of scope of the request and it should't trigger RequestAborted. I'll move this issue to the Kestrel repo.

Workaround: call session.CommitAsync() when you're done modifying the session.

**Comment by aspnet-hello** [comment] 2018-01-01 20:15
_From @Tratcher on Thursday, November 30, 2017 9:34:25 AM_

This issue was moved to aspnet/KestrelHttpServer#2195

**Comment by aspnet-hello** [comment] 2018-01-01 20:15
_From @Tratcher on Monday, December 4, 2017 9:32:04 PM_

After some discussion we've decided to change both Session and Kestrel. Session will no longer depend on RequestAborted for commits, only it's normal timeout.
https://github.com/aspnet/Session/blob/be6b099f6ce45bc1308f2135dbd1bfe295e20a98/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L117

**Comment by shirhatti** [comment] 2019-01-11 22:52
Dupe of #4767

**Closed by shirhatti** 2019-01-11 22:52 UTC
Labels: area-middleware, feature-Session
