### ISSUE TITLE
Wrong value for ContentRootPath when use absolute path

### ISSUE THREAD

**Issue by philiahe** [aspnet/AspNetCore#9317] opened 2019-04-12 07:40 UTC
### Describe the bug
Wrong value for ContentRootPath when use absolute path。

### To Reproduce
1. Using this version of ASP.NET Core 2.2。

2. Use absolute path to execute 'dotnet /opt/tmp/publish/Core-Test-Api.dll' is wrong。
`Content root path: /root`

3. Run this code 'dotnet Core-Test-Api.dll' is ok。
`Content root path: /opt/tmp/publish`

4. Configuration information in ‘appsettings.json’ is not available。

**Comment by Eilon** [comment] 2019-04-12 17:33
I think the content path (and, in fact, all paths) are based on the Current Working Directory. So, typically, to start a web app, you would first `cd` into the app's root, then run `dotnet MyApp.dll`, or `dotnet bin\debug\MyApp.dll`.

**Comment by anurse** [comment] 2019-04-12 18:03
@Eilon is correct, the content path is the current directory at the time you execute the application. If you want to use a different heuristic, or a fixed well-known value, you can use the [`.UseContentRoot` extension method on `WebHostBuilder`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingabstractionswebhostbuilderextensions.usecontentroot?view=aspnetcore-2.2#Microsoft_AspNetCore_Hosting_HostingAbstractionsWebHostBuilderExtensions_UseContentRoot_Microsoft_AspNetCore_Hosting_IWebHostBuilder_System_String_).

Closing this as the behavior is by design. Feel free to post any further questions you have on this topic!

**Comment by anurse** [comment] 2019-04-12 18:04
Actually, can you clarify your instructions and tell us what your **current directory** is for steps 2 and 3 in your example? If you're in the same directory both times, I believe the content root should be that directory.

**Comment by philiahe** [comment] 2019-04-13 03:56
> I think the content path (and, in fact, all paths) are based on the Current Working Directory. So, typically, to start a web app, you would first `cd` into the app's root, then run `dotnet MyApp.dll`, or `dotnet bin\debug\MyApp.dll`.

I know the right thing to do is to cd into the app's root then run dotnet dll，That's what we do now。
But I don't think that should use the current execution path as `Content root path`， It should be the path of the DLL。

**Comment by anurse** [comment] 2019-04-13 21:26
> It should be the path of the DLL。

That would incorrect when you're in a project scenario. The DLL is in `/myproject/bin/Debug/netcoreapp2.2/myproject.dll` but your content is in `/myproject/wwwroot`

**Comment by anurse** [comment] 2019-05-22 20:37
Closing this as we have no plans to change the default `ContentRootPath`.

**Closed by anurse** 2019-05-22 20:37 UTC
Labels: area-hosting, waiting
