### ISSUE TITLE
Endpoint routing selecting incorrect controller/action after 2.0 -> 2.2 upgrade

### ISSUE THREAD

**Issue by epignosisx** [aspnet/AspNetCore#9195] opened 2019-04-09 04:17 UTC
### Describe the bug
I ran into a scenario while migrating an app from 2.0 to 2.2. Basically a route that used to select a controller under an area, now is selecting a controller in the root `controllers` folder.

Here is a repro:

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication1
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "areaRoute",
                    template: "{area:exists}/{controller=Home}/{action=Index}");

                routes.MapRoute(
                    name: "accountsCatchAll",
                    template: "Accounts/{*path}",
                    defaults: new { area = "Accounts", controller = "Home", action = "Index" });

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

//Imagine this is in /WebApplication1/Controllers/HomeController.cs
namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => Content("Home/Index");
    }
}

namespace WebApplication1.Areas.Accounts.Controllers
{
    //This is in /WebApplication1/Areas/Accounts/Controllers/HomeController.cs
    [Area("Accounts")]
    public class HomeController : Controller
    {
        public IActionResult Index() => Content("Accounts/Home/Index");
    }

    //This is in /WebApplication1/Areas/Accounts/Controllers/OtherController.cs
    [Area("Accounts")]
    public class OtherController : Controller
    {
        public IActionResult Index() => Content("Accounts/Other/Index");
    }
}


```

Before using Endpoing Routing the url `/accounts/forgot-username` would match the "accountsCatchAll" and it would execute the `HomeController` under the "Accounts" area. After switching to endpoint routing the controller being picked up is the `HomeController` in the root controller folder (non-area controllers folder).

The issue goes away when I disable endpoint routing via: 

```cs
services.AddMvc(options =>options.EnableEndpointRouting = false);
```

cc: @JamesNK

**Comment by davidfowl** [comment] 2019-04-09 07:24
This looks patch worthy @rynowak @JamesNK

**Comment by JamesNK** [comment] 2019-04-09 07:53
Are you using the latest version of the 2.2 SDK?

You can find out with: dotnet—info

**Comment by epignosisx** [comment] 2019-04-09 10:59
I'm not running latest, I'm going to get latest and try again. 

Here is the output anyway:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by epignosisx** [comment] 2019-04-09 11:08
Upgraded to latest (2.2.3), but the same behavior remains:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

By the way, nothing special in the csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>

```

**Comment by mkArtakMSFT** [comment] 2019-04-16 22:51
@JamesNK did you already investigate this?

**Comment by JamesNK** [comment] 2019-04-16 23:02
Not yet. I'll try to get to it today or tomorrow

**Comment by JamesNK** [comment] 2019-04-17 23:14
Hi @epignosisx 

I've investigated your issue and I have reproduced what you see: your scenario is broken in 2.2 and it is fixed in 2.2 when endpoint routing is turned off.

I also tested your scenario in 3.0 with endpoint routing and confirmed that it works in the latest source code.

Because the fix in 2.2 is quite simple - turn off endpoint routing - and the issue is already fixed in 3.0, I'm hesitant to patch it in 2.2.

Are you ok with leaving endpoint routing off until you upgrade to 3.0?

**Closed** 2019-04-17 23:21 UTC
Labels: area-mvc, investigate

**Comment by epignosisx** [comment] 2019-04-18 03:21
@JamesNK thanks for looking into this. I was able to work around it by removing the root controller (didn't actually need it).
