### ISSUE TITLE
.NET core 3 route failure with separate projects

### ISSUE THREAD

**Issue by jjxtra** [aspnet/AspNetCore#14952] opened 2019-10-12 17:11 UTC
### Describe the bug
Unable to use routing in when creating host and using controllers from separate projects. When using everything from one project, routes work fine.

### To Reproduce
- See reproducible project with instructions in comment down below.

### Expected behavior
Routes, views, razor, etc. should work regardless of which project the host builder, views and controllers are in (as they do in .NET core 2.2).

**Comment by davidfowl** [comment] 2019-10-12 18:11
Can you provide a running project?

**Comment by jjxtra** [comment] 2019-10-12 18:33
Working on it

**Comment by jjxtra** [comment] 2019-10-12 20:20
For some reason, .net core 2 can find controllers in other assemblies. This seems to have broken in .net core 3. For now my hacky work-around is this:

```cs
IMvcBuilder mvcBuilder = services.AddMvc((options) =>
{
    options.EnableEndpointRouting = true;
    options.ModelBinderProviders.Insert(0, new IPBanProExtensionMethods.XmlCDataBinderProvider());
});
Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
foreach (Assembly assembly in assemblies)
{
    try
    {
        if (assembly.GetTypes().Any(t => t.IsSubclassOf(typeof(Controller))))
        {
            mvcBuilder.AddApplicationPart(assembly);
        }
    }
    catch
    {
        // bugs in unit test framework throw exceptions for weird assemblies like intellitrace
    }
}
mvcBuilder.SetCompatibilityVersion(CompatibilityVersion.Latest).AddJsonOptions(options =>
{
    options.JsonSerializerOptions.IgnoreNullValues = true;
});
```

**Comment by jjxtra** [comment] 2019-10-12 21:29
With this solution unfortunately now my razor views cannot find any dlls, including system etc, even with preserve compilation context set in the csproj...

**Comment by davidfowl** [comment] 2019-10-12 22:05
Still waiting for a repro.

**Comment by jjxtra** [comment] 2019-10-12 22:32
Still trying to strip my very large project down into the smallest reproducible case, Will post back if I can get it.

**Comment by jjxtra** [comment] 2019-10-13 04:40
I can reproduce it on my machine here regularly but not able as of yet to upload to a repo. Is it possible to do a screen share?

**Comment by davidfowl** [comment] 2019-10-13 04:48
Did you try to reproduce it in a new project?

**Comment by jjxtra** [comment] 2019-10-13 05:00
Yes, so far it can find the controller in a different assembly but I have not tried razor yet. Copying the code over to my project and suddenly I get 404 errors with the same controller. Very bizzare.
```cs
public static async Task Main(string[] args)
        {
            using (var host = CreateHostBuilder(args).Build())
            {
                await host.RunAsync();
            }
        }

        public static IHostBuilder CreateHostBuilder(params string[] args)
        {
            return Host.CreateDefaultBuilder(args).ConfigureLogging((logBuilder) =>
            {
                logBuilder.AddConsole().SetMinimumLevel(LogLevel.Trace);
            })
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.Configure((ctx, app) =>
                {
                    if (ctx.HostingEnvironment.IsDevelopment())
                    {
                        app.UseDeveloperExceptionPage();
                    }

                    app.UseAuthorization();
                    app.UseRouting();
                    app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapRazorPages();
                        endpoints.MapControllers();
                        endpoints.MapControllerRoute("default", "/{action}/{id?}", new { action = "Index", controller = "WeatherForecast" });
                    });
                })
                .ConfigureServices((serviceCollection) =>
                {
                    serviceCollection.AddAuthorization();
                    serviceCollection.AddRazorPages();
                })
                .ConfigureAppConfiguration((ctx, configBuilder) =>
                {
                    configBuilder.Build();
                });
            });
        }
```

**Comment by jjxtra** [comment] 2019-10-13 05:02
In my project, I hit same controller Index method, get this errors:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
dbug: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
      Wildcard detected, all requests with hosts will be allowed.
trce: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[2]
      All hosts are allowed.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[4]
      Initializing Razor view compiler with no compiled views.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
      No candidates found for the request path '/'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
      Request did not match any endpoints
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLQFJ9TFKQ6A" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 27.218ms 404
```

**Comment by jjxtra** [comment] 2019-10-13 14:19
I have a repro project. It is attached. Nice and small.

Instructions:

- Load NetCore3RouteTestFail.sln
- Note the controller is in a separate project (Controllers)
- Set NetCore3RouteTestFail.csproj as start up project
- Run and visit http://localhost:5000/WeatherForecast
- You should see json
- Stop the running console app, leave browser open. Now uncomment line 21 and comment out line 22 in Program.cs in the NetCore3RouteTestFail project.
- Run again. Refresh the browser using ctrl-F5 to bypass any cache. Notice the 404 error.
- The method to build and run the host has been copied exactly into a separate project using line 21.
- The unit test project has the same symtom. You can run tests and they pass. Then uncomment line 22 and comment out line 23 in UnitTest.cs and run tests again. They fail with a 404.

[NetCore3RouteTestFail.zip](https://github.com/aspnet/AspNetCore/files/3721841/NetCore3RouteTestFail.zip)

**Comment by soeleman** [comment] 2019-10-14 08:38
Try add __UseSetting__ on _CreateHostBuilder_ function.
![CreateHostBuilder](https://user-images.githubusercontent.com/309413/66738178-136f1f00-ee98-11e9-87d6-ad5c24ba94cb.png)

On _Program.Main_ we pass __AssemblyName__.
![ProgramMain](https://user-images.githubusercontent.com/309413/66738287-47e2db00-ee98-11e9-959f-8884548f7648.png)

And to make easy lunch the app, you can modify __launchSettings.json__ (in _Properties_ folder on project _NetCore3RouteTestFail_).
![launchSettings_json](https://user-images.githubusercontent.com/309413/66738342-71036b80-ee98-11e9-9aaf-8240b10031fd.png)

**Comment by javiercn** [comment] 2019-10-14 11:21
@jjxtra Thanks for contacting us and thanks for the repro.

I've looked at the project you sent us and I believe the reason you are not finding the controllers when using HostCreator is because it doesn't have a reference to the Controllers project.

The way discovery works in MVC is thought metadata stamped into the assembly at build time. When you try to start the host it looks for an assembly with the application name to find the assembly level attributes that tell it which assemblies to use for discovering controllers and other MVC primitives.

@soeleman answer will probably help here, as setting the application name should fix this issue. That said, if you are doing this for testing purposes I would highly recommend using https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0 instead.

Let us know if that fixes your issue.

**Comment by chassq** [comment] 2019-10-14 12:32
Maybe this is related or not but if one tries to put a Page into an RCL the page cannot be routed too with the default startup.cs.

**Comment by javiercn** [comment] 2019-10-14 13:59
@chassq I don't think your issue is related.

If you think you've found an issue open a separate issue describing your scenario so that we can track it.

**Comment by jjxtra** [comment] 2019-10-14 14:04
So has this changed from net core 2.2? I had the same pattern in 2.2 and it worked fine, no extra stuff needed.

**Comment by javiercn** [comment] 2019-10-14 14:16
@jjxtra This might have been a change in hosting as a result of the move to generic host.

@Tratcher Did we change something in how we set the app name from 2.2 to 3.0 with regards to UseStartup?

**Comment by Tratcher** [comment] 2019-10-14 15:23
Not intentionally, but there may be a subtle ordering difference or similar.

**Comment by jjxtra** [comment] 2019-10-14 16:10
I don't know if it helps, but the legacy web host builder also has an identical problem. It's possible that it and the new host builder share the same common code now.

**Comment by mkArtakMSFT** [comment] 2019-10-14 16:52
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by jjxtra** [comment] 2019-10-14 17:42
I will attempt the suggested fix this evening and post back

**Comment by jjxtra** [comment] 2019-10-15 01:50
This worked for the regular project, unfortunately the unit test project still fails

**Comment by jjxtra** [comment] 2019-10-15 02:01
One thing that would solve all of this is being able to pass the System.Type of the controller to handle a request instead of a string. Is this possible?

**Comment by jjxtra** [comment] 2019-10-15 02:43
I can add application part for all assembly with typeof(Controller) and that allows api controllers to be found, but anything with razor still gives this, even with these project settings:

```
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
<PreserveCompilationReferences>true</PreserveCompilationReferences>
<PreserveCompilationContext>true</PreserveCompilationContext>
```

![image](https://user-images.githubusercontent.com/1271832/66795876-2519ec00-eec3-11e9-9f7e-0e8e687c43f2.png)

**Comment by javiercn** [comment] 2019-10-15 06:47
I’ll take another look

**Comment by javiercn** [comment] 2019-10-15 11:12
@jjxtra With the repro you provided I did the following:
* Add a project reference from HostCreator to controllers
* Change the test as follows:
  ```csharp
  var host = HostCreator.HostBuilder.CreateHostBuilder().Build(); // broken
  //var host = NetCore3RouteTestFail.Program.CreateHostBuilder().Build(); // works
  ```
* With that, starting up host creator (you need to add the line below) I can get to the API without problems.
  * `CreateHostBuilder(args).Build().Start();` (This needs to be added to program main).
  * ![image](https://user-images.githubusercontent.com/6995051/66826115-8e6c2000-ef00-11e9-9a9c-624da9d62351.png)

The other issue that you are seeing is likely caused by using a different app name, as it results in loading the wrong dependencycontext which is what razor uses to perform recompilation.

My original recommendation still stands, if you are doing this for testing purposes use WebApplicationFactory as it handles all these concerns.

I'm closing this issue as there's no more action to be taken here.

**Closed by javiercn** 2019-10-15 11:12 UTC
Labels: area-mvc, question

**Comment by jjxtra** [comment] 2019-10-15 13:26
Thanks to everyone who looked into this issue and spent time from their busy days trying to help.

I am however very disappointed and disheartened as I feel this is a pretty significant regression from .NET core 2.2. With .NET core 2.2 everything just worked with web host builder in tests and with my large projects including razor views. With .NET core 3, behavior has changed for the worse. I have literally hundreds of failing unit tests now that spin up applications and make http requests and get 404 errors. So now I (and probably many others) are left with two options. Stay on .NET core 2.2 or rewrite all the tests to use web application factory. Not to mention that my larger projects still get 404 errors even with the usesetting and application name.

Most likely I will stay on .NET core 2.2 until this is resolved, even for new projects. If anyone from Microsoft wants to screen share and see what I am dealing with in my large project I am very happy to do so.

**Comment by jjxtra** [comment] 2019-10-15 13:54
I was able to hack around the issue by doing the following. Posting it here for anyone else who comes accross this issue in .NET core 3. This took about a week to figure out and some late nights so I really hope it saves people the headache I went through. My hunch is that something like this is being done behind the scenes in .NET core 2.2, and the code got deleted or broken in the .NET core 3.0 initiative.

In .NET core 3.0, if you get 404 errors from controllers and/or get razor views complaining about common references like Microsoft.* or System.* and you KNOW you've setup your routes properly and the routes work in .NET core 2.2 and you've added preserve compilation context to your csproj, you can do this in your setup:

```cs
/// <summary>
/// Get all assemblies with at least one class matching a type
/// </summary>
/// <param name="type">Type to match</param>
/// <returns>Assemblies with that type</returns>
public static IEnumerable<Assembly> GetAssembliesWithType(Type type)
{
    foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
    {
        Type[] types;
        try
        {
            types = assembly.GetTypes();
        }
        catch
        {
            // some assemblys throw in unit tests in VS 2019, bug in MSFT...
            continue;
        }
        if (types.Any(t => t.IsSubclassOf(type)))
        {
            yield return assembly;
        }
    }
}

private void NetCore3ApplicationPartHack(IMvcBuilder mvc)
{
    Assembly referencedAssembly = Assembly.GetExecutingAssembly();
    mvc.ConfigureApplicationPartManager((applicationPartManager) =>
    {
        ApplicationPartFactory partFactory = ApplicationPartFactory.GetApplicationPartFactory(referencedAssembly);
        foreach (var part in partFactory.GetApplicationParts(referencedAssembly))
        {
            applicationPartManager.ApplicationParts.Add(part);
        }
        IReadOnlyList<Assembly> relatedAssemblies = RelatedAssemblyAttribute.GetRelatedAssemblies(referencedAssembly, throwOnError: true);
        foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            partFactory = ApplicationPartFactory.GetApplicationPartFactory(assembly);
            foreach (var part in partFactory.GetApplicationParts(assembly))
            {
                applicationPartManager.ApplicationParts.Add(part);
            }
        }
    });
}

private void ConfigureServices(IServiceCollection services)
{
    IMvcBuilder mvcBuilder = services.AddRazorPages().AddRazorRuntimeCompilation(options =>
    {
        // add any file providers for razor views here
    }).AddMvcOptions((options) => options.EnableEndpointRouting = true); // set to false if you want 
to stick with old style mvc routes
    foreach (Assembly a in GetAssembliesWithType(typeof(Controller)))
    {
        mvcBuilder.AddApplicationPart(a);
    }
}
```

**Comment by alextof** [comment] 2019-11-21 19:00
@jjxtra , I'm trying to understand your resolution and trying to apply it to #15046 to be able to find a fix, but I still don't see how to relate them. Could you please give a bit more insights on how you was able to solve the issue?

**Comment by guibirow** [comment] 2019-11-28 18:06
I can confirm the `.UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).Assembly.GetName().Name)` works like a charm.

Sample code:
```
WebHost.CreateDefaultBuilder()
                .UseStartup<TestStartup>()
                .UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).Assembly.GetName().Name)
                .Build()
```

**Comment by jjxtra** [comment] 2019-11-28 18:16
The only issue remaining still is that razor does not work in unit tests, something to do with testhost I think, but not sure...
