### ISSUE TITLE
Localization — Generic Class and Localization not working

### ISSUE THREAD

**Issue by ghost** [aspnet/AspNetCore#3422] opened 2018-08-13 07:29 UTC
May be a documentation issue, but I try here:

For non generic class, Localization works as expected. But with generic classes, seems that localization does not work.
 
I tried to localize Identities classes, like AppIdentityUser<TKey>, I tried something like
- `AppIdentityUser.it.resx`
- `AppIdentityUser<T>.it.resx`
- ``AppIdentityUser`1.it.resx`` (name get by reflection)

But nothing works. I cannot get the properties translated.

**Comment by hishamco** [comment] 2018-08-14 15:58
@ckams can you provide a minimal repo to reproduce the issue

**Comment by ckams** [comment] 2018-08-20 13:44
@hishamco 
Not enough time, but you can easily try with MS samples on github.

**Comment by Eilon** [comment] 2018-08-21 21:28
Hi. We're closing this issue because we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by ckams** [comment] 2018-08-22 14:53
Here a repo:

- https://github.com/ckams/Buggy_GENERIC_Localization

This file is not translated:
- https://github.com/ckams/Buggy_GENERIC_Localization/blob/master/Buggy_GENERIC_Localization/ViewModels/Account/RegisterViewModel.cs

**Comment by hishamco** [comment] 2018-08-22 17:43
Downloading & checking your sample ...

**Comment by hishamco** [comment] 2018-08-22 18:04
At the first glance I didn't find a localize `RegisterViewModel.resx` in `Resources\ViewModel\Account` folder, seems that causes the issue .. I will try to add it and check your sample

**Comment by ckams** [comment] 2018-08-22 18:54
> At the first glance I didn't find a localize RegisterViewModel.resx in Resources\ViewModels\Account folder, seems that causes the issue .. I will try to add it and check your sample

I do not think so. The location is related to the namespace.

**Comment by hishamco** [comment] 2018-08-22 19:06
Yep, but there's no resource file related to the class, but seems the issue more than that I think I will start debugging the localization source ..

**Comment by hishamco** [comment] 2018-08-22 21:38
@Eilon I can confirm there's a bug, unless there's a special convention for naming resources for generic classes

But this is a first time I see someone trying to localize a generic class, nothing but still i'm not sure if we really need to localize such classes because `T` is a generic type

A workaround for this is creating a `RegisterViewModel` that inherits from `RegisterViewModel<T>` as the following:
```csharp
    public class RegisterViewModel : RegisterViewModel<String>
    {

    }
```
@ckams this should work as usual ...

**Comment by ckams** [comment] 2018-08-23 06:36
> Yep, but there's no resource file related to the class, but seems the issue more than that I think I will start debugging the localization source ..

@hishamco Are you sure? [What that file](https://github.com/ckams/Buggy_GENERIC_Localization/blob/master/Buggy_GENERIC_Localization/Resources/StarterWeb/ViewModels/Account/RegisterViewModel.fr.resx)?

> But this is a first time I see someone trying to localize a generic class, nothing but still i'm not sure if we really need to localize such classes because T is a generic type

Well, [if you want to localize Identity classes](https://github.com/aspnet/Identity), you will soon see that we really need to localize such classes…

And, I do not want to use empty class as wrapper, **and pollute my projects**, just because ASP.NET Core MVC, is **once again**, buggy… But thanks @hishamco for all your engagement/serious. You are more professional than MS guys…

@Eilon you wrote:
> Hi. We're closing this issue because we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

This is not the first time I see this "kind of reply", whereas other are able—without any difficulties—to reproduce an issue… I do not know how you MS guys work, but seems not very serious/reassuring…

If you do not want to spend time on issue, do not lie, but rather, write—even with a "saved reply"
- "We do not want to spend time in your issue…".

Finally, does anybody use ASP.NET Core MVC??? I often—not only me—find all kind of problems/limitations, **on basic usages**, as if it was a beta project…

**Comment by hishamco** [comment] 2018-08-23 08:27
> Are you sure? What that file?

Strange!! seems I didn't notice that or got confused with your another project

> Well, if you want to localize Identity classes, you will soon see that we really need to localize such classes…

Yep!!

@ckams ASP.NET team are working hard to release 2.2, if there's no reply that doesn't mean that you're ignored, believe it or not I filed some suggestions before year or so without reply but they keep there eyes

Anyhow, I will try to look into your repo again & come back to you ..

**Comment by hishamco** [comment] 2018-08-23 09:33
@ckams are you sure the data annotations localization works in your repo?!! It didn't work on my end at all, even in `en-US` culture

**Comment by hishamco** [comment] 2018-08-23 12:03
Finally after debugging the localization source code, and while you are using `RegisterViewModel<String>` the generated class will have a fully qualified name for `String`, so the resource file should be named to **RegisterViewModel\`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].fr.resx** I knew the name is weird but this how the generic class will be named, for that you need to provide n resource files per `T`

FYI I used `Localization.StarterWeb` sample that the one you provided because the data annotation isn't working at all

**Comment by ckams** [comment] 2018-08-23 16:55
As I stated in my first message:
> May be a documentation issue, but I try here:

So:
1. Nowhere we can find this in the Doc.
2. Obviously, this file name:
- ```RegisterViewModel`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].fr.resx```

is not a name usable normally, or MS guys are just crazy, or more likely, **have missed this…**

Anyway, Thanks again!

**Comment by Eilon** [comment] 2018-08-23 17:04
@ckams this indeed looks like a scenario we might not have considered before. We will take a further look at this and see what we can come up with.

**Comment by hishamco** [comment] 2018-08-23 18:07
But the one you tried is `RegisterViewModel`1.fr.resx` :smile, @Elion IMHO we can file another issue for resource naming cleanup for localize generic classes

**Comment by hishamco** [comment] 2018-08-30 17:15
FYI I added an extra property named `UseGenericResources` on `LocalizationOptions` to make it easier to control the resource name for generic class.  I described everything in details in my blog post [Localization & Generics](http://www.hishambinateya.com/localization-and-generics)

**Comment by mkArtakMSFT** [comment] 2018-11-07 23:37
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Closed by mkArtakMSFT** 2018-11-07 23:37 UTC
Labels: area-mvc
