### ISSUE TITLE
SignalR hub silently disconnects if a payload containing loop references is sent

### ISSUE THREAD

**Issue by fschlaef** [aspnet/AspNetCore#18144] opened 2020-01-06 13:03 UTC
### Describe the bug

When upgrading to .Net Core 3.0, a part of the migration guide (https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30) was to change from `Newtonsoft.Json` to `Json.NET`.

The problem with the latter is that Reference Loop Handling will not be supported until .Net 5.0 : https://github.com/dotnet/corefx/issues/38579 

If you send a payload with a looped reference to a SignalR Hub (I tested this with WebSockets and LongPolling) it will immediately and silently disconnect with the message `Information: Connection disconnected`

This is probably related to #16606

Detailed log :

```
Trace: (WebSockets transport) socket closed.
Debug: HttpConnection.stopConnection(undefined) called while in state Connected.
Information: Connection disconnected.
Debug: HubConnection.connectionClosed(undefined) called while in state Connected.
```

My only solution is to fallback to Newtonsoft.

Config before :
``` C#
services.AddSignalR().AddJsonProtocol(options =>
            {
                options.PayloadSerializerOptions = new JsonSerializerOptions()
                {
                    PropertyNamingPolicy = null
                };
            });
```

Config after :
```csharp
services.AddSignalR().AddNewtonsoftJsonProtocol(options =>
            {
                options.PayloadSerializerSettings.ContractResolver = new UpperCamelCaseContractResolver();
                options.PayloadSerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                options.PayloadSerializerSettings.DateFormatString = "yyyy-MM-ddTHH:mmZ";
                options.PayloadSerializerSettings.Culture = cultureInfo;
            });
```

### Further technical details
- ASP.NET Core version : 3.1
- Windows 10, VS 16.5.0 Preview 1.0

**Comment by BrennanConroy** [comment] 2020-01-06 16:22
> My only solution is to fallback to Newtonsoft.

That's all you can do if you want to use reference loops, until System.Text.Json adds support for it in the future.

As far as silently failing, it does log at the Debug level currently, but we're considering changing that, see https://github.com/aspnet/AspNetCore/issues/13651 for discussion/tracking.

**Comment by halter73** [comment] 2020-01-06 18:43
Looks like this is a duplicate of #13651. Once dotnet/corefx#38579 is resolved, reference loops should be allowable via JsonHubProtocolOptions.PayloadSerializerOptions.

**Closed** 2020-01-06 22:13 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
