### ISSUE TITLE
Edit and Continue failed in ASP.NET Core web project

### ISSUE THREAD

**Issue by tmat** [aspnet/AspNetCore#7390] opened 2019-02-08 18:00 UTC
### Describe the bug
Error CS8055: "Cannot emit debug information for a source text without encoding." is reported when editing ASP.NET Core web project while debugging.

Reported as VS feedback: https://developercommunity.visualstudio.com/content/problem/414645/edit-and-continue-not-working-with-aspnet.html.
Internal bug [736856](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/736856).

### To Reproduce
1. Create a C# ASP.NET Core Web Application (MVC). ASP.NET Core 3.0.
2. Set a break point in `Index` method in `HomeController.cs`.

```C#
public IActionResult Index()
{
   // int i = 1;
   return View();
}
```

3. F5 (The platform is AnyCPU).
4. Uncomment `// int i = 1;`
5. F10

### Expected
ENC is successful.

### Actual
ENC failed with error CS8055: "Cannot emit debug information for a source text without encoding."

**Comment by camainc** [comment] 2019-02-08 20:59
I added a comment line inside a method. There are no compile errors, but I get  a dialog that states "Edits were made which cannot be compiled. Execution cannot continue until the compile errors are fixed."

When I click the "Edit"  button on the dialog then I see the error described above, CS8055.

**Comment by mkArtakMSFT** [comment] 2019-02-10 00:14
Thanks for contacting us, @tmat.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by davidfowl** [comment] 2019-02-12 00:42
This is something that @BillHiebert should look at not @NTaylorMullen

**Comment by DamianEdwards** [comment] 2019-02-12 00:42
I'm pretty sure we don't support Edit and Continue in .NET Core projects.

**Comment by BillHiebert** [comment] 2019-02-12 16:32
@DamianEdwards I tried a .NET Core console application and it seems to work there. I'll need to do some follow up to figure out why it doesn't work for ASP.NET Core.

**Comment by BillHiebert** [comment] 2019-02-12 22:27
@DamianEdwards, @tmat the reason it doesn't work for ASP.NET Core is because it has the debugger attach to the running process. The good news is that the debugging team added support for ENC in attach scenarios a couple of versions ago by setting the environment variable COMPLUS_ForceENC=1 before starting the process. I verified this works. I reactivated the original VS customer feedback item so you can close this issue

**Comment by davidfowl** [comment] 2019-02-12 22:28
Done

**Closed by davidfowl** 2019-02-12 22:28 UTC
Labels: investigate

**Comment by camainc** [comment] 2019-02-12 22:40
So is this something that will be fixed in the next update?

**Comment by tmat** [comment] 2019-02-13 04:05
@BillHiebert Thanks for looking into this. The error message is not reported by the debugger not being able to perform the edit (that would be indicated by a dialog box), but by Roslyn APIs used to create debuggable compilations with SourceText objects that do not specify encoding. So it seems that multiple fixes might be needed in order to make this scenario work.

**Comment by BillHiebert** [comment] 2019-02-13 18:06
@tmat - setting the environment variable seems to work but more testing may be required to verify all scenarios. 

Note that a simple workaround is to add COMPLUS_ForceENC = 1 to the environment variables section in launchsettings.json.

**Comment by camainc** [comment] 2019-02-13 18:21
FYI, I added that workaround to my launchsettings.json and it did not make any difference in my experience.
![image](https://user-images.githubusercontent.com/944606/52734051-161c1c00-2f79-11e9-9795-c9798729510c.png)

**Comment by abuassar** [comment] 2019-03-18 09:57
I'm facing the exact same issue and it is quite frustrating.

any updates or possible work-around will be much appreciated...

**Comment by kurtcodemander** [comment] 2019-04-08 12:41
I'm also facing this same issue. It's also tracked here https://developercommunity.visualstudio.com/content/problem/414645/edit-and-continue-not-working-with-aspnet.html

Bill Hiebert says "_There is an issue in the way compiled razor page classes are being added which is preventing ENC from working_" and I can confirm that that's what it looks like in my project. In my project the error message is related to partials like for example "**_MenuPartial.g.cs**"

I don't know of any workarounds since COMPLUS_ForceENC is not working for me either.

**Comment by ZhangGaoxing** [comment] 2019-04-17 07:02
I think the issue should be reopened. I set `COMPLUS_ForceENC = 1` in `launchSettings.json`, but it doesn't work...☹
![image](https://user-images.githubusercontent.com/15957347/56267548-b3cecb80-6121-11e9-8b2f-1da612351092.png)

**Comment by JonasJes** [comment] 2019-04-17 09:30
It worker for me in VS2017 but after updating to VS2019 it stopped working

**Comment by rynowak** [comment] 2019-04-23 18:26
This is fixed in VS 2019 16.1 Preview 1

**Comment by SeppPenner** [comment] 2019-06-25 10:04
> This is fixed in VS 2019 16.1 Preview 1

Na, it's not (really) fixed. I'm using VS 2019 16.1 Preview 2 and the only thing that works is starting the application with STRG-F5 (Without the debugger). Still you have to press F5 in the browser to see the changes, however. Running the application using F5 won't work.

Check also https://github.com/aspnet/AspNetCore/issues/11489 and https://github.com/aspnet/AspNetCore/issues/5456.

Quote from @danroth27 from https://github.com/aspnet/AspNetCore/issues/11489#issuecomment-505102412: 
> To clarify, if you're using the latest Visual Studio Preview (https://visualstudio.com/preview) you should be able to run the app without debugging (Ctrl-F5), edit files in the project including .razor files, and then VS will rebuild and restart the app automatically so that you can just refresh the browser to see the change. If this isn't working for you with the latest bits please let us know!

**Comment by danroth27** [comment] 2019-06-25 17:26
@SeppPenner It sounds like you're still hitting issues in VS. Please try out the latest VS preview (https://visualstudio.com/preview) and if the problem can still be reproduced please open a new GitHub issue with a detailed description of the problem you are hitting and we'll take a look.

**Comment by SeppPenner** [comment] 2019-06-26 07:49
@danroth27 It's alright. What I was trying to say is: Running without the debugger works properly (As I told in https://github.com/aspnet/AspNetCore/issues/11489#issuecomment-505330487). Like you pointed out in the comment I quoted above: The support for complete live reload (https://github.com/aspnet/AspNetCore/issues/5456) is not yet done.

I don't have other issues, I'm just waiting for https://github.com/aspnet/AspNetCore/issues/5456 to be done :)

**Comment by Nastya-Scherbakova** [comment] 2019-10-07 11:23
Have this issue after updating VS Community 2019

**Comment by CatalinAdlerDF** [comment] 2019-11-23 08:29
I think you have to start Visual Studio having this env var setup, since the debugger is part of VS and has to be properly setup at its startup.
