### ISSUE TITLE
Blazor Server-Side: Api-Controllers of an other assembly got not mapped

### ISSUE THREAD

**Issue by endeffects** [aspnet/AspNetCore#11937] opened 2019-07-06 13:34 UTC
I'm running a blazor server side application on the latest .net core preview6.
When i'm moving the api controllers to an other referenced assembly
the controller got not mapped to any route at runtime. It works when i move them
back to the host or when i remove all the blazor server hosting stuff.

**Comment by mkArtakMSFT** [comment] 2019-07-08 16:39
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by endeffects** [comment] 2019-07-08 17:47
I have provided a sample here: https://1drv.ms/u/s!AvfU-VGBgXuLg-o4LRpQynSJvInKcA?e=Pb00ls
There is an API Project with the moved Controller. By loading the FetchData Page you'll see that the controller was not found. By removing the external controler and activating the original one on the server project you'll see that the FetchData Page is working.

**Comment by mkArtakMSFT** [comment] 2019-07-17 22:47
We're closing this as  this seems to be a dupe of https://github.com/aspnet/AspNetCore/issues/11921

**Closed by mkArtakMSFT** 2019-07-17 22:47 UTC
Labels: area-mvc, investigate
