### ISSUE TITLE
.Net Core 3.0 and gRPC on Mac

### ISSUE THREAD

**Issue by tungphuong** [aspnet/AspNetCore#12463] opened 2019-07-23 05:38 UTC
I followed the document to create one gRPC server with .net core 3.0 preview 6. It works well on window 10 and WSL. However, when I run it on MacOS via console or Visual Studio for Mac that it throws an exception

fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

The current settings and code:
- appsettings.json
```
	 "AllowedHosts": "*",
	  "Kestrel": {
	    "EndpointDefaults": {
	      "Protocols": "Http2"
	    }
	  }
```
- startup.cs
```
	public void ConfigureServices(IServiceCollection services)
    {
    	services.AddGrpc();
    }
```
So, Were gRPC and Http/2 supported on MacOS yet? And how can we solve this issue?

Thanks,

**Comment by shirhatti** [comment] 2019-07-29 20:33
Secure Transport on MacOS doesn't support server-side ALPN and as such we can't support HTTP/2. You can still use gRPC on OS X with h2c. Closing as a dupe of https://github.com/grpc/grpc-dotnet/issues/416.

I've also filed a docs bug to add documentation on how to use gRPC with h2c -https://github.com/aspnet/AspNetCore.Docs/issues/13544

**Closed by shirhatti** 2019-07-29 20:33 UTC
Labels: area-grpc
