### ISSUE TITLE
Blazor 0.8.0 standalone project that was generated by "dotnet new blazor" command could not launch.

### ISSUE THREAD

**Issue by jsakamoto** [aspnet/AspNetCore#7304] opened 2019-02-06 15:15 UTC
### Describe the bug

Blazor 0.8.0 standalone project that was generated by `dotnet new blazor` command could not launch.

### To Reproduce

1. Install .NET Core SDK ver.3.0.0-preview-**19075-0444** from [here](https://dotnet.microsoft.com/download/dotnet-core/3.0).
2. Install Visual Studio 2019 Preview 2.
3. Install Blazor 0.8.0 template by `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04`
4. Create Blazor 0.8.0 **standalone** project by `dotnet new blazor`.
5. Restore and build it by `dotnet build`. (this will be success.)
6. Run it by `dotnet run`
7. The error message (see bellow)  is shown, and it could not launch.

```
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0-preview-19104-06' was not found.
```

### Expected behavior

`dotnet run` launch blazor server successfully.

### Screenshots

![image](https://user-images.githubusercontent.com/95908/52350630-599ff300-2a6c-11e9-9c43-cd09c1dd08b6.png)

### Additional context

The hosted version of Blazor 0.8.0 that was generated by `dotnet new blazorhosted` CLI works fine.

I could not find the version 3.0.0-preview-**19104-06** of .NET Core SDK or Runtime in my internet searching.

### My workaround

I rewrited "%HOME%.nuget\packages\microsoft.aspnetcore.blazor.cli\0.8.0-preview-19104-06\lib\netcoreapp3.0\dotnet-blazor.runtimeconfig.json" to use v.19075-0444 instead of v.19104-06.

![image](https://user-images.githubusercontent.com/95908/52350960-07ab9d00-2a6d-11e9-9a3f-b2256b399233.png)

After that, "dotnet run" works fine.

**Comment by jsakamoto** [comment] 2019-02-07 12:52
### Additional Information

The Blazor standalone project that was generated by **Visual Studio 2019 Preview 2.x** worked fine.

The difference of theses projects was bellow:

```xml
<!-- from "dotnet new blazor"-->
<DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.8.0-preview-19104-06" />
``` 
```xml
<!-- from VS2019-->
<DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.8.0-preview-19104-04" />
``` 
I tried uninstall the project template with `dotnet new -u Microsoft.AspNetCore.Blazor.Templates -Version` command, and reinstall it with `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04` command.

After that, `dotnet new blazor` generate the csproj as bellow:

```xml
<!-- from "dotnet new blazor" after reinstall project template -->
<DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.8.0-preview-19104-04" />
``` 

Of course, Version 0.8.0-preview-19104-04 CLI works fine.

I'm not sure why my first installation of Blazor project template for dotnet CLI was configured for using invalid version"19104-**06**".

**Comment by mkArtakMSFT** [comment] 2019-02-07 16:54
Thanks for contacting us, @jsakamoto.
Glad you've found the cause of this and managed to fix it.
@danroth27, what this could be caused by?

**Comment by danroth27** [comment] 2019-02-08 00:52
@jsakamoto I suspect when you installed the Blazor templates initially you somehow picked up a version of the templates package from one of our MyGet feeds with dev builds.

Since you've resolved your own issue I'm going to go ahead and close this.

**Closed by danroth27** 2019-02-08 00:52 UTC
Labels: area-mvc, question
