### ISSUE TITLE
UseStatusCodePagesWithReExecute does not work if an endpoint returned 404 manually

### ISSUE THREAD

**Issue by raphaelr** [aspnet/AspNetCore#11555] opened 2019-06-25 17:08 UTC
### Describe the bug
When using UseStatusCodePagesWithReExecute() to handle 404 errors, the 404 handler is not executed if the endpoint returned 404 manually (i.e. did `context.Response.StatusCode = 404`). UseStatusCodePagesWithRedirects() works just fine.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview6.19307.2'
2. Run this code

        public class Startup {
            public void ConfigureServices(IServiceCollection services) { }

            public void Configure(IApplicationBuilder app) {
                // Uncomment either this:
                //   app.UseStatusCodePagesWithRedirects("/Status{0}");

                // Or this:
                //   app.UseStatusCodePagesWithReExecute("/Status{0}");

                app.UseRouting();
                app.UseEndpoints(endpoints => {
                    endpoints.MapGet("Status404", async context => {
                        await context.Response.WriteAsync("Status404 handler was executed");
                    });

                    endpoints.MapGet("Weather/{city}", async context => {
                        var city = context.GetRouteData().Values["city"] as string;
                        if (string.Equals(city, "London", StringComparison.OrdinalIgnoreCase))
                        {
                            await context.Response.WriteAsync("Rainy");
                        }
                        else
                        {
                            context.Response.StatusCode = 404;
                        }
                    });
                });
            }
        }

3. Observe the different behaviour when requesting `/Weather/London`, `/Weather/Tokyo`, and `/DoesNotExistAtAll`

4. `/Weather/Tokyo` executed the Status404 handler when using UseStatusCodePagesWithRedirects(), but returns an empty response (no "Status404 handler was executed") message when using UseStatusCodePagesWithReExecute()

### Expected behavior

| | /Weather/London | /Weather/Tokyo | /DoesNotExist
|-|---|---|---
| WithRedirects | "Rainy" | "Status404 handler was executed" | "Status404 handler was executed"
| WithReExecute | "Rainy" | **Empty response** | "Status404 handler was executed"

### Screenshots

n/a

### Additional context

The endpoint routing middleware checks if an endpoint has already been set here: [EndpointRoutingMiddleware.cs#L58](https://github.com/aspnet/AspNetCore/blob/release/3.0-preview6/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L58).

But the status code pages middleware does not reset the endpoint before re-executing the request: [StatusCodePagesExtensions.cs#L175-L202](https://github.com/aspnet/AspNetCore/blob/release/3.0-preview6/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesExtensions.cs#L175-L202).

Therefore the endpoint router will execute the same endpoint again. If this is in fact the expected behavior then I suggest updating the [error handling documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.0#usestatuscodepageswithreexecute) to warn about using UseStatusCodePagesWithReExecute() with the endpoint router.

As a workaround, I've written a middleware that sets the IEndpointFeature's Endpoint to null if the IStatusCodeReExecuteFeature is present.

Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Tratcher** [comment] 2019-06-25 17:52
Duplicate of https://github.com/aspnet/AspNetCore/issues/11233. The endpoint isn't getting cleared so the request doesn't re-route.
@pranavkm

**Comment by pranavkm** [comment] 2019-06-25 18:00
Yup. Thanks for the detailed report @raphaelr. I'll make sure to verify this is addressed as part of #11233

**Closed by pranavkm** 2019-06-25 18:00 UTC
Labels: area-middleware

**Comment by woeterman94** [comment] 2019-11-26 08:19
Any updates / work arounds? It's not working for me either in .NET core 2.0

**Comment by Tratcher** [comment] 2019-11-26 11:55
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

The above was only a temporary regression in 3.0, it did not apply to 2.0.
