### ISSUE TITLE
React template fails to restore

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#8441] opened 2019-03-12 16:50 UTC
Restoring packages for 

```console
/work/AspNetCore/src/ProjectTemplates/test/bin/Debug/netcoreapp3.0/TestTemplates/AspNet.Template.937009/AspNet.Template.937009.csproj...
 /work/AspNetCore/src/ProjectTemplates/test/bin/Debug/netcoreapp3.0/TestTemplates/AspNet.Template.937009/AspNet.Template.937009.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Mvc.ViewFeatures with version (>= 3.0.0-preview4-t000)
 /work/AspNetCore/src/ProjectTemplates/test/bin/Debug/netcoreapp3.0/TestTemplates/AspNet.Template.937009/AspNet.Template.937009.csproj : error NU1102:   - Found 2241 version(s) in https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json [ Nearest version: 3.0.0-preview4-19123-01 ]
 /work/AspNetCore/src/ProjectTemplates/test/bin/Debug/netcoreapp3.0/TestTemplates/AspNet.Template.937009/AspNet.Template.937009.csproj : error NU1102:   - Found 115 version(s) in dotnet-core [ Nearest version: 3.0.0-preview4-19121-14 ]
 /work/AspNetCore/src/ProjectTemplates/test/bin/Debug/netcoreapp3.0/TestTemplates/AspNet.Template.937009/AspNet.Template.937009.csproj : error NU1102:   - Found 90 version(s) in https://dotnet.myget.org/F/dotnet-core/api/v3/index.json [ Nearest version: 2.2.0 ]
 /work/AspNetCore/src/ProjectTemplates/test/bin/Debug/netcoreapp3.0/TestTemplates/AspNet.Template.937009/AspNet.Template.937009.csproj : error NU1102:   -
```

Seems to be due to this

**Unable to find package Microsoft.AspNetCore.Mvc.ViewFeatures** with version (>= 3.0.0-preview4-t000)

The only package references are spaservices and newtonsoftjson

**Comment by javiercn** [comment] 2019-03-12 17:01
Seeing this on linux.

**Comment by mkArtakMSFT** [comment] 2019-03-12 18:21
@Eilon this looks like dependency related issue, rather than an issue in the templates. Should this be reassigned to a different area?

**Comment by Eilon** [comment] 2019-03-12 18:50
Can we have someone try to find the cause? Otherwise I'm not sure where to send this.

**Comment by mkArtakMSFT** [comment] 2019-03-12 19:44
@JunTaoLuo do you know what can cause this failures?

**Comment by JunTaoLuo** [comment] 2019-03-12 19:57
Hmm are you seeing this on a local build? I suspect that because I see `-t000`. cc @ryanbrandenburg.

**Comment by javiercn** [comment] 2019-03-12 20:02
@JunTaoLuo Yeah, but ViewFeatures is not a package, it's part of the shared framework. So something must be going wrong there.

**Comment by javiercn** [comment] 2019-03-12 20:14
The nuspec for newtonsoftjson is being incorrectly generated I believe
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Microsoft.AspNetCore.Mvc.NewtonsoftJson</id>
    <version>3.0.0-preview4-t000</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>https://raw.githubusercontent.com/aspnet/AspNetCore/2.0.0/LICENSE.txt</licenseUrl>
    <projectUrl>https://asp.net/</projectUrl>
    <iconUrl>https://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <description>ASP.NET Core MVC features that use Newtonsoft.Json. Includes input and output formatters for JSON and JSON PATCH.

This package was built from the source code at https://github.com/aspnet/AspNetCore/tree/5aeb375735733543fa2af714933b3efb3a944e0a</description>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <tags>aspnetcore aspnetcoremvc json</tags>
    <serviceable>true</serviceable>
    <repository type="git" url="https://github.com/aspnet/AspNetCore" commit="5aeb375735733543fa2af714933b3efb3a944e0a" />
    <dependencies>
      <group targetFramework=".NETCoreApp3.0">
        <dependency id="Microsoft.AspNetCore.JsonPatch" version="3.0.0-preview4-t000" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Mvc.ViewFeatures" version="3.0.0-preview4-t000" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="12.0.1" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json.Bson" version="1.0.2" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by mkArtakMSFT** [comment] 2019-03-25 21:58
@javiercn who is responsible for proper nuspec generation here?

**Comment by ryanbrandenburg** [comment] 2019-03-25 22:03
@pranavkm was just running into this and we resolved it by doing [The steps here](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/README.md).

**Comment by ryanbrandenburg** [comment] 2019-03-25 22:03
Although perhaps that was just papering over this nuspec thing.

**Comment by javiercn** [comment] 2019-03-25 22:08
I was also able to get past this. But why is the nuspec being incorrectly generated?

**Comment by mkArtakMSFT** [comment] 2019-03-25 22:12
@javiercn, assigning this to you to drive to resolution.

**Comment by pranavkm** [comment] 2019-03-25 22:25
@javiecn I think this was addressed more recently. When I built the repo locally, the NewtonsoftJson package did not have a reference to the Mvc.ViewFeatures

**Comment by mkArtakMSFT** [comment] 2019-03-28 17:20
@javiercn, please close if this is the case.

**Comment by pranavkm** [comment] 2019-04-16 22:49
Ok, I was wrong. This still reproduces. @JunTaoLuo \ @natemcmaster isn't there a thing that runs and erases references to the packages in the shared runtime from other shipping packages? What do we need to do run this as as part of `build -Pack`?

**Comment by natemcmaster** [comment] 2019-04-17 16:19
>  isn't there a thing that runs and erases references to the packages in the shared runtime from other shipping packages

Yes. Until #4257 is complete, packages produced by calling `dotnet pack` may not actually be 100% correct.

**Comment by pranavkm** [comment] 2019-04-17 16:26
Okies. I'll close this as dup.

**Closed by pranavkm** 2019-04-17 16:26 UTC
Labels: area-infrastructure, investigate
