### ISSUE TITLE
The Asp.Net Web Api get request cannot return a result larger than 20K

### ISSUE THREAD

**Issue by AceTheWiz** [aspnet/AspNetCore#8388] opened 2019-03-10 14:47 UTC
### Describe the bug
The Asp.Net Web Api get request cannot return a result larger than 20K.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview3-19153-02' with VS 2019 v 16.0.0 Preview 4.1
2. Run this cmd ```dotnet new blazorhosted```
3. With these code changes
Change the Range from 5 to 200 in the following line.
```C#
return Enumerable.Range(1, 5).Select(index => new WeatherForecast
```
The line should look like this
```C#
return Enumerable.Range(1, 200).Select(index => new WeatherForecast
```
4. Run the App
Click on the "Fetch Data" nav menu item.

5. See error
No data is displayed.

### Expected behavior
1. The page should display 200 lines of WeatherForecast Data
2. I would expect to see an exception.

### Screenshots
N/A
### Additional context
This worked in asp.net core preview 2
Some investigation showed that the call to the WebApi
```C#
forecasts = await Http.GetJsonAsync<WeatherForecast[]>("api/SampleData/WeatherForecasts");
```
was returning garbage.

Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by AceTheWiz** [comment] 2019-03-10 14:51
Damm Github ! Lost all my issue details when navigating to "other possible duplicate issues"

**Comment by mkArtakMSFT** [comment] 2019-04-01 16:26
Thanks for contacting us, @AceTheWiz.
@javiercn, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment] 2019-05-17 16:59
Thanks for contacting us, @AceTheWiz. This is a dupe of https://github.com/aspnet/AspNetCore/issues/9322 and have is now fixed.

**Closed by mkArtakMSFT** 2019-05-17 16:59 UTC
Labels: area-blazor, investigate
