### ISSUE TITLE
Use Code+PKCE OAuth2 flow for SPA applications

### ISSUE THREAD

**Issue by mkrtich-m** [aspnet/AspNetCore#9869] opened 2019-04-30 19:28 UTC
Current SPA templates are using API request to load [oidc-client](https://github.com/IdentityModel/oidc-client-js) configuration which boils down to following
[source code](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/ApiAuthorization.IdentityServer/src/Extensions/DefaultClientRequestParametersProvider.cs#L41). As you can see it only supports implicit code flow which is less secure than alternatives.

There is a very good article by @brockallen called [The State of the Implicit Flow in OAuth2](https://brockallen.com/2019/01/03/the-state-of-the-implicit-flow-in-oauth2/) which describes more secure way of handling authentication in browser based applications using authorization code flow with Proof Key for Code Exchange by OAuth Public Clients (also known as PKCE).

[oidc-client](https://github.com/IdentityModel/oidc-client-js) which is used in all ASP.NET Core SPA templates already [supports](https://github.com/IdentityModel/oidc-client-js/commit/c68ceaa78a43c92ebe6198a07f3bab6b916d559a) Code + PKCE. Here is an [example](https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/9_Combined_AspId_and_EFStorage/src/JavaScriptClient/wwwroot/app.js#L25).

**Comment by blowdart** [comment] 2019-04-30 21:08
Dupe of https://github.com/aspnet/AspNetCore/issues/7734

**Comment by brockallen** [comment] 2019-04-30 21:16
Dom's issue suggests to add to the ASP.NET Core OIDC security handler (for server-side clients). This issue asks that the SPA client be configured to use code+pkce.

**Comment by blowdart** [comment] 2019-06-12 20:11
Also @javiercn 

I believe @Tratcher did the server side bits.

**Comment by Tratcher** [comment] 2019-06-12 20:17
Yes, #7734 is done.

**Comment by javiercn** [comment] 2019-07-12 14:22
We need to do some work on the templates before we can completely move them to code.

**Comment by javiercn** [comment] 2019-07-20 14:03
This is fixed proper now

**Closed by javiercn** 2019-07-20 14:03 UTC
Labels: area-identity, identity-UI
