### ISSUE TITLE
Tag Helper asp-src-include Not Functional in Core 3.0

### ISSUE THREAD

**Issue by craigmcampbell** [aspnet/AspNetCore#14642] opened 2019-10-01 21:15 UTC
### Describe the bug
In 3.0, when using the asp-src-includes tag helper inside of a Scripts section to include a javascript file, a 500 error is generated. This tag helper worked just fine in 2.2.

### To Reproduce
**Version**
AspNetCore 3.0

**Code**
```
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts {
    <script asp-src-include="/js/dist/dashboard*.js"></script>
}

<div id="dashboard">
    <dashboard></dashboard>
</div>
```

**Error**
![image](https://user-images.githubusercontent.com/22157013/66000670-8d99af80-e465-11e9-819b-d122a6a8ec88.png)

### Expected behavior
It should have loaded the designated js file and properly rendered the page.

### Additional context
I tried various permutations of the path to the js file, including relative pathing and removing the wildcard character.

If I remove the tag helper and just use this, the page loads as expected:
```
@section Scripts {
    <script src="/js/dist/dashboard.js"></script>
}
```

The ability to use the tag helper and the wildcard is important to me for cache busting of JS files in the browser.

**dotnet --info**
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by pranavkm** [comment] 2019-10-02 16:38
Thanks for the issue report @craigmcampbell. @ryanbrandenburg could you have a look?

**Comment by ryanbrandenburg** [comment] 2019-10-04 22:44
Hey @craigmcampbell, I tried to reproduce this with 3.0.0 RTM bits based off your description here but could not. The next step is for you to produce a minimalist GitHub repo which demonstrates the problem.

For the record, the steps I took to try reproing:

1. Clean Windows VM/Sandbox, install 3.0.0 sdk.
1. `dotnet new mvc`
1. Create two valid but useless js files matching /wwwroot/js/dist/dashboard*.js.
1. On the `Index.cshtml` page add:
```
@section Scripts {
    <script asp-src-include="/js/dist/dashboard*.js"></script>
}
```

I also tried:
- Not having any files that matched the given pattern.
- Having invalid JS in the files.
- Having the pattern not match any existing folders.
- Omitting the `/` at the front of the asp-src-include.
- Switching `/` to `\`.

**Comment by craigmcampbell** [comment] 2019-10-07 14:28
@ryanbrandenburg Thanks for looking into this, I appreciate it. 

I put together a default web project, included the script, and then referenced it on /Home/Index. Ran the site and I received the same error as above - "The path in 'value' must start with '/'".

A repo with the sample project is here: https://github.com/craigmcampbell/ScriptIncludeExample.

Please let me know if you need anything else from me!

**Comment by ryanbrandenburg** [comment] 2019-10-10 22:20
I have a PR out which should fix this. Basically the system that does Globbing strips the `/` out as part of its search, then a function later on requires the path start with a `/`. Unfortunately I don't know of a workaround that works with the TagHelper and Globbing, but a fix is coming!

**Comment by craigmcampbell** [comment] 2019-10-10 22:54
Thanks, @ryanbrandenburg. If you need anything else, please let me know.

**Comment by JoeYong** [comment] 2019-10-22 13:46
Looks like both asp-href-include and asp-src-include have this same issue. They were working fine under 2.2. Wonder what changed?

A quick question - will the fix be out soon as a patch or until .NET Core 3.1? Trying to assess if we need to abandon the migration until 3.1 comes out. Thank you.

**Comment by craigmcampbell** [comment] 2019-10-22 15:38
@JoeYong I had the same question. Our migration to 3 is on hold until this is resolved.

**Comment by ryanbrandenburg** [comment] 2019-10-22 17:46
I believe preview2 is locked down as of Friday, so this won't be in there. My current aim is to get it into preview3.

**Comment by ryanbrandenburg** [comment] 2019-10-29 23:11
Fixed by #14803. Should go out with preview3.

**Closed by ryanbrandenburg** 2019-10-29 23:11 UTC
Labels: Done, area-mvc, investigate
