### ISSUE TITLE
Multiple Access-Control-Allow-Origin headers when using CORS in IIS

### ISSUE THREAD

**Issue by kenlyon** [aspnet/AspNetCore#3525] opened 2018-09-10 21:30 UTC
I have an `ASP.NET Core` project in which I use _CORS_. I am targeting `.NET Core 2.1`. I believe my settings are fairly standard, but I'll log them here to give context.

Firstly, I add some CORS policies at the start of the `ConfigureServices` method:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors(options =>
    {
        options.AddPolicy(
            "AllowEverything",
            builder => builder
                .AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod());
        options.AddPolicy(
            "AllowLocalhost",
            builder => builder
                .WithOrigins("http://localhost")
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials());
    });
    ...
}
```

Then I specify which policy I am using at the end of the `Configure` method:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IOptions<WorkflowServerSettings> settings, IApplicationLifetime applicationLifetime)
{
   ...
    app.UseCors("AllowLocalhost");
}
```

By the way, this is not a final implementation, so please try to resist the urge to review this too much. At least I don't use "AllowEverything" by default. :)

When I run this via IIS Express, it works fine but I have problems when I run it in IIS. (after publishing via File System.)

The problem is that a parent application has a web.config file that adds the "Access-Control-Allow-Origin" header. Unfortunately, I end up with two "Access-Control-Allow-Origin" headers in my response, and the browser does not like it.

Is this a bug? Should `ASP.NET Core` be replacing the existing header, or at least combining with it? I believe multiple "Access-Control-Allow-Origin" headers is an error, so i think it needs to be more robust.

I can manually fix it in IIS after the deployment but each publish re-creates the web.config and I don't know of a clean way to fix it. I could probably remove it from the context, but that seems more like a workaround than a proper implementation.

**Comment by mkArtakMSFT** [comment] 2018-09-28 18:15
Thanks for contacting us, @kenlyon.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment] 2018-10-04 20:11
@kenlyon This is not a bug on the MVC side. It's an issue with the web.config that gets generated at deployment time. @vijayrkn who owns this part of the publish pipeline?

**Comment by vijayrkn** [comment] 2018-10-04 20:17
the web.config generation logic is in the websdk. I can take a look. 

@kenlyon - Do you have a sample project?

**Comment by kenlyon** [comment] 2018-10-04 21:19
@vijayrkn I don't right now. It's part of something larger and I'm a bit short of time, unfortunately.

The steps to reproduce should be:
1. In IIS, create a Site or Application.
1. In the "HTTP Response Headers" add `Access-Control-Allow-Origin` with a value of `*`.
1. In Visual Studio, create a .NET Core Web API project. (Mine is using .NET Core 2.1)
1. In the `Configure` method of the `Startup` class, add the following **before** `app.UseMcv()`:
            app.UseCors(builder =>
                builder
                .WithOrigins("http://localhost")
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials());
1. Add a Controller with an Action (so you have an endpoint to call).
1. Publish to File System.
1. In IIS, add the published test project as a child of the Site/Application you created at the start.
1. Make sure the site has an https binding. (I think this is necessary for http://localhost to be considered CORS.)
1. Make a request from http://localhost to the endpoint using https. You should see the two `Access-Control-Allow-Origin` headers in the response.

**Comment by vijayrkn** [comment] 2018-10-05 01:53
I tried the steps you mentioned but I can't repro the issue. 

Here is my web.config from the IIS site from Step1

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\WebApplication1.exe" arguments="" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
	<httpProtocol>
		<customHeaders>
			<add name="Access-Control-Allow-Origin" value="*" />
		</customHeaders>
	</httpProtocol>
  </system.webServer>
  </location>
</configuration>
```

And here is the web.config generated by publish (used by the child app) in step 7
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\WebApplication34.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>
```


Do you have this line in the root website? May be that is the issue. I don't see publish re-adding any settings. 

`  <location path="." inheritInChildApplications="false">`

**Comment by pranavkm** [comment] 2018-10-05 16:57
> In the "HTTP Response Headers" add Access-Control-Allow-Origin with a value of *.

@kenlyon why are you doing that? Returning `Access-Control-Allow-Origin: *` with `AllowCredentials` will result in browsers disallowing the request.

**Comment by javiercn** [comment] 2018-11-01 22:35
Closing as per @vijayrkn we can't repro the issue. CORS should be configured in a single place and the recommended place is the app as provide way more flexibility than the server.

**Comment by kenlyon** [comment] 2018-11-02 15:58
My apologies for my delay on this. I overlooked a notification in my inbox.

@vijayrkn The parent web.config does not have `<location path="." inheritInChildApplications="false">`. If you literally start with a new site and add the header and do nothing else, you should be able to reproduce the problem. Could you please try again without that entry?

@pranavkm The project that I'm working on has a number of nested applications with varying requirements. For most of them, we are allowing requests from any origins.

@javiercn Would you please consider re-opening this issue? I understand that ideally CORS should be configured in a single place, but different requirements can call for more creative solutions. I believe my steps to reproduce are accurate and should work, as long as that extra `<location path="." inheritInChildApplications="false">` entry is not added to the parent web.config.

**Comment by vijayrkn** [comment] 2018-11-02 16:42
If you dont have this to the parent site, then the settings will be inherited 
`<location path="." inheritInChildApplications="false">`

Then, this is not a publish tooling problem. I will let @pranavkm & @javiercn comment on the runtime side of things.

**Comment by javiercn** [comment] 2018-11-02 16:46
@kenlyon I don’t see how the runtime can do anything here as we don’t see the header (presumably it gets appended to the response after the ASP.NET Core pipeline has executed) and then IIS appends the extra header.

@shirhatti is there anything the IIS CORS Module should do here? Like avoid adding the header if there’s one already present or an attribute to control this behavior?

**Comment by shirhatti** [comment] 2018-11-02 17:32
As @vijayrkn alluded to, newer versions of the websdk add the `<location path="." inheritInChildApplications="false">` in your web.config.
If you don't have it, you can still clear out all the inherited values in the customHeader collection as shown below

```xml
<configuration>
  <system.webServer>
	<httpProtocol>
		<customHeaders>
			<clear />
		</customHeaders>
	</httpProtocol>
  </system.webServer>
</configuration>
```

**Comment by vijayrkn** [comment] 2018-11-02 20:51
We have web.config transform support in 2.2 SDK. You can find examples here - https://github.com/vijayrkn/webconfigtransform/

**Comment by javiercn** [comment] 2018-11-05 18:20
I believe this issue has been resolved with @vijayrkn's answer, so closing it.

**Closed by javiercn** 2018-11-05 18:20 UTC
Labels: investigate, repo:CORS

**Comment by kenlyon** [comment] 2018-11-05 19:42
This does look like the best way to address the problem. 

Is there a way to actually edit `web.config` directly then, or just transform it? Ideally I'd prefer to do that, but worst case I could add transforms for both Debug and Release to do the same thing.

**Comment by jkotalik** [comment] 2018-11-05 19:48
You can also put a web.config file directly in the root directory of you application and it will be used for debug/release and added to published applications.

**Comment by kenlyon** [comment] 2018-11-05 22:40
Ah! I had no idea that was supported. Thanks for suggesting that. For some reason, I had thought the web.config file needed to be created by the publish process. Now I see that I can add one and it's pre-populated with almost exactly the same content as you get from the default.

I did notice that the default created by Visual Studio doesn't include the `<location path="." inheritInChildApplications="false">` element, but I was able to add that and the appropriate section for removing the offending "Access-Control-Allow-Origin" header.

Thanks everyone for your help and patience!

**Comment by jkotalik** [comment] 2018-11-05 22:42
@vijayrkn the web.config template should include the `<location path="." inheritInChildApplications="false">` by default.

**Comment by vijayrkn** [comment] 2018-11-05 23:29
In the latest version of VS, this section will be automatically added during publish
<location path="." inheritInChildApplications="false">

**Comment by vijayrkn** [comment] 2018-11-05 23:31
https://github.com/aspnet/websdk/blob/master/src/Publish/Microsoft.NET.Sdk.Publish.Tasks/WebConfigTransform.cs#L19

**Comment by kenlyon** [comment] 2018-11-06 16:40
@vijayrkn If I publish when there is no web.config present in the project then the generated one **does** include the `location` element:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\MyProject.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>
<!--ProjectGuid: 06a3f362-aa7c-4b1a-8a2c-3b41b5c11715-->
```
However this process produces a different result:
1. Right-click the ASP.NET Core project in Visual Studio and choose Add > New item...
1. In the "Installed" list in the left column, expand ASP.NET Core and select Web.
1. In the list of templates, select Web Configuration File.
1. Click "Add".

This adds the following web.config file to the project:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <!-- To customize the asp.net core module uncomment and edit the following section. 
  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
  <!--
  <system.webServer>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
  -->

</configuration>
```
Note that the commented-out sample content **does not** include the `location` element, but is otherwise equivalent.

I don't know how much this matters or how high a priority it is to you, but it's the only discrepancy I see. If I want to be sure to produce the equivalent to the web.config that is created when I publish, I need to manually add the `location` element to the file that I add.

**Comment by vijayrkn** [comment] 2018-11-06 16:49
@kenlyon - That is correct. The location tag is only added during publish. The web.config item template does not have the location tag by default. 

I will work with the Project system expert on my side to see if it makes sense to add this to the item template as well. Thank you for reporting this. 

/cc @BillHiebert
