### ISSUE TITLE
Blazor - Documentation management, MVC issues, missing methods and attributes...

### ISSUE THREAD

**Issue by mrbrennonwilliams** [aspnet/AspNetCore#9984] opened 2019-05-05 12:54 UTC
Hello,

*Please don't take this as a negative criticism of the fine work and effort going into this project, but please do pay attention to some of the issues I list here as an extremely experienced dev, picking up the project for the first time. I am hoping some of these issues can be resolved and thought about to improve the experience and help the community existing and future.*

First - from a standing start, this is a bit of a mess. And I get that - things are moving at pace and it is hard to keep it sanitised.

Some of us old school dev's actually read documentation. When that documentation is not managed and updated or accurate, we lose confidence.

This page: https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

Working through this page there are several issues:

The source code is shown to be in CSHTML files, when really they should have a heading tag of .razor - a small but confusing issue.

From a fresh install of everything - builds as described. All good.

Then when we keep working through the documentation and do something like:

```
@functions {
    private int currentCount = 0;

    [Parameter]
    private int IncrementAmount { get; set; } = 1;

    private void IncrementCount()
    {
        currentCount += IncrementAmount;
    }
}
```

The fun starts...

This is the mess inside of the Error list:
![image](https://user-images.githubusercontent.com/32671341/57193833-88c4e400-6f37-11e9-8f8f-73e917977ced.png)

A known issue from previous builds, but a closed bug. Clearly, this is still here.

Then we have Attribute issues:
![image](https://user-images.githubusercontent.com/32671341/57193857-b7db5580-6f37-11e9-9448-e0bf9d876477.png)

Intellisense appears to be a mess:
![image](https://user-images.githubusercontent.com/32671341/57194191-c9bef780-6f3b-11e9-8098-334fa5d92a52.png)

Ok, so let's try and add a new Razor page in the Pages folder:
![image](https://user-images.githubusercontent.com/32671341/57194290-08a17d00-6f3d-11e9-90b1-146b999e8892.png)

Let's try JS Interop... we see code like this in the example documentation:

```
public override void OnInit()
    {
        StocksService.OnStockTickerUpdated += stockUpdate =>
        {
            JSRuntime.InvokeAsync<object>(
                "handleTickerChanged",
                stockUpdate.symbol,
                stockUpdate.price);
        };
    }

```
This doesn't compile unless EventArgs are passed in - and then appears to not even fire? In fact, OnLoad events don't appear to work on elements such as `<Body>` either.

So there are a number of issues here, and there are more which I will start to log as separate issues in line with the team format.

Please feel free to reach out and use me as a resource here - I am converting a substantial WPF UI application to a client-side Blazor/Electron SPA and I am hoping my experiences can help surface and work through issues on this very cool project.

Best,
Brennon

**Comment by pranavkm** [comment] 2019-05-05 14:03
@mrbrennonwilliams for the tooling specific issues, you need to install the preview build of VS 2019: https://visualstudio.microsoft.com/vs/preview/

**Comment by drk-mtr** [comment] 2019-05-05 14:45
https://github.com/ConsenSys/ethql/wiki/Submitting-Bugs-and-Suggestions

`Do not enumerate multiple bugs or feature requests in the same issue.`

I feel your pain, but we need to make this easy for the maintainers to track and resolve.

**Comment by mrbrennonwilliams** [comment] 2019-05-05 15:25
> @mrbrennonwilliams for the tooling specific issues, you need to install the preview build of VS 2019: https://visualstudio.microsoft.com/vs/preview/

It is installed

**Comment by mrbrennonwilliams** [comment] 2019-05-05 15:33
> Some good guidance from a different project: https://github.com/Microsoft/azuredatastudio/wiki/Submitting-Bugs-and-Suggestions
> 
> `Do not enumerate multiple bugs or feature requests in the same issue.`
> 
> I feel your pain, but we need to make this easy for the maintainers to track and resolve.


Point being, this post is not about multiple bugs - it is about a simple trace of the guiding **Documentation** and the multiple issues that it presents, which is in itself -  a bug. If no one is interested in that user experience, feel free to close this out. As I mentioned in the OP, I will log individual bugs.

Cheers

**Comment by drk-mtr** [comment] 2019-05-05 15:54
Just for context - I'm not anything to do with this project or Microsoft - just a very amateur dev chiming in with an opinion.

And it's not that I'm not interested in that user experience, I am because I'm far less experienced and rely on documentation - however I'm just giving my opinion on the easiest way to get it resolved.

**Comment by SteveSandersonMS** [comment] 2019-05-06 08:37
@mrbrennonwilliams Thanks for reporting this.

FYI most of the issues you've observed here are because you're compiling your component as a view/page (`.cshtml`) instead of a component (`.razor`). The APIs are different because these are different technologies that handle different use cases. I know you were misled into doing this by out-of-date docs, which like you've observed, is because this is a fast-moving preview release and we're not promising that the docs and product code are always synchronized at this stage. Obviously they will be once we ship a full release.

Also the point about the Razor scaffolder (which is a valid issue) is a duplicate of another issue.

I'm not sure there's really anything for us to take action on here, other than update the docs which is already a work in progress.

> there are more which I will start to log as separate issues in line with the team format.

Thanks for this. Please do log separate bugs, and if possible check if each duplicates an existing issue (though I appreciate it's not always easy to tell).

With all this in mind, I'll close this because I don't think it represents any new actions for us to take. But please let me know if you think I've missed something important.

**Closed by SteveSandersonMS** 2019-05-06 08:37 UTC
Labels: area-mvc, feature-Components
