### ISSUE TITLE
Shorten paths of Microsoft.AspNetCore.Razor.Language.Test files

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#9358] opened 2019-04-14 02:14 UTC
## Bug
The paths of files in the ComponentDesignTimeCodeGenerationTest project are long enough to break dotnet-maestro-bot and prevent automatic PRs to merge 'release/*' branches into 'master'.

### To Reproduce
1. Merge a change into (say) 'release/3.0-preview4'
2. Watch build jobs for the bot at https://dev.azure.com/dnceng/internal/_build?definitionId=350&_a=summary that relate to the aspnet/AspNetCore-Tooling repo

### Expected behavior
Successful creation of a PR to merge the 'release/3.0-preview4' branch into 'master'

### Actual
No PR to merge the branches is created. Bot builds such as https://dev.azure.com/dnceng/internal/_build/results?buildId=154762 fail to clone the aspnet/AspNetCore-Tooling repo due to filename-to-long errors:
```
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_EventCallback_SpecifiesValueAndExpression_Generic/TestComponent.mappings.txt: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_EventCallback_SpecifiesValue_WithMatchingProperties/TestComponent.codegen.cs: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_EventCallback_SpecifiesValue_WithMatchingProperties/TestComponent.mappings.txt: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_SpecifiesValueAndChangeEvent_WithMatchingProperties/TestComponent.codegen.cs: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_SpecifiesValueAndChangeEvent_WithMatchingProperties/TestComponent.mappings.txt: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_SpecifiesValueAndChangeEvent_WithoutMatchingProperties/TestComponent.codegen.cs: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/BindToComponent_SpecifiesValueAndChangeEvent_WithoutMatchingProperties/TestComponent.mappings.txt: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_WithGenericChildContent_SetsParameterNameOnComponent/TestComponent.codegen.cs: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_WithGenericChildContent_SetsParameterNameOnComponent/TestComponent.mappings.txt: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventHandler_OnElement_ArbitraryEventName_WithEventArgsMethodGroup/TestComponent.mappings.txt: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToComponent_SpecifiesValueAndChangeEvent_WithoutMatchingProperties/TestComponent.codegen.cs: Filename too long
error: unable to create file src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToComponent_SpecifiesValueAndChangeEvent_WithoutMatchingProperties/TestComponent.mappings.txt: Filename too long
```

### Additional context
See also https://github.com/aspnet/AspNetCore-Tooling/pull/422#issuecomment-482895278 and https://github.com/aspnet/AspNetCore-Tooling/pull/422#issuecomment-482910628 comments.

Thanks @dagood !

**Comment by natemcmaster** [comment] 2019-04-15 16:19
Duplicate of https://github.com/aspnet/AspNetCore/issues/7882?

**Comment by dagood** [comment] 2019-04-15 16:23
Ha, yes.

**Comment by natemcmaster** [comment] 2019-04-15 17:31
Closing in favor of https://github.com/aspnet/AspNetCore/issues/7882.

**Closed by natemcmaster** 2019-04-15 17:31 UTC
Labels: 2 - Working, area-infrastructure, area-mvc, feature-razor

**Comment by dougbu** [comment] 2019-04-15 17:46
72b939d85573

**Comment by pranavkm** [comment] 2019-04-18 01:41
@dougbu done?

**Comment by dougbu** [comment] 2019-04-18 01:45
Yes, done
