### ISSUE TITLE
Endpoint Routing: Find The Matched Route

### ISSUE THREAD

**Issue by mgolois** [aspnet/AspNetCore#17389] opened 2019-11-25 20:19 UTC
@rynowak while upgrading from .net core 2.2 to 3.0 these lines of code are no longer working. Am I missing anything? Perhaps, the way we are doing template matching have surely changed to a pattern matching. Let me know your thoughts:

```
    public RouteEndpoint GetRouteEndpoint(string path)
        {
                      
            var routeEndpoints = _endpointDataSource.Endpoints.Cast<RouteEndpoint>();
          
            var matchedEndpoint = routeEndpoints.Where(e => new TemplateMatcher(
                                                                        TemplateParser.Parse(e.RoutePattern.RawText),
                                                                        new RouteValueDictionary())
                                                                .TryMatch(path, new RouteValueDictionary()))
                                                .OrderBy(c => c.Order)
                                                .FirstOrDefault();            
            return matchedEndpoint;        
        }
```

**Comment by javiercn** [comment] 2019-12-11 11:33
@mgolois thanks for contacting us.

@rynowak thoughts?

**Comment by rynowak** [comment] 2019-12-13 21:57
Looks like a dupe of https://github.com/aspnet/AspNetCore/issues/17391

**Closed** 2019-12-14 22:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-mvc, question
