### ISSUE TITLE
Performance issues with logging component

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#6924] opened 2019-01-22 16:30 UTC
### Describe the bug
If I enable logging, the server performance will drop dramatically even if the logging level was set to 'error'.
You can set the logging level to "none" or other values separately and do request benchmark on each of them, and you will find that the QPS down dramatically if the logging is enabled.

Please improve the performance of the logger, thanks!

The benchmark source can be found here: https://github.com/zeekozhu/iris

ASP.NET Core 2.2.1

**Comment by anurse** [comment] 2019-04-11 00:11
The link you provided appears to be to a server framework written in Go. Can you provide a benchmark that illustrates the performance problem in ASP.NET Core?

**Comment by hez2010** [comment] 2019-04-11 00:16
@anurse benchmarks for asp.net core are placed under _benchmarks directory. 
See: [_benchmarks](https://github.com/ZeekoZhu/iris/tree/master/_benchmarks)

**Comment by anurse** [comment] 2019-04-16 22:55
Turning up the log level has some overhead. Can you provide a simple runnable sample and show the performance difference between the log settings? That will allow us to investigate further.

**Comment by halter73** [comment] 2019-04-16 22:58
I opened https://github.com/aspnet/Benchmarks/issues/889 because we should include scenarios with logging enabled in our automated benchmark runs to check for possible regressions. Logging is an area particularly at risk, because it's possible to write logs in less-than-optimal ways.

**Comment by anurse** [comment] 2019-05-22 20:33
Closing, as the linked Benchmarks issue covers reviewing performance when logging is enabled.

**Closed by anurse** 2019-05-22 20:33 UTC
Labels: area-servers, waiting
