### ISSUE TITLE
How to read .json file in client-side blazor

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10577] opened 2019-05-28 10:16 UTC
### Describe the bug
Thanks in Advance;-). I am using CLDR data .json file for locale support in blazor cliet side. but it does not read the file. Is that any way to read the .json file in blazor client -side?

Can any one please help on this.

### Additional context
i am using VS2019 preview version and .net core 3.0 preview 5.

**Comment by mkArtakMSFT** [comment] 2019-05-28 17:04
Thanks for contacting us, @kmuthukumar23.
How do you try to load the file? Where from? Can you share a repro with what you're trying to do?

**Comment by kmuthukumar23** [comment] 2019-05-28 17:15
Hi,
I am trying to load the file from local disk as well as in blazor proj's content folder....it working perfectly in server side...but in client side it does not work....

**Comment by mkArtakMSFT** [comment] 2019-05-28 17:34
Closing this as a dupe of https://github.com/aspnet/AspNetCore/issues/10552

**Closed by mkArtakMSFT** 2019-05-28 17:34 UTC
Labels: area-blazor, more-info-needed, question
