### ISSUE TITLE
Produce reference assemblies for Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#9479] opened 2019-04-17 21:40 UTC
This issue is a follow-up to https://github.com/aspnet/AspNetCore/issues/3610 for remaining work.

From @natemcmaster :

Work remaining: ensure these requirements are met (they are not currently). This will require a combination of writing tests and changing some MSbuild goop.

* Reference assemblies must not change assembly version in patch updates. They remain constant at "Version=3.0.0.0" for the lifetime of netcoreapp3.0.
* Implementation binaries must satisfy the API surface of the reference assembly
* API breaking changes to any assembly in Microsoft.AspNetCore.App are not allowed after 3.0.0

**Comment by natemcmaster** [comment] 2019-07-22 17:45
@Pilchie this one will definitely affect servicing 3.0.x and would be good to review before RTM.

**Comment by anurse** [comment] 2019-08-05 20:33
> * Reference assemblies must not change assembly version in patch updates. They remain constant at "Version=3.0.0.0" for the lifetime of netcoreapp3.0.

We do this for all assemblies already, so I don't think ref assemblies will need anything special here.

> * Implementation binaries must satisfy the API surface of the reference assembly

Essentially this is saying that the `ref` folder contents for a given branch must not change after the release ship. We could have some automation in place to ensure that.

> * API breaking changes to any assembly in Microsoft.AspNetCore.App are not allowed after 3.0.0

My thinking is that this will fall out of the previous item (ensuring binaries satisify the reference assembly). Even today, API breaking changes show up in code check. We would effectively be forbidding regeneration of ref asms (the current way to "fix" ref asm conflicts).

**Comment by dougbu** [comment] 2019-08-30 17:16
> We could have some automation in place to ensure that.

This part is a dupe of what we do in Code Check as well as #4259.

**Closed by dougbu** 2019-08-30 17:16 UTC
Labels: area-platform
