### ISSUE TITLE
Debugging of Blazor ASP.Net core-hosted apps under Visual Studio becomes painfully slow

### ISSUE THREAD

**Issue by NeilMacMullen** [aspnet/AspNetCore#11136] opened 2019-06-12 12:40 UTC
I have an ASP.NET core hosted Blazor App based on the latest public SDK and latest VS2019.

After a few rounds of debugging (F5 in Visual Studio) the page render time seems to degrade to a crawl and I often get the "localhost is not responding"  or "localhost is not responding due to a long-running script" popup.

This _seems_ to be related to rendering rather than calling server APIs.  For example, I often see debug output such as the following after which there are many seconds (sometimes minutes) of inactivity apart from notification of thread exits before the page renders.  It seems that after some number of cycles, restarting Edge and/or VS is not enough to recover performance and a full machine reboot is required.

> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:61456/api/SampleData/Infos  
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'SensizeDashboard.Server.Controllers.SampleDataController.Infos (SensizeDashboard.Server)'
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "Infos", controller = "SampleData"}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[Dtos_std.Api.Private.NewInfoResultDto]] Infos() on controller SensizeDashboard.Server.Controllers.SampleDataController (SensizeDashboard.Server).
> Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Information: Executing ObjectResult, writing value of type 'Dtos_std.Api.Private.NewInfoResultDto[]'.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action SensizeDashboard.Server.Controllers.SampleDataController.Infos (SensizeDashboard.Server) in 17.3045ms
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'SensizeDashboard.Server.Controllers.SampleDataController.Infos (SensizeDashboard.Server)'
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 29.1463ms 200 application/json; charset=utf-8
> The thread 0x36e4 has exited with code 0 (0x0).

**Comment by SteveSandersonMS** [comment] 2019-06-12 16:20
This isn't something I've experienced. Do you have any repro steps? For example, if you had to reproduce the issue on a new machine without access to any of your existing source code, what code would you add to the default template and what actions in VS would be sufficient to trigger this problem?

**Comment by NeilMacMullen** [comment] 2019-06-12 16:25
Thanks Steve, knowing that it's not 'expected' with the current state of the tooling is helpful.    I have a suspicion that using LINQ expressions in the razor may be what exacerbates the problem.   Another possibility might be that I'm using the OzCode debugging extension  but I'll try to narrow it down.

**Comment by NeilMacMullen** [comment] 2019-06-12 16:58
Ok - here's a fairly easy and reliable (for me) way to reproduce the problem...

- Create a new "ASP Core-hosted" application (the one with the sample weather forecasts on the "FetchData" page)
- In the "WeatherForecasts" action, bump the number of forecasts up to 500
- In the FetchData razor page, change OnInitAsync to read..

` var f  = await Http.GetJsonAsync<WeatherForecast[]>("api/SampleData/WeatherForecasts");
        forecasts = f.Where(fc => fc.TemperatureC > 5).ToArray();`
- Hit F5 in Visual Studio to debug
- Click on the FetchData link
- The page will probably render ok but if you then press F5/Refresh in the browser, things will quickly degrade.  You will most likely see the entire page hang at "Loading...." in index.html but after a few cycles you will probably also see it hang after starting to render the Weather Forecast page and after fetching the data.  If you wait longer (many seconds) it may complete and render the table.

**Comment by SteveSandersonMS** [comment] 2019-12-16 13:08
Sorry, I've not been able to repro this problem. I followed the steps given, and refreshed the page around 30 times, and the loading/rendering time didn't change. It continued to load and render quickly, without any trouble.

I know it's been a while since this was reported, so maybe something was fixed in the tooling in the meantime.

**Closed** 2019-12-16 13:08 UTC
Labels: area-blazor, blazor-wasm, closed: no-repro

**Comment by NeilMacMullen** [comment] 2019-12-16 13:11
Thanks for following up on this Steve.  To be honest I had forgotten about it myself.  I haven't seen similar behaviour in the latest tooling.  FWIW it seemed to be related to LINQ but I'm using that a lot in my latest projects and it no longer seems to be an issue.

**Comment by SteveSandersonMS** [comment] 2019-12-16 13:11
Excellent - thanks for confirming!
