### ISSUE TITLE
Firing onchange before painting on input

### ISSUE THREAD

**Issue by montyclt** [aspnet/AspNetCore#5544] opened 2018-07-01 11:47 UTC
Hello everyone,

I have an input that I need that the user only writes in upper case.

I tried to do the following:

```
<input value="@Name" onchange="@ChangeName" />
```

```
void ChangeName(UIChangeEventArgs e)
{
    var value = (string)e.Value;

    Name = value.ToUpper();
}
```

The result:

The user writes in lowercase and when the user left focus, then the content transform to upper.

I tried too a hardcode value of Name property and left ChangeName method in blank like this:

```
<input class="form-control" value="@Name"/>
```

```
string Name = "Foo";

void ChangeName(UIChangeEventArgs e)
{
    // 
} 
```

I expected the original value of input return to "Foo", but when I leave the focus, the changed value stayed in the input.

Is possible make the value of input doesn't change if the value of `value` property doesn't change even if user type letters? (like `readonly` property)

Is possible to fire the onchange method before painting the input value to get in the input the value directly transformed while writing instead on lose focus? (like ReactJS)

**Comment by ag-petrov** [comment] 2019-02-06 15:04
Having information about the caret position is a must when creating editor components. Any update on this? 

Additionally is there any conception for cancellable events. For example I want to cancel the keypress event of an input element. Do I need to use JavaScript interoperability?

**Comment by SteveSandersonMS** [comment] 2019-03-05 14:40
Closing as a duplicate of #5545

The original requirement (text input, into which the all input is forced into uppercase) is handed quite easily using `style="text-transform: uppercase"` so it's presented in uppercase while typing, and then any other technique you like to convert the underlying `string` to uppercase before you use it. Example:

```
<input bind="@UserValue" style="text-transform: uppercase" />

You typed: @UserValue

@functions {
    string _userValue;
    public string UserValue
    {
        get => _userValue;
        set { _userValue = value.ToUpper(); }
    }
}
```

**Closed by SteveSandersonMS** 2019-03-05 14:40 UTC
Labels: area-mvc, feature-Components

**Comment by SteveSandersonMS** [comment] 2019-03-05 14:42
> For example I want to cancel the keypress event of an input element. Do I need to use JavaScript interoperability?

In general, yes. Since this has to be async, you can't use .NET code for that. Our hope is that this is a sufficiently rare case that it's not going to impact productivity much, and if there are scenarios that are common enough, we can come up with suitable helpers for it.
