### ISSUE TITLE
Test failure: _3_Build

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3741] opened 2018-10-29 12:51 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) with the following error:

```
System.InvalidOperationException : Command dotnet restore /warnaserror --no-cache --source https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181029-01/final/index.json --source https://api.nuget.org/v3/index.json  returned exit code 1

  Restoring packages for /Users/vsts/agent/2.141.1/work/_temp/tmpEQ43XF.tmp/razorclasslib/EnvironmentVariableAndNuGetOrg/none/razorclasslib.csproj...
  Installing runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0.
  Installing System.Globalization.Extensions 4.3.0.
  Installing System.Security.Cryptography.Cng 4.4.0.
  Installing System.Numerics.Vectors 4.4.0.
  Installing runtime.native.System 4.0.0.
  Installing System.Runtime.Handles 4.0.1.
  Installing NETStandard.Library 2.0.3.
  Installing Microsoft.AspNetCore.Mvc 2.2.0-rtm-35586.
  Installing Microsoft.NETCore.Platforms 1.1.0.
  Installing Microsoft.AspNetCore.Mvc.Analyzers 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.DependencyInjection 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Razor.Design 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.Caching.Memory 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.ApiExplorer 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Cors 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Formatters.Json 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.DataAnnotations 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.ViewFeatures 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Razor.Extensions 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Localization 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.TagHelpers 2.2.0-rtm-35586.
  Installing System.Reflection.Emit.Lightweight 4.0.1.
  Installing Microsoft.AspNetCore.Mvc.RazorPages 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.Caching.Abstractions 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.Options 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Core 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Cors 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.JsonPatch 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.Localization 2.2.0-rtm-35586.
  Installing System.ComponentModel.Annotations 4.5.0.
  Installing Microsoft.AspNetCore.Diagnostics.Abstractions 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Html.Abstractions 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.WebEncoders 2.2.0-rtm-35586.
  Installing Newtonsoft.Json.Bson 1.0.1.
  Installing Microsoft.AspNetCore.Razor.Language 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Antiforgery 2.2.0-rtm-35586.
  Installing Microsoft.CodeAnalysis.Razor 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Localization 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Razor 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.FileSystemGlobbing 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Razor.Runtime 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Rou
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-10-29 12:51
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-29 12:52
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 165 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) on release/2.2 at 12:38:50 PM:
- _1_Restore
- _3_Build
- _4_BuildIncremental
- _3_Build
- _4_BuildIncremental
- _3_Build
- _2_RestoreIncremental
- _6_Publish
- _1_Restore
- _3_Build
- (And 155 more test failures in this build)

**Comment by natemcmaster** [comment] 2018-10-29 15:50
Duplicate of https://github.com/aspnet/AspNetCore/issues/3686

**Closed by natemcmaster** 2018-10-29 15:50 UTC
Labels: Branch:release/2.2, test-failure
