### ISSUE TITLE
Generated __MyComponent class mismatch with 'this' keyword

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#5514] opened 2018-05-02 09:43 UTC
Consider the following senario:

#### _MyComponent.cshtml_
```xml
<div> My component </div>
@functions{
    
         public void override OnInit()
         {
                 MyHelperClass.InitMyComponent(this);
         }
}

```

#### _MyHelperClass.cs_
```csharp
public static class MyHelperClass
{
         public static void InitMyComponent(MyComponent myComponent)
         {
                   // do stuff here
         }
}
```

This code will not compile because, the keyword `this `is referencing the `__MyComponent `generated class. Any workarounds or fixes ?

**Comment by mkArtakMSFT** [comment] 2019-03-09 00:12
@rynowak, anything we should do here in preview5 specifically, or should this be moved further?

**Comment by mkArtakMSFT** [comment] 2019-05-17 17:30
This is a dupe of #5487

**Closed by mkArtakMSFT** 2019-05-17 17:30 UTC
Labels: 1 - Ready, PRI: 1 - Required, area-blazor, bug
