### ISSUE TITLE
Preview 3: The Module DLL 'aspnetcorev2.dll' could not be loaded due to a configuration problem

### ISSUE THREAD

**Issue by matbech** [aspnet/AspNetCore#8249] opened 2019-03-06 21:02 UTC
### Describe the bug
I have upgraded (uninstalled Preview 2, followed by install of Preview 3) the .net core hosting bundle to version 3.0 Preview 3. I get the following error when the IIS service is started:

The Module DLL 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll' could not be loaded due to a configuration problem. The current configuration only supports loading images built for a AMD64 processor architecture.

I was reading the release notes of Preview 3 and I could not find any breaking changes. I was expecting that the upgrade from Preview 2 to Preview 3 doesn't require any manual fixing on my side. Downgrading to Preview 2 solves the problem.

### To Reproduce
Install 3.0 Preview 3

### Expected behavior
No error

**Comment by jkotalik** [comment] 2019-03-06 21:54
Yeah you are correct. Looks like the x86 version got added to both Program Files and ProgramFiles x86. 

Between preview2 and preview3, there weren't many changes to ANCM, so if you need an immediate work around, try to install just the runtimes alone without the hosting bundle. We will look into why this happened and if we can ship a fix.

**Comment by cole-acepph** [comment] 2019-03-07 01:07
Hi, this same thing just happened to me, I was moving from `dotnet-hosting-3.0.0-preview-19075-0444-win` to `dotnet-hosting-3.0.0-preview3-19153-02-win`, using Windows Server 2012 R2 and IIS 8.
This is the way I solved this: 

I uninstalled `dotnet-hosting-3.0.0-preview3-19153-02-win` and then installed back `dotnet-hosting-3.0.0-preview-19075-0444-win`, copied `C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll` and `C:\Program Files (x86)\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll` into a separated folder to keep these, then uninstalled `dotnet-hosting-3.0.0-preview-19075-0444-win` and installed back `dotnet-hosting-3.0.0-preview3-19153-02-win`, and finally proceeded to overwrite these same `aspnetcorev2.dll` files with the ones I saved previously. So far it seems to be working as before.

The only question that I have now is:

- Is this too harsh/raw way to do it? Maybe I'm missing something here.
- Will I have this same issue in the future? Do you guys recommend me a better Server/IIS configuration for the upcoming .NET Core 3?

Thanks in advance.

**Comment by jkotalik** [comment] 2019-03-07 01:21
Hey @cole-acepph , again apologize for the way you had to work around it. What you did does work

- Is this too harsh/raw way to do it? Maybe I'm missing something here.

I'm think you may have issues with uninstall. Can you try to uninstall the `dotnet-hosting-3.0.0-preview3-19153-02-win` bundle and see if the aspnetcore dlls are still present?

You won't have this issue in the future. The regression was due to a lot of build infrastructure changes did between preview2 and preview3.

I'll update this issue if we do a respin of the hosting bundle for preview3. We will keep you updated.

**Comment by ghd258** [comment] 2019-03-07 01:35
什么时间能解决这个我问题呢 搞的iis程序池无法启动了

**Comment by jkotalik** [comment] 2019-03-07 01:37
@ghd258 as soon as possible.

**Comment by chrdlx** [comment] 2019-03-10 13:15
Hello!, I don't know if this is related because you are talking about the Preview 3 but I have this issue

https://github.com/aspnet/AspNetCore/issues/8378

In my case it happens with the previous Hosting Preview 2 version.
Regards!

**Comment by anurse** [comment] 2019-03-19 21:53
Dupe of https://github.com/aspnet/AspNetCore/issues/8378

**Closed by anurse** 2019-03-19 21:53 UTC
Labels: area-servers, servers-iis
