### ISSUE TITLE
[Blazor server-side] JSRuntime doesn't work properly

### ISSUE THREAD

**Issue by aybelanov** [aspnet/AspNetCore#11595] opened 2019-06-26 14:49 UTC
VS 2019 16.2.0 Preview 3
netcoreapp3.0 preview 6

### Describe the bug
I have  the follow code in a razor page:
```
public string Response { get; set; }

protected override async Task OnAfterRenderAsync()
{          
	if (!isPageLoaded)
	{
		try
		{
			_ = await js.InvokeAsync<object>("GoogleCaptcha.Set", DotNetObjectRef.Create(this), prms.Id, prms.SiteKey, prms.Theme, prms.ScriptSource);
			await base.OnAfterRenderAsync();
			isPageLoaded = true;
		}
		catch { }
	}
}

[JSInvokable]
public void SetCaptchaResponse(string response)
{
	Response = response;
}
```

I have the follow javascript code for interop:

```
window.GoogleCaptcha = {

    Set: function (dotnetHelper, id, siteKey, theme, src) {

        window.gcOnloadCallback = function () {
            grecaptcha.render(id, {
                'callback': reCaptchaCallback,
                'sitekey': siteKey,
                'theme': theme
            });
        };

        var reCaptchaCallback = function (response) {
            dotnetHelper.invokeMethodAsync('SetCaptchaResponse', response);
        };

        var script = document.createElement('script');
        script.src = src;
        script.async = true;
        script.type = 'text/javascript';
        var container = this.document.getElementById(id);
        container.parentNode.insertBefore(script, container.nextSibling);
    }
}
```
It works properly until the page is full updated with F5 key or with address string. Then I have follow errors

> Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer: Warning: Unhandled exception rendering component: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.
> 
> System.InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.
>    at Microsoft.JSInterop.DotNetObjectRefManager.get_Current()
>    at Microsoft.JSInterop.DotNetObjectRef`1..ctor(TValue value)
>    at Microsoft.JSInterop.DotNetObjectRef.Create[TValue](TValue value)
>    at WebApplication2.Shared.Recaptcha.OnAfterRenderAsync() in Z:\dev\source\repos\WebApplication2\WebApplication2\Shared\Recaptcha.cs:line 65
> Microsoft.AspNetCore.Components.Server.ComponentHub: Warning: Unhandled Server-Side exception
> 
> System.AggregateException: One or more errors occurred. (JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.) ---> System.InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.
>    at Microsoft.JSInterop.DotNetObjectRefManager.get_Current()
>    at Microsoft.JSInterop.DotNetObjectRef`1..ctor(TValue value)
>    at Microsoft.JSInterop.DotNetObjectRef.Create[TValue](TValue value)
>    at WebApplication2.Shared.Recaptcha.OnAfterRenderAsync() in Z:\dev\source\repos\WebApplication2\WebApplication2\Shared\Recaptcha.cs:line 65
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.
>    at Microsoft.JSInterop.DotNetObjectRefManager.get_Current()
>    at Microsoft.JSInterop.DotNetObjectRef`1..ctor(TValue value)
>    at Microsoft.JSInterop.DotNetObjectRef.Create[TValue](TValue value)
>    at WebApplication2.Shared.Recaptcha.OnAfterRenderAsync() in Z:\dev\source\repos\WebApplication2\WebApplication2\Shared\Recaptcha.cs:line 65<---
> 
> [2019-06-26T14:17:14.850Z] Error: System.AggregateException: One or more errors occurred. (JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.) ---> System.InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.
>    at Microsoft.JSInterop.DotNetObjectRefManager.get_Current()
>    at Microsoft.JSInterop.DotNetObjectRef`1..ctor(TValue value)
>    at Microsoft.JSInterop.DotNetObjectRef.Create[TValue](TValue value)
>    at WebApplication2.Shared.Recaptcha.OnAfterRenderAsync() in Z:\dev\source\repos\WebApplication2\WebApplication2\Shared\Recaptcha.cs:line 65
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.
>    at Microsoft.JSInterop.DotNetObjectRefManager.get_Current()
>    at Microsoft.JSInterop.DotNetObjectRef`1..ctor(TValue value)
>    at Microsoft.JSInterop.DotNetObjectRef.Create[TValue](TValue value)
>    at WebApplication2.Shared.Recaptcha.OnAfterRenderAsync() in Z:\dev\source\repos\WebApplication2\WebApplication2\Shared\Recaptcha.cs:line 65<---
> 
> [2019-06-26T14:17:14.852Z] Information: Connection disconnected.
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor'
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 448.50390000000004ms 101

**Comment by mkArtakMSFT** [comment] 2019-06-26 16:19
Thanks for contacting us, @aybelanov.
We'll try to get this as soon as we can.

**Comment by tiwj** [comment] 2019-07-03 14:53
I can confirm the same issue. 

Seems like navigating with either F5 or via address issues a new instance of JSRuntime, whilst simple back/forward/link navigation does not (HashCode of JSRuntime stays the same). 

Anyways, the whole blazor connection seems to be resetted. This is probably intended, but something is messed up with subsequent connections from the same browser window (latest Chrome for me).

**Comment by Joe4evr** [comment] 2019-07-05 12:00
I have the same issue but even on initial page load.

**Comment by MarcelJoestingmeier** [comment] 2019-07-08 08:33
@Joe4evr Where did you put your call? Did you notice, that you cannot use it while prerendering? There is a way to check that, documented at https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0

**Comment by mkArtakMSFT** [comment] 2019-07-17 16:56
Thanks for contacting us, @aybelanov.
Looks like this is a duplicate of https://github.com/aspnet/AspNetCore/issues/11159

**Closed by mkArtakMSFT** 2019-07-17 16:56 UTC
Labels: area-blazor, duplicate, investigate
