### ISSUE TITLE
Consider adding a way to use strict comparison for routes matching

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2667] opened 2018-01-02 02:02 UTC
_From @Eilon on Monday, February 6, 2017 12:52:41 PM_

_From @PinpointTownes on February 6, 2017 4:3_

http://stackoverflow.com/questions/42048770/asp-net-core-openiddict-throws-an-openid-connect-response-cannot-be-returned-fr

Consider this action:

```csharp
[HttpPost("~/path")]
public IActionResult Test() => Empty();
```

Oddly, either the routing stack or MVC seems to consider `/path/` requests as valid candidates for this route/action, which is incorrect as `/path` and `/path/` are two different addresses.

Is there any particular reason for this (abusive) normalization?

/cc @Eilon @rynowak 

_Copied from original issue: aspnet/Mvc#5757_

_Copied from original issue: aspnet/Routing#380_

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @Eilon on Monday, February 6, 2017 12:52:42 PM_

_From @PinpointTownes on February 6, 2017 7:31_

> Is there any particular reason for this (abusive) normalization?

After some research, it looks like it matches what ASP.NET MVC and Web API used to do (but not WCF Web API, AFAICT), so I guess it's one of those "by design" decisions.

Unfortunately, this behavior makes the routing stack pretty much inconsistent with the rest of ASP.NET Core, where path comparisons take the trailing slash into account (e.g all the security middleware).

Since changing this behavior at this point is very unlikely, would you consider adding new semantics to enable strict comparisons? E.g:

```csharp
[HttpPost("~/path", StrictMatching = true)]
public IActionResult Test() => Empty();
```

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @Eilon on Monday, February 6, 2017 12:55:52 PM_

@PinpointTownes the reason right now is historical: ASP.NET's Routing always ignored trailing slashes. But then the historical reason is that we found for almost all cases where Routing is used, the difference is insignificant.

Having said that, I fully agree that the two URLs are different - then again, URLs that vary by case are different as well, yet Routing is case-insensitive. And then there's all the crazy path normalization stuff that various layers in the system perform, such as URL-decoding segments, collapsing multiple `/` into a single `/`, etc. You know, by the time the URL makes its way from the browser to the user's app code, it looks nothing alike! 😄 

Ok, ok, ok, yes, the feature you suggest is reasonable. It's probably more specifically in this case something like `MatchTrailingSlash = true` or something because it isn't clear what "strict" means here.

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @rynowak on Tuesday, February 7, 2017 12:25:08 PM_

> then again, URLs that vary by case are different as well, yet Routing is case-insensitive

IMO this is crazy. Yeah I know that I'm not helping 😆 

=======

I'd personally love for us to morph routing into something that isn't just the strict set of compatibility requirements that MVC has always had.

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @Eilon on Tuesday, February 7, 2017 1:38:35 PM_

While we're at it, let's abolish the concept of casing in languages! What purpose does casing really serve?? :trollface:

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @PinpointTownes on Saturday, February 11, 2017 3:19:21 AM_

Sorry for the late reply :sweat_smile: 

> Having said that, I fully agree that the two URLs are different - then again, URLs that vary by case are different as well, yet Routing is case-insensitive.

True, but the big "problem" with how trailing slashes are handled is that there's no consistency across the stack, which led to the bug reported in the SO question: `PathString.Equals` uses the case-insensitive ordinal comparer by default - which matches what Routing does - but considers `/path` and `/path/` as different paths while Routing treats `/path`, `/path/`, `/PATH` and `/PATH/` like identical route templates.

Actually, I guess the discussion shouldn't be limited to Routing, as it's a broader design decision, that would also impact HTTP abstractions primitives like `PathString`.

> It's probably more specifically in this case something like MatchTrailingSlash = true or something because it isn't clear what "strict" means here.

Yeah, it's clearer (`StrictMatching` was generic enough to include both trailing slash and casing, but it's probably better to separate the two).

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @Eilon on Sunday, February 12, 2017 9:54:37 PM_

@PinpointTownes yup, understood.

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @rclabo on Tuesday, March 21, 2017 2:39:56 PM_

The situation where /path and /path/ are considered the same by the Asp.Net Core route engine is also problematic from and SEO perspective.  Google considers these two different end points (which of course they are) and if they return the same content Google will considers this a "Duplicate Content" issue and will reduced the ranking of these pages in the search results (which as you can imagine has financial consequences for companies).

If an attribute based route is specified as [Route("/example/")] then there needs to be some way to indicate that only /example/ should match it;  Not /example and not /Example/  but only /example/  .

I can work around the case insensitivity issue by using middleware to force all paths to lower case by issuing a 301 redirect for non conforming paths to force them to be all lowercase.  But I'm stumped on how to force /example to not match an attribute based route of [Route("/example/")].  Is there a workaround?

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @Eilon on Tuesday, March 21, 2017 4:38:21 PM_

@rclabo yup, that's something we'd want to consider here for sure.

**Comment by aspnet-hello** [comment] 2018-01-02 02:02
_From @rclabo on Monday, April 3, 2017 6:31:35 AM_

I wrote up the duplicate content issue and a workaround here: http://stackoverflow.com/questions/42929370/how-to-require-directory-trailing-slash-when-using-asp-net-core-attribute-based

**Comment by mkArtakMSFT** [comment] 2018-10-22 22:07
Closing this as a dupe of https://github.com/aspnet/Routing/issues/380

**Closed by mkArtakMSFT** 2018-10-22 22:07 UTC
Labels: enhancement, repo:Routing

**Comment by poke** [comment] 2018-10-22 22:13
@mkArtakMSFT Any chance you could unlock that issue again? It was locked by the bot as part of being moved here but later reopened but never unlocked.

**Comment by Eilon** [comment] 2018-10-22 22:15
Done
