### ISSUE TITLE
ASP.NET Core Scaffolding BUG

### ISSUE THREAD

**Issue by dreamdocker** [aspnet/AspNetCore#14881] opened 2019-10-10 08:53 UTC
Windows 10 + Visual studio 2019  Enterprise + .NET Core 3.0

Create ASP.NET Core MVC project based on .NET Core 3.0, create a directory named [Pages] in the root directory of this MVC project. After the above conditions are met, right click [Add] in any folder of MVC [Views] - ->[View], an error is reported.

After deleting the [Pages] folder, continue the above operation and everything is normal.

Why can't I create a view after having a [Pages] folder?

**Comment by javiercn** [comment] 2019-10-10 09:25
@dreamdocker Thanks for contacting us.

@vijayrkn This seems to be a scaffolding issue. Can you get someone to look at it?

**Comment by javiercn** [comment] 2019-10-10 09:26
Closing this as a dupe of https://github.com/aspnet/AspNetCore/issues/14883 which has more details in it.

**Closed by javiercn** 2019-10-10 09:26 UTC
Labels: external
