### ISSUE TITLE
Writing is not allowed after writer was completed.

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore#13847] opened 2019-09-10 08:43 UTC
### Describe the bug
My ASP.Net Core 2.2.6 is running on kubernetes cluster deployed on EKS. The following exception is logged by Fluentd and shows up in Kibana:
```
"exceptions": [
      {
        "Depth": 0,
        "ClassName": "System.InvalidOperationException",
        "Message": "Writing is not allowed after writer was completed.",
        "Source": "System.IO.Pipelines",
        "StackTraceString": "   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()\n   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)\n   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)\n   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)\n   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "HResult": -2146233079,
        "HelpURL": null
      }
    ]
```

### To Reproduce
1. Using this version of ASP.NET Core '...' 2.2.6
2. Run this code '....'
3. With these arguments '....'
### Expected behavior
No such exception
### Additional context
Include the output of `dotnet --info`
```
# dotnet --info

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by BrennanConroy** [comment] 2019-09-10 15:44
This is fixed in 3.0
Dupe of https://github.com/aspnet/AspNetCore/issues/11219

**Closed by BrennanConroy** 2019-09-10 15:44 UTC
Labels: area-signalr
