### ISSUE TITLE
Add Tests and Docs: Razor Components Server Routes

### ISSUE THREAD

**Issue by jbomhold3** [aspnet/AspNetCore#7009] opened 2019-01-25 02:32 UTC
I'm working on porting a project over to Razor Components. However, I have noticed something that could easily be fixed if we had the option to pick the route the Components boot on, on the server.  Would look something like this in a idea world.

app.UseRazorComponents<App.Startup>(o => o.route "/app1");

What my end goal is to be able to boot app1 and app2, ext on the same server. Without having to have two completely separate servers to do so.

**Comment by mkArtakMSFT** [comment] 2019-01-25 18:54
Thanks for your suggestion, @jbomhold3.
@danroth27 any thoughts?

**Comment by dodyg** [comment] 2019-02-23 05:52
This would be amazing. Then we can have scenario such as 

Support.App will go to /support
Main.App will go to /
Admin.App will go to /Admin

**Comment by rynowak** [comment] 2019-02-23 21:03
@javiercn - is this covered in the work you've done so far or requires additional features to do? If this is already possible can we add a functional test and add to docs?

**Comment by javiercn** [comment] 2019-02-25 12:00
@rynowak Yeah, this should be able with the new design.

`app.UseRouting(routes => routes.MapComponentsHub<App>(selector: "app", path: "/app1")` i believe was the overload.

**Comment by jbomhold3** [comment] 2019-03-07 17:35
Overload produces a Connection ID required in Preview 3. Is this not functioning yet?

**Comment by LorenDorez** [comment] 2019-03-08 03:15
@rynowak @javiercn The issue is the components.server.js is hardcoded with the _blazor for the hub.
https://github.com/aspnet/AspNetCore/blob/master/src/Components/Browser.JS/src/Boot.Server.ts#L46

Also thhis Url and the one for the boot.json should be Root-Relative URLs

**Comment by jbomhold3** [comment] 2019-03-08 05:05
Was a user error but I did have to follow @LorenDorez  advise and copy and edit the js file for the hub name ... https://github.com/jbomhold3/workingsplitproject

**Comment by javiercn** [comment] 2019-03-08 12:32
Fair enough. We need to allow configuring that

**Comment by javiercn** [comment] 2019-03-08 12:41
@SteveSandersonMS How do you feel about creating a component/taghelper to render the script tag into the page and provide options? Either that or a component/taghelper that puts the components options in a place where we can find them. Something like
```razor
<ComponentScript HubAddress"/path"></ComponentScript>
```
or
```razor
<ComponentOptions HubAddress="/path"></ComponentOptions>
```

You would replace the script tag with the component/taghelper on the first one and it would produce a script tag with some data-* attributes assigned to it".

You would put the second one inside the `head` tag in your app and would produce one or more meta tags with the configuration options. Then you would put the script tag wherever you choose as normal.

When the components.server.js tag boots up, it will query the dom for the options and use them during the boot process (or use default values if not found).

**Comment by SteveSandersonMS** [comment] 2019-03-08 12:59
I don't quite yet understand the requirement.

You can already connect to different Websocket endpoints by changing the `<base href>` in the page. The only thing about that which is fixed is that the path has to end with `/_blazor` [1], but you can have other custom stuff in the path before that. What are the scenarios where this is insufficient?

[1] The default name for that will change at some point.

> Also thhis Url and the one for the boot.json should be Root-Relative URLs

They are base-relative URLs. They shouldn't be root-relative. The base href already controls the mapping from base-relative to root-relative.

**Comment by SteveSandersonMS** [comment] 2019-03-08 13:01
BTW if the idea is to open multiple concurrent connections to different Razor Components endpoints from within the same page, this isn't something we've ever supported, and may require quite a lot more changes besides controlling the target endpoint. Lots of things, such as the client-side router, rely on the idea that there is exactly one base href and they get to control the URL space. This is common to most SPA frameworks.

**Comment by javiercn** [comment] 2019-03-08 13:03
@SteveSandersonMS Fair enough, I didn't think about the base path as a factor. You are totally right, this is just a matter of aligning your base path with whatever you set up in MapComponentsHub

**Comment by SteveSandersonMS** [comment] 2019-03-08 13:06
OK, I'm going to close this as there's nothing further to be done. If the docs are insufficient, please file an issue or PR on https://github.com/aspnet/docs/

**Closed by SteveSandersonMS** 2019-03-08 13:06 UTC
Labels: area-mvc, feature-Components

**Comment by jbomhold3** [comment] 2019-03-08 14:37
@SteveSandersonMS  The Idea isn't to open multi end points to the same page. It's to have different apps,on different routes using the same server. IG what I have here https://github.com/jbomhold3/workingsplitproject and it does work.  While I have no issue with doing                routes.MapComponentHub<App2.App2>("app", "/app2/_blazor"); to make the script work as is.  If your going to give a overload that allows you to name the end point hub. Then we should have something in the java that allows us to set the endpoint name as well. @LorenDorez and my use case on this does not align.

**Comment by LorenDorez** [comment] 2019-03-08 14:46
@SteveSandersonMS The issue is that base path is not used for the Hub Connection on the JS file. So either this needs to be allowed to customize or the overload on the server side MapComponentsHub needs to be removed. I just tested with  fresh project and when i set my `MapComponentHub("app","app1")` i get a SingalRHub at "/app1" however the JS cant connect because its trying to connect to "'_blazor".

I ask for it to be atleast considered to allow us to customize the JS side.

**Comment by SteveSandersonMS** [comment] 2019-03-08 14:48
You already can do that by having different base href values on different pages.

**Comment by LorenDorez** [comment] 2019-03-08 15:17
Yes but when it created the HUB it doesnt append '_blazor' if we overload the MapCompoenentHub it simply overwrites. so if i do `MapComponentHub("app","app1")` it will do `routes.MapHub<ComponentHub>("app1").AddComponent(componentType, selector);' This should be **app1/_blazor**. it would then need to append the value from `ComponentHub.DefaultPath`

**Comment by LorenDorez** [comment] 2019-03-08 15:45
Here is a sample app where i set the base path, updated iis express to launch on base path and all work expect it dies trying to connect to a signalr hub at "app1/_blazor"

https://github.com/LorenDorez/EatSleepBlazorRepeat/tree/master/RCApp

**Comment by dodyg** [comment] 2019-03-17 11:52
@LorenDorez  do you manage to get this working ? I can't get this working

```
   routes.MapComponentHub<App2.Components.App>("app", "/application2");
```
             
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Multiple Apps</title>
    <base href="/application2/" />
</head>
<body>
    <app></app>
    <script src="_framework/components.server.js"></script>
</body>
</html>

**Comment by dodyg** [comment] 2019-03-17 12:22
> @SteveSandersonMS Fair enough, I didn't think about the base path as a factor. You are totally right, this is just a matter of aligning your base path with whatever you set up in MapComponentsHub

@javiercn This doesn't seem to be the case. I can't get the simplest sample to work.

**Comment by javiercn** [comment] 2019-03-18 08:44
@SteveSandersonMS Do we have an E2E test for this? Feels like we should and we can just point people there for a sample.

**Comment by SteveSandersonMS** [comment] 2019-03-18 15:21
@javiercn Yes, our E2E test app is hosted on a non-root URL for this exact reason.

**Comment by LorenDorez** [comment] 2019-03-18 15:53
@dodyg Yes i got this to work on the base path. Make sure you also update your LaunchSettings.json to launch your app with the new endpoint

**Comment by dodyg** [comment] 2019-03-18 18:31
@LorenDorez I can't make it work with Kestrel at  ```http://localhost:51997/application2```. 

I got JS error `Uncaught SyntaxError: Unexpected token <`  at `http://localhost:51997/application2/_framework/components.server.js`

```
        public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UsePathBase("/application2");
            app.UseRouting(routes =>
            {
                routes.MapComponentHub<App2.Components.App>("app", "application2");
                routes.MapRazorPages();
            });
        }
```

```
@page "{*clientPath}"
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Multiple Apps</title>
    <base href="/application2/" />
</head>
<body>
    <app></app>

    <script src="_framework/components.server.js"></script>
</body>
</html>
```

**Comment by LorenDorez** [comment] 2019-03-18 19:04
@Dodyg did you update your launch settings for Kestrel? so that it knows you want to put on the directory?

**Comment by dodyg** [comment] 2019-03-18 19:28
Kestrel does not allow using path base in launchSetting.json. It must be set via code `    app.UsePathBase("/application2");`
