### ISSUE TITLE
JSON object string problem in cookie storage

### ISSUE THREAD

**Issue by s952787097** [aspnet/AspNetCore#5685] opened 2018-12-18 02:30 UTC
asp.net core version 2.1

Why is the JSON object string stored in cookie encoded by URLEncode by default? Can I change it?

this is under asp.net core
![_20181218095906](https://user-images.githubusercontent.com/26595017/50127543-8f1a3280-02ac-11e9-89ff-5889346af2db.png)

this is under asp.net MVC
![_20181218100046](https://user-images.githubusercontent.com/26595017/50127546-93465000-02ac-11e9-9793-b21684b28837.png)

the cookie is share

**Comment by Eilon** [comment] 2018-12-18 22:39
Can you show what code you are using to store this value?

**Comment by Eilon** [comment] 2018-12-19 18:46
@Tratcher - any idea on this?

**Comment by Tratcher** [comment] 2018-12-19 22:16
JSON isn't a valid format for cookies. E.g. comma is explicitly prohibited.
https://tools.ietf.org/html/rfc6265#section-4.1.1
```
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
```
Cookies.Append uses a conservative encoding (Uri.EscapeDataString) that also covers curly brackets, semicolon, etc..

**Comment by s952787097** [comment] 2018-12-21 02:44
@Tratcher  

Does that mean that the Cookie storage of asp.net MVC5 does not refer to the specification, while asp.net core refers to the specification?

**Comment by Tratcher** [comment] 2018-12-21 05:08
You can put almost whatever you want into headers, but other components will have trouble parsing it.

**Comment by Eilon** [comment] 2018-12-28 21:40
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Closed by Eilon** 2018-12-28 21:40 UTC
