### ISSUE TITLE
Blazor - Configuration Must Be Provided to Debug

### ISSUE THREAD

**Issue by djbreen7** [aspnet/AspNetCore#12779] opened 2019-07-31 21:28 UTC
### Describe the bug
`dotnet run` [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21) states that it will default the configuration to Debug but requires configuration flag to be passed to debug Blazor, e.g., `dotnet run -c Debug`. I have not tested other dotnet projects, so it could be applicable to all of dotnet core.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview7-012821'
1. Run these commands
    - `dotnet new blazor`
    - `dotnet run`
1. Open Chrome
1. Load app at `http://localhost:5000`
1. Press `SHIFT`+`ALT`+`D` with focus on the application
1. `Inspect` > `Console` tab.
1. See error `Cannot start debugging, because the application was not compiled with debugging enabled`

### Expected behavior
- The debugging tab should open, or in the case remote-debugging is not enabled, a tab should open with instructions on running Chrome with remote-debugging enabled (shows the `"%programfiles(x86)%\Google\Chrome\Application\chrome.exe" –remote-debugging-port=9222 http://localhost:5000/` command).

### Screenshots

Error:  
![Error Message](https://user-images.githubusercontent.com/1622880/62246143-9fe56780-b3a8-11e9-8a8e-4890accef5a0.PNG)  
---
Tabs:  
![Tab](https://user-images.githubusercontent.com/1622880/62246148-a2e05800-b3a8-11e9-9a56-13c937ae404e.PNG)

### Additional context
Reported here based on suggestion from https://github.com/aspnet/AspNetCore.Docs/issues/13548

Track with https://github.com/aspnet/AspNetCore.Docs/pull/13594 for documentation updates based on decision from engineering

**Comment by guardrex** [comment] 2019-08-01 17:29
Commenting here so that I get an explicit ping from GH to revert the doc update when this is resolved.

**Comment by mkArtakMSFT** [comment] 2019-08-02 16:32
Thanks for contacting us, @djbreen7.
We are unable to reproduce this behavior with the given set of steps. Please provide any additional information which may help reproduce this.

**Comment by guardrex** [comment] 2019-08-02 18:28
I was just able to repro it here again. For an unmodified template-based client-side Blazor app (`dotnet new blazor`) and running it in Chrome ...

`dotnet run` &ndash; Debugging doesn't fire up with `Shift+Alt+D`. The error is produced and the Chrome 'how to enable debugging' tab doesn't open.
`dotnet run --configuration Debug` (or `-c Debug`) &ndash; Works. No error message. The 'how to debug' tab opens in Chrome.

Chrome latest: Version 76.0.3809.87 (Official Build) (64-bit)
... and Pre7 SDK

**Comment by djbreen7** [comment] 2019-08-02 18:54
Sure thing, @mkArtakMSFT !

1. Add `chrome.exe` to path:  
![image](https://user-images.githubusercontent.com/13296622/62392044-9fbda700-b523-11e9-99fd-05a216675d76.png)

1. Download and install the dotnet-sdk-3.0.100-preview7-windows-x64-installer [link](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview7-windows-x64-installer)
1. Verify version:  
`dotnet --version`  
![image](https://user-images.githubusercontent.com/13296622/62390691-1b1d5980-b520-11e9-8474-d78aff95ab0e.png)
1. Install Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7:  
`dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7`
1. Create a new **Blazor (client-side)** application:  
`dotnet new blazor --name=MyBlazorApp`
1. `cd` into **MyBlazorApp**  
`cd MyBlazorApp`
1. Run the application with no flags:
`dotnet run`  
1. Open Chrome with remote debugging enabled
`chrome.exe --remote-debugging-port=9222 http://localhost:5000/`

![image](https://user-images.githubusercontent.com/13296622/62392261-3ee29e80-b524-11e9-8e93-32354865b89f.png)

1. Go to **localhost:5000**
1. Open Dev Tools and select **Console**
1. Refocus on the application by clicking somewhere in the web content (the negative space below the "How is Blazor working for you?" text is perfect)
1. Press `SHIFT`+`ALT`+`D` to start debugging

At this point, the error should be visible in the console:  
![image](https://user-images.githubusercontent.com/13296622/62391195-68e69180-b521-11e9-8e83-3d90e17a0f1b.png)

- Note that `dotnet run` implicitly builds in Debug mode. This can be confirmed by the presence of a `/bin/Debug` folder after running `dotnet run`  
![image](https://user-images.githubusercontent.com/13296622/62391355-cbd82880-b521-11e9-9093-b1c9546745f4.png)

- Note that it works fine if the `-c Debug` | `--configuration Debug` is explicitly  
![image](https://user-images.githubusercontent.com/13296622/62392445-a862ad00-b524-11e9-8054-5552daf73c4a.png)

**Comment by mkArtakMSFT** [comment] 2019-08-05 16:33
Thanks @djbreen7.
We'll tackle this after we're done with the upcoming 3.0 release.

**Comment by salavatov** [comment] 2019-10-01 15:25
Need instructions for Edge. Using:
"%programfiles(x86)%\Microsoft\Edge Beta\Application\msedge.exe" --remote-debugging-port=9222 http://localhost:2847/

instead of 
"%programfiles(x86)%\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 http://localhost:2847/

doesn't. Edge still shows 
"Could not get a list of browser tabs from http://localhost:9222/json. Ensure Chrome is running with debugging enabled."
Edge Version 78.0.276.11 (Official build) beta (64-bit)

**Comment by eByte23** [comment] 2019-12-28 21:38
I have also reproduced this, it seems like the `Debug` configuration is not being applied as the environment is still `Production`.

Is there any updates here?

**Comment by guardrex** [comment] 2019-12-28 21:40
FYI @eByte23 in case you don't get a quick answer. Many/most are OOF for the holidays ⛄️. It might take a few weeks to get a response.

**Comment by pranavkm** [comment] 2020-01-06 16:40
This should be fixed in the 3.2-preview1 release.

**Closed by pranavkm** 2020-01-06 16:40 UTC
Labels: Done, area-blazor, blazor-wasm, bug, cost: S
