### ISSUE TITLE
VS Community 16.1.0 Preview 1 - Blazor intellisense errors

### ISSUE THREAD

**Issue by Garderoben** [aspnet/AspNetCore#9366] opened 2019-04-14 11:34 UTC
### Describe the bug
VS Community Preview 16.1.0 intellisense is not recognizing Blazor components or "@injects, @inherits, @body etc"
Application builds and runs as normal.

### To Reproduce
1. Install/Use VS Community 16.1.0 Preview 1
2. Use any Blazor Template from` dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.9.0-preview3-19154-02`
3. Create a new project with the Blazor Template or Blazor (ASP.NET Core hosted)
4. Open Pages/FetchData.cshtml and Shared/MainLayout.cshtml
5. See intellisense error

### Expected behavior
This errors is not present in my Blazor 0.7.0 .NET Core 2.1 setup. And application builds and runs as expected.

### Screenshots
![interror1](https://user-images.githubusercontent.com/10367109/56092141-54ba4e00-5eb8-11e9-846c-1325bcc09ce2.png)
![interro2](https://user-images.githubusercontent.com/10367109/56092148-6ac80e80-5eb8-11e9-9022-ca3c1648dea1.png)
![interror3](https://user-images.githubusercontent.com/10367109/56092168-b975a880-5eb8-11e9-97cb-37c4122f5b06.png)

### Additional context
After some research i think problem is with VS Community 16.1.0 Preview 1. Since Microsoft pulled the previous releases (RC,Preview 4 etc) from download i cant test and verify this.

### dotnet --info
```
PM> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PM> 
```
### Client.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.9.0-preview3-19154-02" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.9.0-preview3-19154-02" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApplication1.Shared\WebApplication1.Shared.csproj" />
  </ItemGroup>

</Project>
```

### Server.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Server" Version="0.9.0-preview3-19154-02" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Server" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview3.19153.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview3.19153.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApplication1.Client\WebApplication1.Client.csproj" />
    <ProjectReference Include="..\WebApplication1.Shared\WebApplication1.Shared.csproj" />
  </ItemGroup>

</Project>
```

**Comment by henkmollema** [comment] 2019-04-14 13:54
Possibly a duplicate of #9320.

**Comment by mkArtakMSFT** [comment] 2019-04-17 16:31
This indeed seems like a dupe, as @henkmollema has pointed out above.

**Closed by mkArtakMSFT** 2019-04-17 16:31 UTC
Labels: area-mvc, feature-Components
