### ISSUE TITLE
Blazor InputBase<T> does not call StateHasChanged when EditContext.NotifyValidationStateChanged

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#14386] opened 2019-09-24 17:09 UTC
### Describe the bug
`InputBase<T>` does not subscribe to EditContext.OnNotifyValidationStateChanged in order to call StateHasChanged. 

As a consequence, the `class` for the control is not updated to reflect an error state when the validation is done asynchronously.

ValidationMessage and ValidationSummary do subscribe, so they do not have the same problem.

### To Reproduce
Index.razor
```
@page "/"

<EditForm Model=@MyPerson>
	<ValidationTester/>
	<InputText @bind-Value=MyPerson.Name/>
	<ValidationMessage For=@(() => MyPerson.Name) style="display:inline" /><br/>
	<FixedInputText @bind-Value=MyPerson.Name/>
	<ValidationMessage For=@(() => MyPerson.Name) style="display:inline" /><br/>
	<input type="submit" value="Validate"/>
</EditForm>


@code
{
	Person MyPerson = new Person();

	public class Person
	{
		public string Name { get; set; }
	}
}
```

FixedInputText.cs
```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using System.Threading.Tasks;

namespace InputValidationStateBug.Shared
{
	public class FixedInputText : InputText
	{
		public override async Task SetParametersAsync(ParameterView parameters)
		{
			var originalEditContext = EditContext;
			await base.SetParametersAsync(parameters);
			if (EditContext != originalEditContext)
				EditContext.OnValidationStateChanged += (s, e) => StateHasChanged();
		}
	}
}
```

ValidationTester.cs
```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InputValidationStateBug.Shared
{
	public class ValidationTester : ComponentBase
	{
		[CascadingParameter] EditContext EditContext { get; set; }
		private ValidationMessageStore MessageStore;

		public override async Task SetParametersAsync(ParameterView parameters)
		{
			EditContext originalEditContext = EditContext;
			await base.SetParametersAsync(parameters);
			if (EditContext != originalEditContext)
				HookupEditContext();
		}

		void HookupEditContext()
		{
			MessageStore = new ValidationMessageStore(EditContext);
			EditContext.OnValidationRequested += EditContext_OnValidationRequested;
		}

		private async void EditContext_OnValidationRequested(object sender, ValidationRequestedEventArgs e)
		{
			FieldIdentifier fieldIdentifier = EditContext.Field("Name");
			foreach (int i in Enumerable.Range(1, 5))
			{
				MessageStore.Clear();
				EditContext.NotifyValidationStateChanged();
				await Task.Delay(500);
				MessageStore.Add(fieldIdentifier, "<= This should flash");
				EditContext.NotifyValidationStateChanged();
				await Task.Delay(500);
			}
		}
	}
}
```

### Expected behavior
The class if the `<InputText>` should alternate between being valid/invalid

### Screenshots
https://imgur.com/a/WAL25MV

**Comment by mkArtakMSFT** [comment] 2019-09-25 16:23
Potential dupe of #11914

**Closed** 2019-09-25 16:24 UTC
Labels: area-blazor
