### ISSUE TITLE
Compilation error on VS2019 for mac, Microsoft.AspNetCore.Mvc.Razor.Extensions.dll cannot find /usr/local/bin/host/fxr

### ISSUE THREAD

**Issue by pjustino** [aspnet/AspNetCore#17258] opened 2019-11-20 12:48 UTC
### Describe the bug

Hi,

I'm using Visual Studio for mac (version 8.3.9(build2) ) and now  any asp.net core  project don't compile due to a razor error.
`
    /usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Razor/extensions/mvc-3-0/Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
    
    A fatal error occurred, the folder [/usr/local/bin/host/fxr] does not exist
    /usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets(99,5): error : rzc discover exited with code 131.
Done building target "ResolveTagHelperRazorGenerateInputs" in project "teste.csproj" -- FAILED.
`

My environment is:
MacOS Mojave  version 10.14.5
Visual Studio for mac 

Output of `dotnet --info`
`
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.201 [/usr/local/share/dotnet/sdk]
  2.1.802 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
`

**Comment by javiercn** [comment] 2019-11-20 13:57
@pjustino thanks for contacting us.

@NTaylorMullen do you have any idea?

**Comment by NTaylorMullen** [comment] 2019-11-20 16:40
Honesty this looks like a bad .NET install.

@KirillOsenkov have you seen this before?

**Comment by KirillOsenkov** [comment] 2019-11-20 16:45
never seen anything like this and no idea what the problem is

**Comment by javiercn** [comment] 2019-11-20 17:18
@NTaylorMullen Can you handle it or close it if it's external?

**Comment by NTaylorMullen** [comment] 2019-11-20 17:25
Closing given this looks to be a bad .NET install

**Closed by NTaylorMullen** 2019-11-20 17:25 UTC
Labels: area-mvc, external

**Comment by pjustino** [comment] 2019-11-21 10:07
I followed the procedure on this page https://docs.microsoft.com/en-
us/visualstudio/mac/uninstall?view=vsmac-2019.   

I also removed a dotnet file I had on /usr/local/bin/dotnet

That seems to be the root of the problem as I then reinstalled VS2019 and it all worked.

Thanks for your support
