### ISSUE TITLE
[FromRoute] binding and Route Template. How to avoid Route Template ?

### ISSUE THREAD

**Issue by Ellaiyaraja** [aspnet/AspNetCore#17847] opened 2019-12-13 06:58 UTC
When I set [FromRoute] Model, I must set template matching for model binding to works . I would like to avoid template set. Is it possible without template? 

[HttpGet(“Student/{ID}/{Name}”)]
public string Student([FromRoute]Student s)
{
   
}

Without Template

[HttpGet(“Student”)]
public string Student([FromRoute]Student s)
{
   
}

Class Student 
{
   ID
   Name
}

**Comment by javiercn** [comment] 2019-12-13 13:46
@Ellaiyaraja thanks for contacting us.

The behavior you are observing is by design. If you use [FromRoute] it implies that the values for binding to that type come from the route hence they need to be part of the route template.

It doesn't make sense to have [FromRoute] without having a matching template for it.

Hope that helps.

I'm closing this issue as the question has been asnwered.

**Closed by javiercn** 2019-12-13 13:46 UTC
Labels: area-mvc
