### ISSUE TITLE
System.TypeLoadException: Could not load type 'System.Web.HttpUtility' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by KamranShahid** [aspnet/AspNetCore#17654] opened 2019-12-06 13:40 UTC
I am getting following error in my asp.net core 3.0 application

`System.TypeLoadException: Could not load type 'System.Web.HttpUtility' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

My application project file looks like follwoing

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RuntimeIdentifiers>ubuntu.16.04-x64;ubuntu.16.10-x64;win-x64;win10-x64;win10-x86;debian-x64;debian.8-x64;debian.9-x64;win81-x64;ubuntu.18.04-x64;</RuntimeIdentifiers>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />

  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>
</Project>
```

**Comment by pranavkm** [comment] 2019-12-06 14:57
Can you share a minimal project that reproduces this error? I don't think that particular type was ever part of AspNetCore.

**Comment by KamranShahid** [comment] 2019-12-07 13:50
i have shared the project config as mentioned above. it's a .net core 3.0 solution. i published as self contained project with trimmed version as mentioned above. I am simply using httputility.parsequerystring() to get the name value collection. and getting this error.
It is called in my controller.
Interesting thing is i can reference Microsoft.AspNetCore.Http.Abstractions 2.2 library in my some domain project to extract same info it works. but i don't wanted to use .net core 2.2 specific library.

this problem is linked to one of my old highlighted issue

https://github.com/aspnet/AspNetCore/issues/17325

**Comment by KamranShahid** [comment] 2019-12-07 21:01
some one given me a suggestion of using request.Query collection for same purpose. will try to get rid of this HttpUtility.Parsequery... related implementation

**Comment by pranavkm** [comment] 2019-12-20 19:04
Closing this since the related issue has a resolution.

**Closed by pranavkm** 2019-12-20 19:04 UTC
Labels: Needs: Attention :wave:, area-platform
