### ISSUE TITLE
Minor UI: Microsoft login button disappears when an invalid password is used to login via the form

### ISSUE THREAD

**Issue by Max-Hollywood** [aspnet/AspNetCore#12337] opened 2019-07-19 01:16 UTC
### Using
ASP.NET Core 2.2, MVC, Identity

### Describe the bug
In ASP.NET MVC, using Identity and the 3rd party Microsoft login system, if you click "Login", and enter a password that doesn't match anything in your database, the Microsoft 3rd party login button disappears, replaced with the "Use another service to login" message.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run with the basic code that VS gives you and generates with scaffolding and adding in 3rd party Microsoft login code (ie. app.UseMicrosoft...)
3. Build/Migrate/Run
4. Click Login
5. Enter any email, real or fake
6. Enter any invalid password that won't actually match
7. Microsoft login button replaced with the dev message to add 3rd party login

**Comment by blowdart** [comment] 2019-07-19 13:08
@HaoK @javiercn this sounds familiar, did it get fixed in 3.0?

**Comment by javiercn** [comment] 2019-07-19 13:24
I don't remember if it got fixed, but I definitely filed a bug for it or a very similar bug at the time, not sure if it got closed or fixed though.

**Comment by HaoK** [comment] 2019-07-19 17:10
Pretty sure I fixed this one, I will track down the issue/PR

**Comment by HaoK** [comment] 2019-07-19 19:46
Yep dupe of https://github.com/aspnet/AspNetCore/issues/5765

**Closed by HaoK** 2019-07-19 19:46 UTC
Labels: area-identity
