### ISSUE TITLE
<option value=""> incorrectly omits value attribute when body of option contains razor content

### ISSUE THREAD

**Issue by kswoll** [aspnet/AspNetCore#5625] opened 2018-11-04 19:41 UTC
What follows is a simple example that leverages HTML5 `required` for an HTML `<select>` element.  The idea is to force the user to choose a value from the dropdown when submitting the form.  A value must be provided to the first option that is the empty string.  (see https://stackoverflow.com/a/6048891/189950)  This works, but if the content of the option element is, for example, provided by a field, Blazor incorrectly omits the `value` attribute, which breaks validation (in Chrome and Edge, anyway).

You can see this behavior in the example.  The first select element tries to make the "none" option text provided by a field (`@noneString`) whereas the second select element just hard codes it to `None`.

If you run it, you'll notice that when clicking the submit button, it highlights the second select element as being required and ignores the first one.  If you simply replace `@noneString` with `None`, then it correctly validates the first select element as well.  (If you look at devtools and examine the first option element in the broken version, there is no `value` attribute present.)

```
@page "/"

<form>
    <p>
        <select required size="1">
            <option value="" selected>@noneString</option>
            <option value="1">1</option>
            <option value="2">2</option>
        </select>
    </p>
    <p>
        <select required size="1">
            <option value="" selected>None</option>
            <option value="1">1</option>
            <option value="2">2</option>
        </select>
    </p>
    
    <input type="submit" />
</form>

@functions {
    string noneString = "None";
}  
```

**Comment by SteveSandersonMS** [comment] 2018-12-18 13:22
Duplicate of #5616

**Closed by SteveSandersonMS** 2018-12-18 13:22 UTC
Labels: area-mvc, feature-blazor
