### ISSUE TITLE
[Question] Problem with EF Core migrations with IHostBuilder

### ISSUE THREAD

**Issue by sven5** [aspnet/AspNetCore#7685] opened 2019-02-18 15:59 UTC
Hi,

I came across an issue regarding the change from WebHostBuilder to HostBuilder in 3.0 Prev2. 
We're using EF Core migrations. 
With the new `HostBuilder` the cmdlet `Add-Migration` fails with complaining about either a missing parameterless constructor or `IDesignTimeDbContextFactory` (design-time DbContext creation).

This was not necessary when using a WebHostBuilder in 2.1 It seems that the DbContext options are not injected properly. 

In the meantime, I can workaround this using the WebHostBuilder.
Is there any workaround for this change? 

Thanks
Sven

**Comment by Eilon** [comment] 2019-02-19 06:07
Also cc @ajcvickers @divega @bricelam

**Comment by davidfowl** [comment] 2019-02-19 06:19
cc @Tratcher

**Comment by Tratcher** [comment] 2019-02-19 06:32
Fixed here: https://github.com/aspnet/EntityFrameworkCore/pull/14378 (preview 3?)

**Comment by Tratcher** [comment] 2019-02-19 06:34
Does your Program.cs match this? https://github.com/aspnet/AspNetCore/blob/dffe9abf6b6b009e183e808459e65770c9210a52/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Program.cs#L14-L26

**Comment by sven5** [comment] 2019-02-19 07:18
@Tratcher 
Yes that's the code in my Program.cs 

I get the error
**Unable to create an object of type 'QualityAssuranceDataContext'. Add an implementation of 'IDesignTimeDbContextFactory<QualityAssuranceDataContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.**

**Comment by ajcvickers** [comment] 2019-02-22 21:55
Closing as external since I believe this is already fixed for preview3.

**Closed by ajcvickers** 2019-02-22 21:55 UTC
Labels: area-hosting

**Comment by oliverjanik** [comment] 2019-04-16 07:37
🤦‍♂️ This will land in core 3.0? So for us in 2.2 using IHostBuilder there's no way to get EF Add-Migration to work.

**Comment by davidfowl** [comment] 2019-04-16 07:53
@oliverjanik can you clarify what you mean? We switched to use the IHostBuilder as part of 3.0, there's no known regression here in 2.2.

**Comment by bricelam** [comment] 2019-04-16 21:53
IHostBuilder should work with EF Core 2.2 (however you managed to do that) if you name the method Create**Web**HostBuilder
