### ISSUE TITLE
API freezing with indexed file uploads in a DTO

### ISSUE THREAD

**Issue by MakoPhil** [aspnet/AspNetCore#8879] opened 2019-03-28 06:55 UTC
### Describe the bug
I'm trying to load data from an Angular application into a .NET Core API. All other POST and GET calls work as expected, but there is one method that doesn't cooperate. I have distilled the problem into the following files to try to isolate the problem.

#### FileCollectionViewModel.cs
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Http;
    
    public class FileCollectionViewModel
    {
        public List<FileViewModel> FilesVm { get; set; } // See next class
        public string Title { get; set; }
        public IFormFile File { get; set; }
        public IFormFileCollection FilesCollection { get; set; }
        public List<IFormFile> FilesList { get; set; }
        public FileViewModel SingleFile { get; set; }
    }

#### FileViewModel.cs
    using Microsoft.AspNetCore.Http;

    public class FileViewModel
    {
        public IFormFile File { get; set; } // This seems to be problematic
        public string Filename { get; set; }
    }

#### FilesController.cs
    ...
    [HttpPost("[action]")]
    public void FileTestMethod(FileCollectionViewModel files)
    {
        System.Diagnostics.Debug.WriteLine("Entered Method");
    }
    ...

#### FilesService.ts
    ...
    public SendFilesTest(): void {
        const formData = new FormData();
        formData.append("Title", "deal usually");
        formData.append("File", new Blob(), "blanket solution");
    
        // Start Sub VM
        formData.append("FilesVm[0].File", new Blob(), "magic force");
        formData.append("FilesVm[1].File", new Blob(), "broad occur");
        formData.append("FilesVm[2].File", new Blob(), "plenty limited");
        formData.append("FilesVm[3].File", new Blob(), "next experience");
        formData.append("FilesVm[0].Filename", "cold drink");
        formData.append("FilesVm[1].Filename", "problem deep");
        formData.append("FilesVm[2].Filename", "south test");
        formData.append("FilesVm[3].Filename", "tower correctly");
        // End Sub VM
    
        formData.append("FilesCollection[0]", new Blob(), "famous period");
        formData.append("FilesCollection[1]", new Blob(), "sentence organized");
        formData.append("FilesCollection[2]", new Blob(), "those car");
        formData.append("FilesCollection[3]", new Blob(), "collect path");
        formData.append("FilesList[0]", new Blob(), "act tight");
        formData.append("FilesList[1]", new Blob(), "fur sang");
        formData.append("FilesList[2]", new Blob(), "bit visitor");
        formData.append("FilesList[3]", new Blob(), "determine somewhere");
        formData.append("SingleFile.File", new Blob(), "during football");
        formData.append("SingleFile.Filename", "hole paragraph");

        this.http.post<void>(`${this.baseUrl}api/Files/FileTestMethod`, formData)
            .subscribe(() => { });
    }
    ...

### To Reproduce
Place a breakpoint on the _System.Diagnostics.Debug..._ line in the FilesController.cs file.
Submit the mock data using _FormData_.
Breakpoint doesn't hit, client continues to wait for a response.

To prove it works when _FileViewModel_ is not included in FormData:
Comment out the code between the comments with _Start Sub VM_ and _End Sub _VM_ in the FileService.ts file.
Submit again.
Breakpoint is hit, continuing the application sends a response back to the client.

### Expected behavior
Breakpoint is hit and all data is provided.

### Additional context
This _definitely used to work_ and I don't know what's changed. I've tried reverting to .NET Core 2.1 with no success, tried on Windows and Linux. I know the other file arrays in the sample code are not being populated either, that I can live with but I would like to know what is going on with the embedded ViewModel (other embedded VMs without IFormFile or IFormFileCollection work fine). The suspicious thing is the freezing up of the .NET Core host, it takes a restart of .NET Core to continue doing anything.

#### dotnet --info
    .NET Core SDK (reflecting any global.json):
     Version:   2.2.105
     Commit:    7cecb35b92
    
    Runtime Environment:
     OS Name:     ubuntu
     OS Version:  18.10
     OS Platform: Linux
     RID:         ubuntu.18.10-x64
     Base Path:   /usr/share/dotnet/sdk/2.2.105/
    
    Host (useful for support):
      Version: 2.2.3
      Commit:  6b8ad509b6
    
    .NET Core SDKs installed:
      2.1.505 [/usr/share/dotnet/sdk]
      2.2.105 [/usr/share/dotnet/sdk]
    
    .NET Core runtimes installed:
      Microsoft.AspNetCore.All 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by mkArtakMSFT** [comment] 2019-03-28 16:53
Thanks for contacting us, @MakoPhil.
This seems to be a duplicate of https://github.com/aspnet/AspNetCore/issues/4802, which we've addressed for 3.0 release.
As a workaround, while it's not that nice, you can use @dougbu 's suggestion at https://github.com/aspnet/AspNetCore/issues/4802#issuecomment-454914479. That is - move the `IFormFile` type from the `FileCollectionViewModel.FileVM` to be a flat list top-level collection.

**Closed by mkArtakMSFT** 2019-03-28 16:53 UTC
Labels: area-mvc, feature-Model-Binding
