### ISSUE TITLE
<option value=""> incorrectly omits value attribute

### ISSUE THREAD

**Issue by jonbrauer** [aspnet/AspNetCore#17735] opened 2019-12-10 14:13 UTC
### Bug
<option value="">[Select]</option> becomes <option>[Select]</option> on the client thus eliminating the ability to select "nothing" as a value in a drop down. 

### To Reproduce

``` TestComponent.razor

<div><input id="tbx" value="@MyValue"  /></div>
<div>
    <select id="ddlAdm1" @onchange="@OnMyValChange" value="@MyValue">
        <option value="">[Select]</option>
        <option value="1">One</option>
        <option value="2">Two</option>
    </select>
</div>

@code {
    [Parameter] public string MyValue { get; set; }

    protected void OnMyValChange(ChangeEventArgs e)
    {
        MyValue = e.Value.ToString();
    }
}

```
Produces

``` HTML

<div><input id="tbx"></div><!--!-->
    <div>
        <!--!-->
        <select id="ddlTest">
            <!--!-->
            <option>[Select]</option><!--!-->
            <option value="1">One</option><!--!-->
            <option value="2">Two</option><!--!-->
        </select><!--!-->
    </div>
```

This causes selecting the first line to put "[Select]" in the "tbx" input box.

### Version Info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

Visual Studio 2019

**Comment by mkArtakMSFT** [comment] 2019-12-10 17:52
Thanks for contacting us.
This is the intended behavior we have in place for the Select tag helpers.
@NTaylorMullen is there a way to prevent this behavior?

**Comment by appsupport-gc** [comment] 2019-12-10 18:10
Intended?  How then can I select a “null” or empty value?

**Comment by NTaylorMullen** [comment] 2019-12-10 18:28
> Thanks for contacting us.
> This is the intended behavior we have in place for the Select tag helpers.
> @NTaylorMullen is there a way to prevent this behavior?

@mkArtakMSFT this is Blazor.

@jonbrauer / @appsupport-gc when I run your sample locally I get expected the expected output:
![image](https://user-images.githubusercontent.com/2008729/70557080-02105f00-1b37-11ea-94ea-75f418cfe520.png)

If you look at the output in the Chrome inspector you'll see what you pasted but that's just an interpreted version of the HTML you wrote (you can view source to get a better representation). All that being said it also doesn't populate the textbox on my side either via `dotnet new blazorserver`:

![image](https://user-images.githubusercontent.com/2008729/70557481-bf02bb80-1b37-11ea-9d00-cac5153f6cc1.png)

If you can provide a simple repro based off of the `dotnet new blazorserver` template apps that would be helpful for us to investigate further.

**Comment by appsupport-gc** [comment] 2019-12-10 19:17
Ok demo available here.  https://github.com/appsupport-gc/BlazorIssue-EmptyOptionValue

**Comment by NTaylorMullen** [comment] 2019-12-10 19:47
Thanks @appsupport-gc!

@pranavkm / @javiercn / @SteveSandersonMS can one of you three assign this to yourself to investigate? It looks like the Blazor runtime is triggering change events after the page has been loaded resulting in the TextBox's content getting filled.

**Comment by SteveSandersonMS** [comment] 2019-12-12 18:53
Thanks very much @jonbrauer for reporting this and for providing such a clear repro.

This is a bug and will be fixed in https://github.com/aspnet/AspNetCore/pull/17838. In the meantime, the workaround I'd recommend is to have a different value (other than an empty string) to represent "no selection", and set that value as the initial value for your bound model property.

**Comment by appsupport-gc** [comment] 2019-12-12 19:29
GREAT!  Thanks so much!

**Closed** 2019-12-13 10:23 UTC
Labels: area-mvc, bug
