### ISSUE TITLE
Run Helix on a schedule instead of on PRs

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8453] opened 2019-03-12 22:14 UTC
- [x] Remove Helix from PR checks
- [x] Have Helix run on 'master' on a 4 hour cadence (Daily currently @ 3:42 PM M-F)
- [x] Ensure that RaaS_whatever sees the Helix failures and reports on flaky issues

**Comment by HaoK** [comment] 2019-03-12 22:46
PR to disable Helix in PRs is https://github.com/aspnet/AspNetCore/pull/8454

I didn't see any obvious way to specify 4 hour builds in Azdo, but I was able to schedule daily builds at a fixed time (I configured Monday-Friday @ 3:42 since that what time it was).

**Comment by HaoK** [comment] 2019-03-12 22:48
@ryanbrandenburg the first scheduled build is https://dev.azure.com/dnceng/public/_build/results?buildId=122465 if you need a test build to train RaaS against

**Comment by ryanbrandenburg** [comment] 2019-03-12 23:10
Cool beans. It's not so much that we need to "train" RaaS, I just have to double check that it's triageing builds from that config.

**Comment by jkotalik** [comment] 2019-03-12 23:28
We need to keep some parts of Helix in tact for IIS testing for PRs. Without helix, we remove all PR validation for IIS and make my life as a dev unbearable.

**Comment by ryanbrandenburg** [comment] 2019-03-12 23:32
If the IIS tests are reliable on helix (or can be made to be) it seems like a reasonable ask to run only them on helix. Having 0 PR coverage for those is, I agree, a very high price. Is the IIS stuff the only thing that has helix-only tests?

**Comment by HaoK** [comment] 2019-03-12 23:46
Maybe we can compromise and just run windows on helix for now, that preserves IIS and most of the coverage and also gets rid of all the flaky tests which generally are non windows

**Comment by jkotalik** [comment] 2019-03-13 00:09
That isn't a compromise I am okay with. 

What batches of tests are we still considering flaky on Helix? For example, the InMemory Functional tests for Kestrel are flaky on Helix. Let's disable that entire test project. I thought our plan was to aggressively disable tests. Are we short on resources? Is the inner loop for test feedback too slow? 

If we have deemed demoting helix to this position, what is our plan to re-enabling for every PR? Also have we deemed disabling tests too hard to do on Helix?

Why can't we have a bot that runs PRs on Helix and then comments on the PR if there is a failure?

This is too big of a decision to not have details like these.

**Comment by HaoK** [comment] 2019-03-13 00:40
It was the collective managers call, but I'm not sure anyone realized that IIS has helix only tests, I believe highest priority is to get PRs consistently green.  Looking at the helix queues, the pass rate is still only 46% recently.  The long term plan is still to do only run tests on helix, but the short/medium term idea was to only run helix on master until more issues are ironed out so PRs aren't constantly red.

**Comment by jkotalik** [comment] 2019-03-13 01:22
Chatted with @eilon offline. I understand the motivation. Let's try to make it so Helix ONLY runs on this agent type. https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190312.29.

**Comment by HaoK** [comment] 2019-03-13 05:34
Alternative to turning off helix runs on pr, is ignoring any helix test failures for the build, see https://github.com/aspnet/AspNetCore/pull/8464 for an alternative fix.

We could continue to look at helix test runs in PRs as needed, but it should never be red due to tests failing

**Comment by HaoK** [comment] 2019-03-13 05:34
So for IIS you would have to manually go look at the helix runs to make sure your tests pass since the green helix check is meaningless

**Comment by jkotalik** [comment] 2019-03-13 05:36
> So for IIS you would have to manually go look at the helix runs to make sure your tests pass since the green helix check is meaningless

That is fine with me. I prefer this option significantly. Thanks @HaoK !

**Comment by HaoK** [comment] 2019-03-13 19:54
Merged https://github.com/aspnet/AspNetCore/pull/8464 which should keep helix 'green' for PRs :)

**Comment by Eilon** [comment] 2019-03-13 20:35
Yay!

**Comment by ryanbrandenburg** [comment] 2019-03-15 21:36
I confirmed that RaaS finds these, so we're done here.

**Closed by ryanbrandenburg** 2019-03-15 21:36 UTC
Labels: 3 - Done, PRI: 1 - Required, area-infrastructure, cost: S
