### ISSUE TITLE
ObjectDisposedException using TestServer

### ISSUE THREAD

**Issue by tjrobinson** [aspnet/AspNetCore#8207] opened 2019-03-05 17:11 UTC
I'm trying to run a simple test using `TestServer` but getting an `ObjectDisposedException`.

### Environment
* ASP.NET Core 2.2.2 with `netcoreapp2.2`
* Running `dotnet test` at the command line, or using Rider

## Exception and stack trace

```
MyProduct.Web.IntegrationTests.BasicTests.Get_EndpointsReturnSuccessAndCorrectContentType(url: "/")

System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.TestHost.TestServer'.
   at Microsoft.AspNetCore.TestHost.TestServer.<Microsoft.AspNetCore.Hosting.Server.IServer.StartAsync>b__21_0[TContext]()
   at Microsoft.AspNetCore.TestHost.TestServer.ApplicationWrapper`1.ProcessRequestAsync(TContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MyProduct.Web.IntegrationTests.BasicTests.Get_EndpointsReturnSuccessAndCorrectContentType(String url) in C:\Code\MyProduct\tests\MyProduct.Web.IntegrationTests\BasicTests.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
```

If I put a breakpoint on this line in the test:

```
var response = await client.GetAsync(url);
```

Then I can see that `this.webApplicationFactory.Server._disposed` is `true`.

## Code

```
namespace MyProduct.Web.IntegrationTests
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc.Testing;
    using Xunit;

    public class BasicTests : IClassFixture<CustomWebApplicationFactory<Startup>>
    {
        private readonly CustomWebApplicationFactory<Startup> webApplicationFactory;

        public BasicTests(CustomWebApplicationFactory<Startup> webApplicationFactory)
        {
            this.webApplicationFactory = webApplicationFactory;
        }

        [Theory]
        [InlineData("/")]
        public async Task Get_EndpointsReturnSuccessAndCorrectContentType(string url)
        {
            // Arrange
            var client = this.webApplicationFactory.CreateClient(new WebApplicationFactoryClientOptions
            {
                AllowAutoRedirect = false
            });
           
            // Act
            var response = await client.GetAsync(url);

            // Assert
            response.EnsureSuccessStatusCode(); // Status Code 200-299
            Assert.Equal("text/html; charset=utf-8",
                response.Content.Headers.ContentType.ToString());
        }
    }
}
```

```
namespace MyProduct.Web
{
    using Microsoft.AspNetCore.Builder;
    using Microsoft.Extensions.DependencyInjection;

    public class Startup
    {
        public void Configure(IApplicationBuilder app)
        {
            app.UseMvc();
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddMvc();
        }
    }
}
```

```
namespace MyProduct.Web.IntegrationTests
{
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc.Testing;
    using Microsoft.AspNetCore.TestHost;

    public class CustomWebApplicationFactory<TStartup>  : WebApplicationFactory<TStartup> where TStartup: class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                builder.UseSolutionRelativeContentRoot("src/MyProduct.Web/");
            });
        }
    }
}
```

### Expected behavior
The test should pass or fail with something other than an `ObjectDisposedException`.

### Additional context
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Tratcher** [comment] 2019-03-05 20:30
@javiercn ?

**Comment by anurse** [comment] 2019-04-10 18:47
When I try your sample code, I get an expected result:

```
[4/10/2019 11:45:52 AM Error] [xUnit.net 00:00:01.46]     MyProduct.Web.IntegrationTests.BasicTests.Get_EndpointsReturnSuccessAndCorrectContentType(url: "/") [FAIL]
[4/10/2019 11:45:52 AM Informational] [xUnit.net 00:00:01.47]       System.Net.Http.HttpRequestException : Response status code does not indicate success: 404 (Not Found).
[4/10/2019 11:45:52 AM Informational] [xUnit.net 00:00:01.47]       Stack Trace:
[4/10/2019 11:45:52 AM Informational] [xUnit.net 00:00:01.47]            at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
[4/10/2019 11:45:52 AM Informational] [xUnit.net 00:00:01.47]         C:\Users\anurse\source\repos\WebApplication1\XUnitTestProject1\UnitTest1.cs(33,0): at MyProduct.Web.IntegrationTests.BasicTests.Get_EndpointsReturnSuccessAndCorrectContentType(String url)
[4/10/2019 11:45:52 AM Informational] [xUnit.net 00:00:01.47]         --- End of stack trace from previous location where exception was thrown ---
```

Since your sample doesn't show any controllers/actions/etc. I get a 404 because nothing handles the request. I don't get any `ObjectDisposedException`. Can you create a sample project that reproduces the issue? That way we can see how the app could be affecting the `TestServer`.

**Comment by tjrobinson** [comment] 2019-04-11 12:33
@anurse Thanks, I will have a go though it may not be for a while. If you'd rather close this issue in the meantime that's fine with me.

**Comment by anurse** [comment] 2019-04-12 04:55
I'll close it for now, but if you get a repro together please re-open the issue!

**Closed by anurse** 2019-04-12 04:55 UTC
Labels: area-servers, waiting
