### ISSUE TITLE
FlushAsync doesn't actually write data to the client?

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#3542] opened 2018-09-19 22:42 UTC
_From @drauch on Tuesday, 11 September 2018 10:39:35_

I have a Razor view which (as a minimal repro sample) looks like this:

    @{ var longStr = new string('x', 100 * 1024); /* more than 64KB */ }
    ...
    @functions { string Throw () { throw new Exception(); } }
    ...
    <p>@longStr</p>
    @await FlushAsync()
    <p>@Throw()</p>

I expected to see many x on the client, instead I see a proper error page. How is this possible if `FlushAsync` already sent `longStr` to the client? Is the data still buffered somewhere on the server?

_Copied from original issue: aspnet/KestrelHttpServer#2912_

**Comment by muratg** [comment] 2018-09-19 22:42
_From @benaadams on Tuesday, 11 September 2018 10:43:44_

Think its an issue with [`HttpResponseStreamWriter` in `HttpAbstractions`](https://github.com/aspnet/HttpAbstractions/blob/02f55e181b19d8854672d05225e0dbbf991100db/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs) that `FlushAsync` never actually calls `FlushAsync` on the underlying stream.

/cc @rynowak

**Comment by muratg** [comment] 2018-09-19 22:42
_From @drauch on Tuesday, 11 September 2018 11:23:29_

Is there a definitive way to move content to the client?

**Comment by muratg** [comment] 2018-09-19 22:42
_From @benaadams on Thursday, 13 September 2018 03:44:51_

I think its a bug in the ` HttpResponseStreamWriter`

It even has the comment
```csharp
        // We want to flush the stream when Flush/FlushAsync is explicitly
        // called by the user (example: from a Razor view).
```

On pure Kestrel it should act the same; however if you have an intermediate stream like compression; a reverse proxy (IIS or ngnix) or are using a different server like HttpSysServer then it probably won't.

**Comment by drauch** [comment] 2018-09-20 05:29
For now it looks like ASP.NET Core buffers the whole page before sending any data to the client. This is not what we'd expect from a high performance framework.

**Comment by davidfowl** [comment] 2018-09-20 05:42
Razor views/pages are buffered by design (for efficiency). That said, there should be a way to flush to the client if needed.

cc @pranavkm @rynowak

**Comment by Tratcher** [comment] 2018-09-20 13:27
The HttpResponseStreamWriter looks like it buffers up to 16kb at a time. Are your views larger than that?

**Comment by drauch** [comment] 2018-09-20 14:12
See my initial post. I rendered 100KB of data. Also tested with 50MB. Also tested with 50 times 1MB, if that matters.

**Comment by pranavkm** [comment] 2018-09-20 17:05
This seems to work fine - https://github.com/pranavkm/repro/blob/aspnet/Home/3542/Views/Home/Index.cshtml. Do you have a sample where this isn't working correctly?

**Comment by rynowak** [comment] 2018-09-20 17:10
> Razor views/pages are buffered by design ~~(for efficiency)~~ **(as a fundamental part of the programming model)**

**Comment by drauch** [comment] 2018-09-20 18:06
> Razor views/pages are buffered by design (for efficiency) **(as a fundamental part of the programming model)**

Good to know. I'm fine with it. It hasn't been the case in ASP.NET Core 1.1.x. We had issues with throwing view components while some content has already been pushed to the client (and no possibility to show an error page anymore). If that's gone in 2.1.x we're more than happy.

**Comment by rynowak** [comment] 2018-09-20 18:14
>  If that's gone in 2.1.x we're more than happy.

There's been no change to how any of this works in 2.1.

To explain what I mean - views need to execute **inside out**.

Since `.Layout` is a settable property on a view, you must execute a view (and save the result), then you can find out whether it has a layout page (which could be modified while running the view). Then you need to run the layout, and repeat the process, building up more content.

There's a fairly complex system in place to try and make the buffering efficient. We keep objects in their 'string' form for as long as possible to avoid requiring a lot of memory. Since most of the content in Razor is static  markup this usually works well in practice.

**Comment by benaadams** [comment] 2018-09-21 01:49
`HttpResponseStreamWriter.FlushAsync` currently empties it buffers and calls `WriteAsync` on the underlying stream; but **doesn't** call `FlushAsync` on the underlying stream.

If the underlying stream is Kestrel's response stream then this will cause an immediate Flush; as Kestrel doesn't differentiate between Write and Flush (its `WriteAsync` always flushes).

So am not sure what **not** calling `_stream.FlushAsync` as part of `FlushAsync()` gains?

However; if the Kestrel stream was wrapped in another buffering stream (gzip, tls, etc); then not propagating the Flush to the underlying stream could be problematic?

**Comment by anurse** [comment] 2019-04-11 22:28
> `HttpResponseStreamWriter.FlushAsync` currently empties it buffers and calls `WriteAsync` on the underlying stream; but **doesn't** call `FlushAsync` on the underlying stream.

@benaadams This is what you filed in https://github.com/aspnet/AspNetCore/issues/2894, right?

Given the issue Ben filed, I'm going to close this issue in lieu of #2894. The Razor buffering behavior is by design as @rynowak posted earlier.

**Closed by anurse** 2019-04-11 22:28 UTC
Labels: area-servers, feature-HttpAbstractions

**Comment by drauch** [comment] 2019-04-12 06:12
OK for me, I will subscribe to the other issue for updates.
