### ISSUE TITLE
ASP.NET Core 2.2  after scaffolding Identity Autogenerated Login.cshtml.cs file provides _signInManager.PasswordSignInAsync with wrong parameters!

### ISSUE THREAD

**Issue by pavsavov** [aspnet/AspNetCore#4539] opened 2018-12-09 18:58 UTC
Using this version of ASP.NET Core '2.2'

Here is my configuration for using Identity.

            services.AddIdentity<SuperCharactersUser, IdentityRole>(options =>
               {
                   options.Password.RequireDigit = false;
                   options.Password.RequiredLength = 3;
                   options.Password.RequiredUniqueChars = 0;
                   options.Password.RequireLowercase = false;
                   options.Password.RequireNonAlphanumeric = false;
                   options.Password.RequireUppercase = false;
               })
                .AddDefaultTokenProviders()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<SuperCharactersAppDbContext>();

I have also custom IdentityUser. 

    public class SuperCharactersUser : IdentityUser
    {
        public  Score Score { get; set; }
    }

Already created IdentityDbContext:

    public class SuperCharactersAppDbContext : IdentityDbContext<SuperCharactersUser>
    {
        //public DbSet<Score> Scores { get; set; }
        public DbSet<SecretIdentity> SecretIdentities { get; set; }
        public DbSet<SuperCharactersUser> AppUsers { get; set; }
        public DbSet<Character> Characters { get; set; }
        public DbSet<SuperPower> SuperPowers { get; set; }
        public DbSet<Team> Teams { get; set; }
        
        public SuperCharactersAppDbContext()
        {

        }

        public SuperCharactersAppDbContext(DbContextOptions<SuperCharactersAppDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            //builder.Entity<TeamsCharacters>().HasKey(tc => new { tc.CharacterId, tc.TeamId });

        }
    }

I have a middleware which seeds two roles called Admin and Creator and two users for these roles

 public class PowerUsersAndRolesSeedMiddleware
    {
        private readonly RequestDelegate next;
        private readonly Dictionary<string, SuperCharactersUser> powerUsers = new Dictionary<string, SuperCharactersUser>()
        {
            {"Admin",new SuperCharactersUser{Email = "admin@admin.ad",PasswordHash="admin123",UserName ="Admin" } },
            {"Creator",new SuperCharactersUser{ Email="creator@creator.cr",PasswordHash="creator123",UserName = "Creator"} },
        };

        public PowerUsersAndRolesSeedMiddleware(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task InvokeAsync(HttpContext context, IServiceProvider provider)
        {
            var roleManager = provider.GetRequiredService<RoleManager<IdentityRole>>();
            var userManager = provider.GetRequiredService<UserManager<SuperCharactersUser>>();

            await SeedRoles(roleManager);
            await SeedUsers(userManager);

            await next(context);
        }
        private async Task SeedRoles(RoleManager<IdentityRole> roleManager)
        {

            foreach (var roleName in powerUsers.Keys)
            {
                if (await roleManager.FindByNameAsync(roleName) == null)
                {
                    var result = await roleManager.CreateAsync(new IdentityRole(roleName));

                    if (!result.Succeeded)
                    {
                        ExceptionCatcher(result);
                    }
                }
            }
        }

        private async Task SeedUsers(UserManager<SuperCharactersUser> userManager)
        {

            foreach (var user in powerUsers)
            {
                if (await userManager.FindByNameAsync(user.Key) == null)
                {
                    var result = await userManager.CreateAsync(user.Value, user.Value.PasswordHash);

                    if (!result.Succeeded)
                    {
                        ExceptionCatcher(result);
                    }

                    var isAdded = await userManager.AddToRoleAsync(user.Value, user.Key);
                    if (!isAdded.Succeeded)
                    {
                        ExceptionCatcher(isAdded);
                    }
                }
            }
        }
        private void ExceptionCatcher(IdentityResult result)
        {
            throw new Exception(string.Join(Environment.NewLine, result.Errors.Select(e => e.Description)));
        }
    }

After scaffolding Identity to an existing ASP.NET Core 2.2 , I receive failed log in message even though I am logging with correct credentials 

The following code was generated for me within the Login.cshtml.cs RazorPage->

    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<SuperCharactersUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<SuperCharactersUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            //[EmailAddress]   //No longer an EmailType
            public string UserName { get; set; }  //Renamed to UserName

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);   **// Here is the problem**
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }

   var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true); ->

 **### // here is the problem. It seems PasswordSignInAsync can receive only UserName as parameter not Email. When I changed it to Input.UserName, then the result is true and login is sucessfull.**

This is autogenerated code from Identity which provides PasswordSignInAsync with wrong parameters.

If needed more information can be provided !

Best Regards,
Pavel Savov

**Comment by blowdart** [comment] 2018-12-10 14:21
This isn't the wrong parameter.

Username is the unique key in ASP.NET Identity, but in order to make things "easier" when a user is created the username and email address are identical. Emails can be duplicated, by default, unless you set the option to require emails to be unique,

**Comment by pavsavov** [comment] 2018-12-10 14:58
If I am correct, by default you can not register unless you provide email. That is the [Email] attribute doing, right?

**Comment by pavsavov** [comment] 2018-12-19 19:02
If I understood correctly that is a normal behaviour?

**Comment by MiguelIPerez** [comment] 2019-01-15 23:15
sorry but, where do i find this "UIFramework.Bootstrap4" i am implementing something similar but i cant find this UIFramework stuff

**Comment by pavsavov** [comment] 2019-01-18 12:31
I believe it is part of the v2.2 .net core startup template, provided within ASP.

**Comment by weitzhandler** [comment] 2019-07-02 03:52
Hi folks,

I'm setting up the identity as follows:

```c#
services
        .AddDefaultIdentity<Tenant>()
        .AddDefaultUI(UIFramework.Bootstrap4)
        .AddEntityFrameworkStores<CatalogDbContext>();
```

Then in the `OnModelCreating` I'm initializing a user like this:
```c#
builder.Entity<Tenant>(t =>
  {
    var tenant = new Tenant { ... }
    var hasher = new PasswordHasher<Tenant>();
    tenant.PasswordHash = hasher.HashPassword(tenant, "mypass");
    t.HasData(tenant);
  });
```

When I go to the login page and try to login with the provided email/password, I get an error "Invalid login attempt".
Why is that?

**Comment by blowdart** [comment] 2019-07-24 20:28
We're closing this issue as the behaviour discussed seems to be by design.

**Closed by blowdart** 2019-07-24 20:28 UTC
Labels: area-identity
