### ISSUE TITLE
Angular template: User.Identity.Name return null in webapi controllers

### ISSUE THREAD

**Issue by wjsgzcn** [aspnet/AspNetCore#13366] opened 2019-08-23 05:58 UTC
Using dotnet core 3.0 preview8 to create a new angular project with individual authentication, I got a null when calling User.Identity.Name in the webapi controller, while I was logged in and the web page could display correct username.

I found the name claim is missing in the User's claims, and I have to get userid from claims, then use ef to get username from the database.

I wonder if this is a bug, or can I get the username through User.Identity.Name here.

**Comment by blowdart** [comment] 2019-08-23 12:24
@javiercn are we providing wrappers to send a token to an api controller or anything in these templates?

**Comment by javiercn** [comment] 2019-08-23 15:03
@blowdart Not sure what you mean.

We attach the access token to outgoing requests in the angular template, but that's it.
The API is not expected to know personal information about the user, it only receives the access token and should make any security decisions based on the sub claim, which is the user identifier.

Closing this as it is by design. Refer to the Identity Server documentation to change the contents of the token if you want to do so.

**Closed by javiercn** 2019-08-23 15:03 UTC
Labels: area-identity

**Comment by blowdart** [comment] 2019-08-23 17:06
@wjsgzcn To expand on this, yes, this is expected. You can [expand the claims out via scopes](https://stackoverflow.com/questions/41387069/identity-server-4-adding-claims-to-access-token), but because it's all in-app, it's just as easy to use the usermanager.
