### ISSUE TITLE
Razor compiler should give an error for improperly nested tags

### ISSUE THREAD

**Issue by stefan-schweiger** [aspnet/AspNetCore#11590] opened 2019-06-26 12:31 UTC
### Describe the bug
I'm trying to have some conditional tags so I don't have to repeate my code. But when I'm nesting those tags the actual generated code isn't nested anymore.

I'm not certain if this is an intended behavior. But if it is, is there any other way to achieve this?

### To Reproduce
```
@if (ShowWrapper)
{
    @:<div>
}

<span>@Name</span>

@if (ShowWrapper)
{
    @:</div>
}

@code {
    public bool ShowWrapper { get; set; } = true;

    public string Name { get; set; } = "Hi";
}
```

This renders

```
<div></div>
<span>Hi</span>
```

### Expected behavior
I would expect it to render

```
<div>
    <span>Hi</span>
</div>
```

### Additional context
.NET Core 3.0-preview6

**Comment by SteveSandersonMS** [comment] 2019-06-26 14:17
Blazor components compile to code that builds a tree structure, not an HTML string. All tags must be balanced at compile time. You can't put an `@if` around an opening or closing tag on its own.

TBH I'm surprised this case doesn't give you a compiler error saying the tags are unbalanced. Would you have expected that, @rynowak?

The correct way to do what you're doing is:

```razor
@if (ShowWrapper)
{
    <div><span>@Name</span></div>
}
else
{
    <span>@Name</span>
}

@code {
    public bool ShowWrapper { get; set; } = true;

    public string Name { get; set; } = "Hi";
}
```

If your concern is that, instead of just `<span>@Name</span>`, you actually have a lot of markup that you don't want to duplicate like this, you can factor that part out into a child component, just like you'd factor out repeating parts of a C# method into another method that can get called from two places.

**Comment by stefan-schweiger** [comment] 2019-06-26 14:45
@SteveSandersonMS thanks for your answer. This only works with the `@:` syntax, if I just use the tags I'm getting the error you described.

Still it's a bit cumbersome because my real code contains multiple generic RenderFragments which would need to be duplicated in both components so I can cascade my values down.

The next best thing would be to have a [`@helper`](https://docs.microsoft.com/en-us/aspnet/web-pages/overview/ui-layouts-and-themes/creating-and-using-a-helper-in-an-aspnet-web-pages-site)-like or react-like functionallity to write reusable `RenderFragments` (with razor syntax) in a component without having to create them in c# code or another Component.

So something like

```
@if (ShowWrapper)
{
    <div>@Greeter()</div>
}
else
{
    @Greeter()
}

@fragment Greeter {
    <span>@Name</span>
}
```

But it seems this kind of functionality currently isn't on the road, right? https://github.com/aspnet/Blazor/issues/693

**Comment by rynowak** [comment] 2019-06-26 17:18
> TBH I'm surprised this case doesn't give you a compiler error saying the tags are unbalanced. Would you have expected that, @rynowak?

I would expect this to be an error. Reopening this to track the error

**Comment by NTaylorMullen** [comment] 2019-06-26 18:00
The `@:` syntax blindly consumes all markup until end of line. We could disallow `@:` in components because without that functionality it has limited value. Nearly all uses of `@:` today are to get around tag balancing restrictions.

**Comment by SteveSandersonMS** [comment] 2019-06-26 18:02
Disallowing it sounds right.

**Comment by mkArtakMSFT** [comment] 2019-06-27 00:55
Related: https://github.com/aspnet/AspNetCore/issues/11612

**Comment by mkArtakMSFT** [comment] 2019-08-12 17:10
Closing as a dupe of: https://github.com/aspnet/AspNetCore/issues/11612

**Closed by mkArtakMSFT** 2019-08-12 17:10 UTC
Labels: PRI: 1 - Required, area-blazor, bug
