### ISSUE TITLE
Consider support for additional input types in SignalR Client to Server Streaming

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#8292] opened 2019-03-07 18:32 UTC
We had discussed the idea of adding support for additional input types in client to server streaming feature  like streams in C# or blobs/FileReaders in TS, etc.

More context https://github.com/aspnet/AspNetCore/issues/5323#issue-391846533
Even More Context: https://github.com/aspnet/AspNetCore/issues/5316

**Comment by faryu** [comment] 2019-03-07 18:47
In my case I would be very happy if we could use the ChannelReader and Writer just like we do on the server side on the C# client side.
The workaround right now is using larger transfer size limits and paging or to ignore SignalR for this entirely and use a REST API to push data to the server.

**Comment by BrennanConroy** [comment] 2019-03-07 20:04
Isn't this just a dupe?

**Comment by anurse** [comment] 2019-03-25 19:08
Closing a dupe of #5316

**Closed by anurse** 2019-03-25 19:08 UTC
Labels: area-signalr
