### ISSUE TITLE
Error using Blazor Server with Proxy not allowing WebSocket-Connection

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/AspNetCore#14613] opened 2019-10-01 09:30 UTC
After upgrading to the RTM-Version of AspNetCore, the connection-fallback to LongPolling doesn't work again. (this was fixed in Preview7)

Console output is (nothing happens on the screen):

```
WebSocket connection to 'wss://xxx.domain.ext/_blazor?id=zqmUOV0jdiG8Tdz5FhuHCA' failed: Error in connection establishment: net::ERR_SOCKS_CONNECTION_FAILED

Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.

Warning: Call to HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 ().) was ignored because the connection hasn't yet left the in the connecting state.

Error: Failed to start the transport 'LongPolling': TypeError: Cannot set property 'onreceive' of undefined

Error: Failed to start the connection: Error: Unable to connect to the server with any of the available transports. WebSockets failed: Error: There was an error with the transport. ServerSentEvents failed: Error: 'ServerSentEvents' does not support Binary. LongPolling failed: TypeError: Cannot set property 'onreceive' of undefined

Error: Error: Unable to connect to the server with any of the available transports. WebSockets failed: Error: There was an error with the transport. ServerSentEvents failed: Error: 'ServerSentEvents' does not support Binary. LongPolling failed: TypeError: Cannot set property 'onreceive' of undefined

Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:formatted:2228)
    at e.sendMessage (blazor.server.js:formatted:855)
    at e.sendWithProtocol (blazor.server.js:formatted:859)
    at blazor.server.js:formatted:885
    at new Promise (<anonymous>)
    at e.invoke (blazor.server.js:formatted:880)
    at e.<anonymous> (blazor.server.js:formatted:10537)
    at blazor.server.js:formatted:10491
    at Object.next (blazor.server.js:formatted:10504)
    at blazor.server.js:formatted:10410
```

I wish I could give more information.

**Comment by pranavkm** [comment] 2019-10-01 13:35
> Error: Failed to start the transport 'LongPolling': TypeError: Cannot set property 'onreceive' of undefined

/cc @BrennanConroy

**Comment by BrennanConroy** [comment] 2019-10-01 15:05
Dupe of https://github.com/aspnet/AspNetCore/issues/14075

We're fixing this in 3.0.X

**Closed by BrennanConroy** 2019-10-01 15:05 UTC
Labels: area-signalr
