### ISSUE TITLE
Enable helix VSTS test reporting

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#8087] opened 2019-03-01 17:42 UTC
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/Readme.md

```
    <!-- Enable reporting of test results to azure dev ops -->
    <EnableAzurePipelinesReporter>false</EnableAzurePipelinesReporter>
```

cc @anurse

**Comment by natemcmaster** [comment] 2019-04-11 22:49
Closing as duplicate of https://github.com/aspnet/AspNetCore/issues/7368

**Closed by natemcmaster** 2019-04-11 22:49 UTC
Labels: area-infrastructure, blocked
