### ISSUE TITLE
SignalR NPM package breaks Angular app build

### ISSUE THREAD

**Issue by AndrewMayorov** [aspnet/AspNetCore#12279] opened 2019-07-17 15:08 UTC
**Disclaimer:** It related to older `@aspnet/signalr` package, I don't know if it is already fixed in the new one, but for now the package is pretty unusable in Angular/Webpack scenario.

After adding `@aspnet/signalr` project stopped compiling with the error "TS2322: Type 'Timeout' is not assignable to type 'number'."

### To Reproduce
1. Make Angular project that has a call to `setTimeout`:
```
var t: number = setTimeout( () => { console.log( "here" ); }, 1000 );
```
2. Build it with `ng build`
3. It should fail with error TS2322. 

### The cause
`@aspnet/signalr` package has dependency on `@types/node`. If it gets installed, it hijacks the "standard" ambient declarations, so `setTimeout` gets wrong type. Unfortunately it's impossible to tell TypeScript compiler to skip some type, and also the signalr package doesn't want to compile if there is no nodejs types.

**Comment by mkArtakMSFT** [comment] 2019-07-17 18:14
Thanks for contacting us, @AndrewMayorov.
I don't see any easy workaround here. @anurse thoughts?

**Comment by anurse** [comment] 2019-07-17 21:50
We'll look at it

**Comment by anurse** [comment] 2019-07-23 19:58
@AndrewMayorov can you post a runnable sample project that reproduces the issue? Also, are you using the ASP.NET Angular SPA templates or just a standard Angular app?

**Comment by anurse** [comment] 2019-07-23 21:23
I managed to get the repro together. As a workaround (I know it's not ideal) you can override the TypeScript behavior using the below snippet and it should work:

```typescript
let t: number = (setTimeout(() => { console.log("..."); }, 1000)) as unknown as number;
```

Casting to `number` via `unknown` tells TypeScript to ignore the conflict :).

We'll look at a first-class fix though, since that's not ideal.

**Comment by anurse** [comment] 2019-07-23 21:30
Looks like the easiest fix here is for us to remove all our `@types` dependencies from the `devDependencies` section. The assumption was that since they were `devDependencies` they'd only apply to this instance (not when installed as a package) but it seems that's incorrect. The conflict is occurring (as @AndrewMayorov pointed out) because installing `@aspnet/signalr` also brings down the dev dependencies.

**Comment by AndrewMayorov** [comment] 2019-07-24 08:56
Thank you for the answer, @anurse! Workarounds are not a real option here, because we already have tons of code, and this is, after all, a hack. So for now I preferred the workaround with loading SinglarR as an external script. But this also bad, of course.

**Comment by anurse** [comment] 2019-07-24 16:39
Ok, glad to hear you've got some kind of workaround. I realize this is something we need to fix, just want to make sure you can be unblocked as quickly as possible :).

**Comment by BrennanConroy** [comment] 2019-07-25 15:55
@AndrewMayorov  I tried out an `ng new` app and could repro the issue without adding `@aspnet/signalr`.
This is because by default `ng new` comes with a direct reference to `@types/node` and an indirect reference via `@angular-devkit/build-angular`. See https://github.com/angular/angular-cli/issues/13784 for a discussion about that.
After removing both of those deps and then adding `@aspnet/signalr` I couldn't repro the issue.

> After adding `@aspnet/signalr` project stopped compiling with the error "TS2322: Type 'Timeout' is not assignable to type 'number'."

This sounds like your project was working fine before so we'll need some help getting a repro because we can't reproduce it. Would it also be possible to provide your package.lock.json?

**Comment by anurse** [comment] 2019-07-26 20:11
Yeah, I also can't repro this on a plain `package.json` with SignalR installed. I don't think SignalR is the one bringing in `@types/node`. I'm going to close this for now, but if you can share a project that works without `@aspnet/signalr` and doesn't work with `@aspnet/signalr` we can investigate further.

```
> cat .\package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aspnet/signalr": "^1.1.4"
  }
}
> dir .\node_modules\@types
dir : Cannot find path 'C:\Code\anurse\Scratch\test\node_modules\@types' because it does not exist.
At line:1 char:1
+ dir .\node_modules\@types 2>&1 | clip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Code\anurse\Scra\u2026node_modules\@types:String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**Closed by anurse** 2019-07-26 20:11 UTC
Labels: area-signalr, more-info-needed

**Comment by AndrewMayorov** [comment] 2019-07-30 11:32
@anurse, @BrennanConroy, you are right, guys. I also cannot make a fresh project that reproduces the problem. Angular template indeed has `@types/node` in devDependencies, and just removing it is not enough, as Angular build depends on it (via webpack). 

So I have no idea why in our project it behave differently. We don't have explicit reference to node typing, but transient dependency is still there. I will try to reproduce it there.
