### ISSUE TITLE
Test failure: _5_Run

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3685] opened 2018-10-20 02:41 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=33104) with the following error:

```
System.InvalidOperationException : Command dotnet restore /warnaserror --no-cache   returned exit code 1

  Restoring packages for /Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/web.csproj...
/Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/web.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App (>= 2.1.0)' for '.NETCoreApp,Version=v2.1'.
/Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/web.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App (>= 2.1.1)' for '.NETCoreApp,Version=v2.1'.
/Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/web.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Razor.Design (>= 2.1.2)' for '.NETCoreApp,Version=v2.1'.
  Generating MSBuild file /Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/obj/web.csproj.nuget.g.props.
  Generating MSBuild file /Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/obj/web.csproj.nuget.g.targets.
  Restore failed in 183.55 ms for /Users/vsts/agent/2.140.2/work/_temp/tmpnZr6KS.tmp/web/None/none/web.csproj.



```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.1.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-10-20 02:41
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-25 19:31
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 66 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=35365) on release/2.2 at 6:15:37 PM:
- _8_Exec
- _6_Publish
- _3_Build
- _3_Build
- _8_Exec
- _7_PublishIncremental
- _6_Publish
- _6_Publish
- _7_PublishIncremental
- _1_Restore
- (And 56 more test failures in this build)

**Comment by natemcmaster** [comment] 2018-10-29 15:51
Duplicate of #3686

**Closed by natemcmaster** 2018-10-29 15:52 UTC
Labels: Branch:release/2.1, Branch:release/2.2, test-failure
