### ISSUE TITLE
Please update javascript tutorial with proper hub url

### ISSUE THREAD

**Issue by AndersMalmgren** [aspnet/AspNetCore#8305] opened 2019-03-07 23:24 UTC
**UPDATE** 
It still does not work if I remove the trailign / from the url so this works

http://localhost/aspcore/

this does not

http://localhost/aspcore

### Describe the bug
Javascript tutorial suggests a broken URL when deployed to IIS

The tutorial states

```javascript
const connection = new signalR.HubConnectionBuilder()
    .withUrl("/chatHub")
    .configureLogging(signalR.LogLevel.Information)
    .build();

connection.start().then(function () {
    console.log("connected");
});
```

This is all fine while you develop inside VS, but if you deploy to a sub-app in IIS with its own folder it will break. The negotiate url will remove the sub folder. To fix I remove the dash  `.withUrl("chatHub")`

Thanks, Anders

**Comment by muratg** [comment] 2019-03-11 18:26
cc @bradygaster could you take a look please?

**Comment by halter73** [comment] 2019-03-25 18:41
Removing the preceding forward slash could cause issues in other scenarios.

**Comment by anurse** [comment] 2019-03-25 18:41
The doc includes a sample which does work this way. If you are deploying things to a sub-app you will indeed have to change this URL, just as you would other links and URLs in the samples. If the URL passed to `withURL` starts with a `/` it is considered domain-relative.

**Comment by AndersMalmgren** [comment] 2019-03-25 19:30
Doesn't matter if you remove the slash. If you remove the slash from the page URL in the browser is still doesn't work

**Comment by anurse** [comment] 2019-03-25 23:17
No, I mean the leading slash in the `withUrl` call. It's expected that you need to remove this when you're hosting in a subdirectory, otherwise the path is treated as "domain-relative", so it is rooted on the domain that your page is served from. If you don't have a leading slash it's treated as page-relative, so it's rooted from the page.

For example: If your page is at `http://localhost/a/b`

* `.withUrl("/chatHub")` would request `http://localhost/chatHub`
* `.withUrl("chatHub")` would request `http://localhost/a/chatHub`

The sample in the docs is configured to run at the root of the domain, so it uses a leading slash.

**Comment by AndersMalmgren** [comment] 2019-03-25 23:37
Yeah I got that, what I ment was regardless of slash or no slash in hub URL signals breaks if you remove the trailing slash to the page URL. 

So http://mysite.com/subapp/ works, remove trailing slash and It breaks. You can even try here on my demo site for my signalr library

http://malmgrens.org/signalrcore/

It works with trailing slash, will break if you remove it

**Comment by anurse** [comment] 2019-03-26 01:43
Ah, I see. Thanks for clarifying this. GitHub strips trailing slashes from URLs unless you wrap them in back-ticks (\`) like so: `https://mysite.com/subapp/` which was confusing me since your URLs looked the same. I'll reopen this and we'll investigate further.

**Comment by anurse** [comment] 2019-04-12 05:56
Ok, I tried your sample link and I think this behavior is intended. It has to do with how the URL breaks down. SignalR doesn't actually resolve the URL at all, what we do is ask the browser to resolve it, so these rules are defined by your web browser (and specified in [RFC 1808](https://tools.ietf.org/html/rfc1808) if you want a nice long read to help you get to sleep ;)).

Below, I've tried to put a clear explanation of how this works. The short explanation is that this is just how browsers resolve URLs. If you want to support this reliably, the general recommendation is that when a user requests `http://localhost/foo/bar` you **redirect them** to `http://localhost/foo/bar/`.

When I try to reproduce this in our [Chat Sample](https://github.com/aspnet/SignalR-samples/tree/master/ChatSample) by changing the `launchSettings.json` to put the app in a sub folder (`http://localhost:1234/subapp` for example), I see that I'm automatically redirected from `http://localhost:1234/subapp` to `http://localhost:1234/subapp/` (with the trailing slash). That logic is built in to the [static files middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2). If you're using something like Razor Pages, you may need to build your own redirect logic in.

I'm going to close this issue since it's not something we control in SignalR (it's a browser behavior). Adding a redirect is my recommendation to fix this issue if it's important to your scenario.

Below is a more detailed explanation of why this happens:

Basically, the URL is always split at the **last `/` in the URL** to get the **Base URL** which is used to resolve all relative links, the rest (the last path segment) is the **Page URL**. These rules only apply when the URL you provide to SignalR **does not have a `/` at the start**. If you put a `/` at the start, it'll always be relative to the **root of the domain**.

Consider a URL like `http://malmgrens.org/signalrcore/foo.html` (this is just an example), the URL is split into two parts:
* The **Base URL** is `http://malmgrens.org/signalrcore`
* The **Page URL** is `index.html`

When you give the URL `EventAggregatorProxyHub` to SignalR, since it **does not start with a `/`**, the browser puts the **Base URL** in front of it, and gets `http://malmgrens.org/signalrcore/EventAggregatorProxyHub`, which **works**.

Now consider the URL `http://malmgrens.org/signalrcore/`. It splits into two parts like this
* The **Base URL** is `http://malmgrens.org/signalrcore`
* The **Page URL** is **an empty string**

Again, when you give the URL `EventAggregatorProxyHub` to SignalR, the browser puts the **Base URL** in front of it, and gets `http://malmgrens.org/signalrcore/EventAggregatorProxyHub`, which **works**.

However, when you have the URL `http://malmgrens.org/signalrcore` (without the trailing `/`), it splits like this:
* The **Base URL**  is **`http://malmgrens.org`** (because there is no trailing slash!)
* The **Relative URL** is **`signalrcore`**

Once again, the browser resolves `EventAggregatorProxyHub` by putting the **Base URL** in front and you get `http://malmgrens.org/EventAggregatorProxyHub` which **does not work**!

**Closed by anurse** 2019-04-12 05:56 UTC
Labels: area-signalr, investigate
