### ISSUE TITLE
VS2019 How to Build a Web API2 for .Net Framework 4.8

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14932] opened 2019-10-11 17:55 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/758689/vs2019如何建立net-framework48的web-api2.html)._

---
(Regression)
(worked-in:16.3)
1. Building a project

2. Only .Net Core 2.2, .Net Core 3.0 API

Hope to join back .Net Framework 4.8 Web API 2
Reason:
Because there are problems with both .Net Core 2.2 and 3.0 APIs, Establish the initial Web API Core, keep reorganizing the call Get API, memory will only keep going up, not down, .Net Framework Web API 2 without this issue

---
#### Visual Studio Feedback System on 10/3/2019, 01:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### s52076663135 on 10/8/2019, 06:38 PM: 

感恩，我重新安裝了VS2019，.Net Framework 4.8 Web API 2 有出現，但 .Net Core 2.2 與 3.0 API 記憶體上升問題，依舊無法得到解答
#### Visual Studio Feedback System on 10/11/2019, 00:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2019-10-11 17:56
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Alan-Lun** [comment] 2019-10-12 02:11
我有在這邊也有留言
https://github.com/dotnet/corefx/issues/41669

.Net Core 2.2 API
Memory
https://imgur.com/Gri252Z

.Net Core 2.2 Console 安裝 https://www.nuget.org/packages/Quartz/
Memory
https://imgur.com/sZ2KSuX

.Net Core 2.2 Razor Page 和 MVC
Memory
https://imgur.com/53J9bUg

我有設定 csproj ，Memory 上漲速度有減緩但依舊無法停止每天上漲的 Memory，都不會降下來
<ServerGarbageCollection>false</ServerGarbageCollection>

.Net Core 3.0 初始API 也有此狀況 , 記憶體不會下降到原本
https://imgur.com/lavFW6r

----------------------------------------------

有使用 Visual Studio，也有看dotMemory
但看不出來為什麼飆升
https://imgur.com/xJfcjpP

我看其他文章也有此問題
https://stackoverflow.com/questions/51388701/asp-net-core-memory-inscrease-on-every-request-and-gc-does-not-free-it

https://stackoverflow.com/questions/57591344/why-asp-net-core-2-2-do-not-release-memory

https://chat.stackoverflow.com/rooms/198268/discussion-on-question-by-kevin-tanudjaja-why-asp-net-core-2-2-do-not-release-me

aspnet/AspNetCore#6102 (comment)

**Comment by Alan-Lun** [comment] 2019-10-12 02:17
像現在 (2019/10/12)
.Net Core 2.2 Console 安裝 https://www.nuget.org/packages/Quartz/
https://imgur.com/6gWNkLb

**Comment by mkArtakMSFT** [comment] 2019-10-12 13:56
Thanks @Alan-Lun.
It seems there's already investigation happening on the corefx repo. Not to duplicate the effort, we're closing this issue. If it turns out that the problem is caused by ASP.NET Core, @danmosemsft will transfer the issue from corefx to here and we'll use the transferred issue instead.

**Closed by mkArtakMSFT** 2019-10-12 13:56 UTC
Labels: area-mvc, investigate
