### ISSUE TITLE
Error in Blazor (ASP.NET Core hosted) template

### ISSUE THREAD

**Issue by aadamsx** [aspnet/AspNetCore#11387] opened 2019-06-19 18:32 UTC
Ran the following steps:

1) .NET Core 3.0 Preview 6 SDK (3.0.100-preview6-012264)
2) Visual Studio Preview (16.2 Preview 2 or later) with the ASP.NET and web development workload selected.
3) The latest Blazor extension from the Visual Studio Marketplace.
4) The Blazor templates on the command-line:
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2

Then used the Blazor (ASP.NET Core hosted) template.

Without touching the code, just doing 

1) Restore NuGet packages 
2) built Shared project
3) build the Client project

I get the following error inside the Client project:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ9980	Unclosed tag 'WeatherForecast' with no matching end tag.	Blazor.Client	C:\Users\AAdams1\Repos\FullStackBlazor2\Blazor.Client\Pages\FetchData.razor	43	
```

**Comment by mkArtakMSFT** [comment] 2019-06-19 22:35
Thank you for filing this issue. We are unable to reproduce this issue.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by herrozerro** [comment] 2019-06-20 02:04
I am also having this issue, here is a repo.

https://github.com/herrozerro/singularity-lathe

![image](https://user-images.githubusercontent.com/2041213/59813096-db831100-92d5-11e9-9bf2-a6cede2f6376.png)

**Comment by mkArtakMSFT** [comment] 2019-06-20 17:16
Thanks @herrozerro. Looks like your repo is private. Can you please move the repro to a public repo so we can get to it?

**Comment by herrozerro** [comment] 2019-06-20 18:14
@mkArtakMSFT it should be public now.

**Comment by mkArtakMSFT** [comment] 2019-06-20 21:59
@herrozerro, I'm unable to repro it using your repo. It successfully builds for me:
![image](https://user-images.githubusercontent.com/34246760/59883988-ade8a700-936b-11e9-8908-56177abbebf3.png)
![image](https://user-images.githubusercontent.com/34246760/59883996-b345f180-936b-11e9-8a3f-838a8b9fb466.png)

Can you open the `Package Manager Console` when you have the project loaded, and run `dotnet --version` and you should see:
![image](https://user-images.githubusercontent.com/34246760/59884047-e38d9000-936b-11e9-8b04-b0f04f490e6f.png)

**Comment by herrozerro** [comment] 2019-06-20 23:58
That was it, I updated blazor but not .net core.

**Comment by isaac2004** [comment] 2019-06-21 13:33
@mkArtakMSFT FYI I see this issue building from source and running a template from source. The main painpoint is that it works on BlazorFiddle

**Comment by mkArtakMSFT** [comment] 2019-06-21 15:52
@isaac2004 I'm going to try this out and get back to you.

**Comment by mkArtakMSFT** [comment] 2019-07-03 15:50
Talked to @isaac2004 on this and he is going to try to repro one more time. Seems like he also feels like this is not an issue any more, but waiting for confrirmation.

**Comment by axa88** [comment] 2019-07-15 17:01
new to blazor, web in general.
Just updated latest VS and Blazor extension (see version below)

Followed directions to set up a client side application from here:
[https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio]

Ran the template as is, got the same error.
RZ9980	Unclosed tag 'WeatherForecast' with no matching end tag.


![image](https://user-images.githubusercontent.com/13371986/61234047-15daa500-a700-11e9-85e1-814b5aa1b5fe.png)


`Microsoft Visual Studio Community 2019 Preview
Version 16.2.0 Preview 3.0
VisualStudio.16.Preview/16.2.0-pre.3.0+29021.104
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

ASP.NET and Web Tools 2019   16.2.226.19058
ASP.NET and Web Tools 2019

ASP.NET Core Blazor Language Services   16.0.19307.2

ASP.NET Web Frameworks and Tools 2019   16.2.226.19058
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.226.19058
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.2.226.19058
Azure Functions and Web Jobs Tools

C# Tools   3.2.0-beta3-19312-05+5905d757a89126ebbcdb383b1a10cadda8c6fdc3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.1.1   Build 191.0.20190501.122851
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.11170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10610.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.0-beta3-19312-05+5905d757a89126ebbcdb383b1a10cadda8c6fdc3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19306.3+3de631a4ba0f54953bad33661008d39fb6df7669
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers`

**Comment by mkArtakMSFT** [comment] 2019-07-15 21:26
@isaac2004, I'm closing this. Please reopen if you'll face this issue again.

**Closed by mkArtakMSFT** 2019-07-15 21:26 UTC
Labels: area-blazor, investigate, more-info-needed

**Comment by isaac2004** [comment] 2019-07-18 12:37
@maulinshah1015 do you have the latest blazor template?

**Comment by AYanuseuskaya** [comment] 2019-08-15 13:00
Good day! I decided to try creating a Blazor WebAssembly App project template. Everything was done as it is written here - https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio. At Press F5 to run the app a blank page opens with an inscription in the upper left corner Loading.
SDK - 3.0.100 - preview8-013656
Visual Studio Community 2019 Preview 16.3.0 Preview 2.0
In Output VS i see -
Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:49566/_framework/blazor.boot.json]
SyntaxError: Unexpected end of JSON input
at Object. (http://localhost:49566/_framework/blazor.webassembly.js:1:30734)
at http://localhost:49566/_framework/blazor.webassembly.js:1:30237
at Object.next (http://localhost:49566/_framework/blazor.webassembly.js:1:30342)
at i (http://localhost:49566/_framework/blazor.webassembly.js:1:29088)
The program '' has exited with code -1 (0xffffffff).
The program '[3548] dotnet.exe' has exited with code -1 (0xffffffff).
I tried to run like this - For a Blazor client-side experience, execute the following commands in a command shell:
dotnet new blazorwasm -o WebApplication1
cd WebApplication1
dotnet run
The result is the same. Help, please! I can’t do anything, because I stopped at the very beginning.

**Comment by mkArtakMSFT** [comment] 2019-08-15 16:05
Hi.

**It looks like you are posting on a closed issue!**
We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
