### ISSUE TITLE
API default template opens invalid url by default

### ISSUE THREAD

**Issue by neville-nazerane** [aspnet/AspNetCore#12503] opened 2019-07-24 07:05 UTC
### Describe the bug
While the new template no longer has the ValuesController and only has a WeatherForecastController controller, when you run the API, the default url is "api/values" by default, which returns a 404.

### To Reproduce
1. Create a new .net core web API 3.0
2. Run the application 

### Expected behavior
By default, it points to /WeatherForecast

**Comment by mkArtakMSFT** [comment] 2019-07-24 15:54
Thanks for contacting us, @neville-nazerane.
This is a known issue with preview7 release, and the fix is coming in Preview8. The fix is trivial and it's to update the launchSettings.json to reflect the correct path, as was done in the fix for it: https://github.com/aspnet/AspNetCore/pull/11753/files#diff-dda1b7b71a5698180e79d02c5401d65fR24

**Comment by mkArtakMSFT** [comment] 2019-07-24 15:54
Dupe of https://github.com/aspnet/AspNetCore/issues/11699

**Closed by mkArtakMSFT** 2019-07-24 15:54 UTC
