### ISSUE TITLE
[Test Failure] DATA_Sent_TooSlowlyDueToFlowControlOnSmallWrite_AbortsConnectionAfterGracePeriod

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7142] opened 2019-01-30 20:39 UTC
```
2019-01-30T19:45:19.0396496Z   Failed   DATA_Sent_TooSlowlyDueToFlowControlOnSmallWrite_AbortsConnectionAfterGracePeriod
2019-01-30T19:45:19.0397293Z   Error Message:
2019-01-30T19:45:19.0397599Z    Moq.MockException : 
2019-01-30T19:45:19.0397979Z   Expected invocation on the mock once, but was 0 times: h => h.OnTimeout(TimeoutReason.WriteDataRate)
2019-01-30T19:45:19.0399650Z   
2019-01-30T19:45:19.0400642Z   Configured setups: 
2019-01-30T19:45:19.0400930Z   ITimeoutHandler h => h.OnTimeout(It.IsAny<TimeoutReason>())
2019-01-30T19:45:19.0401213Z   No invocations performed.
2019-01-30T19:45:19.0401504Z   Stack Trace:
2019-01-30T19:45:19.0401813Z      at Moq.Mock.VerifyCalls(Mock targetMock, InvocationShape expectation, LambdaExpression expression, Times times, String failMessage)
2019-01-30T19:45:19.0402107Z      at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
2019-01-30T19:45:19.0402563Z      at Moq.Mock`1.Verify(Expression`1 expression, Times times)
2019-01-30T19:45:19.0402827Z      at Moq.Mock`1.Verify(Expression`1 expression, Func`1 times)
2019-01-30T19:45:19.0403165Z      at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TimeoutTests.DATA_Sent_TooSlowlyDueToFlowControlOnSmallWrite_AbortsConnectionAfterGracePeriod() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TimeoutTests.cs:line 420
2019-01-30T19:45:19.0404335Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-30T19:45:19.0404804Z   Standard Output Messages:
2019-01-30T19:45:19.0405696Z    | [0.000s] TestLifetime Information: Starting test DATA_Sent_TooSlowlyDueToFlowControlOnSmallWrite_AbortsConnectionAfterGracePeriod at 2019-01-30T19:45:18
2019-01-30T19:45:19.0406217Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
2019-01-30T19:45:19.0406497Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
2019-01-30T19:45:19.0406761Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
2019-01-30T19:45:19.0407007Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
2019-01-30T19:45:19.0407269Z    | [0.036s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received HEADERS frame for stream ID 1 with length 318 and flags END_HEADERS
2019-01-30T19:45:19.0407540Z    | [0.036s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received DATA frame for stream ID 1 with length 12 and flags END_STREAM
2019-01-30T19:45:19.0407811Z    | [0.038s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id ":00000001": started reading request body.
2019-01-30T19:45:19.0408070Z    | [0.038s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending HEADERS frame for stream ID 1 with length 37 and flags END_HEADERS
2019-01-30T19:45:19.0408317Z    | [0.038s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending DATA frame for stream ID 1 with length 6 and flags NONE
2019-01-30T19:45:19.0408596Z    | [0.053s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)" is closed. The last processed stream ID was 1.
2019-01-30T19:45:19.0408833Z    | [0.065s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
2019-01-30T19:45:19.0409255Z    | [0.073s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "(null)", Request id ":00000001": An unhandled exception was thrown by the application.
2019-01-30T19:45:19.0412415Z    | System.IO.IOException: The request stream was aborted. ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
2019-01-30T19:45:19.0412725Z    |    --- End of inner exception stack trace ---
2019-01-30T19:45:19.0412862Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ValidateState(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestStream.cs:line 217
2019-01-30T19:45:19.0413026Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestStream.cs:line 111
2019-01-30T19:45:19.0413184Z    |    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
2019-01-30T19:45:19.0413739Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.<>c.<<-ctor>b__52_10>d.MoveNext() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 228
2019-01-30T19:45:19.0414016Z    | --- End of stack trace from previous location where exception was thrown ---
2019-01-30T19:45:19.0414124Z    |    at Microsoft.AspNetCore.Testing.DummyApplication.ProcessRequestAsync(HttpContext context) in /_/src/Servers/Kestrel/shared/test/DummyApplication.cs:line 45
2019-01-30T19:45:19.0414240Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 565
2019-01-30T19:45:19.0414362Z    | [0.074s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id ":00000001": done reading request body.
2019-01-30T19:45:19.0414464Z    | [0.073s] TestLifetime Information: Finished test DATA_Sent_TooSlowlyDueToFlowControlOnSmallWrite_AbortsConnectionAfterGracePeriod in 0.0726913s
```
https://dev.azure.com/dnceng/public/_build/results?buildId=83296

**Comment by jkotalik** [comment] 2019-02-08 02:39
Another one: https://dev.azure.com/dnceng/public/_build/results?buildId=90177

**Comment by anurse** [comment] 2019-03-27 19:34
Duplicate of https://github.com/aspnet/AspNetCore-Internal/issues/1323

**Closed by anurse** 2019-03-27 19:34 UTC
Labels: area-servers, release-3.0, servers-kestrel
