### ISSUE TITLE
Razor engine crashing while editing a .cshtml file

### ISSUE THREAD

**Issue by Parrawk** [aspnet/AspNetCore#15074] opened 2019-10-16 17:28 UTC
### Description
I've been having this issue with the razor engine crashing constantly while editing .cshtml files, it ends with a popup "The Razor Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.".

I haven't been able to reproduce it, sometimes it does it instantly, sometimes it takes hours, last time it happened I just added a css class to a span element in a ASP.NET Core 3 project. I'm using VSCode on a Windows 8.1 machine.

I have tried completely reinstalling the extension, erasing the folder, but it keeps doing it.

### To Reproduce
Haven't been able to reproduce it, I tried the Report a Razor issue, but the error didn't happen again.
Happens randomly when editing the document, last time I was adding a class, and before that I was editing a C# variable between @{ }

### Expected behavior
To not crash randomly.

### Additional context
Last time I caught the error this is what I got:

`Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 12:10:02] Connection to server got closed. Server will not be restarted.`

**Comment by NTaylorMullen** [comment] 2019-10-16 18:55
@Parrawk would you mind turning `razor.trace` to `Verbose` and then the next time it happens sharing your `Razor Log`?

**Comment by Parrawk** [comment] 2019-10-17 17:41
@NTaylorMullen Sorry for the late response, today I got the error again and this is the razor log and the file I was editing.

[GIST](https://gist.github.com/Parrawk/d2eee2dcf16654ad50b0cacf6b390171)

**Comment by NTaylorMullen** [comment] 2019-10-18 16:44
@Parrawk thanks for the Razor log! This looks to be a duplicate of https://github.com/aspnet/AspNetCore/issues/14324

**Closed by NTaylorMullen** 2019-10-18 16:44 UTC
Labels: area-mvc, duplicate, more-info-needed
