### ISSUE TITLE
Improve logging for SignInManager

### ISSUE THREAD

**Issue by lukepuplett** [aspnet/AspNetCore#11146] opened 2019-06-12 19:12 UTC
### Is your feature request related to a problem? Please describe.
The `SignInManager` does not log enough information for productive troubleshooting.

For example, `GetExternalLoginInfoAsync` returns a `null` which is questionable anyway, but has various points where it bails out, none of which are logged. Consequently, tricky problems with OAuth/identity which are complicated anyway, are made much harder to analyse.

### Describe the solution you'd like
I could do this myself??! I don't know what the community thinks about a good logging approach so I am suggesting it instead of PR-ing my own edits.

I'd like to see more debug logging around the decision making esp. at points where execution can bail out of the happy path.

### Describe alternatives you've considered
None.

### Additional context
See the steps I had to take over the course of a few evenings to diagnose a problem where the Google middleware isn't pulling out the required fields from my Google+ user account JSON.

https://stackoverflow.com/a/56551438/107783

Remember, this code returns a `null` without reason and with no logging. It's not great.

**Comment by blowdart** [comment] 2019-06-12 20:04
We're open to suggestions here. We err on the not logging because of concerns around logging personal information and people not protecting logs. Community consensus would be good :)

**Comment by lukepuplett** [comment] 2019-06-13 09:43
Thanks Barry. It appears `GetExternalLoginInfoAsync` is the main offender in that class. The other `return null` statements appear to have logging, e.g.

https://github.com/aspnet/AspNetCore/blob/ea2f35c45ee49dd4f8457770f08fac6c0682e953/src/Identity/Core/src/SignInManager.cs#L271

So just some debugging, a succinct reason for returning null between lines 638 to 665 would suffice.

**Comment by HaoK** [comment] 2019-07-02 06:32
Dupe of https://github.com/aspnet/AspNetCore/issues/7155 which was fixed in preview7

**Closed by HaoK** 2019-07-02 06:32 UTC
Labels: area-identity
