### ISSUE TITLE
Malformed HTTP Request causes InvalidDataException and 500

### ISSUE THREAD

**Issue by pgrm** [aspnet/AspNetCore#13927] opened 2019-09-12 14:13 UTC
### Describe the bug

We received a random request with the following content type: `Content-Type: multipart/form-data;`

The result was status code 500 with the following exception: `System.IO.InvalidDataException: Missing content-type boundary.`

I believe the error is coming from https://github.com/aspnet/AspNetCore/blob/4ef204e13b88c0734e0e94a1cc4c0ef05f40849e/src/Http/Http/src/Features/FormFeature.cs#L316

The application is running in a docker container, using `FROM mcr.microsoft.com/dotnet/core/aspnet:2.2` as the base

### Expected behavior

I think the correct response should be status code 400, as a publicly available service shouldn't fail if random http clients send malformed requests.

Thanks

**Comment by pgrm** [comment] 2019-09-16 08:51
@Tratcher I tried to understand what exactly was going on. Fact is - that action where the client tried to submit the form is `GET`-only but maybe this stack trace helps you?

```
System.IO.InvalidDataException: Missing content-type boundary.
   at Microsoft.AspNetCore.Http.Features.FormFeature.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

there was also another request that was caught by our identity server middleware:

````
IdentityServer4.Hosting.IdentityServerMiddleware|FATAL|Unhandled exception: Missing content-type boundary. System.IO.InvalidDataException: Missing content-type boundary.
   at Microsoft.AspNetCore.Http.Features.FormFeature.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
````

hope you can find all the information you need in those call stacks

**Comment by Tratcher** [comment] 2019-09-16 14:45
> that action where the client tried to submit the form is GET-only

Was the client malicious?

Indeed `Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory` is part of the MVC model binder. Moving this to you @rynowak. It's a little weird MVC even routed the POST to a GET endpoint.

**Comment by mkArtakMSFT** [comment] 2019-09-16 16:45
This is a dupe of #10291

**Closed** 2019-09-16 16:45 UTC
Labels: area-mvc
