### ISSUE TITLE
[Blazor][Preview-8] Server-side deployed blazor.server.js throwing error on invoking StartCircuit

### ISSUE THREAD

**Issue by glararan** [aspnet/AspNetCore#13354] opened 2019-08-22 21:21 UTC
### Describe the bug
Localhost works fine. Deployed throws in browser:
`blazor.server.js:1 Uncaught (in promise) Error: An unexpected error occurred invoking 'StartCircuit' on the server.`

`[2019-08-22T21:06:44.121Z] Error: Circuit not initialized.`

No blazor function is working anylonger.

App is simple.. using buttons to change int value and use few conditions to show content.

### To Reproduce
1. Using this version of ASP.NET Core 'SDK 3.0.100-preview8-013656'
2. Create server side Blazor project with individual auth
3. Deploy on server using self-contained win-x64
4. See error in browser console

### Expected behavior
No error.

BUILDING MACHINE
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

**Comment by pranavkm** [comment] 2019-08-23 02:07
What do the server logs say?

**Comment by vaheeds** [comment] 2019-08-24 10:14
I have the same issue. it works fine on localhost, but after deployment, database inserts do not work.

  ```
blazor.server.js:1 Uncaught (in promise) Error: An unexpected error occurred invoking 'StartCircuit' on the server.
    at t.callbacks.<computed> (blazor.server.js:1)
    at e.processIncomingData (blazor.server.js:1)
    at e.connection.onreceive (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at s (blazor.server.js:1)
t.callbacks.<computed> @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:8
s @ blazor.server.js:8
Promise.then (async)
c @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
m @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
n @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
blazor.server.js:15 [2019-08-24T10:05:58.716Z] Error: Circuit not initialized.
e.log @ blazor.server.js:15
E @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.poll @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.connect @ blazor.server.js:1
e.startTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.createTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startWithStateTransitions @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
w @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
m @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
n @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
Show 39 more frames
blazor.server.js:1 [2019-08-24T10:05:58.730Z] Information: Connection disconnected.
```

**Comment by pranavkm** [comment] 2019-08-24 18:34
I'm unable to reproduce this. Can you look at the server logs and see if there are issues with EF migrations?

**Comment by ElectricHavoc** [comment] 2019-08-24 21:43
I just got the same thing setting up a devops demo for local user group: 

- Preview 8
- default blazor server side project with identity
- win-x86 / self contained
- azure devops > publish to azure using run from package deployment

Clearing out and trying again without identity...
Removing identity apparently solved the issue with no changes to the devops pipelines.

Hopefully this helps narrow it down.

FYI The new proj has no References, the old one had the following, some I added in trying to debug (the Azure ones per some older blog entry)

```  
    <PackageReference Include="Microsoft.AspNetCore.AzureAppServices.HostingStartup" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.AzureAppServicesIntegration" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.0.0-preview8.19405.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview8.19405.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="2.2.5" />

**Comment by glararan** [comment] 2019-08-27 10:59
I figured it out!

Its broken by IIS Application Pool.. after setting it correctly it started working.
Default application pool is not working.

**Comment by pranavkm** [comment] 2019-08-28 22:34
@ElectricHavoc if you'd like you could [try our](https://github.com/aspnet/AspNetCore#how-to-engage-contribute-and-give-feedback) preview9 nightlies. I'm unable to reproduce this issue with the steps that you specified our most recent build.

Closing this since it doesn't look like there's anything to fix here.

**Closed by pranavkm** 2019-08-28 22:34 UTC
Labels: area-blazor, investigate

**Comment by Jazzman82** [comment] 2019-09-03 09:06
@glararan What did you do to resolve this? I have the same problem after deploying to azure...
Can I configure the settings in the portal as you did?

**Comment by Jazzman82** [comment] 2019-09-03 10:45
Ok! I figured it out: You have to turn on "Websockets" in the Azure Portal: App-Services => Configuration => General Settings

**Comment by IoanaEmma** [comment] 2019-09-09 11:25
> I figured it out!
> 
> Its broken by IIS Application Pool.. after setting it correctly it started working.
> Default application pool is not working.

Can you please give me more details about setting IIS Application Pool correctly?

**Comment by glararan** [comment] 2019-09-09 11:29
> > I figured it out!
> > Its broken by IIS Application Pool.. after setting it correctly it started working.
> > Default application pool is not working.
> 
> Can you please give me more details about setting IIS Application Pool correctly?

StartMode: AlwaysRunning (i guess not needed)
.NET CLR: v4.0
Identity: ApplicationPoolIdentity
Load User Profile: true
Regular Time Interval: 0
Managed pipeline mode: Integrated
