### ISSUE TITLE
Identity errors not displayed properly when using UseStatusCodePagesWithReExecute

### ISSUE THREAD

**Issue by badamsdev** [aspnet/AspNetCore#5792] opened 2018-05-21 15:36 UTC
When using UseStatusCodePagesWithReExecute, custom error StatusCodes like those found in GenerateRecoveryCodes.cshtml.cs do not display using the route as defined by UseStatusCodePagesWithReExecute  in the startup config.

Eg. `return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");` 

Retuning a `StatusCode(404)` without an object displays fine in the custom error layout, but when returned with an object like `StatusCode(404, "Custom message...")`, it's returned as a string result.

**Comment by blowdart** [comment] 2019-07-24 20:32
Closing as by design in MVC

**Closed by blowdart** 2019-07-24 20:32 UTC
Labels: area-identity
