### ISSUE TITLE
"embedded file manifest" exception when starting blazor project on macOS

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#9360] opened 2019-04-14 04:10 UTC
Using latest preview 5 nightly on macOS, create a new project:

"dotnet new blazor"

Run it with "dotnet run"

It gives an exception on startup:

System.InvalidOperationException: Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'Microsoft.AspNetCore.Components.Server'.

**Comment by mkArtakMSFT** [comment] 2019-04-17 21:21
Thanks for contacting us, @tn-5.
Closing this issue as a dupe of #9402

**Closed by mkArtakMSFT** 2019-04-17 21:21 UTC
Labels: area-mvc, feature-Components
