### ISSUE TITLE
InProcess hosting does not support auto rebuild

### ISSUE THREAD

**Issue by Suchiman** [aspnet/AspNetCore#9371] opened 2019-04-14 21:51 UTC
### Describe the bug
If you use `InProcess` hosting in Visual Studio, then starting without debugging does no longer auto rebuild when you make a change, save and refresh in the browser. Since `InProcess` hosting is the default with 2.2, this feature doesn't work anymore by default since 2.2.

### To Reproduce
1. Create an ASP.NET Core 2.2 API App
2. Start without debugging (CTRL + F5)
3. See the browser opening printing `["value1", "value2"]`
4. Change `value2` to `value3` in the `ValuesController`, save, and press F5 in the browser
5. It still prints `["value1", "value2"]`

### Expected behavior
It should now print `["value1", "value3"]`.
Change to `OutOfProcess` hosting and repeat steps 2 - 5 and it will print `["value1", "value3"]`

Also see https://stackoverflow.com/questions/53887157/how-to-enable-automatic-rebuild-in-asp-net-core-2-2-when-i-refresh-page-in-the-b

**Comment by proxseas** [comment] 2019-04-14 21:56
This is pretty important, for convenience purposes. I was affected by this because 'InProcess' was the default setting in 2.2.

**Comment by jkotalik** [comment] 2019-04-15 15:43
Yep, this is a known regression. A fix for this should be in VS 16.1. If you are using preview builds, this should be available in 16.1-preview2.

**Comment by jkotalik** [comment] 2019-04-16 19:11
Closing as this is fixed in 16.1-preview2 and verified.

**Closed by jkotalik** 2019-04-16 19:11 UTC
Labels: area-servers
