### ISSUE TITLE
Limit response compression based on response size

### ISSUE THREAD

**Issue by francisminu** [aspnet/AspNetCore#9087] opened 2019-04-04 22:13 UTC
### Is your feature request related to a problem? Please describe.
I am using the AddResponseCompression available in ASP.NET Core.
The issue I am facing now is, even if the response size is too small, the response is being compressed. Is it possible to limit compression based on the response size?

### Describe the solution you'd like
Add a parameter to the AddResponseCompression, namely Size (similar to EnableForHttps) which stops compression if the response size is less than the specified Size value.

### Additional context
We were using the below package earlier,
https://github.com/azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression
They seem to have the ability to pass in a value, based on which it halts the compression process.

**Comment by francisminu** [comment] 2019-04-04 22:16
I meant to say, Add options either in AddResponseCompression (not GzipCompressionProviderOptions, in which case it will have to be added to every provider separately).

**Comment by Tratcher** [comment] 2019-04-04 22:41
Duplicate of https://github.com/aspnet/AspNetCore/issues/5994

**Closed** 2019-04-04 22:43 UTC
Labels: ResponseCompressionMiddleware, area-middleware
