### ISSUE TITLE
Dotnet Core 3.0 - Only one in-process application is allowed per IIS application pool.

### ISSUE THREAD

**Issue by yannnis** [aspnet/AspNetCore#15371] opened 2019-10-24 12:39 UTC
Hi . I upgraded one of my projects to .net core 3.0 This has stopped working as expected (as with dotnet core 2.2). I get this error in my error page.

Only one in-process application is allowed per IIS application pool. 

Why is that?

**Comment by javiercn** [comment] 2019-10-24 13:41
@yannnis thanks for contacting us.

@jkotalik Can you provide details?

**Comment by Tratcher** [comment] 2019-10-24 14:56
The 3.0 default changed from OutOfProcess to InProcess. If you're running multiple apps together then you'll need to switch back to OutOfProcess.

**Comment by yannnis** [comment] 2019-10-24 15:30
So its actually interesting. We got a staging server with dotnet 2.2 runtime installed 

![image](https://user-images.githubusercontent.com/581650/67500496-6bbdd200-f68b-11e9-845a-ce49fc8d5247.png)

This is whats installed in terms of .net core IIS modules on this server

![image](https://user-images.githubusercontent.com/581650/67500628-a4f64200-f68b-11e9-9615-2e3e961048db.png)

The application works fine there.

On the prod server however - where we are facing this problem - we dont have dotnet runtime installed.

![image](https://user-images.githubusercontent.com/581650/67500814-ec7cce00-f68b-11e9-9357-63efd2317b46.png)

IIS modules are the same as above.

The application in these servers is the same (compiled once through our build environment) with different .net core environment config. App is .net core 3.0 Release / Self-Contained build.

**Comment by jkotalik** [comment] 2019-10-24 15:34
There is a difference between not have the runtime and not having the SDK installed; from the last image, it does look like you have the runtime but not the sdk, which is expected when installing the hosting bundle. Are each of your applications in a separate application pool?

**Comment by yannnis** [comment] 2019-10-24 15:39
So I have two apps sharing an application pool on the first machine but
this didnt work in the second machine so I had to create one app pool per
app

**Comment by anurse** [comment] 2019-11-05 21:14
Closing as I believe the question is answered, let me know if that's not the case. The InProc hosting model doesn't support multiple apps per app pool by design.

**Closed by anurse** 2019-11-05 21:14 UTC
Labels: area-servers, question, servers-iis
