### ISSUE TITLE
"Unexpected token" error in React app with authentication created with ASP.NET Core 3.0 Preview 3

### ISSUE THREAD

**Issue by loop-evgeny** [aspnet/AspNetCore#8281] opened 2019-03-07 16:32 UTC
### Describe the bug
An error occurs as soon as you start an app created using the React app template with authentication.

### To Reproduce
1. Using this version of ASP.NET Core '3.0 Preview 3'
2. Create a new project with `dotnet new react --auth Individual`
3. Build and run the project with VS 2019
4. See error:

```
×
Error: Module build failed: SyntaxError: C:/W ork/Play/ReactTest1/ClientApp/src/components/api-authorization/ApiAuthorizationConstants.js: Unexpected token (27:25)

  25 |   DefaultLoginRedirectPath: '/',
  26 |   ApiAuthorizationClientConfigurationUrl: `/_configuration/${ApplicationName}`,
> 27 |   ApiAuthorizationPrefix = prefix,
     |                          ^
  28 |   Login: `${prefix}/${LoginActions.Login}`,
  29 |   LoginFailed: `${prefix}/${LoginActions.LoginFailed}`,
  30 |   LoginCallback: `${prefix}/${LoginActions.LoginCallback}`,
```

### Expected behavior
No error.

### Additional context
The error is fixed by changing `=` to `:` on the offending line. (Though the app still fails with another error - bug to follow.)

`dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment] 2019-03-07 17:52
@javiercn

**Comment by mkArtakMSFT** [comment] 2019-03-07 17:58
Thanks for contacting us, @loop-evgeny.
@javiercn, can you please look into this, as this seems to be related to the new SPA templates area.

**Comment by javiercn** [comment] 2019-03-07 18:28
@mkArtakMSFT Yeah, I just ran into this as I was poking through the area. I'm already fixing it as part of some improvements to this template.

**Comment by Amine-Smahi** [comment] 2019-03-10 09:21
To fix this error change the content of ApiAuthorizationConstants.js file 
from
`ApiAuthorizationPrefix = prefix,`
to
`ApiAuthorizationPrefix: prefix,`

@mkArtakMSFT @javiercn

**Comment by javiercn** [comment] 2019-03-11 15:24
Thanks for contacting us. This is a known issue. Check out the known issues for our preview3 release at https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md for details on how to workaround it.

**Comment by guyng** [comment] 2019-03-18 20:11
@javiercn can you post a workaround for the angular template? i believe the issue is similar.
#8598
ty.

**Comment by javiercn** [comment] 2019-03-20 08:50
This is fixed now.

**Closed by javiercn** 2019-03-20 08:50 UTC
Labels: area-identity, identity-service, investigate
