### ISSUE TITLE
Application shutdown on Ctrl-C (SIGTERM)

### ISSUE THREAD

**Issue by RoySalisbury** [aspnet/AspNetCore#5940] opened 2018-10-05 18:33 UTC
I have 2 hosted services running within my ASPNET Core application.

```
services.AddSingleton<IHostedService, ServiceHost1>();
services.AddSingleton<IHostedService, ServiceHost2>();
```

Prior to 2.1.4 (2.1.402) a CTRL-C would cause the cancellationToken in each of the hostedservices to be set so that I could exist the tasks and the process would stop.  However, that is no longer the case.

The CancellationToken does not get set and the hosted services DO NOT stop.  Which will not let the ASPNET main task stop either.  I get the message in the console "Application is shutting down", but nothing happens.

This is running on the latest Raspbian image on a Pi 3 B+.

Anyone else having this issue?

**Comment by voroninp** [comment] 2018-12-21 11:31
This example from docs is not stopped by `CTRL+C`:

```CSharp
public static async Task Main(string[] args)
{
    var host = new HostBuilder()
        .Build();

    await host.RunAsync();
}
```

**Comment by anurse** [comment] 2019-03-29 17:19
@Tratcher is the SIGTERM issue @Markeli posted resolved by https://github.com/aspnet/AspNetCore/pull/8294 ?

@voronip I can't reproduce that issue, it terminated just fine for me.

**Comment by Tratcher** [comment] 2019-03-29 18:14
Unclear, I hadn't reproduced it yet either. #8294 should have only changed the exit code, not affected if it did or did not exit.

**Comment by anurse** [comment] 2019-03-29 18:59
Ok, so we do still need to investigate if SIGTERM is working in this scenario then.

**Comment by Tratcher** [comment] 2019-04-12 22:13
Tested this sample (https://github.com/aspnet/AspNetCore/issues/5940#issuecomment-449364978) on 2.2.4 (2.2.203) on Ubuntu 18.04 and CTL+C is working on the console as expected.

Backlogging any investigation of daemons until we focus on those in a future milestone.

**Comment by anurse** [comment] 2019-04-12 22:34
Ok, closing this for now then. @voroninp if you have more information about the environment you are in where Ctrl-C is not working, please let us know!

**Closed by anurse** 2019-04-12 22:34 UTC
Labels: PRI: 1 - Required, area-hosting, investigate, release-3.0
