### ISSUE TITLE
[Blazor] Reload link doesn't work

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#13288] opened 2019-08-20 18:07 UTC
![image](https://user-images.githubusercontent.com/6995051/63372309-a8dbb000-c33a-11e9-8303-1fd635ab4a52.png)

That button doesn't work when the connection is lost.

**Comment by NTaylorMullen** [comment] 2019-08-20 21:00
Hmm, I didn't change how we suggest the user page reloads (it uses an `<a href>...</a>` tag) but I can definitely see what you're seeing in `dotnet new blazorserver`. Also, it doesn't seem like it's consistent either. In Blazors test app it worked just fine:

![image](https://i.imgur.com/6SRW6yV.gif)

Tried reproducing it working in a `dotnet new blazorserver` template app and haven't been able to. @rynowak do you think this is ask mode worthy?

**Comment by NTaylorMullen** [comment] 2019-08-20 21:18
So talked offline. Given that this behavior hasn't changed from previous Blazor releases (we brought forward how we suggested users reload the page) and that it's pretty obvious for a user to just "reload" in their browser I'm going to park this in 3.1

**Comment by SteveSandersonMS** [comment] 2019-08-23 12:39
I also filed https://github.com/aspnet/AspNetCore/issues/13370 without realising it was a dupe of this.

However, since #13370 also contains a diagnosis of exactly what was broken, I'm going to close this one in favour of that.

That also means we'll re-triage. So, closing as dupe of #13370.

**Closed by SteveSandersonMS** 2019-08-23 12:39 UTC
Labels: area-blazor, bug, cost: XS
