### ISSUE TITLE
SignalR Client for Fullter/Dart

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#6432] opened 2019-01-06 20:02 UTC
@Team;

Is there plan to have an official Flutter/Dart client for SignalR Core?
Thanks!

**Comment by BrennanConroy** [comment] 2019-01-06 20:04
Dupe of https://github.com/aspnet/AspNetCore/issues/5310

**Closed** 2019-01-06 20:09 UTC
