### ISSUE TITLE
Generic Host Template

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/AspNetCore#6929] opened 2019-01-22 19:06 UTC
_From @r734 on December 26, 2018 20:21_

I'd really like to see a template for the [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2) project type. The closest templates right now are `web` and `webapi`, but they're both focused on HTTP-based applications.

Ideally, I would just do `dotnet new generichost`, and I'd have a ready-to-go Generic Host project with configuration, logging, and a HostedService or two (such as the `LifetimeEventsHostedService` or `TimedHostedService` from the documentation) as examples.

_Copied from original issue: dotnet/templating#1725_

**Comment by davidfowl** [comment] 2019-01-23 07:12
Dupe of https://github.com/aspnet/AspNetCore/issues/6817

**Closed by davidfowl** 2019-01-23 07:12 UTC
