### ISSUE TITLE
Blazor.Net Docs link point to Server Side Razor Components

### ISSUE THREAD

**Issue by lohithgn** [aspnet/AspNetCore#7381] opened 2019-02-08 06:47 UTC
### Describe the bug
The docs link from https://blaor.net points to service side razor components doc. It should be pointing to client side razor components aka blazor standalone.

### To Reproduce
1. Head over to https://blazor.net
2. click on Docs link from the menu bar
3. Notice the link navigated to. It is https://docs.microsoft.com/en-us/aspnet/core/razor-components/?view=aspnetcore-3.0

### Expected behavior
Docs link from https://blazor.net should point to client side razor components development docs link. 

### Screenshots
![Docs Page](https://files.gitter.im/aspnet/Blazor/V5Sa/image.png)

### Additional context
I see that the server side razor components & client side razor components overview point to a single overview page. Looks like a reused page. But if i land from blazor.net i expect to be in client side blazor development. thoughts ?

Feel free to dismiss this issue. I felt a confusion and wanted to check with you folks as to what you think.

**Comment by mkArtakMSFT** [comment] 2019-02-11 20:48
Thanks for contacting us, @lohithgn. We're closing this issue as a dupe of https://github.com/aspnet/Docs/issues/10825

**Closed by mkArtakMSFT** 2019-02-11 20:48 UTC
Labels: area-mvc, duplicate
