### ISSUE TITLE
StateHasChanged causes `InvalidOperationException`

### ISSUE THREAD

**Issue by DevelAx** [aspnet/AspNetCore#8814] opened 2019-03-26 10:05 UTC
### To Reproduce
1. ASP.NET Core '3.0'
2. Run this code: ['Blazor tab example'](https://gist.github.com/SteveSandersonMS/f10a552e1761ff759b1631d81a4428c3)
3. Close the browser or stop debugging (Shift + F5).
4. See error at the line with `StateHasChanged()`: 
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Components.dll
An exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Components.dll but was not handled in user code
The current thread is not associated with the renderer's synchronization context. Use Invoke() or InvokeAsync() to switch execution to the renderer's synchronization context when triggering rendering or modifying any state accessed during rendering.
```

### Expected behavior
Normal program termination without errors.

**Comment by javiercn** [comment] 2019-03-26 10:54
Can you provide the call stack for the error when this happens?

**Comment by SteveSandersonMS** [comment] 2019-03-26 11:24
Thanks for reporting this, @DevelAx!

I've tracked down the underlying issue which causes this and reported it at https://github.com/aspnet/AspNetCore/issues/8816. So, I'll close this issue in favour of the other one which describes root cause.

**Closed by SteveSandersonMS** 2019-03-26 11:24 UTC

**Comment by DevelAx** [comment] 2019-03-26 11:38
Ok, thank you for the quick response!
Actually, there is no "callstack" I can see. Even the exception message disappears after a second and the debugger immediately stops.
