### ISSUE TITLE
JsonResult missing Content-Length header

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [aspnet/AspNetCore#14858] opened 2019-10-09 16:49 UTC
### Describe the bug
A `JsonResult` response does not include the `Content-Length` header. This is hidden and I was unable to detect it in unit tests because it seems that something in the core library is setting this value on an `HttpResponseMessage`.

### To Reproduce
1. Using ASP.NET Core 2.1.3
2. Create a controller (this one is intended to serve as the `rootdomain.com/.well-known/microsoft-identity-association.json` file):
```
public class MicrosoftController : Controller
{
    private readonly MicrosoftApplicationIdentitySettings _apps;

    private static JsonSerializerSettings jsonSettings = new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    };

    public MicrosoftController(MicrosoftApplicationIdentitySettings apps)
    {
        _apps = apps ?? throw new ArgumentNullException(nameof(apps));
    }

    // https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-configure-publisher-domain
    public JsonResultWithContentLength GetIdentityAssociation()
    {
        var result = Json(_apps, jsonSettings);

        // We want exactly "application/json" with no charset or Azure will reject the file. See https://social.msdn.microsoft.com/Forums/en-US/61ef2463-c132-4246-8748-c3090e0deed0/publisher-domain-verification-fails-because-quotverification-of-publisher-domain-failed-error?forum=WindowsAzureAD
        result.ContentType = new MediaTypeHeaderValue("application/json").ToString();

        return result;
    }
}
```
3. Serve the endpoint
4. Using Postman, run a GET request on your endpoint and note that the header `Content-Length` is not included.
5. Run unit test:
```
[Fact]
public async Task RouteToMicrosoftIdentityAssociation()
{
    var response = await _client.GetAsync("/.well-known/microsoft-identity-association.json");
    var content = await response.Content.ReadAsStringAsync();
    var contentType = response.Content.Headers.ContentType;

    // We want exactly "application/json" with no charset. See https://social.msdn.microsoft.com/Forums/en-US/61ef2463-c132-4246-8748-c3090e0deed0/publisher-domain-verification-fails-because-quotverification-of-publisher-domain-failed-error?forum=WindowsAzureAD
    var expectedContentType = new MediaTypeHeaderValue("application/json");

    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    Assert.False(string.IsNullOrEmpty(content));
    Assert.Equal(expectedContentType, contentType);
    Assert.NotEqual(0, response.Content.Headers.ContentLength.GetValueOrDefault(0));
}
```
6. Note that the test passes even though the header was not included, as shown by Postman

### Expected behavior

The `Content-Length` header should be set on JSON responses.

### Additional context

I am using 2.1.3 at the moment so was able to workaround this by inheriting from `JsonResult` and `JsonResultExecutor` and adding the header, but this will not be possible in 3.x as the executor has been changed to internal.

The problem exists in 2.1.3 and 3.x.

The reason I even found this was because the Azure portal requires the Content-Length header in order to verify a publisher domain, which means that I won't be able to use the Microsoft libraries to work with a Microsoft product.

**Comment by davidfowl** [comment] 2019-10-10 03:16
Isn’t a bug it’s by design. By default all responses are unbuffered and chunked. It’s something that a piece of middleware can fix.

**Comment by javiercn** [comment] 2019-10-10 10:29
@Blackbaud-ChristiSchneider Thanks for contacting us.

@davidfowl is right. Closing as there's no more action to be taken here.

**Closed by javiercn** 2019-10-10 10:29 UTC
Labels: area-mvc
