### ISSUE TITLE
SignInManager.PasswordSignInAsync redireciona sozinho

### ISSUE THREAD

**Issue by vinivsl** [aspnet/AspNetCore#9833] opened 2019-04-29 18:59 UTC
I'm a beginner in programming, I do not know how to write English yet. Translation with Google Translate. Forgiveness if it is difficult to understand =/

Using ASP.NET Core 2.2.

I'm using a **POST** action with JavaScript (`fetch`) for the method:

``` csharp
public async Task<ApiResult> OnPostAsync(InputModel input,
    [FromServices] SignInManager<User> signInManager, [FromServices] UserManager<User> userManager)
{
    ValidationResult validationResult = new InputModelValidator().Validate(input);

    if (!validationResult.IsValid)
    {
        return ApiResult.Failed(validationResult.Errors);
    }

    User user = await userManager.FindByNameAsync(input.UsernameOrEmail) ??
        await userManager.FindByEmailAsync(input.UsernameOrEmail);

    if (user == null)
    {
        return ApiResult.Failed(
            nameof(InputModel.UsernameOrEmail), errorMessage: "Nome de usuário ou e-mail não existe");
    }

    SignInResult result = await signInManager.PasswordSignInAsync(user, input.Password.Trim(), true, true);

    if (result.Succeeded)
    {
        return ApiResult.Succeeded("Entrou na conta com sucesso", redirectUrl: Url.GetReturnUrl());
    }

    if (result.IsLockedOut)
    {
        return ApiResult.Failed(
            "Não é possível entrar na conta devido as várias tentativas fracassadas, tente novamente mais tarde");
    }

    return ApiResult.Failed(nameof(InputModel.Password), errorMessage: "Senha inválida");
}
```
But when I run `signInManager.PasswordSignInAsync` and succeed, it redirects to `?ReturnUrl=<url here>` and I can not get the result I need to run the JavaScript code.

> When `?ReturnUrl=..` is not present, `signInManager.PasswordSignInAsync` does not authenticate the user, ie it does not work.

**Comment by blowdart** [comment] 2019-05-15 20:18
It needs a redirect to write the cookie, which is why it's not working. If you want to try to do this without the redirects you're going to have to generate the cookies and write them yourself, and that's not recommended. It is better to just take the redirect.

**Comment by blowdart** [comment] 2019-07-24 20:08
We're closing this issue as the behaviour discussed seems to be by design.

**Closed by blowdart** 2019-07-24 20:08 UTC
Labels: area-identity
