### ISSUE TITLE
Yaml configuration provider

### ISSUE THREAD

**Issue by ahryshchanka** [aspnet/AspNetCore#17355] opened 2019-11-23 10:17 UTC
What about add `YamlConfigurationProvider` as a one of default, available without any nuget package and costomization configuration provider?

Examples of custom `YamlConfigurationProvider`:
- [link1](https://andrewlock.net/creating-a-custom-iconfigurationprovider-in-asp-net-core-to-parse-yaml/)
- [link2](https://blog.kloud.com.au/2017/01/25/adding-yaml-settings-into-aspnet-core-apps/)
- [link3](https://medium.com/@dneimke/custom-configuration-in-net-core-2-193ff6f02046)

**Comment by gfoidl** [comment] 2019-11-23 10:52
See https://github.com/aspnet/Extensions/issues/2659

**Comment by javiercn** [comment] 2019-11-25 12:18
@ahryshchanka thanks for contacting us.

I'm closing this issue as it is a dupe of aspnet/Extensions#2659 which is tracking it on the right repository.

**Closed by javiercn** 2019-11-25 12:18 UTC
