### ISSUE TITLE
Test failure: _1_Restore

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3742] opened 2018-10-29 12:51 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) with the following error:

```
System.InvalidOperationException : Command dotnet restore /warnaserror --no-cache --source https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181029-01/final/index.json --source https://api.nuget.org/v3/index.json --runtime osx-x64 returned exit code 1

  Restoring packages for /Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj...
/Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj : error NU1102: Unable to find package Microsoft.Extensions.ObjectPool with version (>= 2.2.0-rtm-181029-01 && < 2.3.0)
/Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj : error NU1102:   - Found 18 version(s) in nuget.org [ Nearest version: 2.2.0-preview3-35497 ]
/Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj : error NU1102:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181029-01/final/index.json
/Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj : error NU1102: Unable to find package Microsoft.Extensions.Primitives with version (>= 2.2.0-rtm-181029-01 && < 2.3.0)
/Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj : error NU1102:   - Found 18 version(s) in nuget.org [ Nearest version: 2.2.0-preview3-35497 ]
/Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj : error NU1102:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181029-01/final/index.json
  Generating MSBuild file /Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/obj/angular.csproj.nuget.g.props.
  Generating MSBuild file /Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/obj/angular.csproj.nuget.g.targets.
  Restore failed in 2.44 sec for /Users/vsts/agent/2.141.1/work/_temp/tmp9am1Ul.tmp/angular/EnvironmentVariableAndNuGetOrg/osx-x64/angular.csproj.



```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-10-29 12:51
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-29 12:52
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 627 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) on release/2.2 at 12:38:50 PM:
- _7_PublishIncremental
- _7_PublishIncremental
- _8_Exec
- _8_Exec
- _2_RestoreIncremental
- _1_Restore
- _2_RestoreIncremental
- _6_Publish
- _6_Publish
- _7_PublishIncremental
- (And 617 more test failures in this build)

**Comment by natemcmaster** [comment] 2018-10-29 15:50
Duplicate of https://github.com/aspnet/AspNetCore/issues/3686

**Closed by natemcmaster** 2018-10-29 15:50 UTC
Labels: Branch:release/2.2, test-failure
