### ISSUE TITLE
HttpRequest.Protocol always / only reports HTTP/1.1

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore#14188] opened 2019-09-20 13:39 UTC
### Describe the bug
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#http2-support-1
"If an HTTP/2 connection is established, HttpRequest.Protocol reports HTTP/2."

That's not true. I have the following setup in Program.cs:
```
`            .ConfigureKestrel((context, options) =>
            {
                options.Listen(IPAddress.Any, 5002, listenOptions =>
                {
                    listenOptions.UseHttps("/tmp/localhost.pfx", "4xLabs.com");
                    listenOptions.UseConnectionLogging();
                    listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                    //listenOptions.UseHttps("testCert.pfx", "testPassword");
                });
            });
```
And I setup HttpRequest logging in Startup.cs:
```
            app.Use(async (context, next) =>
            {
                // Request method, scheme, and path
                _logger.LogInformation(JsonConvert.SerializeObject(new RequestLog(context?.Request?.Method, 
                                    context?.Request?.Scheme, 
                                    context?.Request?.PathBase, 
                                    context?.Request?.Path, 
                                    context?.Request?.Host.ToString(), 
                                    context?.Request?.ContentLength, 
                                    context?.Connection?.RemoteIpAddress?.ToString(), 
                                    context?.Request?.QueryString.ToString(), 
                                    context?.Request?.ContentType,
                                    context?.Request?.Protocol,
                                    context?.Request?.Headers
                                    )));
                await next();
            });
```
I use Chrome to browse to my application. Logs are collected by Elasticsearch and shown in Kibana. Application is deployed to Kubernetes on cloud behind Load Balancer which uses HTTPS. Unfortunately ONLY HTTP/1.1 is recorded. There is no other protocols observed.

### To Reproduce
1. Using this version of ASP.NET Core '...' 2.2
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
HttpRequest.Protocol records correct values: HTTP/2, Websocket, etc.

### Additional context
Include the output of `dotnet --info`
```
# dotnet --info

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by blowdart** [comment] 2019-09-20 13:48
Are you sure the load balancer is actually forwarding the requests as HTTP/2? Have you set up the header forwarding?

**Comment by khteh** [comment] 2019-09-20 14:21
This is what I do in my RequestLog.cs shown in my original post:
```
                foreach (var header in headers)
                    if (header.Key.Equals("X-Forwarded-For") || header.Key.Equals("X-Original-For"))
                        IP = header.Value;
                    else if (header.Key.Equals("X-Forwarded-Proto") || header.Key.Equals("X-Original-Proto"))
                        X_Forwarded_Proto = header.Value;
                    else if (header.Key.Equals("X-Forwarded-Host") || header.Key.Equals("X-Original-Host"))
                        X_Forwarded_Host = header.Value;
```

**Comment by Tratcher** [comment] 2019-09-20 14:52
Likely a duplicate of https://github.com/aspnet/AspNetCore/issues/11833, try reversing the order:
```
                         listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                         listenOptions.UseHttps("/tmp/localhost.pfx", "4xLabs.com");
                         listenOptions.UseConnectionLogging();
```

**Comment by khteh** [comment] 2019-09-20 15:45
Just tried. Doesn't work.

**Comment by Tratcher** [comment] 2019-09-20 15:51
Then the issue is likely in the reverse proxy configuration. You can verify by
A) Testing direct access to the server.
B) Testing a alternate server behind the reverse proxy.
C) Checking the proxy docs to confirm HTTP/2 is even supported.

**Comment by khteh** [comment] 2019-09-21 02:25
I use AWS Application Load Balancer and it terminates HTTP/2 connections and only use HTTP/1.1 with services behind it. How is the case with Azure load balancer? Does it use HTTP/2 all the way to the backend services?

**Comment by Tratcher** [comment] 2019-09-21 03:12
@shirhatti ?

**Comment by khteh** [comment] 2019-09-23 02:03
This is related to https://github.com/aspnet/AspNetCore/issues/14229 If the header forwarding works, I could have obtained the *original* protocol used by the client in X-Forwarded-Proto header value.

**Comment by Tratcher** [comment] 2019-09-23 02:37
x-forwarded-proto does not forward the HTTP version, it's forwards "http" or "https" indicating if encryption was used.

**Comment by khteh** [comment] 2019-09-23 02:45
How can I get the original `HttpRequest.Protocol` from client? Is it recorded and forwarded in any header?

**Comment by Tratcher** [comment] 2019-09-23 03:13
I don't see any common header for that. You could define your own in your proxy config.

**Closed** 2019-09-23 06:09 UTC
Labels: area-servers
