### ISSUE TITLE
Blazor: setting SVG attributes to null throws error

### ISSUE THREAD

**Issue by Wibble199** [aspnet/AspNetCore#15311] opened 2019-10-23 11:40 UTC
### Description
If there is an attribute on an SVG element, which is then set to null, an error is thrown in the console. I am using server-side Blazor. The error in the Blazor console is:

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Error: Cannot remove attribute from non-element child
System.InvalidOperationException: Error: Cannot remove attribute from non-element child
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'Yk8Af-rrgPjwWI9LXGHZZQVGdKMrQKAeZVdsJEjAIqg'.
System.AggregateException: One or more errors occurred. (Error: Cannot remove attribute from non-element child)
 ---> System.InvalidOperationException: Error: Cannot remove attribute from non-element child
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```

### To Reproduce

```razor
@page "/testsvg"

<svg id="svg-root">
    <path data-some-data="@someNullable?.ToString()"></path>
</svg>

<button @onclick="() => SetToNull()">Set to null</button>

@code {
    int? someNullable = 10;

    void SetToNull() {
        someNullable = null;
    }
}
```

When clicking the "set to null" button, an error appears in the browser console and the Blazor console.

### Expected behaviour

The attribute is removed from the SVG element like it would be with a standard HTML element.

### Additional

Looking at the `BrowserRenderer.ts` file, it appears as though the removeAttribute edit type does a check for `if (element instanceof HTMLElement)` (currently on [line 130](https://github.com/aspnet/AspNetCore/blob/74360c7d97f9b55b94fecbd6e0598daf0c1b7cd1/src/Components/Web.JS/src/Rendering/BrowserRenderer.ts#L130) in the master), whereas the above setAttribute edit type does a check for `if (element instanceof Element)` instead ([Line 118](https://github.com/aspnet/AspNetCore/blob/74360c7d97f9b55b94fecbd6e0598daf0c1b7cd1/src/Components/Web.JS/src/Rendering/BrowserRenderer.ts#L118)). I suspect this is the cause, since an SVG element is not an instance of a HTML element but it is an instance of Element, which would explain why you can update attributes on the path element successfully but not set them to null.

**Comment by javiercn** [comment] 2019-10-23 16:28
@Wibble199 thanks for contacting us.

We believe this issue is a duplicate of #6169

**Closed by javiercn** 2019-10-23 16:28 UTC
Labels: area-blazor
