### ISSUE TITLE
Run Universe external dependency check on every PR in each repo

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3651] opened 2018-10-17 18:27 UTC
_From @Eilon on Friday, April 13, 2018 2:48:28 PM_

This will find errors such as mismatched dependencies, including 3rd party packages.

Can also automate checking if OSS approval is registered via some magical script that @anurse knows about.

_Copied from original issue: aspnet/Universe#1071_

**Comment by natemcmaster** [comment] 2019-01-23 00:41
@Eilon is this basically a duplicate of https://github.com/aspnet/AspNetCore-Internal/issues/1648?

**Comment by Eilon** [comment] 2019-01-28 18:20
Not quite a dup of that one; more a dup of https://github.com/aspnet/AspNetCore-Internal/issues/1254. So either way, closing this.

**Closed by Eilon** 2019-01-28 18:20 UTC
Labels: 1 - Ready, area-infrastructure, task
