### ISSUE TITLE
Taghelpers in netstandard 2.0 assembly must now reference Microsoft.AspNetCore.Razor 2.1.0

### ISSUE THREAD

**Issue by vincentparrett** [aspnet/AspNetCore#9766] opened 2019-04-26 00:28 UTC
### Describe the bug
Prior to 3.0 preview 4, you could have taghelpers in a netstandard 2.0 assembly with a reference to 
````xml
 <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
````
and it would run fine. 

As of preview 4, the only way I could get my taghelpers to run was change the assembly reference to 

````xml
  <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.1.0" />
````
(or a later version) -  Microsoft.AspNetCore.Razor 2.0.0 does not have TagHelpers so not an option.

### To Reproduce

1)Create an mvc app from the template. 
2) Create a netstandard 2.0 library, add a reference to Microsoft.AspNetCore.Mvc 2.0.0
3) Create a minimal taghelper in the library
3) Add a reference to the library in the mvc project.
4) Add the taghelper lib to _ViewImports.cshtml
5) Use the taghelper in the home.cshtml view 

### Expected behavior
Taghelper should run, but it is never instantiated or called. 

### Additional context
Using Microsoft.NETCore.App 3.0.0-preview4-27615-11

Note, this worked fine in 3.0 preview 3. 

This will affect third party netstandard 2.0 libs that support asp.netcore 2.0+, I discovered this issue with https://github.com/Shazwazza/Smidge

**Comment by pranavkm** [comment] 2019-04-26 00:51
@vincentparrett what version of the SDK are you targeting (`dotnet --info`)? There was a bug in the preview3 SDK that was resolved as part of part of preview4: https://github.com/aspnet/AspNetCore/issues/6825. Just making certain it's not the same issue you're running into.

**Comment by vincentparrett** [comment] 2019-04-26 00:54
Output from dotnet --info
````
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  1.1.12 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
````

**Comment by pranavkm** [comment] 2019-05-23 00:36
@vincentparrett this seems to be working fine when I try it with SDK v`3.0.100-preview6-012037`. Here's the application I created using your repro steps: https://github.com/pranavkm/repro/blob/issue9766/WebApplication6/Views/Home/Index.cshtml#L5. I'd recommend trying the preview5 bits, or grabbing the preview6 nightlies from https://github.com/dotnet/core-sdk#installers-and-binaries if you'd like to verify the issue is resolved with a later SDK.

Feel free to reopen this issue if you continue to reproduce the problem with a newer SDK, I'd be happy to investigate.

**Closed by pranavkm** 2019-05-23 00:36 UTC
Labels: area-mvc, investigate

**Comment by vincentparrett** [comment] 2019-05-23 02:26
I'm not able to test this in my application, the debugger crashes

---------------------------
Microsoft Visual Studio
---------------------------
A fatal error has occurred and debugging needs to be terminated. For more details, please see the Microsoft Help and Support web site. HRESULT=0x80131c49. ErrorCode=0x0.
---------------------------
OK   
---------------------------

**Comment by vincentparrett** [comment] 2019-05-23 02:26
That's with the preview 6 nightly.

**Comment by pranavkm** [comment] 2019-05-23 03:03
@vincentparrett I'd use the VS feedback tool to file an issue for the debugger crash.
