### ISSUE TITLE
Razor Components do not include embedded resources from assemblies

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/AspNetCore#7310] opened 2019-02-06 17:56 UTC
Just upgraded a project to Razor Components from Blazor 0.7
Unfortunately, it depends on CSS/JS-Files located in a separate assembly.
With Blazor, after declaration of these CSS/JS-Files as embedded resource with a certain name (blazor:js:** and blazor:css:**), they were packed and referenced automagically by blazor.
After migraton to Razor Components, this functionality seems to be not available any more (at least, the resources are not shipped to the browser any more)
What must be done to make inclusion of JS/CSS from separate assemblies work again?

Thanks!

**Comment by vertonghenb** [comment] 2019-02-06 19:55
Duplicate of https://github.com/aspnet/AspNetCore/issues/6349

**Comment by mkArtakMSFT** [comment] 2019-02-07 16:47
Closing as this is indeed a duplicate.

**Closed by mkArtakMSFT** 2019-02-07 16:47 UTC
Labels: area-mvc
