### ISSUE TITLE
Blazor WebAssembly: A way to get progress of startup using JavaScript?

### ISSUE THREAD

**Issue by GerritBergen** [aspnet/AspNetCore#15411] opened 2019-10-25 18:21 UTC
It'd be really nice to show some progress of where the app is in downloading dll or wasm files, and maybe where the app is in loading the whole application before the splash screen disappears.

Is this possible somehow using JavaScript or some other method?

**Comment by DamianEdwards** [comment] 2019-10-25 19:06
Similar to #13933

I don't believe the required hooks on the JS side exist yet, but I agree it would be a great addition.

**Comment by mkArtakMSFT** [comment] 2019-10-28 16:43
Thanks for contacting us, @GerritBergen.
This is a dupe of the issue @DamianEdwards has reference, so closing this one.

**Closed by mkArtakMSFT** 2019-10-28 16:43 UTC
Labels: area-blazor, blazor-wasm
