### ISSUE TITLE
Blazor Custom formatting for numbers and strings

### ISSUE THREAD

**Issue by ericgrantholland** [aspnet/AspNetCore#9435] opened 2019-04-16 19:25 UTC
I am looking into formatting strings and numbers using blazor-data-bindings. For example, formatting a number with currency, formatting a number with thousands-separators. Currently, there is a method of formatting only DateTime fields as shown below:

`
<input type="text" bind="@Birthday" /><br />
    What is your birthday (German date format)? <input type="text" bind="@Birthday" format-value="dd.MM.yyyy" /><br />
`

You can always use a Javascript library such as AutoNumeric, but an out-of-the-box solution would speed up development and user-experience. AutoNumeric can also apply formats live while the user is typing in the input fields.

Here are a few simple number formats for demonstration.
-Currency ($5,700.99, €65.76, £62 )
-Percentages (56.789%, 99%)

**Comment by mkArtakMSFT** [comment] 2019-04-17 16:23
Thanks for contacting us, @ericgrantholland.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by gingters** [comment] 2019-06-18 13:34
Please reconsider "This means that it is not going to happen for the coming release. ". This is an essential required feature for displaying data to the user and would repell a lot of users from using Blazor for real-world applications.

**Comment by mkArtakMSFT** [comment] 2019-06-18 22:37
We're closing this issue as a dupe of https://github.com/aspnet/AspNetCore/issues/5523, which we plan to handle during 3.1 timeframe.

**Closed by mkArtakMSFT** 2019-06-18 22:37 UTC
Labels: area-blazor, enhancement
