### ISSUE TITLE
HttpResponseStreamWriter WriteLineAsync can cause exception

### ISSUE THREAD

**Issue by antifree** [aspnet/AspNetCore#16740] opened 2019-11-01 13:46 UTC
### Describe the bug
WriteLineAsync method of HttpResponseStreamWriter  in Asp.Net Core 3.0 can cause the following exception:

```InvalidOperationException when attempting to write to the response body – with a message “Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.”```. 

I think it occurs, because [default implementation on TextWriter](https://github.com/dotnet/corefx/blob/0fbb5f15e2c9b7ff51f5d194dbf06c406c14da9e/src/Common/src/CoreLib/System/IO/TextWriter.cs#L551-L580) creates new Task which calls Write method. This method is overriden in HttpResponseStreamWriter and writes to response stream in synchronous way. I guess it is a bug.

I've found an issue #2895 says this one and other methods should be overriden. But as I see, it is delayed.

### Expected behavior
To work without setting `AllowSynchronousIO = true` or using `WriteAsync(line + "\n")`

**Comment by Tratcher** [comment] 2019-11-01 17:51
@javiercn FYI HttpAbstractions issues are tracked in area-servers, not hosting.

**Comment by Tratcher** [comment] 2019-11-01 17:56
That would be a good reason to fix #2895.

**Comment by davidfowl** [comment] 2019-11-02 16:02
We have a similar issue for the reading side

**Comment by anurse** [comment] 2019-11-05 21:22
Let's tackle all this together. Closing this as a dupe of #2895

**Closed by anurse** 2019-11-05 21:22 UTC
Labels: area-servers, bug
