### ISSUE TITLE
Certificate expired, clean and trust does not create a new certificate

### ISSUE THREAD

**Issue by kYann** [aspnet/AspNetCore#12832] opened 2019-08-02 14:10 UTC
### Describe the bug
Launch react website using kestrel, when browsing, brower say certificate invalid.
After looking at the certificate it is expired.

Tried to clean and recreate certificate but it still says certificate invalid.
When looking at the certificate store I can't find a expired certficiate.
Other dotnet website use the new certificate and does not show the same error

### To Reproduce
Sorry I don't know how to reproduce this one

### Expected behavior
Kestrel use a valid certificate

### Additional context
Certificate is invalid on all browsers

**Comment by Rick-Anderson** [comment] 2019-11-21 03:50
@kYann  is this still an issue? If not, can you close? Did you try the instructions at [Troubleshoot certificate problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#troubleshoot-certificate-problems)

Are you saying other ASP.NET Core web apps use the ASP.NET Core HTTPS development certificate but react website using Kestrel can't?

**Comment by kYann** [comment] 2019-11-21 13:15
I am saying that one of the project was using an expired certificate was not visible in the certificate store. And the other was fine.

Cleaning the certificate did not fix it.

When migrating to .Net Core 3, Visual Studio ask me if I needed to create a new certificate. Clicking on Yes and trusting it fix the issue.

**Comment by Rick-Anderson** [comment] 2019-11-21 17:12
Sounds like the issue is fixed. Can you close this issue?

**Closed** 2019-11-26 23:17 UTC
Labels: area-commandlinetools
