### ISSUE TITLE
Update to Angular 8

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5431] opened 2018-08-21 06:05 UTC
It looks like Angular 7 is scheduled to be released in Sept/Oct of this year: https://angular.io/guide/releases#release-schedule

**Comment by blogcraft** [comment] 2019-01-05 00:14
The problem is that March/April 2019 will be the [release](https://angular.io/guide/releases#release-schedule) of Angular 8.

It seems you are always 1 version behind.

**Comment by stephenlautier** [comment] 2019-02-13 22:56
With the current template (on .net 2.2) I got it working with Angular7 + SSR. 

The only thing I can't get working for SSR is optimization or bundling together (both on server), if I enable one of them it works, together they don't (cause i don't want to copy all **node_modules** for SSR).

**NOTE**
- I had to do several changes/fixes in order to get SSR workin (even for Angular 6)


#### SSR Error with optimization + bundling

```
An unhandled exception occurred while processing the request.
NodeInvocationException: StaticInjectorError[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
TypeError: StaticInjectorError[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
at insertElement (C:\dev\git\Cosmowrench\Sketch7.Cosmowrench\ClientApp\dist-server\main.js:1:2597704)
at insertHTMLElement (C:\dev\git\Cosmowrench\Sketch7.Cosmowrench\ClientApp\dist-server\main.js:1:2597428)
at before_head_mode (C:\dev\git\Cosmowrench\Sketch7.Cosmowrench\ClientApp\dist-server\main.js:1:2635408)
at HTMLParser.htmlparser.insertToken (C:\dev\git\Cosmowrench\Sketch7.Cosmowrench\ClientApp\dist-server\main.js:1:2596464)
````

**Comment by stephenlautier** [comment] 2019-02-22 20:51
Just if anyone wants to see the repo, feel free to check it out on

 https://github.com/sketch7/dotnet-ngx-sample ❤️

**Comment by mkArtakMSFT** [comment] 2019-02-25 16:54
Looks like Angular 8 is going to be released before 3.0 ships, so we'll wait for that instead and skip update to Angular 7.
I'm updating the title to reuse this issue for that purpose.

**Comment by varghesep** [comment] 2019-05-19 14:29
I manually upgraded the angular app that runs under ```asp.net core 2.2``` to 8.0 Preview. One major problem that I came across was Angular generates an error related to ```https``` quite often in Chrome, but not on edge. I posted a [question ](https://stackoverflow.com/questions/55892546/how-to-remove-the-sockjs-node-error-for-a-asp-net-core-angular-application)in stackoverflow regarding this.

**Comment by isaac2004** [comment] 2019-06-06 19:12
Looks like Angular 8 was released end of May, I can add it

**Comment by mkArtakMSFT** [comment] 2019-06-18 21:22
Moving this to preview 8, as we're blocked on security review.

**Comment by ngohungphuc** [comment] 2019-06-21 10:28
Is ther any update on my PR https://github.com/aspnet/AspNetCore/pull/10616 ?

**Comment by mkArtakMSFT** [comment] 2019-06-21 22:45
@ngohungphuc we're working through some security-related aspects of this, before we can take it.

**Closed** 2019-07-02 17:32 UTC
Labels: Done, PRI: 1 - Required, area-mvc, cost: S, enhancement

**Comment by blogcraft** [comment] 2019-09-10 16:19
... And what about Angular 9 with Ivy?

**Comment by danroth27** [comment] 2019-09-17 20:04
> And what about Angular 9 with Ivy?

@blogcraft https://github.com/aspnet/AspNetCore/issues/14076
