### ISSUE TITLE
Status code in Problem()

### ISSUE THREAD

**Issue by Sinhk** [aspnet/AspNetCore#15259] opened 2019-10-22 11:19 UTC
### Is your feature request related to a problem? Please describe.
When using the new Problem() methods on ControllerBase, it appears to be no link between the status code in the ProblemDetails instance and the status code of the response.
This can be somewhat misleading when the Problem() method by default sets statusCode = 500 in the ProblemDetails instance, but not for the response. 

Example:   
```
[ApiController]
[Route("[controller]")]
public class AController : ControllerBase
{
    [HttpGet]
    public IActionResult Get()
    {
        return Problem();
    }
}
```
returns a response with status code 200 and body:
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
  "title": "An error occured while processing your request.",
  "status": 500,
  "traceId": "|4e6eef48-40764b599dcda631."
}
```

### Describe the solution you'd like
Since the Problem() method has a statusCode parameter, I expected it to also set the status code of the response. 

I can't find much documentation on this method yet, so I'm not sure what's the expected behavior. 
If this is currently working as expected, then it could be made more clear from the method. And the statusCode default of 500 should maybe be removed. 
 
I know i could make this work as I expected by making a custom ProblemDetailsFactory. 

### Additional context
dotnet sdk: 3.0.100
using the webapi template

**Comment by javiercn** [comment] 2019-10-22 11:49
@Sinhk Thanks for contacting us.

This issue is a dupe of #14663 that has already been fixed in 3.1

**Closed by javiercn** 2019-10-22 11:49 UTC

**Comment by Sinhk** [comment] 2019-10-22 12:52
Apparently i forgot to remove the is:open filter when searching for this...

Sorry for wasting your time

**Comment by javiercn** [comment] 2019-10-22 12:55
No problem 😄.
