### ISSUE TITLE
AuthorizeRouteView, DefaultLayout can take dynamic type but does not work as expected

### ISSUE THREAD

**Issue by jingzheshan** [aspnet/AspNetCore#16783] opened 2019-11-03 03:29 UTC
### Describe the bug
The AuthorizeRouteView is not using the correct default layout

### To Reproduce
![image](https://user-images.githubusercontent.com/2770401/68079899-3fa60c00-fe56-11e9-929f-db3abaaf800c.png)

![dynamiclayout](https://user-images.githubusercontent.com/2770401/68079902-4e8cbe80-fe56-11e9-9f1d-3be6ccf11024.gif)

### Expected behavior
After login, navigate to the counter page should use MainLayout instead of LoginLayout.

@danroth27  did I do sth wrong here?

**Comment by javiercn** [comment] 2019-11-04 11:50
@jingzheshan thanks for contacting us.

I'm not able to repro this. Could you provide a minimal repro project so that we can help you identify the issue?

**Comment by javiercn** [comment] 2019-11-04 12:32
On second look, I believe your issue is that the CascadingAuthenticationState must wrap the entire component. Here is a simplified sample project that shows this working.

[dynamicauthlayout.zip](https://github.com/aspnet/AspNetCore/files/3803972/dynamicauthlayout.zip)

**Comment by jingzheshan** [comment] 2019-11-05 09:48
@javiercn thanks for your time and investigation. 

Here is a demo sln you can try.
[demo.zip](https://github.com/aspnet/AspNetCore/files/3808236/demo.zip)

I have mocked the code as close as to yours, hope you can reproduce the issue. The main difference right now I think I am using Blazor WebAssembly client-side instead of server-side. BTW. I could confirm your solution works as I expect. 👍

![dynamiclayout](https://user-images.githubusercontent.com/2770401/68196755-ea1c5b80-001d-11ea-9586-199868006b65.gif)

**Comment by javiercn** [comment] 2019-11-05 12:13
@jingzheshan For some reason the cascading authentication state doesn't get updated.

@SteveSandersonMS Can you take a look here? I can't see what's wrong.

**Comment by SteveSandersonMS** [comment] 2019-11-08 10:25
There's a bit too much going on in `demo.zip` for me to narrow in on any specific thing causing a problem.

@jingzheshan I would recommend that you keep comparing your implementation against @javiercn's until you track down what specific difference means that his works and yours doesn't. If at that stage you think it's a bug in the framework, please describe which specific API call is producing the wrong result.

**Comment by javiercn** [comment] 2019-11-08 13:22
We are closing this issue for the time being. If as @SteveSandersonMS mentions you end up tracking down the root cause and you think it's a bug, feel free to comment on the issue and we'll re-evaluate.

Thanks!

**Closed by javiercn** 2019-11-08 13:22 UTC
Labels: area-blazor, blazor-wasm
