### ISSUE TITLE
There is no TargetFrameworkOverride parameter in project templates anymore

### ISSUE THREAD

**Issue by xtmq** [aspnet/AspNetCore#7690] opened 2019-02-18 21:28 UTC
In 3.0.3.0.0-preview [19075-0444]
And there is no possibility to customize target framework. For example to use 2.1 instead of 3.0.

Was it intended? Is so, why?

**Comment by Eilon** [comment] 2019-02-19 06:07
@xtmq can you show an example CSPROJ of what you tried, and explain what you expected, and what didn't work?

**Comment by xtmq** [comment] 2019-02-19 07:33
I'm trying to expand a project template:
```
dotnet new mvc --TargetFrameworkOverride netcoreapp2.1
```

**Comment by Eilon** [comment] 2019-02-19 17:44
@xtmq and the setting was ignored?

cc @ryanbrandenburg

**Comment by xtmq** [comment] 2019-02-19 18:32
There is no such parameter anymore. It was dropped from all web templates so I can not specify it

**Comment by pranavkm** [comment] 2019-02-20 03:05
AFAIK, the property was infrastructural and existed for generating desktop templates. It doesn't exist any longer since we the templates no longer support desktop.

**Comment by xtmq** [comment] 2019-02-20 09:08
Rider IDE uses this property to allow an user specify target framework for a new project. 
All other dotnet core project templates (classlib, concoleapp, unit testing, winforms, wpf) still have this property.

**Comment by ryanbrandenburg** [comment] 2019-02-20 20:52
To my knowledge @pranavkm is correct, this was a part of the templating infrastructure that was removed/changed. The templates you listed are all maintained by the dotnet team, so maybe @mlorbetske can shed a little light on this situation, or point us toward someone who can.

**Comment by mlorbetske** [comment] 2019-02-21 17:38
The parameter in question is defined on each template that supports it, there’s nothing special about the parameter itself nor any special support for it in the template engine code. If Rider is offering support for this parameter to the user, it should be checking to see whether it’s allowed to pass it before doing so. If support for it is needed for the web templates (for targeting different runtime versions for instance), it’d need to be added back on each of them. Alternatively, if there’s a small closed set of valid tfm values for which the template content is valid, providing the extra choices as values for the framework parameter in template.json could be a better approach. /cc @seancpeters

**Comment by Eilon** [comment] 2019-02-21 17:41
OK so if this parameter isn't needed in the ASP.NET Core templates, then it's by-design that it isn't there, and it can be closed.

**Comment by ryanbrandenburg** [comment] 2019-02-21 17:56
Thanks for the history @mlorbetske. Knowing that I dug a little deeper and found some git history that got disconnected in a file rename. That parameter was [removed here](https://github.com/aspnet/Templating/commit/0af2acd6fff0f51ec42183f5a5b01f8f0712af5f#diff-f11a2a3be8896f9f6fcc0b986f1d5cadL4) as part of ASP.NET Core [no longer supporting running on .NET Framework](https://github.com/aspnet/Templating/pull/835).

That being the case this one is by design as @Eilon suggested. Closing.

**Closed by ryanbrandenburg** 2019-02-21 17:56 UTC
Labels: area-mvc, external

**Comment by xtmq** [comment] 2019-02-21 19:05
So are you sure web templates (from netcore 3.0) are completely incompatible with dotnet sdk 2.*? And I can not specify other `TargetFramework` (e.g. netcoreapp2.1) in them?

**Comment by ryanbrandenburg** [comment] 2019-02-21 19:21
The short answer is that you can't use new templates with old SDKs.

The problem is netcoreappX.X is used to determine which version of Microsoft.AspNetCore.App to use, which then pulls in things like Microsoft.AspnetCore.Mvc and Microsoft.AspNetCore.Hosting. We had several breaking changes in 3.0 such as https://github.com/aspnet/AspNetCore/commit/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0#diff-c4a7676f31802c6a8a610516d79129d1R11 which would make just downgrading to netcoreapp2.2 not work. If you want/need to use netcoreapp2.2 our suggestion is to use the 2.2 templates. If it is important to you you may be able to hack together a working 3.0 template which uses netcoreapp2.2, but it is an unsupported scenario.

**Comment by xtmq** [comment] 2019-02-21 19:32
Ok thanks

**Comment by bluetianx** [comment] 2019-04-18 05:56
@xtmq when dose ridder solve this problem in ridder IDE ?
