### ISSUE TITLE
Razor Component: Calling a method without @

### ISSUE THREAD

**Issue by mythrz** [aspnet/AspNetCore#15152] opened 2019-10-18 14:37 UTC
### Issue: it is very easy to forget the @ when calling a method.
After hours/days/weeks of coding it is easy to forget something as simple as the @ when calling a method. There is no warning or error about lack of @ when you forget it. 

### Add warning, error or suggestion when we forget about it.
![image](https://user-images.githubusercontent.com/44119535/67102604-a28f7600-f1bb-11e9-9f38-99de850dd5cb.png)

I think it wasn't mentioned yet, even if it is a minor issue, it's a life quality improvement.
https://github.com/aspnet/AspNetCore/issues/8177
### Other issues:
Lack of intellisense (recognition) on static assets from an RCL and quick actions and Refactoring inside razor components.

**Comment by mkArtakMSFT** [comment] 2019-10-18 16:37
Thank you for your feedback.
We're closing this issue as the behavior you're observing here is by design.
Using the '@' sign or not has a purpose. It's up to the caller to decide whether they want to output the result of the method or not. Both calls will be valid, so we can't make a decision on behalf of the user in this case.

**Closed by mkArtakMSFT** 2019-10-18 16:37 UTC
Labels: area-blazor
