### ISSUE TITLE
Blazor Server-Side Not Working

### ISSUE THREAD

**Issue by PilotC150** [aspnet/AspNetCore#9747] opened 2019-04-25 15:26 UTC
I'm having an issue getting server-side rendering to work with the latest Blazor (3.0.0-preview4-19216-03).

I created a basic ASP.NET Core Web Application using the "Blazor (ASP.NET Core Hosted)" template and build and run.  It works correctly.

**FIRST BUG:** I expect the application created by this template to be already configured to run as a Blazor Server-Side application, since that's what the template leads me to believe it is.  Instead it's running as a Blazor Client-Side app.  This is confusing.

I then followed the directions here (https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0), in the "Hosting models" section, to make it run server side, but the directions appear out of date.

**SECOND BUG:** The directions on that link tell me to add in `services.AddServerSideBlazor<App.Startup>();`.  That function doesn't exist with a type parameter.  Only as `services.AddServerSideBlazor();` 

It also tells me to add `app.UseServerSideBlazor<App.Startup>();` but this function doesn't appear to exist at all anymore.

Additionally I changed the javascript reference from blazor.webassembly.js to blazor.server.js.

If I leave out the call to `app.UseServerSizeBlazor()` (since it doesn't exist) and try to run my application I get a javascript error on an xhr call to "negotiate" in the blazor.server.js file.  The error message is:
> InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

It's likely that the error message is because of the missing function call, but I don't know that for certain.

I'm testing this in latest Chrome, and I just installed all of the Blazor and .NET Core 3 tooling/extensions/libraries yesterday (4/24/2019).

What am I missing to make the server-side rendering work correctly?

**Comment by javiercn** [comment] 2019-04-25 16:26
You've picked the wrong template.

> Blazor (ASP.NET Core Hosted)

Is a blazor **client-side** application hosted within an ASP.NET Core application.

I recommend you start from the blazor (server-side) template
![image](https://user-images.githubusercontent.com/6995051/56752005-2d774280-673c-11e9-9971-d29031d892dd.png)

**Comment by HelvioMarkman** [comment] 2019-04-25 16:50
Javier I am using this template but every time I add a new Page the project start to shut a number of errors

**Comment by javiercn** [comment] 2019-04-25 16:54
@HelvioMarkman Can you post details on your environment?

**Comment by HelvioMarkman** [comment] 2019-04-25 17:46
![image](https://user-images.githubusercontent.com/20973414/56756785-91136700-6760-11e9-827a-4e3aad98217a.png)

**Comment by javiercn** [comment] 2019-04-25 17:51
@HelvioMarkman That looks like a blazor client-side issue.

@SteveSandersonMS

**Comment by HelvioMarkman** [comment] 2019-04-25 18:02
Javier, I please disregard the last picture it was caused by a reference I add in the shared project trying solve the problem. Right now It is does not find the HttpClient in the inject statement. Please see the picture.
![image](https://user-images.githubusercontent.com/20973414/56757644-bdc87e00-6762-11e9-87ac-ccfb9a374074.png)

**Comment by HelvioMarkman** [comment] 2019-04-25 18:03
It is can be fixed by remove the Users page that is the first page of the system I am working on.

**Comment by PilotC150** [comment] 2019-04-25 18:08
Using the "Blazor (Server-Side)" template appears to have lead me in the right direction.  The way the templates are sorted in Visual Studio just made me not see that one (there were two Blazor ones near the top of the list with the third one further down so I missed it).  The documentation also confused me a bit, but now it all makes sense.

Using this template, then adding a Controllers folder with my own controller, then adding `services.AddMvc();` and `endpoints.MapDefaultControllerRoute();` into the Startup.cs let's me add in my own controllers for WebAPI purposes, which is what I'm looking to do.  Moreso for pushing data into the app from external sources rather than an external site getting data from the app, but same difference.

I'm running into some other issues now, but they aren't related to this bug, so I'll research independently from this.

Thanks for the quick response!

**Comment by javiercn** [comment] 2019-04-26 11:41
@PilotC150 Happy I was able to help.

Closing this issue as there's nothing else to do here.

**Closed by javiercn** 2019-04-26 11:41 UTC
Labels: area-mvc, feature-Components

**Comment by mxplusb** [comment] 2019-09-23 18:59
I stumbled across this when trying to research HTTP 400 errors on Blazor server-side issues after migrating to client side.

I was able to resolve the issue with `app.UseEndpoints(endpoints => { endpoints.MapBlazorHub(); });`.
