### ISSUE TITLE
SignalR - ObjectDisposedException in MobileAuthenticatedStream

### ISSUE THREAD

**Issue by freever** [aspnet/AspNetCore#9362] opened 2019-04-14 08:59 UTC
I have a Xamarin app that uses SignalR for all communication between client and server. When the app is sent into the background I call `StopAsync()` on all the HubConnections. When the app is foregrounded I call `StartAsync()`. 

This works, however I am picking up a lot of unobserved task exceptions in Android TaskSchedulerOnUnobservedTaskException and iOS HandleUnobservedTaskException:

Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
> at Mono.Net.Security.MobileAuthenticatedStream+d__58.MoveNext () [0x001bf] in <3e9b3e26c4694baab3f689687ad40612>:0

These may or may not be causing actual crashes for users, I am not sure. 

There seems to be some chatter about an issue in Mono and Xamarin:
https://github.com/mono/mono/issues/8350
https://github.com/xamarin/xamarin-macios/issues/3838
https://github.com/xamarin/xamarin-android/issues/2159

Some of the commentary suggests possible issues in libraries interacting with network streams:
> Appearances of unobserved exceptions from MobileAuthenticatedStream could indeed be caused by calls that use NetworkStream via some code path other than HttpClient.SendAsync(). Any library that interacts with network streams directly rather than via higher level APIs would need to ensure that it called EndWrite()

I'm at a loss as to how to solve this so I'm reaching out to see if there might be any problems with how I am doing my disconnect and reconnects. I am not Diposing of the HubConnection, I instantiate it once and then connect and disconnect it. 

I am using 1.1.0 of SignalR on client and server, and Visual Studio 15.9.4. 

Any help would be appreciated.

**Comment by anurse** [comment] 2019-04-16 19:45
Unfortunately that stack trace doesn't give us a lot to work with. Are you able to repro this yourself or is this data coming in from telemetry?

https://github.com/xamarin/xamarin-android/issues/2159 seems like the most likely candidate. We don't use `NetworkStream` directly, we use `HttpClient` and `ClientWebSocket`, and since that references a `ClientWebSocket` issue, it seems likely to be the underlying issue.

From the repro steps in the linked issue:

> * Perform a SendAsync and ReceiveAsync (passing in a CancellationToken)
> * Cancel the token during a Send or Receive

We *definitely* do this, during shutdown. It seems like this is pretty clearly causing the problem. Hopefully with such a reliable repro we can get Xamarin folks involved.

**Comment by anurse** [comment] 2019-04-16 21:15
@bradygaster can you ping some Xamarin folks to look at the linked Xamarin Android issue (2159)

**Comment by freever** [comment] 2019-04-17 11:41
Hi @anurse - thanks for the prompt action. I am able to reproduce this myself but the stack trace I get is very... terse. This is all I have from Android:

```json
[{
	"outerId": "0",
	"message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
	"type": "System.AggregateException",
	"id": "-2024460701"
}, {
	"parsedStack": [{
		"assembly": "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
		"method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
		"level": 0,
		"line": 0
	}, {
		"assembly": "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
		"method": "Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext",
		"level": 1,
		"line": 0
	}],
	"outerId": "-2024460701",
	"message": "Cannot access a disposed object.\nObject name: 'MobileAuthenticatedStream'.",
	"type": "System.ObjectDisposedException",
	"id": "1542684386"
}]
```

I'm a bit snowed under right now but if you don't manage to reproduce this let me know and I'll give it a shot. 

I'll see if the iOS stack trace is any more helpful and post it here if it is.

**Comment by anurse** [comment] 2019-04-17 14:50
> the stack trace I get is very... terse

Yeah, unfortunately it looks like the stack trace isn't terribly helpful because it's an unobserved task exception. Task stack traces are notoriously tricky because the async code means the "logical" stack and the actual execution stack aren't the same.

We'll be bringing this up to some of our Xamarin contacts and see if we can dig something up :).

**Comment by anurse** [comment] 2019-05-21 21:26
Closing as this is an external issue (the issue is in the Xamarin networking stack)

**Closed by anurse** 2019-05-21 21:26 UTC
Labels: area-signalr, cost: 0, xamarin

**Comment by freever** [comment] 2019-05-22 06:27
Thanks for the update @anurse 

Are you aware of there being an issue tracked somewhere else that I can follow for a resolution?

**Comment by anurse** [comment] 2019-05-22 16:08
https://github.com/xamarin/xamarin-android/issues/2159 (linked above) is the issue in Xamarin Android's repo.
