### ISSUE TITLE
Impossible to check if HttpContext-body is null/empty...

### ISSUE THREAD

**Issue by ststeiger** [aspnet/AspNetCore#3345] opened 2018-07-20 10:15 UTC
In ASP.NET-Core, there is no way to check if the request's body is NULL/empty...

I make a fetch request 
```
    let result = <any>await fetch(markerUrl, {
        "method": 'POST',
        // "headers": {'auth': '1234','content-type': 'application/json'},
        // https://stackoverflow.com/questions/38156239/how-to-set-the-content-type-of-request-header-when-using-fetch-api
        "headers": new Headers({ 'content-type': 'application/json' }),
        "body": null 
    })
    .then(function (response) { return response.json(); })
    ;
```
either with setting body to NULL or by omiting body altogether. 

In ASP.NET-Core, I get:

```
context.Responst.Body: is not NULL 
context.Request.Body.Length: System.NotSupportedException 
context.Request.Body.Position: System.NotSupportedException 
context.Request.Body.Seek(0, System.IO.SeekOrigin.End): System.NotSupportedException 
and
context.Request.Body._body.IsEmpty: true 
```
there is no public empty property on Body...

Consequentially, it's not possible to read the stream directly into a JSON-object, because there's no way to tell if there actually is a stream/empty-stream...

```
            if (string.Equals(context.Request.ContentType, "application/json", System.StringComparison.InvariantCultureIgnoreCase))
            {
                Newtonsoft.Json.Linq.JObject jsonData = null;

                // Can only be read ONCE ! 
                using (System.IO.StreamReader reader = new System.IO.StreamReader(context.Request.Body, System.Text.Encoding.UTF8, false, 4096, true))
                {
                    using (Newtonsoft.Json.JsonTextReader jsonReader = new Newtonsoft.Json.JsonTextReader(reader))
                    {
                       // KABOOM ! 
                        var a = Newtonsoft.Json.Linq.JToken.Load(jsonReader);
                        System.Console.WriteLine(a);
                        jsonData = Newtonsoft.Json.Linq.JObject.Load(jsonReader);
                    } // End Using jsonReader 

                } // End Using reader 
```

I don't want to use exceptions for this, because this is slowwwww...
I don't want to read it into a string, because that shouldn't be necessary either...

**Comment by Tratcher** [comment] 2018-07-20 16:07
@ststeiger how about checking the content-length header?

@JamesNK any suggestions for making the parser not choke on an empty stream?

**Comment by ststeiger** [comment] 2018-07-20 21:56
@Tratcher: Thanks, didn't think of that. That does the trick - assuming it's there - which it seems like it is.

**Comment by JamesNK** [comment] 2018-07-21 04:44
Doesn't JsonTextReader.Read() return false for an empty Stream?

**Comment by ststeiger** [comment] 2018-07-21 09:30
Is it intentional that it returns an empty stream instead of NULL when content-length is 0 ? 
I guess I can live with it, but it doesn't make much sense.

**Comment by Tratcher** [comment] 2018-07-21 13:05
Yes, it prevents a lot of null ref exceptions.

**Comment by ststeiger** [comment] 2018-07-21 14:13
And causes other problems in return ;)
Don't know if fetch can send a huge JSON as chunked - in which case you won't have a content-length. 
Anyway, for that specific problem, content-length is there, seems to work good enough for me atm. 
For all possible use-cases of a framework, it looks like a looming question-mark, waiting to shoot other people into the foot.

**Comment by anurse** [comment] 2019-04-12 03:58
`null` would be incorrect here. An empty stream is the correct behavior since that's what this is, it's a valid stream with no data. `ReadAsync` should return `0` indicating the end of the stream, as [per the contract for Stream](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=netframework-4.7.2).

Closing this as the current behavior is by design.

**Closed by anurse** 2019-04-12 03:58 UTC
Labels: area-servers, feature-HttpAbstractions
