### ISSUE TITLE
Blazor Library (preiview4) leaks *.razor into the host project

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#9650] opened 2019-04-22 19:51 UTC
### Describe the bug
After updating a Blazor Lib to preview4 we see that:

1. When adding it to a Blazor project you can now see all the *.razor files that are in the lib
2. Compile fails with an error: MSB3105 duplicate items in the sources parameter

### To Reproduce
Install from Nuget BlazorStrap-1.0.0-preview4 and add it to a blank blazor project

It was mentioned in the Glitter channel for Blazor that this behavior has been seen in other libraries as well.

### Expected behavior
*.razor should not be shown in the host project and it should compile

### Screenshots

![](https://user-images.githubusercontent.com/9521987/56518564-a5ebc280-64f4-11e9-9199-0b0e2380a0ec.png)

**Comment by IvanJosipovic** [comment] 2019-04-22 20:18
Looks like this is related to https://github.com/aspnet/AspNetCore/issues/9577

**Comment by danroth27** [comment] 2019-04-23 16:38
Closing as duplicate of #9577

**Closed by danroth27** 2019-04-23 16:38 UTC
Labels: area-mvc, feature-Components
