### ISSUE TITLE
web.config AspNetCoreModuleV2 SQLite unable to open database file

### ISSUE THREAD

**Issue by SeriaWei** [aspnet/AspNetCore#6117] opened 2018-12-25 15:41 UTC
### Unable to open database file
web.config `AspNetCoreModuleV2` SQLite throw the exception "unable to open database file".
### ConnectionString
```
"ConnectionString": "Data Source=Database.sqlite"
```
But when i change to use `AspNetCoreModule` or change the connection string to `Data Source=D:\\ZKEACMS\\Database.sqlite` the application run correctly.
### web.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\ZKEACMS.WebHost.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess" />
    </system.webServer>
  </location>
</configuration>
```

**Comment by SeriaWei** [comment] 2018-12-25 15:45
IIS Version :10.0

**Comment by pakrym** [comment] 2018-12-26 01:00
It's probably due to the CurrentDirectory issue: #4206. Here is our recommended workaround for now: https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs. This will be fixed in a patch.

**Comment by SeriaWei** [comment] 2018-12-26 01:02
I found that, `System.IO.Directory.GetCurrentDirectory()` not return the right directory
![image](https://user-images.githubusercontent.com/6006218/50427876-7b924b80-08ec-11e9-9243-e39ba102b81b.png)

**Comment by SeriaWei** [comment] 2018-12-26 01:09
@pakrym Thanks.

**Comment by pakrym** [comment] 2018-12-29 00:45
I assume the workaround has resolved your issue. Feel free to reopen otherwise.

**Closed by pakrym** 2018-12-29 00:45 UTC
Labels: area-servers, servers-iis

**Comment by ericjohannsen** [comment] 2019-03-13 02:31
How would the work-around help when attempting to create a SQLite database from Package Manager Console?

PM> Update-Database
SQLite Error 14: 'unable to open database file'.

**Comment by pakrym** [comment] 2019-03-13 16:32
@ericjohannsen the issue in this thread is not related to your problem and neither is the workaround. It's only applicable to applications running in IIS using AspNetCore InProcess hosting model. Can you please file your issue in http://github.com/aspnet/EntityFrameworkCore

**Comment by ericjohannsen** [comment] 2019-03-13 17:08
@pakrym Are you certain? The issue is that EF receives its configuration from AspNetCore using this line:

```
    services.AddDbContext<MyContext>(options =>
        options.UseSqlite(Configuration.GetConnectionString("DefaultConnection")));
```

I can make it work by hacking appsettings.json like this:

```
  "ConnectionStrings": {
    //"DefaultConnection": "Filename=./db/my.db"
    "DefaultConnection": "Data Source=E:/dev/myproject/wwwroot/db/my.db"
  },
```

Have a look at [this documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation), 

> If your startup project is an ASP.NET Core app, the tools try to obtain the DbContext object from the application's service provider.
> 
> The tools first try to obtain the service provider by invoking Program.BuildWebHost() and accessing the IWebHost.Services property.

If you still feel the issue is not related to how AspNetCore sets the current directory, please provide enough context so I can explain to the EF Core team why the problem resides with them.

**Comment by jkotalik** [comment] 2019-03-13 17:15
I would make sure that you are running on ASP.NET Core 2.2.2 and check again.

**Comment by ericjohannsen** [comment] 2019-03-14 02:47
I'm running on ASP.NET Core 2.2.3.
