### ISSUE TITLE
ASP.NET Core 2.1 Roadmap Update

### ISSUE THREAD

**Issue by steji113** [aspnet/AspNetCore#2135] opened 2017-08-16 16:51 UTC
# Roadmap Update

I know ASP.NET Core 2.0 was just released, but it might be helpful for contributors and users alike to have an idea of what the roadmap for ASP.NET Core 2.1 is looking like. Is this something that can be updated [here](https://github.com/aspnet/Home/wiki/Roadmap)?

Thanks!

**Comment by ghd258** [comment] 2017-08-18 00:16
Enterprise Library ，Unity and AntiXss support net core?

**Comment by Eilon** [comment] 2017-08-18 17:18
We'll have @DamianEdwards get an update to this. I think he's a few thousand miles/kilometers/parsecs away from work right now, but I'm sure he can do this when he returns.

**Comment by DamianEdwards** [comment] 2017-08-18 17:34
When I'm back, I'll update the roadmap and post a planning announcement over in aspnet/Announcements. In the meantime, folks can look at issues created in the 2.1 milestone in each of the repos to start getting an idea of what we're investigating for 2.1.

**Comment by steji113** [comment] 2017-08-18 19:43
Awesome, sounds good, thank you!

**Comment by ghd258** [comment] 2017-08-18 23:51
Razor Pages support ASP.Net server controls or have server controls?

**Comment by ghd258** [comment] 2017-08-18 23:51
The MVC programming model to his advantage, but there are also disadvantages, page data and logic processing mainly by JS control, C# is only to the front-end data transfer function, the C# instead of weakening, the enhanced JS and web; from ASPX, aspx.cs aspx.cs played this way with powerful back-end processing capabilities of C#, not only can provide data, but also can process the front interface with C# display or logical processing; hope to use the Razor Pages Cs, play the powerful function of C#

**Comment by garora** [comment] 2017-08-20 00:26
It would be nice, if we can have T4 templates.

**Comment by grahamehorner** [comment] 2017-09-01 19:13
@ghd258 have a look at #blazor 😎 C# in the browser could provide a powerful client side programming model that would works with the DOM to give the user experience your looking for 😉

**Comment by encrypt0r** [comment] 2017-09-20 06:03
Any plans to support a more modular architecture? Something like [OrchardCore ](/OrchardCMS/OrchardCore) would be nice

**Comment by Eilon** [comment] 2017-09-20 17:03
@encrypt0r - for a more modular architecture please use OrchardCore - it's great!

**Comment by Eilon** [comment] 2017-09-20 17:03
cc @sebastienros - see above comment.

**Comment by encrypt0r** [comment] 2017-09-20 20:07
@Eilon indeed it is. But an official solution means that Visual Studio supports it much better. Currently you need some sort of hacks to get a decent experience.

**Comment by Eilon** [comment] 2017-09-20 20:11
@encrypt0r there are no plans at this time to have something built into ASP.NET Core, but the community has produced some great solutions to many problems that aren't solved in the core product.

We'd like to learn more about what hacks are required for this and where the Visual Studio experience isn't as good as you'd like. Some might be issues in OrchardCore, and some might be issues elsewhere in ASP.NET Core or Visual Studio.

**Comment by encrypt0r** [comment] 2017-09-20 21:10
@Eilon These are a couple of the issues I can think of right now:
1. You can't add Views and Controllers via Add New Item (And therefore no scaffolding) in a Net Standard library. I get it, Visual Studio is trying to help you by giving you only the list of things that it thinks are applicable to a class library. One way to solve that is to use `Microsoft.Net.Sdk.Web`
2. I get some weird compilation issues when trying to use razor pages in the modules.

**Comment by Eilon** [comment] 2017-10-05 20:58
@encrypt0r thanks for the info.

Adding @rynowak regarding this feedback on Razor because these are some areas that we're looking to improve in future releases.

Also adding @sebastienros because he's had to deal with some of these issues while working on [Orchard Core](https://github.com/OrchardCMS/OrchardCore) and he might have some insights or tips & tricks on getting a better experience with what's already available.

**Comment by rynowak** [comment] 2017-10-05 21:50
>I get some weird compilation issues when trying to use razor pages in the modules.

@encrypt0r - can you please log an issue on https://github.com/aspnet/MvcPrecompilation

**Comment by encrypt0r** [comment] 2017-10-05 22:40
@rynowak Actually, I can't reproduce that issue anymore. It could have been some issue with not referencing the right packages or something. Using the empty web project template for the modules makes the experience much better.

**Comment by rynowak** [comment] 2017-10-06 01:28
@encrypt0r - I've added your feedback about new item to a tracking item here https://github.com/aspnet/Razor/issues/1712

If you have more feedback about what's broken/missing from class library scenarios please add it there

**Comment by encrypt0r** [comment] 2017-10-06 11:14
@rynowak No that's all I had

**Comment by SanderDeclerck** [comment] 2017-10-13 12:36
So... No updates on the 2.1 roadmap yet?

**Comment by Eilon** [comment] 2017-10-13 16:06
@SanderDeclerck we've been doing some internal planning and I think very soon @DamianEdwards will be posting some public info.

**Comment by mpoettgen** [comment] 2017-11-09 19:49
If I could make some wishes in terms of features, then it would be @SteveSandersonMS's Angular template based on Angular CLI (seems to be almost done, so would be great to get it) and [Health Checks](https://github.com/dotnet-architecture/HealthChecks).

**Comment by Guymestef** [comment] 2017-11-20 11:01
+1 for [Health Checks](https://github.com/dotnet-architecture/HealthChecks)

**Comment by Eilon** [comment] 2017-11-20 17:50
@mpoettgen we're actually planning to ship the Angular-CLI based templates even before the next full release of ASP.NET Core. Certainly at least a preview.

**Comment by Matthewsre** [comment] 2017-12-08 22:06
I have been hunting for updates on 2.1 roadmap and there doesn't appear to be much available. We are stuck with a dependency on WS-Fed, which support was cut from 2.0, and I was hoping this would be making an appearance in the near future.

**Comment by DamianEdwards** [comment] 2017-12-08 22:14
We have a preview of WS-Fed support out already, for use with 2.0.0

**Comment by nefcanto** [comment] 2017-12-13 03:47
I wanted to compile views/pages in assemblies and reuse them somewhere else, but I couldn't. I think this needs to be addressed too.
https://stackoverflow.com/questions/47726991/how-to-reuse-views-pages-in-asp-net-core-mvc

**Comment by DamianEdwards** [comment] 2017-12-13 04:01
@nefcanto we're working on a number of things that will help this scenario (in fact we had a meeting about it today). We'll share details in an issue soon.

**Comment by SychevIgor** [comment] 2018-01-11 07:20
It ill be nice to finally see updated version roadmap in wiki. https://github.com/aspnet/Home/wiki/Roadmap last update was in October - 4 months ago.

**Comment by Eilon** [comment] 2018-11-05 21:20
Closing old discussion. Please log a new issue if you have a question about anything else.

**Closed by Eilon** 2018-11-05 21:20 UTC
Labels: discussion
