### ISSUE TITLE
Blazor WASM: RenderTreeBuilder#AddMarkupContent is closing tags early

### ISSUE THREAD

**Issue by StandardDuckling** [aspnet/AspNetCore#17161] opened 2019-11-16 00:21 UTC
### Describe the bug

The Blazor WASM renderer seems to close tags early in AddMarkupContent. The use-case here is to dynamically invoke a Blazor component between some dynamic HTML.

Interestingly, when using server-side Razor rendering (prerendering), the proper HTML is built.

### To Reproduce

Have the following code in a Razor component. FooComponent is just a span echoing the text.

```C#
string[] lines = new string[] { "<p>", "<blazorcomponent>", "</p>" };
foreach (string line in lines)
{
    if (line == "<blazorcomponent>")
    {
        builder.OpenComponent(1, typeof(FooComponent));
        builder.AddAttribute(2, "SomeParameter", "SomeValue");
        builder.CloseComponent();
    }
    else
    {
        builder.AddMarkupContent(3, line);
    }
}
```

When rendering the code server-side the code is:

```html
<p>
	<span>SomeValue</span>
</p>
````

Once the page reloads for the WASM renderer, the following is in the DOM:

```html
<p></p><span>SomeValue</span>
```

It seems the WASM renderer here is closing the `</p>` tag in the MarkupContent automatically. Whilst this may be useful when forgetting closing a tag, it breaks my feature here.

### Further technical details
- ASP.NET Core version: 3.1.100-preview3-014645

**Comment by rynowak** [comment] 2019-11-16 00:26
I would have been really surprised if this works actually. We expect each fragment of markup in an `AddMarkupContent` call to be a well-formed set tree of dom nodes.

**Comment by javiercn** [comment] 2019-11-18 17:40
We are closing this issue as the behavior is by design. Add markup content is for complete markup blocks. If you need something else, then you should use `builder.OpenElement` and similar methods.

**Closed by javiercn** 2019-11-18 17:40 UTC
Labels: area-blazor
