### ISSUE TITLE
Server-side blazor with rendering errors races and consumes all memory

### ISSUE THREAD

**Issue by csharpfritz** [aspnet/AspNetCore#13676] opened 2019-09-04 14:48 UTC
#12637 ```# Describe the bug
While working with a server-side blazor project, when a NullReference error happens inside the razor file, the server races and all memory is consumed.  Consider the demo on video at:  https://www.twitch.tv/videos/476717145?t=00h33m29s

### To Reproduce
1. Using ASP.NET Core 3 preview 8, build a simple server-side blazor application
2. Reference a null object in the razor markup
3. browse to that page
4. wait while memory is consumed

### Expected behavior
No extra memory consumption when a rendering error happens

### Screenshots
https://www.twitch.tv/videos/476717145

### Additional context
Error reported in JavaScript console is:

```
[2019-09-04T14:47:55.837Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PixelBot.Orchestrator.Components.Pages.Configuration.BuildRenderTree(RenderTreeBuilder builder) in C:\dev\Quiltoni.PixelBot\PixelBot.Orchestrator\Components\Pages\Configuration.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
```

**Comment by csharpfritz** [comment] 2019-09-04 14:51
The project used in this video sample is at:  https://github.com/csharpfritz/Quiltoni.PixelBot

**Comment by rynowak** [comment] 2019-09-04 14:58
would it be possible for you to collect a dump while this is happening?

**Comment by rynowak** [comment] 2019-09-04 14:59
We've seen issues like this internally a few times, but never with a repro - usually the issue has already been fixed by the time it's reported and triaged.

**Comment by rynowak** [comment] 2019-09-20 20:25
Closing this as no repro. We were able to reproduce this one earlier previews, but I haven't been able to repro on a recent build.

**Closed by rynowak** 2019-09-20 20:25 UTC
Labels: area-blazor, bug, more-info-needed

**Comment by TheCakeMonster** [comment] 2019-09-22 11:18
Not sure if this is relevant, but posting as an idea in case this is seen again in the future.

In this component, Jeff had an overriding OnInitializedAsync method. At the end of the method, he delegated to base.OnInitializedAsync, but without a return or await statement, which looked a bit odd. That's exactly what you'd do with a sync method, but it's not right with an async one is it?

```
	protected override async Task OnInitializedAsync()
	{
		/// Some code with an await
		await Task.Delay(20);

		base.OnInitializedAsync();
	}
```

**Comment by rynowak** [comment] 2019-09-23 16:29
Well spotted.

I don't think this could be the cause (unless this inherited from another component) because we intentionally leave the `base` methods on `ComponentBase` empty.
