### ISSUE TITLE
GenericHost throws PlatformNotSupportedException on Xamarin

### ISSUE THREAD

**Issue by SteveBush** [aspnet/AspNetCore#14783] opened 2019-10-07 07:18 UTC
### Describe the bug
ConsoleLifetime uses static Console class to add/remove a Cancel (ctrl-C) keypress.  The Console.CancelKeyPress event handler on Xamarin.Android and Xamarin.IOS throws a PlatformNotSupportedException. 

### To Reproduce
Steps to reproduce the behavior in Visual Studio 16.3.2:
1. Using Microsoft.Extensions.Hosting, v3.0.0 and Xamarin.Android v28.0.0.3.
2. Create a blank Xamarin Forms Mobile App

in MainActivitity.cs, add
           var host = new HostBuilder().Build();
            host.StartAsync().GetAwaiter().GetResult();
before Loading Application

Result: Exception is thrown
System.PlatformNotSupportedException
  Message=Operation is not supported on this platform.

### Expected behavior
Expect no thrown exception.  Three potential options for fixing:
1) Create a new AppLifetime class which does not include the hooking of CancelKeyPress.
2) Implement CancelKeyPress in Android and IOS Xamarin.
3) Allow ConsoleLifetime to be superclassed so I could override the StartAsync and StopAsync methods to remove the calls to CancelKeyPress.

I was able to work around this issue by implementing my own MobileLifetime class that excludes the calls to CancelKeyPress.  I injected the MobileLifetime class in ConfigureServices to replace the ConsoleLifetime implementation of the IHostLifetime interface.

**Comment by Tratcher** [comment] 2019-10-07 16:00
Duplicate of https://github.com/aspnet/Extensions/issues/1631

**Closed by Tratcher** 2019-10-07 16:00 UTC
Labels: area-hosting
