### ISSUE TITLE
MVC client-side validation issues with Edge input field auto-complete

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#4243] opened 2018-11-27 02:35 UTC
Reproduced this with 2.2.0 RTM bits, VS 2017 15.9.2, and Edge (build). See output of `dotnet --info` below.

## Overview
It seems the Edge field auto-completion implementation is firing DOM events in such a way that it results in usability issues for our client-side validation story (jQuery Validate). None of these issues appear to reproduce in Chrome.

## Reproduction Steps
1. In VS, create an app using the "ASP.NET Core Web Application" template, targeting .NET Core, using ASP.NET Core 2.2, and using Individual User Accounts:
   ![image](https://user-images.githubusercontent.com/249088/49046663-b5efb800-f189-11e8-92bb-7d043315e24f.png)
1. Launch it without debugging (Ctrl+F5) in Edge
1. Once the home page appears, open the Edge Dev Console (F12)
1. Click the "Accept" link in the cookie/privacy policy alert
1. Click the "Register" link in the main nav bar
1. Give the email field focus and type the first 2 or 3 characters of an email **that has been entered previously** (i.e. it must appear in the auto-complete drop-down that Edge shows)
1. Select the suggested full email address from the drop-down by using the arrow keys to navigate to it and hit `Tab`

## Expected Results
The value is populated in the field, no error message is displayed, and the next field is selected.

## Actual Results
The value is populated in the field, the next field is selected, but an validation error message is displayed stating that the email address is not valid. It seems the validation ran before the field was populated with the value from the auto-complete list.

![image](https://user-images.githubusercontent.com/249088/49054691-eb0c0280-f1a9-11e8-957a-60adb085cce4.png)

@mkArtakMSFT @rynowak  

## Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    51868761f2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by ryanbrandenburg** [comment] 2018-11-28 20:17
My research suggests that this is either a jquery-validation or an Edge problem (depending on your philosophy) rather than a problem with jquery-validatioin-unobtrusive. What seems to happen is that when you hit Tab the field loses focus firing the "focusout" event and validation is then run against the value that you had typed in (probably "da" or some such in your case). THEN Edge updates the field with the value that you selected, firing only the "change" event. jquery-validation doesn't register events for "change" events, so it has no idea that it needs to re-evaluate that field and it leaves the validation message for "da" despite a valid email being the current value.

This does not replicate on my personal copies or Chrome or Firefox.

It seems to me that a fix should come from either jquery-validation or Edge, to either start paying attention to change events or make the change to the field before losing focus, respectively. @DamianEdwards which team should we pursue/alert for a fix (or should it be both)?

**Comment by ryanbrandenburg** [comment] 2018-11-28 20:31
This also does not replicate if you hit Enter instead of Tab, because focus is not lost when enter is pressed.

**Comment by ryanbrandenburg** [comment] 2018-11-30 19:04
I'm not sure how to determine if this is a regression in Edge since I can't find any way to downgrade it on my machine and I can't for the life of me get a VM to create successfully on AspNetEF.

The more I think about it I'm not sure that watching both `focusout` and `change` would even be a good idea. `change` fires when a change has been "submitted", and one of the ways that a change can be "submitted" it when the element loses focus, so validation would trigger twice.

Regardless of which avenue we pursue, I don't think we'll be getting this change into 2.2.1

**Comment by ryanbrandenburg** [comment] 2018-12-18 20:15
I filed an issue against Edge [here](https://userfeedback.visualstudio.com/UIF/_workitems/edit/7599645/).

**Comment by mkArtakMSFT** [comment] 2018-12-19 18:44
Moving this out to a further milestone, as this is just a tracking issue.

**Comment by ryanbrandenburg** [comment] 2019-03-25 19:15
Is this something we still care about considering the changes coming for Edge?

**Comment by lizmathew92** [comment] 2019-05-09 07:59
Any updates on this?

**Comment by mkArtakMSFT** [comment] 2019-05-10 22:54
Closing as this is not actionable for us and we've been using this as just a tracking issue.

**Closed by mkArtakMSFT** 2019-05-10 22:54 UTC
Labels: 1 - Ready, PRI: 1 - Required, area-mvc, blocked, bug, cost: 0, external
