### ISSUE TITLE
Html.BeginForm() does not render appropriate attributes needed for IFormFile to be non-null

### ISSUE THREAD

**Issue by D9001** [aspnet/AspNetCore#11452] opened 2019-06-21 16:55 UTC
> Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

_Originally posted by @mkArtakMSFT in https://github.com/aspnet/Mvc/issues/7901#issuecomment-398143571_

This issue still exists in .NET Core 2.2. Is it intentionally not being supported without the workaround referenced in the original issue? @mkArtakMSFT seemed to close it because he could not reproduce it, but this seems to be a widely known issue at this point.

**Comment by mkArtakMSFT** [comment] 2019-06-21 22:34
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by D9001** [comment] 2019-06-24 01:41
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

I can do that, but it would literally just be the default project + the code that he added in the earlier issue. The fact is that` Html.BeginForm() `doesn't automatically produce the required `enctype` attribute without additional parameters being added as he mentioned. Without that attribute, the controller methods never pick up the file from the form (i.e., it is null) every time. If this is by design, that's okay. It just took a little while for me to track down.

**Comment by mkArtakMSFT** [comment] 2019-07-17 22:29
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Closed by mkArtakMSFT** 2019-07-17 22:29 UTC
Labels: area-mvc, investigate
