### ISSUE TITLE
JsonInputFromatter validation issue

### ISSUE THREAD

**Issue by ArtemAstashkin** [aspnet/AspNetCore#4946] opened 2018-11-20 10:06 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1. You have an action in a Controller
2. The action has a requestModel with array of integers
3. You send a request to the action with invalid model - for example array with string.Empty instead integers
4. You expect to receive BadRequest, but you will receive Http Ok after a long period of time

I've attached the repo to reproduce this issue https://github.com/ArtemAstashkin/JsonInputFormatterTest

1) The repo has 2 projects (Web and Web.Tests). Web has HomeController and Post action with RequestModel 
```C#
    public class RequestModel
    {
        public string Key { get; set; }

        [FromBody]
        [Required]
        public PostRequestModelBody Body { get; set; }
    }
```
2) The Web.Tests project has only one specific test to reproduce the issue
```C#
        [Fact]
        public async Task ShouldReturnBadRequest()
        {
            var itemIds = Enumerable.Repeat(string.Empty, 621).ToArray();
            var body = JSON.SerializeDynamic(new { ItemIds = itemIds });

            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Post,
                RequestUri = new Uri("/api/home?key=test", UriKind.Relative),
                Content = new StringContent(body, Encoding.UTF8, "application/json"),
            };

            var sut = await Sut.AsyncInstance;
            var response = await sut.SendAsync(request);

            Assert.Equal(
                expected: HttpStatusCode.BadRequest,
                actual: response.StatusCode);
        }
```

The test will fail. But, if you change 621 to 199 it will pass.

#### Description of the problem:
The issue is related to the JsonInputFormatter which tries to mark validation errors as handled and validate all items in arrays and all properties in a model. But it take a lot of time. Moreover it has a limit of exceptions (200 as default). Eventually if somebody sends invalid model with 600 string.Empty (for example, 201 - enough) in array instead of integers, the formatter will spend a lot of time to parse it without any expected result - because it will fail after 200th error and return status OK instead of BadRequest.

It has 2 problems:
1) validation doesn't work properly
2) performance issue - formatter spends a lot of time to try to parse all invalid values so a malefactor can cause serious performance issues on online high-load services

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.1

**Comment by dougbu** [comment] 2019-02-03 21:55
@ArtemAstashkin I see now that this issue is a duplicate of aspnet/Mvc#7992. That bug was fixed in ASP.NET Core 2.2.0 (with aspnet/Mvc@f2608c2ff4). Suggest upgrading your application to 2.2.1, the latest 2.2.x release.

**Closed by dougbu** 2019-02-03 21:55 UTC
Labels: 1 - Ready, PRI: 1 - Required, area-mvc, bug
