### ISSUE TITLE
ASP.NET Core 2.2 issue with setting up http/2 endpoint on Kestrel via code

### ISSUE THREAD

**Issue by KirylZotkin** [aspnet/AspNetCore#12089] opened 2019-07-11 13:39 UTC
### Describe the bug
I want to set up http/2 endpoint on Kestrel. It only works if I do configuration in appSettings.json. Configuring the same settings from the code leads to serving requests via http1.1 only.

### To Reproduce
1. Using this version of ASP.NET Core 2.2.300
2. On Windows 10 Pro, x64, Version 1903 OS build 18362.239
3. Create WebHosting cert in IIS10 and export it into a .pfx file
2. Create asp.net core web-api app in VS2019 v16.1.5
2. Run this code

```
   WebHost.CreateDefaultBuilder(args)
                 .UseKestrel(opt =>
                 {
                     opt.ListenAnyIP(44336, listenOptions =>
                     {
                         listenOptions.UseHttps(@"testcert.pfx", "123456");
                         listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                     });
                 })
   .UseStartup<Startup>();
```

3. Launch Chrome Version 75.0.3770.100 (Official Build) (64-bit)
4. Make a request at https://localhost:44336/api/values

### Expected behavior
Chrome reports h2 in Protocol tab in DevTools

### Actual behavior
Chrome reports http/1.1 in Protocol tab in DevTools

===========================================

**And here is an odd thing. It works just fine via appSettings.json** -

### Configuration via appSettings.json

```
  "Kestrel": {
    "EndPoints": {
      "HttpsInlineCertFile": {
        "Url": "https://localhost:44336",
        "Protocols": "Http1AndHttp2",
        "Certificate": {
          "Path": "./testcert.pfx",
          "Password": "123456"
        }
      }
    }
  }
```

```
  WebHost.CreateDefaultBuilder(args)
                 .UseKestrel()
  .UseStartup<Startup>();
```

### Expected behavior
Chrome reports h2 in Protocol tab in DevTools

### Actual behavior
Chrome reports h2 in Protocol tab in DevTools

### Additional context

Chrome reports the same info on Security tab for the both cases - 

"The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with P-384, and AES_256_GCM."

**Comment by Tratcher** [comment] 2019-07-11 15:34
Duplicate of https://github.com/aspnet/AspNetCore/issues/11833, try reversing the order:
```
                         listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                         listenOptions.UseHttps(@"testcert.pfx", "123456");
```

**Comment by anurse** [comment] 2019-07-16 22:25
Closing as this is a duplicate.

**Closed by anurse** 2019-07-16 22:25 UTC
Labels: area-servers, duplicate, servers-kestrel
