### ISSUE TITLE
Bug on web.config file, if application's name has a SPACE (character)

### ISSUE THREAD

**Issue by livarcocc** [aspnet/AspNetCore#3947] opened 2018-11-06 17:46 UTC
_From @vitox32 on November 6, 2018 10:6_

## Error
On webapp startup (asp.net core module, with IIS, that uses on background the commandline), it crashes because the name of the webapp has a space (character) in it, and the `.dll` file also has the space in its name. So, when the argument value is passed on the commandline, the argument is not a literal string, but is split in multiple arguments.

## Expected  behavior
Inside `web.config` file, it should have surrounding quotations for the `attributes` value, for the element `<aspNetCore>`.
Example: `<aspNetCore processPath="dotnet" arguments='".\My WebApp.dll"' />`

## Actual behavior
Inside `web.config` file, there is NO surrounding quotations for the `attributes` value. 
Example: `<aspNetCore processPath="dotnet" arguments=".\My WebApp.dll" />`

## Steps to reproduce
Create and Publish a Web Application with Asp.net Core 2.1 (or up), with the last current Visual Studio (mine is 15.8.9). **The application must have a space (character) in its name**, like "My WebApp". Publish using method "File System".

## Environment data
`dotnet --info` output: 2.1.403
Windows Server 2012 R2 (but this is not important)
IIS 8.5
Visual Studio 15.8.9
Application: Asp.net Core 2.1

_Copied from original issue: dotnet/cli#10285_

**Comment by livarcocc** [comment] 2018-11-06 17:46
_From @vitox32 on November 6, 2018 10:54_

@wli3

**Comment by jkotalik** [comment] 2018-11-06 21:36
@vijayrkn shouldn't we escape spaces appropriately in processPath generation?

**Comment by vijayrkn** [comment] 2018-11-06 21:41
This is a dupe of this issue - https://github.com/aspnet/websdk/issues/237

**Closed** 2018-11-06 21:45 UTC
Labels: area-servers
