### ISSUE TITLE
Asp Core Razor Components (SS) removing or comment create hard to understand error

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/AspNetCore#10016] opened 2019-05-06 22:02 UTC
### Describe the bug
With Asp Core Razor Components removing or comment line of code create an error.

> 'Hero' does not contain a definition for 'Birthfactors' and no accessible extension method 'Birthfactors' accepting a first argument of type 'Hero' could be found (are you missing a using directive or an assembly reference?)
> \obj\Debug\netcoreapp3.0\Razor\Components\Layout\Hero\Properties.cshtml.g.cs	

### To Reproduce
1. Using this version of ASP.NET Core 'Preview 3.0 preview 3' (i don't know how to query the build)
2. Rebuild and Clean Solution don't fix the problem
3.
I use a class named hero and another class named calculatepropertyvalue. In hero i create a property named birthfactors. 
```
 public class Hero
    {
        public Hero()
        {
             public List<CalculatePropertyValue> Birthfactors { get; set; } = new List<CalculatePropertyValue>();
            }
       }
```
3. I add to a Razor Component this line
`<button onclick="@((p) => hero.Factors.Add(hero.Birthfactors[1].Id))">Speichern</button>`

The line of code see in 3 create the error. 
### Additional context

.NET Core SDK (gem„á "global.json"):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

The code at 3 create the error, but the error is hard to understand, because it leads to a different file at a different code position (of the generated file).

**Comment by SteveSandersonMS** [comment] 2019-05-07 15:05
The code sample you've posted is invalid and won't compile, because it contains a property definition inside a constructor, here:

```cs
 public class Hero
    {
        public Hero()
        {
             public List<CalculatePropertyValue> Birthfactors { get; set; } = new List<CalculatePropertyValue>();
            }
       }
```

Could you post a valid code sample that reproduces the problem?

**Comment by SteveSandersonMS** [comment] 2019-05-07 15:08
Or are you just reporting that, when you deliberately cause a compiler error (by commenting out the `Birthfactors` property), the error message refers to the generated code (`Properties.cshtml.g.cs`) instead of the original source (`Properties.cshtml`)?

If this is the case then it's a known limitation of how things work currently.

**Comment by UrielMhezzek** [comment] 2019-05-07 16:26
When I first wrote the problem, I didn't know how to fix it. 
Yes, the error is generated in the .g.cs. It would be helpful to jump to the g.cs when "double-clicking" on the error. So the search is very laborious.

**Comment by SteveSandersonMS** [comment] 2019-05-07 16:38
Great news - this was fixed in the preview 5 release!

If you update to preview 5 and still encounter this, please let us know.

**Closed by SteveSandersonMS** 2019-05-07 16:38 UTC
Labels: area-mvc, feature-Components
