### ISSUE TITLE
Behaviour of Spa Middleware seems odd, please confirm

### ISSUE THREAD

**Issue by chrisckc** [aspnet/AspNetCore#5260] opened 2018-11-02 15:35 UTC
I have been attempting to get a Spa app running nicely from a sub-path of the root of an MVC app in both development and production modes. While getting it working I decided to take a step back and gain a deeper understanding how the various bits of Spa middleware actually worked under the hood.

The Docs don't say much about how it works: https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio
 
During my analysis I found a number of things that seem a bit odd so i thought i would post about them here to get some help gain an understanding why it's doing what it does, here is what i did:

I used 'dotnet new angular' to create a project and then deleted all the contents of the ClientApp dir.
I then added 2 test files, index.html and test.html to an empty 'ClientApp/dist' dir.

I also commented out app.UseStaticFiles() which serves files from wwwroot as i am only concerned with how the Spa related code behaves.
I added some logging to the middleware pipeline so i can see what's going on. The repo is available here: https://github.com/chrisckc/DotNetCoreSpaTemplateAnalysis

I then ran the project and made some requests from the browser as follows:

Running in Development mode:
```
These requests are handled by the UseProxyToSpaDevelopmentServer middleware:
https://localhost:5001 > forwarded to: https://localhost:8080/
https://localhost:5001/page.html > forwarded to: https://localhost:8080/page.html
https://localhost:5001/some/arbitary/path > forwarded to: https://localhost:8080/some/arbitary/path
https://localhost:5001//some/arbitary/path > Generates an exception: SocketException: Device not configured
https://localhost:5001//example.com > forwarded to: http://example.com

These requests are handled by the UseSpaStaticFiles middleware:
https://localhost:5001/index.html > Serves contents of file: ClientApp/dist/index.html
https://localhost:5001/test.html > Serves contents of file: ClientApp/dist/test.html
https://localhost:5001//test.html > Serves contents of file: ClientApp/dist/test.html
```

Running in Production mode:
```
These requests are handled by the UseSpa middleware: (which rewrites all requests to /index.html)
https://localhost:5001 > Serves contents of file: ClientApp/dist/index.html
https://localhost:5001/page.html > Serves contents of file: ClientApp/dist/index.html
https://localhost:5001/some/arbitary/path > Serves contents of file: ClientApp/dist/index.html
https://localhost:5001//some/arbitary/path > Serves contents of file: ClientApp/dist/index.html
https://localhost:5001//example.com > Serves contents of file: ClientApp/dist/index.html

These requests are handled by the UseSpaStaticFiles middleware:
https://localhost:5001/index.html > Serves contents of file: ClientApp/dist/index.html
https://localhost:5001/test.html > Serves contents of file: ClientApp/dist/test.html
https://localhost:5001//test.html > Serves contents of file: ClientApp/dist/test.html
```

As can be seen from the above its possible to get the SpaProxy to proxy requests to any other host which should not be allowed. Refer to this issue: https://github.com/aspnet/JavaScriptServices/issues/1779

In development mode, matching file as still served from the ClientApp/dist dir, this could cause headaches, such as finding that changes to files are not being reflected in the browser because a production build has been left behind in the ClientApp/dist dir.

Luckily the file bundle created during the production build using the default config uses hashes in the filenames so there should not be any clashes. Requests for / are not handled by the UseSpaStaticFiles as it does not match a filename, so the Request then hits the UseSpa middleware which unconditionally rewrites the request path to /index.html.

So due to the above, again as luck would have it, when you hit https://localhost:5001 you will get the latest index.html from the Angular dev server which references the latest files. However if you hit https://localhost:5001/index.html you will get the index.html from the ClientApp/dist dir and a copy of the previous production build.

There are 3 issues here as i see it:

1. In the generated Angular Spa template project, the UseSpaStaticFiles middleware should be wrapped in an if !env.Development() statement, i can't see any reason for it to be enabled in Development mode with the workflow designed as it is.

2. In production mode there seems to be no need for the UseSpa (internally just uses SpaDefaultPageMiddleware) middleware to unconditionally rewrite every request path that hits it to /index.html. It only needs to rewrite requests to the root '/'. _**EDIT: I noticed that the Angular app is using HTML5 pushstate so that real url's can be used rather than hash based url fragments off root such as /#/somepage. (I have been using Aurelia which uses hash based url fragments by default). Because of this it would need to also rewrite non-root requests.**_ In fact it would be better not to have UseSpa enabled in production mode and instead but some middleware before the UseSpaStaticFiles middleware which just rewrites requests to '/' to index.html. **_EDIT: or rewrite requests that do not contain a dot in the path, ie. ones that don't look like requests for files._** So rather than wrapping just the call to the proxy middleware in the if statement, wrap the whole UseSpa block in it and instead use a custom rewrite middleware before UseSpaStaticFiles.

3. I think the structure of the Spa middleware needs to be reviewed to make it more configurable and flexible for different scenario's such as hosting to the Spa off the root path, for example at '/app' or '/frontend'

As a side note, If you run the Node Http server against the dist dir, as described in the readme in my repo, you will notice that it only rewrties requests to '/' to index.html. My guess is that the Spa middleware has been designed to work like the Angular dev server which does seem to rewrite any requests that don't match a file to the index.html. This is only dev behaviour but it seems like the Spa middleware has been designed to behave like this in production mode as well. I don't agree with that behaviour in either mode, it should still only be rewriting '/' in my opinion. **_EDIT: or rewriting requests that do not contain a dot in the path, ie. ones that don't look like requests for files._**

Here is the relevant code:

https://github.com/aspnet/JavaScriptServices/blob/ea3a7bc8974271d6e9eeb9e890f23f953b8b40e2/src/Microsoft.AspNetCore.SpaServices.Extensions/SpaDefaultPageMiddleware.cs#L23-L28

**Comment by mkArtakMSFT** [comment] 2019-07-22 17:18
Seems to be a dupe of https://github.com/aspnet/AspNetCore/issues/5261

**Closed by mkArtakMSFT** 2019-07-22 17:18 UTC
Labels: area-mvc, feature-spa
