### ISSUE TITLE
Test failure: _8_Exec

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3744] opened 2018-10-29 12:52 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) with the following error:

```
System.InvalidOperationException : Command dotnet restore /warnaserror --no-cache --source https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181029-01/final/index.json --source https://api.nuget.org/v3/index.json --runtime osx-x64 returned exit code 1

  Restoring packages for /Users/vsts/agent/2.141.1/work/_temp/tmpPiBxUx.tmp/web/EnvironmentVariableAndNuGetOrg/osx-x64/web.csproj...
  Installing System.Xml.XmlSerializer 4.3.0.
  Installing System.Private.DataContractSerialization 4.3.0.
  Installing System.Security.Principal 4.3.0.
  Installing System.Diagnostics.DiagnosticSource 4.3.0.
  Installing Microsoft.AspNetCore.App 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Authentication.Google 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Authentication.Facebook 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Authentication 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Authentication.Twitter 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Authentication.MicrosoftAccount 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Cryptography.KeyDerivation 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.HostFiltering 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Authentication.Cookies 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.DataProtection.Extensions 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Diagnostics.HealthChecks 2.2.0-rtm-35586.
  Installing System.Runtime.Serialization.Xml 4.3.0.
  Installing Microsoft.AspNetCore.HttpOverrides 2.2.0-rtm-35586.
  Installing System.Security.Claims 4.3.0.
  Installing Microsoft.IdentityModel.Logging 5.3.0.
  Installing System.Diagnostics.Contracts 4.3.0.
  Installing runtime.win-x64.runtime.native.System.Data.SqlClient.sni 4.4.0.
  Installing Microsoft.AspNetCore.Connections.Abstractions 2.2.0-rtm-35586.
  Installing runtime.win-x86.runtime.native.System.Data.SqlClient.sni 4.4.0.
  Installing Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.2.0-rtm-35586.
  Installing runtime.win-arm64.runtime.native.System.Data.SqlClient.sni 4.4.0.
  Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
  Installing System.IO.FileSystem 4.0.1.
  Installing Microsoft.AspNetCore.Localization.Routing 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Identity 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.HttpsPolicy 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.CookiePolicy 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Formatters.Xml 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Owin 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.ResponseCompression 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Mvc.Razor.ViewCompilation 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.ResponseCaching 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Session 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Rewrite 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.SignalR 1.1.0-rtm-35586.
  Installing Microsoft.AspNetCore.Identity.UI 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.SpaServices 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.StaticFiles 2.2.0-rtm-35586.
  Installing Microsoft.EntityFrameworkCore.Analyzers 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Server.Kestrel.Https 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.SpaServices.Extensions 2.2.0-rtm-35586.
  Installing Microsoft.EntityFrameworkCore.Abstractions 2.2.0-rtm-35586.
  Installing Microsoft.EntityFrameworkCore.InMemory 2.2.0-rtm-35586.
  Installing Microsoft.AspNetCore.Server.Kestrel 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.Configuration 2.2.0-rtm-35586.
  Installing Microsoft.Extensions.Configuration.Binder 2.2.0-rtm-355
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-10-29 12:52
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-29 12:52
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 141 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=36467) on release/2.2 at 12:38:50 PM:
- _4_BuildIncremental
- _8_Exec
- _8_Exec
- _7_PublishIncremental
- _8_Exec
- _7_PublishIncremental
- _3_Build
- _6_Publish
- _4_BuildIncremental
- _1_Restore
- (And 131 more test failures in this build)

**Comment by natemcmaster** [comment] 2018-10-29 15:50
Duplicate of https://github.com/aspnet/AspNetCore/issues/3686

**Closed by natemcmaster** 2018-10-29 15:50 UTC
Labels: Branch:release/2.2, test-failure
