### ISSUE TITLE
ERR_INVALID_HTTP_RESPONSE since Net Core 2.2

### ISSUE THREAD

**Issue by pietrodicaprio** [aspnet/AspNetCore#6166] opened 2018-12-28 23:33 UTC
### Describe the bug
Since the upgrade to Net Core 2.2 the API(s) are answering, most of the times, with a status code 0 (instead of 200)

### To Reproduce
1. Create an API project based on Net Core 2.2
2. Enable CORS
3. Make an API request trough javascript `XMLHttpRequest()`
4. Check the status code of the request

Test solution here: https://github.com/pietrodicaprio/NetCoreTestAPI2.2

### Expected behavior
Good answer with status code 200

### Screenshot
(auto) request interval of 5 seconds
Net Core 2.1: https://i.imgur.com/kLtSc3R.png
Net Core 2.2: https://i.imgur.com/6QsxQp3.png

### Additional context
Since this upgrade is not even possible to add an API controller by
`right click on 'controllers' -> Add -> Controller -> API Controller - Empty`
since there is an error `there was an error running the selected code generator`

If you perform multiple 'fast' requests the answer is almost always good but if there is something like more than 1 second between requests then you have this strange behavior. 
Found this StackOverflow post from 24/Dec/18 from an user with the same issue: https://stackoverflow.com/questions/53906866/neterr-invalid-http-response-error-after-post-request-with-angular-7

output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by pietrodicaprio** [comment] 2018-12-28 23:54
Just found that author of StackOverflow post opened #6114

**Comment by pietrodicaprio** [comment] 2018-12-29 00:54
@pakrym you're right! It is the same issue and the workaround works!
Moreover i noticed that the pre-flight request is sent only if i set the 'Authorization' Header in the 'XMLHttpRequest', that's why you don't see it in every scenario.

**Comment by pakrym** [comment] 2018-12-29 00:55
Closing this a duplicate of #4398.

**Closed by pakrym** 2018-12-29 00:55 UTC
Labels: area-servers, servers-iis
