### ISSUE TITLE
AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures 'zh-CN, zh'.

### ISSUE THREAD

**Issue by zirain** [aspnet/AspNetCore#6435] opened 2019-01-07 03:20 UTC
### Describe the bug
Open any url with chrome got warn message

### To Reproduce
1. Using this version of ASP.NET Core '2.1' 
2.Open any url with Chorme 71+, insepect http request
![image](https://user-images.githubusercontent.com/4354057/50747203-b17ceb80-126d-11e9-8848-90a9f34a046b.png)
4. get error as follow
Logger name: Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware
Level: Warn
Message: AcceptLanguageHeaderRequestCultureProvider returned the following unsupported UI Cultures 'zh-CN, zh, en'.

### Expected behavior
show not report this warn message

### Additional context
Nothing happen when open the same url with Microsoft Edge

**Comment by sebastienros** [comment] 2019-02-14 20:51
I can reproduce. The problem is that it adds a WARN level log for any request that is from a browser whose default culture is not one from the list of supported cultures in the application. Let's say you configure your application to support English and French, anyone who doesn't have these will generate a WAN log on every request. 

I think the issue is the level of logging, it should not even be INFO IMO. I think Warning is the default log level for ASP.NET templates.

**Comment by zirain** [comment] 2019-02-15 02:42
@sebastienros maybe it's a Chrome issue? cause I can't reproduce on Microsoft Edge

**Comment by daniel-white** [comment] 2019-02-21 19:36
duplicate of: https://github.com/aspnet/AspNetCore/issues/4504

**Comment by sebastienros** [comment] 2019-02-21 19:42
I confirm it's a duplicate and this can be closed.

**Closed** 2019-02-25 06:02 UTC
Labels: area-mvc
