### ISSUE TITLE
Move password management out of UserManager into its own injectable class

### ISSUE THREAD

**Issue by saluce65** [aspnet/AspNetCore#11043] opened 2019-06-10 16:47 UTC
In ASP.NET Identity, I want to use LDAP (or Active Directory) for password management while storing user data using EntityFrameworkCore.  Changing the password authentication should be as simple as injecting a custom `IUserPasswordStore`, but the interface only provides `GetPasswordHash` and `SetPasswordHash` methods, which are not possible to use for LDAP. 

I'd like to propose alternatives to a `IUserPasswordStore` that will move the authentication of the password out of the `IUserStore` implementations (which are implementing `IUserPasswordStore`) into a separate class/interface.  

I'm thinking of something like a `PasswordManager` implementation of an `IPasswordManager` interface. 
````Csharp
public interface IPasswordManager<TUser>
{
    bool SupportsUserPassword { get; }
    Task<PasswordManagerResult> SetPasswordAsync(TUser user, string password);
    Task<PasswordManagerResult> RemovePasswordAsync(TUser user);
    Task<bool> HasPasswordAsync(TUser user);
    Task<bool> CheckPasswordAsync(TUser user, string password);
}
````

Usage in the `UserManager` would take an `IPasswordManager` in the constructor, then have code changes similar to
````Csharp
public UserManager(IUserStore<TUser> store,
    // <truncated>
    IPasswordManager<TUser> passwordManager)
{
    // <truncated>
    PasswordManager = passwordManager;
    // <truncated>
}

public IPasswordManager PasswordManager;

protected virtual async Task<PasswordVerificationResult> VerifyPasswordAsync(PasswordManager manager, TUser user, string password)
{
    return await manager.CheckPasswordAsync(user, CancellationToken);
}

private IUserPasswordStore<TUser> GetPasswordStore()
{
    if (!PasswordManager.SupportsUserPassword)
    {
        throw new NotSupportedException(Resources.PasswordManagerDoesNotSupportPasswords);
    }
    return PasswordManager;
}
````

This would allow users to inject their own `PasswordManager` in the `Startup.cs` file:

````Csharp
services.AddDefaultIdentity<ApplicationUser>()
    .AddPasswordManager<LdapPasswordManager>() // <--- Extension method off IdentityBuilder
    .AddEntityFrameworkStores<ApplicationDbContext>();
````

**Comment by blowdart** [comment] 2019-06-12 20:22
At this point the extensibility point is UserManager and UserStore. We don't want to implement another layer of abstraction. 

Why doesn't implementing your own UserManager work for your scenario? Password stores are expecting you to store the password, not call elsewhere to validate.

**Comment by blowdart** [comment] 2019-07-17 20:12
Closing as by design.

**Closed by blowdart** 2019-07-17 20:12 UTC
Labels: area-identity

**Comment by slaneyrw** [comment] 2019-07-31 08:06
Because you enforce synchronous password hashing ( IPasswordHasher) and hide all relevant methods that invoke it
