### ISSUE TITLE
Server-Side Blazor loses connection randomly without visible errors

### ISSUE THREAD

**Issue by detachmode** [aspnet/AspNetCore#10459] opened 2019-05-22 17:36 UTC
I am currently trying out Blazor Server-Side with 3.0.100-preview5 and I love the newly introduced reconnection feature, if it loses the connection. It always recovers the state perfectly, which is great. But some things could be improved.

The app will be in an unresponding state (where a button click has no effect) for too long, without any visual feedback for the user (about 20-30 seconds). Then the greyed out overlay is displayed and the app will work again 2-3 seconds later. It would be nice, if the connection lose was showed/ detected earlier.

The app loses connection seemingly randomly, without any errors showing up at the console / logging output of the app or even the chrome dev tools. Which makes it hard to investigate the issues for why the connection loss happend.

**Comment by BarnyardTech** [comment] 2019-05-22 19:05
Yes, this is happening to me as well.  It is quite frequent and makes my app appear very unreliable to the user.  Why are connections dropping so frequently?  And why is it taking so long to detect and recover?

**Comment by mkArtakMSFT** [comment] 2019-05-24 17:02
Thanks for contacting us, @detachmode.
@anurse what information we can provide to customers to help understand what's going on with their SignalR connection?

**Comment by mkArtakMSFT** [comment] 2019-05-24 17:04
Just to add some important point here: if your app is running in development mode, and you modify your project in a way which requires recompilation, your connection will drop as the server will restart. At that point you'll need to refresh the browser. It doesn't sound this is exactly what you're facing, so just a note.

**Comment by BrennanConroy** [comment] 2019-05-24 17:34
It is possible the connection losses are happening due to an issue that caused a deadlock on the server. See https://github.com/aspnet/AspNetCore/issues/9683. This has been fixed in our nightly builds and will be available in preview 6.

**Comment by glacasa** [comment] 2019-05-30 10:02
I have the same issue, I have made a "minimal" project wich reproduces the problem : 
https://dev.azure.com/glacasa/_git/BlazorRepro?path=%2FExap.Web%2FViews&version=GBmaster

Open the page, navigate between tabs, and very fast it stops responding.

Hope this helps :)

**Comment by mkArtakMSFT** [comment] 2019-06-10 16:44
@ajaybhargavb can you please verify this repro project with `Preview6` bits and see whether it repros or not. If not, there's nothing else for us to do.

**Comment by glacasa** [comment] 2019-06-13 07:40
I have updated the repo (in branch `preview6`), and it works fine now. Thanks !

**Comment by BrennanConroy** [comment] 2019-06-13 15:20
Excellent! Thanks for trying out the previews :)

Closing as the original issue looks resolved.

**Closed by BrennanConroy** 2019-06-13 15:20 UTC
Labels: Working, area-blazor, investigate
