### ISSUE TITLE
BackgroundService CancellationToken is null on IIS 

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#12502] opened 2019-07-24 05:59 UTC
After Update my IIS machine to preview 7 the existing application breaks. Update Packages, recompile, copy new dll to production machine creates a Error in Background Service on

 protected override Task ExecuteAsync(CancellationToken stoppingToken)

It works local on iisexpress.
It worked with Preview 6!

  protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {

            //var path = Path.Combine(AppDomain.CurrentDomain.GetData("WWWBaseDirectory").ToString(),
            //    "wwwroot\\videos"); ;

             var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\videos");
            _fsw = new FileSystemWatcher(path, "*.content");
            _fsw.Created += _fsw_Created;
            _fsw.Changed += _fsw_Changed;
            _fsw.Renamed += _fsw_Renamed;
            _fsw.Error += _fsw_Error;
            _fsw.EnableRaisingEvents = true;
            _fsw.IncludeSubdirectories = true;
            return Task.CompletedTask;
        }

**Comment by davidfowl** [comment] 2019-07-24 06:01
CancellationToken  can't be null, its a struct. Do you have an exception? What exactly are you running into?

**Comment by davidfowl** [comment] 2019-07-24 06:03
Assuming this is the same issue as https://github.com/aspnet/AspNetCore/issues/12502. Closing.

**Closed by davidfowl** 2019-07-24 06:03 UTC

**Comment by hannespreishuber** [comment] 2019-07-24 06:05
12502 =12502 is correct, but why your are Closing?

**Comment by hannespreishuber** [comment] 2019-07-24 06:09
in any case- after rollinig Code back to - error case (which I tried for Hours) - it works at the Moment.

**Comment by davidfowl** [comment] 2019-07-24 06:09
Sorry, this one https://github.com/aspnet/AspNetCore/issues/12501

**Comment by davidfowl** [comment] 2019-07-24 06:11
It's the same bug. The null ref is caused by the ordering change (which you identified) described in the other bug.
