### ISSUE TITLE
JavascriptServices Hot Module Replacement (HMR) Doesn't Work With InProcess Hosting Model

### ISSUE THREAD

**Issue by DanielStout5** [aspnet/AspNetCore#7253] opened 2019-02-04 20:29 UTC
### Describe the bug

Hot Module Replacement (HMR) for my JS single page application was working fine until I added <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel> to my csproj. After that, it fails to reload when changes are made in the project.

The browser console still says `[HMR] connected` as before

NodeServices still outputs `webpack built 4e73e4e1deb48362321c in 223ms` as before

But the browser console now never says `[HMR] bundle rebuilding` so the changes are never applied.

I've tried the solutions from this issue  #4547 regarding Environment.CurrentDirectory, but even when I set it to the same value it has when it's running as OutOfProcess (`Environment.CurrentDirectory = Directory.GetParent(AppContext.BaseDirectory).Parent.Parent.Parent.FullName;`) HMR still doesn't work.

Commenting out the `AspNetCoreHostingModel` line from the csproj makes HMR work again.

Versions:
* .Net Core 2.2.103
* Visual Studio 2017 15.9.6
* aspnet-webpack 2.0.1
* webpack-hot-middleware 2.12.2
* webpack 2.7.0

I've tried updating aspnet-webpack but that caused additional issues.

**Comment by mkArtakMSFT** [comment] 2019-02-04 22:44
Thank you for filing this issue, @DanielStout5. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment] 2019-02-04 22:45
@ryanbrandenburg, can you please look into this? Thanks

**Comment by DanielStout5** [comment] 2019-02-15 17:49
I updated to the latest versions of all the related NPM packages (webpack 4, aspnet-webpack 3.0.0, webpack-hot-middleware 2.24.3, etc) and this issue is still present - as soon as I uncomment the InHosting model, webpack will still rebuild the changes, but they never get applied in the browser.

I'll see if I can setup a minimalistic example.

**Comment by paulirwin** [comment] 2019-03-20 19:20
Thank you! I was about to post an issue here but I didn't know what the problem was, but then this was suggested as a related issue. I confirmed that removing the InProcess line from the csproj fixes it! 

Here's an example project to reproduce the issue. Note that you must run "npm i" from the ClientApp folder first, I haven't set that up to be automated. https://github.com/paulirwin/WebpackHMRIssue

If you remove the InProcess line, it works great.

**Comment by paulirwin** [comment] 2019-03-20 19:25
Also, FWIW, that line in the .csproj is included by default in ASP.NET Core 2.2 templates, so it is officially broken in its default configuration.

**Comment by jkotalik** [comment] 2019-03-21 15:54
This is a known issue that we are working to resolve with the inprocess hosting model and visual studio integration. Thanks for letting us know.

cc @BillHiebert

**Comment by ryanbrandenburg** [comment] 2019-04-08 23:24
Sounds like this is a Server issue, so tossing it @jkotalik's way.

**Comment by anurse** [comment] 2019-04-09 22:26
This is the "Ctrl-F5" work that we're working on. cc @jkotalik

**Comment by jkotalik** [comment] 2019-04-16 19:00
This is fixed in VS 16.1-preview2.

**Closed by jkotalik** 2019-04-16 19:00 UTC
Labels: PRI: 1 - Required, area-servers, servers-iis

**Comment by Daniel-Khodabakhsh** [comment] 2019-08-15 06:11
I'm on VS 16.2.2 and I'm still having this issue.

**Comment by anurse** [comment] 2019-08-15 15:37
@Daniel-Khodabakhsh as this is a closed issue, I'd suggest filing VS Feedback for this, or a new issue.

**Comment by cjblomqvist** [comment] 2019-08-23 17:05
I'd lke to add that a workaround is to use the out of process hosting model only when developing. The general settings set in csproj/web.config (as specifed @ https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio ) can be overriden by:

Right-click your project -> Properties -> Debug -> Select all profiles -> (Web Server Settings [at the bottom]) -> Hosting Model -> Set it to Out Of Process
