### ISSUE TITLE
WebSocket fail to connect to Blazor server cluster

### ISSUE THREAD

**Issue by ElderJames** [aspnet/AspNetCore#17286] opened 2019-11-21 07:36 UTC
### Describe the bug
I deploy the blaor server app on docker swarm at the mode replicated 2 instance,and the browser can't connected properly,but it work well at replicated 1 mode.

### To Reproduce

``` C#
    services.AddControllersWithViews();
    services.AddRazorPages();
    services.AddServerSideBlazor();
```
log in docker:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://**.com:20120/_blazor?id=D1YvvM0Dmxx8R8UbbiNkaw  
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware[10]
      No CORS policy found for the specified request.
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/_blazor'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/_blazor'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 89.79010000000001ms 404 
```
![image](https://user-images.githubusercontent.com/7550366/69316166-32b95300-0c73-11ea-8567-395f0c96c792.png)

### Further technical details
- ASP.NET Core version 3.0.0

**Comment by davidfowl** [comment] 2019-11-21 07:43
docker swarm round robins by default and blazer server and SignalR needs sticky sessions https://docs.docker.com/ee/ucp/interlock/usage/sessions/

**Comment by javiercn** [comment] 2019-11-21 15:58
@davidfowl is correct.

I'm closing this issue as this is not a bug but an issue with the deployment configuration.

**Closed by javiercn** 2019-11-21 15:58 UTC
Labels: area-blazor

**Comment by ElderJames** [comment] 2019-11-22 01:41
Fine,but how to setup the configuration?

**Comment by davidfowl** [comment] 2019-11-22 03:55
The link in my comment should have the information
