### ISSUE TITLE
Blazor: Go To Implementation not working

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#16793] opened 2019-11-03 19:17 UTC
Using a Blazor Component in .cs file -> the "Go To Implemention" command has no effect.

Example:

![sample](https://user-images.githubusercontent.com/8482283/68090681-eac6bd80-fe76-11e9-9bab-9f8703239711.gif)

**Comment by javiercn** [comment] 2019-11-04 10:50
@Postlagerkarte thanks for contacting us.

@NTaylorMullen @rynowak @ajaybhargavb thoughts?

**Comment by javiercn** [comment] 2019-11-04 17:21
This is likely a dupe of #9731

**Closed by javiercn** 2019-11-04 17:21 UTC
Labels: area-blazor, more-info-needed
