### ISSUE TITLE
[Razor] AsyncEventHandler_OnElement_ActionEventArgs_Lambda generates the wrong code

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#8826] opened 2019-03-26 16:34 UTC
The handler below is quoted as a string instead of just being a lambda
`...,"async (e) => await Task.Delay(10)"));`
instead of
`..., async (e) => await Task.Delay(10)));`

https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/AsyncEventHandler_OnElement_ActionEventArgs_Lambda/TestComponent.codegen.cs#L18

**Comment by NTaylorMullen** [comment] 2019-03-26 16:41
lol

**Comment by mkArtakMSFT** [comment] 2019-03-29 18:27
@javiercn reassigning this back to you as Taylor has no capacity in this milestone any more. If this is not a critical issue, feel free to push it out to a further preview.

**Comment by ajaybhargavb** [comment] 2019-04-08 18:24
This is by design. The test that @javiercn linked does not wrap the lambda in an explicit expression which mean it will be parsed as HTML. I'll update the tests.

**Closed** 2019-04-08 19:49 UTC
Labels: 2 - Working, PRI: 1 - Required, area-mvc, bug, by design
