### ISSUE TITLE
[Identity] Profile page fails to maintain model on validation failure

### ISSUE THREAD

**Issue by KevinCathcart** [aspnet/AspNetCore#11749] opened 2019-07-01 15:01 UTC
### Describe the bug
Identity DefaultUI's (and also the scaffold template's) Profile page fails to part of the (output) model on  (input) Model validation failure.

Bug is present in 2.2, and still present in trunk.

### To Reproduce
1. `dotnet new mvc -au individual`
2. `dotnet run`
3. Register a new user, and sign in.
4. Disable javascript (assume for the sake of argument that the user is running no-script or the like).
5. Go to the Profile page, enter a phone number of 'zzzz' and submit.

Obviously 'zzzz' causes the model to fail validation, so we see an error message. Notice though that the username textbox is blank. (If testing against the current release, and the user had previously verified their email address, you would also see a form requesting that the address be validated again.)

This normally would not be seen, since the client side validation would prevent the form submission. However if javascript is not running, for any reason, this can happen.

### Cause
https://github.com/aspnet/AspNetCore/blob/60a8f2348e09f577b05568aba6ee6e5c9e4d4e81/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Manage/Index.cshtml.cs#L19-25

`Username` (and in the current released version a field named `IsEmailConfirmed`) is a non-bound property of the model, which means it is only available in the view if it is set explicitly. 

https://github.com/aspnet/AspNetCore/blob/60a8f2348e09f577b05568aba6ee6e5c9e4d4e81/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Manage/Index.cshtml.cs#L102-L109

Now in the post handler, if model validation fails, the page is re-rendered, but these fields are never set, so they take on default values.

### Additional Cases
Note that in trunk, Email.cshtml.cs has the same issue, although it requires both a browser too old to handle `<input type='email'>` validation, as well as javascript not running.

**Comment by blowdart** [comment] 2019-07-01 15:06
@HaoK

**Comment by HaoK** [comment] 2019-07-02 06:29
Dupe of https://github.com/aspnet/AspNetCore/issues/11519

**Closed** 2019-07-19 23:23 UTC
Labels: area-identity
