### ISSUE TITLE
[Components] "You cannot rename this element" when renaming element from referenced project

### ISSUE THREAD

**Issue by chucker** [aspnet/AspNetCore#9686] opened 2019-04-23 16:38 UTC
(This sounds similar to https://github.com/aspnet/Razor/issues/2476, but apparently wasn't fixed by that one.)

### Describe the bug
Within a Blazor component, renaming elements (such as members of an enum) fails if those elements are defined in a referenced project.

### To Reproduce
1. Using this ASP.NET Core 3.0.0-preview4-19216-03 and Visual Studio 16.1.0 Preview 1.0
2. Create a Blazor project (Project **A**) and, in the same solution, a referenced class library (**B**)
3. In Project **A**, create an enum:

```csharp
public enum MyEnumFromTheSameAssembly
{
    MyPoorlyNamedMember
}
```

In Project **B**, create another enum:

```csharp
public enum MyEnumFromADifferentAssembly
{
    MyPoorlyNamedMember
}
```

4. Create a component which references both those members in its Razor markup:

```razor
@{
    _ = MyEnumFromTheSameAssembly.MyPoorlyNamedMember;
    _ = MyEnumFromADifferentAssembly.MyPoorlyNamedMember;
}
```

5. Select each instance of `MyPoorlyNamedMember` and hit `ctrl-R`, `ctrl-R` to invoke the rename refactor

### Expected behavior
Both should behave the same.

### Actual behavior
For the first enum, a renaming UI is offered.

For the second, an error dialog is shown:

```
---------------------------
Microsoft Visual Studio
---------------------------
You cannot rename this element.
---------------------------
OK   
---------------------------
```

**Comment by danroth27** [comment] 2019-04-24 16:20
Unfortunately we don't yet support refactoring in Razor files. This is on our backlog to address, but there are a bunch of things that need to happen first. Since the current behavior is expected, I'm closing this issue as by design.

**Closed by danroth27** 2019-04-24 16:20 UTC
Labels: area-mvc, feature-Components
