### ISSUE TITLE
Blazor client side configured for prerendering returns status 500 instead of 404 for missing resources

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#11106] opened 2019-06-11 19:20 UTC
### Describe the bug
Server should return status code 404 for missing resources. It returns 500 with the following stack trace:
```
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce
Clone this repository: https://github.com/danroth27/ClientSideBlazorWithPrerendering
It contains Blazor client side application (ASP.NET Core hosted) with prerendering enabled. In `index.razor` file add something similar to this:
```html
<img src="my-wrong-image-file-name.jpg"/>
```
and run application. In the browser open developer's tools and look at network tab. You will see status 500 as status code for image request.

### Additional context
```
dotnet --version
3.0.100-preview5-011568
```

**Comment by SteveSandersonMS** [comment] 2019-06-11 19:57
This will no longer be the same with preview 6, since we no longer use the "SPA default page middleware" that is referenced in the error message. It's possible there could still be issues with preview 6, but if there are, the underlying cause would be different.

I'll close this since it definitely doesn't apply as-is to preview 6, but please open a new issue if you can reproduce any similar problem with preview 6. Hope that's OK!

**Closed by SteveSandersonMS** 2019-06-11 19:57 UTC
Labels: area-blazor

**Comment by Andrzej-W** [comment] 2019-06-14 00:11
I have just checked in Preview6 - works correctly - status 404, no exception.
