### ISSUE TITLE
The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception.

### ISSUE THREAD

**Issue by abrantie1z** [aspnet/AspNetCore#11594] opened 2019-06-26 14:41 UTC
i created a simple demo app to test signalR with xamarin forms and i get the above error. 
![Screenshot (21)](https://user-images.githubusercontent.com/19966094/60189423-6907b900-9820-11e9-9750-d5436ef695ba.png)

**Comment by BrennanConroy** [comment] 2019-06-26 15:24
We'll need a bit more info here. What version of SignalR are you using? What version of Visual Studio and Xamarin do you have? Is it possible to get more info from the exception or is that it?

**Comment by abrantie1z** [comment] 2019-06-27 11:17
Thank you sir for your quick reply.
Signal R Version:  Microsoft.Aspnetcore.Signalr.Client\3.0.0-preview6.19307.2
Visual Studio Version : 16.1.3
Xamarin. Forms : 4.0.0.482894

**Comment by halter73** [comment] 2019-06-27 22:49
Can you provide details on TypeInitializationException's InnerException? Is the default JsonHubProtocol constructor throwing?

**Comment by abrantie1z** [comment] 2019-06-28 11:56
Ok sir.
System.TypeLoadException: Could not load type of field 'System.Text.Json.JsonWriterHelper:s_hexStandardFormat' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'System.Buffers.StandardFormat' in assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Buffers.StandardFormat member:(null)

**Comment by BrennanConroy** [comment] 2019-06-28 15:33
Thank you for the exception information. This is a dupe of https://github.com/aspnet/AspNetCore/issues/8768

I verified a build of VS 16.2 had the fix so you might need to update your VS installation.

**Comment by abrantie1z** [comment] 2019-06-29 12:40
ok Sir, will look at that, if it works , will comment and close the issue. Thanks you all

**Comment by anurse** [comment] 2019-07-09 21:12
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Closed by anurse** 2019-07-09 21:12 UTC
Labels: area-signalr, waiting

**Comment by abrantie1z** [comment] 2019-07-10 11:25
I can gladly confirm to the entire World, the issue has been resolved by our wonderful developers . Kudus @anurse @BrennanConroy @halter73 . Thanks

**Comment by abrantie1z** [comment] 2019-07-10 11:26
But i think VS 16.2 is not yet released like @BrennanConroy  specified, the current update i got today was VS 16.1.6.
