### ISSUE TITLE
OutputFormatter does not respect Accept header from request when Content-Type is not present

### ISSUE THREAD

**Issue by m-wilczynski** [aspnet/AspNetCore#8469] opened 2019-03-13 12:00 UTC
### Describe the bug
We are currently incorporating `application/x-msgpack` into our internal HTTP APIs and we are having hard time implementing interoperability with `application/json`.
 
Our current perception is that because of `JsonOutputFormatter` base class `OutputFormatter` (AspNetCore/src/Mvc/Mvc.Core/src/Formatters/OutputFormatter.cs) content negotiation works differently than described in docs: https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.1.
According to docs ASP.NET Core MVC should look on **Accept** header in request and respond with requested media type if there is registered `IOutputFormatter` that supports it.
Current behaviour when **Accept** header is set to `application/x-msgpack` and no **Content-Type** header is set, `JsonOutputFormatter` (because of `OutputFormatter` base class implementation) will default to first supported media type (`SupportedMediaTypes[0]`) in`OutputFormatter.CanWriteResult`.
This will result in `JsonOutputFormatter` picking up request (provided it is present in `MvcOptions.OutputFormatters`) on **Accept=application/x-msgpack** and returning response with **Content-Type=application/json** even if there is `IOutputFormatter` that can produce such content type.

Our MessagePack output fomatter CanWriteResult implementation:
```
private const string ContentType = "application/x-msgpack";

public bool CanWriteResult(OutputFormatterCanWriteContext context) =>
    context.HttpContext.Request.Headers["Accept"] == ContentType;
```
What's more interesting, if we set **Content-Type** header of request to `application/json` and **Accept** to `application/x-msgpack`, our MessagePack output formatter will be invoked and response of `application/x-msgpack` will be returned.

### To Reproduce
1. Scaffold ASP.NET Core MVC application.
2. Add custom output formatter. Example:
```
    public class LZ4MessagePackOutputFormatter : IOutputFormatter
    {
        private const string ContentType = "application/x-msgpack";
        
        public bool CanWriteResult(OutputFormatterCanWriteContext context) =>
            context.HttpContext.Request.Headers["Accept"] == ContentType;

        public Task WriteAsync(OutputFormatterWriteContext context)
        {
            context.HttpContext.Response.ContentType = ContentType;

            //Ommited irrelevant serialization logic

            return Task.CompletedTask;
        }
    }
```
3. Register output formatter in `Startup.cs`:
```
services.AddMvc()
    .AddMvcOptions(options =>
    {
        options.OutputFormatters.Add(new LZ4MessagePackOutputFormatter());
    });
```
4. Create controller action with no arguments, ie: `public string DoStuff() => "Did stuff";` accepting POST requests.
5. Launch application and send request to http://localhost:[iisExpressPort]/api/[controller]/DoStuff from any non-browser client (ie. Postman, Insomnia or any other client that **does not set Content-Type by default**) with header **Accept: application/x-msgpack**:
```
> POST /api/[controller]/DoStuff HTTP/1.1
> Host: localhost:[iisExpressPort]
> User-Agent: insomnia/6.3.2
> Accept: application/x-msgpack
```
6. Result will be: 
```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=utf-8
< Server: Kestrel
(...)
```

### Expected behavior
Default `JsonOutputFormatter` should respect media type in **Accept** header even if **Content-Type** header is not present and MVC should pickup `IOutputFormatter` that can produce requested media type.

### Additional context
ASP.NET Core nugets:
- Microsoft.AspNetCore 2.1.7
- Microsoft.AspNetCore.Mvc 2.1.3

**Comment by mkArtakMSFT** [comment] 2019-03-25 20:49
Thanks for contacting us, @m-wilczynski.
@pranavkm, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment] 2019-05-29 22:41
Hi @m-wilczynski. Given that we've had no other reports of this issue it seems you may have some issue on your end. Have you ever managed to get this fixed?

**Comment by m-wilczynski** [comment] 2019-05-30 08:37
Well, its still reproducable when implementing `IOutputFormatter`. 
If you inherit from `OutputFormatter` it behaves as expected.

I guess you've had no reports of it because:
- you can simply inherit from `OutputFormatter` and walk away
- not so many people decide on other format than `application/json`
- from my analysis - most of the libraries that provide registration of custom `ContentType` also went with `MyFormatter : OutputFormatter` approach as we did

**Comment by jrilheu** [comment] 2019-06-13 19:19
Hi everyone, I'm having the same issue, the msgpack formatter doesn't respect the accept header
### Describe the bug
In our case we need test the capabilities about .Net Core Web API and multiple formatters, precisely `application/json`, `application/xml` and `application/x-msgpack`.  The OuputFormatters works as expected when is omitted  the  MessagePack OutputFormatter.

### To Reproduce
1. Scaffold ASP.NET Core MVC application.
2. Add Nugets `Microsoft.AspNetCore.Mvc.Formatters.Xml` and `MessagePack.AspNetCoreMvcFormatter`
3. Add custom output formatter. We test in this two ways: 

```
services.AddMvc().AddMvcOptions(option =>
   {
                //respect browser accept header
                option.RespectBrowserAcceptHeader = true;
                
                //msgpack
                option.OutputFormatters.Add(new MessagePackOutputFormatter(ContractlessStandardResolver.Instance));
                option.InputFormatters.Add(new MessagePackInputFormatter(ContractlessStandardResolver.Instance));

                //xml
                option.OutputFormatters.Add(new XmlSerializerOutputFormatter());
                option.InputFormatters.Add(new XmlSerializerInputFormatter());
            });
```
and 
```

services.AddMvc().AddMvcOptions(option =>
            {
                //accept header
                option.RespectBrowserAcceptHeader = true;
                
                //msgpack
                option.OutputFormatters.Add(new MessagePackOutputFormatter(ContractlessStandardResolver.Instance));
                option.InputFormatters.Add(new MessagePackInputFormatter(ContractlessStandardResolver.Instance));

                
            }).AddXmlSerializerFormatters();
```
4. Launch the app and do a request with Postman, in both startup configuration get the same wrong result.

```
> GET /api/v2/[controller]/ HTTP/1.1
> Host: localhost:[port]
> Accept: application/xml
> User-Agent: PostmanRuntime/7.13.0
> Cache-Control: no-cache
> accept-encoding: gzip, deflate
> Connection: keep-alive
> cache-control: no-cache
```
and the response: 

```
< Transfer-Encoding →chunked
< Content-Type →application/x-msgpack
< Server →Microsoft-IIS/10.0
```

and should be: 

```
< Transfer-Encoding →chunked
< Content-Type →application/xml
< Server →Microsoft-IIS/10.0
```
### Expected behavior
the media type specified in the Accept header should be respected and response in accordance to the format requested.

**Comment by rynowak** [comment] 2019-06-13 19:30
This is the bug in the message pack serializer library. https://github.com/neuecc/MessagePack-CSharp/blob/master/src/MessagePack.AspNetCoreMvcFormatter/MessagePackOutputFormatter.cs#L26

Each formatter on its own decides what criteria it wants to use to determine whether it will write the response. In the case of the messagepack formatter, it is only looking at the request's content type.

I would suggest that you file a bug on their repo. I think the best solution would be for them to derive from `OutputFormatter` which has a very complete implementation of this logic. https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Formatters/OutputFormatter.cs#L96

**Comment by mkArtakMSFT** [comment] 2019-06-25 21:10
Closing this as this is not a bug.

**Closed by mkArtakMSFT** 2019-06-25 21:10 UTC
Labels: area-mvc, external
