### ISSUE TITLE
Typo - Error message

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#13583] opened 2019-08-30 16:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/714586/typo-error-message.html)._

---
What steps will reproduce the problem?
1. I changed the version of .net core from 2.2 to 3.0
2. I see a green line under app. UseMvc();
3. I hover over UseMvc()

What is the expected output? What do you see instead?
When I see the error message it says: please set 'MvcOptions.EnableEndpointRounting = false' inside 'ConfigureServices'
I Expect: please set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices'.
Please provide any additional information below.
EnableEndpointRounting has typo must be : EnableEndpointRouting

---
#### Visual Studio Feedback System on 8/27/2019, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/28/2019, 00:05 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by adrianwright109** [comment] 2019-09-02 08:42
This is a duplicate of #11467.

**Comment by pranavkm** [comment] 2019-09-03 15:31
@mkArtakMSFT \ @rynowak can we consider fixing this for 3.0? As @adrianwright109 pointed out, the PR was merged in to master, it's incorrect in 3.0.

**Comment by rynowak** [comment] 2019-09-03 15:35
This pretty obviously doesn't meet the bar for 3.0

**Comment by danroth27** [comment] 2019-09-03 18:04
Given the number of users that have reported this we should just fix it.

**Closed** 2019-09-04 15:11 UTC
Labels: Done, area-mvc, bug
