### ISSUE TITLE
IApplicationLifetime events not being hit when running ASP.NET Core with IIS using the out-of-process model

### ISSUE THREAD

**Issue by madelson** [aspnet/AspNetCore#9124] opened 2019-04-05 19:37 UTC
### Context
I have an application which I am porting from ASP.NET to ASP.NET Core. The application used to leverage ASP.NET's IRegisteredObject API to perform custom shutdown logic (keeping the app alive while various bits of work complete), and with ASP.NET Core I'm transitioning this to the new IApplicationLifetime cancellation token events. I followed the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.2) to set up my app to run behind *local* IIS (not IIS Express) using the out-of-process model (we're still .NET Framework at this point in our transition so we can't use the in-process model yet).

### Describe the bug
Despite having registered handlers for both ApplicationStopping and ApplicationStopped, when running behind IIS I can't seem to get these events to trigger. Instead, whenever I rebuild my app, IIS seems to just kill the old process immediately (this also aborts outstanding requests despite my having set UseShutdownTimeout to a high value).

### To Reproduce
1. Using this version of ASP.NET Core '2.1.7'
2. Set up a default ASP.NET Core .NET framework site in VS2017. Add ApplicationStopping/Stopped handlers
3. Follow https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.2 to set things up running behind IIS
4. Make a code change, rebuild => shutdown logic doesn't happen

### Expected behavior
Shutdown logic should run. I would expect IIS to signal the current process to begin graceful shutdown and at the same time start up the new process to handle new incoming requests.

**Comment by davidfowl** [comment] 2019-04-06 06:34
I don't believe that visual studio does a graceful shutdown when killing IIS Express, AFAIK it's its just killing the process. When you say "rebuild and make a code change" I assume you're testing this during development in Visual Studio using IIS Express? Is that correct?

cc @BillHiebert

**Comment by madelson** [comment] 2019-04-06 12:57
@davidfowl no we use local IIS rather than IIS express. We have a microservices architecture where devs are frequently running a handful of services locally. Additionally, some of our front-end devs use VSCode over VS. That makes it very convenient to have local services always running instead of having to have VS open in debug mode to run the app.

**Comment by michaelxh** [comment] 2019-04-08 22:34
I have a similar problem with IIS AspNetCoreModule not triggering a graceful shutdown locally.
Seems different from this issue https://github.com/aspnet/AspNetCore/issues/7367 as the shutdown is triggered by a rebuild changing bin directory.

Ideally, behavior would also for the current process to be able to finish handling long running requests while also spinning up a new process for incoming requests not only locally, but remotely with Web Deploy as well.

Oddly enough, for me, manually **recycling** the app pool the site is configured triggers `Application.Stopping` and `Application.Stopped`, but outputs contradictory events ...

`Sent shutdown HTTP message to process '15280' and received http status '202'.` from `IIS AspNetCoreModule` with event ID `1006`
`Failed to gracefully shutdown process '15280'.` from `IIS AspNetCoreModule` with event ID `1005`

When the shutdown is triggered by a rebuild, though, there is only one event ...

`Application 'MACHINE/WEBROOT/APPHOST/PLATFORM/ASPNETCOREDEMO' with physical root 'C:\dev\platform\aspnetcoredemoapp\AspNetCoreDemo\AspNetCoreDemo.Web\' shut down process with Id '644' listening on port '1393'` from `IIS AspNetCoreModule` with eventID `1030`

**Comment by davidfowl** [comment] 2019-04-09 04:55
cc @jkotalik

**Comment by anurse** [comment] 2019-04-09 22:44
> I don't believe that visual studio does a graceful shutdown when killing IIS Express

@BillHiebert is this the case?

**Comment by BillHiebert** [comment] 2019-04-09 22:50
VS first tries the IIS Express API's to shutdown the process, but if that fails or takes too long VS will terminate it.

**Comment by anurse** [comment] 2019-04-10 02:40
Ok, so it does sound like the events should at least be firing, though if you take too long in the handler, it will be terminated. Do you know the approximate timeout value @BillHiebert ?

@madelson Would you be able to provide a sample project that reproduces the issue? That way we know exactly what your configuration is (it also helps to isolate the problem and make sure there's a runtime issue at hand)

**Comment by davidfowl** [comment] 2019-04-10 15:36
@BillHiebert So it sends a control+c to the process and waits for 2 seconds?

**Comment by BillHiebert** [comment] 2019-04-10 15:50
@davidfowl No, it calls [IIISExpressProcessUtility](https://docs.microsoft.com/en-us/iis/extensions/express-api-reference/iiisexpressprocessutility)..StopProcess(pid), and then waits for up to 2 seconds for the process to exit. I am not sure what that function does under the covers.

**Comment by davidfowl** [comment] 2019-04-10 15:52
What happens in full IIS?

**Comment by BillHiebert** [comment] 2019-04-10 16:18
I just noticed the title of this issue  is out of process. For out of process hosting, we just kill the dotnet process - this is for both IIS and IIS express. For in-process IIS hosting we use the Microsoft.Web.Administration apis, specifically the ApplicationPool.Stop() method. And similar to IIS Express, if the app pool doesn't stop within 2 seconds we terminate it.

**Comment by anurse** [comment] 2019-04-10 16:46
Ok, since this is about out-of-process hosting, VS is terminating the process and the `IApplicationLifetime` events don't fire because the process is being terminated abruptly. There's no ASP.NET Core issue here then since we can't run the lifecycle events when being terminated like this.

**Comment by madelson** [comment] 2019-04-10 23:43
@anurse is there a reason the IIS module managing the Kestrel process doesn't send CTRL+C to do graceful shutdown? The "out-of-process" hosting option is billed in the docs as being a first-class solution so I'm surprised to see this shortcoming just dismissed.

**Comment by anurse** [comment] 2019-04-11 01:20
Is this occurring when you restart in production? My comment was about the VS behavior since you referenced rebuilding and the development-time article.

**Comment by davidfowl** [comment] 2019-04-11 02:02
@BillHiebert we need to send Ctrl+C to dotnet.exe

**Comment by anurse** [comment] 2019-04-11 03:30
I'll leave this open for now to track/discuss improving the VS scenario here. I mostly just want to ensure there isn't a runtime issue to resolve.

**Comment by madelson** [comment] 2019-04-12 10:25
Thanks @anurse . Is there a different place to file issues against the IIS integration?

**Comment by davidfowl** [comment] 2019-04-12 14:36
It’s a visual studio problem.

**Comment by anurse** [comment] 2019-04-12 15:20
@madelson The best place to file Visual Studio issues is through the built-in feedback tool. If you do that and put a link in here, we can get it to the right folks.

![VS Feedback icon in the top-right of the Visual Studio window](https://user-images.githubusercontent.com/7574/56048166-c1d4b480-5cfb-11e9-9215-65519d2c3906.png)

**Comment by madelson** [comment] 2019-04-17 13:34
@anurse is VS the one that owns the IIS module that makes this all work? My experience is that this problem exists both when starting the app via VS and when deploying the app using msdeploy.

**Comment by anurse** [comment] 2019-04-17 14:51
We work very closely together but when it comes to launching and managing the IIS process as well as deploying the app, that is a VS concern. It just helps to track these issues in the relevant place :). Feel free to link any issue you create here and we'll work closely with the appropriate teams.

**Comment by anurse** [comment] 2019-07-09 23:09
Closing as this is external (in the VS integration) rather than in the IIS module itself.

**Closed by anurse** 2019-07-09 23:09 UTC
Labels: area-servers, servers-iis, triaged

**Comment by rclabo** [comment] 2019-09-20 14:41
This issue makes it difficult to debug and test my ApplicationStopping code in Visual Studio.  Is there a corresponding Visual Studio issue that can be linked to from here?

**Comment by anurse** [comment] 2019-09-20 15:26
I'm not aware of one, but if you file one in the VS Feedback tool you'll get an issue in the developer community site and you can link that here.

**Comment by rclabo** [comment] 2019-09-20 15:43
OK, sounds good.  I just filed one and once I get the email with the link I will post it here.

**Comment by rclabo** [comment] 2019-09-20 15:44
I have reported this issue to the Visual Studio team here:  https://developercommunity.visualstudio.com/content/problem/741787/aspnet-core-applicationstopping-event-not-firing-w.html

Upvotes appreciated.
