### ISSUE TITLE
Razor Components: Differ for deltas (renderer)  ignores IDs

### ISSUE THREAD

**Issue by springy76** [aspnet/AspNetCore#8954] opened 2019-03-31 20:09 UTC
Using 3.0 preview3 of Razor Components (server-side)

Sample: https://github.com/springy76/RazorComponentsProblems/blob/problem/DifferIgnoresIDs/WebApp/Components/Pages/Index.razor

Because the differ does ignore IDs when removing the first node of a list, instead of really removing the first node then all nodes get its ID (and all attributes and children) reassigned and finally the last one is removed.
The side effect of this (wrong) behavior is that not only far too much deltas are transported, but also all sorts of CSS animations and transitions may be run.

**Comment by danroth27** [comment] 2019-04-02 16:34
@SteveSandersonMS Will support for `key` address this?

**Comment by mkArtakMSFT** [comment] 2019-04-03 16:19
This is dupe of #8232

**Closed by mkArtakMSFT** 2019-04-03 16:19 UTC
Labels: area-mvc, feature-Components
