### ISSUE TITLE
Renaming Model Property, doesn't get updated in cshtml

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#16642] opened 2019-10-29 17:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/583449/renaming-model-property-doesnt-get-updated-in-csht.html)._

---
After renaming a property in my model class, it won't rename it in the view

---
#### Visual Studio Feedback System on 5/27/2019, 01:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/12/2019, 00:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2019-10-30 09:33
Tried this with 16.4 preview2 and doesn't repro.

I'm closing this as I can't reproduce the behavior and we need more info for further troubleshooting if necessary.

At least the Visual Studio version in use, and the technologies/frameworks in use. I've tried with Razor pages and 16.4 preview2.

**Closed by javiercn** 2019-10-30 09:33 UTC
Labels: area-mvc
