### ISSUE TITLE
Custom Host header gets malformed when using TestServer

### ISSUE THREAD

**Issue by hiteshmadan** [aspnet/AspNetCore#9217] opened 2019-04-09 19:46 UTC
### Describe the bug
When using the TestServer and sending a request with a custom Host header, the header value gets malformed.

### To Reproduce
- Using ASP.NET Core 2.1
- Send an HttpRequestMessage to a TestServer's CreateClient() client with request.Host set to 'someuri.com'
- Notice that the Host header that's received in the web app is "localhost,someuri.com"

### Expected behavior
The value of host header in the web app should be someuri.com

The bug is in src\Hosting\TestHost\src\ClientHandler.cs, over here:
````
// request.Uri has localhost, so the req.Host first gets set to "localhost"
req.Host = HostString.FromUriComponent(request.RequestUri);
...
foreach (var header in request.Headers)
{
    // Append calls ParsingHelpers.AppendHeaderUnmodified, which concatenates the old header value and the new value being appended here.
    req.Headers.Append(header.Key, header.Value.ToArray());
}

**Comment by Tratcher** [comment] 2019-04-09 21:14
Duplicate of https://github.com/aspnet/AspNetCore/issues/7852, already fixed in all 3.0.0 previews.

**Closed by Tratcher** 2019-04-09 21:14 UTC
Labels: area-hosting
