### ISSUE TITLE
Provide some guidance for managing WebSocket lifetime

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2462] opened 2018-01-01 21:46 UTC
_From @anurse on Friday, October 27, 2017 2:44:52 PM_

We've had a few reports from customers who are taking the `WebSocket` object, handing it off to a background thread and then allowing the request thread to complete. This causes the underlying connection to be closed and breaks the WebSocket. We should consider providing some guidance (a sample, blog post, docs, even changes to behavior if we feel that's valid) to help customers understand how the lifetime of the WebSocket needs to be managed.

_Copied from original issue: aspnet/WebSockets#208_

**Comment by aspnet-hello** [comment] 2018-01-01 21:46
_From @Tratcher on Friday, October 27, 2017 2:49:01 PM_

@BrennanConroy does SignalR do this too? What's the pattern used there?

**Comment by aspnet-hello** [comment] 2018-01-01 21:46
_From @anurse on Friday, October 27, 2017 3:42:43 PM_

I think the right pattern to document for today is something like this:

```csharp
app.Use(async (context, next) => {
    var socket = await context.WebSockets.AcceptWebSocketAsync();
    var tcs = new TaskCompletionSource<object>();
    BackgroundProcessor.Enqueue(socket, tcs);
    await tcs.Task;
});
```

**Comment by aspnet-hello** [comment] 2018-01-01 21:46
_From @anurse on Friday, October 27, 2017 3:44:01 PM_

It's also worth considering if there's any value in moving the socket to a background processor at all. You have to block the request thread anyway. Maybe people are coming from an ASP.NET 4.x model where Request Threads are somehow "special", whereas IIRC ours are just ThreadPool threads.

**Comment by aspnet-hello** [comment] 2018-01-01 21:46
_From @Tratcher on Friday, October 27, 2017 3:48:37 PM_

My understanding is that they are usually handing the socket off to a central management system. E.g. Something that wants to broadcast to all connected sockets.

Does a wrapper help any? It's one less object to track.
```
app.Use(async (context, next) => {
    var socket = await context.WebSockets.AcceptWebSocketAsync();
    var lifetime = new WebSocketLifetime(socket);
    BackgroundProcessor.Enqueue(lifetime);
    await lifetime.Task;
});
```

**Comment by aspnet-hello** [comment] 2018-01-01 21:46
_From @anurse on Friday, October 27, 2017 4:00:12 PM_

I don't know if I would want us to create such a thing. I'd imagine there may be other context data a user would want to capture (HttpContext, etc.).

**Comment by mbedded** [comment] 2018-02-06 09:04
Hello together,
is there a solution or workaround available? I guess i am running into the same problem as mentioned by @Tratcher above. I accept a socket and the complex handling is done in a separate class which contains a loop to receive new messages and handle them. It enables a better separation of logic.

I get the same issue as refered in aspnet/Home#2460. I created some breakpoints into my `socket.CloseAsync(..)` calls but noone of them is hit.
Furthermore i traced my Middleware like mentioned in aspnet/Home#2742. I don't exit my Middleware and the code stays within the loop of my WebSockerHandler. Unfortunately i run into the same exceptions.

**Comment by mika76** [comment] 2018-02-06 10:28
I used the post at https://radu-matei.com/blog/aspnet-core-websockets-middleware/ for creating a notification websocket but am hitting the issue in #2742. Some guidance on properly connecting and handling websockets would be very appreciated. 🙏

**Comment by anurse** [comment] 2018-02-06 16:35
Can either of you provide a sample repro of the issue you are seeing? Also, seeing the stack trace would be very helpful.

**Comment by tpeczek** [comment] 2018-02-07 01:39
@mika76 Sorry for coming out of nowhere, but I'm currently working on post on this subject in context of my demo project (https://github.com/tpeczek/Demo.AspNetCore.WebSockets) and I have stumbled uppon this issue while gathering materials. I believe the core of the problem is that socket is not removed from the manager when connection is being closed prematurely.

The connection being closed prematurely typically results in exception being thrown from receiving loop and killing the middleware thread, but if the reference to the socket is kept somewhere else it still going to be valid (and the state will still be open) so attempting to send from different place in application will result in more exceptions.

In my opinion (@anurse can correct me if I'm wrong) the correct approach could be to swallow/log the exception from receiving loop and make sure the socket is removed from manager. In case of the article you have mentioned it should be enough to wrap the call to `Receive` inside  `WebSocketManagerMiddleware.Invoke` method like this:

```
try
{
    await Receive(socket, async(result, buffer) =>
    {
        ...
    });
catch (WebSocketException wsex) when (wsex.WebSocketErrorCode == WebSocketError.ConnectionClosedPrematurely)
{
    await _webSocketHandler.OnDisconnected(socket);
}
```

This can also be the root cause behind #2460

**Comment by mbedded** [comment] 2018-02-07 05:24
As mika76 mentioned above: I used the same URL as a base for my application. As core i use following code/classes. I pass the socket to a class which handles the socket-interactions. I planned to make a new class like `new MyWebSocketHandler(socket)` and call something like `myHandler.Run()` but i guess (as mentioned by anurse above) that this won't work, will it?

```
//WebSocketMiddleware.cs
public async Task Invoke(HttpContext context) {
  if (!context.WebSockets.IsWebSocketRequest) {
	context.Response.StatusCode = (int) HttpStatusCode.BadRequest;
	return;
  }

  WebSocket socket = await context.WebSockets.AcceptWebSocketAsync();
 
  await ReceiveLoopAsync(socket, async (result, buffer) => {
	if (result.MessageType == WebSocketMessageType.Text) {
	  await _webSocketHandler.ReceiveAsync(socket, result, clientID, sessionID, buffer);
	} else if (result.MessageType == WebSocketMessageType.Close) {
	  await _webSocketHandler.OnDisconnectedAsync(socket);
	}
  });
}

private async Task ReceiveLoopAsync(WebSocket socket, Action<WebSocketReceiveResult, byte[]> handleMessage) {
  byte[] buffer = new byte[WebSocketHandler.BUFFER_SIZE];

  while (socket.State == WebSocketState.Open) {
	WebSocketReceiveResult result = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
	handleMessage(result, buffer);
  }
}
```

```
// WebSocketHandler.cs

public override async Task ReceiveAsync(WebSocket socket, WebSocketReceiveResult result, string clientId, string sessionId, byte[] buffer) {
  if (_sessionPool.ContainsSession(sessionId) == false) {
	return;
  }

  IList<string> clients = _myPool.GetClientsOfSession(sessionId);

  foreach (string client in clients) {
	if (client == clientId || _connectionManager.Contains(client) == false) {
	  continue;
	}

	WebSocket targetSock = _connectionManager.GetSocketById(client);
	await SendBufferAsync(targetSock, result, buffer);
  }
}

public async Task SendBufferAsync(WebSocket socket, WebSocketReceiveResult result, byte[] buffer) {
  if (socket.State != WebSocketState.Open) {
	return;
  }

  try {
	await socket.SendAsync(new ArraySegment<byte>(buffer, 0, result.Count), WebSocketMessageType.Text, true, CancellationToken.None);
  } catch (Exception ex) {
	Console.WriteLine(ex);
	throw;
  } 
}
```

Here a small excerpt of my debug-output:

```
MyApplication> I: Executing HttpStatusCodeResult, setting HTTP status code 200 [Microsoft.AspNetCore.Mvc.StatusCodeResult(1)]
MyApplication> I: Executed action MyApplication.Controllers.FilesController.DeleteFile (MyApplication) in 106.2955ms [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker(2)]
MyApplication> I: Request finished in 125.542ms 200  [Microsoft.AspNetCore.Hosting.Internal.WebHost(2)]
MyApplication> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.ObjectDisposedException: Cannot access a disposed object.
MyApplication> Object name: 'FrameResponseStream'.
MyApplication>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.ValidateState(CancellationToken cancellationToken)
MyApplication>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
MyApplication>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameDuplexStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
MyApplication>    at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer)
MyApplication>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyApplication>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MyApplication>    at MyApplication.WSocket.WebSocketHandler.<SendBufferAsync>d__10.MoveNext() in C:\..\WebSocketHandler.cs:line 80
MyApplication> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.ObjectDisposedException: Cannot access a disposed object.
MyApplication> Object name: 'FrameResponseStream'.
MyApplication>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.ValidateState(CancellationToken cancellationToken)
MyApplication>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
```

Line 80 of my `WebSocketHandler.cs` is the following one
`  await socket.SendAsync(new ArraySegment<byte>(buffer, 0, result.Count), WebSocketMessageType.Text, true, CancellationToken.None);`

**Comment by mika76** [comment] 2018-02-07 08:00
@tpeczek you're absolutely right, even when catching the error, the manager had the reference to the faulted socket and kept trying to send data through it. 

The interesting thing is that the socket keeps it's open status (the handler was checking the socket status before sending but it was always open) - I would suggest the framework should probably close it if it ever has to throw this Exception since there is no way to recover from this state.

Thanks for the help 👍

**Comment by anurse** [comment] 2018-02-07 17:31
> I would suggest the framework should probably close it if it ever has to throw this Exception since there is no way to recover from this state.

Depending on the circumstances, that might be something they'd consider. You could file it on dotnet/corefx if you wanted to open that discussion.

> @anurse can correct me if I'm wrong

Nope, that sounds pretty good. It's definitely correct that when that error occurs, the socket is broken and can never be recovered. Might as well remove it then :).

**Comment by mbedded** [comment] 2018-02-08 09:07
Hello together,
i found a solution now, too. In my case the "DEBUG" Build from VisualStudio (somehow) broke my application.

As i compiled i got a folder like "Client" with `Client.exe` and the needed DLLs. As i started Client.exe twice (from same location) it may cause some issues so the Server got a "ObjectDisposedException".
As test i copied the exe and dlls into a separate folder (lets call them ClientA and ClientB). As i started `ClientA.exe` it was working, as i started `ClientB.exe` it was working, too (remember: separate folder, exe and dlls).
I compiled my application as Release. As i started `Client.exe` (as above from my output folder) twice, it was working without any issues, too. So in my case: Debug-Build caused some issues with my client-application which was raising this errors in my Kestrel-Server.
So for now: i have to improve my error-manamgement in my applications (client + server).

As @mika76 said above:
It would be really awesome when the socket-state is changed to "Aborted" if Kestrel has some errors with my WebSocket (or the underlying stream got disposed). From my point of view it is wrong that the Socket stays `open` when i am not able to recover the socket or re-open the connection to the client.

Thanks all for your help 😄 Much appreciated

**Comment by anurse** [comment] 2018-02-08 16:43
> From my point of view it is wrong that the Socket stays open when i am not able to recover the socket or re-open the connection to the client.

Agreed. That's what #2466 is tracking.

**Comment by anurse** [comment] 2019-04-17 17:59
Closing as we have other issues tracking the work that came out of this discussion.

**Closed by anurse** 2019-04-17 17:59 UTC
Labels: area-websockets
