### ISSUE TITLE
start debugging (F5) - I cant see changed value on it is working 

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#16927] opened 2019-11-08 16:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/790591/start-debugging-f5-i-cant-see-changed-value-on-it.html)._

---
[regression] [worked-in:Communitiy 2019 Version v.16.3.6]
Hi
Communitiy 2019 Version v.16.3.6
When I try to start debugging (F5) mode for test my project, I cant see changed value that on .cshtml page

---
#### Visual Studio Feedback System on 10/23/2019, 08:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/24/2019, 00:11 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2019-11-08 16:27
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by ryanbrandenburg** [comment] 2019-11-08 18:28
So the workflow here is:
1. F5 debug
2. Launch the page, see the content.
3. Edit the cshtml for this page.
4. Refresh the page.
5. The content has not changed.

If that's the scenario then this is working as intended. Check out [this announcement](https://github.com/aspnet/AspNetCore/issues/7647) for more details on why run-time compilation is no longer our default and how you can enable it.

If that's not the scenario you're reporting then it would be helpful to go into more detail about it.

**Comment by mkArtakMSFT** [comment] 2019-11-11 17:26
Closing this per @ryanbrandenburg 's response above. The announcement he referred to explains it all.

**Closed by mkArtakMSFT** 2019-11-11 17:26 UTC
Labels: area-mvc, investigate, more-info-needed
