### ISSUE TITLE
ASP.NET Core Identity Cosmos DB SQL API Support

### ISSUE THREAD

**Issue by wpan008** [aspnet/AspNetCore#14640] opened 2019-10-01 21:07 UTC
Is there any plan to support ASP.NET Core Identity with Cosmos DB?

**Comment by blowdart** [comment] 2019-10-01 21:12
Not directly, the EF Core backing identity can use Cosmos DB, so there's no need for us to get specific.

There are 3rd party implementations for the specific documentdb api

https://github.com/codekoenig/AspNetCore.Identity.DocumentDb
https://github.com/FelschR/AspNetCore.Identity.DocumentDB

**Comment by blowdart** [comment] 2019-10-09 19:02
We're closing this issue as the behaviour discussed seems to be by design.

**Closed by blowdart** 2019-10-09 19:02 UTC
Labels: area-identity
