### ISSUE TITLE
Error on implementing custom FileProvider - Cannot find compilation library location for package 'projectCLB'

### ISSUE THREAD

**Issue by livarcocc** [aspnet/AspNetCore#7904] opened 2019-02-24 18:29 UTC
_From @YankdaCode on February 23, 2019 1:35_

So, I am designing a very customized solution from scratch wherein I have asp.net mvc core app as the main web app. Then I create separate class libraries and update the SDK to Microsoft.NET.Sdk.Razor and use:

```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
```

This allows me to create MVC type class library, lets say "projectCLB" and then at startup I scan the folder that is located outside of the project main directory and load the assemblies for my project:
projectCLB.dll
projectCLB.Views.dll

This was working fine by the following code:

```c#
Assembly assembly;
                try
                {
                    assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(file.FullName);
                }
                catch (FileLoadException ex)
                {
                    // If assembly is already loaded, we'll just catch it and continue to the next one, plugins can have same dependencies:
                    if (ex.Message == "Assembly with same name is already loaded")
                    {
                        continue;
                    }
                    throw;
                }

// Check if the assembly has already been loaded:
                if (!(mvcBuilder.PartManager.ApplicationParts.Any(x => x.Name == assembly.GetName().Name)))
                {
                    //Load the pre-compiled Views:
                    if (assembly.ManifestModule.Name.Contains(".Views.dll"))
                    {
                        mvcBuilder.ConfigureApplicationPartManager(mgr =>
                        {
                            foreach (var b in CompiledRazorAssemblyApplicationPartFactory.GetDefaultApplicationParts(assembly))
                            {
                                mvcBuilder.ConfigureApplicationPartManager(apm => apm.ApplicationParts.Add(b));
                            }

                        });

                    }
                    // Load the plug in assemblies:
                    else
                    {
                        
                        mvcBuilder.AddApplicationPart(assembly);
                     
                       

                    }

                }
```

This is how my class library project file looks:

```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">


  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>


  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    
  </PropertyGroup>


  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\" />
    <Folder Include="Infrastructure\Data\" />
  </ItemGroup>

  <ItemGroup>

    <ProjectReference Include="..\..\<baseapp project>.Common\baseapp project.Common.csproj" />

    <ProjectReference Include="..\..\baseapp project.Data\baseapp project.Data.csproj" />
    <ProjectReference Include="..\..\baseapp project.Repositories\baseapp project.Repositories.csproj" />
  </ItemGroup>
  <Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
    <ItemGroup>
      <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\plugin\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />

    </ItemGroup>
  </Target>
 

</Project>
```

It was working all fine until I implemented a File Provider so that we can use cshtml files at development time instead of precompiled views since I was having to copy the dlls/ rebuild after a cshtml change. 
Reason being that PhysicalFileProvider doesn't look outside of the webroot. Now I get this error and there are other posts that I saw but none of the workarounds actually work for me.

```
System.InvalidOperationException: Cannot find compilation library location for package 'projectCLB'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

_Copied from original issue: dotnet/sdk#2981_

**Comment by YankdaCode** [comment] 2019-02-25 05:47
I just wanted to add to the description that I created this solution so that we can deploy independent modules without even touching the base app at all and thus removing regression time.

I was able to get around the issue. Basically I implemented this from @pranavkm suggestion:
https://github.com/dotnet/core-setup/issues/2981#issuecomment-322572374

But after doing that it was failing on  
`foreach (var path in library.ResolveReferencePaths())` 
for the projectclb.
So I had to manually provide a path for the assembly which is fine by me.

Also, after fixing this I removed the custom physical file provider that I had implemented so that the Views outside of the root can be loaded.
Instead I used new PhysicalFileProvider(externalfolderPath). And it worked. 

So was my assumption wrong that PhysicalFileProvider doesn't work outside of the main project root? I thought I read that somewhere. Any guidance is appreciated. I haven't hosted the app on IIS and tested yet, works on my local though.

**Comment by pranavkm** [comment] 2019-02-26 23:17
> So was my assumption wrong that PhysicalFileProvider doesn't work outside of the main project root?

It limits itself to files that it's rooted to. The one that AspNetCore sets up is rooted to the content root (the application root directory). 

It looks like you found a solution for your issue. Closing this one. Feel free to open a new issue if have further questions.

**Closed by pranavkm** 2019-02-26 23:17 UTC
Labels: area-mvc
