### ISSUE TITLE
[Perf] Connection creation

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#10956] opened 2019-06-06 16:48 UTC
![image](https://user-images.githubusercontent.com/1165805/59050822-2e71b880-8840-11e9-9178-819df5ab77c3.png)

Detected a regression in connection creation over http. Https didn't change. More pronounced on Windows.

**Comment by sebastienros** [comment] 2019-06-11 21:51
It's from ASP.NET, isolated to these commits, there were no build between these. 
https://github.com/aspnet/AspNetCore/compare/0b54783877cca229e2fc3f772ce7257cf0b3814f...bb9ba122c169c3fe4d8edc3446c2434cafe194aa

It's probably from the BedRock refactor (@davidfowl)

Updated chart with 20% decrease

![image](https://user-images.githubusercontent.com/1165805/59309415-56a25280-8c58-11e9-8963-e62056887677.png)

**Comment by anurse** [comment] 2019-06-11 22:26
> It's probably from the BedRock refactor (@davidfowl)

@davidfowl are you able to take a look? We need to determine what to do for 3.0 here or if we need to just eat it and fix it in 3.1.

@sebastienros can you get libuv numbers as well?

**Comment by sebastienros** [comment] 2019-06-11 22:39
Libuv is 10K connections per sec (on Windows)

**Comment by anurse** [comment] 2019-06-11 22:42
But any regression? Or do we not have history to check for that?

**Comment by sebastienros** [comment] 2019-06-11 22:44
We don't track because sockets is faster everywhere now

**Comment by davidfowl** [comment] 2019-06-12 01:20
I would maybe expect this to be a little slower but not by much, 20% is big.

**Comment by davidfowl** [comment] 2019-06-12 04:19
Did this regress sockets and Libuv?

**Comment by sebastienros** [comment] 2019-06-12 18:20
It didn't regression with Libuv on Windows.

**Comment by anurse** [comment] 2019-07-09 22:51
@davidfowl This is assigned to you, do we know what's going on here?

**Comment by davidfowl** [comment] 2019-07-10 02:27
I took a look at while ago and didn’t figure it out, I’ll spend a few more cycles this release looking.

**Comment by davidfowl** [comment] 2019-07-15 06:11
@sebastienros it didn't regress libuv because we stopped measuring libuv https://github.com/aspnet/Benchmarks/commit/905799f87dfdf7906310df6c2a6530c08c90da71 😄 . Which makes sense because I'd hope this regressed both scenarios equally. Still digging...

**Comment by davidfowl** [comment] 2019-07-15 07:17
I'm not sure how this is related to the changes but in the profile it seems like the most expensive thing happening per request/connection was the exception thrown by the connection close and the new profile shows very expensive sys calls (maybe they are happening more?):

Here's what threads look like previously:

![image](https://user-images.githubusercontent.com/95136/61200080-1b4ed580-a695-11e9-9787-c5452a50e3c9.png)

After the dip:

![image](https://user-images.githubusercontent.com/95136/61200100-31f52c80-a695-11e9-903c-16b212398a11.png)

It's ~2x  more expensive for some reason. Here's the old profile (for a single thread)

![image](https://user-images.githubusercontent.com/95136/61200204-839db700-a695-11e9-8531-2526f803cc66.png)

Here's a new profile:

![image](https://user-images.githubusercontent.com/95136/61200235-9b753b00-a695-11e9-8610-6965658d12ce.png)

**Comment by sebastienros** [comment] 2019-07-15 07:38
Or maybe it didn't regress Libuv because I measured it manually to be sure. You'd bet I know that ;)

**Comment by halter73** [comment] 2019-07-16 00:51
Do you think this is related to hopping threads between accepting the connection and the first read?

**Comment by davidfowl** [comment] 2019-07-16 08:15
I was thinking similar things but the opposite, when I originally investigated this bug, I wanted to try this change https://github.com/aspnet/AspNetCore/compare/davidfowl/dispatch-connection-execution. 

Looking more deeply my guess it that more code is executing on IO threads stopping other connections from being accepted. It's happening because the we start reading from the connection before returning from AcceptAsync which means data is ready by the time the HttpConnectionMiddleware runs. As a result, the read happens and it remains on the thread doing the accept loop until something goes asynchronous.

**Closed** 2019-07-18 13:36 UTC
Labels: area-servers, area: Performance
