### ISSUE TITLE
New Project don't start

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/AspNetCore#11057] opened 2019-06-10 19:24 UTC
### Describe the bug
Created new project give a Error

### To Reproduce
Using Visual Studio Version 16.0.0 Preview 5 and SDK 3.0.100 - preview 5 (i hope, i have multiple SDKs installed, but only the preview 5 of Core)
* I create a new project
* Choose Asp Core Web Application
* Project and Soulution name WebApplication4
* Choose Blazor Asp Core hosted
Run the solution

I get this errors
rzc generate exited with code -2147450730.	...\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets

**Comment by UrielMhezzek** [comment] 2019-06-10 19:59
I installed Preview 5 to Preview 3. After it, all my projects don't work and give the same error. 
I deinstalled all SDK and installed only Preview 3 to work on my old projects. but my old project give still the same error.

**Comment by astecenko** [comment] 2019-06-10 22:00
Have you completed all the steps listed in https://docs.microsoft.com/ru-ru/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio ?

**Comment by UrielMhezzek** [comment] 2019-06-10 22:16
No and yes. Minutes bevor i installed the preview 5 I worked at my preview 3 project. I only reinstall to preview 5.

**Comment by Css-IanM** [comment] 2019-06-14 13:47
#11222 could possibly be a duplicate of this. Though `rzc` is throwing a different error code and also a different sdk version but has the same outcome.

**Comment by mkArtakMSFT** [comment] 2019-06-19 22:53
Thanks for contacting us, @UrielMhezzek.
Can you please confirm that you have the latest VS Preview release installed?
Alternatively, you can try to run the app from the command line. If that works, then it's for certain VS version mismatch.

FYI: The latest required version of VS for the Preview 6 SDK is VS 16.2.

**Comment by mkArtakMSFT** [comment] 2019-06-25 16:51
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by mkArtakMSFT** 2019-06-25 16:51 UTC
Labels: area-blazor, question
