### ISSUE TITLE
"Writing is not allowed after writer was completed", with SignalR 1.1

### ISSUE THREAD

**Issue by viktorgullmark** [aspnet/AspNetCore#6701] opened 2019-01-15 12:02 UTC
### Describe the bug
I'm receiving "Writing is not allowed after writer was completed" on the latest release of SignalR with .NET Core 2.2. We previously used 1.0.0-rc1-final without any issues, and all of a sudden started receiving this issue with 1.1 on the client. We also receive a lot of "Task was cancelled" from the RedisHubLifetimeManager. Attaching screenshots below.

We ran SignalR 1.1 on the backend with 1.0.0-rc1-final on the client without any issues, but when we upgraded our client to 1.1, we started receiving this in our logs.

Another change we did while upgrading was to add "skipNegotiate: true" on the client, as well as forcing websockets. Not sure if this is related. I can't reproduce the error locally, since it doesn't happen often and seems related to only a few of our clients.

Also, the server seems to go down quite often after the upgrade. Can't seem to find any reason for this, but it was stable before we upped our clients.

### To Reproduce
Can't reproduce the error locally, we just see it in our production environment logs. 

### Expected behavior
Expected it to be gone with 1.1.0, since I saw previous reports of the problem on RC versions.

### Screenshots

Screenshot of writing is not allowed message:
![image](https://user-images.githubusercontent.com/11405940/51179025-ae64a980-18c4-11e9-9929-04b3388d9797.png)

Screenshot of task cancelled exception:
![image](https://user-images.githubusercontent.com/11405940/51179623-63e42c80-18c6-11e9-9c55-d5c0b62d2f22.png)

### Additional context
`dotnet --info` output:
![image](https://user-images.githubusercontent.com/11405940/51179466-d6a0d800-18c5-11e9-8083-f0df9bb811ce.png) 
This is on our production environment. Locally we have the 2.2 runtime.

EDIT: If this issue is misplaced or inproper, feel free to close it. I didn't know where to turn.

**Comment by viktorgullmark** [comment] 2019-01-17 15:12
Thanks for the input. We've resolved the Task canceled exception now thanks to your clarification.

We're seeing the "Writing is not allowed after writer was completed" a few times every hour, with around 100 users online. Can't find a disconnect at this timestamp in the logs though 🤔

**Comment by BrennanConroy** [comment] 2019-01-28 23:54
Could you capture logs around the exception, at Debug level preferably.

**Comment by bradygaster** [comment] 2019-02-06 19:15
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by imperugo** [comment] 2019-02-06 20:44
Hi, 
I'm getting the same error with this scenario:

.NET Core 2.2, SignalR 1.1, scaling using Redis (2.x) and hosting into Docker.

Unfortunately, I'm unable to reproduce the problem and the log isn't so helpful (Writing is not allowed after writer was completed)
Is there anything I can do to provide more information? (add more logging somewhere, try another build or whatever?).

I'm also using Groups so, probably is the same problem of @viktorgullmark but I don't have the issue related to the Task Canceled exception.

Let me know.

**Comment by codingsteff** [comment] 2019-02-07 12:25
We have the same errors, only in production inside Docker behind Nginx.
The messages appeared after upgrade to .NET Core 2.2.

It doesn't matter if we use SignalR 1.1 or 1.0 on the Client Side.

By the way, we don't use Groups or Redis.

**Comment by BrennanConroy** [comment] 2019-02-07 17:08
@imperugo Enabling Debug level logs would be nice. I'd like to see the logs around the failure if possible, as they can give context on what is happening on the server.

@codingsteff Can you confirm that switching from SignalR 1.0.0 to 1.1.0 on the server causes the issue? And could you also collect logs please?

**Comment by imperugo** [comment] 2019-02-08 07:49
@BrennanConroy I'll switch the log only for "Microsoft.AspNetCore.SignalR.*" to debug.

Soon news

**Comment by codingsteff** [comment] 2019-02-08 08:46
I rolled back our server to .NET Core 2.1 and now we have no errors in the log anymore.
Currently all our clients using JavaScript SignalR 1.1.0, the server runs with .Net Core 2.1.1 and Microsoft.AspNetCore.SignalR 1.0.3.

Next week I can switch the production to Microsoft.AspNetCore.SignalR 1.1.0, but because of the dependency to Microsoft.AspNetCore.Connections.Abstractions I need to switch to .NET Core 2.2 as well.

I'll send you some log entries.

**Comment by imperugo** [comment] 2019-02-08 13:05
@BrennanConroy here my logs

<img width="1189" alt="screenshot 2019-02-08 at 14 05 09" src="https://user-images.githubusercontent.com/758620/52479947-97a33100-2baa-11e9-93a2-18a9fafdb370.png">

**Comment by codingsteff** [comment] 2019-02-13 08:15
@BrennanConroy  here are the logs from the same ConnectionId
![image](https://user-images.githubusercontent.com/4362821/52696620-b79e7000-2f6f-11e9-9358-fbf41d61e6e6.png)

**Comment by fabiano** [comment] 2019-02-13 12:47
We have the same errors here in two applications.

One is running on .NET Core 2.2.1 (deployed as self-contained). The other is running on .NET 4.7.1.

They are built using the SDK 2.2.103 and runtime 2.2.1.

The Microsoft.AspNetCore.SignalR package version is 1.1.0.
The @aspnet/signalr package version is 1.0.4.

We enabled the SignalR log on our servers, then soon I'll be able to share more data about the connections and errors.

Microsoft.AspNetCore.SignalR.HubConnectionContext -> Failed writing message. Aborting connection.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.<TryWritePingSlowAsync>d__49.MoveNext()

**Comment by BrennanConroy** [comment] 2019-02-13 21:54
This is a benign error as it looks like the client is already disconnected.

We'll look at making this either not try to write after the client is gone, or at a minimum not be an error log.

**Comment by viktorgullmark** [comment] 2019-02-13 22:37
@BrennanConroy Alright, thanks for looking into it!

**Comment by pashchuk** [comment] 2019-03-26 09:52
Is there any progress on this one?  
Can anyone confirm that this type of error can be safely ignored by our log filter(as it constantly fire our alerting system based on Error log level) and does not indicate any issues in a running service?

**Comment by pashchuk** [comment] 2019-03-26 09:54
Probably I can try to fix this and submit a PR if there is no one in the team already on this issue or you have focused on the more priority tasks.

**Comment by rfrancisco** [comment] 2019-04-12 12:11
This is also affecting us. We have roughly 30k connections on each server and we don't use any backplane between them. Might be a coincidence but i noticed an increase in the number of exceptions of this type when i updated the typescript clients from 1.0.0-rc-final to 1.1.4.

Here is an example of 1s of logs from one of the servers:

`
2019-04-12 12:05:00.015 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.064 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.190 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.297 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.301 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.306 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.315 +00:00 [ERR] Failed writing message. Aborting connection.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
2019-04-12 12:05:00.322 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.327 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.329 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.329 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.331 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.332 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.334 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.336 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.339 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.341 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.344 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.344 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.347 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.356 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.368 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.371 +00:00 [ERR] Failed writing message. Aborting connection.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
2019-04-12 12:05:00.372 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.374 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.375 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.385 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.387 +00:00 [ERR] Failed writing message. Aborting connection.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
2019-04-12 12:05:00.389 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.390 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.401 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.411 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.414 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.418 +00:00 [ERR] Failed writing message. Aborting connection.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
2019-04-12 12:05:00.420 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.420 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.421 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.422 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.426 +00:00 [ERR] Failed writing message. Aborting connection.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
   at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
2019-04-12 12:05:00.513 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.831 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.865 +00:00 [ERR] Failed connection handshake.
2019-04-12 12:05:00.957 +00:00 [ERR] Failed connection handshake.`

**Comment by rfrancisco** [comment] 2019-04-13 10:57
> Might be a coincidence but i noticed an increase in the number of exceptions of this type when i updated the typescript clients from 1.0.0-rc-final to 1.1.4

I reverted the client script to the version compiled with 1.0.0-rc1-final and the exceptions disappeared after an hour or so. Moved back to the version compiled with 1.1.4 and the `System.InvalidOperationException: Writing is not allowed after writer was completed.` exceptions start to occur.

I did this 3 times and the results were always the same.

**Comment by anurse** [comment] 2019-04-30 21:39
To confirm, is anyone seeing a functional problem here or is it just a spurious exception message in the logs? I just want to make sure to understand if this is actually causing a functional problem. It looks like it's the writing of the "ping" message that's failing, which is fine (though annoying to see in the logs).

We'll look at ensuring the pings are stopped before the pipeline is closed in preview 6.

**Comment by rfrancisco** [comment] 2019-04-30 21:44
I believe that there is a functional problem. We saw a reduction of connected users, that was the main reason i was forced to move revert back to the version compiled with 1.0.0-rc-final.

**Comment by anurse** [comment] 2019-04-30 23:51
Hrm, I don't think that would be directly related to the callstack you're seeing though. The ping logic is very carefully designed to be resiliant to failures like this. In fact, if that log message is written it means the exception is **not** bubbling up, since we catch it and don't re-throw it: https://github.com/aspnet/AspNetCore/blob/0b7458cc984c0c0f9c702f9831c1815a365c07ac/src/SignalR/server/Core/src/HubConnectionContext.cs#L305-L308

The log message is unfortunately unclear about this. It says "Failed writing message. Aborting connection.". This is because we share the same log message in multiple places and in the other places it occurs it causes the connection to terminate. In this specific call stack though, the connection is **not terminated**. I'll open a PR to fix that message since it's not super clear. I am, however, very confident that those log messages aren't causing connections to be terminated.

The "Failed Connection Handshake" messages (referenced in your other issue https://github.com/aspnet/AspNetCore/issues/9327) are more likely to indicate a problem.

**Comment by kofifus** [comment] 2019-05-07 01:24
So the message is confusing and unclear, can it please be changed ?

**Comment by BrennanConroy** [comment] 2019-05-07 02:54
Yes. that is part of what we're doing.

**Closed** 2019-05-12 07:38 UTC
Labels: PRI: 2 - Preferred, area-signalr, bug, cost: XS, release-3.0

**Comment by BrennanConroy** [comment] 2019-05-28 20:46
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present.
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [x] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [3.0.100-preview6-012096]
			* ASP.NET Core Runtime: [3.0.0-preview6-19277-03]
			* .NET Core Runtime: [3.0.0-preview6-27727-02]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]

**Comment by Veikedo** [comment] 2019-05-29 13:56
Hi all, same problem.

> This is a benign error as it looks like the client is already disconnected.

No, the client is not disconnected at the time of the error. In our case the client is still waiting for the response, and disconnects after timeout.

Here is exception from the client:
> "lg-exception": "System.TimeoutException: Server timeout (30000.00ms) elapsed without receiving a message from the server.",
> "lg-callsite": "Microsoft.AspNetCore.SignalR.Client.HubConnection+<ReceiveLoop>d__62.MoveNext:0",

Btw, why it says timeout is 30000.00ms though I see it should be only 5 seconds by default?

**Comment by BrennanConroy** [comment] 2019-05-29 15:19
Hi, we don't track closed issues. If you're seeing a problem please open a new issue with details of the issue.

We have a nice guide for collecting information that is often useful to include in issues: https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2
