### ISSUE TITLE
Parent ViewModel is not bound (null) when error occurs in child VM

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#5681] opened 2018-12-17 23:44 UTC
_From @montella1507 on Monday, 17 December 2018 22:24:34_

# General
When error occurs in binding of child viewmodel, parent ViewModel is NULL. 

#Desired behavior
Parent ViewModel should not be NULL, only Child VM.

How to simulate:
```c#
public class ParentVM {
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public ChildVM Xyz { get; set; }
}

public class ChildVM 
    {
        public string A { get; set; }
        public string B { get; set; }
}

Request payload:
{
    "firstName": "PETER",
    "lastName": "PARKER",
    "xyz":  "kldqwjkld"  <<<< should be { "a": "qddq", "b": "dqdd" }
}
```

Result in controller is, VM is NULL:
![image](https://user-images.githubusercontent.com/10418323/50119343-c9ef7c80-0252-11e9-86c6-356a32326bad.png)

Version info:
Microsoft.AspnetCore.App (2.1.1) 
Win 10 x64  .NET Core runtime.

_Copied from original issue: dotnet/core#2156_

**Comment by mkArtakMSFT** [comment] 2018-12-20 18:18
Thanks for contacting us, @montella1507.
@dougbu, isn't this by design?

**Comment by dougbu** [comment] 2018-12-20 20:51
This is by design. Though MVC views easily handle errors lower in the model tree, APIs (where input formatters and JSON or XML request bodies are used) rarely can. Input formatters _never_ provide a model if an error occurred.

**Comment by dougbu** [comment] 2019-02-05 16:18
@montella1507 thank you for your feedback. We're closing this issue as the questions asked here have been answered.

**Closed by dougbu** 2019-02-05 16:18 UTC
Labels: area-mvc, question

**Comment by montella1507** [comment] 2019-02-05 17:11
Yes, sorry. Forgot to close.
