### ISSUE TITLE
git clone issues

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#11913] opened 2019-07-05 08:06 UTC
issues when cloning repo - other repo's work fine; also tried multiple clients and internet connections

git.exe clone --progress --recursive -v "https://github.com/aspnet/AspNetCore.git" "C:\DEV\github.com\aspnet\AspNetCore"

Cloning into 'C:\DEV\github.com\aspnet\AspNetCore'...
POST git-upload-pack (gzip 11775 to 5727 bytes)
remote: Enumerating objects: 218, done.
remote: Counting objects: 100% (218/218), done.
remote: Compressing objects: 100% (180/180), done.
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

git did not exit cleanly (exit code 128) (31266 ms @ 05/07/2019 09:05:08)

**Comment by grahamehorner** [comment] 2019-09-03 20:45
@mkArtakMSFT any update with regards this ? I've completely rebuilt a development system from scratch and I'm still having the same issue.

**Comment by mkArtakMSFT** [comment] 2019-09-03 21:01
Ping @aspnet/build

**Comment by dougbu** [comment] 2019-09-03 21:51
@grahamehorner I'm not sure exactly what causes `git` to exit with that code. I'm guessing the root cause is your relatively long path to the repo root. (AspNetCore has some rather long paths itself.)

Suggest either
1. `git clone --config core.longpaths=true` though some parts of the build may fail later.
2. Move the AspNetCore repo to something closer to the drive's root e.g. c:\DEV

**Comment by grahamehorner** [comment] 2019-09-04 17:09
@dougbu FYI, I've been able to clone the repo now by adding the --depth 1
I used the same path as previously detailed.

git.exe clone --progress --recursive -v --depth 1 "https://github.com/aspnet/AspNetCore.git" "C:\DEV\github.com\aspnet\aspnetcore"

Cloning into 'C:\DEV\github.com\aspnet\aspnetcore'...
POST git-upload-pack (190 bytes)
POST git-upload-pack (199 bytes)
remote: Enumerating objects: 14092, done.
remote: Counting objects: 100% (14092/14092), done.
remote: Compressing objects: 100% (11262/11262), done.
remote: Total 14092 (delta 4455), reused 5919 (delta 2011), pack-reused 0
Receiving objects: 100% (14092/14092), 13.76 MiB | 827.00 KiB/s, done.
Resolving deltas: 100% (4455/4455), done.
Updating files: 100% (12354/12354), done.
Submodule 'src/submodules/MessagePack-CSharp' (https://github.com/aspnet/MessagePack-CSharp.git) registered for path 'src/submodules/MessagePack-CSharp'
Submodule 'googletest' (https://github.com/google/googletest) registered for path 'src/submodules/googletest'
Cloning into 'C:/DEV/github.com/aspnet/aspnetcore/src/submodules/MessagePack-CSharp'...
remote: Enumerating objects: 8118, done.
remote: Total 8118 (delta 0), reused 0 (delta 0), pack-reused 8118
Receiving objects: 100% (8118/8118), 6.29 MiB | 875.00 KiB/s, done.
Resolving deltas: 100% (6053/6053), done.
Cloning into 'C:/DEV/github.com/aspnet/aspnetcore/src/submodules/googletest'...
remote: Enumerating objects: 18002, done.
remote: Total 18002 (delta 0), reused 0 (delta 0), pack-reused 18002
Receiving objects: 100% (18002/18002), 6.45 MiB | 900.00 KiB/s, done.
Resolving deltas: 100% (13282/13282), done.
Submodule path 'src/submodules/MessagePack-CSharp': checked out '8861abdde93a3b97180ac3b2eafa33459ad52392'
Submodule path 'src/submodules/googletest': checked out '4e4df226fc197c0dda6e37f5c8c3845ca1e73a49'

Success (126906 ms @ 04/09/2019 18:06:47)

**Comment by grahamehorner** [comment] 2019-09-04 17:13
also please note that without --depth 1 with a short path the result is :-

git.exe clone --progress --recursive -v "https://github.com/aspnet/AspNetCore.git" "C:\DEV\AspNetCore"

Cloning into 'C:\DEV\AspNetCore'...
POST git-upload-pack (gzip 14225 to 6957 bytes)
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (32/32), done.
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

git did not exit cleanly (exit code 128) (32812 ms @ 04/09/2019 18:11:48)

**Comment by dougbu** [comment] 2019-09-05 07:28
@grahamehorner if `--depth 1` makes a difference, you're likely reporting a problem with `git clone` and the size of our history.

That said, I'm unable to reproduce the issue with `git` version '2.23.0.windows.1'. If you're using an earlier version, please upgrade and try again.

**Comment by grahamehorner** [comment] 2019-09-06 09:11
@dougbu the version of git I'm using is git version 2.23.0.windows.1

**Comment by dougbu** [comment] 2019-09-06 16:24
I recommend working with the `git` for Windows owners to find what can lead to exit code 128. There must be something specific to your machine or the network between you and GitHub leading to these errors.

**Comment by grahamehorner** [comment] 2019-09-19 13:18
@dougbu FYI,  this issue also occurs with VisualStudio 2019 v16.3.0 preview 4 (clean rebuild with Windows 10 - 1903 build 18362.356) I've tried three different network connections/internet service providers and 5 different machines builds both physical/virtual

```
> Git failed with a fatal error.
> early EOF
> the remote end hung up unexpectedly
> index-pack failed
> RPC failed; curl 18 transfer closed with outstanding read data remaining
```

**Comment by grahamehorner** [comment] 2019-09-20 22:01
@dougbu @mkArtakMSFT FYI, this issue looks to be related to virtual network adapters installed when using hyper-v/docker ce for windows; removing the virtual adapters using 'computer management' allowed git clone to work without the depth parameter and clone the repo in approx. 1/2 the time.

**Comment by mkArtakMSFT** [comment] 2019-09-20 23:18
Thanks for additional details, @grahamehorner.
@danroth27 do you know anybody from that side of the world to take over this investigation?

**Comment by danroth27** [comment] 2019-10-01 01:37
@msartakmsft Sorry, but I don't.

**Comment by mkArtakMSFT** [comment] 2019-10-11 21:03
@grahamehorner the best thing to do would be to file a VS Feedback issue with details and a reference to this issue. That way the feedback will be directed to the team who owns this much quicker. I'm closing this issue as there is no pending action for us.

**Closed by mkArtakMSFT** 2019-10-11 21:03 UTC
Labels: area-infrastructure, external
