### ISSUE TITLE
[Blazor] Double routing not working

### ISSUE THREAD

**Issue by ichensky** [aspnet/AspNetCore#10686] opened 2019-05-31 08:15 UTC
1. Create page(change a little bit from basic blazor web app template) that accept several routes: 
```
@page "/fetchdata"
@page "/fetchdata/{page:int}"
```
 and implement simple pagination(several buttons that implement onclick event, which change number of elements of  `WeatherForecast[]` arr and call then `UriHelper.NavigateTo($"/fetchdata/{page}")`)

2. Lunch app, go from `menu` to the page `/fetchdata`, then to the pages: `/fetchdata/1`, `fetchdata/3`, `/fetchdata/5`, etc routing works ok, page rendered, data changed at page and url in browser.
3. If you try to go from page (with number), for ex. `/fetchdata/5` to the page: `/fetchdata` (click on `menu` item)-> 
url in browser will be changed as expected, but page wouldn't be rendered(changed). 
--
If you go from page for ex. `/fetchdata/5` to the page: `/fetchdata/0` url in browser will be changed and page will be rendered as expected.

**Comment by mkArtakMSFT** [comment] 2019-05-31 16:52
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by javiercn** [comment] 2019-05-31 16:54
This is not supported. You can achieve the same thing by using an optional parameter `/fetchdata/{page:int?}`

**Comment by ichensky** [comment] 2019-06-03 08:29
@javiercn 
It is not possible to achive this thing with `/fetchdata/{page:int?}`, becuase threre will be exception: 
```
"System.InvalidOperationException: Invalid template '/fetchdata/{page:int?}'. The character '?' in parameter segment '{page:int?}' is not allowed."
```

**Comment by javiercn** [comment] 2019-06-03 16:23
Maybe I got the syntax wrong.

Reopening for further investigation.

**Comment by SteveSandersonMS** [comment] 2019-06-03 17:38
Thanks for reporting it. This is a duplicate of a known issue: https://github.com/aspnet/AspNetCore/issues/7419

We did fix it at one point, but had to revert the fix after discovering it caused worse issues. I agree we still do need to find a working fix.

**Closed by SteveSandersonMS** 2019-06-03 17:38 UTC
Labels: area-blazor, investigate

**Comment by ichensky** [comment] 2019-06-04 05:11
To fix this issue, needed, 
when blazor navigated to the page: `/fetchdata` clean all possible params 
for ex. in the `SetParametersAsync` , then multiple routing become work fine. 

```csharp
@page "/fetchdata"
@page "/fetchdata/{page:int}"

[Parameter]
public int Page { get; set; }
public override Task SetParametersAsync(ParameterCollection parameters)
{
        if (!parameters.TryGetValue("page", out int page)) {
            Page = 0;
        }
        return base.SetParametersAsync(parameters);
}
```
This functionality should be done inside of the blazor or needed to document, that for multiple routing it is needed manualy to clean params.
