### ISSUE TITLE
Blazor: Unable to add new .razor-Files

### ISSUE THREAD

**Issue by Z3roCoder** [aspnet/AspNetCore#13487] opened 2019-08-27 19:13 UTC
### Describe the bug
I have copied the Counter.razor and renamed it to "Test.razor".
Now the compiler complains to me with the following error:
'Template.ExecuteAsync()': no suitable method found to override	DiscordBot.Client	

### To Reproduce
1. Create a new Client Side Blazor Project (WebAssembly) with the Preview 8
2. Duplicate "Counter.razor" and name it "Test.razor"
3. See error

### Expected behavior
It should work as expected, the file should be compiled.

### Additional context
Apparently it works when I Right-Click my newly created file and click "Run Custom tool" - But I think it should do that automatically before building.

**Comment by mkArtakMSFT** [comment] 2019-08-30 16:25
@pranavkm please work with @danroth27 as he has a repro for this.

**Comment by danroth27** [comment] 2019-08-30 16:30
I'm able to reproduce this with Preview9. The errors appear to be specific to intellisense. The normal build succeeds, but intellisense is broken in the copied file until I close and reopen it.

**Comment by mkArtakMSFT** [comment] 2019-09-04 16:29
@ajaybhargavb is this something you can handle?

**Comment by rynowak** [comment] 2019-10-04 16:09
Blocked because we can't reproduce this right now. Let's have @ajaybhargavb and @danroth27 sit together and try

**Comment by mkArtakMSFT** [comment] 2019-11-01 16:04
We're closing this issue as we were unable to reproduce this behavior.
If you happen to have more information / sample project, which can help with reproducing this, please provide it and reopen the issue.

**Closed by mkArtakMSFT** 2019-11-01 16:04 UTC
Labels: PRI: 2 - Preferred, Tooling, area-blazor, blocked, bug, cost: S
