### ISSUE TITLE
How could I use multiple UserManager<T> in a project?

### ISSUE THREAD

**Issue by NanaseRuri** [aspnet/AspNetCore#5130] opened 2018-12-15 13:52 UTC
### Is your feature request related to a problem? Please describe.
I created two IdentityDbContext<T>, one is AdminIdentityDbContext:IdentityDbContext<Admin>, and another is StudentIdentityDbContext:IdentityDbContext<Student>. 

And I created two controllers, one is:
```
    public class AdminAccountController : Controller
    {
        private UserManager<Admin> _userManager;
        private SignInManager<Admin> _signInManager;

        public AdminAccountController(UserManager<Admin> userManager, SignInManager<Admin> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
```

Another is:
 ```
public class StudentAccountController : Controller
    {
        private UserManager<Student> _userManager;
        private SignInManager<Student> _signInManager;

        public StudentAccountController(UserManager<Student> studentManager, SignInManager<Student> signInManager)
        {
            _userManager = studentManager;
            _signInManager = signInManager;
        }

```

My Startup.cs is as below:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryDemo.Data;
using LibraryDemo.Infrastructure;
using LibraryDemo.Models.DomainModels;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace LibraryDemo
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddDbContext<LendingInfoDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("LendingInfoDbContext"));
            });
            services.AddDbContext<AdminIdentityDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("AdminIdentityDbContext"));
            });
            services.AddDbContext<StudentIdentityDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("StudentIdentityDbContext"));
            });
            services.AddIdentity<Student, IdentityRole>(opts =>
                {
                    opts.User.RequireUniqueEmail = true;
                    opts.User.AllowedUserNameCharacters = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM0123456789";
                    opts.Password.RequiredLength = 6;
                    opts.Password.RequireNonAlphanumeric = false;
                    opts.Password.RequireLowercase = false;
                    opts.Password.RequireUppercase = false;
                    opts.Password.RequireDigit = false;
                }).AddEntityFrameworkStores<StudentIdentityDbContext>()
                .AddDefaultTokenProviders();
            services.ConfigureApplicationCookie(opts =>
            {
                opts.LoginPath = "/StudentAccount/Login";
            });
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }
            app.UseAuthentication();
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
            DatabaseInitiator.Initial(app.ApplicationServices).Wait();
        }
    }
}
```

But when I got the site "/AdminAccount/Login", I got an error:

> InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[LibraryDemo.Models.DomainModels.Admin]' while attempting to activate 'LibraryDemo.Controllers.AdminAccountController'.

### Describe the solution you'd like
I don't feel like the Role feature, so what else can I do to resolve this problem? Thanks a lot.

### Describe alternatives you've considered
I tried to change the schema of the DbContext but failed the same.

### Additional context
I have put the project to github:
https://github.com/NanaseRuri/LibraryDemo

**Comment by RemiBou** [comment] 2018-12-16 17:04
There is no "AddIdentity<Admin, IdentityRole>" in your ConfigureServices. You need one per user type I guess

**Comment by NanaseRuri** [comment] 2018-12-17 00:04
> There is no "AddIdentity<Admin, IdentityRole>" in your ConfigureServices. You need one per user type I guess

In fact, I added AddIdentity<Admin, IdentityRole> and there is another error.

**Comment by NanaseRuri** [comment] 2018-12-17 00:14
> There is no "AddIdentity<Admin, IdentityRole>" in your ConfigureServices. You need one per user type I guess

In fact, I have already tried it but another error occured.

**Comment by RemiBou** [comment] 2018-12-17 12:15
I don't think it's a bug or a missing feature maybe you can ask for help on stackoverflow.com about how to setup multiple UserManager in a single app.

**Comment by NanaseRuri** [comment] 2018-12-17 13:05
> I don't think it's a bug or a missing feature maybe you can ask for help on stackoverflow.com about how to setup multiple UserManager in a single app.

Well, I have search for the solution for whole day but make no sense. It seems that if I use Identity in my project I could never use cookie for authorization.

**Comment by blowdart** [comment] 2019-07-24 20:28
We're closing this issue as the behaviour discussed seems to be by design.

**Closed by blowdart** 2019-07-24 20:28 UTC
Labels: area-identity
