### ISSUE TITLE
"HTTP Error 500.30 - ANCM In-Process Start Failure" in Azure when CPU and Memory are maxed out

### ISSUE THREAD

**Issue by uniqueumang** [aspnet/AspNetCore#10383] opened 2019-05-20 06:01 UTC
### Describe the bug
When CPU (100%) & memory (90%) are maxed out in Azure App Service, the application fails to start with Http error 500.30 - ANCM In-process Start Failure.

![CPUUsage](https://user-images.githubusercontent.com/3345614/57999352-68d91700-7b18-11e9-8545-56cb81d77e46.png)

As per event log: 
```xml
<Event>
<System>
<Provider Name="IIS AspNetCore Module V2"/>
<EventID>1007</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2019-05-20T03:35:32Z"/>
<EventRecordID>648962046</EventRecordID>
<Channel>Application</Channel>
<Computer>xyz</Computer>
<Security/>
</System>
<EventData>
<Data>
Application '/LM/W3SVC/1272574654/ROOT' with physical root 'D:\home\site\wwwroot\' failed to load clr and managed application. Managed server didn't initialize after 120000 ms.
</Data>
<Data>Process Id: 123884.</Data>
<Data>
File Version: 12.2.19024.2. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 522705f9a27b99ca4ad261f2e89fe51a77b2338e
</Data>
</EventData>
</Event>
```
### To Reproduce
1. Make sure your app service is at 100% CPU 
2. Deploy a new web application (.net core 2.2 & with In-process)
3. Try sending any request 

### Expected behavior
Give more meaningful exception on why application failed to start. 

### Additional context
Include the output of `dotnet --info`

**Comment by davidfowl** [comment] 2019-05-20 12:56
I’m not sure we can easily attribute the 100% or 90% CPU usage to the reason why ANCM fails to start. Even though it could be the cause, it’s not necessarily correct to assume it is. 

How did you end up in this situation? What was causing the 100% CPU? We’re you just at capacity?

**Comment by uniqueumang** [comment] 2019-05-20 17:01
> How did you end up in this situation? What was causing the 100% CPU? We’re you just at capacity?

We have 61 apps deployed on small single instance.

**Comment by jkotalik** [comment] 2019-05-20 17:09
Do you have the autoStart feature enabled? Can you try increasing the startupTimeoutLimit? See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#attributes-of-the-aspnetcore-element

**Comment by uniqueumang** [comment] 2019-05-20 17:14
> I’m not sure we can easily attribute the 100% or 90% CPU usage to the reason why ANCM fails to start. Even though it could be the cause, it’s not necessarily correct to assume it is.

We ran few experiments & it feels like it is high CPU usage which is causing application not to start. For example, when our application doesn't start, by simply stopping an existing app in 'Application Service plan'  then our application starts. 

Again this might be symptoms not actual problem.

**Comment by uniqueumang** [comment] 2019-05-20 17:31
> Do you have the autoStart feature enabled? Can you try increasing the startupTimeoutLimit? See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#attributes-of-the-aspnetcore-element

How do I make sure autoStart is enabled? 
Also, the default timeout is 120s (which I think is high enough). what are we trying to achieve by increasing it?

**Comment by anurse** [comment] 2019-05-21 22:33
It sounds like this is timing out (as per the event log) this is a likely situation if you have a lot of apps starting on a machine with a lot of CPU load. Moving to discussions for now as there isn't an actionable work item for us right now. We can't expose the detailed error in the error page and the event log is pretty clear about what's happening (we don't know that the timeout is due to CPU usage, we have no way of being sure of that).

**Comment by uniqueumang** [comment] 2019-05-22 03:29
> It sounds like this is timing out (as per the event log) this is a likely situation if you have a lot of apps starting on a machine with a lot of CPU load. Moving to discussions for now as there isn't an actionable work item for us right now. We can't expose the detailed error in the error page and the event log is pretty clear about what's happening (we don't know that the timeout is due to CPU usage, we have no way of being sure of that).

I disagree that event log is clear. All Event log is mentioning is that the process failed to start after 120s. No mention of why it failed. 

Also, as a developer I have no control over the error page (Http error 500.30 - ANCM In-process Start Failure). I don't want to show that to my customer/end-users.

**Comment by anurse** [comment] 2019-05-22 16:12
> No mention of why it failed.

Because we **don't know why** it failed. It could be because your startup logic has long-running code, or it could be because the CPU is so busy it caused the startup logic to take too long. We don't know which it is, _all we know_ is that the startup logic didn't complete in the expected time which is exactly what we report. If you think the error message could be rephrased to make that clearer, we can look at doing that.

> Also, as a developer I have no control over the error page

This is the page generated by ANCM, but I believe you can customize it in your web.config file using the [`<httpErrors>` section](https://docs.microsoft.com/en-us/iis/configuration/system.webServer/httpErrors/error)

**Comment by uniqueumang** [comment] 2019-05-29 19:50
> > No mention of why it failed.
> 
> Because we **don't know why** it failed. It could be because your startup logic has long-running code, or it could be because the CPU is so busy it caused the startup logic to take too long. We don't know which it is, _all we know_ is that the startup logic didn't complete in the expected time which is exactly what we report.

Shouldn't we be logging more logs that can give more clues on why it is taking so long (not sure if we can enable more logs on startup). The code we tried was bare bone template from VS so pretty sure start-up was as slim as possible. Is it not possible to log information that happened before it called the startup logic?

Few other things we have noticed:
* Once in-process Application has started it keeps working given the same environment 
* the behaviour doesn't seem to happen for Out of process application.

**Comment by anurse** [comment] 2019-05-29 20:00
Have you [configured logging to be more detailed](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-filtering)? By default we are pretty light on what we log to the `Information` level to avoid overloading systems. If you turn the logging up to `Debug` or `Trace` you would get a bunch of extra information. If there are areas where more logs would help you identify this issue, we can certainly look at adding more logging.

It's my understanding that your App Service is **already at 100% cpu** when you start, right? I'm not sure what additional logging would help here. If your server is under heavy load, things get slower and timeouts elapse. If this is a common situation, you may have to just increase these timeouts to compensate. What is the steady-state CPU load for your app (i.e. the CPU load when all the apps are running smoothly)?

**Closed** 2019-05-31 15:59 UTC
Labels: area-servers
