### ISSUE TITLE
FileNotFoundException after copying and renaming a cshtml file in a Blazor app

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8317] opened 2019-03-08 06:31 UTC
Here's what I did that resulted in this exception:
- Create a new Blazor 0.9.0 standalone app in VS2019 Preview channel
- Copy and paste *Index.cshtml* (generated name is *Index - Copy.cshtml*) and rename it to *Todos.cshtml*
- Update the contents of *Todos.cshtml* with:

  ```cshtml
  @page "/todos"
  <h1>Todos</h1>
  ```

- Run the app and browse to /todos

Exception from ActivityLog.xml

```
Error encountered from project 'C:\Users\daroth\Source\Repos\WebApplication6\WebApplication6\WebApplication6.csproj': System.IO.FileNotFoundException: Could not find file 'C:\Users\daroth\Source\Repos\WebApplication6\WebApplication6\Pages\Index - Copy.cshtml'. File name: 'C:\Users\daroth\Source\Repos\WebApplication6\WebApplication6\Pages\Index - Copy.cshtml'    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.FileInfo.get_Length()    at Roslyn.Utilities.FileUtilities.GetFileLength(String fullPath)    at Microsoft.CodeAnalysis.FileTextLoader.ValidateFileLength(Workspace workspace, String path)    at Microsoft.CodeAnalysis.FileTextLoader.<LoadTextAndVersionAsync>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass20_0.<<DocumentClosed>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.<GetTextVersionAsync>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.<GetGeneratedOutputAndVersionCoreAsync>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.<GetGeneratedOutputAsync>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.CodeAnalysis.Razor.BackgroundDocumentGenerator.<ProcessDocument>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.CodeAnalysis.Razor.BackgroundDocumentGenerator.<TimerTick>d__43.MoveNext()
```

**Comment by mkArtakMSFT** [comment] 2019-03-12 16:34
@ajaybhargavb could you please look into this? Thanks!

**Comment by ajaybhargavb** [comment] 2019-03-20 21:10
@danroth27, are you able to reliably repro this? I tried your steps and I was only able to reproduce this once in 16.0 Preview and I can't reproduce this at all in 16.1.

**Comment by danroth27** [comment] 2019-03-20 22:11
@ajaybhargavb From experience I've learned that copying files in the solution is problematic, but no I can't repro this particular issue reliably.

**Comment by ajaybhargavb** [comment] 2019-03-21 01:33
I can't reproduce this in 16.1 even once makes me think we did something to fix this but I'm not sure what. I'll keep trying.

**Comment by rynowak** [comment] 2019-03-21 01:36
if we can't repro this I don't think it's worth spending lots of time on it unless it comes through VS feedback.

Doing _imports.razor would be more valuable

**Comment by mkArtakMSFT** [comment] 2019-03-21 15:59
Agree. Closing this. If there is such an issue, it'll show up again in the future.

**Closed by mkArtakMSFT** 2019-03-21 15:59 UTC
Labels: area-mvc, feature-Components, investigate
