### ISSUE TITLE
Add a possibility to stop request (short-circuiting pipeline) when CORS are not allowed

### ISSUE THREAD

**Issue by JulijaRamoskiene** [aspnet/AspNetCore#3171] opened 2018-05-29 14:47 UTC
Update CORS middleware to support configuration to terminate request when CORS are not allowed for given request, e.g. Origin is not allowed. 
It could look something like this:
app.UseCors(builder => builder
                .WithOrigin("http://some.allowed.origin")
                .AllowAnyHeader()
                .AllowAnyOrigin()
              **.TerminateIfNotAllowed ()**);

Currently, request will be passed to next middleware even if origin is not allowed.

**Comment by javiercn** [comment] 2018-09-27 18:18
This is by design. CORS is not meant to change the response produced by the server but only to prevent unauthorized origins from accessing the contents of the response. Anything that could be dangerous and couldn't be done before CORS is done through a preflight request and anything else could be done already without using CORS.

**Comment by javiercn** [comment] 2018-10-11 22:13
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Closed by javiercn** 2018-10-11 22:13 UTC
Labels: 1 - Ready, PRI: 2 - Preferred, enhancement, repo:CORS
