### ISSUE TITLE
[CI] SignalR LongPollingTransport HubConnectionTests.CanStartConnectionFromClose

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#7895] opened 2019-02-23 16:18 UTC
AspNetCore-ci (Test: Ubuntu 16.04 x64)

Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClose
```
System.Exception : 3 error(s) logged.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport - LongPollingTerminated - UFGNbt8Lv_wrJYlcpw_fmg - Long Polling transport was terminated due to an error on connection.
===================
System.InvalidOperationException: Reading is not allowed after reader was completed.
at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token) in /_/src/SignalR/common/Http.Connections/src/Internal/Transports/LongPollingTransport.cs:line 97
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionContext.cs:line 310
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionContext.cs:line 223
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionManager.cs:line 225
===================
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager - FailedDispose - Failed disposing connection UFGNbt8Lv_wrJYlcpw_fmg.
===================
System.InvalidOperationException: Reading is not allowed after reader was completed.
at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token) in /_/src/SignalR/common/Http.Connections/src/Internal/Transports/LongPollingTransport.cs:line 97
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionContext.cs:line 310
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionContext.cs:line 223
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionManager.cs:line 225
===================
Microsoft.AspNetCore.Server.Kestrel - ApplicationError - Connection id "0HLKPIQJ29LV8", Request id "0HLKPIQJ29LV8:00000005": An unhandled exception was thrown by the application.
===================
System.InvalidOperationException: Reading is not allowed after reader was completed.
at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token) in /_/src/SignalR/common/Http.Connections/src/Internal/Transports/LongPollingTransport.cs:line 97
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully) in /_/src/SignalR/common/Http.Connections/src/Internal/Http

Stack trace
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /home/vsts/work/1/s/src/SignalR/common/testassets/Tests.Utils/VerifyNoErrorsScope.cs:line 61
   at Microsoft.AspNetCore.SignalR.Tests.FunctionalTestBase.MultiDisposable.Dispose() in /home/vsts/work/1/s/src/SignalR/common/testassets/Tests.Utils/FunctionalTestBase.cs:line 59
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(String protocolName, HttpTransportType transportType, String path) in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
```

Seen in https://github.com/aspnet/AspNetCore/pull/7894

**Comment by mikaelm12** [comment] 2019-02-25 05:04
I believe that this is a dupe of https://github.com/aspnet/AspNetCore/issues/6597. This is in our preview 4 milestone

**Closed** 2019-02-25 19:56 UTC
Labels: area-signalr
