### ISSUE TITLE
Registering IHostedService interface having service does not automatically start it

### ISSUE THREAD

**Issue by Grafu** [aspnet/AspNetCore#8761] opened 2019-03-23 19:22 UTC
### Describe the bug
If you do `services.AddSingleton<IHostedService, HostedService>();`, the service is automatically started. But if you do `services.AddSingleton<ICustomHostedService, HostedService>();` where ICustomHostedService implements IHostedService, the service no longer starts automatically. 

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code 
```c#
services.AddSingleton<IHostedService, HostedService>(); // After that try services.AddSingleton<ICustomHostedService, HostedService>();

public interface ICustomHostedService : IHostedService {
        void SendMessage(string topic, string message);
    }

using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using WebApplication1.Interfaces;

public class HostedService : ICustomHostedService {

	private readonly ILogger _logger;

	public Service(ILogger<HostedService> logger) {
		_logger = logger;
	}

	public Task StartAsync(CancellationToken cancellationToken) {
		_logger.LogInformation("Hello");
		return Task.CompletedTask;
	}

	public Task StopAsync(CancellationToken cancellationToken) {
		_logger.LogInformation("Good bye");
		return Task.CompletedTask;
	}
}
```

### Expected behavior
The singleton service should start immediately no matter if it was registered as IHostedService or ICustomHostedService implementing IHostedService.

### Screenshots
IHostedService:
![image](https://user-images.githubusercontent.com/11540828/54870600-76d91880-4db1-11e9-81b8-e7a679b0ce1f.png) 

ICustomHostedService:
![image](https://user-images.githubusercontent.com/11540828/54870612-996b3180-4db1-11e9-8401-b59ec3464349.png)

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    b9f2fa0ca8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Eilon** [comment] 2019-03-25 03:15
I believe that services are resolved by the service type they are registered as, without inspecting the type inheritance hierarchy. At the extreme, if you try to resolve a service of type `object`, in theory you'd get every single service in the system, but of course that doesn't happen.

**Comment by Tratcher** [comment] 2019-03-27 17:10
Correct, this is by design. If you really want to register your service under multiple types then you can register one of the types as a factory that redirects.
https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/HostBuilder.cs#L202

**Closed** 2019-04-12 06:16 UTC
Labels: area-hosting
