### ISSUE TITLE
Move x-plat testing into VSTS

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#5571] opened 2018-08-08 17:55 UTC
AppVeyor and Travis are still required to provide full test coverage. To make VSTS provide the same level of coverage, we need to

* Enable selenium-standalone on VSTS
* Add macOS and Linux build phases
* Ensure tests run with `/p:BlazorAllTests=true` (or just make this default)

**Comment by SteveSandersonMS** [comment] 2019-02-06 14:20
Closing as duplicate of #5457

**Closed by SteveSandersonMS** 2019-02-06 14:20 UTC
Labels: area-mvc, feature-Components
