### ISSUE TITLE
.Net Core 3.0 WebApi Reports Error When Return OK(List<dynamic>)

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#16610] opened 2019-10-28 18:19 UTC
_From @carroty3334 on Friday, October 25, 2019 3:05:54 AM_

When .net core 3.0 webapi returns Ok(List< dynamic >) or Ok(List< object >), this error occurs:
System.InvalidCastException: Unable to cast object of type '< GetEnumerator >d__9' to type 'System.Collections.IDictionaryEnumerator'.

_Copied from original issue: dotnet/core#3691_

**Comment by pranavkm** [comment] 2019-10-28 19:51
@carroty3334 this is very likely the same issue as https://github.com/dotnet/corefx/issues/41329. This is fixed as part of the 3.1.0-preview2 release. For 3.0, you can workaround this issue  either by authoring a custom JSON serializer or by using Newtonosft.Json - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support

/cc @ahsonkhan \ @steveharter

**Comment by javiercn** [comment] 2019-10-29 16:33
We are closing this issue as it's a duplicate of  dotnet/corefx#41329 and it has been fixed in 3.1 preview2.

**Closed by javiercn** 2019-10-29 16:33 UTC
Labels: area-mvc

**Comment by ahsonkhan** [comment] 2019-11-14 05:00
@carroty3334 - can you please verify that the issue you reported has been fixed with 3.1?

**Comment by carroty3334** [comment] 2019-11-14 05:30
> @carroty3334 - can you please verify that the issue you reported has been fixed with 3.1?

I ran a small test and it seems this issue has been fixed.
