### ISSUE TITLE
Dependency injection Annotation

### ISSUE THREAD

**Issue by josejmoran** [aspnet/AspNetCore#5140] opened 2018-12-16 14:02 UTC
### Is your feature request related to a problem? Please describe.
It will be great to have a feature that automatically register classes into the Dependency Injection container, so I just have to use an annotation on top of the class I want to be registered. For example:

[Singleton]
class EmailSend() {
  .....
}

This way I just write my class and put the annotation and that's all I need to do.

**Comment by davidfowl** [comment] 2018-12-16 14:09
Dupe of https://github.com/aspnet/Extensions/issues/680

**Closed by davidfowl** 2018-12-16 14:09 UTC
