### ISSUE TITLE
[Blazor] select element binding fails on bind init.

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/AspNetCore#10481] opened 2019-05-23 00:44 UTC
### Describe the bug
When a `select` element is bound, the element wont reflect the backing property value until after manually interacting with the element.

### To Reproduce
1. Create a Blazor (ASP.NET Core hosted) project using the Visual Studio provided template.
2. Delete all the code inside the `Counter.razor` page and paste the following code:

```
@page "/counter"

@if (this.Model != null)
{
    <select bind="@this.Model.MyProperty">
        <option value="0">Zero</option>
        <option value="1">One</option>
    </select>
}

<hr />

<button onclick="@DoIt">Prove That Binding is working by changing value to Zero via code</button>

@functions {

    class SomeClass
    {
        public int MyProperty { get; set; } = 1;
    }

    SomeClass Model { get; set; }

    protected override Task OnInitAsync()
    {
        this.Model = new SomeClass();
        return base.OnInitAsync();
    }

    private void DoIt()
    {
        this.Model.MyProperty = 0;
    }
}

```
3. Run the project and select the Counter page.
4. Look at the value on the combo-box, it should read `One` but instead it reads `Zero`.
5. Now manually set the combo box value so that it reads 'One'.
6. Now click the only button on the form and watch the combo box update from `One` to `Zero`.  This proves (at least to me) that the binding is now working.

**Comment by enetstudio** [comment] 2019-05-23 17:11
This is a known issue: https://github.com/aspnet/AspNetCore/issues/9716

**Comment by mkArtakMSFT** [comment] 2019-05-24 16:55
Thanks for contacting us, @rxelizondo.
This is indeed a duplicate of the referenced issue, so closing.

**Closed by mkArtakMSFT** 2019-05-24 16:55 UTC
Labels: area-blazor

**Comment by dipenlama22** [comment] 2019-10-24 13:35
As a workaround, I assign the property value of the first item from collection I retrieved from the server by default.

**Comment by FelipeCostaGualberto** [comment] 2019-11-11 03:13
Hello, I'm having an issue with this problem.
In my CRUD application, each `Belt `must be assigned to a `Management` and a `Situation`. Model is:
```
    public class Belt {
        public int Id { get; set; }
        public string Text { get; set; }
        public int ManagementId { get; set; }
        public virtual Management Management { get; set; }
        public int SituationId { get; set; }
        public virtual Situation Situation { get; set; }
    }
    public class Situation {
        public int Id { get; set; }
        public string Text { get; set; }
    }
    public class Management {
        public int Id { get; set; }
        public string Text { get; set; }
    }
```

This is the Form component of my App:

```
@inject HttpClient http

<EditForm Model="@Belt" OnValidSubmit="@OnValidSubmit">
    <div class="form-group">
        <label>Belt Name</label>
        <input @bind="Belt.Text" class="form-control" />
    </div>

    <div class="form-group">
        <label>Management</label>
        <select class="form-control" @bind="Belt.ManagementId">
            <option value="">-- Select a Management --</option>
            @foreach (var item in Managements) {
                <option value="@item.Id">@item.Text</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label>Situation</label>
        <select class="form-control" @bind="Belt.SituationId">
            <option value="">-- Select a Situation --</option>
            @foreach (var item in Situations) {
                <option value="@item.Id">@item.Text</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</EditForm>

@code {
    [Parameter] public Belt Belt { get; set; }
    [Parameter] public EventCallback OnValidSubmit { get; set; }

    List<Management> Managements = new List<Management>();
    List<Situation> Situations = new List<Situation>();

    protected override async Task OnInitializedAsync() {
        Managements = await http.GetJsonAsync<List<Management>>("api/management");
        Situations = await http.GetJsonAsync<List<Situation>>("api/situation");
    }
}

```
The binding from `input` (`Belt.Name`) always works perfectly.

The binding from `select` (`Belt.ManagementId`) works for the first time, then it doesn't work anymore.

The binding from `select` (`Belt.SituationId`) works for the first time and then randomly works. I really couldn't find a pattern to determine when it works or when it doesn't work.

Do you have any workaround in this situation, like, forcing its initial value in the `select` element? How would I do that?
