### ISSUE TITLE
[Preview 8] Build Razor Page Components Project 2.2 fails in Docker Container

### ISSUE THREAD

**Issue by kdcllc** [aspnet/AspNetCore#13146] opened 2019-08-14 22:42 UTC
The following project builds inside VS.NET on a windows box with the version of AspNetCore=`Version: 3.0.0-preview8-28405-07`
```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateEmbeddedFilesManifest>True</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
    <Content Update="**\*.cshtml" Pack="false" />
  </ItemGroup>
</Project>
```
In the docker container it fails.

Ended up installing DotNetCore 2.2 into docker container as follows:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview8-buster AS build

# Install .NET Core SDK
# https://github.com/aspnet/AspNetCore/issues/10833#issuecomment-499134467
ENV DOTNET_SDK_VERSION 2.2.401

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && dotnet_sha512='08e1fcafa4f898c80ff5e88eeb40c7497b4f5651af3b8ec85f65a3daa2f1509a766d833477358d3ff83d179e014034ab0c48120847ef24736c8d1a5b67fec10b' \
    && echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz
```
- https://github.com/aspnet/AspNetCore/issues/10833
- https://github.com/aspnet/AspNetCore/issues/12598

**Comment by mkArtakMSFT** [comment] 2019-08-15 16:37
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.
Razor SDK requires the related runtime to be installed.

**Closed by mkArtakMSFT** 2019-08-15 16:37 UTC
Labels: area-mvc
