### ISSUE TITLE
Blazor - Enum.GetName does not return the attribute display

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#12895] opened 2019-08-05 22:16 UTC
In latest Blazor preview Enum.GetName and Enum.GetValue return the same thing. We need a way to get the display name for an enum. For example:

`public enum FontFamilyGenericTypes { serif, [Display(Name = "san-serif")] sans_serif, cursive, fantasy, monospace }`

If the name is missing, the value would be used. 

We need this so on a razor page to generate a select control containing the enum's value/display. Where the value is the option's value and the display is what is shown to the users.

**Comment by VR-Architect** [comment] 2019-08-05 23:02
I ended up making a helper which would be a great addition to the main code. The purpose of this code is to convert the enum into value/display for use with a foreach loop in the razor file to populate a select control. It could also be used to populate other controls like a tree.

```
    public static class Helpers
    {
        public static Dictionary<string, string> GetKeyValues(Type enumType)
        {
            Dictionary<string, string> fonts = new Dictionary<string, string>();
            //var type = typeof(T);
            foreach (var field in enumType.GetFields())
            {
                var attribute = Attribute.GetCustomAttribute(field, typeof(DisplayAttribute)) as DisplayAttribute;
                if (attribute == null)
                {
                    if (field.Name != "value__")
                    {
                        fonts.Add(field.Name, field.Name);
                    }
                }
                else
                {
                    fonts.Add(field.Name, attribute.Name);
                }
            }

            return fonts;
        }
    } 
```

**Comment by Joe4evr** [comment] 2019-08-06 06:15
Basically duplicate of #12572.

**Comment by mkArtakMSFT** [comment] 2019-08-06 16:42
Thanks for contacting us, @VR-Architect.
This is not something we plan to include in the product. This would, however, be a great component from the community to provide.

**Closed by mkArtakMSFT** 2019-08-06 16:42 UTC
Labels: area-blazor
