### ISSUE TITLE
[Asp.NET Core 3.1] [TypeScript SignalR Client v3.1.0 MessagePack] "global is not defined"

### ISSUE THREAD

**Issue by cyraid** [aspnet/AspNetCore#17915] opened 2019-12-17 00:41 UTC
### Describe the bug
I find it hard to believe there's mostly docs for just Javascript, and not for Typescript! I'm attempting to use MessagePack for Typescript (@microsoft/signalr-protocol-msgpack 3.1.0) with the Typescript Client (@micorosoft/signalr 3.1.0), I'm getting a:
> global is not defined

### To Reproduce

```Typescript
    this._con = new HubConnectionBuilder()
      .withUrl("/hub")
      .withHubProtocol(new MessagePackHubProtocol())
      .configureLogging(LogLevel.Information)
      .withAutomaticReconnect()
      .build();
```

In the documentation for Javascript it states to use:
```Javascript
new signalR.protocols.msgpack.MessagePackHubProtocol()
```

But that's Javascript, and would mean I'd need to "import * as signalR from". Everything else was working without MessagePack, so it would be the hiccup right now.

### Stacktrace

```
Uncaught ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:78)
    at Module../node_modules/@microsoft/signalr-protocol-msgpack/dist/esm/MessagePackHubProtocol.js (MessagePackHubProtocol.js:1)
    at __webpack_require__ (bootstrap:78)
    at Module../node_modules/@microsoft/signalr-protocol-msgpack/dist/esm/index.js (index.js:1)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/services/hub.service.ts (hub.service.ts:1)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/pages/home/home.component.ts (home.component.ts:1)
    at __webpack_require__ (bootstrap:78)
```

### Further technical details
- ASP.NET Core 3.1
- VSCode 1.41.0

**Comment by anurse** [comment] 2019-12-18 21:01
Can you post a runnable sample that reproduces the issue? We do support TypeScript via importing the module.

**Comment by cyraid** [comment] 2019-12-19 22:33
Thank you @anurse for the assistance! Absolutely, here is a snippet:

```Typescript
//========[[ Imports ]]=======================================================//

import { Observable, Subject } from "rxjs";
import { Injectable } from "@angular/core";
import { HubConnection, HubConnectionBuilder, LogLevel } from "@microsoft/signalr";
import { MessagePackHubProtocol } from "@microsoft/signalr-protocol-msgpack";

//========[[ Global Types ]]==================================================//

export enum HubState {
  Connected,
  Disconnected
} // Enum //

//****************************************************************************//
//========[[ HubService Class
//****************************************************************************//

@Injectable({
  providedIn: "root"
}) // Injectable //
export class HubService {

  //========[[ Public Properties ]]===========================================//

  public get connected(): boolean { return this._con.connectionId !== null; }
  public get state$(): Observable<HubState> { return this._state$; }

  //========[[ Private Fields ]]==============================================//

  private _con!: HubConnection;
  private _state$: Subject<HubState> = new Subject<HubState>();

  //========[[ Public Methods ]]==============================================//

  public constructor() {

    this._con = new HubConnectionBuilder()
      .withUrl("/hub")
      .withHubProtocol(new MessagePackHubProtocol())
      .configureLogging(LogLevel.Information)
      .withAutomaticReconnect()
      .build();

    this._con.onreconnected = (id) => {
      this._state$.next(HubState.Connected);
    };

    this._con.onclose = (err) => {
      this._state$.next(HubState.Disconnected);
    };

    this._con.start();

  } // Constructor //

} // Class //
```

**Comment by anurse** [comment] 2019-12-20 16:06
That's helpful, but I don't see anything wrong in that. Also, it's not really _runnable_. The problem is we don't know what other things are going on in the project. For example, the error you produced indicated you were using WebPack, is that correct? How have you configured WebPack? Can you provide a sample that we can clone/download and actually run to observe the error?

**Comment by cyraid** [comment] 2019-12-20 16:09
Sorry I thought by the metatag it was obvious I was using Angular (ver 8) haha .. My apologies.

**Comment by cyraid** [comment] 2019-12-20 17:54
Oop.. Seems like I'm not alone.. There are [other](https://github.com/aspnet/SignalR/issues/2736) [issues](https://github.com/aspnet/AspNetCore/issues/9687) that deal with angular and MessagePack.

**Comment by anurse** [comment] 2020-01-03 19:14
Closing this as it's a duplicate of https://github.com/aspnet/AspNetCore/issues/9687

**Closed by anurse** 2020-01-03 19:14 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
