### ISSUE TITLE
Proper E2E test for blazorwasm template

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#5485] opened 2018-03-14 01:51 UTC
Now we have project templates and publishing, we should have a maximally end-to-end test that:

 * Installs the project template package
 * Creates a new project via `dotnet new`
 * Restores and builds, launches it in the dev server, verifies it works via browser automation
 * Check that live reloading works when a source file is edited (when live reloading is implemented)
 * Publishes
 * Launches it in the production server, verifies it works via browser automation

We have the majority of the infrastructure we need already (e.g., for starting up test servers and doing browser automation) but this will still be quite involved. There's prior art for installing `dotnet new` packages and using them from E2E tests in the aspnet/templating repo.

**Comment by SteveSandersonMS** [comment] 2019-11-28 10:46
@mkArtakMSFT I think this is something we'd expect to happen as part of #14866, since once the Blazor WebAssembly templates are moved to be with the other templates, we should automatically have all the infrastructure we need to add a true E2E test that includes publishing and running the published app through browser automation.

So, I'm suggesting this should be moved to be alongside #14866 in the same milestone (preview 7). @ryanbrandenburg Since that's assigned to you, do you have any concerns about the viability of adding this test? Do you want to re-assess the cost estimate? #14866 is currently flagged as `Cost: S` - should that be increased to account for adding this test too?

To make sure this doesn't get missed, I'm moving it into that milestone now, but @mkArtakMSFT please feel free to re-triage or move it further or reassign if you want!

**Comment by SteveSandersonMS** [comment] 2019-11-28 11:19
From speaking with @javiercn just now, it sounds like this might be a duplicate of work in progress by @pranavkm. Pranav, can you confirm if this is a dupe? Same for #14866 which is currently assigned to @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2019-12-02 18:56
@SteveSandersonMS I'm not sure I 100% follow. #14866 would certainly make this issue easier, but neither are dupes of the other?

**Comment by mkArtakMSFT** [comment] 2019-12-03 18:41
This is a dupe of https://github.com/aspnet/AspNetCore/issues/10269

**Closed by mkArtakMSFT** 2019-12-03 18:41 UTC
Labels: area-blazor, blazor-wasm, task
