### ISSUE TITLE
More missing descriptions

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17205] opened 2019-11-18 19:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/750513/more-missing-descriptions.html)._

---
The **Configuration** interface is missing a description as are the following classes:

- **SocketsHttpHandler**
- **WebHostBuilderSocketExtensions**
- **WebSocketAcceptControl**
- **WebSocketMiddlewareExtensions**

---
#### Visual Studio Feedback System on 9/27/2019, 00:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/27/2019, 01:32 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2019-11-18 21:32
@halter73 Not sure if this is servers, but I'll let you folks deal with it.

**Comment by Vasilisdm** [comment] 2019-11-19 22:27
I can work with that if the issue is still open.

**Comment by halter73** [comment] 2019-11-20 02:35
I don't know how the @vsfeedback bot works, but SocketsHttpHandler is in https://github.com/dotnet/corefx, so we might want @vsfeedback to open that issue there.

Also, do we typically provide class-level doc comments for extension method classes? These classes are typically never explicitly referenced, only the extension methods themselves.  Not even WebHostBuilderExtensions has these.

I don't know what WebSocketAcceptControl is referring to.

**Comment by javiercn** [comment] 2019-11-20 02:38
@halter73 This is typically a VSTS query that someone moved to GitHub for better tracking. If you open the ticket you can see who moved it.

Feel free to route this appropriately and close the issue. Maybe the VSTS issue needs to be moved to a different area.

@anurse or @mkArtakMSFT can probably help with that.

**Comment by anurse** [comment] 2019-11-20 16:28
> Also, do we typically provide class-level doc comments for extension method classes?

We should.

> SocketsHttpHandler is in [dotnet/corefx](https://github.com/dotnet/corefx), so we might want @vsfeedback to open that issue there.

Covered by https://github.com/dotnet/dotnet-api-docs/issues/1551 already.

> I don't know what WebSocketAcceptControl is referring to.

Agreed, I can't find that or what the original author was referring to by "Configuration".

Let's take this work item as adding class-level XML docs to:

* WebHostBuilderSocketExtensions
* WebSocketMiddlewareExtensions

@Vasilisdm if you're interested, feel free to submit a PR! XML doc updates are pretty easy, you just have to add the XML docs ;).

**Comment by Vasilisdm** [comment] 2019-11-20 19:35
I will try and do that!
Thanks for the update!

**Comment by anurse** [comment] 2019-11-20 20:40
Done! Looking forward to it!

**Comment by Vasilisdm** [comment] 2019-11-21 08:07
Hello there! Thanks for the assign, I will try to address it the next few days.

**Comment by halter73** [comment] 2019-11-21 21:48
@Vasilisdm If you can do [WebHostBuilderExtensions](https://github.com/aspnet/AspNetCore/blob/e2def80a0ad5143fdbd72f2051a86b2082ca92ce/src/Hosting/Hosting/src/WebHostBuilderExtensions.cs) as part of this too, that'd be great. Thanks!

**Comment by Vasilisdm** [comment] 2019-11-21 21:51
@halter73 I will try and do that.

I'll keep you posted!

**Comment by Mika-net** [comment] 2019-12-13 14:39
@Vasilisdm are you still working on this? I'm looking for an issue to pick up.

**Comment by Vasilisdm** [comment] 2019-12-13 14:46
@Mika-net feel free to grab it!
I have not addressed it due to some unexpected issues i had not the time.

**Comment by Mika-net** [comment] 2019-12-13 14:48
@Vasilisdm Thanks! Hope you are alright brother.

**Closed** 2019-12-19 19:08 UTC
Labels: Done, area-servers, good first issue, help wanted
