### ISSUE TITLE
Functionality to dynamically add eventhandlers at runtime

### ISSUE THREAD

**Issue by phillsonntag** [aspnet/AspNetCore#15214] opened 2019-10-21 09:59 UTC
### Is your feature request related to a problem? Please describe.
I'm working on a **serverside Blazor** project that has the goal to dynamically render components and add them to the view. The dynamic addition of components works fine already. 
The next step is to dynamically add eventhandlers to the specific components (e.g. 
the `@onclick=""` from this element:
`
<button @onclick="() => Callback()">Dynamic button with event handler</button>
`
). 
These attributes should only be added when the handler is set. 

### Describe the solution you'd like
The easiest solution would be to add eventhandlers to html attributes only when there is at least one callback defined.

### Additional context
This feature should be implemented to reduce the traffic and resource consumption on dynamically created components.

**Comment by javiercn** [comment] 2019-10-21 12:06
@phillsonntag thanks for contacting us.

I believe this issue is a dupe of https://github.com/aspnet/AspNetCore/issues/13181 and I believe this work has already been done (at least partially).

**Closed by javiercn** 2019-10-21 12:06 UTC
Labels: area-blazor

**Comment by phillsonntag** [comment] 2019-10-21 13:05
Does this also work without using a value?
