### ISSUE TITLE
ClientHandler seems to be duplicating the Host header

### ISSUE THREAD

**Issue by abjrcode** [aspnet/AspNetCore#7852] opened 2019-02-22 12:43 UTC
### Describe the bug
I was testing a scenario *(unit test with xUnit)* using [TestServer](https://github.com/aspnet/AspNetCore/blob/93a24b03bbda1aa0ab9b553a50b70dd36d554934/src/Hosting/TestHost/src/TestServer.cs) where I have a web host that listens to an incoming request then echos back some information about the request to the client.  
One of this information is the `Host` header.
In my case the host is listening on `proxy.com` but it doesn't really matter as I was getting the same problem regardless of the chosen domain.
I always get back the value: `proxy.com,proxy.com` so it seems the header value is duplicated twice or copied twice.

### To Reproduce
Code is roughly the following:
```c#
[Fact]
public async Task ShouldEchoBackCorrectInformation()
{
    // Build Proxy TestServer
    var proxyWebHostBuilder = new WebHostBuilder()
        .UseStartup<ProxyStartup>()
        .UseUrls("http://proxy.com:5000");
    var proxyTestServer = new TestServer(proxyWebHostBuilder);

    // Get HttpClient make a request to the proxy
    var httpClient = new HttpClient(proxyTestServer.CreateHandler());
    var response = await httpClient.GetAsync("http://proxy.com:5000/");
    var responseText = await response.Content.ReadAsStringAsync();
    responseText.Should().Contain("Hi from Host ProxyHost");
    responseText.Should().Contain("RequestUrl=http://proxy.com:5000/");
}

public class ProxyStartup
{
    app.Run(async context =>
    {
        context.Response.ContentType = "text/plain";
        await context.Response.WriteAsync($"Hi from Host ProxyHost\n");
        await context.Response.WriteAsync($"RequestUrl={context.Request.GetEncodedUrl()}\n");
        await context.Response.WriteAsync($"PathBase={context.Request.PathBase}\n");
        foreach (var requestHeader in context.Request.Headers)
        {
            await context.Response.WriteAsync(
                $"{requestHeader.Key}={string.Join(",", requestHeader.Value)}\n");
        }
    });
}
```
### Expected behavior
`Host` header to have the value `proxy.com:5000`

### Additional context
I am using JetBrains Rider and I tried to step into the code and I saw the following:
This is a snippet from decompiled code of [ClientHandler](https://github.com/aspnet/AspNetCore/blob/f06e1822f50c033504610d3ffd04cd463f8db6d4/src/Hosting/TestHost/src/ClientHandler.cs)
```c#
contextBuilder.Configure((Action<HttpContext>) (context =>
      {
        HttpRequest request1 = context.Request;
        request1.Protocol = "HTTP/" + request.Version.ToString(2);
        request1.Method = request.Method.ToString();
        request1.Scheme = request.RequestUri.Scheme;
        request1.Host = HostString.FromUriComponent(request.RequestUri);
        if (request.RequestUri.IsDefaultPort)
          request1.Host = new HostString(request1.Host.Host);
        request1.Path = PathString.FromUriComponent(request.RequestUri);
        request1.PathBase = PathString.Empty;
        PathString remaining;
        if (request1.Path.StartsWithSegments(this._pathBase, out remaining))
        {
          request1.Path = remaining;
          request1.PathBase = this._pathBase;
        }
        request1.QueryString = QueryString.FromUriComponent(request.RequestUri);
        foreach (KeyValuePair<string, IEnumerable<string>> header in (HttpHeaders) request.Headers)
          request1.Headers.Append(header.Key, (StringValues) header.Value.ToArray<string>());
        if (requestContent != null)
        {
          foreach (KeyValuePair<string, IEnumerable<string>> header in (HttpHeaders) requestContent.Headers)
            request1.Headers.Append(header.Key, (StringValues) header.Value.ToArray<string>());
        }
        if (body.CanSeek)
          body.Seek(0L, SeekOrigin.Begin);
        request1.Body = body;
        responseBody = context.Response.Body;
      }));
```
I see the `Host` header is appended too after it is set explicitly initially in the preceding code which seems to explain the issue I am facing *(partly)*
Checking the [official source code](https://github.com/aspnet/AspNetCore/blob/f06e1822f50c033504610d3ffd04cd463f8db6d4/src/Hosting/TestHost/src/ClientHandler.cs#L69) on the GitHub repository yields this:
```c#
contextBuilder.Configure(context =>
            {
                var req = context.Request;

                req.Protocol = "HTTP/" + request.Version.ToString(fieldCount: 2);
                req.Method = request.Method.ToString();

                req.Scheme = request.RequestUri.Scheme;

                foreach (var header in request.Headers)
                {
                    req.Headers.Append(header.Key, header.Value.ToArray());
                }

                if (!req.Host.HasValue)
                {
                    // If Host wasn't explicitly set as a header, let's infer it from the Uri
                    req.Host = HostString.FromUriComponent(request.RequestUri);
                    if (request.RequestUri.IsDefaultPort)
                    {
                        req.Host = new HostString(req.Host.Host);
                    }
                }

                req.Path = PathString.FromUriComponent(request.RequestUri);
                req.PathBase = PathString.Empty;
                if (req.Path.StartsWithSegments(_pathBase, out var remainder))
                {
                    req.Path = remainder;
                    req.PathBase = _pathBase;
                }
                req.QueryString = QueryString.FromUriComponent(request.RequestUri);

                if (requestContent != null)
                {
                    foreach (var header in requestContent.Headers)
                    {
                        req.Headers.Append(header.Key, header.Value.ToArray());
                    }
                }

                if (body.CanSeek)
                {
                    // This body may have been consumed before, rewind it.
                    body.Seek(0, SeekOrigin.Begin);
                }
                req.Body = new AsyncStreamWrapper(body, () => contextBuilder.AllowSynchronousIO);

                responseBody = context.Response.Body;
            });
```
And here the order looks *CORRECT*

This is where I get confused. I don't really know if I am doing something wrong or the compiler is re-ordering the code or is it Rider's decompiler fault or something else completely?
Thank you for your help

**Comment by Eilon** [comment] 2019-02-22 19:00
Tagging @javiercn

**Comment by javiercn** [comment] 2019-02-22 19:16
@Eilon You are looking for @Tratcher. 😄

**Comment by Tratcher** [comment] 2019-02-22 21:12
What version are you using? 2.2?

**Comment by abjrcode** [comment] 2019-02-23 15:46
> What version are you using? 2.2?

latest preview at the time of this writing.
I think it was 3.0 preview-3

**Comment by Eilon** [comment] 2019-02-25 05:27
@javiercn - I wasn't sure if it's maybe some of the custom stuff that TestServer does.

**Comment by damianh** [comment] 2019-02-25 13:24
Already fixed here? https://github.com/aspnet/AspNetCore/commit/3e0b689ac2ea72a8dee81f8ae3a349610ac1fb0c#diff-22356e5b7de1c9d8b3046bd1c6418043R81

**Comment by Tratcher** [comment] 2019-02-25 16:07
Hmm, that PR went into 2.2 https://github.com/aspnet/Hosting/pull/1483

**Comment by Tratcher** [comment] 2019-02-25 16:13
Nevermind, that PR/issue was labeled 2.2, but for some reason didn't make it in until 3.0.

**Comment by abjrcode** [comment] 2019-02-26 09:23
Hmm I am not sure it is the same problem?

**Comment by damianh** [comment] 2019-02-26 11:17
Prior to the PR #1483 the Host header was copied from the `request.RequestUri` and set to `req.Host` here: https://github.com/aspnet/AspNetCore/blob/82ccf4f06e749d2044f3adb88e870b431341274f/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs#L75

Little bit further down, _all_ the headers were _appended_ from the `request`: 

https://github.com/aspnet/AspNetCore/blob/82ccf4f06e749d2044f3adb88e870b431341274f/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs#L90-L93

If there was a Host header explicitly defined in `request.Headers` (usually it's missing), and because the operation was an append, you'd get duplicate Host headers in `req.Headers`.

**Comment by Tratcher** [comment] 2019-03-07 18:37
Confirmed, the given test is passing on 3.0. Closing as a duplicate.

**Closed by Tratcher** 2019-03-07 18:37 UTC
Labels: area-hosting, bug
