### ISSUE TITLE
Running "ng build" manually causes VS to stop recognizing client side file changes and breaks angular-cli hot updates

### ISSUE THREAD

**Issue by AlejandroFlorin** [aspnet/AspNetCore#5229] opened 2018-08-03 18:49 UTC
For an angular project, if you manually run ng build in a command prompt, it populates the dist folder. For some reason, this causes visual studio to stop recognizing changes to any client side files (css, scss, ts, html) and the hot updates for debugging stops working.

The work around is to delete the dist folder. 
https://stackoverflow.com/questions/50867385/development-server-hot-updates-not-working

I'm using the latest template and Angular 6.1.1

**Comment by westerncj** [comment] 2019-01-07 15:21
I'm running into this same issue using the new angular 6 template. Deleting the dist folder isn't fixing the issue for me. Are there any other work arounds?

**Comment by mkArtakMSFT** [comment] 2019-08-08 18:00
Thanks for contacting us.
@ryanbrandenburg I assume this is because of the issue, where when the `Dist` folder is created, that's being used during development too. Wasn't this fixed as part of some other issue just recently?

**Comment by ryanbrandenburg** [comment] 2019-08-09 21:06
Yeah, this seems like a duplicate of https://github.com/aspnet/AspNetCore/issues/11797.

**Closed by ryanbrandenburg** 2019-08-09 21:06 UTC
Labels: area-mvc, bug, feature-spa
