### ISSUE TITLE
Some packages don't get published on myget

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#6322] opened 2019-01-03 01:03 UTC
See this trace:

http://aspnetci/viewLog.html?buildId=609574&buildTypeId=AspNetCore_Publish&tab=buildLog&_focus=704

**Comment by davidfowl** [comment] 2019-01-03 01:03
cc @natemcmaster

**Comment by natemcmaster** [comment] 2019-01-03 01:20
Duplicate of https://github.com/aspnet/AspNetCore-Internal/issues/1459

**Closed by natemcmaster** 2019-01-03 01:20 UTC
