### ISSUE TITLE
Problem overriding attributes when Splatting

### ISSUE THREAD

**Issue by Discovery-support** [aspnet/AspNetCore#14830] opened 2019-10-08 16:24 UTC
Attempting to override an attribute causes the program to not initialise, or if using CaptureUnmatchedValues, wipes all the predetermined attributes and only inserts the value you give as an argument

This is with v3.0.0-preview9.19465.2

I have created two razor files 'SplatWithcapture' and 'SplatNocapture'

`@* <SplatWithcapture />    Declares [Parameter(CaptureUnmatchedValues=true)] on InputAttributes *@
 @* <SplatNocapture />      Declares [Parameter] on InputAttributes *@`

and the file calls.txt shows 6 different tests I have run along with the results I get.

[calls.txt](https://github.com/aspnet/AspNetCore/files/3703473/calls.txt)

[SplatWithcapture.txt](https://github.com/aspnet/AspNetCore/files/3703424/SplatWithcapture.txt)
[SplatNocapture.txt](https://github.com/aspnet/AspNetCore/files/3703425/SplatNocapture.txt)

**Comment by mkArtakMSFT** [comment] 2019-10-08 16:37
Thanks for contacting us, @Discovery-support.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by Discovery-support** [comment] 2019-10-09 09:35
Done
https://github.com/Discovery-support/splatting

**Comment by Bluebeerd** [comment] 2019-10-09 10:04
Sorry, proper link is

https://github.com/Bluebeerd/splatting

**Comment by pranavkm** [comment] 2019-10-09 16:18
Thanks for sharing the repro app. @javiercn could you have a look?

**Comment by Discovery-support** [comment] 2019-10-09 18:22
@javiercn  All code issues are present in the **client side Blazor index.razor**.  Some code is **rem'ed** so that the project will execute and exhibit html rendering issues.  The rem'ed code will need to unrem'ed to expose further critical issues that prevent program initialization.

**Comment by javiercn** [comment] 2019-10-09 18:33
Thanks for the repro,

SplatWithNoCapture throwing an exception when you try to pass additional parameters to it presents the expected behavior. Unless there is a parameter that captures all unmatched attributes the behavior of the component is to throw if there is one or more attributes that don't match the component parameters.

SplatWithCapture does not have a max length property when passing additional parameters to it because we don't try to merge the additional attributes in the existing parameter dictionary, that would be problematic when multiple calls to setparametersasync happened. A component parameter that captures unmatched attributes will always be set with a dictionary including the unmatched attributes for that render.

If you want to provide some default values you can technically achieve this by doing
```
<input @attributes="InputAttributes" maxlength="10" type="text" />
```

Any value passed through `@attributes` should always override any of the default values set in the element itself.

However, I've tested this with the RTM bits and there seems to be a bug here where we don't correctly override the values with those included in attributes. To workaround this yourself you can do something like this
```
<input @attributes="GetAttributes()InputAttributes" maxlength="10" type="text" />

@code{
    public IDictionary<string,object> GetAttributes() 
    {
        var result = new Dictionary<string,object>(InputAttributes);
        result.TryAdd("type", "text");
        result.TryAdd("maxlength", "10");
        return result;
    }
}
```

@danroth27 thoughts on including this for 3.1?

/cc @rynowak

**Comment by rynowak** [comment] 2019-10-09 21:19
> Any value passed through @attributes should always override any of the default values set in the element itself.

What's the actual bug, can you post the complete code sample that you think has a problem?

**Comment by javiercn** [comment] 2019-10-09 22:17
`<input @attributes="InputAttributes" maxlength="10" type="text" />`

https://github.com/Bluebeerd/splatting/blob/b6b2db76e722db9742f7a228532b4677d17a6590/BlazorApp_090919/Client/Shared/SplatWithcapture.razor#L1

Replace the input attribute in the component above with the one above and remove the dictionary initialization code.

And invoke it like `<SplatWithcapture type="password" />`

I would expect the output to be
`<input @attributes="InputAttributes" maxlength="10" type="password" />`

**Comment by rynowak** [comment] 2019-10-09 22:59
I wouldn't expect to see `@attributes` appear in the render frames or DOM.

**Comment by Bluebeerd** [comment] 2019-10-10 10:17
`
@javiercn  commented

> <input @attributes="GetAttributes()InputAttributes" maxlength="10" type="text" />
> 
> @code{
>     public IDictionary<string,object> GetAttributes() 
>     {
>         var result = new Dictionary<string,object>(InputAttributes);
>         result.TryAdd("type", "text");
>         result.TryAdd("maxlength", "10");
>         return result;
>     }
> }
> ```
> 
> @danroth27 thoughts on including this for 3.1?
> 
> /cc @rynowak


The above workaround you suggested would not compile, but I have attempted to refactor it as follows: 
`<input @attributes="GetAttributes()" />

@code {
    [Parameter(CaptureUnmatchedValues=true)]
    public Dictionary<string, object> InputAttributes { get; set; }
    public IDictionary<string, object> GetAttributes()
    {
        var result = new Dictionary<string, object>(InputAttributes); 
  // **InputAttributes always results in NULL and an exception is thrown!**

        result.TryAdd("type", "text");
        result.TryAdd("maxlength", "10");
        return result;
    }
}

**Comment by javiercn** [comment] 2019-10-10 10:23
@Bluebeerd I hand-coded the answer on the github comment.
```
var result = InputAttributes != null ? new Dictionary<string,object>(InputAttributes) : new Dictionary<string,object>();
```

should do it.

**Comment by javiercn** [comment] 2019-10-10 10:26
> I wouldn't expect to see `@attributes` appear in the render frames or DOM.

I was typing on my phone. Other than attributes, does the expected output match your expectation? because the reality is that it shows `<input maxlength="10" type="text" />` so no override seems to be taking place.

**Comment by javiercn** [comment] 2019-10-11 16:50
@rynowak It works fine,

I was missing a detail, the order in which you put the attributes matter. It was not part of the docs, but @danroth27 will open an issue to get it added.

@Bluebeerd In essence, the most right attribute wins, so to achieve your scenario you simply need to define your component as shown below.

```razor
<input maxlength="10" type="text" @attributes="InputAttributes" />

@code {
    [Parameter(CaptureUnmatchedValues=true)]
    public Dictionary<string, object>
    InputAttributes { get; set; }
}
```

Closing this issue as there's no more action for us to take.

**Closed by javiercn** 2019-10-11 16:50 UTC
Labels: area-blazor, bug
