### ISSUE TITLE
Error if input tags are not closed in Blazor apps

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10498] opened 2019-05-23 19:40 UTC
![image](https://user-images.githubusercontent.com/1874516/58281371-dde65f80-7d57-11e9-8192-1bf6aa524ef3.png)

**Comment by NTaylorMullen** [comment] 2019-05-23 21:09
In TagHelper land we can accomplish the fix for this by specifying a "WithoutEnd" TagStructure. When we generate components if they apply to `input` tags etc. we should generate them without end tag.

**Comment by GeertvanHorrik** [comment] 2019-06-06 13:08
Same issue with this markup:

```
@if (IsSplitButton)
{
    <div class="@Class">
        @SplitButtonItems
}

        some content here

@if (IsSplitButton)
{
    </div>
}
```

**Comment by NTaylorMullen** [comment] 2019-06-06 21:04
@GeertvanHorrik that code is by design. We don't allow having partial HTML tags split among different code blocks.

**Comment by JosKrause** [comment] 2019-08-08 00:09
Does this new rule also apply to the `<option>` element?

**Comment by NTaylorMullen** [comment] 2019-08-08 17:03
> Does this new rule also apply to the `<option>` element?

The rule also applies to the `option` element. Essentially any [Void Elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) as defined by the HTML spec are allowed to not have end tags in C# blocks. All others must. This rule behaves the same as non-Blazor apps/files.

**Comment by mkArtakMSFT** [comment] 2019-11-01 16:05
@rynowak should this be closed as `fixed` ?

**Comment by rynowak** [comment] 2019-11-10 21:36
Fixed!

**Closed by rynowak** 2019-11-10 21:36 UTC
Labels: Done, PRI: 2 - Preferred, Tooling, area-blazor, bug, cost: XS
