### ISSUE TITLE
asp.net core 3 empty layout kestrel

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#10303] opened 2019-05-16 20:08 UTC
get a ERR_EMPTY_RESPONSE  Error message in Chrome running in Kestrel (iis express works)

```
@page
@model perf3.Pages.speedModel
@{
    Layout = null;
}

<!DOCTYPE html>
```

looking with fiddler- missing everything  like HTML Body ect

**Comment by anurse** [comment] 2019-05-16 21:25
Can you provide a full sample project that reproduces the issue? Your sample page doesn't have an HTML body and has a `<!DOCTYPE html>` so it seems entirely expected that you wouldn't be seeing a body tag...

**Comment by hannespreishuber** [comment] 2019-05-17 04:16
ist just simple page. Confusing works with iis express and not with kestrel command line hosted (started from Visual Studio 2019 )
`@page
@model perf3.Pages.demoModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>speed</title>
</head>
<body>
</body>
</html>`

**Comment by anurse** [comment] 2019-05-17 20:51
> it is some how related with Response.write

Yes, that is what's causing your issue. The page is rendered **after** the `OnGetAsync` method completes, so what the browser is getting is this:

```
[your elapsed time]
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>speed</title>
</head>
<body>
</body>
</html>
```

This is not valid HTML so browsers may have problems with it.

**Comment by hannespreishuber** [comment] 2019-05-18 15:05
makes sense, but why not with iisexpress?

**Comment by anurse** [comment] 2019-06-11 00:12
> makes sense, but why not with iisexpress?

That I'm not sure about. Closing though since the behavior is invalid and would be expected to produce rendering issues in browsers.

**Closed by anurse** 2019-06-11 00:12 UTC
Labels: area-servers, waiting
