### ISSUE TITLE
Authorization failed in Blazor server-side app

### ISSUE THREAD

**Issue by romandres** [aspnet/AspNetCore#13124] opened 2019-08-14 12:39 UTC
SDK: dotnet-sdk-3.0.100-preview8-013656-win-x64
IDE: Visual Studio 2019 16.3 Preview 2.0
OS: Windows 10 1903 (18362.1.amd64fre.19h1_release.190318-1202)

Using Windows Authentication, authorization in Blazor server-side app always results in NotAuthorized when using debug launch command 'Project' instead of 'IISExpress'.

Steps to reproduce using a new app:
1. Create a new Blazor App in Visual Studio (Server-side, Windows Authentication)
2. Debug the app using launch command 'IISExpress' -> The LoginDisplay component displays the Windows Username
3. Debug the app using launch command 'Project' -> The LoginDisplay component displays nothing. The log contains this message: [Microsoft.AspNetCore.Authorization.DefaultAuthorizationService] Authorization failed.

Before updating to .NET Core 3.0 preview8 I was using preview7 where this was not an issue.
I have an existing app which I migrated from preview7 to preview8. The MVC part of the app and the authorization works while the Blazor server-side part always results in NotAuthorized if I don't use IISExpress to debug.

**Comment by mkArtakMSFT** [comment] 2019-08-14 16:14
Thanks for contacting us, @romandres.
@SteveSandersonMS don't we have a CTI scenario validating this daily?

**Comment by SteveSandersonMS** [comment] 2019-08-22 15:46
@mkArtakMSFT No, we only have a CTI scenario covering the Identity auth case (not Windows auth).

In any case, as far as I'm aware, Windows Authentication is not expected to work by default when hosting directly on Kestrel, since Kestrel doesn't support it. I checked, and the default MVC site template with Windows authentication also doesn't work if you run it directly on Kestrel instead of IISExpress.

The fact that Kestrel doesn't support Windows Authentication directly is [mentioned here](https://github.com/aspnet/AspNetCore.Docs/issues/2711#issuecomment-283485115), though I'm unsure where this fact is covered in official documentation.

It *is* possible to [host ASP.NET Core on HTTP.sys directly](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-3.0#how-to-use-httpsys) and [then enable Windows authentication via HTTP.sys](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#httpsys), which should work the same with server-side Blazor. But setting it up is nontrivial as per docs.

@HaoK Do you agree with this diagnosis? Is there anything I've missed?

**Comment by pranavkm** [comment] 2019-08-22 16:53
Closing this as by design.

**Closed by pranavkm** 2019-08-22 16:53 UTC
Labels: area-blazor, question
