### ISSUE TITLE
~6000 wasm files generated in solution explorer

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore#13809] opened 2019-09-08 08:03 UTC
I have create my wasm app hosted by asp.net core in VS2019 Prev using `dotnet new blazorwasm --hosted`.

When I **stop** the app after a couple of seconds by closing the browser, VS becomes unresponsive for a longer period of time because because about 6000 wasm files get generated in solution explorer again.

**Steps to reproduce** 
1.) `dotnet new blazorwasm --hosted`
2.) Run the app from VS using `F5`
3.) Close the app:
**It only happens, when I close the browser (not when hitting STOP in VS).** 

Usually in ASP.NET also VS stops debugging instantly.
SO when I close my browser, VS does not stop and it is not stoppable until it finishes to generate these wasm files all over again (it looks like this in solution explorer)

Don't know if it's an IDE problem or yours.

**Comment by Legends** [comment] 2019-09-08 20:44
Here is a [mp4 file](https://drive.google.com/file/d/1FPGpUb9JBY0xFWJaQ3zi9hlAQQsztRaL/view?usp=sharing) on my google drive that demonstrates the issue.

SO usually when hit the close "x" button of the browser, VS stops debugging instantly, but here I got this issue.

**Comment by GerardSmit** [comment] 2019-09-09 09:39
Related or duplicate of https://github.com/aspnet/AspNetCore/issues/13803.

**Comment by Legends** [comment] 2019-09-09 19:23
@GerardSmit 	
In my case VS doesn't crash and my reproduction steps are bit different,
but it shows the same problem indeed.

**Comment by mkArtakMSFT** [comment] 2019-09-10 16:54
Thanks for contacting us, @Legends.
We don't support F5 debugging for Blazor WASM projects at the moment. We are going to enable support in the future.

**Closed by mkArtakMSFT** 2019-09-10 16:54 UTC
Labels: area-blazor

**Comment by Legends** [comment] 2019-09-11 07:02
What kind of debugging do you support currently? Thanks.

**Comment by RemiBou** [comment] 2019-09-11 07:03
You can find the doc about it here :

https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0
