### ISSUE TITLE
Easy way to log request and response bodies

### ISSUE THREAD

**Issue by Mikilll94** [aspnet/AspNetCore#13217] opened 2019-08-17 17:23 UTC
### Is your feature request related to a problem? Please describe.
I am trying to build a logging mechanism in my app which logs every request and response. There are many tutorials on how to do this. I think the most popular is:

https://exceptionnotfound.net/using-middleware-to-log-requests-and-responses-in-asp-net-core/

Unfortunately, I think that logging request and response bodies is too complicated because both request body and response body are Streams instead of strings. Just look at this code in this article. To achieve just simple logging we have to write a lot of difficult code. This also causes other problems which are related to Streams, i.e. Large Object Heap.

Many of these problems are described below this article in comments. 

### Describe the solution you'd like
I'd like to have an easy way to log request and response bodies in ASP.NET Core.
Solutions:
1. Request and response bodies should be strings instead of streams (don't know if this is possible)
2. Give a user some method to get request and response body as a string.

### Additional context
Almost every app needs some way to log events happening in it. Middleware in ASP.NET Core seems the best place to include logging. Unfortunately, there is no official or approved solution on how to perform logging request and responses in ASP.NET Core.

**Comment by davidfowl** [comment] 2019-08-17 17:26
Dupe of https://github.com/aspnet/AspNetCore/issues/3700

**Closed by davidfowl** 2019-08-17 17:26 UTC
