### ISSUE TITLE
Second part of #13846 that was missed (Add queue name to HttpSysOptions) - add option to connect to existing Q

### ISSUE THREAD

**Issue by bkatms** [aspnet/AspNetCore#14138] opened 2019-09-19 08:45 UTC
Original request for 'Add queue name to HttpSysOptions #13846' was checked-in but missed the second part which was to support the ability to connect to an existing Q.  This is to add the missing behavior.  Code is available and branch pushed.

**Comment by bkatms** [comment] 2019-09-19 08:52
I have a fix for this

**Comment by Tratcher** [comment] 2019-09-19 14:45
Isn't this is a duplicate of https://github.com/aspnet/AspNetCore/issues/5866?

**Comment by bkatms** [comment] 2019-09-19 15:00
Actually it was intended to be a part of #13846 that got missed.

I have no problem in how you want to deliver it, just that we need it.

It sounded on the other thread you did not want to deliver it so I need to look for a workaround.

However, if you want to do it that is great.

We can actually configure in our own management process if that helps.

**Comment by Tratcher** [comment] 2019-09-19 15:08
Closing as a duplicate. We can re-evaluate #5866 to see if it's viable for 3.1. The biggest reason we did not pursue it in the past was lack of customer demand 😁

**Closed by Tratcher** 2019-09-19 15:08 UTC
Labels: area-servers, servers-httpsys
