### ISSUE TITLE
Unable to run netcoreapp2.1 referencing Microsoft.AspNetCore.All 2.1.7 after installing .NET Core SDK 2.2

### ISSUE THREAD

**Issue by wdolek** [aspnet/AspNetCore#7565] opened 2019-02-14 08:36 UTC
### Describe the bug
I have application with following `.csproj`:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <!-- ... -->
  </PropertyGroup>

  <!-- ... -->
</Project>
```

After installing .NET Core SDK 2.2 and doing update of Visual Studio 2017 to 15.9.7, I'm not able to run my app when referencing `Microsoft.AspNetCore.All` `2.1.7`, getting runtime exception:

```
System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.AspNetCore, Version=2.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
```

When I change version to `2.1.8`, app works, however application is broken to anyone else in team who has not performed SDK/runtime update yet.

I have already tried to configure `global.json` or run app with command `dotnet run -f netcoreapp2.1 --project ...` without any luck.

- [.NET Core 2.1.8 Update - January 08, 2019](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.8/2.1.8.md#changes-in-218)
- [AspNetCore v2.1.8 changelog](https://github.com/aspnet/AspNetCore/releases/tag/v2.1.8)

### To Reproduce
1. Install SDK 2.1
2. Create web app using `netcoreapp2.1`
3. Reference `Microsoft.AspNetCore.All` `2.1.7`
4. Update SDK to 2.2 (additionally update VS to 15.9.7, not sure whether that brought anything into system)
5. Try run app

### Expected behavior
App works normally as it worked before update.

### Additional context

```
$ dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
2.1.401 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.2.103 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
```

```
$ dotnet --version
2.2.104

$ dotnet run -f netcoreapp2.1 --project X
C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(153,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.All' specified a Version of `2.1.7`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [... .csproj]

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore, Version=2.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ... .Program.BuildWebHost(String[] args)
   at ... .Program.Main(String[] args) in ...\Program.cs:line 9
```
(apparently `-f` has no effect)

With `global.json`:
```
$ echo '{ "sdk": { "version": "2.1.504" } }' > global.json

$ dotnet --version
2.1.504

$ dotnet run -f netcoreapp2.1 --project X
Using launch settings from X\Properties\launchSettings.json...

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore, Version=2.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ... .Program.BuildWebHost(String[] args)
   at ... .Program.Main(String[] args) in ...\Program.cs:line 9
```

```
PS> ([System.Reflection.Assembly]::LoadFile("C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.1.7\Microsoft.AspNetCore.dll")).FullName
Microsoft.AspNetCore, Version=2.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

**Comment by dweggemans** [comment] 2019-02-14 09:56
I just experienced the same thing after installing SDK 2.2. The workaround updating the reference to 2.1.8 works like a charm.

**Comment by Gleaken** [comment] 2019-02-14 12:39
Yes, workaround with updating the reference to 2.1.8 works

**Comment by Eilon** [comment] 2019-02-14 17:00
@natemcmaster - this is the known issue that was discovered yesterday, yes? Close as dup?

**Comment by natemcmaster** [comment] 2019-02-14 17:01
Closing as a duplicate of #7546.

@wdolek the recommended way to use Microsoft.AspNetCore.App is to remove the `Version` attribute. But if you still need it for some reason, upgrade the version to 2.1.8.

**Closed by natemcmaster** 2019-02-14 17:01 UTC
Labels: area-platform

**Comment by wdolek** [comment] 2019-02-14 18:58
@natemcmaster Hi! Thanks for taking care of this. Yet I still don't really understand, _why_ - I _just_ installed SDK 2.2 along other older SDKs. I never had intention (in this particular project) to upgrade `Microsoft.AspNetCore.All` dependency nor upgrading target to `netcoreapp2.2`.
