### ISSUE TITLE
Have url_rewrite middleware resolve server variables from IIS when running ANCM in-proc

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#6013] opened 2018-10-16 21:42 UTC

**Comment by mderriey** [comment] 2019-05-06 20:04
Hi @muratg, @shirhatti and @jkotalik 👋

I'm keen to give this one a shot, but I'd appreciate some pointers on how to do this.
How does IIS expose server variables?

Thanks 🙇‍♂️

**Comment by mderriey** [comment] 2019-05-06 23:40
I've found [`IServerVariableFeature`](https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IIS/src/IServerVariableFeature.cs) and the associated [`GetIISServerVariable`](https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IIS/src/HttpContextExtensions.cs) extension method.

The current thinking is to create a new `PatternSegment` that gets values from the `IServerVariableFeature` while allowing fallback on the existing implementation if we're not using in-proc hosting.

Please let me know if that sounds about the direction you'd like this to take.

Cheers 🙏

**Comment by jkotalik** [comment] 2019-05-06 23:45
Yeah, that would be the right direction to take this!

**Comment by mderriey** [comment] 2019-05-15 23:29
I'm surprised the issue isn't closed given the associated PR was merged and the PR description mentions "Addresses #<number>".

Is that because I don't have permissions to close the issue?

**Comment by anurse** [comment] 2019-05-15 23:42
"Addresses" doesn't close the attached issue, you have to use "Closes" or "Fixes" :)

**Comment by anurse** [comment] 2019-05-15 23:42
But yeah, it's also because you don't have the permissions :). Thanks for this contribution!

**Comment by anurse** [comment] 2019-05-15 23:43
Fixed in https://github.com/aspnet/AspNetCore/pull/10022 (https://github.com/aspnet/AspNetCore/commit/4a2bd2adbf74b316f01eb062de3e83261562801d)

**Closed by anurse** 2019-05-15 23:42 UTC
Labels: area-middleware, up-for-grabs
