### ISSUE TITLE
User Secrets not supported by Microsoft.NET.Sdk.Razor project types - Razor Components

### ISSUE THREAD

**Issue by EdCharbeneau** [aspnet/AspNetCore#7360] opened 2019-02-07 18:31 UTC
### Describe the bug
When using the project type as defined in .csproj `<Project Sdk="Microsoft.NET.Sdk.Razor">` the Manage User Secrets dialog is missing from Visual Studio.

### To Reproduce
1. Using ASP.NET Core 3.0 preview-2
2. Choose File > New Web > Razor Components
3. In Solution Explorer right click <projectname>.App
4. Manage User Secrets is missing
5. To see proper functionality. Repeat these steps with the <projectname>.Server and the option is available

### Expected behavior
Ability to manage user secrets for Razor Components (RC). Since RC run in the context of the server it's useful to have user secrets available. We are currently using this to supply a connection string to EF.

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

**Comment by enetstudio** [comment] 2019-02-08 16:57
EdCharbeneau: Since RC run in the context of the server it's useful to have user secrets available

But you yourself says: Repeat these steps with the .Server and the option is available

Correct me if I am wrong... You want the User Secrets feature be available in  .App, right ?

**Comment by EdCharbeneau** [comment] 2019-02-08 19:49
Yes. Sorry that was confusing. I meant to say, repeat these steps for the Server project to see the properly working menu dialog.

**Comment by mkArtakMSFT** [comment] 2019-02-11 20:54
Thanks for your feedback, @EdCharbeneau.
We're closing this issue as the behavior discussed is by design. The UserSecrets management is available to Server projects only. If you'd like to read those secrets at runtime from the .App project, you'll have to take a dependency on the `IConfiguration` from the DI and read the necessary values.

**Closed by mkArtakMSFT** 2019-02-11 20:54 UTC
Labels: area-mvc

**Comment by EdCharbeneau** [comment] 2019-02-12 02:19
So Razor Components are supposed to have secrets that are easily managed?

**Comment by StevenTCramer** [comment] 2019-02-12 03:03
The dialog doesn't show up for console apps either.  @mkArtakMSFT you mention "by design" but where is that discussion?  I thought the key point of "user secrets" was to keep these secrets out of source code.
So I don't understand why the project type even matters?  Maybe we just don't understand the reasoning?

**Comment by EdCharbeneau** [comment] 2019-02-12 18:07
To elaborate even more:

Given that services are defined in <solution>.App.Startup

https://github.com/telerik/ui-for-blazor-examples/blob/master/TelerikBlazor/TelerikBlazor.App/Startup.cs#L13

Why would there be no support for managing secrets?
