### ISSUE TITLE
Blazor: System.DllNotFoundException: MonoPosixHelper

### ISSUE THREAD

**Issue by codec-abc** [aspnet/AspNetCore#6668] opened 2019-01-14 17:14 UTC
### Describe the bug
I am developing a small app with blazor where a 3rd party ([ExcelDataReader](https://github.com/ExcelDataReader/ExcelDataReader) - [Nuget page](https://www.nuget.org/packages/ExcelDataReader/)) library have to decompress a zip file in memory. I encountered an error and I managed to reduce the problem to 2 lines of codes (see below).

### To Reproduce
1. Using this version of Blazor 0.7.0
2. Run this code: A simple Blazor page with an overrided OnInitAsync with the following code:

```cs
protected override async Task OnInitAsync()
{
    var stream = new System.IO.MemoryStream();

    DeflateStream compressionStream = 
        new System.IO.Compression.DeflateStream(stream, CompressionMode.Compress);
}
```

will result in the following exception being thrown:

```
System.DllNotFoundException: MonoPosixHelper
at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CreateZStream(System.IO.Compression.CompressionMode,bool,System.IO.Compression.DeflateStreamNative/UnmanagedReadOrWrite,intptr)
at System.IO.Compression.DeflateStreamNative.Create (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean gzip) <0x1ff7158 + 0x00088> in <7c5c7bfffd57465d85cd5b632c22c41b>:0
at System.IO.Compression.DeflateStream..ctor (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen, System.Boolean gzip) <0x1ff3890 + 0x0006e> in <7c5c7bfffd57465d85cd5b632c22c41b>:0
at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionMode mode) <0x1ff3780 + 0x0001c> in <7c5c7bfffd57465d85cd5b632c22c41b>:0
at BlazorApp1.Pages.Index.OnInitAsync () <0x1ff3350 + 0x00030> in <9934c1196e1f4be5a4cb948658302568>:0 
```

### Expected behavior
No exception and no dependencies to a native dll.

### Additional context
```
$ dotnet --info
SDK .NET Core (reflétant tous les global.json) :
 Version:   2.1.502
 Commit:    c74ce8f29f

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

my csproj file

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.7.0" PrivateAssets="all" />
    <PackageReference Include="ExcelDataReader" Version="3.4.2" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.1" />
    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.7.0" />
  </ItemGroup>

</Project>
```

**Comment by mkArtakMSFT** [comment] 2019-01-14 23:01
Thanks for contacting us, @codec-abc.
@SteveSandersonMS, can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment] 2019-01-14 23:12
Thanks for reporting this, @codec-abc! As it happens, it's a duplicate of https://github.com/aspnet/Blazor/issues/445, with the underlying issue being tracked for resolution at https://github.com/mono/mono/issues/8216

**Closed by SteveSandersonMS** 2019-01-14 23:12 UTC
Labels: area-mvc, investigate
