### ISSUE TITLE
Controller not hitting and no response from server, Browser keep loading 

### ISSUE THREAD

**Issue by rsmmukesh** [aspnet/AspNetCore#9019] opened 2019-04-03 06:52 UTC
Hi,
Controller not hitting and no response from server, Browser keep loading .

To reproduce the issue, just download the attached application, then run the application. then you will get home page, it contains a text box and file uploader. Just click submit button. controller will not hit. 

Then problem is when i use file , controller is hitting if i remove the below code from the BModel class
`public IFormFileCollection myfile
        {
            get; set;
        }`

[WebApplication2.zip](https://github.com/aspnet/AspNetCore/files/3037200/WebApplication2.zip)

**Comment by danroth27** [comment] 2019-04-03 21:17
Is there an exception in the ASP.NET Core logs?

This might be a known issue with model binding. @dougbu can you confirm?

**Comment by rsmmukesh** [comment] 2019-04-04 06:14
No exceptions.

**Comment by dougbu** [comment] 2019-04-04 06:14
@danroth27 yes, this is a duplicate of #4802 The fix was in our [3.0.0 Preview 3 release](https://github.com/aspnet/AspNetCore/releases/tag/v3.0.0-preview3-19153-02)

@rsmmukesh thank you for your feedback. We're closing this issue as we think this is fixed in our working code base. Would you be able to try [3.0.0 Preview 3](https://github.com/aspnet/AspNetCore/releases/tag/v3.0.0-preview3-19153-02) and see if the issue is resolved for you? Please reopen this issue if not.

**Closed by dougbu** 2019-04-04 06:14 UTC
Labels: area-mvc, investigate

**Comment by ByEBA** [comment] 2019-04-06 14:34
> @danroth27 yes, this is a duplicate of #4802 The fix was in our [3.0.0 Preview 3 release](https://github.com/aspnet/AspNetCore/releases/tag/v3.0.0-preview3-19153-02)
> 
> @rsmmukesh thank you for your feedback. We're closing this issue as we think this is fixed in our working code base. Would you be able to try [3.0.0 Preview 3](https://github.com/aspnet/AspNetCore/releases/tag/v3.0.0-preview3-19153-02) and see if the issue is resolved for you? Please reopen this issue if not.


Why don't you edit the 2.2.x version of this topic?

**Comment by dougbu** [comment] 2019-04-06 18:14
> Why don't you edit the 2.2.x version of this topic?

@ByEBA is your question about backporting the #4802 fix? If yes, please see my [comment](https://github.com/aspnet/AspNetCore/issues/4802#issuecomment-476316779) in that issue:
> @Plasma we do not have plans to backport this fix to the release branches because Model Binding changes have a history of causing different problems. We have not had reports of new issues in the 3.0 releases, but…
