### ISSUE TITLE
Test failure: _3_Build

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3723] opened 2018-10-25 19:31 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=35365) with the following error:

```
System.InvalidOperationException : Command dotnet restore /warnaserror --no-cache   returned exit code 1

  Restoring packages for C:\Users\VssAdministrator\AppData\Local\Temp\tmpEDC5.tmp\web\None\none\web.csproj...
C:\Users\VssAdministrator\AppData\Local\Temp\tmpEDC5.tmp\web\None\none\web.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Razor.Design (>= 2.2.0-rtm-35542)' for '.NETCoreApp,Version=v2.2'.


```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment] 2018-10-25 19:31
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-25 19:31
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 87 failures [with about the same error](https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=35365) on release/2.2 at 6:15:37 PM:
- _5_Run
- _4_BuildIncremental
- _4_BuildIncremental
- _2_RestoreIncremental
- _3_Build
- _4_BuildIncremental
- _8_Exec
- _2_RestoreIncremental
- _4_BuildIncremental
- _7_PublishIncremental
- (And 77 more test failures in this build)

**Comment by mkArtakMSFT** [comment] 2018-10-25 20:36
@pranavkm, can you please look into this? Seems like related to Razor Design.

**Comment by pranavkm** [comment] 2018-10-25 20:56
@JunTaoLuo seems like the same issue that we were discussing earlier:

```
2018-10-25T18:19:41.7400920Z C:\Users\VssAdministrator\AppData\Local\Temp\tmp6F8D.tmp\react\None\none\react.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Razor.Design (>= 2.2.0-rtm-35542)' for '.NETCoreApp,Version=v2.2'.
2018-10-25T18:19:41.7401142Z C:\Users\VssAdministrator\AppData\Local\Temp\tmp6F8D.tmp\react\None\none\react.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App (>= 2.2.0-rtm-27024-02)' for '.NETCoreApp,Version=v2.2'.
2018-10-25T18:19:41.7401334Z C:\Users\VssAdministrator\AppData\Local\Temp\tmp6F8D.tmp\react\None\none\react.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App (>= 2.2.0-rtm-35542)' for '.NETCoreApp,Version=v2.2'.
```

**Comment by pranavkm** [comment] 2018-10-25 22:52
Marking this as external per email thread. This was caused by a change to the NuGet client.

**Closed** 2018-10-26 16:38 UTC
Labels: external
