### ISSUE TITLE
How to get ASP.NET 2.2 Web Application (Model-View-Controller) template with Identity to have AccountController and ManageController instead of Razor Pages? 

### ISSUE THREAD

**Issue by asafgo** [aspnet/AspNetCore#6978] opened 2019-01-24 07:03 UTC
Choosing "Web Application (Model-View-Controller) with Individual User Accounts for ASP.NET Core 2.2 Generates Identity in Razor Pages.
If I choose ASP.NET 2.2 Web Application (Model-View-Controller) template I expect to have AccountController and ManageController and not Razor Pages "Combine" with MVC!
So my question is how do I make new ASP.NET 2.2 with AccountController and ManageController when choosing Web Application (Model-View-Controller) template?

**Comment by pranavkm** [comment] 2019-01-24 17:55
Likely a dup of https://github.com/aspnet/AspNetCore/issues/6978

cc @blowdart

**Comment by blowdart** [comment] 2019-01-24 17:58
A dupe of itself?

You mean https://github.com/aspnet/Scaffolding/issues/864 :)

**Closed by blowdart** 2019-01-24 17:58 UTC
