### ISSUE TITLE
Add Ability to use Component Type with Constructors and This Keyword

### ISSUE THREAD

**Issue by TheFanatr** [aspnet/AspNetCore#7236] opened 2019-02-04 11:22 UTC
### Is your feature request related to a problem? Please describe.
In the latest release of Razor Components, the context for the code inside a component `.cshtml` file is always the generated class <code>__*ComponentClassName*</code> instead of simply the actual class <code>*ComponentClassName*</code>. Due to this fact, using the component classes outside of code in the component itself becomes very difficult, especially if `this` references are to be passed around; the difficulty arises because type-checking in the Razor syntax will cause a compile-time failure if `this` is cast to anything but the actual class, while the generated code will also fail to compile if `this` is cast to anything but the generated class. This means that regardless of if the component-external code expects the actual class or the generated class, supplying `this` will either fail on Razor's side or the generated code's side. #5514 Details this as well, but the issues get deeper. For example, a side effect of this property is that constructors are also susceptible to the same flip-flop compile-time failures, with the only difference that there is no way around the issue except defining a partial class. This is problematic, because even basic things like static constructors cannot be declared, so no app-initialization code can be declared independently in a component. An example of this use case would be using static constructors to add individual pages to a menu, so that hard-coded lists can be avoided.

```csharp
public static Counter() => MenuHelper.AddListing(href: "counter", name: "Counter");
``` 

### Describe the solution you'd like
At this point, I see no reason why the generated classes cannot simply be `partial`, which would remove the need for a new class with `__` prepended to the name to be generated for all the components. Such a solution would solve most of the glaring issues with the current behavior.

### Describe alternatives you've considered
A possible alternative could be getting the code generator to rename constructors and destructors for the actual class to the generated class, and then derive the generated class from the actual one.

**Comment by mkArtakMSFT** [comment] 2019-02-04 23:03
Thanks for contacting us, @TheFanatr.
@rynowak, @SteveSandersonMS thoughts?

**Comment by SteveSandersonMS** [comment] 2019-02-04 23:14
All the points here are valid, but this is a duplicate of #5514. 

We will change components to be partial classes, but we have to do some work in VS to make it handle that first.

**Closed by SteveSandersonMS** 2019-02-04 23:14 UTC
Labels: area-mvc, enhancement
