### ISSUE TITLE
onclick event fired when disabled the icon button in blazor

### ISSUE THREAD

**Issue by mohankumar91** [aspnet/AspNetCore#16655] opened 2019-10-30 10:31 UTC
### Current behavior:

`@onclick` event fired when disabled the button (with icon) in blazor

### Desired behavior:

`@onclick` event not fired when disabled the button(with icon) in blazor

### Steps to reproduce: (app code and test code)

```html
<button class="btn1" @onclick="onToggleClick" disabled>
<span class="fa fa-home" />@Content</button>
```

```js
@code {
  public string Content = "Play";
private void onToggleClick(Microsoft.AspNetCore.Components.Web.MouseEventArgs e)
    {
        if (this.Content == "Play")
        {
            this.Content = "Pause";
        }
        else
        {
            this.Content = "Play";
        }
    }
}
```

```html
<style>
  
.btn1 {
 
  border: none;
  color: white;
  padding: 12px 16px;
  font-size: 16px;
  cursor: pointer;
}
</style>
```

**Refer the below css file in **_host.cshtml** page**

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

### Versions

3.4.1

I have uploaded the reproducible example. Could you please reopen the issue and ensure the sample.

[DemoSample.zip](https://github.com/cypress-io/cypress/files/3700718/DemoSample.zip)
![Demo](https://user-images.githubusercontent.com/18420823/66367553-499d3200-e9b2-11e9-9c14-3a42eea088da.gif)

**Comment by javiercn** [comment] 2019-10-30 13:15
@mohankumar91 thanks for contacting us.

I've downloaded the example and I'm not able to reproduce the behavior you are mentioning. It just works for me.

Can you add more details like the output from `dotnet --info` and your visual studio version?

**Comment by mohankumar91** [comment] 2019-10-30 13:54
Hi @javiercn ,

Could you please click the **icon** in button.

VS Info:
1.Version 16.4.0 Preview 2.0
2. .Net core SDK 3.1.100- review1

**Comment by javiercn** [comment] 2019-10-30 14:04
@mohankumar91 Thanks, I missed that detail

**Comment by javiercn** [comment] 2019-10-30 14:07
I repro the behavior now and can confirm is a bug.

**Comment by SteveSandersonMS** [comment] 2019-10-31 09:29
Fixed in https://github.com/aspnet/AspNetCore/pull/16671

**Closed by SteveSandersonMS** 2019-10-31 09:29 UTC
Labels: area-blazor, bug

**Comment by mohankumar91** [comment] 2019-10-31 09:32
@SteveSandersonMS  When available this fix?

**Comment by SteveSandersonMS** [comment] 2019-10-31 10:03
It will be included in the 3.1 Preview 3 release

**Comment by mohankumar91** [comment] 2019-10-31 10:07
Thanks for your information @SteveSandersonMS

**Comment by mohankumar91** [comment] 2019-11-18 05:41
Hi @SteveSandersonMS ,

I have checked the latest blazor updates (https://github.com/dotnet/core/blob/master/release-notes/3.1/preview/3.1.0-preview3.md) , above reported issues reproduced in latest updates
