### ISSUE TITLE
Ambiguous routes error (Bindings and lambda expressions)

### ISSUE THREAD

**Issue by McHeff** [aspnet/AspNetCore#9105] opened 2019-04-05 07:18 UTC
When I created a new page, I ran the application, everything worked fine... I then added some html controls and re-ran the app to see if everything was correct... I then added in some bindings and some C# methods, re-ran, everything was fine... 

I then added some foreach loops and some lambda expressions, 

All of a sudden I get the "The following routes are ambiguous"
![image0](https://user-images.githubusercontent.com/47241975/55610212-bc6aed80-5782-11e9-9196-d2a9acdac7ea.jpg)

### To Reproduce
1. Using Blazor 0.7 (Target framework .NET Standard 2.0) 
2. Run this code 'LoadPallets()':

![image](https://user-images.githubusercontent.com/47241975/55610448-37cc9f00-5783-11e9-8c3e-01be2c0efa7c.png)

3. With these arguments: Where(x=> (x.Selected == true) && (x.SalesOrder == SearchValue))

### Expected behavior
What I expected to happen was the for loop to only return what I selected for whatever sales order I typed in. What I got though was an app that couldn't start, and upon opening the console window, I see lots of red writing, with the ambiguous routes error at the top. 

### Additional context

I have encountered this error before but that time it had nothing to do with lambda expressions, it actually had to do with data binding, please see the thread in this link: 

https://github.com/aspnet/AspNetCore/issues/5548

Hope this is helpful, and like I said, I very rarely get this error, only got it a handful of times, but when I do get it, it's quite a shlep to get working again as the page declarations are actually fine, and the "Ambiguous error" we get, is ambiguous itself, oh the irony :D   

PS: SalesOrderPallets.json

`[
  {
    "SalesOrder": "000000000123456",
    "StockCode": "A100",
    "PalletQty": 150,
    "PalletNumber": "P100"
  },
  {
    "SalesOrder": "000000000123456",
    "StockCode": "A100",
    "PalletQty": 175,
    "PalletNumber": "P101"
  },
  {
    "SalesOrder": "000000000123456",
    "StockCode": "A101",
    "PalletQty": 205,
    "PalletNumber": "P102"
  },
  {
    "SalesOrder": "000000000123457",
    "StockCode": "A101",
    "PalletQty": 250,
    "PalletNumber": "P103"
  }
]
`

**Comment by danroth27** [comment] 2019-04-10 16:26
Thanks for reporting this issue! This looks like a duplicate of #5548, so closing this one.

**Closed by danroth27** 2019-04-10 16:26 UTC
Labels: area-mvc
