### ISSUE TITLE
System.IO.InvalidDataException:“Form key length limit 2147483647 or value length limit 2147483647 exceeded.”

### ISSUE THREAD

**Issue by namelhp2000** [aspnet/AspNetCore#14407] opened 2019-09-25 07:09 UTC
--- Add the service below
  services.Configure<FormOptions>(option =>
            {
                option.ValueCountLimit = int.MaxValue;
                option.ValueLengthLimit = int.MaxValue;
                option.KeyLengthLimit = int.MaxValue;
                option.MultipartBodyLengthLimit = int.MaxValue;
                option.MultipartBoundaryLengthLimit = int.MaxValue;
            });

  ----Error reported by custom method
 public static string Forms(this HttpRequest request, string key)
        {
            return (string.IsNullOrEmpty(request.Form[key])) ? string.Empty : (string)request.Form[key];

        }

at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ThrowKeyOrValueTooLargeException()
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.<ReadFormAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()

**--The request method that the front end returns to the background，
prompt：System.IO.InvalidDataException:“Form key length limit 2147483647 or value length limit 2147483647 exceeded.”**
   string str = base.Request.Forms("Account1");

**----Comment out the following three attributes and you will not get an error**
 option.ValueCountLimit = int.MaxValue;
                option.ValueLengthLimit = int.MaxValue;
                option.KeyLengthLimit = int.MaxValue;

Requesting the above method prompts for a title error

**Comment by davidfowl** [comment] 2019-09-25 14:47
This is an overflow bug. Dupe of #13719

**Closed by davidfowl** 2019-09-25 14:47 UTC
Labels: area-hosting
