### ISSUE TITLE
Cookies value not in `HttpContext.Request.Cookies`, but real exists in `HttpContext.Request.Headers`

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/AspNetCore#7053] opened 2019-01-28 06:54 UTC
### Describe the bug
For Asp.Net Core 2.2, there are cookies in `HttpContext.Request.Headers["Cookie"]`, but I could not access it by `HttpContext.Request.Cookies`.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Set Cookie in the View   
```
@section Scripts{
    <script type="text/javascript">
        document.cookie = "username=John Doe";
    </script>
}
```
3. Try to access the cookie in Controller, but its value is null.
```
var name = HttpContext.Request.Cookies["username"];
```

4. If I try to access it by `HttpContext.Request.Headers["Cookie"]` like 

```
            StringValues values;
            HttpContext.Request.Headers.TryGetValue("Cookie", out values);
            var cookies = values.ToString().Split(';').ToList();
            var result = cookies.Select(c => new { Key = c.Split('=')[0].Trim(), Value = c.Split('=')[1].Trim() }).ToList();
            var username = result.Where(r => r.Key == "username").FirstOrDefault();
```
I could get the value.
### Expected behavior
`HttpContext.Request.Cookies["username"]` return the expected value `John Doe`.

**Comment by Andrzej-W** [comment] 2019-01-31 12:59
Is the dot before cookie name intentional?
```js
document.cookie = ".username=John Doe";
                   ^
```
Here you don't have a dot
```c#
var name = HttpContext.Request.Cookies["username"];
```

**Comment by Edward-Zhou** [comment] 2019-02-01 01:42
It the mistake by posting code, I will update it.

**Comment by anurse** [comment] 2019-06-18 21:49
Cookies don't support spaces in cookie values, thus the parsing fails. Quoting doesn't work either, you'll have to escape it some how.

Closing as this is expected behavior, since the cookie invalid.

**Closed by anurse** 2019-06-18 21:49 UTC
Labels: area-servers, triage-review
