### ISSUE TITLE
ASP.NET Identity Core 2.0 - Expiration phone token

### ISSUE THREAD

**Issue by FXFernandes** [aspnet/AspNetCore#5784] opened 2018-04-17 18:10 UTC
One of the methods exposed by UserManager is GenerateChangePhoneNumberTokenAsync.

Looking to the code, I noticed that the method mentioned is calling Rfc6238AuthenticationService.GenerateCode. It seems to me that the lifetime of the token is hardcoded to 3 minutes as showed bellow.

```
private static readonly TimeSpan _timestep = TimeSpan.FromMinutes(3);

        // More info: https://tools.ietf.org/html/rfc6238#section-4
        private static ulong GetCurrentTimeStepNumber()
        {
            var delta = DateTime.UtcNow - _unixEpoch;
            return (ulong)(delta.Ticks / _timestep.Ticks);
        }

        // More info: https://tools.ietf.org/html/rfc6238#section-4
        private static ulong GetCurrentTimeStepNumber()
        {
            var delta = DateTime.UtcNow - _unixEpoch;
            return (ulong)(delta.Ticks / _timestep.Ticks);
        }

        public static int GenerateCode(byte[] securityToken, string modifier = null)
        {
            if (securityToken == null)
            {
                throw new ArgumentNullException(nameof(securityToken));
            }

            // Allow a variance of no greater than 9 minutes in either direction
            var currentTimeStep = GetCurrentTimeStepNumber();
            using (var hashAlgorithm = new HMACSHA1(securityToken))
            {
                return ComputeTotp(hashAlgorithm, currentTimeStep, modifier);
            }
        }
```

Source: https://github.com/aspnet/Identity/blob/85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c/src/Core/Rfc6238AuthenticationService.cs

Am I correct? Is this the lifetime of the phone token?
If yes, since the value is hardcoded, any ideas how to change it?

**Comment by guylando** [comment] 2019-03-09 19:11
+1

**Comment by slaneyrw** [comment] 2019-07-10 03:18
Having to replace EmailTokenProvider and PhoneTokenProvider because they rely on the *inconfigurable* internal Rfc6238AuthenticationService.  This is starting to become a pattern where classes are "designed" for override, but hide/pin all the bits you need.

for example.
* UserManager  ( UpdateSecurityStampInternal, UpdatePasswordHash, NewSecurityStamp, etc )
* UserStore ( DbSets )
* IdentityUserContext ( GetStoreOptions ) 
* OpenIdConnectHandlers ( Hardcoded generic parameter type for base - closes event handler extensibility )

When these issues are brought up they are generally put on the backlog, never to be addressed, meanwhile we copy all your code and hope it doesn't change.

**Comment by blowdart** [comment] 2019-09-11 18:12
Closing as by design

**Closed by blowdart** 2019-09-11 18:12 UTC
Labels: area-identity
