### ISSUE TITLE
Update Streaming to not use our AsyncEnumerableAdapters

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#9866] opened 2019-04-30 17:58 UTC
Cancellation should be fully supported on `IAsyncEnumerable` now (or soon?) so we shouldn't need to use our `AsyncEnumerableAdapters` and `CancelableAsyncEnumerable` helper classes anymore.

**Comment by anurse** [comment] 2019-04-30 21:32
Duplicate of https://github.com/aspnet/AspNetCore/issues/7960

**Closed by anurse** 2019-04-30 21:32 UTC
Labels: PRI: 2 - Preferred, area-signalr
