### ISSUE TITLE
10% Regression in Plaintext Pipelined

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#11778] opened 2019-07-02 00:16 UTC
![image](https://user-images.githubusercontent.com/1142958/60473871-0ae73580-9c67-11e9-89fd-ce121188b641.png)

**Comment by BrennanConroy** [comment] 2019-07-02 17:48
Caused by https://github.com/aspnet/AspNetCore/commit/bcb59fa5c9082de1a53234edfecd3b918c5340e6

Can verify by using
**Before:**
aspnet: 3.0.0-preview7.19328.3
net: 3.0.0-preview7-27825-08

**After:**
aspnet: 3.0.0-preview7.19328.5
net: 3.0.0-preview7-27825-08

**Comment by mkArtakMSFT** [comment] 2019-07-07 22:30
So it seems the fix has fixed some of this,
![image](https://user-images.githubusercontent.com/34246760/60774650-0f2eab00-a0cc-11e9-90dc-8bc93d4f07fa.png)


yet the perf is still well below from the all-time high:
![image](https://user-images.githubusercontent.com/34246760/60774638-e4dced80-a0cb-11e9-940b-73100d0ccd19.png)

**Comment by mkArtakMSFT** [comment] 2019-07-07 22:31
@DamianEdwards, @davidfowl is the cause known for the drop in late May/early June?
![image](https://user-images.githubusercontent.com/34246760/60774660-4b620b80-a0cc-11e9-8d9e-2d23db484890.png)

Has any investigation happened for that drop?

**Comment by benaadams** [comment] 2019-07-07 22:40
NIC upgrade issue? https://github.com/aspnet/Benchmarks/issues/1053

**Comment by davidfowl** [comment] 2019-07-07 22:42
> So it seems the fix has fixed some of this,

Seems like Windows isn't running properly. The last run was on 7/3

> @DamianEdwards, @davidfowl is the cause known for the drop in late May/early June?

Supposedly a hardware issue. Thanks @benaadams

**Comment by davidfowl** [comment] 2019-07-07 22:44
Yup:

![image](https://user-images.githubusercontent.com/95136/60774770-15be2200-a0ce-11e9-83b9-b47086874397.png)

**Comment by mkArtakMSFT** [comment] 2019-07-07 22:49
Thanks folks.

I'll try to follow up on the hardware issue tomorrow, after will find out who is managing it for us.

**Comment by davidfowl** [comment] 2019-07-07 22:51
> I'll try to follow up on the hardware issue tomorrow, after will find out who is managing it for us.

There's an email thread with @DamianEdwards and @sebastienros about the hardware issue.

The windows failures are just something else that's broken. Unrelated to any performance regression.

**Comment by mkArtakMSFT** [comment] 2019-07-08 20:31
@davidfowl so are you saying there is nothing to follow up on here and all the partners involved are aware of these and what needs to happen is happening?

**Comment by anurse** [comment] 2019-07-09 22:16
@halter73 got this fixed in preview7

**Closed by anurse** 2019-07-09 22:16 UTC
Labels: Working, area-servers, area: Performance
