### ISSUE TITLE
Generating an absolute URL while ignoring all ambient values

### ISSUE THREAD

**Issue by poke** [aspnet/AspNetCore#17850] opened 2019-12-13 11:34 UTC
Is there a simple way to generate an URL to the current Razor page, while ignoring all ambient values?

Let’s assume I’m on a Razor page `Foo` that has an optional route parameter `id`, `@page {id?}`. So my current URL is `http://localhost:5000/Foo/Bar`. Now I want to generate a link to that same Razor page but without the `id`. The desired result would be `http://localhost:5000/Foo`.

All my attempts to use the `IUrlHelper` failed because it will always reuse the ambient values, even when I specify an explicit `RouteValueDictionary`. That’s because the UrlHelper will eventually use the link generator to create an address, and [that will always extract the ambient values first](https://github.com/aspnet/AspNetCore/blob/v3.1.0/src/Http/Routing/src/LinkGeneratorRouteValuesAddressExtensions.cs#L200).

The only way I got this to work now is the following:

```c#
public static string GetPageUri(this HttpContext httpContext, string page)
{
    var linkGenerator = httpContext.RequestServices.GetService<LinkGenerator>();
    var values = new RouteValueDictionary
    {
        ["page"] = page,
    };
    return linkGenerator.GetUriByAddress(httpContext, new RouteValuesAddress
    {
        ExplicitValues = values,
    }, values);
}
```

So I use the link generator and the *most low-level* function it offers to create an URI by a `RouteValuesAddress` where I explicitly leave out the ambient values.

Am I missing something or is there really no way to generate a link like that from the UrlHelper directly? I am aware that reusing ambient values for the same page is [completely per design](https://github.com/aspnet/AspNetCore/issues/3746) but there should still be some way to opt out of this, or not?

**Comment by javiercn** [comment] 2019-12-13 11:49
@poke thanks for contacting us.

@rynowak can correct me if I'm wrong, but I believe that if you don't pass in the HttpContext instance to the link generator it will generate a link without using the ambient values.

**Comment by poke** [comment] 2019-12-13 12:08
When going through `UrlHelper`, e.g. with the following:

```c#
Url.PageLink(page,
    protocol: HttpContext.Request.Scheme,
    host: HttpContext.Request.Host.ToString())
```

Then this will still use the HttpContext from the current action context:

https://github.com/aspnet/AspNetCore/blob/4c3996f8241df09ad811008111440e8c6cf20c9d/src/Mvc/Mvc.Core/src/UrlHelperExtensions.cs#L623

But yes, you’re right, when using `LinkGenerator` directly, you can skip that apparently:

```c#
linkGenerator.GetUriByPage(page,
    handler: null,
    values: null,
    scheme: httpContext.Request.Scheme,
    host: httpContext.Request.Host);
```

Not sure if that’s really a better solution though. Ideally, I would want this on the UrlHelper, so that I can use it directly within a view without having to retrieve a link generator.

**Comment by javiercn** [comment] 2019-12-13 12:11
@poke I see.

I'm going to close the issue for now as the question has been answered. I'll let @rynowak comment on the fragment below if he has any further thoughts and we can potentially open a separate issue if necessary to track any remaining work.

> I would want this on the UrlHelper, so that I can use it directly within a view without having to retrieve a link generator.

**Closed by javiercn** 2019-12-13 12:11 UTC
Labels: area-mvc

**Comment by poke** [comment] 2019-12-13 12:13
That works for me. Thanks for the quick response! :blush:

**Comment by rynowak** [comment] 2019-12-13 21:22
> simple way

@poke  - sorry there's nothing simple in link generation 🤣 

> All my attempts to use the IUrlHelper failed because it will always reuse the ambient values, even when I specify an explicit RouteValueDictionary. 

You can do this by explicitly specifying null/empty-string for your `id` value. `Url.Page(new { id = "" })`. We always look at the explicit values first, and specifying null/empty is the way to *delete* a value.

> Not sure if that’s really a better solution though. Ideally, I would want this on the UrlHelper, so that I can use it directly within a view without having to retrieve a link generator.

I'd suggest adding `@inject LinkGenerator Link` to your top-level `_ViewImports.cshtml`. Now you have it everywhere. 

We'll likely add this to be base class eventually. The APIs that are on UrlHelper have been around since MVC (non-core) 1.0 and are pretty complex to use right. The `LinkGenerate` is freshly designed, and a little bit more verbose to use, but hopefully easier to understand.

**Comment by poke** [comment] 2019-12-13 22:59
> sorry there's nothing simple in link generation :rofl:

Great 😅

> You can do this by explicitly specifying null/empty-string for your `id` value.

Yeah, I know but then I need to know exactly what ambient value I need to overwrite. I was looking for a generic way to do this… for reasons (I'm working on an alternative Blazor router… don't ask 🙈)

> We'll likely add this to be base class eventually.

That's good. The UrlHelper does feel a bit old at times.

**Comment by rynowak** [comment] 2019-12-16 16:45
> That's good. The UrlHelper does feel a bit old at times.

Super yes. The problem is that we have *many many* experiences that are layered on top of it, and these areas are super touchy.
