### ISSUE TITLE
toString calls observed during SignalR processing

### ISSUE THREAD

**Issue by aaronhudon-ts** [aspnet/AspNetCore#14530] opened 2019-09-27 18:57 UTC
### Describe the bug
During SignlarR processing, expensive `toString` calls observed in profiler.

### To Reproduce
1. ASP.NET Core 3.0 Blazor Server Side
2. Send fairly large packets (200kb) to the browser using `IJSRuntime.InvokeVoidAsync`
3. In Chrome, record a performance profile for a few seconds of the packets being sent.
4. Notice in the frame visualization:
- i.onmessage
- connection.onreceive
...
- s.toString()
- c.toString()

![image](https://user-images.githubusercontent.com/49655238/65794770-bba58980-e11d-11e9-8b3a-2ac96d0d4dcc.png)

**Comment by anurse** [comment] 2019-10-01 21:11
What's the expected behavior here? Is your concern that this is too much time? Or the fact that it's `toString` specifically? Of course, there's always room for performance improvment. Do you have a specific suggestion to improve this?

**Comment by aaronhudon-ts** [comment] 2019-10-01 22:19
> What's the expected behavior here? Is your concern that this is too much time? Or the fact that it's `toString` specifically? Of course, there's always room for performance improvment. Do you have a specific suggestion to improve this?

Since it's happening very frequently for my use-case, I wanted to raise the potential performance issue with the team.

Can anyone direct me to the originating source where toString is called?

**Comment by anurse** [comment] 2019-10-02 17:52
I just noticed that this is actually a Blazor scenario rather than a direct SignalR scenario. It's likely in code borrowed from SignalR so it's relevant to us but we should involve the blazor team as well. Adding some labels and tagging @rynowak for more info. Looks like it's related to the BlazorPack protocol handler.

> Can anyone direct me to the originating source where toString is called?

From that screenshot alone, I can't directly reliably. I can say that [`parseMessage`](https://github.com/aspnet/AspNetCore/blob/de9a8a9c0bf5e7f3e550cf91db45702807004dee/src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts#L88) pretty much calls straight down in to [`msgpack5`](https://github.com/mcollina/msgpack5) which is implementation of Message Pack we use on the JavaScript client. It's possible this is affecting it.

What's the **performance** impact you're seeing? Are operations happening too slowly? Getting more context on how this is affecting your app will help us understand how to prioritize investigation into this.

In general though, if you're sending a large message via JavaScript we have to get that large message into a format that can be sent on the wire. What is the content of that message? Is it a single large 200kb string parameter, for example? We don't do any chunking of that data by default, it would be up to your app to do so.

**Comment by aaronhudon-ts** [comment] 2019-10-02 20:04
It's still preliminary development, I just wanted to raise it with the team.  The `toString` calls are consistently consuming around 15% of each invocation.  Maybe it scales with the size of the message.  I understand that SignalR prefers small messages, but if there's a quick-win to be had by someone analyzing the `toString` here.

![image](https://user-images.githubusercontent.com/49655238/66077428-cfcdfa00-e514-11e9-88a2-c1489221f63d.png)

**Comment by anurse** [comment] 2019-10-02 21:26
> Maybe it scales with the size of the message. I understand that SignalR prefers small messages, but if there's a quick-win to be had by someone analyzing the `toString` here.

Certainly possible. We are looking at how we can better support larger messages, so we won't necessarily exclude investigations based on large messages.

**Comment by mkArtakMSFT** [comment] 2019-10-08 16:51
@anurse are there any pending actions here?

**Comment by anurse** [comment] 2019-10-08 18:29
Depends on what priority we have on optimizing the client-side code for large method invocations. I don't think we have any action to take right now, this was just an observation about a particularly expensive call in the code-path used by Blazorpack (and SignalR's MessagePack protocol) to send a large message.

We can probably close this for now and come back to it when we're doing more specific perf analysis on message/invocation sizes in JSInterop and SignalR.

**Closed by anurse** 2019-10-08 18:29 UTC
Labels: Blazor ♥ SignalR, area-blazor, area-signalr, more-info-needed
