### ISSUE TITLE
SignalR silently closes circuit if asked to send dynamic data

### ISSUE THREAD

**Issue by willdean** [aspnet/AspNetCore#17136] opened 2019-11-15 12:05 UTC
### Describe the bug
We have a method defined on a SignalR strongly-typed hub like this:

```
        Task bad(object obj);
```

We attempt to pass data to it from outside the hub.  This data has arrived at the server from elsewhere, we don't have strongly-typed classes to map it to, so we deserialize it (in the real app we then look at some properties of it) and then pass the remainder of it to SignalR to be sent out to browser clients:

```
            var json = "{ 'a' : 'b' }";
            object message = JsonConvert.DeserializeObject(json);
            _hubContext.Clients.All.bad(message);
```

What happens then is that there are no exceptions thrown at the server, no message is sent, and the SignalR connection is closed.
At the browser console we see `Information: Connection disconnected.` from SignalR

@davidfowl has indicated elsewhere that the SignalR Core will not cope with dynamic objects, which is fair enough (there are plenty of workarounds), but the lack of any error/exception anywhere made this very time-consuming to debug.
In general, we would also prefer that SignalR did not abandon a circuit because of a problem on a single message send.

### To Reproduce
I think all you have to do is deserialize something (anything) with JsonConvert and pass it to a SignalR hub method.  But there's a complete repro at https://github.com/willdean/SignalRDisconnectTest if that's helpful.

### Further technical details
- ASP.NET Core version 
3.0.100
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS2019 16.3.8

**Comment by BrennanConroy** [comment] 2019-11-15 19:19
Mostly a dupe of https://github.com/aspnet/AspNetCore/issues/13651

There is a debug log on the server stating that the message could not be serialized and that the connection is being closed. We're planning on changing the log level to be more obvious.

In your specific example it fails to serialize because System.Text.Json is unable to serialize a Newtonsoft.Json object. If you changed to use System.Text.Json.JsonSerializer and changed the string to `"{\"a\":\"b\"}"` then you could pass the object successfully.

Another alternative could be to change to using Newtonsoft.Json in SignalR by following the docs: https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-3.0&tabs=dotnet#switch-to-newtonsoftjson

**Comment by willdean** [comment] 2019-11-15 22:44
@BrennanConroy - thanks for the link.  There's no problem with a workaround - we just send the json as a string and deserialize it on the client in the message handler.

It seems to me that merely logging this might be appropriate (though not at Debug) if all that had happened is that the message hadn't sent.  But what's actually happened is that the entire SignalR link has completely collapsed (which affects all sorts of other activities) because of a type error involving a single message call.  

I'm sure there's some good reason for this, but is it possible to expand on why it's necessary for the link to be torn down because of a serialisation problem on a single message?  Does every client of the hub get disconnected when this happens?

If this has to be dealt with as log message rather than an exception then can I please put in a vote for it to be at Error level rather than anything less?

**Comment by anurse** [comment] 2019-11-20 21:12
Closing this issue as #13651 is tracking the actual work here (logging).

**Closed** 2019-11-20 21:12 UTC
Labels: area-signalr, duplicate
