### ISSUE TITLE
(blazor, razor) Chinese encoding is not supported by the latest preview version

### ISSUE THREAD

**Issue by LuohuaRain** [aspnet/AspNetCore#10360] opened 2019-05-18 02:22 UTC
### Describe the bug
the latest Blazor version:3.0.100-preview5-011568 doesn't support Chinese encoding in .razor file.

I replace English word "Home" in file NavMenu.razor to Chinese word "首页", and dotnet run, it shows garbled words. 

### To Reproduce
1. Using this version of ASP.NET Core:3.0.100-preview5-011568
2. Run this code

> <div class="@NavMenuCssClass" onclick="@ToggleNavMenu">
    <ul class="nav flex-column">
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="oi oi-home" aria-hidden="true"></span> 信息录入
            </NavLink>
        </li>
    </ul>
</div>

4. and the page shows  > ��Ϣ¼��
    in Windows 10 Chinese-simplified

### Expected behavior
I excepte the normal encoding for Chinese-simplified.

### Screenshots
![code1](https://user-images.githubusercontent.com/37979368/57963430-b3ab3100-7956-11e9-98af-cb38822d7e1e.png)

![result2](https://user-images.githubusercontent.com/37979368/57963438-cde50f00-7956-11e9-9c3c-390180d4c6fc.png)

**Comment by pranavkm** [comment] 2019-05-22 21:46
@LuohuaRain do you have an app to share that reproduces this issue? I can't seem reproduce the error you're seeing:

![image](https://user-images.githubusercontent.com/174281/58211267-4c67e680-7ca0-11e9-8732-6ce08421fc42.png)

**Comment by LuohuaRain** [comment] 2019-05-23 12:49
> @LuohuaRain do you have an app to share that reproduces this issue? I can't seem reproduce the error you're seeing:
> 
> ![image](https://user-images.githubusercontent.com/174281/58211267-4c67e680-7ca0-11e9-8732-6ce08421fc42.png)

 My friend and I all got this issue in different Windows 10 simplified and the same verson of VS 2019 Preview. And I just updated my VS to 16.2.0 Preview 1.0, this issue still exist. 
What kind of information do I need to provide more?

**Comment by LuohuaRain** [comment] 2019-05-23 13:14
> @LuohuaRain do you have an app to share that reproduces this issue? I can't seem reproduce the error you're seeing:
> 
> ![image](https://user-images.githubusercontent.com/174281/58211267-4c67e680-7ca0-11e9-8732-6ce08421fc42.png)

I put a demo in  docker centos 7.6 with .net core 3 preview runtime  , and the result is the same as this demo run on my local environment.
[http://cdcl.net.cn:8000/](url)
![2333](https://user-images.githubusercontent.com/37979368/58255467-a4d1dd80-7d9f-11e9-86e0-2fde3bdf802d.png)

**Comment by ajaybhargavb** [comment] 2019-05-30 22:24
@LuohuaRain, can you try the following?
After you type "信息录入" in your razor file in VS and save it. Close and reopen that razor file and check if it is displayed properly in VS?

If the default encoding is UTF-8, it shouldn't run into this problem. I am trying to understand if you are doing something specific when you save or open the file to specify the encoding.

**Comment by LuohuaRain** [comment] 2019-06-01 03:22
@ajaybhargavb I didn't do anything else, and it is displayed properly in VS.  Only in runtime, it is displayed wrong.
![image](https://user-images.githubusercontent.com/37979368/58743183-76b76200-845f-11e9-8e5e-7de80e182385.png)

**Comment by mkArtakMSFT** [comment] 2019-06-21 21:17
@ajaybhargavb please dupe this with the issue where we track the actual issue causing this.

**Comment by ajaybhargavb** [comment] 2019-06-21 22:10
Dupe of https://github.com/aspnet/AspNetCore/issues/11225.

**Closed by ajaybhargavb** 2019-06-21 22:10 UTC
Labels: PRI: 2 - Preferred, Working, area-blazor, bug
