### ISSUE TITLE
[Test Failure] ReactReduxTemplate_Works_NetCore

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7377] opened 2019-02-08 02:37 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=90177

```
 Failed   Templates.Test.SpaTemplateTest.ReactReduxTemplateTest.ReactReduxTemplate_Works_NetCore
2019-02-07T23:59:00.6960983Z   Error Message:
2019-02-07T23:59:00.6961587Z    Assert.Equal() Failure
2019-02-07T23:59:00.6961720Z   Expected: OK
2019-02-07T23:59:00.6961783Z   Actual:   InternalServerError
2019-02-07T23:59:00.6961865Z   Stack Trace:
2019-02-07T23:59:00.6962130Z      at Templates.Test.Helpers.AspNetProcess.AssertStatusCode(String requestUrl, HttpStatusCode statusCode, String acceptContentType) in /_/src/ProjectTemplates/test/Helpers/AspNetProcess.cs:line 156
2019-02-07T23:59:00.6962330Z      at Templates.Test.SpaTemplateTest.SpaTemplateTestBase.TestApplication(Boolean publish) in /_/src/ProjectTemplates/test/SpaTemplateTest/SpaTemplateTestBase.cs:line 54
2019-02-07T23:59:00.6962786Z      at Templates.Test.SpaTemplateTest.SpaTemplateTestBase.SpaTemplateImpl(String template, Boolean noHttps) in /_/src/ProjectTemplates/test/SpaTemplateTest/SpaTemplateTestBase.cs:line 45
2019-02-07T23:59:00.6963062Z      at Templates.Test.SpaTemplateTest.ReactReduxTemplateTest.ReactReduxTemplate_Works_NetCore() in /_/src/ProjectTemplates/test/SpaTemplateTest/ReactReduxTemplateTest.cs:line 19
2019-02-07T23:59:00.6963333Z   Standard Output Messages:
2019-02-07T23:59:00.6965038Z    ==> /home/vsts/work/1/s/.dotnet/dotnet new reactredux --debug:custom-hive "/home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/.templateengine" [/home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/TestTemplates/AspNet.Template.ad7824]
2019-02-07T23:59:00.6965155Z    The template "ASP.NET Core with React.js and Redux" was created successfully.
2019-02-07T23:59:00.6965358Z    
2019-02-07T23:59:00.6965795Z    Processing post-creation actions...
2019-02-07T23:59:00.6966238Z    Running 'dotnet restore' on /home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/TestTemplates/AspNet.Template.ad7824/AspNet.Template.ad7824.csproj...
2019-02-07T23:59:00.6966602Z      Restoring packages for /home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/TestTemplates/AspNet.Template.ad7824/AspNet.Template.ad7824.csproj...
2019-02-07T23:59:00.6967028Z      Generating MSBuild file /home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/TestTemplates/AspNet.Template.ad7824/obj/AspNet.Template.ad7824.csproj.nuget.g.props.
2019-02-07T23:59:00.6967231Z      Generating MSBuild file /home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/TestTemplates/AspNet.Template.ad7824/obj/AspNet.Template.ad7824.csproj.nuget.g.targets.
2019-02-07T23:59:00.6967437Z      Restore completed in 311.42 ms for /home/vsts/work/1/s/src/ProjectTemplates/test/bin/Release/netcoreapp3.0/TestTemplates/AspNet.Template.ad7824/AspNet.Template.ad7824.csproj.
2019-02-07T23:59:00.6967603Z    
```

cc @mkArtakMSFT @ryanbrandenburg

**Comment by ryanbrandenburg** [comment] 2019-02-22 23:33
The important part here is: `System.IO.EndOfStreamException: Attempted to read past the end of the stream.` out of the React middleware.

**Comment by anurse** [comment] 2019-03-01 19:23
Skipping this test to unblock builds.

**Comment by mkArtakMSFT** [comment] 2019-03-07 18:48
This is a dupe of https://github.com/aspnet/AspNetCore-Internal/issues/1745

**Closed by mkArtakMSFT** 2019-03-07 18:48 UTC
Labels: 1 - Ready, PRI: 1 - Required, area-mvc, cost: S, task
