### ISSUE TITLE
ApplyFormatInEditMode is not working

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore#6744] opened 2019-01-16 14:48 UTC
### Describe the bug
Setting the DateTime annotation:

`[DisplayFormat(DataFormatString="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]`
has no effect on the field at the edit time.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Apply this annotation to a DateTime field '[DisplayFormat(DataFormatString="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]'
3. See the UI problem in edit mode. By the way, the UI is not changed whether you put or remove the "ApplyFormatInEditMode"

### Expected behavior
The format should be yyyy-MM-dd, however, the UI shows the field with the format mm/dd/yyyy

### Screenshots
![reporting-a-bug](https://user-images.githubusercontent.com/12829248/51256426-0e834a80-19ae-11e9-9e6b-a4fffc89b027.png)

### Additional context
Include the output of `dotnet --info`
[dotnetinfo.txt](https://github.com/aspnet/AspNetCore/files/2764583/dotnetinfo.txt)

**Comment by Rick-Anderson** [comment] 2019-01-16 20:30
See https://stackoverflow.com/questions/43752832/format-date-within-view-in-asp-net-core-mvc

**Comment by Rick-Anderson** [comment] 2019-01-16 20:58
@shadinamrouti 	if that doesn't solve your problem post a Github link to the simplest possible sample that reproduces the issue and I'll take a look.

**Comment by Rick-Anderson** [comment] 2019-01-17 18:56
@shadinamrouti 	thanks for your report. I thought it was probably a local problem.

@ryanbrandenburg 	please advise on how to handle date/edit.

**Comment by mkArtakMSFT** [comment] 2019-06-24 17:37
Thanks for contacting us, @shadinamrouti.
Closing this as a dupe of #10992

**Closed by mkArtakMSFT** 2019-06-24 17:37 UTC
Labels: area-mvc
