### ISSUE TITLE
The preview 6 Blazor (server-side) default project website doesn't work on Chrome and Firefox while ran as console application

### ISSUE THREAD

**Issue by cristianiorga** [aspnet/AspNetCore#12273] opened 2019-07-17 11:53 UTC
### Describe the bug
The preview 6 Blazor (server-side) default project website doesn't work on Chrome and Firefox while ran as console application. It does work in Edge and IE11.

### To Reproduce
1. Create a new Blazor (server-side) project using .Net Core preview 6
2. Run as console application
3. Open https://localhost:5001 in Chrome or Firefox

### Expected behavior
The website should work on all browsers.

### Screenshots
![image](https://user-images.githubusercontent.com/9863741/61373213-8668f980-a899-11e9-8d9b-ec615e3ceb13.png)

### Additional context
Incognito mode doesn't change anything. 
Running in IIS Express makes it work in Chrome and Firefox.
Chrome version 75.0.3770.142 (Official Build) (64-bit)
Firefox version 68.0 (64-bit)

>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment] 2019-07-17 16:18
Thanks for contacting us, @cristianiorga.
There are couple of things in play here. The issue in the image in Chrome you've shown there was fixed and will be released in the upcoming `Preview 7` release.
As for the Firefox, it is a known behavior of Firefox, where they don't respect certificates in the certificate store on the machine. There is a way, however, you can still say "it's ok, trust this website" and see the website load just fine.
Hope this helps.

**Closed by mkArtakMSFT** 2019-07-17 16:18 UTC
Labels: area-blazor

**Comment by cristianiorga** [comment] 2019-07-17 17:32
@mkArtakMSFT Glad to hear that some of it is fixed for preview 7. However, for Firefox I did add the certificate to the Firefox certificate store as shown below. If anything else is needed, please do let me know as otherwise I don't see where Firefox is at fault.

![image](https://user-images.githubusercontent.com/9863741/61396813-d1e6cc00-a8c8-11e9-8e47-0c3ad53b59a7.png)

![image](https://user-images.githubusercontent.com/9863741/61396820-d57a5300-a8c8-11e9-9abe-9495880ce32d.png)

![image](https://user-images.githubusercontent.com/9863741/61396824-d8754380-a8c8-11e9-8e0e-f46c562d50af.png)

**Comment by mkArtakMSFT** [comment] 2019-07-17 21:55
@SteveSandersonMS , @javiercn thoughts?

**Comment by SteveSandersonMS** [comment] 2019-07-18 08:16
It may be something to do with HSTS. @cristianiorga, you might want to try clearing Firefox's history of any information related to HSTS: https://support.mozilla.org/en-US/questions/919498

@mkArtakMSFT This is definitely a usage question, not a bug in Blazor or another part of ASP.NET Core.

**Comment by javiercn** [comment] 2019-07-18 09:53
We explicitly exclude localhost and all its derivatives from sending HSTS headers by default, so this has been the result of a user change. Its also not set during development

**Comment by cristianiorga** [comment] 2019-07-19 17:32
@SteveSandersonMS I can confirm that as expected from what @javiercn mentioned, there is no entry for localhost in the Firefox HTST file database SiteSecurityServiceState.txt

**Comment by cristianiorga** [comment] 2019-07-23 18:13
Issue no longer reproduces on 3.0.100-preview7-012821
