### ISSUE TITLE
The probleam for Model binding and Tag Helper in Naming.

### ISSUE THREAD

**Issue by wugelis** [aspnet/AspNetCore#7695] opened 2019-02-19 03:16 UTC
### Describe the bug
When I use variable name todo in Controller Action, And parameter name of the ToDoListViewModel. It is get null for all properties.

### To Reproduce
1. Using this version of ASP.NET Core '2.1.500'

2. Run this code

**My ToDoListViewModel:**

    [Serializable]
    public class ToDoListViewModel
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(10)]
        [Required]
        [Display(Name = "使用者名稱：")]
        public string UserName { get; set; }

        [MaxLength(50)]
        [Required]
        [Display(Name = "代辦事項（ToDo）：")]
        public string ToDo { get; set; }

        [Display(Name = "開始日期：")]
        public string StartDate { get; set; }

        [Display(Name = "結束日期：")]
        public string EndDate { get; set; }
    }

(2). Because property have 'ToDo', So the View page also use 'ToDo' in Tag Helpers!
https://i.imgur.com/RapmhuQ.jpg

**Default use the view page of the Tag Helper:**

`            <div class="form-group">
                <label asp-for="ToDo" class="control-label"></label>
                <input asp-for="ToDo" class="form-control" />
                <span asp-validation-for="ToDo" class="text-danger"></span>
            </div>`

3. With these arguments 'todo'

**It is get null fro all properties.**
https://i.imgur.com/bhuzNLV.jpg

**The parameter name is the Post action of 'todo':**

        [HttpPost]
        public IActionResult Create([BindRequired] ToDoListViewModel todo)
        {
            if (ModelState.IsValid)
            {
                var todoList = todo;

                _context.ToDoLists.Add(new Models.ToDoList() {
                    Name = todo.UserName,
                    ToDo = todo.ToDo,
                    StartDate = string.IsNullOrEmpty(todo.StartDate)?null:(DateTime?) Convert.ToDateTime(todo.StartDate),
                    EndDate = string.IsNullOrEmpty(todo.EndDate)?null:(DateTime?) Convert.ToDateTime(todo.EndDate)
                });

                _context.SaveChanges();
            }
            
            return RedirectToAction("ToDoList");
        }

**Interestingly, I am mark Tag Helper for 'ToDo':**

`            @*<div class="form-group">
                <label asp-for="ToDo" class="control-label"></label>
                <input asp-for="ToDo" class="form-control" />
                <span asp-validation-for="ToDo" class="text-danger"></span>
            </div>*@`

**It get all data for now!**
https://i.imgur.com/12bHsEr.jpg

**others Interestingly, When parameter name changed to 'model'.**

        [HttpPost]
        public IActionResult Create([BindRequired] ToDoListViewModel model)
        {
            if (ModelState.IsValid)
            {
                var todoList = model;

                _context.ToDoLists.Add(new Models.ToDoList() {
                    Name = model.UserName,
                    ToDo = model.ToDo,
                    StartDate = string.IsNullOrEmpty(model.StartDate)?null:(DateTime?) Convert.ToDateTime(model.StartDate),
                    EndDate = string.IsNullOrEmpty(model.EndDate)?null:(DateTime?) Convert.ToDateTime(model.EndDate)
                });

                _context.SaveChanges();
            }
            return RedirectToAction("ToDoList");
        }

### Expected behavior
I hope Tag Helper in use ToDo can to bind data.

### Screenshots

 It get all data for now!
Picture:
https://i.imgur.com/1xAUebh.jpg

**Comment by mkArtakMSFT** [comment] 2019-02-20 22:13
Thanks for contacting us, @wugelis.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment] 2019-02-20 23:48
Duplicate of https://github.com/aspnet/Mvc/issues/3735. Renaming the parameter (`toDo` -> `model`) is the fix for this.

An interesting thing to note is that [the analyzer that was added in 2.2](https://github.com/aspnet/Mvc/issues/7753) to warn about this specifically targets Controllers and not Razor Pages and Page models. I've added https://github.com/aspnet/AspNetCore/issues/7773 to track adding support for Razor Pages \ Page models as part of the analyzer.

**Closed by pranavkm** 2019-02-20 23:48 UTC
Labels: area-mvc, investigate

**Comment by wugelis** [comment] 2019-02-21 14:16
Thank you!

I just thinking at the time to get the Cause of the problem.

I have solved the problem by using rename.
Also know that it is my naming problem. I am sorry!

thank you very much!

Gelis
