### ISSUE TITLE
Netcore debugging broken on macOS in preview4 nightly

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#9165] opened 2019-04-08 15:31 UTC
Up to preview 3 one could use VS Code or VS Mac (with some issues) to compile, run and debug netcore3 projects. From a couple of weeks ago the nightly builds of preview 4 do not debug, I submitted a bug to the omnisharp project. It was analysed and determined that the issue is in the coreclr project.

The relevant issue is: https://github.com/dotnet/coreclr/issues/23773

What happens is that coreclr throws an exception on the start of debugging. This basically renders the macOS platform incapable of any netcore work until this is resolved.

I'm just logging it here for reference in case someone comes across this issue after preview 4 is released.

**Comment by Eilon** [comment] 2019-04-09 17:51
@tn-5 is there any action in ASP.NET Core? It looks like the issue is already reported in https://github.com/dotnet/coreclr/issues/23773, so I would like to know what additional tasks there are.

**Comment by tn-5** [comment] 2019-04-10 15:53
As far as I know no further action is required (as long as  dotnet/coreclr#23773 <https://github.com/dotnet/coreclr/issues/23773> is actually attended to).

As it stands it is not possible to do ANY netcore debugging on the mac platform. VS for mac disabled any compilation if netcore 3 preview is installed a few versions back (8.1 should address this but not sure about the release date). VS code worked fine up to this regression in coreclr.

**Comment by Eilon** [comment] 2019-04-11 17:13
Got it. Please track the coreclr issue to see status updates. Closing this.

**Closed by Eilon** 2019-04-11 17:13 UTC
