### ISSUE TITLE
Select is not binding

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#9716] opened 2019-04-24 13:22 UTC
I have placed select code on the out-of-box Blazer-Client/Server project's client for a select control and it is not binding. Note all other control types (textbox, checkbox, etc) on the same page are binding correctly. Is my syntax correct?

### To Reproduce 
Index.razor file
```
Index.razor file

@page "/"

<select bind="@testing">
    <option value="Unknown">Unknown</option>
    <option value="Male">Male</option>
    <option value="Female">Female</option>
    <option value="Other">Other</option>
</select>

@functions {
    string testing { get; set; } = "Female";
}

### Expected behavior
Female value is showing in select control. Currently Unknown is showing.

### Additional context
Project Type: Blazor Client-Server
Visual Studio 16.1.0 Preview 2
Microsoft.AspNetCore.Blazor 3.0.0-preview4-19216-03
Microsoft.AspNetCore.Blazor.Build 3.0.0-preview4-19216-03
NETStandard.Library 2.0.3

**Comment by rjmr97** [comment] 2019-04-24 23:07
I don't know if it the `select` binding is supposed to work with strings, but it does work with enums:

```
<select bind="@testing">
    <option value="@testingEnum.Unknown">Unknown</option>
    <option value="@testingEnum.Male">Male</option>
    <option value="@testingEnum.Female">Female</option>
    <option value="@testingEnum.Other">Other</option>
</select>


@functions {
    enum testingEnum { Unknown, Male, Female, Other };
    testingEnum testing { get; set; } = testingEnum.Female;
}
```


![image](https://user-images.githubusercontent.com/30321188/56699550-e4000680-66ed-11e9-828b-d7622d38078e.png)

**Comment by Andrzej-W** [comment] 2019-05-02 23:29
I think it is tracked here #5616

**Comment by VR-Architect** [comment] 2019-05-08 20:50
Yeah, enums was in the example in the documentation.  But not for non-enums :(

**Comment by VR-Architect** [comment] 2019-05-10 15:08
FYI, I saw a video yesterday from a SyncFusion Blazor avangelist who stated the issue is the fact bind attaches to the "value" attribute of the control and not the "checked" attribute for a radio button. He then showed how to use a onclick event to set the binding. 

That may be a work around for folks until a long-term solution is created?

**Comment by danroth27** [comment] 2019-06-14 16:47
When we fix this, we should verify the fix also resolves #11181

**Comment by MichelArendt** [comment] 2019-06-19 02:05
Don't think I can add much to the issue since It's already known. Anyways, it appears I'm experiencing the same issue with LONG data type:

```
[2019-06-19T01:58:06.162Z] Error: System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputSelect`1[System.Int64] does not support the type 'System.Int64'.
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.TryParseValueFromString(String value, T& result, String& validationErrorMessage)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1.set_CurrentValueAsString(String value)
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.<BuildRenderTree>b__4_0(String __value)
   at Microsoft.AspNetCore.Components.BindMethods.<>c__DisplayClass9_0.<SetValueHandler>b__0(UIEventArgs eventArgs)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Rendering.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I'm just very inexperienced on Github, but should I try a workaround until Preview 8 due to this?
**_mkArtakMSFT modified the milestones: 3.0.0-preview7, 3.0.0-preview8 on May 17_**

Thanks in advance!

**Comment by SteveSandersonMS** [comment] 2019-06-27 10:08
I see - this is a duplicate of https://github.com/aspnet/AspNetCore/issues/5616, so will close in favour of that one.

**Closed by SteveSandersonMS** 2019-06-27 10:08 UTC
Labels: area-blazor, investigate
