### ISSUE TITLE
[blazor]how to resolve prerender twice call ?

### ISSUE THREAD

**Issue by git-net** [aspnet/AspNetCore#16945] opened 2019-11-09 16:30 UTC
My component is instantiated twice, so ,if i write a lib ,i must avoid/careful use all before onafterrender things? what i can do？

**Comment by javiercn** [comment] 2019-11-10 11:39
@git-net thanks for contacting us.

When you prerender the component runs
OnInitialized
OnInitializedAsync
OnParametersSet
OnParametersSetAsync

When you don't prerender, the component runs
OnInitialized
OnInitializedAsync
OnParametersSet
OnParametersSetAsync
OnAfterRender
OnAfterRenderAsync

The first 4 methods will run twice, as the component is rendered twice, the first time into static html and the second one as an interactive component. You can avoid running code twice if you put it inside OnAfterRender, but otherwise it will run twice. As the component renders twice, is imperative that the same logic runs to produce the initial render.

**Comment by git-net** [comment] 2019-11-11 02:19
i have some logic that can't run twice,and OnAfterRender looks later.
now i move some code to OnAfterRender,and check firstrender.
```
if(firstrender) { 
  ..... // init code here;  
componentInit=true;//
this.StateHasChanged();
}
```
and change my render code
```
if(componentInit) builder........
```
i means,use (OnAfterRender and firstrender ) do init things, and  force component rerender,is right way?

**Comment by git-net** [comment] 2019-11-11 03:34
constructor run twice too.

**Comment by javiercn** [comment] 2019-11-11 11:17
@git-net That sounds abut right.

> constructor run twice too.

Yes, this is expected too, as the app  prerenders, shuts down and then starts again.

**Comment by javiercn** [comment] 2019-11-11 11:17
I'm closing this issue as the question has been answered and the behavior is by design.

**Closed** 2019-11-11 11:18 UTC
Labels: area-blazor, question
