### ISSUE TITLE
Razor Class Library - Static File Path

### ISSUE THREAD

**Issue by nfplee** [aspnet/AspNetCore#14562] opened 2019-09-29 18:26 UTC
I'm trying to remove the Startup class in my application. Therefore I have the changed the CreateHostBuilder method in my Program class to the following:

```
public static IHostBuilder CreateHostBuilder(string[] args) {
    return Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder => {
            webBuilder.UseApplication(Assembly.GetExecutingAssembly().FullName);
        });
}
```

Where UseApplication looks like:

```
public static IWebHostBuilder UseApplication(this IWebHostBuilder hostBuilder, string entryAssemblyName) {
    return hostBuilder.ConfigureServices((context, services) => ...)
        .Configure(app => ...)
        .UseSetting(WebHostDefaults.ApplicationKey, entryAssemblyName);
}
```

Note: Without the UseSetting(WebHostDefaults.ApplicationKey, entryAssemblyName) line the application doesn't run at all.

However I am having issues where the path to my static files in my razor class libraries (e.g. "~/_content/MyLibrary/js/app.js") now returns a 404.

I found that if I call the Configure extension method in my Program.cs file instead of the UseApplication extension method then it works fine so I tried looking into the source to see if I can fix it but so far everything I have tried has not worked.

I'm not sure if this is a bug or if there is some way to configure it that I have not found. I'd really appreciate the help.

Thanks

**Comment by rynowak** [comment] 2019-09-30 15:19
I think you're missing a call to `.UseContentRoot(Directory.GetCurrentDirectory())`

This tells the server to use the current directory as the root directory for the app.

One question though - if you're trying to get rid of startup - why replace all of `CreateDefaultBuilder` - the template code looks like:

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>(); // This is the startup part
                });
```

**Comment by Tratcher** [comment] 2019-09-30 16:11
> I found that if I call the Configure extension method in my Program.cs file instead of the UseApplication extension method then it works fine so I tried looking into the source to see if I can fix it but so far everything I have tried has not worked.

Is UseApplication defined in a different assembly?

`.UseSetting(WebHostDefaults.ApplicationKey, entryAssemblyName);` would normally deal with this.

**Comment by nfplee** [comment] 2019-09-30 16:44
@rynowak that didn't make a difference.

@Tratcher yeah UseApplication is in another assembly.

**Comment by nfplee** [comment] 2019-09-30 17:30
I've attached a sample application which shows the problem.

[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3672464/WebApplication1.zip)

**Comment by anurse** [comment] 2019-10-01 22:57
> However I am having issues where the path to my static files in my razor class libraries (e.g. "~/_content/MyLibrary/js/app.js") now returns a 404.

This seems like an issue in @javiercn 's static file manifest stuff.

**Comment by anurse** [comment] 2019-10-03 16:26
Bouncing over to MVC because it seems to be an issue in the static files support in Razor Class Libraries and I don't have a ton of context there.

**Comment by soeleman** [comment] 2019-10-06 06:31
With current sample [WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3672470/WebApplication1.zip), without any modification.

The static file 404 only happen when we running on IISExpress.
![14562_IISExpress](https://user-images.githubusercontent.com/309413/66265221-f2298580-e83c-11e9-837c-b6431b63cead.png)

The Project work fine
![14562_Project](https://user-images.githubusercontent.com/309413/66265225-0b323680-e83d-11e9-96f9-f3a25354d0e9.png)

And also fine on __dotnet run__
![14562_DotnetRun](https://user-images.githubusercontent.com/309413/66265228-200eca00-e83d-11e9-8846-09a3320b9e49.png)

**Comment by javiercn** [comment] 2019-10-07 13:44
@nfplee Seems you are not using generic host.

There might be an issue lurking with the old hosting mode. I'd recommend you move to use generic web host and that should fix it, if not, alterntively try calling UseStaticWebAssets on your IWebHostBuilder and that should also fix it.

**Comment by nfplee** [comment] 2019-10-07 15:02
@javiercn I am using the generic host. See my original post and my sample. I've also tried calling UseStaticWebAssets but it did not make a difference.

**Comment by javiercn** [comment] 2019-10-07 18:38
@nfplee I downloaded your app and it doesn't seem to be using generic host.

In any case, I switched it to use generic host and found that the issue is that you are passing in the full name (which contains version, etc) and that causes issues when static web assets tries to find the manifest file. If you switch it to use the assembly simple name, everything works:
```
Assembly.GetExecutingAssembly().GetName().Name
```

**Comment by javiercn** [comment] 2019-10-07 18:41
Closing this issue as there's no more action for us to take here.

**Closed by javiercn** 2019-10-07 18:41 UTC
Labels: area-mvc, investigate

**Comment by nfplee** [comment] 2019-10-08 07:48
@javiercn - Thanks, it looks like I over simplified the example as I thought I was using the generic web host. I used the generic web host in the original question. Your fix also seems to have done the trick.
