### ISSUE TITLE
Expose MVC JSON formatter using UTF8JsonReader/Writer (System.Text.Json)

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7837] opened 2019-02-22 02:26 UTC
cc @rynowak @mkArtakMSFT 

As UTF8 is the only supported encoding, we will create the UTF8JsonReader/Writer if the passed in encoding is UTF8, otherwise we will use a stream.

**Comment by davidfowl** [comment] 2019-02-22 02:39
Closing as dupe of https://github.com/aspnet/AspNetCore/issues/7256

**Closed by davidfowl** 2019-02-22 02:39 UTC
Labels: area-mvc, feature-Pipelines
