### ISSUE TITLE
[Blazor] Proposal: Async wrapper components

### ISSUE THREAD

**Issue by aL3891** [aspnet/AspNetCore#15383] opened 2019-10-24 18:23 UTC
#### Summary
Today it's not possible to await calls inside markup in blazor, however a very similar effect can be accomplished by wrapping the task in a component that awaits it in `ParametersSetAsync` and then outputs a renderfragment with the result. This approach also enabled rendering other markup while waiting for the task, such as a "loading" text.

I believe it will be very common for people to want to await things in markup, we certainly use it quite a bit, so it would useful to have in the framework.
Besides tasks there is also the async stream support in c#8 and being able to update values as they come in has been very useful for us as well.

I propose three components to enable this.

##### AsyncValue 
Takes a task<t> used to show a single value in an async fashion

##### AsyncList
Takes an `IAsyncEnumerable<T>` and appends values as they come in, useful for a log or a chat

##### AsyncUpdatedValue
Takes an `IAsyncEnumerable<T>` and updates the value in place, useful for a status label or progress bar

#### Open questions:
Is this even a good idea?
Does this already exist?
Use a renderfragment for loading or expose a property that can be bound to by the caller?
Better names?
Multiple components or a single one with configuration properties?
Better handling of prerendering? 

#### Example

    @page "/"

    <AsyncValue Source="@SomeValue">
        <LoadingContent>
            <p>Loading</p>
        </LoadingContent>
        <ChildContent>
            <p>@context</p>
        </ChildContent>
    </AsyncValue>

    <AsyncValue Source="@SomeValue">
        <p>@context</p>
    </AsyncValue>

    <AsyncUpdatedValue Source="@ASequenceOfValues">
        <p>@context%</p>
    </AsyncUpdatedValue>

    <ul>
        <AsyncList MaxCount="10" Source="@ASequenceOfValues">
            <li>@context</li>
        </AsyncList>
    </ul>
    <button @onclick="GetValue">GetValue</button>

    @code {
        public Task<int> SomeValue { get; set; }
        public IAsyncEnumerable<int> ASequenceOfValues { get; set; }

        protected override void OnAfterRender(bool firstRender)
        {
            if (firstRender)
            {
                SomeValue = GenerateValue();
                ASequenceOfValues = GenerateValues();
                StateHasChanged();
            }
        }

        public async Task<int> GenerateValue()
        {
            await Task.Delay(1000);
            return 5;
        }

        public async Task GetValue()
        {
            SomeValue = GenerateValue();
            ASequenceOfValues = GenerateValues();
        }

        public async IAsyncEnumerable<int> GenerateValues()
        {
            for (int i = 0; i < 100; i++)
            {
                await Task.Delay(100);
                yield return i;
            }
        }
    }

#### AsyncValue 

    @typeparam T

    @if (_loading)
    {
        @LoadingContent
    }
    else
    {
        @ChildContent(_value)
    }

    @code {
        T _value;
        bool _loading  = true;

        [Parameter]
        public Task<T> Source { get; set; }
        [Parameter]
        public RenderFragment<T> ChildContent { get; set; }
        [Parameter]
        public RenderFragment LoadingContent { get; set; }

        protected override async Task OnParametersSetAsync()
        {
            _loading = true;
            if (Source != null)
            {
                _value = await Source;
                _loading = false;
            }
        }
    }

#### AsyncList

    @typeparam T

    @if (_loading)
    {
        @LoadingContent
    }

    else
    {
        @foreach (var item in _values)
        {
            @ChildContent(item)
        }
    }

    @code {
        Queue<T> _values = new Queue<T>();
        bool _loading = true;

        [Parameter]
        public IAsyncEnumerable<T> Source { get; set; }
        [Parameter]
        public int MaxCount { get; set; } = int.MaxValue;

        [Parameter]
        public RenderFragment<T> ChildContent { get; set; }
        [Parameter]
        public RenderFragment LoadingContent { get; set; }

        protected override async Task OnParametersSetAsync()
        {
            _loading = true;
            _values.Clear();

            if (Source != null)
            {
                await foreach (var item in Source)
                {
                    _values.Enqueue(item);
                    _loading = false;
                    if (_values.Count > MaxCount)
                        _values.Dequeue();
                    StateHasChanged();
                }
            }
        }
    }

#### AsyncUpdatedValue

    @typeparam T

    @if (_loading)
    {
        @LoadingContent
    }
    else
    {
        @ChildContent(_value)
    }

    @code {
        T _value;
        bool _loading = true;

        [Parameter]
        public IAsyncEnumerable<T> Source { get; set; }
        [Parameter]
        public RenderFragment<T> ChildContent { get; set; }
        [Parameter]
        public RenderFragment LoadingContent { get; set; }

        protected override async Task OnParametersSetAsync()
        {
            _loading = true;
            if (Source != null)
            {
                await foreach (var item in Source)
                {
                    _value = item;
                    _loading = false;
                    StateHasChanged();
                }
            }
        }
    }

**Comment by javiercn** [comment] 2019-10-24 22:42
@aL3891 Thanks for contacting us.

Blazor already supports this type of behavior without the need to wrap things inside a component. When you do async work inside a component we call StateHasChanged after the synchronous part has finished running and again later when the asynchronous part finishes running.

For example, if you override `OnInitAsync` and do something like this:

```razor
if(_data == null){
   <p>...Loading</p>
}else{
   @* Show data *@
}

@code{
  List<string> _data;
  OnInitAsync(){
  
  // A render will be triggered here
  _ data = await GetData()
  // Another render will be triggered here
  }
}
```

Isn't this what you are looking for?

**Comment by aL3891** [comment] 2019-10-25 10:57
Not really, i mean that is also good, but what i wanted to enable was the equivalent of awaiting something inside the markup itself, witch is not supported as far as i understand.

Also, doing this with a lot of tasks in a view can get a little verbose in my opinion, especially if i don't want to specify the order in witch they should be awaited. 

Having IAsyncEnumerable support is also something that would be nice for the same reason, and that also results in a lot of very similar code. StateHasChanged is also necessary here because the async work is not finished, the iteration of the async stream is still going on, but the view should still re-render. At least that seems to be the case from my testing, but perhaps i missed something.

**Comment by javiercn** [comment] 2019-10-25 11:10
I don't think we plan to introduce something like this on the framework itself. This is a good space for component libraries to fill-in if they feel there is a gap in the experience.

The framework goes to great lengths to avoid requiring the user to call state has changed, and for the most parts it succeeds in doing so.

With regards to the IAsyncEnumerable I feel that rather than wrapping the component inside another component it's easier to wrap the IAsyncEnumerable in some other IAsyncEnumerable that calls StateHasChanged through an extension method.

```
protected Task OnInitializedAsync()
{
    await foreach(var result in GetAsyncEnumerable().WithStateUpdate(this))
    {
        elements.Add(result);
    }
}
```

In your async IEnumerable you would call StateHasChanged inside each call to MoveNext() and that would be a potential solution.

**Comment by aL3891** [comment] 2019-10-25 15:35
Fair enough, I thought I'd share it since I've found this approach useful, perhaps it will be useful to someone else as well :)

Wrapping the iasyncenumerale in another one that calls StateUpdateChanged is a good approach, however the main value of this approach in my opinion is the ability to essentially use async calls directly in the markup without adding intermediate properties to the component.

One example for this is a list of users for example, where upon load, each item kicks of an async request for the user name or some other data. Of course this can be solved in alot of different ways but I've found this to be a very clean way to do it.

**Comment by javiercn** [comment] 2019-10-25 15:37
@aL3891 Rendering in Blazor is sync by design. It needs to be really fast and if it was async, it would be much harder to make it performant.

**Comment by javiercn** [comment] 2019-10-25 16:20
Thanks for the suggestion.

We are closing this issue as we don't plant to include this functionality in the framework.

**Closed by javiercn** 2019-10-25 16:20 UTC
Labels: area-blazor, question

**Comment by aL3891** [comment] 2019-10-29 10:54
I know that, but i think a solution like this would enable users to get the best of both worlds by buth having the actual rendering to not be async while still semantically "awaiting" async code inside the markup.
