### ISSUE TITLE
Razor Components bound textarea not working properly without WebSocket

### ISSUE THREAD

**Issue by wanton7** [aspnet/AspNetCore#6301] opened 2019-01-02 18:37 UTC
### Describe the bug
If you disable WebSocket for BlazorHub then textarea that uses bind, then textarea starts reverting to earlier text while you are writing to it.
I wanted to test Razor Components with higher latency so I wanted to disable WebSocket so browsers throttling will work.

### To Reproduce
```html
@page "/oddness"

<textarea style="width:100%;resize:vertical" rows="5" bind-value-oninput="@Text"></textarea>
<div>@Text</div>

@functions {
    string Text { get; set; }
}
```
Then instead of `app.UseServerSideBlazor<App.Startup>();` use
```
app.UseSignalR(route => route.MapHub<BlazorHub>(BlazorHub.DefaultPath, opts => opts.Transports &= ~Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets));
app.UseBlazor<App.Startup>();
```

If you apply browser throttling (added latency) it will get much worse.

### Expected behavior
That textarea would work normally

### Additional context
I used these NuGets
```xml
<PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="0.8.0-preview1-20181126.4" />
<PackageReference Include="Microsoft.AspNetCore.Components.Build" Version="0.8.0-preview1-20181126.4" PrivateAssets="all" />
```

**Comment by mkArtakMSFT** [comment] 2019-04-05 16:46
Thanks for contacting us, @wanton7.
We believe this is dupe of #8204.

**Closed by mkArtakMSFT** 2019-04-05 16:46 UTC
Labels: area-mvc, feature-Components
