### ISSUE TITLE
[Test failure] RunIndividualTestCase

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#6691] opened 2019-01-14 23:06 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=72170
```
2019-01-14T18:59:54.8230988Z   Failed   RunIndividualTestCase(testCase: http2/6.10/6, HTTPS:True, Sends a CONTINUATION frame preceded by a DATA frame)
2019-01-14T18:59:54.8233132Z   Error Message:
2019-01-14T18:59:54.8238293Z    System.TimeoutException : h2spec didn't exit within 30 seconds.
2019-01-14T18:59:54.8240542Z   Stack Trace:
2019-01-14T18:59:54.8243309Z      at Interop.FunctionalTests.H2SpecCommands.RunTest(String testId, Int32 port, Boolean https, ILogger logger) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 194
2019-01-14T18:59:54.8245293Z      at Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase(H2SpecTestCase testCase) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 51
2019-01-14T18:59:54.8247660Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-14T18:59:54.8249742Z   Standard Output Messages:
2019-01-14T18:59:54.8250683Z    | [0.001s] TestLifetime Information: Starting test RunIndividualTestCase-http2/6.10/6, HTTPS:True, Sends a CONTINUATION frame preceded by a DATA frame at 2019-01-14T18:59:24
2019-01-14T18:59:54.8252544Z    | [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
2019-01-14T18:59:54.8254187Z    | [0.019s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
2019-01-14T18:59:54.8258586Z    | [0.020s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Interop.FunctionalTests
2019-01-14T18:59:54.8260289Z    | [0.080s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLJQA9HEKVG0" started.
2019-01-14T18:59:54.8260950Z    | [0.102s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
2019-01-14T18:59:54.8261417Z    | [0.102s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
2019-01-14T18:59:54.8264020Z    | [0.102s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
2019-01-14T18:59:54.8289043Z    | [0.102s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
2019-01-14T18:59:54.8289550Z    | [0.103s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
2019-01-14T18:59:54.8292686Z    | [0.103s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" received HEADERS frame for stream ID 1 with length 16 and flags NONE
2019-01-14T18:59:54.8293202Z    | [0.103s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" received DATA frame for stream ID 1 with length 4 and flags END_STREAM
2019-01-14T18:59:54.8295726Z    | [0.103s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLJQA9HEKVG0": HTTP/2 connection error.
2019-01-14T18:59:54.8296249Z    | Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): The client sent a DATA frame to stream ID 1 before signaling of the header block for stream ID 1.
2019-01-14T18:59:54.8296711Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessDataFrameAsync(ReadOnlySequence`1 payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 431
2019-01-14T18:59:54.8297097Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 400
2019-01-14T18:59:54.8297508Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 203
2019-01-14T18:59:54.8298251Z    | [0.104s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLJQA9HEKVG0" is closed. The last processed stream ID was 1.
2019-01-14T18:59:54.8298546Z    | [0.104s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJQA9HEKVG0" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
2019-01-14T18:59:54.8298978Z    | [0.104s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLJQA9HEKVG0" sending FIN because: "The Socket transport's send loop completed gracefully."
2019-01-14T18:59:54.8299281Z    | [0.105s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLJQA9HEKVG0" stopped.
2019-01-14T18:59:54.8299523Z    | [30.031s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
2019-01-14T18:59:54.8299825Z    | [30.032s] TestLifetime Information: Finished test RunIndividualTestCase-http2/6.10/6, HTTPS:True, Sends a CONTINUATION frame preceded by a DATA frame in 30.0313818s
2019-01-14T18:59:54.8300096Z   
2019-01-14T18:59:54.8300496Z   
2019-01-14T19:00:22.4382260Z   Results File: F:\vsagent\2\s\artifacts\logs\Interop.FunctionalTests-netcoreapp3.0-20190114.12.trx
2019-01-14T19:00:22.4383192Z   
2019-01-14T19:00:22.4389365Z   Total tests: 293. Passed: 291. Failed: 1. Skipped: 1.
2019-01-14T19:00:22.4393600Z   Test execution time: 1.1051 Minutes
```

@Tratcher @halter73

**Comment by jkotalik** [comment] 2019-01-16 21:51
Another one: https://dev.azure.com/dnceng/public/_build/results?buildId=74189

**Comment by muratg** [comment] 2019-02-04 18:36
Does this still happen?

**Comment by jkotalik** [comment] 2019-02-08 02:36
Are they? https://dev.azure.com/dnceng/public/_build/results?buildId=90177

**Comment by Tratcher** [comment] 2019-02-08 03:35
I just turned them back on with additional debugging.

**Comment by pranavkm** [comment] 2019-02-09 21:30
Another failure here - https://dev.azure.com/dnceng/public/_build/results?buildId=91312. Skipping the test as part of https://github.com/aspnet/AspNetCore/pull/7165/commits/c14f2ab745232d8ce9f24dcf631467a4733e447b (ongoing PR)

**Comment by Tratcher** [comment] 2019-02-09 23:11
Oh good, the verbose logs may have finally tracked down a bug in the client.
```
2019-02-09T02:34:39.8786527Z   [xUnit.net 00:00:42.57]     RunIndividualTestCase(testCase: http2/4.3/3, HTTPS:False, Sends a HEADERS frame to another stream while sending the header blocks) [FAIL]
2019-02-09T02:35:14.2263772Z   Failed   RunIndividualTestCase(testCase: http2/4.3/3, HTTPS:False, Sends a HEADERS frame to another stream while sending the header blocks)
2019-02-09T02:35:14.2265139Z   Error Message:
2019-02-09T02:35:14.2266481Z    System.TimeoutException : h2spec didn't exit within 30 seconds.
2019-02-09T02:35:14.2266877Z   Stack Trace:
2019-02-09T02:35:14.2267479Z      at Interop.FunctionalTests.H2SpecCommands.RunTest(String testId, Int32 port, Boolean https, ILogger logger) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 225
2019-02-09T02:35:14.2268245Z      at Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase(H2SpecTestCase testCase) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 52
2019-02-09T02:35:14.2268915Z   --- End of stack trace from previous location where exception was thrown ---
2019-02-09T02:35:14.7012619Z   Standard Output Messages:
2019-02-09T02:35:14.9978804Z    | [0.001s] TestLifetime Information: Starting test RunIndividualTestCase-http2/4.3/3, HTTPS:False, Sends a HEADERS frame to another stream while sending the header blocks at 2019-02-09T02:34:09
2019-02-09T02:35:15.0018691Z    | [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
2019-02-09T02:35:15.0034466Z    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
2019-02-09T02:35:15.0065632Z    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Interop.FunctionalTests
2019-02-09T02:35:15.0078218Z    | [0.058s] Interop.FunctionalTests.H2SpecTests Debug: Hypertext Transfer Protocol Version 2 (HTTP/2)
2019-02-09T02:35:15.0086390Z    | [0.060s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLKE6S61NCL3" started.
2019-02-09T02:35:15.0094188Z    | [0.062s] Interop.FunctionalTests.H2SpecTests Debug:   4. HTTP Frames
2019-02-09T02:35:15.0101296Z    | [0.062s] Interop.FunctionalTests.H2SpecTests Debug:     4.3. Header Compression and Decompression
2019-02-09T02:35:15.0109784Z    | [0.062s] Interop.FunctionalTests.H2SpecTests Debug:            [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
2019-02-09T02:35:15.0117699Z    | [0.062s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
2019-02-09T02:35:15.0125687Z    | [0.062s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
2019-02-09T02:35:15.0138673Z    | [0.062s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
2019-02-09T02:35:15.0153366Z    | [0.062s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] SETTINGS Frame (length:18, flags:0x00, stream_id:0)
2019-02-09T02:35:15.0164659Z    | [0.063s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
2019-02-09T02:35:15.0174787Z    | [0.063s] Interop.FunctionalTests.H2SpecTests Debug:            [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
2019-02-09T02:35:15.0185840Z    | [0.063s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
2019-02-09T02:35:15.0194456Z    | [0.063s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] WINDOW_UPDATE Frame (length:4, flags:0x00, stream_id:0)
2019-02-09T02:35:15.0212247Z    | [0.063s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
2019-02-09T02:35:15.0221798Z    | [0.063s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" received HEADERS frame for stream ID 1 with length 16 and flags NONE
2019-02-09T02:35:15.0227797Z    | [0.063s] Interop.FunctionalTests.H2SpecTests Debug:            [send] HEADERS Frame (length:16, flags:0x00, stream_id:1)
2019-02-09T02:35:15.0231510Z    | [0.063s] Interop.FunctionalTests.H2SpecTests Debug:            [send] HEADERS Frame (length:4, flags:0x05, stream_id:3)
2019-02-09T02:35:15.0238248Z    | [0.063s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" received HEADERS frame for stream ID 3 with length 4 and flags END_STREAM, END_HEADERS
2019-02-09T02:35:15.0244902Z    | [0.064s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLKE6S61NCL3": HTTP/2 connection error.
2019-02-09T02:35:15.0252832Z    | Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): The client sent a HEADERS frame to stream ID 3 before signaling of the header block for stream ID 1.
2019-02-09T02:35:15.0256896Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessHeadersFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 487
2019-02-09T02:35:15.0261630Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 410
2019-02-09T02:35:15.0263193Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 306
2019-02-09T02:35:15.0274497Z    | [0.064s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLKE6S61NCL3" is closed. The last processed stream ID was 1.
2019-02-09T02:35:15.0319184Z    | [0.064s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE6S61NCL3" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
2019-02-09T02:35:15.0338233Z    | [0.064s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLKE6S61NCL3" sending FIN because: "The Socket transport's send loop completed gracefully."
2019-02-09T02:35:15.0344876Z    | [0.065s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLKE6S61NCL3" stopped.
2019-02-09T02:35:15.0348639Z    | [0.102s] Interop.FunctionalTests.H2SpecTests Debug:            [send] CONTINUATION Frame (length:3512, flags:0x04, stream_id:1)
2019-02-09T02:35:15.0355131Z    | [0.103s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:35:15.0362897Z    | [0.103s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:35:15.0379015Z    | [0.103s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:35:15.0392690Z    | [0.103s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:35:15.0398480Z    | [0.103s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
... repeated a few thousand times
2019-02-09T02:36:24.3117269Z    | [29.999s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:36:24.3118781Z    | [30.000s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:36:24.3119660Z    | [30.000s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:36:24.3120918Z    | [30.000s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:36:24.3122019Z    | [30.000s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:63806->127.0.0.1:63805: wsarecv: An established connection was aborted by the software in your host machine.
2019-02-09T02:36:24.3123038Z    | [30.013s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
2019-02-09T02:36:24.3124463Z    | [30.048s] TestLifetime Information: Finished test RunIndividualTestCase-http2/4.3/3, HTTPS:False, Sends a HEADERS frame to another stream while sending the header blocks in 30.0465251s
```

**Comment by Tratcher** [comment] 2019-02-11 16:54
Duplicate of https://github.com/aspnet/AspNetCore-Internal/issues/1786

**Closed by Tratcher** 2019-02-11 16:54 UTC
Labels: area-servers, servers-kestrel, test-failure

**Comment by halter73** [comment] 2019-02-11 21:41
> wsarecv: An established connection was aborted by the software in your host machine.

This might be related to https://github.com/aspnet/AspNetCore/issues/4703
