### ISSUE TITLE
Generate const for Route from the @page keyword

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/AspNetCore#9674] opened 2019-04-23 09:58 UTC
### Is your feature request related to a problem? In general I prefer to eliminate magic strings.  The current code generated for the @page requires the associated NavLink to use a magic string as in the demo app:

```
<NavLink class="nav-link" href="counter">
```

### Describe the solution you'd like
```
    [Microsoft.AspNetCore.Components.RouteAttribute(Route)]
    [Microsoft.AspNetCore.Components.RouteAttribute(Route2)]
    public class Admin
    {
      public const string Route = "/admin";
      public const string Route2= "/otheradmin";
```
Thus the NavLink would not need a magic string 

```
<NavLink class="nav-link" href="Admin.Route">
```
### Describe alternatives you've considered
We could add 

```
public const string Route = "/admin"; 
```

to the class ourselves but the @page directive currently won't let me reference that.

### Additional context

I took a quick search trying to find where the code for the .g.cs files gets generated and was unable to locate it.  If this is acceptable change then maybe we more readily get community assistance on this if you point us to the source area. 

Thanks!   Blazor Rocks!

**Comment by SteveSandersonMS** [comment] 2019-04-23 20:36
It’s a great idea. So great that we already have an issue tracking this :)

Closing as a duplicate of https://github.com/aspnet/AspNetCore/issues/6352

**Closed by SteveSandersonMS** 2019-04-23 20:36 UTC
Labels: area-mvc, feature-Components

**Comment by StevenTCramer** [comment] 2019-04-24 02:32
I searched really I swear I did.  The new GH interface even searches automatic.   Sorry I didn't see it. :)
