### ISSUE TITLE
.net core 2.2 Downward compatibility problem（about cross domain）

### ISSUE THREAD

**Issue by JiangJiaqi90** [aspnet/AspNetCore#5155] opened 2018-12-17 08:19 UTC
The code which developmented on .net core 2.1 SDK , when it  runs on the .net core 2.2 runtime, the signalr does not support cross-domain.
When I switch back to 2.1 runtime,the cross-domain problem solving.
In the same way, only signalr does not support cross-domain on Windows , and even common API on ubuntu do not support cross-domain .The solution is the same as above.

**Comment by BrennanConroy** [comment] 2019-01-02 18:11
Dupe of https://github.com/aspnet/AspNetCore/issues/4483#issuecomment-445081348?

**Comment by pranavk** [comment] 2019-01-10 04:38
@bradygaster I think you incorrectly mentioned me.

**Comment by pranavkm** [comment] 2019-01-30 14:42
Very likely a dup of the other issue. @JiangJiaqi90 feel free to reopen if you believe this is a different issue.

**Closed by pranavkm** 2019-01-30 14:42 UTC
Labels: area-mvc
