### ISSUE TITLE
Unknown html tags raise no warning.

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/AspNetCore#9799] opened 2019-04-27 06:01 UTC
### Is your feature request related to a problem? Please describe.
When one is missing an import for a Component, the tag is just rendered into the HTML. Which may be fine and desired but when not it is hard to find them.

### Describe the solution you'd like
I would like a setting that can enable "Unkown HTML tags": severity: warning.

### Describe alternatives you've considered
Manually looking for them in the editor.  Or running app and look for missing pieces.

**Comment by conficient** [comment] 2019-04-27 20:43
Related to #9786

**Comment by mkArtakMSFT** [comment] 2019-05-01 16:52
Thanks @conficient.
This is indeed a dupe of the referenced issue

**Closed by mkArtakMSFT** 2019-05-01 16:52 UTC
Labels: area-mvc, feature-Components
