### ISSUE TITLE
GeneratePasswordResetTokenAsync does not clear existing PasswordResetTokens for a user

### ISSUE THREAD

**Issue by nauticalcoder** [aspnet/AspNetCore#9953] opened 2019-05-03 20:35 UTC
When using GeneratePasswordResetTokenAsync to generate a password reset token, it is not clearing out existing tokens for the user so if a user generates multiple password reset tokens, they all appear to be recognized.  We would expect that only the latest token will still be active.  We should at least have a method to allow clearing the password reset tokens for a user (like ResetAuthenticatorKeyAsync for 2FA).

**Comment by HaoK** [comment] 2019-05-03 21:16
this is by design of using self signed tokens that expire that aren't stored in the database, but changing the security stamp of the user, which happens automatically when the password or other security things automatically will invalidates any outstanding tokens that are based on the security stamp

**Comment by HaoK** [comment] 2019-05-03 21:17
So its technically true that all the tokens are valid...until you change your password, then ALL of the tokens will be invalid.

**Comment by nauticalcoder** [comment] 2019-05-03 21:37
Thanks for clarifying this and it makes sense now.  It appears that if we did want it to behave as I described where only the latest token works, that we would have to also UpdateSecurityStampAsync each time we generate a password reset token.

**Closed** 2019-05-03 22:00 UTC
Labels: area-identity
