### ISSUE TITLE
Error UI

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9009] opened 2019-04-02 21:47 UTC
* When the application errors out we don't produce any visual indication (other than the console).
  * We should display some UI when an error ocurs in the server so that developers can better visualize errors.

**Comment by rynowak** [comment] 2019-04-03 05:37
Dupe of: https://github.com/aspnet/AspNetCore/issues/8613

**Comment by SteveSandersonMS** [comment] 2019-04-03 16:07
Closing as dupe then. The other bug has a lot more detail.

**Closed by SteveSandersonMS** 2019-04-03 16:07 UTC
Labels: area-mvc, enhancement, feature-Components
