### ISSUE TITLE
Blazor server side template in VS 2019 throws System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Endpoints.EndpointHttpContextExtensions'

### ISSUE THREAD

**Issue by lusocoding** [aspnet/AspNetCore#11156] opened 2019-06-12 21:32 UTC
### Describe the bug
A TypeLoadException is thrown when attempting to start a Blazor server side web application that is created using the default VS 2019 templates.

### To Reproduce

1. Steps to reproduce the behavior:
2. Enable "Use previews of .NET Core SDK" in VS 2019 options (Environment > Preview Features)
3. Using the New Project dialog, create a server side Blazor web application
4. Hit F5 to start the application
5. See error in browser

### Expected behavior
The example web application should start without any exceptions being thrown

### Additional context

> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
>       Request starting HTTP/1.1 GET http://localhost:1693/
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Endpoints.EndpointHttpContextExtensions' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, Func`1 next)
>    at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished in 295.373ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
>       Request starting HTTP/1.1 GET http://localhost:1693/favicon.ico
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Endpoints.EndpointHttpContextExtensions' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, Func`1 next)
>    at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished in 17.568ms 500 text/plain

**dotnet --info**

> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100-preview6-012264
>  Commit:    be3f0c1a03
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\
> 
> Host (useful for support):
>   Version: 3.0.0-preview6-27804-01
>   Commit:  fdf81c6faf
> 
> .NET Core SDKs installed:
>   1.1.13 [C:\Program Files\dotnet\sdk]
>   1.1.14 [C:\Program Files\dotnet\sdk]
>   2.1.602 [C:\Program Files\dotnet\sdk]
>   2.1.604 [C:\Program Files\dotnet\sdk]
>   2.1.700 [C:\Program Files\dotnet\sdk]
>   2.2.202 [C:\Program Files\dotnet\sdk]
>   2.2.204 [C:\Program Files\dotnet\sdk]
>   2.2.300 [C:\Program Files\dotnet\sdk]
>   3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by SteveSandersonMS** [comment] 2019-06-12 22:34
This app doesn’t look like it was created using the default template, since the stack trace implies it uses SpaDefaultPageMiddleware. The current templates don’t use that.

Are you trying to upgrade an existing application?

**Comment by lusocoding** [comment] 2019-06-12 22:49
No... It's the first Blazor web app I'm creating using VS 2019 and I did nothing else except the reproduce steps I mentioned in the ticket. I've tried to create another application from the template, same issue.

You can see all steps on this gif. Currently using VS 2019 Enterprise, version 16.1.3

![test](https://user-images.githubusercontent.com/114126/59391589-a8d49800-8d6c-11e9-9cc3-0b3e261d6dad.gif)

**Comment by RickStrahl** [comment] 2019-06-13 00:58
Same for me...

**Comment by SteveSandersonMS** [comment] 2019-06-13 06:40
I was confused because the issue says server-side, but you’re both actually creating client-side (hosted) apps. 

To create client-side apps, did you update to the preview 6 version of the Blazor VSIX?

**Comment by RickStrahl** [comment] 2019-06-13 08:28
I did:
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2
```

which brought in the Visual Studio template. And I'm running latest VS Preview Update that showed up today.

**Comment by SteveSandersonMS** [comment] 2019-06-13 08:31
Unfortunately running that command does *not* update the templates inside VS. You do have to install the newer VSIX.

I know it would be better if the .NET CLI and VS could keep themselves in sync better than this, but unfortunately there's still some way to go on that.

**Comment by SteveSandersonMS** [comment] 2019-06-13 08:32
> Also tried dotnet new for blazor client with the same result (as expected).

That's strange though. I'll see if I can reproduce this.

**Comment by SteveSandersonMS** [comment] 2019-06-13 09:13
I'm afraid I've been unable to reproduce this. I have the full set of preview 6 bits, i.e.:

 * VS 2019 16.2.0 Preview 2
    * … into which I installed the latest Blazor extension (16.0.19307.2)
 * NET Core 3.0 Preview 6 (so “dotnet --version" prints 3.0.100-preview6-012264)

... and the "Blazor hosted" template works correctly both on the command line and from VS.

If you have any further information about how to reproduce the issue, please let us know.

**Comment by VladislavAntonyuk** [comment] 2019-06-13 14:28
replace app.UseBlazor with
```
app.UseClientSideBlazorFiles<Client.Startup>();
app.UseRouting();
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
                endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");
            });
```

**Comment by maheshkumarjadhav** [comment] 2019-06-14 01:33
**To create and run Blazor (ASP.NET Core hosted) App**

Please follow below steps as per Get started with Blazor | Microsoft Docs

1. Install the latest .NET Core 3.0 Preview SDK release.
2. Install the Blazor templates by running the following command in a command shell:
      dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2
3. Install the latest Blazor extension from the Visual Studio Marketplace. This step makes Blazor templates available to Visual Studio.

Once you install you can create **Blazor client-side** and **Blazor server-side** using Visual Studio.


However if you are unable to run **Blazor (ASP.NET Core hosted)**  app then follow given steps , execute the following commands from a command shell:

1. Make sure you have Blazor (ASP.NET Core hosted)  template installed using  **dotnet new -l** command

2. If you see Blazor (ASP.NET Core hosted)/blazorhosted listed then please follow below commons to create new Blazor (ASP.NET Core hosted) app using below command

            dotnet new blazorhosted -o WebApplication1
            cd WebApplication1.Server
            dotnet run
3. you can see below details on command

Hosting environment: Development
Content root path: ...\WebApplication1.Server
Now listening on: http://localhost:2470 [ Port can be different for you]

4. Open modern browser and navigate to localhost Url shown on your command window

**Comment by dougkuchna** [comment] 2019-06-17 15:08
@maheshkumarjadhav, followed your instructions and when navigating to http://localhost:5000 receive the following:
fail: Microsoft.AspNetCore.Server.Kestrel[13]                                                                                                                                                                           Connection id "0HLNJ6GDI37UA", Request id "0HLNJ6GDI37UA:00000001": An unhandled exception was thrown by the application.                                                                                   System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Endpoints.EndpointHttpContextExtensions' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by kakins** [comment] 2019-06-17 20:49
> @maheshkumarjadhav, followed your instructions and when navigating to http://localhost:5000 receive the following:
> fail: Microsoft.AspNetCore.Server.Kestrel[13] Connection id "0HLNJ6GDI37UA", Request id "0HLNJ6GDI37UA:00000001": An unhandled exception was thrown by the application. System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Endpoints.EndpointHttpContextExtensions' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I receive this error too, but I downloaded the SDK and am running the app in VS Code, using `dotnet run`.  The app builds and runs, however, whenever I access localhost I get the above error.

**Comment by mvr-devs** [comment] 2019-06-17 22:43
@maheshkumarjadhav followed your instructions... Had done all of them EXCEPT the newer extension from the marketplace once I did that the type load exception went away.

**Comment by diego81b** [comment] 2019-06-19 10:14
My problem was that Blazor server-side and Blazor client-side template are scaffolded with preview6 but Blazor (ASP.NET Core hosted) is scaffolded with preview5 (using Visual Studio 2019 16.1.3.

I suppose it's related to Visual Studio 2019 version that is not a preview

**Comment by mkArtakMSFT** [comment] 2019-06-25 16:51
Closing this as this seem to be resolved already.

**Closed by mkArtakMSFT** 2019-06-25 16:51 UTC
Labels: area-blazor
