### ISSUE TITLE
Allow ComponentFactory to be extended

### ISSUE THREAD

**Issue by BickelLukas** [aspnet/AspNetCore#5638] opened 2018-11-13 15:30 UTC
When using a custom DI container that doesn't provide an IServiceProvider it's not possible to inject services into components.

I'm using SimpleInjector as a DI container. Now I can't inject services into Views that were registered into that container.

It would be great If the renderer wouldn't depend on the IServiceProvider but instead take an IComponentFactory that I can then override to provide my own implementation using my DI container. 

Here's a great post on the creator of SimpleInjector on this topic: https://simpleinjector.org/blog/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/

**Comment by mkArtakMSFT** [comment] 2019-04-15 16:30
Closing this as a dupe of https://github.com/aspnet/AspNetCore/issues/7962

**Closed by mkArtakMSFT** 2019-04-15 16:30 UTC
Labels: area-mvc, feature-Components
