### ISSUE TITLE
Blazor Client Side App can't be started with custom App Url with .NET Core 3 Preview 5

### ISSUE THREAD

**Issue by TFTomSun** [aspnet/AspNetCore#10226] opened 2019-05-14 08:04 UTC
### To Reproduce
1. Create a client side blazor app
2. open project settings
3. change app url to e.g. http://localhost:60792/test/
4. The error appears

![image](https://user-images.githubusercontent.com/5387192/57681121-5b5ef100-762f-11e9-8f24-7b3bed8c2c89.png)

### Expected behavior
The browser starts with the specified url and opens the app (like in blazor 0.7)

**Comment by danroth27** [comment] 2019-05-14 16:52
Hi @TFTomSun,

Could you please provide the contents of the log file mentioned in the error dialog?

I'm unable to reproduce this issue myself. When I change the app URL I get 404s for the static assets for the site because the base URL in the *index.html* file is set to `/`. If I update the base URL to then be `/test/` then everything works fine again.

**Comment by danroth27** [comment] 2019-05-20 22:49
Since we can't reproduce this, I'm going to go ahead and close this issue.

**Closed by danroth27** 2019-05-20 22:49 UTC
Labels: area-blazor, question
