### ISSUE TITLE
Missing Self Hosted Template

### ISSUE THREAD

**Issue by 274188A** [aspnet/AspNetCore#12348] opened 2019-07-19 08:36 UTC
### Missing Self Hosted Template
Trying to Create a new ASP.NET Core Web Application
Wanting to use the Self Host Balzor template

**PROBLEM**:
It is not there - instead I have a duplicate Blazor WebAssembly App

[LINK TO SCREEN SHOT](https://ibb.co/m8mNCjB)

Installed SDK - .NET Core 3.0 Preview 6 SDK (3.0.100-preview6-012264)
Installed the latest Blazor extension from the Visual Studio Marketplace.
ran dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2

**VISUAL STUDIO**
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.2.0 Preview 4.0
VisualStudio.16.Preview/16.2.0-pre.4.0+29111.141
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Enterprise

**Comment by mkArtakMSFT** [comment] 2019-07-19 16:25
Thanks for contacting us, @274188A.
This is a dupe of #11706.

**Closed by mkArtakMSFT** 2019-07-19 16:25 UTC
Labels: area-blazor
