### ISSUE TITLE
SignalR 3.0 and Xamarin Forms 

### ISSUE THREAD

**Issue by ScarlettCode** [aspnet/AspNetCore#16875] opened 2019-11-06 17:50 UTC
### Describe the bug

After adding Signal R and then launching the app, after the splash screen loads this error gets thrown.

System.TypeLoadException
  Message=Could not load type of field 'Microsoft.AspNetCore.Http.Features.Authentication.HttpAuthenticationFeature:<Handler>k__BackingField' (1) due to: Could not resolve type with token 0100007c from typeref (expected class 'Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler' in assembly 'Microsoft.AspNetCore.Http.Features, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Http.Features, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler member:(null)

### To Reproduce

I tried reproducing with a new solution with all the same nuget's but unfortunately it works.. the worst kind of error. If someone could point me in the right direction of how to debug this. I'm guessing from another similar issue #14543 that it's a transitive dependency but I'm not sure how I work out what is it.

### Further technical details

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by BrennanConroy** [comment] 2019-11-07 16:50
>Microsoft.AspNetCore.Http.Features, Version=2.0.0.0

Somehow you have a reference to a 2.0.0 package?

You can view the project.assets.json to see where dependencies are coming from.

**Comment by anurse** [comment] 2019-11-07 18:47
@ScarlettCode do you have references to both 3.0 and 2.0 packages with the `Microsoft.AspNetCore` or `Microsoft.Extensions` prefix.

**Comment by ScarlettCode** [comment] 2019-11-08 09:29
Thanks @BrennanConroy it looks like Rollbar (https://www.nuget.org/packages/Rollbar/3.5.0) pulls in Microsoft.AspNetCore.Http (>= 2.0.0) which was the cause of the issue.

Do I need to get Rollbar to update to v3 in order to use these two libraries together?

**Comment by anurse** [comment] 2019-11-08 20:36
In general, it's OK if you have a package referencing an older version. The problem is that we do load the **newer** version of that package in your app. And since we do make some breaking changes between major releases, it's likely that's what you're hitting.

So yes, it sounds like Rollbar is not compatible with ASP.NET Core 3.0 at this time, you'd need to reach out to them to update their package.

**Comment by anurse** [comment] 2019-11-08 20:36
Closing this issue since it appears to be an issue in an external component. Please feel free to let us know if that's not the case!

**Comment by anurse** [comment] 2019-11-08 20:38
Actually... looking back a bit, this is a client application running Xamarin.Forms, right? Not a server?

It's really odd that you have these components in the dependency graph at all since they are server-side components. Can you share all the package references you have in your `csproj`?

**Comment by davidfowl** [comment] 2019-11-09 04:31
We reference that assembly for FeatureCollection in the connection context API

**Comment by ScarlettCode** [comment] 2019-11-10 16:03
@anurse Yes Xamarin.Forms and just the client side. 

    <PackageReference Include="akavache" Version="6.9.10" />
    <PackageReference Include="Com.OneSignal" Version="3.6.0" />
    <PackageReference Include="FormsPinView" Version="2.0.0" />
    <PackageReference Include="fusillade" Version="2.0.5" />
    <PackageReference Include="getAddress.Sdk" Version="1.6.4" />
    <PackageReference Include="Humanizer.Core" Version="2.7.9" />
    <PackageReference Include="IdentityModel" Version="4.1.0" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="2.5.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="2.5.0" />
    <PackageReference Include="Microsoft.AppCenter.Distribute" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.0.0" />
    <PackageReference Include="modernhttpclient-updated" Version="3.4.2" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="PCLCrypto" Version="2.1.32-alpha" />
    <PackageReference Include="Polly" Version="7.1.1" />
    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.616" />
    <PackageReference Include="Prism.Plugin.Popups" Version="7.2.0.573" />
    <PackageReference Include="Refit" Version="4.8.14" />
    <PackageReference Include="Rg.Plugins.Popup" Version="1.2.0.223" />
    <PackageReference Include="SkiaScene.TouchManipulation" Version="2.1.0" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="1.68.0" />
    <PackageReference Include="System.Reactive" Version="4.2.0" />
    <PackageReference Include="TouchTracking.Forms" Version="1.1.0" />
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle" Version="3.0.0.5" />
    <PackageReference Include="Xamarin.Essentials" Version="1.3.1" />
    <PackageReference Include="Xamarin.Forms" Version="4.3.0.947036" />
    <PackageReference Include="Prism.DryIoc.Forms" Version="7.2.0.1367" />
    <PackageReference Include="Xamarin.Forms.InputKit" Version="3.0.15" />
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="1.3.5" />
    <PackageReference Include="Xamarin.Forms.StateSquid" Version="1.1.3" />
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="4.3.0.947036" />

**Comment by anurse** [comment] 2019-11-11 17:12
@davidfowl cleared up my confusion about the package.

So, given that, if Rollbar is using the same library but at a different version then yeah, you'll have to get Rollbar to update.

**Closed by anurse** 2019-11-11 17:12 UTC
Labels: area-signalr, more-info-needed
