### ISSUE TITLE
Blazor server template error when scaffolded identity pages are added

### ISSUE THREAD

**Issue by joseph-adam** [aspnet/AspNetCore#14224] opened 2019-09-22 02:55 UTC
The blazor server template does not play nicely with the scaffolded identity templates when the individual user accounts selection is made.    

Version: 3.0.0-rc1.19457.4

Repro steps:

1. Select File > New > Project and select the serverside Blazor app using Visual Studio 2019 preview and the 3.0.0-rc1.19457.4 version of .net core.  
2.  During the blazor server template create, select the change link below Authentication and select the individual user accounts option. 
3. Once the template is created add a scaffolded identity page to the project.  Right-click on the solution and select add > new scaffolded item.  Select Identity and click 'Add'.  At this point, you should presented with a list of possible custom identity views to generate.  Select Login and Register scaffolded views and select the application db context in the drop-down and click 'Add'.  
4. When the view is generated you will get the compile error below:

Error | CS0246 | The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?)  

5. To fix the compile error look at the top of the /Pages/Shared/_Layout.cshtml file in the project.  You will see new using declarations were added to the top of the file but the very top line is missing the @using directive (see code below).  Adding @using will fix the compile error but the template will look wonky with two top navs both containing a log in a register link.  I think what is happening is that the add new scaffolding should not be touching the shared layout used by the Blazor view.  I suspect a new shared layout should be scaffolded in under the Areas/Identity/Pages/Shared path.  

[note the missing @using in the _Layout.cshtml page below]

Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine

**Comment by adrianwright109** [comment] 2019-09-22 06:30
Duplicate of #13699

**Comment by joseph-adam** [comment] 2019-09-22 14:06
This is still an open issue; The fix (aspnet/Scaffolding#1066) mentioned in #13699 does not resolve this.  It has to do with the layout page referenced by the scaffolded identity views.  The identity scaffolding mechanism incorrectly adjusts the _layout.cshtml page used by the Blazor views.  When this happens, we see two navbars present in the browser (one from the injected identity view and the one from the Blazor template view).

**Comment by mkArtakMSFT** [comment] 2019-09-23 16:27
Thanks for contacting us, @joseph-adam.
This is indeed a duplicate issue and will be fixed for the upcoming 3.1 release.

**Closed by mkArtakMSFT** 2019-09-23 16:27 UTC
Labels: area-blazor
