### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by k00ksta** [aspnet/AspNetCore#11690] opened 2019-06-28 20:25 UTC
It would be excellent if you added support for React Native, I have a pretty large project and cannot  seem to get the current release to connect to a asp.net core signalr server via websockets with having negotiation errors with the server. If anyone else has managed to get it working I would love to know how but as it currently stands it would be great for a client to be released from Microsoft.

**Comment by hez2010** [comment] 2019-06-29 09:02
If you want to use raw Websocket, you need to add app.UseWebSockets() and write your own middlewares to route and handle WebSockets connections.

**Comment by k00ksta** [comment] 2019-07-01 13:24
By adding that what URL would we use to connect via web sockets /client?hub= with the hub name  Also  can we not invoke hub methods? I was under the impression that ASP.NET Core SignalR uses websockets by default and downgrades to long polling or server sent events.

**Comment by BrennanConroy** [comment] 2019-07-01 15:52
Dupe of https://github.com/aspnet/AspNetCore/issues/6565
If you can provide any additional information to what is on that issue that would be helpful 😃

**Closed by BrennanConroy** 2019-07-01 15:52 UTC
Labels: area-signalr

**Comment by k00ksta** [comment] 2019-07-01 16:02
It is really not a Dupe of #6565 because he could not even get a web socket to initialize for some reason .. The issues I have is that if you import the @aspnet/signalr javascript sdk into a react native project when it tries to connect to the hub it will kick back an error negotiating with the server. The same code works fine in a javascript webpage so I am unsure what is missing under the hood or if the headers are even correct coming from react-native. You can easily attempt to duplicate this yourself with just creating a blank react-native app (not with expo!) and npm install @aspnet/signalr into the project. I am also using the aspnet core Signalr ChatHub example for the server side of things which you can use as well. 

Sample Code

`
// Imports
import { HubConnectionBuilder, JsonHubProtocol } from '@aspnet/signalr';
`
`
componentDidMount() {
var connection = new HubConnectionBuilder().withHubProtocol().withUrl('https://localhost:44376/myhub').build();

connection.start().catch((error) => {
      console.log(error);
    });

connection.on("ReceiveMessage", function (user, message) {
      console.log('Message Received: ', user, message);
    });
}
`
This will hit the Signalr server but throw an error which I thought was maybe CORS but it seems like the handshake is incorrect and not CORS as the error returned is "Fail to Negotiate with the Server".

**Comment by BrennanConroy** [comment] 2019-07-01 16:27
Ok sure, "dupe" is the wrong word.

Tracked by https://github.com/aspnet/AspNetCore/issues/6565 is more correct.

We haven't officially supported the client working on React Native yet, but we would like it to work there.
