### ISSUE TITLE
Validate `dotnet new`, `dotnet run` sequence doesn't fail for templates on Windows and MacOS

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#9441] opened 2019-04-16 21:45 UTC
https://github.com/aspnet/AspNetCore/issues/9420

**Comment by mkArtakMSFT** [comment] 2019-04-23 20:42
@ryanbrandenburg I've moved this to preview6 as it didn't make in to preview5.

**Comment by ryanbrandenburg** [comment] 2019-04-26 23:52
While looking at a separate issue I found that all of our tests actually [already run on Linux and Mac](https://dnceng.visualstudio.com/internal/_build/results?buildId=165537&view=ms.vss-test-web.build-test-results-tab)? That's weird to me considering it's [specifically disabled](https://github.com/aspnet/AspNetCore/blob/master/src/Shared/E2ETesting/E2ETesting.props#L6) (but apparently without reason, because they're running and passing). I'm going to do some more research here but this PR will probably get closed.

This seems to be caused by a change in behavior when we started running Templating tests in their own task, and as such the fact that it works is basically an accident. The task here now is just to make it work for the right reasons.

**Comment by ryanbrandenburg** [comment] 2019-05-15 17:20
I talked this over with Dan and Pranav given the above. We agreed that even though what we have right now didn't cover the exact scenario (probably because the "Shared Framework" used in templating tests is not the real thing) which prompted this bug it still covers the general scenario of build/run on x-plat. @javiercn seems to be doing some work to enable selenium on mac and Linux, which would increase our ability to catch problems like this.

Given all that I'm going to close this out.

**Closed by ryanbrandenburg** 2019-05-15 17:20 UTC
Labels: 2 - Working, PRI: 1 - Required, area-mvc, task

**Comment by javiercn** [comment] 2019-05-15 17:31
I did an experiment to enable cross-platform E2E tests, because Nate suggested that all requirements were met, but it turns out that is not the case.

For the record, in case we want to invest on this in the future, there's a bug tracking it, and someone should investigate exactly why it's not working.

**Comment by ryanbrandenburg** [comment] 2019-05-15 17:36
That's the bug? I thought there was one too but I couldn't find it after a couple searches.

**Comment by javiercn** [comment] 2019-05-15 17:39
https://github.com/aspnet/AspNetCore-Internal/issues/2048
