### ISSUE TITLE
Automatic reconnection for Circuits

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6360] opened 2019-01-03 23:26 UTC
This would be a set of features that allow a circuit's lifetime to span multiple SignalR connections.

For instance, the train goes through a tunnel, and you can preserve your UI state on the other side. 

See: https://github.com/aspnet/AspNetCore/issues/6353#issuecomment-451307907

**Comment by SteveSandersonMS** [comment] 2019-02-06 14:24
Closing as duplicate of #5562

**Closed by SteveSandersonMS** 2019-02-06 14:24 UTC
Labels: area-mvc, feature-Components
