### ISSUE TITLE
Big fall in Json, MVC plaintext, MVC Json

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#9388] opened 2019-04-15 18:58 UTC
![image](https://user-images.githubusercontent.com/1142958/56157688-08eece00-5fb8-11e9-8cfa-ce51f89805fb.png)

Change set: https://github.com/aspnet/AspNetCore/compare/dc08a60f5edebdf3d6048afb1b147de776661562...d2db4677c98c5e46d5a8a1d4942c6a684a774fd5 looks to be deps outside AspNetCore 

@dougbu @sebastienros  as you may understand what deps are related?

The MVC gain at end is changeset https://github.com/aspnet/AspNetCore/compare/d2db4677c98c5e46d5a8a1d4942c6a684a774fd5...1baeaaac36b78c33bce80ed92c5c0f82a0e5aa11

**Comment by sebastienros** [comment] 2019-04-15 19:01
The bot got it and I am already investigating. Traces will follow, currently trying to pinpoint the change.

**Comment by sebastienros** [comment] 2019-04-15 19:35
Better changeset containing the regression: https://github.com/aspnet/AspNetCore/compare/dc08a60f5edebdf3d6048afb1b147de776661562...88599a5c266b9bce014b5bd499daae3d170a950d

**Comment by benaadams** [comment] 2019-04-15 19:50
Anyway to get the changeset for the Extension reference change? I assume the EF changes aren't relevant... or at least one hopes 😄

**Comment by sebastienros** [comment] 2019-04-15 19:51
I can try to get that

**Comment by sebastienros** [comment] 2019-04-15 19:51
In the meantime, from Citrine's diff:
![image](https://user-images.githubusercontent.com/1165805/56160930-39fddd00-5f7d-11e9-8518-ff8abda3e418.png)

**Comment by benaadams** [comment] 2019-04-15 19:58
> In the meantime, from Citrine's diff:

Not sure if that's a decrease in contention for SocketAsyncEngine? As this PR is in range of the previous runtime update "SocketAsyncEngine.Unix: improve performance of context lookup" https://github.com/dotnet/corefx/pull/36358

@tmds @stephentoub

**Comment by sebastienros** [comment] 2019-04-15 20:00
The negative needs to be read in the opposite, I compared the lowest to the baseline (higher)

**Comment by sebastienros** [comment] 2019-04-15 20:01
Here is the diff for extensions:
https://github.com/aspnet/Extensions/compare/17cb5265d011311233c2795727532d5c8eb22b5f...0b1aa473a7a722cd3f0aab5166fbe9e5203f0582

Which updated System.IO.Pipelines

**Comment by benaadams** [comment] 2019-04-15 23:17
Libuv hit by same drop so unlikely to be the sockets change

![image](https://user-images.githubusercontent.com/1142958/56171262-8af0ee00-5fdc-11e9-9404-25ad178c59ce.png)

Platform and mw plaintext seem uneffected; mvc middleware heavily effected

**Comment by sebastienros** [comment] 2019-04-15 23:19
Any "pipelined" one I think

**Comment by sebastienros** [comment] 2019-04-15 23:20
Has there there been any change related to the ThreadPool or Exceptions management?

**Comment by benaadams** [comment] 2019-04-15 23:25
However mw json effected as is mvc json 🤔

**Comment by benaadams** [comment] 2019-04-15 23:27
> Any "pipelined" one I think

mw plaintext not being effected (neither non-pipelined or pipelined), but mvc plaintext being effected is the oddity (and then both forms of json being effected)

**Comment by sebastienros** [comment] 2019-04-15 23:27
I can only repro the numbers on the citrine machines, which could be explain by a locking symptom as these machines have more cores.

**Comment by benaadams** [comment] 2019-04-15 23:47
Runtime version unchanged though?

![image](https://user-images.githubusercontent.com/1142958/56172370-110f3380-5fe1-11e9-987a-bba51d62d190.png)

**Comment by sebastienros** [comment] 2019-04-15 23:47
Oh, I mean non-pipelined, but you are right it's still wrong :/

**Comment by benaadams** [comment] 2019-04-16 03:38
I think it has to still be something vs the previous runtime

3.0.0-preview5-27608-16 -> 3.0.0-preview5-27611-18
Microsoft.NetCore.App / Core FX
https://github.com/dotnet/corefx/compare/6ca16758a5d454c1f1b04975bf55f259dd71fc49...fe5c12ad8315e043e62285117a56bba1784756d1

Microsoft.NetCore.App / Core CLR
https://github.com/dotnet/coreclr/compare/991817d90827b206ab25e74e7a5bd326a7e86ad4...759e3777aad6e711c6c6171ee738df9f38e877a0

**Comment by sebastienros** [comment] 2019-04-16 19:52
I isolated the issue to be in this range:

3.0.0-preview5-27611-10 -> 3.0.0-preview5-27611-12
Microsoft.NetCore.App / Core FX
https://github.com/dotnet/corefx/compare/7b7345665ec28a85084b3ad2932e03f7641d6151...af562e84b8b5a4a335ceb5006886a6c42c1c023e

Microsoft.NetCore.App / Core CLR
https://github.com/dotnet/coreclr/compare/45e04dd1bb1c7171d88a24454cb2c2811f46ce55...b574fac287e8ebe94f95d1b0919807523bb55b86

**Comment by stephentoub** [comment] 2019-04-16 20:03
This regression only shows up on Linux?  Assuming the ranges above are correct, looks like the best candidate would be @janvorli's changes from https://github.com/dotnet/coreclr/pull/23824.  @janvorli, any chance your changes could have had this kind of impact?

**Comment by benaadams** [comment] 2019-04-16 20:23
That would fit with Platform and Plaintext mw being unaffected as they don't allocate 😎 so don't involve GC

**Comment by janvorli** [comment] 2019-04-16 20:25
Before my change, CoreCLR was able to utilize only upto 64 CPUs, with the change, CoreCLR is not limited to that and can use all the CPUs available on the machine. So it may be possible that if the affected machines have more than 64 CPUs, there is some unexpected impact.
@sebastienros what is the configuration of the machines that are having the perf degradation? You've mentioned that these are high core machines.
There is a couple of things that can be tested to see if the number of CPUs is causing the trouble (provided there are more than 64 CPUs).
* Run the test using `taskset` command, limiting the process to run on the first 64 CPUs only. That makes the whole process to run on 64 CPUs only.
* Run the test with env variable `COMPlus_GCHeapCount` set to 64. That limits only the number of GC heaps / threads, but doesn't affect the threadpool behavior.

Would it be possible to try that?

**Comment by sebastienros** [comment] 2019-04-16 20:27
I will answer your questions in a second, could you in the meantime give me the list of clr files that are impacted by the change, I could then confirm it's the actual change by swapping these files before and after the change.

**Comment by benaadams** [comment] 2019-04-16 20:30
Other item it could be from that list is Contextual reflection? https://github.com/dotnet/coreclr/pull/23740

As again the uneffected tests don't use reflection and the others do; however that should? impact Windows equally?

**Comment by janvorli** [comment] 2019-04-16 20:34
> list of clr files that are impacted by the change

libcoreclr.so

**Comment by benaadams** [comment] 2019-04-16 20:34
>  what is the configuration of the machines that are having the perf degradation?

1 x [Intel Xeon Gold 5120 CPU](https://ark.intel.com/content/www/us/en/ark/products/120474/intel-xeon-gold-5120-processor-19-25m-cache-2-20-ghz.html), 32 GB of memory; 14 cores, 28 HT cores

Should be under the 64 CPU limit and non NUMA?

**Comment by sebastienros** [comment] 2019-04-16 20:34
Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz, 2195 Mhz, 14 Core(s), 28 Logical Processor(s)

I confirm windows is not impacted (same physical hardware). Tested on MvcPlaintext.
Linux: 1.7M -> 1.4M
Windows: 2.0M -> 2.0M

**Comment by janvorli** [comment] 2019-04-16 20:40
Is there a way to run the test locally? I have an Intel Core i9 9900x (10 Cores, 20 logical processors) machine with 32GB RAM, so it may be enough to repro the issue.

**Comment by benaadams** [comment] 2019-04-16 20:44
GC mode still getting propagated? i.e. its reporting Server rather than Client?

**Comment by janvorli** [comment] 2019-04-16 20:51
The change only affects number of processors threadpool and GC can see.

**Comment by sebastienros** [comment] 2019-04-16 20:54
Updating libcoreclr.so only is not sufficient, it fails. There must be other dependent ones.

**Comment by janvorli** [comment] 2019-04-16 21:06
It is best to replace all files built in the coreclr repo. libcoreclr.so is tied to System.Private.CoreLib.dll, but sometimes it is not enough to copy these two. 
To stay on the safe side, please replace these:
```
libclrjit.so
libcoreclr.so
libcoreclrtraceptprovider.so
System.Globalization.Native.so
System.Private.CoreLib.dll
```

**Comment by sebastienros** [comment] 2019-04-16 21:12
I can repro the regression by updating these files. So this is coming from this set.

What next, do you want some traces, or do you have an idea about how to fix it?

**Comment by janvorli** [comment] 2019-04-16 21:20
I have no specific idea what is causing the regression yet. I need to look at my change in detail to see if I can spot something. For machines with less than 64 CPUs, there should be no change in behavior, in fact I would rather expect some improvements due to shorter code paths at some places.

Could you also please run `strings libcoreclr.so | grep "@(#)"` on the libcoreclr.so with and without the regression that you've used for testing so that I can see the exact commits they were built from?

**Comment by sebastienros** [comment] 2019-04-16 21:41
I looked in the self-contained apps I confirm that the commits are this range:

Microsoft.NetCore.App / Core CLR
dotnet/coreclr@45e04dd...b574fac

Actually we do this automatically already to generate these links based on the version. We download the runtime, and extract the git hashes from SOS and System.Collections.

**Comment by janvorli** [comment] 2019-04-16 23:02
Issue found and fixed in https://github.com/dotnet/coreclr/pull/24045

**Comment by benaadams** [comment] 2019-04-16 23:09
Thank you all 😄

**Comment by mkArtakMSFT** [comment] 2019-04-18 16:42
Thanks folks. Closing this as it seems this has been fixed already in the referenced issue.

**Closed by mkArtakMSFT** 2019-04-18 16:42 UTC
Labels: area-mvc, area: Performance
