### ISSUE TITLE
DeveloperExceptionPageMiddleware should not log exceptions

### ISSUE THREAD

**Issue by Rookian** [aspnet/AspNetCore#13716] opened 2019-09-05 13:58 UTC
I am using AspNetCore with ApplicationInsights and Serilog. In development environment exceptions are logged twice , because RequestLoggingMiddleware (Serilog) and DeveloperExceptionPageMiddleware is handling exceptions and logging them.

In my opinion the DeveloperExceptionPageMiddleware responsibility should only be to show an exception page. It should not log the given exception. 

See also: https://github.com/serilog/serilog-aspnetcore/issues/129

**Comment by sungam3r** [comment] 2019-09-05 16:27
I agree in principle. The name speaks for itself. But due to backward compatibility, this behavior should be disabled only through middleware options.

**Comment by Tratcher** [comment] 2019-09-05 16:42
I'd argue that RequestLoggingMiddleware has the incorrect behavior in this scenario. As a rule a component should only log an exception it's not going to re-throw or else it's subject to double logging. In production you'd have the same issue when the server catches and logs the exception.

**Comment by sungam3r** [comment] 2019-09-05 17:53
This middware does 2 things at once. The issue is about letting **the developer choose** only what is needed.

**Comment by rynowak** [comment] 2019-09-05 18:38
The developer exception page does two things.
- It catches an exception
- It shows a UI for the exception

**because** it catches the exception, it also logs.

**Comment by sungam3r** [comment] 2019-09-05 21:04
> The developer exception page does two things

i.e. breaking SRP

> because it catches the exception, it also logs.

Sorry, I do not understand the causal relationship. Why not just add something like ` bool DeveloperExceptionPageOptions.SuppressLog { get; set; }`? Backward compatibility will be fully preserved and everyone will be happy.

**Comment by Rookian** [comment] 2019-09-16 14:13
> I'd argue that RequestLoggingMiddleware has the incorrect behavior in this scenario. As a rule a component should only log an exception it's not going to re-throw ...

@Tratcher and @rynowak If the RequestLoggingMiddleware is swallowing the exception, then the DeveloperExceptionPage would not be shown.

Any other ideas or recommendations?

**Comment by Tratcher** [comment] 2019-09-16 14:56
Configure your log levels to suppress logs from the area "Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware".

**Comment by anurse** [comment] 2019-09-17 22:38
Closing as we don't intend to change this behavior.

**Closed by anurse** 2019-09-17 22:38 UTC
Labels: area-middleware, diagnostics
