### ISSUE TITLE
Question: Controller discovery across multiple assemblies using new routing system

### ISSUE THREAD

**Issue by kimbell** [aspnet/AspNetCore#13850] opened 2019-09-10 10:17 UTC
I have a class library containing a Controller currently working on 2.0. I'm in the process of migrating things over to 3.0 using preview 9.

My class library has a test project that sets up things using WebApplicationFactory. In 2.0 the controller in my class library was automatically discovered. With the new routing system, it cannot find the path handled by the controller. 

This is how I've set things up in the test project. Am I missing something? 
```CS
protected override void ConfigureWebHost(IWebHostBuilder webhostBuilder)
        {
            webhostBuilder
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseDefaultServiceProvider(p => p.ValidateScopes = true)
                .ConfigureServices((context, services) =>
                    {
                        services.AddControllers();
                    })
                .Configure(appBuilder =>
                {
                    appBuilder.UseRouting();
                    appBuilder.UseEndpoints(config =>
                    {
                        config.MapControllers();
                    });
                });
        }
´´´

**Comment by kimbell** [comment] 2019-09-10 11:26
I found out that
```CS
services.AddControllers().AddApplicationPart(typeof(MyController).Assembly);
```
makes things work, but is this the correct way or am I seeing the result of a side effect?

**Comment by mkArtakMSFT** [comment] 2019-09-10 17:15
@pranavkm can you please confirm this approach is the right one? Thanks.

**Comment by mkArtakMSFT** [comment] 2019-09-10 17:15
Also, is this potential 3.0 regression?

**Comment by pranavkm** [comment] 2019-09-10 21:18
@kimbell is this a previously compiled library that wasn't recompiled using a 3.0 SDK?

**Comment by kimbell** [comment] 2019-09-11 05:31
I'm in the process of recompiling our libraries against netcoreapp3.0 when I came across this, so it's not a 2.0 precompiled library. 

My solution contains two projects; my library and a test project; both target netcoreapp3.0. In my library I have a controller that I want to automatically expose to anyone that uses it. When running tests that target the url of the controller, they fail due to a 404. 

Since 2.0 automatically made all controllers in all referenced assemblies available, it's something we have used in multiple places. If things need to change due to the new routing system, so be it. I'm trying to figure out the correct way of doing this without introducing side-effects that can cause problems later on.

**Comment by mkArtakMSFT** [comment] 2019-09-11 16:51
@kimbell please provide a minimal repro project for us to investigate this further.

**Comment by kimbell** [comment] 2019-09-11 17:51
[Common.Caching.zip](https://github.com/aspnet/AspNetCore/files/3602096/Common.Caching.zip)
I've copied my original code and stripped it down to a minimum. 

The test projects has 3 tests. 
1 calls controller in test project
2 calls controller in main project (fails)
3 calls controller in main project, but uses AddApplicationPart()

**Comment by pranavkm** [comment] 2019-09-13 16:50
Thanks @kimbell . @javiercn could you have a look?

**Comment by javiercn** [comment] 2019-09-23 21:43
@kimbell Can you provide a github repo with a minimal repro project and detailed steps to reproduce the issue?

**Comment by javiercn** [comment] 2019-09-23 22:20
@kimbell Thanks for the repro project. There are a three things in the project that need fixing.
* Your app needs to be an executable.
* You need to provide Web Application Factory with a type from the entry point assembly.
* Your app needs to be referencing the Microsoft.Net.SDK.Web

**Comment by javiercn** [comment] 2019-09-23 22:47
Closing as there's no more action to be taken here. If you still have issues after implementing those fixes, feel free to reopen the issue with an updated repro.

**Closed by javiercn** 2019-09-23 22:47 UTC
Labels: area-mvc, investigate

**Comment by kimbell** [comment] 2019-09-26 13:21
@javiercn I've now updated the code to support netstandard2.0/netcoreapp2.2 and netcoreapp3.0 without doing any of the suggested fixes. Things work fine in 2.0 but fail in 3.0. Either I've been depending on undocumented side-effects in 2.0, or something has changed.

When I run this code, one test fails for 3.0, but works for 2.2. 
https://github.com/kimbell/ControllerDiscoveryIssue

**Comment by javiercn** [comment] 2019-09-26 13:33
@kimbell I'm not seeing the suggestions applied in your repro. 

> * Your app needs to be an executable.

That's not the case from the repro you have there. src/Services.Common.Caching needs to be an executable.

> * You need to provide Web Application Factory with a type from the entry point assembly.

You are giving it a type in your test assembly https://github.com/kimbell/ControllerDiscoveryIssue/blob/master/test/Services.Common.Caching.Test/Infrastructure/TestContext.cs#L23

> * Your app needs to be referencing the Microsoft.Net.SDK.Web

src/Services.Common.Caching needs to be referencing the web sdk 
https://github.com/kimbell/ControllerDiscoveryIssue/blob/master/src/Services.Common.Caching/Services.Common.Caching.csproj#L1

**Comment by kimbell** [comment] 2019-09-26 13:43
I know I haven't made those changes and that is on purpose. The point I'm trying to make is that I have code that has existed since netcore 1.1 and has worked without any problem. When upgrading to 3.0 things start breaking. 

Are these breaking changes by-design, or should the code still work unmodified on 3.0? 

We have a bunch of libraries that expose Controllers for internal use. These libraries are included in other services. I find it hard to justify why a library should be an executable.

**Comment by javiercn** [comment] 2019-09-26 14:10
@kimbell They are by design. It's just reflecting changes in hosting and how MVC does discovery.

**Comment by kimbell** [comment] 2019-09-26 14:22
Thanks @javiercn 

Since this problem is currently only showing up in the test project, I have no problem adding extra code to make it work. Depending on what information we get related to #14469 we might change things. 

We haven't gotten as far as running services as 3.0 yet; we are still working through our libraries. But if I understand you correctly, once we move our services to 3.0, controllers should be discovered from other assemblies as well? For those we have a full Startup class and everything is more normal.

**Comment by javiercn** [comment] 2019-09-26 14:51
@kimbell Controllers have always been discovered from other assemblies. We used to build a list of application parts (the raw materials for controller discovery, etc) using the dependency context. That might have changed in 3.0. I believe @pranavkm did some work on it.
