### ISSUE TITLE
ASPNETCORE_URLS not working when IConfiguration is re-added as singleton in ConfigureServices

### ISSUE THREAD

**Issue by Hoffs** [aspnet/AspNetCore#16819] opened 2019-11-04 18:55 UTC
### Describe the bug
When using old `WebHost.CreateDefaultBuilder(args)...;` method of starting aspnetcore application if `IConfiguration` is injected inside `Startup#ConfigureServices(IServiceCollection services)` it does not affect internally stored `IConfiguration` and Kestrel can successfully use its `ASPNETCORE_URLS` (or rather just `URLS`) setting.
When using new generic `Host.CreateDefaultBuilder(args)...;` this behavior is different as injected `IConfiguration` replaces internally stored `IConfiguration` and if the transformed configuration (`ASPNETCORE_URLS` -> `URLS`) is not persisted in the new `IConfiguration` the `ASPNETCORE_URLS` has no effect on the urls that it's going to bind to.
I've tried looking and it seems that old `WebHost` stores has `IConfiguration` as a field, where as `Host` uses `ServicesContainer` for accessing it, hence when injected inside `ConfigureServices` it gets overridden. This is just a guess after kind of unsuccessfully trying to look for the cause, but seems sort of plausible. 

I'm not entirely sure if this is a bug, maybe it shouldn't have worked with `WebHost` as well, but the thing is that this is quite unclear and confusing part as docs state that `ASPNETCORE_URLS` should make it work and using `WebHost` it does work but with `Host` it suddenly doesn't. There are no indications what would cause it.

Also the internal part that `ASPNETCORE_URLS` gets remapped to `URLS` is a bit strange too, as I didn't see it documented anywhere and someone could just easily use `urls` env variable themselves and break this part as well. When considering the issue at hand, if instead of `ASPNETCORE_URLS`, I se `URLS` as desired bind url both approaches initialize on 8080 (obviously).

### To Reproduce
Minimal repro repo: https://github.com/Hoffs/aspnetcore-repro
Key parts:
```c#
// env ASPNETCORE_URLS set to "http://+:8080"
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run(); // Starts with default 5000/5001
        CreateWebHostBuilder(args).Build().Run(); // Starts with 8080
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();
}
// partial Startup.cs
public class Startup
{
        public Startup(IWebHostEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .AddEnvironmentVariables()
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json", optional: true);
                // Some other configuration stuff added.

            Configuration = builder.Build();
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton(Configuration); // This breaks generic Host, but not older WebHost.
            services.AddControllers();
        }
}
```

### Further technical details
- ASP.NET Core version: 3.0
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Tratcher** [comment] 2019-11-04 23:55
3.0 consumes more of these services from DI so I'm not surprised that overriding config breaks this.

Why are you building a different config in Startup? With IHostBuilder the guidance is to build config in Program.cs using ConfigureHostConfiguration or ConfigureAppConfiguration. CreateDefaultBuilder also already pulls in the appsettings.json and friends so you shouldn't need to build that config at all.

> Also the internal part that `ASPNETCORE_URLS` gets remapped to `URLS` is a bit strange too,

AddEnvironmentVariables("ASPNETCORE_") trims ASPNETCORE_ from all environment variables it maps in. That way you can use "urls" in command line args or other config sources without the prefix.

**Comment by Hoffs** [comment] 2019-11-05 07:12
> Why are you building a different config in Startup?

Because at the time I was unaware of `ConfigureAppConfiguration` and this solution of building/injecting `IConfiguration` has been used in services without issues for over a year (2.1, 2.2). It's only when switched to `Host` (3.0) it suddenly stopped working. I don't think there were mentions about not overriding `IConfiguration` too.

> AddEnvironmentVariables("ASPNETCORE_") trims ASPNETCORE_ from all environment variables it maps in. That way you can use "urls" in command line args or other config sources without the prefix.

Yes, I understand that, just that it's sort of unintuitive (and not documented explicitly) from user perspective, as even if building my custom `IConfiguration` in startup, that variable is visible there, but for some reason (well it's known why now) it doesn't affect the program.

As I mentioned, maybe this is not a bug, but I just think that something should either try to prevent or warn the user when it is used this way as the behaviour is quite confusing from that perspective and not very documented (at least I didn't find anything when looking through docs).

**Comment by anurse** [comment] 2019-11-07 23:39
This is essentially the same problem as #15011 . Closing this as a duplicate of that.

**Closed by anurse** 2019-11-07 23:39 UTC
Labels: area-hosting
