### ISSUE TITLE
JSInteropt calls of byte[]'s result in string conversion

### ISSUE THREAD

**Issue by JPVenson** [aspnet/AspNetCore#17266] opened 2019-11-20 18:32 UTC
### Describe the bug
As written in https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#invoke-javascript-functions-from-net-methods it should be clear that it is possible to transfer arrays of numbers from c# client code to a js method. This does not seem to work with arrays of bytes. When calling a js function with an int[] the method will receive an object and with the constructor of UInt8Array() it is possible to use the int[]. When calling the same function from c# with an byte[], the same js function will receive an string that is formatted in an unkown way.

### To Reproduce

Assume this js method:
```
function TestArray(arrayFromCs) {
	console.log(typeof arrayFromCs);
	console.log(arrayFromCs);
}
```
and These calls:
```
public static ValueTask CallJs(this IJSRuntime js, byte[] data)
{
	return js.InvokeVoidAsync(
		"TestArray",
		data);
}
public static ValueTask CallJs(this IJSRuntime js, int[] data)
{
	return js.InvokeVoidAsync(
		"TestArray",
		data);
}

public static async Task TestCalls(this IJSRuntime js)
{
	var testArray = new byte[]
	{
		1, 2, 3, 4, 5
	};
	Console.WriteLine("Write INT Array");
	await js.CallJs(testArray.Select(f => (int)f).ToArray());
	Console.WriteLine("Write BYTE Array");
	await js.CallJs(testArray);
}
```
Output:
```
cw: WASM: Write INT Array
cw: object
cw: (5) [1, 2, 3, 4, 5]
cw: Write BYTE Array
cw: string
cw: AQIDBAU=

```
Expected Behavior:
When submitting an byte[] to an js function it should be handled just as an other array of numbers and should not be converted into a string or it should be stated on the documentation how this string is created and what it represents.

### Further technical details
- ASP.NET Core version 
3.0.0-preview9.19465.2
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2019 latest (19.3.9)

**Comment by javiercn** [comment] 2019-11-20 21:44
@JPVenson thanks for contacting us.

I believe this is the expected behavior as we are using system.text.json and it will base64 encode byte arrays during serialization. It is likely that you need to use `atob` or a similar method to transform it back.

**Comment by JPVenson** [comment] 2019-11-20 22:11
@javiercn you are right with the base64 stuff i checked it myself:

```
public static ValueTask CallJs(this IJSRuntime js, byte[] data)
{
	return js.InvokeVoidAsync(
		"TestArray",
		data);
}

public static ValueTask CallJsWithBase64(this IJSRuntime js, byte[] data)
{
	return js.InvokeVoidAsync(
		"TestArray",
		Convert.ToBase64String(data));
}
public static ValueTask CallJs(this IJSRuntime js, int[] data)
{
	return js.InvokeVoidAsync(
		"TestArray",
		data);
}

public static async Task TestCalls(this IJSRuntime js)
{
	var testArray = new byte[]
	{
		1, 2, 3, 4, 5
	};
	Console.WriteLine("Write INT Array");
	await js.CallJs(testArray.Select(f => (int)f).ToArray());
	Console.WriteLine("Write BYTE Array");
	await js.CallJs(testArray);
	Console.WriteLine("Write BYTE Array as BASE64");
	await js.CallJsWithBase64(testArray);
}
```

Results in:
```
WASM: Write INT Array
cw: object
cw: [1, 2, 3, 4, 5]
cw: Found a BeatSaberSongProvider
cw: Write BYTE Array
cw: string
cw: AQIDBAU=
cw: Found a Playlist Provider
cw: Write BYTE Array as BASE64
cw: string
cw: AQIDBAU=
```

still fmpov this is not exactly the expected behavior.

**Comment by pranavkm** [comment] 2019-11-21 06:53
There's planned work for System.Text.Json to add support for serialization formats other than base64 encoded strings for byte arrays - https://github.com/dotnet/corefx/issues/39961. This should allow byte[] to be transferred more efficiently when using IJSRuntime . However at this point it's not very clear how we would enable breaking changes to IJSRuntime's serialization settings.

**Comment by javiercn** [comment] 2019-11-21 15:56
I'm closing this issue as this is not something we can do anything about in the near future and is not a bug, but a behavior by design.

@pranavkm It might be worth to check with the corefx folks to allow configuring this behavior on a per-property basis.

**Closed by javiercn** 2019-11-21 15:56 UTC
Labels: area-blazor
