### ISSUE TITLE
UseStaticFiles with StaticFileOptions/FileExtensionContentTypeProvider breaks server side Blazor

### ISSUE THREAD

**Issue by glent1** [aspnet/AspNetCore#9588] opened 2019-04-20 00:31 UTC
### Describe the bug
Passing StaticFileOptions with a FileExtensionContentTypeProvider to app.UseStaticFiles breaks Blazor

### To Reproduce

dotnet new blazorserverside
edit startup.cs, replacing  app.UseStaticFiles(); with the following ...

var provider = new FileExtensionContentTypeProvider();
provider.Mappings.Add(".appx", "application/octet-stream");
app.UseStaticFiles(new StaticFileOptions() { ContentTypeProvider = provider });

### Expected behavior
Blazor works

### Error message

info: Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService[1]
      Request starting HTTP/2 GET https://localhost:5001/_framework/blazor.server.js
info: Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService[2]
      Request finished in 2.66ms 404

### dotnet version 

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by glent1** [comment] 2019-04-20 01:06
As is often the way, writing this up made me think about it more.  Adding this fixes ...

provider.Mappings.Remove(".js");

**Comment by glent1** [comment] 2019-04-20 02:04
Stupid caching.  No it doesn't.

**Comment by mkArtakMSFT** [comment] 2019-05-17 16:54
Thanks for contacting us, @glent1.
We do plan to fix this as part of #6349. Leaving this issue open to verify this scenario.

**Comment by javiercn** [comment] 2019-06-25 14:16
This is fixed for static assets comming out of RCL, but I fear that this is by design for blazor-server side as it brings in an embedded file and to do so it configures the options for the static files middleware. If you use your own options then it misconfigures blazor server-side.

The alternatives are:
* Configure options though DI, using `services.Configure<StaticFileOptions>(...)`
* Add two calls to app.UseStaticFiles one with your options before and another one like `app.UseStaticFiles()` later.
  * All content but blazor.server.js will be served with your options.

@rynowak @SteveSandersonMS in case we want to reconsider not shipping blazor.server.js as an embedded file, as the reasons against it keep stacking up.

**Comment by javiercn** [comment] 2019-06-25 14:17
I'm closing this as by design as this is a limitation of the current experience we plan to ship with.

**Closed by javiercn** 2019-06-25 14:17 UTC
Labels: PRI: 1 - Required, area-blazor, investigate
