### ISSUE TITLE
Assemblies referenced by EF are not coming from the Shared Framework

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#8836] opened 2019-03-26 18:30 UTC
Here is an overview of the dlls that are created when doing a `dotnet publish` on 3.0 (latest build).

![image](https://user-images.githubusercontent.com/1165805/55023474-1c5ed880-4fba-11e9-89f1-524799a3241f.png)

The application is referencing EF with a specific version `3.0.0-preview4.19168.3`.
As a result the assemblies that EF depends on (DI, Logging, Caching) are copied locally from a Nuget feed and not taken from the shared framework as expected.

It might be because when we eventually publish EF on Nuget.org it will have matched versions with the aspnet shared framework, but I assumed it would just pick up whatever version is in the shared framework already.

The unfortunate impact is that startup time is significantly impacted, as it's not just EF that isn't crossgened in this case.

**Comment by sebastienros** [comment] 2019-03-26 18:53
I checked which version the ASP.NET share framework had:

![image](https://user-images.githubusercontent.com/1165805/55025202-ba07d700-4fbd-11e9-86ad-c09b161379d7.png)

while the local version is

![image](https://user-images.githubusercontent.com/1165805/55025195-b4aa8c80-4fbd-11e9-80ca-73126874a63f.png)

The shared framework has a newer version, yet the nuget one was taken.

**Comment by DamianEdwards** [comment] 2019-03-27 18:20
Seems like an issue in the SDK, or the data we pass to the relevant targets in the SDK, that do assembly resolution and knockout. My understanding is that assemblies from the shared framework should always win, and previously you'd get a build error detecting a downgrade (since 2.1-ish).

**Comment by anurse** [comment] 2019-03-29 21:20
If it's an SDK issue, then perhaps @livarcocc can help route it?

**Comment by livarcocc** [comment] 2019-03-29 23:40
We never copied things into application from the shared framework that ships with the SDK. When publishing an application, the application bits always come from NuGet, implementation wise.

That is to say, for FDD apps, there is nothing to be copied, what is from the shared framework stays there. For self-contained apps, they the implementation assemblies come from runtime packs.

Lastly, I thought EF was no longer part of the framework.

**Comment by livarcocc** [comment] 2019-04-01 19:33
Still, we don't copy things from the framework. We only copy things from NuGet (packages).

**Comment by livarcocc** [comment] 2019-04-01 19:43
I think it will depend on how coherent the build being used is. As in, what version of those packages are inserted into the shared framework versus what is referenced by EF. Granted, conflict resolution will play a role here, but it is possible that the ones referenced by EF are newer and therefore are winning.

cc @dsplaisted to confirm.

**Comment by Eilon** [comment] 2019-04-01 21:56
@anurse yup.

**Comment by sebastienros** [comment] 2019-04-01 22:11
> it is possible that the ones referenced by EF are newer and therefore are winning

I pasted the versions used, the ones in the shared framework were newer.

**Comment by anurse** [comment] 2019-04-02 15:40
@pakrym mentioned that the versions have to align exactly for the framework to knock it out, so it sounds like the misalignment is the problem, regardless of the direction. I'll assign to @JunTaoLuo then to look at when he's back in.

**Comment by DamianEdwards** [comment] 2019-04-08 17:53
I'm seeing that even assemblies that match exactly are showing up in the output folder of apps created from templates in the SDK that contain package references that share deps with the shared framework, e.g. Razor Components app.

![image](https://user-images.githubusercontent.com/249088/55745629-87fa6a00-59ec-11e9-999a-c3b932e874f2.png)

**Comment by natemcmaster** [comment] 2019-04-08 18:05
@JunTaoLuo I'm available to help debug this now that I'm back from leave. I don't know what's broken, but have a few ideas where to start looking.

**Comment by dsplaisted** [comment] 2019-04-08 21:00
I finally had the time to look at this after mostly being done with https://github.com/dotnet/sdk/pull/3086.

The problem is the SDK is not picking up the platform manifest from the ASP.NET Core targeting pack, because they are using slightly different conventions.  The platform manifest in the ASP.NET Core targeting pack is under `\data\Microsoft.AspNetCore.App.PlatformManifest.txt`.  However, the SDK [is using](https://github.com/dotnet/sdk/blob/6b2c06d50e1397de5a8040dee2c17c7b691e6fb6/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L86-L87) the targeting pack name to generate the path for the manifest file, so it is expecting it to be in `\data\Microsoft.AspNetCore.App.Ref.PlatformManifest.txt` (note the extra `.Ref`).

I talked with @nguerrera, and we suggest that eventually we should use file names in these packages that don't embed the package / shared framework name, IE:

- `data\PackageOverrides.txt`
- `data\PlatformManifest.txt`

However, if we want to fix this quickly (ie for preview 4), then we can simply modify the SDK to also look at the filename that is currently used by the ASP.NET Core targeting pack.

**Comment by natemcmaster** [comment] 2019-04-08 21:44
It's like 1 line of code to make our manifest end up in `data/PlatformManifest.txt`, and it looks like the [SDK already supports that location](https://github.com/dotnet/sdk/blob/6b2c06d50e1397de5a8040dee2c17c7b691e6fb6/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L85), right? if so, let's just adjust our package.

**Comment by dsplaisted** [comment] 2019-04-08 21:46
@natemcmaster That works too, but I wasn't sure if you already had packages that you would prefer not to respin for preview 4.

**Comment by natemcmaster** [comment] 2019-04-08 21:49
We haven't had our final preview4 build yet, so I don't think this would be a big deal. But it's also my first day back from leave, so let me check with the managers.

**Comment by nguerrera** [comment] 2019-04-08 22:00
Welcome back, @natemcmaster :)

**Comment by natemcmaster** [comment] 2019-04-10 00:20
Should be fixed with #9180. Leaving open to validate once we have an SDK with the new runtime inserted.

**Comment by natemcmaster** [comment] 2019-04-15 22:18
Validated this has been fixed in 3.0.100-preview4-011216

**Closed by natemcmaster** 2019-04-15 22:18 UTC
Labels: 2 - Working, PRI: 1 - Required, area-platform
