### ISSUE TITLE
Static assets from razor class library not found add a razor class library to a running app

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#17535] opened 2019-12-03 04:48 UTC
Repro steps:

- Create a standalone Blazor WebAssembly app from VS (3.1.0-preview4)
- Run the app (Ctrl-F5)
- Add a Razor Class Library to the project
- Reference the RCL from the app
- Add a link to *_content/RazorClassLibrary1/styles.css* to *index.html*
- Add `<RazorClassLibrary1.Component1 />` to *Index.razor*
- Rerun the app

Expected result:

- `Component1` shows up on the home page of the app with proper styling

Actual result:

- The *styles.css* files is not found.

Workaround:

- Close and reopen the solution, rerun the app

**Comment by javiercn** [comment] 2019-12-03 08:07
@danroth27 Thanks for contacting us.

This has never worked. You need to build the app for it to work so that the manifest gets regenerated.

**Comment by danroth27** [comment] 2019-12-03 13:55
@javiercn I did rebuild the app.

**Comment by danroth27** [comment] 2019-12-03 14:06
Also, the same steps work fine with a Blazor Server app and an ASP.NET Core hosted Blazor WebAssembly app. It's only the standalone Blazor WebAssembly app that has this problem, and it only happens if I've already run the app without the RCL.

**Comment by MarkStega** [comment] 2019-12-04 15:18
I'll chime in with exactly the same experience that Dan reported. My 'self hosted' CSB app fails to load content from a RCL component but when the same app is hosted on a DNC 3.1 site the content is loaded as expected.

**Comment by gustavnavar** [comment] 2019-12-12 09:54
I have the same issue with the [Grid.Blazor](https://github.com/gustavnavar/Grid.Blazor) compoment.

As soon as I upgrade the RCL [GridBlazor](https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazor) to netstandard2.1 the [client demo project](https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorClientSide.Server) no static assest can be found.

**Comment by javiercn** [comment] 2019-12-13 13:06
This behavior is currently by design, as we don't stop and re-start the server when the app is re-built in order to provide a faster inner loop.

You can opt-out of this behavior by setting the following  property explicitly in your project.
```xml
<NoRestartServerOnBuild>false</NoRestartServerOnBuild>
```

As per improvements to this scenario, I'm going to close this issue as there's a separate issue tracking the broader scenario https://github.com/aspnet/AspNetCore/issues/5512

**Closed by javiercn** 2019-12-13 13:06 UTC
Labels: area-blazor, blazor-wasm
