### ISSUE TITLE
Kestrel over-unescapes some (but not all) values in the Request Path

### ISSUE THREAD

**Issue by davidmatson** [aspnet/AspNetCore#14170] opened 2019-09-19 21:44 UTC
### Describe the bug
When a raw request URL contains the string ```%2520```, Kestrel treats it as if it had just contained ```%20```.

### To Reproduce
```c#
        [Route("test/{blobPath}")]
        public IActionResult Post(string blobPath)
        {
            string value = Uri.UnescapeDataString(blobPath);
            return Ok();
        }
```
Send requests with the following values for blobPath:
```
Uri.EscapeDataString("test")
Uri.EscapeDataString("a b")
Uri.EscapeDataString("a%20b")
```
example raw request URIs as sent by Fiddler:
```
http://localhost:5000/test/test
http://localhost:5000/test/a%20b
http://localhost:5000/test/a%2520b
```

### Expected behavior
The semantic value sent by the client (before URI escaping) always matches the value received by the server (after URI un-escaping).
Similarly, the wire value send by the client (after URI escaping) always the matches the value seen by the method (before URI un-escaping).

### Additional context
Changing ```%2520``` to ```%20``` is a semantic change and prevents the client from sending a parameter that actually contains the text ```%20``` as a substring. The server cannot distinguish between the second and third example request above.

I'm not currently sure what transformations Kestrel is doing to the request URI it receives - it does not appear to be doing a full Uri.UnescapeDataString on the values it receives (for example, ```%2F``` is left as-is, while ```%25``` or ```%20``` are un-escaped). Without knowing which sequences it is replacing, I'm not sure how to get back to the value as sent by the client.

**Comment by Tratcher** [comment] 2019-09-19 23:11
Kestrel un-escapes everything except %2f (because doing so would be a semantic change to the path segment boundaries). The resulting path should be treated as un-escaped, so `%20` should not be un-escaped again, it's a literal value. Changing `%2520` to `%20` is not a semantic change because it's distinct from the escaped value `%20` that would have un-escaped to ` ` (space).

Put another way, if you eliminate the possibility of double un-escaping, you don't have semantic changes.

**Comment by davidmatson** [comment] 2019-09-19 23:47
So if, on the client, I do Uri.EscapeDataString on some value before putting it into the path and want to get the same value back on the server, I just need to do:
```
valueFromPath.Replace("%2F", "/")
```
And then I should always have exactly what I originally passed into Uri.EscapeDataString?

**Comment by Tratcher** [comment] 2019-09-20 00:29
Something like that. Note however that EscapeDataString is very aggressive, it doesn't take into account were in the url you're putting something. That's OK for user input, but don't pass in full url paths or anything structured like that.

**Comment by davidmatson** [comment] 2019-09-20 01:24
Yeah, I'm intending to pass something that's decoded as a single path segment - I just need it to roundtrip (be able to get exactly the same out on the server).

Here's what I ended up using as a workaround:
```c#
static class KestrelPathSegment
{
    // See: https://github.com/aspnet/AspNetCore/issues/14170
    public static string FinishUriUnescape(string pathSegment)
    {
        if (pathSegment == null)
        {
            return null;
        }

        return pathSegment.Replace("%2f", "%2F").Replace("%2F", "/");
    }
}
```

(Please let me know if there's anything else I'd need to do to get fully correct roundtripping.)

In general, how does ASP.NET Core handle providing URI data to the author - are path and query data all provided generally unescaped? That appears to be the case. Testing with:
```c#
    public class TestController : Controller
    {
        [Route("test/{segment}")]
        public IActionResult Get(string segment, string foo)
        {
            return Ok();
        }
    }
```

And the escaped version of the following string as a path segment and query string value:
```c#
Uri.EscapeDataString("a/b?c=d&e=f:g@h")
```

Produces a URL such as:
```http://localhost:5000/test/a%2Fb%3Fc%3Dd%26e%3Df%3Ag%40h?foo=a%2Fb%3Fc%3Dd%26e%3Df%3Ag%40h```

With the controller above, foo gets the value entirely URI un-escaped, but segment gets the URI mostly un-escaped - everything except the path separator. If model binding gives the value of foo as fully un-escaped, should it do the same for segment? i.e., should it replace ```%2F```/```%2f``` with ```/``` when model binding for consistency with how URI un-escaping is applied for query string values?

I also tested the same string as a query string key, and it also gets fully un-escaped there.

Overall, having Request.Path have a mostly-unescaped URI string is a bit confusing - I would have hoped for entirely escaped - I understand that entirely un-escaped isn't possible because un-escaping / would change the meaning of the path. Since QueryString is entirely escaped, doing Path the same would be great. Regardless, having model binding always provide fully un-escaped values would really help the consistency of the programming experience here.

**Comment by Tratcher** [comment] 2019-09-20 02:36
Yeah, the `%2F` discrepancy is feedback we've had before. @rynowak here it is again.

**Comment by anurse** [comment] 2019-09-24 22:30
This is essentially a duplicate of https://github.com/aspnet/AspNetCore/issues/2655 which was closed. @davidmatson , the original reported issue appears to be resolved in the discussion.

**Closed by anurse** 2019-09-24 22:30 UTC
Labels: area-servers
