### ISSUE TITLE
In Process poor performance when Logging is Information (Or Above)

### ISSUE THREAD

**Issue by firstasync** [aspnet/AspNetCore#10078] opened 2019-05-08 11:46 UTC
### Describe the bug
The app seems to have a poor performace when Logging is "Information" or above and **In Process** (IIS) hosting mode is being used. This doesn't seem to affect when **Out Of Process** (IIS + Kestrel) hosting mode is being used. 

### To Reproduce
1. Create a new ASP.NET Core Web app.
2. Set Logging.LogLevel.Microsoft to "Information" on appsettings.json
3. Publish it in your server.
4. Test performance
[Link to tested project](https://github.com/Kossx2/PerformanceOutInProcessTest)

### Screenshots (Updated with more simple tests) 
**Logging.LogLevel.Microsoft  = Information**
- **In Process**
![IN-Information](https://user-images.githubusercontent.com/6104477/57439758-0003bc00-7247-11e9-85cd-42b81b56e121.PNG)

- **Out Of Process**
![OUT-Information](https://user-images.githubusercontent.com/6104477/57439772-042fd980-7247-11e9-9153-3990ef68892f.PNG)

**Logging.LogLevel.Microsoft  = Below Information**
- **In Process**
![IN-Warning](https://user-images.githubusercontent.com/6104477/57440419-49a0d680-7248-11e9-9687-b42c8b949e5d.PNG)

- **Out Of Process**
![OUT-Warning](https://user-images.githubusercontent.com/6104477/57439986-72749c00-7247-11e9-96ab-f9cf6f5d0773.PNG)

**Comment by anurse** [comment] 2019-05-10 15:59
That data looks very strange. Why does the "Information" level data show `999 req/sec` but `59` requests over `60` seconds. It seems like maybe it should say `.999 req/sec`?

Regardless, we should look at the performance of in process when logging is enabled. The fact that out-of-process is much less impacted is notable.

**Comment by Kossx2** [comment] 2019-05-13 09:37
> That data looks very strange. Why does the "Information" level data show `999 req/sec` but `59` requests over `60` seconds. It seems like maybe it should say `.999 req/sec`?

999 req/sec * 60 seconds ~ 59.945 (exactly 59.940, the total request per seconds seems to be truncated). 
Overall, it's just a simple test, but also give us a big picture of the problem.

**Comment by anurse** [comment] 2019-05-13 16:06
Ah, I think I see the confusion. I presume you are using a non-US-english number format (where the meaning of `.` and `,` are different)? So `10.119` means `10119` requests per second, rather than just over `10` requests per second (as it would in US english).

Anyway, this is useful data, thanks!

**Comment by anurse** [comment] 2019-05-14 22:03
Do you have the `stdout` redirection enabled in your out-of-process web.config file? That could be why out-of-proc appears so much faster since it isn't capturing the standard output of the server process.

**Comment by anurse** [comment] 2019-05-14 22:03
Also, could you publish your sample application (even if it is just a File > New Project) so we can take a look at it in detail and make sure we're on the same page?

**Comment by anurse** [comment] 2019-05-14 22:04
(Note: We should do some profiling when doing https://github.com/aspnet/AspNetCore/issues/10005 as it may be affected by this performance issue)

**Comment by Kossx2** [comment] 2019-05-16 21:16
> 
> 
> Do you have the `stdout` redirection enabled in your out-of-process web.config file? That could be why out-of-proc appears so much faster since it isn't capturing the standard output of the server process.

Having stdoutLogEnabled enable doesn't affect performance in a big way.

**Comment by Kossx2** [comment] 2019-05-16 21:17
> 
> 
> Also, could you publish your sample application (even if it is just a File > New Project) so we can take a look at it in detail and make sure we're on the same page?

Sure! There you are: [https://github.com/Kossx2/PerformaceTest](url)

**Comment by anurse** [comment] 2019-05-16 21:32
Thanks! We can take a look at this. We've got some high priority work going on right now (for 3.0 preview 6) but I've put this in the preview 7 milestone to revisit.

**Comment by matthewblott** [comment] 2019-06-10 09:52
I can confirm this is an issue, glad to see it's being worked on :-)

**Comment by anurse** [comment] 2019-06-10 17:49
I'm actually going to close this in lieu of https://github.com/aspnet/Extensions/issues/1817 which was filed as part of investigation in to this in our own performance lab. If the finding there don't align with what you're seeing, please feel free to discuss further on that issue. Any fixes will be in logging rather than in the servers directly, hence why I'm closing this one and shifting the focus to that issue.

**Closed by anurse** 2019-06-10 17:49 UTC
Labels: area-servers, area: Performance
