### ISSUE TITLE
Blazor OnInitAsync method returns output only after the async part completes when @page called by GET method.

### ISSUE THREAD

**Issue by KrystofZacek** [aspnet/AspNetCore#12866] opened 2019-08-04 20:50 UTC
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by KrystofZacek** [comment] 2019-08-04 20:57
Blazor Preview 7, VS 2019, 16.3 preview 1
Consider the bellow attached Server-side Blazor @page /foo. When calling the page by GET (e.g. not by click but by enetring URL localhost:5000/foo in the browser or pressing F5 when on foo page) the following happens:

- sync part of OnInitAsync gets executed
- rendering is called afterwards as expected but NO output is sent to browser, Browser is still waiting for response.
- when the async part of OnInitAsync completes then rendering occurs again and only then the output is sent to browser.

@page “/foo”
<p>Status: @m_status</p>

@code {
private string m_status = “”;

protected async override Task OnInitAsync()
{
    m_status = "Loading...";
    await Task.Delay(3000);

    m_status = "Done";
    await base.OnInitAsync();
}
}

**Comment by mkArtakMSFT** [comment] 2019-08-05 16:21
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.
This is so that you can'd do asynchronous work before pre-rendering produces its output. If you don't want to have this behavior you can inject a type `IComponentContext` and check `IsConnected` property on it to avoid doing async work.

**Closed by mkArtakMSFT** 2019-08-05 16:21 UTC
Labels: area-blazor

**Comment by KrystofZacek** [comment] 2019-08-06 06:37
OK. Just please make sure such unintuitive gotchas are well documented. Current documentation is pretty rudimentary.
