### ISSUE TITLE
ActionFilterAttribute，IAsyncAuthorizationFilter no  IAllowAnonymousFilter

### ISSUE THREAD

**Issue by ghd258** [aspnet/AspNetCore#15002] opened 2019-10-15 02:15 UTC
if(context.Filters.Any(filter=>filter is IAllowAnonymousFilter))
            {
                return;
            }
return all  false

**Comment by javiercn** [comment] 2019-10-15 10:52
@ghd258 thanks for contacting us.

Can you provide more details about the issue you are experiencing?

**Comment by ghd258** [comment] 2019-10-16 03:40
public class ApiAuthorizeFilter : IAsyncAuthorizationFilter
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public async Task OnAuthorizationAsync(AuthorizationFilterContext context)
        {
            if (context.Filters.Any(filter => filter is IAllowAnonymousFilter))
            {
                return;
            }

        }

 public class MenuActionAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
          
            if (context.Filters.Any(item => item is IAllowAnonymousFilter))
            {
                return;
            }
        }
     }
    }

**Comment by javiercn** [comment] 2019-10-16 06:52
@ghd258 We still can't understand what you are asking. Can you please provide a few sentences about what your problem is, what your expected behavior is and what you are actually seeing? 

That will help us give you an answer.

**Comment by ghd258** [comment] 2019-10-16 06:56
https://q.cnblogs.com/q/DetailPage/120427/

**Comment by javiercn** [comment] 2019-10-16 07:02
From the link (Translated from chinese I think)
>In previous versions of .netcore 3.0, the project implemented IAsyncAuthorizationFilter to intercept requests and verify that permissions were required for authentication. When the Action is configured with the AllowAnonymous feature, no permission validation is required.
>
>So in the code, it will determine whether there is AllowAnonymousFilter by getting the IFilterMetadata collection of the current context.
>
>After the framework is upgraded to 3.0, the AllowAnonymousFilter cannot be found in the IFilterMetadata collection of the AuthorizationFilterContext.

I'm not sure what has changed in this area for 3.0

**Comment by ghd258** [comment] 2019-10-16 07:05
3.0  no  IAllowAnonymousFilter

**Comment by ghd258** [comment] 2019-10-16 07:08
[HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginModel loginModel)
        {
        }


if (context.Filters.Any(filter => filter is IAllowAnonymousFilter))
            {
                return;
            }
2.0 returns true but 3.0 returns flash

**Comment by javiercn** [comment] 2019-10-16 08:11
ASP.NET Core 3.0 includes a new feature "Endpoint Routing" that is used by default. When that is used, we don't add filters to the action, but instead it's the authorization middleware the one that takes care of handling the authorization process.

As such, the [AllowAnonymous] attribute is the piece of data you need to use to make any decision. You can access the metadata as
```csharp
var endpointFeature = httpContext.GetFeature<Microsoft.AspNetCore.Http.Features.IEndpointFeature>();
var metadata = endpointFeature?.Endpoint?.Metadata;
```

**Comment by javiercn** [comment] 2019-10-16 10:40
Closing this issue as the behavior here is by design.

**Closed by javiercn** 2019-10-16 10:40 UTC
Labels: area-mvc, by design
