### ISSUE TITLE
Custom dependencies injected into Startup class.

### ISSUE THREAD

**Issue by eddie-jb** [aspnet/AspNetCore#14542] opened 2019-09-28 02:23 UTC
Question - Can we not inject custom dependencies into a startup class anymore?
My dotnet info

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```

If I use `dotnet new webapi --name SomeProj` and modify the Program.cs and Startup.cs files to the following.

### Program.cs
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace SomeProj 
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices(services => services.AddTransient<Testing>())
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>());
    }

     public class Testing
     {
     }
}
```

### Startup.cs
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace SomeProj 
{
    public class Startup
    {
        Testing _testing;

        public Startup(IConfiguration configuration, Testing testing)
        {
            Configuration = configuration;
            _testing = testing;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
```

And then run `dotnet run` I get the following exception
```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'SomeProj.Testing' while attempting to activate 'SomeProj.Startup'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at SomeProj.Program.Main(String[] args) in C:\Work\testing\Startup\Program.cs:line 11
```

**Comment by davidfowl** [comment] 2019-09-28 04:27
See https://github.com/aspnet/Announcements/issues/353. It’s by design. The web host still supports this but there’s no plan to bring that functionality back

**Comment by Pilchie** [comment] 2019-10-02 16:20
Closing as this is answered.

**Closed by Pilchie** 2019-10-02 16:20 UTC
Labels: question
