### ISSUE TITLE
The TagHelpers component sets the asp-append-version property, which is invalid on linux (centos7)

### ISSUE THREAD

**Issue by netnr** [aspnet/AspNetCore#4000] opened 2018-11-11 04:37 UTC
```js
<script src="/js/mix/about.js" asp-append-version="true"></script>
```
Set asp-append-version, invalid on linux (centos7), feasible on windows

**version 2.1.403**

**Comment by Eilon** [comment] 2018-11-26 20:56
Can you explain what you mean by "invalid on Linux"? It's just an ASP.NET Core tag helper attribute, it is not OS-specific.

**Comment by netnr** [comment] 2018-11-26 23:31
Is running on linux, there is no version number behind

**Comment by Eilon** [comment] 2018-11-27 06:20
Can you show exactly what got rendered in the output HTML?

**Comment by netnr** [comment] 2018-11-27 06:31
https://github.com/netnr/netnrf/blob/master/src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_Layout.cshtml

https://rf2.netnr.com/home/desk
view-source:https://rf2.netnr.com/home/desk

**Comment by Eilon** [comment] 2018-11-27 06:39
Thank you for the details, we will have a team member investigate.

**Comment by mkArtakMSFT** [comment] 2018-11-28 18:35
Thanks for contacting us, @netnr.
@NTaylorMullen, what can be done here? Should we just not append the version info when run on linux?

**Comment by NTaylorMullen** [comment] 2018-11-28 19:14
@netnr could you provide a more minimal repro? I've tried reproducing this in a publish-like scenario and I'm seeing versions being appended:
![image](https://user-images.githubusercontent.com/2008729/49176034-c7a69c00-f2fe-11e8-8e7f-b605dd3d3e7c.png)

**Comment by netnr** [comment] 2018-11-28 23:59
Sorry, I am creating a new project for testing, there is a version number, maybe the original project is missing a reference.

https://github.com/netnr/test/blob/master/src/Netnr.Test/Views/AspAppendVersion/Index.cshtml

https://test.netnr.com/aspappendversion

**Comment by NTaylorMullen** [comment] 2018-11-29 00:04
I'd suggest verifying that the files you expect to have versions appended are on disk. If the version generator can't find the file on disk it fails to generate the 

Closing this for now since it seems we've ruled out the scenario of a product bug 😄

**Closed by NTaylorMullen** 2018-11-29 00:04 UTC
Labels: area-mvc, investigate
