### ISSUE TITLE
Actix scenarios not running

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14053] opened 2019-09-17 01:50 UTC
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| FortunesPostgreSql-Actix | Linux, Physical, http, KestrelSockets | 9/16/19 1:24:04 AM +00:00 |
| Json-Actix | Linux, Physical, http, KestrelSockets | 9/16/19 1:23:13 AM +00:00 |
| Plaintext-Actix | Linux, Physical, http, KestrelSockets | 9/16/19 1:22:22 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment] 2019-10-01 23:21
Duplicate of https://github.com/aspnet/AspNetCore/issues/14495

**Closed by sebastienros** 2019-10-01 23:21 UTC
Labels: not-running
