### ISSUE TITLE
Add an overload for IWebHostBuilder.Configure that takes in AssemblyName

### ISSUE THREAD

**Issue by fitdev** [aspnet/AspNetCore#14183] opened 2019-09-20 08:12 UTC
### Is your feature request related to a problem? Please describe.
I am trying to create an internal library-based framework for authoring "hosted" apps, including ASP.NET apps. As such, I am not relying on the Startup class approach and instead [I am following your guidelines for Startup-less configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0#configure-services-without-startup).

The problem comes if this configuration is split across several assemblies. In my case, there would be a "top-most" assembly with controllers and views, which would depend on other assemblies that are responsible for configuring ASP.NET. Turns out that routing does not work properly if [IWebHostBuilder.Configure](https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/WebHostBuilderExtensions.cs#L24) is called from other assembly (that does not contain controllers and actions).

### Describe the solution you'd like
Ideally, it would be really nice if there was a mechanism to clearly provide all controller and action (and possibly other endpoint) "sources" as part of configuration process, perhaps as an overload of `IWebHostBuilder.Configure` accepting either a single AssemblyName as a string, or better yet an params? array of assembly names that should be looked in for relevant types (controllers, etc.).

**Comment by Tratcher** [comment] 2019-09-20 16:55
`Turns out that routing does not work properly if IWebHostBuilder.Configure is called from other assembly (that does not contain controllers and actions).` @rynowak this is because MVC/routing depends on AppName for discovering controllers, right? And AppName is set based on the caller of Configure.

**Comment by davidfowl** [comment] 2019-09-20 17:35
This has actually been broken since inception. Hosting tries to deduce the "application assembly" from the Startup class or the class that contains the Configure delegate, dupe of https://github.com/aspnet/AspNetCore/issues/7315.

We shouldn't be adding anything to hosting here, this is mainly about controller discovery and there are ways to explicitly add assemblies (https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2). 

Going forward we'll need to decide what our defaults are.

**Comment by mkArtakMSFT** [comment] 2019-09-23 16:50
@davidfowl is there any other action pending here?

**Comment by davidfowl** [comment] 2019-09-24 03:58
Closed.

**Closed** 2019-09-24 17:20 UTC
Labels: area-hosting, area-mvc
