### ISSUE TITLE
[Blazor] Select tag is not bound on first render

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#6550] opened 2019-01-10 00:51 UTC
In the following example, the **initial value** of `currentServer` is not bound to the select tag.
And if I specify `select="selected"` in one option, then it's not reflected in the variable.
It works when I change the variable by code, or when the selection is changed.

Sample:
```
<p>Current server: @currentServer</p>

<div class="form-group">

    <select class="form-control" bind="@currentServer">
        <option value="WindowsPhysical">Windows - Physical</option>
        <option value="LinuxPhysical">Linux - Physical</option>
        <option value="WindowsCloud">Windows - Cloud</option>
        <option value="LinuxCloud">Linux - Cloud</option>
    </select>

</div>

<button class="btn btn-primary" onclick="@RunJob">Run</button>

@functions {
    string currentServer = "LinuxCloud";

    void RunJob()
    {
        currentServer = "WindowsCloud";
    }
}
```

**Comment by sebastienros** [comment] 2019-01-10 19:23
I could solve this behavior by setting the default value in `OnInit()` instead of assigning the value on the variable declaration.

**Comment by Andrzej-W** [comment] 2019-01-10 19:40
Similar to #6427 and #5616

**Comment by SteveSandersonMS** [comment] 2019-06-25 20:39
Yep, this is a duplicate of #5616 which we plan to fix in the current milestone.

**Closed by SteveSandersonMS** 2019-06-25 20:39 UTC
Labels: 1 - Ready, PRI: 2 - Preferred, area-blazor, bug, cost: S
