### ISSUE TITLE
HttpContext.Session.GetString Not Working on Linux

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#14012] opened 2019-09-15 16:50 UTC
_From @ZackTech on Tuesday, September 10, 2019 6:56:59 AM_

I have an Asp.net Core application version 2 (I have yet to upgrade it to version 2.2and beyond)

The following code generates a Captcha image:
```
public FileStreamResult GetCaptchaImage()
        {
            int width = 200;
            int height = 60;

            string captchaCode = Captcha.GenerateCaptchaCode();
            
            var result = Captcha.GenerateCaptchaImage(width, height, captchaCode);

            HttpContext.Session.SetString("CaptchaCode", result.CaptchaCode);

            Stream s = new MemoryStream(result.CaptchaByteData);

            return new FileStreamResult(s, "image/png");
        }
```
When I test the Captcha code is correct with code like this:
```
if (viewModel.CaptchaCode != HttpContext.Session.GetString("CaptchaCode"))
{
}
```
It works fine on my local windows PC and on Azure but not on a Ubuntu VPS.
On the Ubuntu VPS it always comes back as null.

I build the project on a Windows PC using the following commands:
```
dotnet restore -r ubuntu.16.04-x64
dotnet build -r ubuntu.16.04-x64
dotnet publish -f netcoreapp2.0 -c Release -r ubuntu.16.04-x64
```
And then  publish to Linux.

Any ideas how I can fix this?

_Copied from original issue: dotnet/corefx#41116_

**Comment by Tratcher** [comment] 2019-09-15 16:50
_From @davidsh on Sunday, September 15, 2019 2:34:14 PM_

@Tratcher This looks like an ASP.NET issue

**Comment by Tratcher** [comment] 2019-09-15 16:51
Anything in the server logs?

**Comment by ZackTech** [comment] 2019-09-16 05:46
Unfortunately there are no messages generated in the server logs, I re-checked this morning.

**Comment by Tratcher** [comment] 2019-09-16 14:48
Turn your log levels up to Debug, Session always writes some logs.

**Comment by ZackTech** [comment] 2019-09-17 13:02
[crmwebsite.out.log](https://github.com/aspnet/AspNetCore/files/3621379/crmwebsite.out.log)

That is the log file ^^^^^

**Comment by Tratcher** [comment] 2019-09-17 14:59
```
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.0 GET http://localhost:54446/UserAccount/GetCaptchaImage?code=VB74  
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /UserAccount/GetCaptchaImage does not match a supported file type
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Routing.RouteConstraintMatcher[1]
      Route value 'UserAccount' with key 'area' did not match the constraint 'Microsoft.AspNetCore.Mvc.Routing.KnownRouteValueConstraint'.
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action Crm.WebSite.Controllers.UserAccountController.GetCaptchaImage (Crm.WebSite)
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Crm.WebSite.Controllers.UserAccountController.GetCaptchaImage (Crm.WebSite) with arguments (VB74) - ModelState is Valid
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Session.DistributedSession[2]
      Accessing expired session, Key:5be4992c-3a19-0eb7-d292-5dcf8729a9af
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Crm.WebSite.Controllers.UserAccountController.GetCaptchaImage (Crm.WebSite), returned result Microsoft.AspNetCore.Mvc.FileStreamResult.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.VirtualFileResultExecutor[1]
      Executing FileResult, sending file as 
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[6]
      Connection id "0HLPRDNIQ1M9A" received FIN.
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLPRDNIQ1M9A" disconnecting.
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[7]
      Connection id "0HLPRDNIQ1M9A" sending FIN.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Crm.WebSite.Controllers.UserAccountController.GetCaptchaImage (Crm.WebSite) in 10.4434ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Session.SessionMiddleware[10]
      Committing the session was canceled.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 15.4873ms 200 image/png
```

Ah, this explains it: "Committing the session was canceled.". The request was made using HTTP/1.0 and the result had a fixed content-length, so the client disconnected as soon as it received the response but before the session was saved.

Do you control the client? Why is the client using HTTP/1.0 instead of HTTP/1.1? 1.1 would be a lot more efficient and would avoid closing the connection immediately.

The link between client disconnect and session commit has caused several problems like this so we disconnected them in 3.0. Would you be able to try this on 3.0?

The other workaround you can use is to call Session.CommitAsync after you set the session values and before you send the response. Then it won't matter that the client disconnects.

On another note, you should check on your data protection configuration:
```
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
```

Protected data like your session keys will stop working if the server restarts.
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2

**Comment by anurse** [comment] 2019-09-17 22:43
Closing this as we believe it is fixed in 3.0. Feel free to comment/reopen if it still reproduces in 3.0!

**Closed by anurse** 2019-09-17 22:43 UTC
Labels: area-middleware

**Comment by ZackTech** [comment] 2019-09-23 09:47
Thanks Tratcher, Session.CommitAsync seems to be the answer.

>>
Do you control the client? Why is the client using HTTP/1.0 instead of HTTP/1.1? 1.1 would be a lot more efficient and would avoid closing the connection immediately.
<<

Been on freenode in the nginx chat room and they tell me my nginx config is OK. May be I need to do something to the Kestrel application?

**Comment by Tratcher** [comment] 2019-09-23 14:43
The caller (proxy) selects the protocol version, not the server. Did you try the nginx config from our docs?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#configure-nginx
