### ISSUE TITLE
Razor Components - Parameters passed through RenderComponentAsync are lost after Prerendering

### ISSUE THREAD

**Issue by honkmother** [aspnet/AspNetCore#8596] opened 2019-03-17 08:24 UTC
### Describe the bug
Parameters passed through RenderComponentAsync are lost immediately after prerendering.

### To Reproduce
Razor Components Preview3 0.9
`@(await Html.RenderComponentAsync<html>(new { Example = "something" }))`

`[Parameter] private string Example {get; set;}` is null after prerendering is finished.

### Expected behavior
For passed parameters to persist after prerendering is finished.

This is probably an actual issue (it could just be countless hours of sleep derivation at this point).

I figured out a workaround after posting this by creating a component and juggling the parameters; but the reality is the way I was trying to initially do this should have worked out of the box. Whenever I passed `Example` into the Cascade, it would always be null after Prerendering was finished.

To give you an idea of the weirdness I'm doing at 4:40 AM...
This works as expected, when inside of Body.razor you pass the reference forward as a CascadeValue so that the children Components can get access to the Metatags object.

So yeah, as of 5:40 AM I now have fully proper SEO.. without any weird hacking up Index.cshtml and using unclosed tags.

```C#
    public class html : ComponentBase
    {
        public static string HeadTXT = File.ReadAllText("head.htm");
        Metatags meta = new Metatags() { Title = "zzzzzzzz" };
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "head");
            builder.AddMarkupContent(1, HeadTXT);
            builder.OpenComponent<Head>(2);
            builder.AddAttribute(3, "MetaInfo", meta);
            builder.CloseComponent();
            builder.CloseElement();

            builder.OpenElement(4, "body");
            builder.OpenComponent<Body>(5);
            builder.AddAttribute(6, "MetaInfo", meta);
            builder.CloseComponent();
            builder.AddMarkupContent(7, "<script src=\"_framework/components.server.js\"></script>");
            builder.CloseElement();

        }
    }

```

)

**Comment by mkArtakMSFT** [comment] 2019-03-18 21:09
Thanks for contacting us, @honkmother.
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment] 2019-03-18 21:13
This is by design for now until we finish the "robust reconnect" feature.

**Comment by SteveSandersonMS** [comment] 2019-03-22 16:19
Closing as by design currently, though as @javiercn notes, we will later add a feature that changes this design.

**Closed by SteveSandersonMS** 2019-03-22 16:19 UTC
Labels: area-mvc, feature-Components

**Comment by javiercn** [comment] 2019-03-22 16:35
Related issue: https://github.com/aspnet/AspNetCore/issues/8034
