### ISSUE TITLE
[Blazor] Add ability to add/remove link tag in header via code

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#12413] opened 2019-07-21 17:24 UTC
When using dynamic Google fonts, we need to set the link in the header to point to the required font. As our users can change their font dynamically, how can we have the link in the header also changed? As there are over 900 Google fonts, putting them all into the header would not be feasible. 

Example:
```
<link href='https://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet'>
then use font-family: 'ABeeZee'; for the element
```

Thanks for the consideration :)

**Comment by Joe4evr** [comment] 2019-07-21 17:37
Potential duplicate of #9128.

**Comment by mkArtakMSFT** [comment] 2019-07-22 16:18
Thanks for contacting us, @VR-Architect .
You should simply use JSInterop for this.

**Closed by mkArtakMSFT** 2019-07-22 16:18 UTC
Labels: area-blazor

**Comment by VR-Architect** [comment] 2019-08-06 00:01
Actually, just putting the link in the component worked like magic! Guess I should have tried it first
