### ISSUE TITLE
With Two Factor enabled,  need ability to determine if the user is only password authenticated

### ISSUE THREAD

**Issue by nauticalcoder** [aspnet/AspNetCore#10044] opened 2019-05-07 16:55 UTC
### Is your feature request related to a problem? Please describe.
The Authorize attribute is either on or off but we would like the ability to control access to endpoints based on whether the user is password authenticated only, or has also verified their second factor.

### Describe the solution you'd like
There are several possibilities.  One could be a separate Authorize attribute or some parameter that could be passed to the Authorize attribute.  If that isn't possible, at least a simple function in the SignInManager that would let us know how far the user has gotten in the authentication process.

**Comment by brockallen** [comment] 2019-05-07 18:22
This is what the `AuthenticationType` property (and ctor arg) is for on `ClaimsIdentity`:
https://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsIdentity.cs,451

**Comment by nauticalcoder** [comment] 2019-05-07 19:16
I may not have explained the scenario very well.  The scenario I am referring to is when a user has 2fa enabled and comes to the site to login.  We first call `PasswordSignInAsync`.  At this point, I would like to be able to know that this user has "Password Signed In".  Unfortunately, if I look at the ClaimsIdentity or the ClaimPrinciple, nothing has been set yet.  The auth provider must know from that the state we are in, otherwise the next step of calling `TwoFactorAuthenticatorSignInAsync` would not work correctly.  I would like to have some way of knowing  that a user with 2fa enabled has password signed in, but not yet verified their authenticator code.

**Comment by blowdart** [comment] 2019-05-08 08:20
@HaoK is there a way to do this?

**Comment by nauticalcoder** [comment] 2019-05-08 16:09
Just a follow up and explain what I am trying to accomplish.  We would like to restrict the endpoints for verifying the authenticator code, using a recovery code, etc to users that have signed in with their password but not yet finished the 2FA process.  We also have some endpoints during the registration process that we would also like to restrict to users that have completed the password sign in process.  The reference implementation leaves those endpoints as allowing anonymous and we would like to prevent that.

**Comment by mderriey** [comment] 2019-05-15 05:54
Hey @nauticalcoder

Behind the scenes, Identity uses several cookies to differentiate users that:

- signed in with password only;
- signed in with password but need to complete MFA;
- signed in with password, completed MFA and checked the "Remember me" checkbox.

Each of those cookies is registered in the authentication system with different scheme names. See the [`IdentityConstants`](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Identity/Core/src/IdentityConstants.cs) class.

If you want to restrict endpoints for people who signed in with passwords but still need to complete MFA, you can decorate the controllers and/or actions with an `[Authorize(AuthenticationSchemes = IdentityConstants.TwoFactorUserIdScheme)]` attribute.

**Comment by blowdart** [comment] 2019-05-15 20:12
Dupe of https://github.com/aspnet/AspNetCore/issues/5783 where we will get the amr claim on a user

**Closed by blowdart** 2019-05-15 20:12 UTC
Labels: area-identity
