### ISSUE TITLE
[Preview 8] Typescript generated js file in wwwroot in RCL not included

### ISSUE THREAD

**Issue by MarkStega** [aspnet/AspNetCore#13122] opened 2019-08-14 12:13 UTC
### Describe the bug
Typescript generated js file in wwwroot in Razor Class Library not included as content.

### To Reproduce
1. Using ASP.NET Core 3.0P8/VS2019 16.3.0P2
2. See #12646 that was closed but without a resolution
3. Same error as described

### Expected behavior
Expect JS that was generated by TSC to be included as a static asset without having to manually create a target for the generated file.

**Comment by mkArtakMSFT** [comment] 2019-08-14 16:35
Thanks for contacting us, @MarkStega.
We'll cover this through docs.

**Comment by MarkStega** [comment] 2019-08-14 17:29
In the meantime, what is the "magic sauce" needed to force the inclusion of generated wwwroot\js files as content?

**Comment by SQL-MisterMagoo** [comment] 2019-08-14 21:10
@mkArtakMSFT I have a github repo here https://github.com/SQL-MisterMagoo/BlazorPreview_8_Typescript_Sample - where the Typescript file is correctly compiled to a JS file and is included as a static web asset.

The JS content is served up correctly in the Server-side blazor project, but only if the ASPNETCORE_ENVIRONMENT is set to Development. If you change that environment setting, the asset is no longer served. 

This means you cannot publish the Server-Side Blazor project and expect static web assets to work.

The repo contains one Client-Side project, one Server-Side project and a component library - all produced using the templates from preview 8.

The RCL project also has EmbeddedResources because that is the only way to get the static web assets to work in Client-Side currently.

Hopefully this helps with reproducing the problems.

**Comment by mkArtakMSFT** [comment] 2019-08-15 02:09
Thanks for the info, @SQL-MisterMagoo.
@javiercn do you have any recommendation here? Would be great to put it here, if it's quick, before you get to the docs.
If not very simple, that's ok - do it when you get to this.

For context to others, this is scheduled to be handled during preview 9, so not much left for this to be handled.

**Comment by javiercn** [comment] 2019-08-22 17:41
You need to add TypeScriptCompile as a dependency for resolving the static web assets for the current project so that the typescript build happens before we compute the list of static web assets for the current project.
```xml
    <ResolveCurrentProjectStaticWebAssetsInputsDependsOn>
      TypeScriptCompile;
      $(ResolveCurrentProjectStaticWebAssetsInputsDependsOn)
    </ResolveCurrentProjectStaticWebAssetsInputsDependsOn>
```

You might also need to remove any unwanted output to prevent them from being included as content or contentFiles in the package. You can do so by adding your own custom target.

This will work in preview9 and onwards.

**Comment by javiercn** [comment] 2019-08-22 17:47
Filed an issue to track the addition to the docs. https://github.com/aspnet/AspNetCore.Docs/issues/13969

Closing this one as there's no further action to be taken here.

**Closed by javiercn** 2019-08-22 17:47 UTC
Labels: Docs, area-mvc
