### ISSUE TITLE
Validation attributes not added for fields with duplicate names on the same form

### ISSUE THREAD

**Issue by akraines** [aspnet/AspNetCore#6584] opened 2019-01-10 23:47 UTC
Validation attributes not added for model Properties with duplicate **names** rendered at the same time if they are in the same form (or are _both_ not in Html.BeginForm section) - even if the Properties are members of different classes!
Please see [this SO question](https://stackoverflow.com/questions/39807978/strange-behavior-of-asp-net-mvc-razor-engine-with-unobtrusive-validation-attribu) where the user describes the same issue.

### To Reproduce
Make 2 Model classes with properties which have the same name and have the Required attribute.
Make 3 Views: 1 for each model and a 3rd one which  @await Html.PartialAsync renders the 2 Views
The 2 views should have these lines (Not in a BeginForm block)
```
@Html.TextBoxFor(m => new Model1().FirstName)
@Html.ValidationMessageFor(m => new Model1().FirstName, "")

```
Make 3 controller actions: one for each view.

### Expected behavior
The rendered inputs should have the data-val-required attributes

Here is the comment that I wrote in my code to describe this issue:
Context:
There are 2 Models which are almost identical: ClientPricings and VendorPricings, except that VendorPricings has one additional property called "Vendor".
```
@*
* 
* There is some bug with razor pages that it sometimes doesn't add data validation to inputs unless they are in a form.
* I noticed that this only occurred when rendering this view as a child of ProjectView && only for fields that occur also outside of a form: Eg. UnitTypePrice which also exists as a property
* of ClientPricings. I think that the Razor renderer notices a duplicate property name and only applies the validation attributes to the first occurrence in any context. Since neither "model-container-table" 
* is in a form, the renderer groups them together and only applies the attribute to the first occurrence. That is why only the Vendor column (in the Vendor view) gets a star (with js code to highlight required fields) as opposed to the other fields, since vendor is the only 
* property name that is unique to vendor pricings over client pricings, so the razor page renderer is willing to add the attribute there.
* This also explains why after clicking submit suddenly the validation attributes are added - this is because getvendorpricings only updates the vendor form and the razor renderer no longer 
* runs into the above issue (since the client page isn't being rendered at the same time)   
 *@
```

**Comment by mkArtakMSFT** [comment] 2019-03-27 16:51
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Closed by mkArtakMSFT** 2019-03-27 16:51 UTC
Labels: area-mvc
