### ISSUE TITLE
[SignalR] Possibility to catch custom (hub)exceptions in client

### ISSUE THREAD

**Issue by ddweber** [aspnet/AspNetCore#11891] opened 2019-07-04 08:14 UTC
I´ve read in aspnet/SignalR#3009 that it is possible to throw custom exceptions on the hub which inherit from `HubException ` so that they will be propagated to the clients.
I want to catch this custom exceptions on the clients so that i can react accordingly. Is there any possible way to do that? I would like to do some kind of:

```csharp
try
{
    connection.InvokeAsync().Wait();
}
catch (CustomException ex) 
{
    ...
}

OR

catch (Exception ex) when (ex is CustomException)
{
    ...
}
```

At the moment im doing it as the follwing because only the exception-message contains the name of the CustomException, but that is not ideal:
```csharp
try
{
    connection.InvokeAsync().Wait();
}
catch (Exception ex) when (ex.InnerException.Message.Contains("CustomExceptionName"))
{
    ...
}
```

**Comment by anurse** [comment] 2019-07-05 18:35
We don't preserve the actual exception type right now, just the message. The issue is that SignalR's protocol is intentionally .NET-agnostic (i.e. it doesn't assume that either the server or client are running .NET code), so we can't just encode the exception type. This is something we have considered before, but for now your workaround is the best solution.

**Comment by anurse** [comment] 2019-07-05 18:36
Another design question to consider is what if the exception type isn't available on the client application? It's not likely that `catch(CustomException)` would ever work. Perhaps something like `catch(HubException ex) when (ex.ServerExceptionType == "CustomException")` could work eventually.

**Comment by anurse** [comment] 2019-07-30 21:27
Given the design challenges noted above and our current plans, this isn't something likely to bubble up in our priority list. Closing the issue to reflect that.

**Closed by anurse** 2019-07-30 21:27 UTC
Labels: area-signalr, enhancement
