### ISSUE TITLE
Razor Components - Disable PreRendering

### ISSUE THREAD

**Issue by keithwill** [aspnet/AspNetCore#8744] opened 2019-03-22 17:26 UTC
Is there a way to disable Razor Components prerendering?

With the API changing in Startup.cs at the same time as prerendering was enabled in the razor components template, I can't find any guidance on how to run from an index.html file instead of index.cshtml.

**Comment by dodyg** [comment] 2019-03-24 13:49
`<app>@(await Html.RenderComponentAsync<App>())</app>`

remove the `@(await Html.RenderComponentAsync<App>())` and you won't have pre-rendering.

**Comment by keithwill** [comment] 2019-03-25 12:00
@dodyg 
Thanks! I think that meets the concerns for my current project. 

The question still remains as to how to set up a Razor Components project to use an index.html instead of an index.cshtml. I think it is a valid use case.

I don't know that using a CDN to host the index.html is that useful, but many other JS tools expect a root html file for their entry points. For example, what entry point do I use if I want to write my JS interop methods in TypeScript and compile them at build time? Do some css build tools expect an entry point? I think most browser packagers (e.g. WebPack) will expect an entry point.

**Comment by xclud** [comment] 2019-03-25 12:16
@keithwill Delete Index.cshtml and put index.html in wwwroot folder. Make sure UseStaticFiles is there.

**Comment by keithwill** [comment] 2019-03-25 12:21
@xclud
I tried that. It didn't seem to work. It wouldn't load index.html unless I navigated to it, and then it couldn't find _framework/components.server.js. I was under the impression (perhaps mistakenly) the previous template that used index.html required the SPA middleware, and I'm not sure if that is true anymore.

**Comment by SteveSandersonMS** [comment] 2019-03-25 15:49
Inside your `Startup.cs`, in the `UseRouting` block, use `builder.MapFallbackToFile` if you want to configure fallback to an `index.html` file.

Closing as the original question (how to disable prerendering) has been answered.

**Closed by SteveSandersonMS** 2019-03-25 15:49 UTC
Labels: area-mvc, feature-Components

**Comment by cores-system** [comment] 2019-04-21 15:43
The problem is again relevant, the @dodyg method no longer works

**Comment by SteveSandersonMS** [comment] 2019-04-22 10:04
@cores-system Since this issue is closed, if there is a problem, could you please open a new issue and include repro steps for whatever the problem is?

**Comment by cores-system** [comment] 2019-04-22 10:10
@SteveSandersonMS , I apologize, I found the current PR https://github.com/aspnet/AspNetCore/pull/8911 which contains the new rendering logic.
