### ISSUE TITLE
Identity UI Register should offer providers

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#8131] opened 2019-03-03 02:14 UTC
Going via Login to register with Google account and not being able to do it via Register; is a bit of a weird UX.

If providers are registered; Register does not show them as a method to create a new account

![image](https://user-images.githubusercontent.com/1142958/53689978-a029fa00-3d59-11e9-9c9b-444350790dc1.png)

However, Login will show them, and you can use Login with an external provider to create a new account

![image](https://user-images.githubusercontent.com/1142958/53689984-bfc12280-3d59-11e9-9fcc-11769571bff1.png)

If you are a new user the expectation is likely that you will have to go via the Register page; and the idea of going via Login because you have an account somewhere else so therefore you also have an account here is a bit meta.

**Comment by alexsandro-xpt** [comment] 2019-03-03 05:45
:ok_hand:
I don't know why this never was thinking as project default before...

**Comment by HaoK** [comment] 2019-03-09 00:04
Yep this is a dupe of https://github.com/aspnet/AspNetCore/issues/5766 and should be fixed in preview4 builds

**Closed by HaoK** 2019-03-09 00:04 UTC
Labels: area-identity
