### ISSUE TITLE
Kestrel logging should be more informative about application crashes.

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#13929] opened 2019-09-12 17:57 UTC
### Describe the bug
This isn't really a bug and also not really a feature. I think logging should be improved at a particular point in kestrel:
![grafik](https://user-images.githubusercontent.com/5545184/64808000-af0a2880-d596-11e9-89c3-e25f3edf279c.png)

i executed the following command in powershell to verify my program works:
dotnet run .\ShutdownTimer.Server.csproj --console --no-launch-profile
based on https://github.com/taori/ShutdownTimer/commit/b1c3cb865e0d5c0e4dbea1302591f353c65458e8

After looking for clues what happened here i tried my luck in eventviewer which contained the relevant details:

```cs
Microsoft.AspNetCore.Server.Kestrel
Unable to start Kestrel.

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Das System kann den angegebenen Pfad nicht finden
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```

Die Meldungressource ist vorhanden, aber die Meldung wurde nicht in der Zeichenfolge-/Meldungstabelle gefunden

### Expected behavior
It would be good if that error was shown in powershell instead of just silently logging it in eventviewer.

**Comment by Tratcher** [comment] 2019-09-13 14:56
Translation: `WindowsCryptographicException: The system can not find the specified path`

Was "Application is shutting down..." the full powershell output?

**Comment by taori** [comment] 2019-09-13 17:44
Yes. only when using dotnet run -v diag i even saw messages indicating that something is wrong with the cert - no indication of the reason of the crash however.

**Comment by Tratcher** [comment] 2019-09-16 15:04
Failing to start the server should be the reason for the crash. That exception should have been written to the console before the application shut down.

Are the results any different if you run it from the bin folder `dotnet ShutdownTimer.Server.dll`?

**Comment by taori** [comment] 2019-09-16 17:48
@Tratcher it is compiled as exe - i suppose that is what you meant. Unforuntately not, no. Both launching it as service and launching it manually with dotnet *.exe --console returned the same output. Could adding event logging possibly make a difference here and discard the log message after forwarding it to event log? One way or another this really should be displayed in the console too :)

**Comment by anurse** [comment] 2019-10-08 23:00
Are you catching the exception in Program.Main? It looks like you might be:

https://github.com/taori/ShutdownTimer/blob/423da8969fa441003c39cc1c0e784615360824c9/src/ShutdownTimer.Server/Program.cs#L53

If you do this, nothing will write the exception to the console because it's not escaping Program.Main.

**Comment by taori** [comment] 2019-10-08 23:03
Unfortunately by the time of reading this i scrapped the migration table and recreated the model so i can't debug it again. If it happens again i'll check the logs and post them though

**Comment by anurse** [comment] 2019-10-23 18:44
Ok, I'm going to close this now since we don't really have enough info to work with. Please let us know if you can reproduce it and we can re-open it to investigate further!

**Closed by anurse** 2019-10-23 18:44 UTC
Labels: area-hosting, more-info-needed
