### ISSUE TITLE
Status of QUIC transport

### ISSUE THREAD

**Issue by hismichael** [aspnet/AspNetCore#8394] opened 2019-03-11 03:36 UTC
What is the status of QUIC and HTTP over QUIC?

Is now an appropriate time point to visit implementing HTTP over QUIC? (I assume that QUIC is the transport layer)

Thanks

**Comment by shirhatti** [comment] 2019-03-11 06:22
HTTP/3 which is HTTP over QUIC is still being worked on by the IETF and is currently [still in draft](https://tools.ietf.org/html/draft-ietf-quic-http-18). We will revisit when once this has been ratified. 

I'm closing this as a dupe of #4695

**Closed by shirhatti** 2019-03-11 06:22 UTC
Labels: area-servers
