### ISSUE TITLE
Browser still Promot a Cert Selection Window to a user even with "ClientCertificateMode.AllowCertificate"

### ISSUE THREAD

**Issue by gynet** [aspnet/AspNetCore#18101] opened 2020-01-02 22:30 UTC
Our BE service support both token based auth and client cert based auth, and we would like to make the client cert request optional, we set ClientCertificateMode  to be AllowCertificate, but it will  makes browsers prompt for a certificate. How can I turn off the browser prompt? 
```C#
var webHostBuilder = new WebHostBuilder()
    .UseSerilog()
    .UseKestrel(options => {
        options.Listen(IPAddress.Any, port, listenOptions => {
            var httpsConnectionAdapterOptions = new HttpsConnectionAdapterOptions {

                // This line is required to allow a Client Certificate to be provided
                // for authentication with the Web API.  However, it also makes 
                // browsers prompt for a certificate.
                ClientCertificateMode = ClientCertificateMode.AllowCertificate, 

                SslProtocols = System.Security.Authentication.SslProtocols.Tls12,
                ServerCertificate = GetCertificate()
            };

        listenOptions.UseHttps(httpsConnectionAdapterOptions);
    });
```

**Comment by blowdart** [comment] 2020-01-02 23:32
Possible dupe of https://github.com/aspnet/AspNetCore/issues/18064

Although allow should make it optional/

**Comment by gynet** [comment] 2020-01-02 23:48
Any workaround for this issue?

**Comment by anurse** [comment] 2020-01-03 19:24
Triage discussion: Short of TLS renegotiation (which has a lot of problems, including TCP flow control deadlocks) there isn't really a way to have "optional" client certificates. The correct way to do this is to have a separate host binding, which is what #18064 is discussing.

Closing this as a duplicate of that one.

**Closed by anurse** 2020-01-03 19:24 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
