### ISSUE TITLE
Windows Authentication (Kerberos/NTLM) in asp.net core linux

### ISSUE THREAD

**Issue by FZ14** [aspnet/AspNetCore#4737] opened 2018-07-12 03:35 UTC
Hello.
Enterprise Application Development still requires Windows Authentication (via NTLM/Kerberos).
It perhaps in asp.net core development model on kestrel server in Linux?

**Comment by kenk667** [comment] 2019-02-07 15:39
This has been an issue within my organization as well. We run cloud foundry and have no desire to launch windows images just to be able to configure windows auth. It's surprising to hear how this isn't a priority when it's very common to have Windows AD as the identity provider with a dominantly linux enterprise environment. @blowdart please bring this into your current iteration.

**Comment by ChrisWeinrich** [comment] 2019-02-08 12:07
Same Here, we want to switch to NGNIX on Red Hat in a Big Enterprise Environment and missing AD authentication is a complete showstoper.

**Comment by Drawaes** [comment] 2019-02-08 12:11
Why don't you do the auth at NGNIX in this case? Surely this is only an issue (that I think is useful) for people running raw Kestrel.

**Comment by ChrisWeinrich** [comment] 2019-02-08 12:22
Ok then my understanding of auth and reverse proxies is not deep enough

**Comment by mertuarez** [comment] 2019-02-12 20:29
This message is show when mssql-cli is trying to connect to server which is not default realm.

**# cat /etc/krb5.conf**
```
[libdefaults]
        default_realm = SOME.LOCAL
[realms]
        SOME.LOCAL = {
                kdc = some-dc1
        }

        OTHER.LOCAL = {
                kdc = other-dc2
        }

[domain_realm]
        some.server1 = SOME.LOCAL
        other.server2 = OTHER.LOCAL

```
**# kinit principal@OTHER.REALM** 
**# mssql-cli -S other.server2**

```
Error message: Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Server not found in Kerberos database).
at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
```

This work normal

**# kinit principal@SOME.REALM** 
**# mssql-cli -S some.server1**

**Comment by Tratcher** [comment] 2019-04-09 17:44
Closing as a duplicate of https://github.com/aspnet/AspNetCore/issues/4662, which we're prototyping for 3.0.

**Closed by Tratcher** 2019-04-09 17:44 UTC
Labels: area-servers, enhancement, servers-kestrel

**Comment by fngch** [comment] 2019-07-26 19:15
Hello,
I am developing a microservice connect to sharepoint soap service by using .net core 3.0,hosted in docker(linux), and getting {System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Negotiate, NTLM', looks like sharepoint require NTLM+ Negotiate authentication scheme, .net core 3.0 only supports single authentication scheme, 
thank in advance for any suggestion on this.
-Charles

**Comment by Tratcher** [comment] 2019-07-26 20:14
@fngch Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

Client errors should be reported here: https://github.com/dotnet/corefx

**Comment by roeidalm** [comment] 2019-09-17 06:57
Hello @Drawaes, I try to integrate Kerberos authentication in my code (core 2/3) and it still not working. Can you help me with this?
