### ISSUE TITLE
First request regression

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#9401] opened 2019-04-15 22:37 UTC
Between `3.0.0-preview4-19204-02` and `3.0.0-preview4-19208-06`.

It's a lot of changes but it doesn't look like there were successful builds in between.

![image](https://user-images.githubusercontent.com/1165805/56169799-2dd14a00-5f94-11e9-93ba-f7d3ec4779d7.png)

The chart above is for JsonPlatform.

Changes:
https://github.com/aspnet/AspNetCore/compare/518b879895d1c2e2b5bac716c8c4f9806e92dcfc...1a259fb49ee2d4d296de984b6f8336143f46356b

**Comment by pranavkm** [comment] 2019-04-16 03:56
Includes the change where we bumped up the runtime: https://github.com/aspnet/AspNetCore/commit/1b500858354efe26493af632bf0e3f5462dc6246#diff-8b8f08ffbf7b863fb3700c1718eeb4cbL23

**Comment by Eilon** [comment] 2019-04-16 15:54
Which scenario is this?

**Comment by sebastienros** [comment] 2019-04-17 00:22
Apparently all the scenarios are impacted. I will do some more investigation. But filing so we don't forget.

**Comment by Eilon** [comment] 2019-04-17 00:23
Got it. Just trying to figure out if it's MVC-specific, EF-specific, or general.

**Comment by anurse** [comment] 2019-06-10 15:00
Apparently we forgot :). @sebastienros are we still seeing this regression across all scenarios in our current builds?

**Comment by anurse** [comment] 2019-07-09 22:40
Looking at the latest benchmarks data, it looks like we're back. It also looks like this was really jittering while it was "regressed" so maybe this was a machine configuration thing?

![image](https://user-images.githubusercontent.com/7574/60927753-cf003180-a25f-11e9-9ed1-5f7746aba20f.png)

Closing based on that.

**Comment by sebastienros** [comment] 2019-07-10 07:11
It's jettery if you are looking at two scenarios at the same time. In your case u assume it was because both Linux and Windows where displayed, and it started to look correct since the windows numbers and re bit gathered anymore.

**Comment by anurse** [comment] 2019-07-10 15:54
Ah, I see now. The initial issue wasn't clear on which scenarios were affected but it looks like if I isolate to Windows, there is still a regression:

![image](https://user-images.githubusercontent.com/7574/60984288-52696380-a2f0-11e9-8238-9111daea0519.png)

**Comment by anurse** [comment] 2019-07-10 15:55
ConnectionClose appears to be the one with the clearest regression. Many scenarios have no regression, Plaintext (and it's variants) has one.

**Comment by anurse** [comment] 2019-07-16 22:35
Assigning @davidfowl since he apparently is exploring a theory.

**Comment by anurse** [comment] 2019-07-23 21:58
@davidfowl what is outstanding here? Do we still need someone to look in to this regression?

**Comment by davidfowl** [comment] 2019-07-23 23:17
Not sure, there might be but I believe there wasn’t a change to ASP.NET Core when the original regression happened

**Comment by anurse** [comment] 2019-07-26 20:49
If we believe this regression is significant, we can evaluate it in 3.0-preview9.

cc @sebastienros @davidfowl

**Comment by anurse** [comment] 2019-07-30 22:26
@jkotalik believes his changes will improve this. If not, we'll bump this out.

**Comment by jkotalik** [comment] 2019-08-08 21:29
![image](https://user-images.githubusercontent.com/8302101/62738960-7bad0a80-b9e8-11e9-93b6-3a35bde87982.png) (linux, http, kestrel sockets).

Seems like my change positively affected time to first response. The CVE patch occured on 8/1, and we see the time to first response decrease on 8/2. I'm going to remove my assignment. @sebastienros feel free to close too if you believe this scenario looks good.

**Comment by sebastienros** [comment] 2019-08-08 21:37
The green part went down, which is the startup time (JITing mostly) so it should not be related.

**Comment by sebastienros** [comment] 2019-08-08 21:38
But overall we are faster than 2.2, and faster than the number when we reported this issue, so I think we should close it.

**Closed** 2019-08-08 22:06 UTC
Labels: area-servers, area: Performance
