### ISSUE TITLE
Blazor WebAssembly Locks up UI when working with Tasks/Delegates

### ISSUE THREAD

**Issue by enusbaum** [aspnet/AspNetCore#16954] opened 2019-11-10 14:20 UTC
### Describe the bug
I have a scenario where I'm invoking a long running task that updates at regular intervals. My internal application is actually a class that is rendering bitmaps at 60fps and invoking a delegate with each rendered frame. I noticed that as soon as I started the task, the entire browser UI (Chrome) locks up. 

I boiled the scenario down to brass tacks and posted a repo with the example scanario.

[https://github.com/enusbaum/BlazorWASMLockup](https://github.com/enusbaum/BlazorWASMLockup)

I setup several scenarios in this example both using **Thread.Start()**, **Task.Run()**, and **Task.Factory.StartNew()**

When invoking Thread.Start() on a Thread object, an error is immediately thrown to the console:
```
WASM: * Assertion: should not be reached at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/utils/mono-threads-wasm.c:254
```
Invoking the tasks appears to start them and they seem to be running as the delegate is being invoked (Console logs verify this), but the UI completely locks up and becomes unresponsive.

### To Reproduce

View repo mentioned above. Basic solution of Class that takes in a delegate in the constructor, then a long running task/thread invokes the delegate at regular intervals.

I published the above test application to the following URL:
[https://blazorlockup.z13.web.core.windows.net/](https://blazorlockup.z13.web.core.windows.net/)

### Further technical details
- dotnetcore 3.1.100-preview2-014569
- Visual Studio Professional 16.4 Preview 4
- Chrome 78.0.3904.87 (Official Build) (64-bit)

**Comment by Andrzej-W** [comment] 2019-11-10 19:44
Unfortunately I don't have time to check your code now, but you should remember that Blazor Wasm works in a single thread. Currently you cannot create additional threads. This limitation exists in Wasm not in Blazor itself.

**Comment by enusbaum** [comment] 2019-11-10 20:07
Ah, thanks @Andrzej-W! That would seen to make sense then.

So anywhere in the application, even if it's another "Thread/Task", anything that would pause that "thread" execution (**.Wait()**, **.Sleep()**, etc.) actually pauses the entire application. I imagine then the Mono AOT is just doing some smoke and mirrors when it comes to handling of Tasks.

In my example then, while the delegate is getting executed, the immediate following Sleep/Wait pauses the entirety of the application until the timeout at which point it fires the delegate again and pauses.

**Comment by enusbaum** [comment] 2019-11-10 20:11
Further investigation based on your feedback pointed me to this previously reported bug:

[https://github.com/aspnet/AspNetCore/issues/14253](https://github.com/aspnet/AspNetCore/issues/14253)

It would seem in my example I'd need to refactor to have the running task Yield vs. waiting as it's running in a single threaded context.

**Comment by javiercn** [comment] 2019-11-11 13:25
@enusbaum thanks for contacting us.

As per the other issue, you should avoid blocking the thread as you will lock the UI.

I'm closing this issue as there's nothing for us to do here.

**Comment by javiercn** [comment] 2019-11-11 13:25
This is a duplicate of https://github.com/aspnet/AspNetCore/issues/14253

**Closed by javiercn** 2019-11-11 13:25 UTC
Labels: area-blazor, blazor-wasm
