### ISSUE TITLE
WebSocket.ReceiveAsync and KeepAliveInterval

### ISSUE THREAD

**Issue by sepehr1014** [aspnet/AspNetCore#3128] opened 2018-05-09 10:00 UTC
We're using .NET Core 2.1 RC1 and we've set keep-alive interval using
`app.UseWebSockets(new WebSocketOptions() { KeepAliveInterval = TimeSpan.FromSeconds(10) })`

But when the client is disconnected without sending the close frame (because of connection loss or power outage for instance), `WebSocket.ReceiveAsync` does NOT return even after 10 seconds. My understanding is that if the server is not receiving a pong frame in 10 seconds, the connection should be regarded as dead and `ReceiveAsync `should return an empty result.

BTW this is behind IIS on Windows Server 2016 with the latest updates installed. We've also set IIS ping pong in application host config. (Though as far as I know .NET Core 2.1 does not use libuv anymore and sockets are handled in managed code)

**Comment by sepehr1014** [comment] 2018-06-06 12:42
Any updates on this issue?

**Comment by Tratcher** [comment] 2018-07-16 18:02
ANCM/IIS or CoreFx WebSockets.

**Comment by Eilon** [comment] 2018-07-16 18:45
@Tratcher where do you think we should start? If the bug doesn't belong here, I'd like to at least move it to somewhere more likely.

**Comment by Tratcher** [comment] 2018-07-16 18:58
By trying to repro with and without ANCM/IIS.

**Comment by Eilon** [comment] 2018-07-16 21:05
@jkotalik - could you take a look at this to see where it should go? Thanks!

**Comment by jkotalik** [comment] 2018-07-19 17:37
@sepehr1014 just to clarify, does `WebSocket.ReceiveAsync` ever return? Also, what version of ANCM are you using (specifically dll file version under Windows\System32\inetsrv. 

If you have a repro available, please follow up by emailing me at the email listed on my github profile.

**Comment by jkotalik** [comment] 2018-07-25 06:43
> ping functionality is not yet implemented by ASP.NET Core

When you say ASP.NET Core, do you mean the websocket middleware or ANCM itself? I'm fairly sure that AspNetCore implements pings.

**Comment by pan-wang** [comment] 2018-07-25 09:03
Ping/pong is handled by windows websocket (networking) and winhttp separately and never hit ANCM.  In the case of client disconnected and HTTP.sys did not notify ANCM, ANCM will not send the close frame. The back-end thus will not close the websocket connection and wait on the async receive. I could not repro this disconnect (missing client disconnect from HTTP.sys) issue locally. Need a repro app to further investigation.  A workaround is to let the back-end sends some ping message periodically  as SignalR does.

**Comment by moshegutman** [comment] 2018-08-28 03:43
I'm experiencing this issue too with my app hosted in Azure App Service.

**Comment by moshegutman** [comment] 2018-08-28 19:59
Is there a workaround for this? @pan-wang

**Comment by moshegutman** [comment] 2018-08-29 21:36
@jkotalik I can repro this issue in IISExpress and IIS. The issue does not occur when running as a self-host server.

**Comment by pan-wang** [comment] 2018-08-30 04:43
@moshegutman  the workaround depends on the nature of the application. Could you please share your repro so that I can take a look? You can reach me at panwang(at)Microsoft(dot)com.

**Comment by zlatanov** [comment] 2018-09-03 14:47
@pan-wang I've created a simple repo here: https://github.com/zlatanov/aspnetcore-websockets-experiments. A simple server that only ever expects Pings and replies with Pongs.

If you run it Kestrel, works as expected. If you run it with IIS or IIS Express, doesn't work. Connect a simple websocket client that doesn't do anything but send pings.

**Comment by andriusbutk** [comment] 2018-10-11 14:13
Is there any update? We are having issues responding to pings on Azure app service(ASP.NET CORE 2.1) similarly to everyone above. Is there a known workaround for this issue on app service(ASP.NET CORE 2.1)?

**Comment by florinciubotariu** [comment] 2018-10-25 09:18
On another PC, where an old version of AspNetCoreModule was installed (version starting with 7.1), this bug would not reproduce. After upgrading the .NET Core Hosting Bundle with the latest version, the bug is reproducible.

**Comment by Eilon** [comment] 2018-10-25 18:22
@jkotalik / @pan-wang - any further ideas on this?

**Comment by NPSF3000** [comment] 2018-10-30 20:09
We've discovered the same bug in our WS prod code.  Setting KeepAliveInterval = TimeSpan.FromSeconds(120) completely failed to detect an incorrectly shutdown client.  We suspect this has lead to significant performance degradation due to increased load.

**Comment by ConnorL33t** [comment] 2018-11-14 19:32
I'm running into this issue as well. Server is an Azure App service instance.

**Comment by Eilon** [comment] 2018-11-15 17:34
@zlatanov we are working on a resolution to this issue - we will provide an update in this issue when we have more to report.

**Comment by Rakiah** [comment] 2018-12-31 14:56
Any information about this ?
still not working in ASP.NET Core 2.2.2

**Comment by davidfowl** [comment] 2018-12-31 17:35
What isn’t working? In 2.2 we added pings from client to server as well. It has nothing to do with the keep alive interval and in fact you shouldn’t configure that separately because we disable it in favor of our own pings

**Comment by sepehr1014** [comment] 2019-01-01 08:36
@davidfowl What do you mean by your "own" pings? Is there any documentation on how ping-pong should be implemented in ASP.NET Core?

**Comment by zlatanov** [comment] 2019-01-03 14:34
@davidfowl I have created a Unit Test to illustrate the issue. The branch with the test is here - https://github.com/zlatanov/AspNetCore/tree/ws-keep-alive-issue.

The actual test - https://github.com/zlatanov/AspNetCore/blob/f21fcd3f3ab7b0f585385a65701160e6a4ad6ad0/src/Middleware/WebSockets/test/UnitTests/SendReceiveTests.cs#L109.

The NET Core WebSocket client does send a keep alive frame, but the server socket never receives it.

**Comment by jkotalik** [comment] 2019-01-11 21:44
Hey all, the issue originally state with websockets and IIS is fixed fixed. Please download the latest versions of 2.1, 2.2, and 1.x: https://dotnet.microsoft.com/download/dotnet-core/2.1, https://dotnet.microsoft.com/download/dotnet-core/2.2, and https://dotnet.microsoft.com/download/dotnet-core/1.1.

**Comment by jkotalik** [comment] 2019-01-11 21:46
@zlatanov are you using IIS in that unit test? It doesn't look like it, so you may have a different issue.

**Comment by jkotalik** [comment] 2019-01-30 00:16
Closing as the original issue is resolved.

**Closed by jkotalik** 2019-01-30 00:16 UTC
Labels: area-servers, investigate
