### ISSUE TITLE
Symbols don't work

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8604] opened 2019-03-17 17:40 UTC
Our symbols aren't available anywhere documented, so they should be on the public MS symbol server. This is a blocker to doing any kind of bug investigation using our installers/nightlies. I assumed that we were getting this as part of the dotnet/arcade effort.

**Repro steps:**
1. Create a razor components project
2. Enable the public MS symbol server and source link 
3. Turn on first chance exceptions and turn off just my code
4. Debug the app

You will hit a breakpoint at an exception during startup. You can resolve symbols for BCL and CoreCLR assemblies, but not for anything from ASP.NET Core.

**Comment by adrianwright109** [comment] 2019-03-22 11:07
Duplicate of #7710 ?

**Comment by davidfowl** [comment] 2019-04-01 04:21
> Our symbols aren't available anywhere documented, so they should be on the public MS symbol server. This is a blocker to doing any kind of bug investigation using our installers/nightlies. I assumed that we were getting this as part of the dotnet/arcade effort.

They should be pushed to myget. Add https://dotnet.myget.org/F/aspnetcore-dev/symbols as a symbol server https://dotnet.myget.org/F/aspnetcore-dev/symbols

**Comment by pranavkm** [comment] 2019-04-15 21:26
Closing as duplicate of https://github.com/aspnet/AspNetCore/issues/7710. Adding some notes https://github.com/aspnet/AspNetCore/pull/9396 that describes how to turn on stepping in to ASP.NET Core sources.

**Closed by pranavkm** 2019-04-15 21:26 UTC
Labels: area-infrastructure, duplicate, infra-thon
