### ISSUE TITLE
ASP.NET Core 3.0 Use UseStatusCodePagesWithReExecute  invalid

### ISSUE THREAD

**Issue by dreamdocker** [aspnet/AspNetCore#16838] opened 2019-11-05 03:41 UTC
`app.UseStatusCodePagesWithReExecute("/StatusCode", "?code={0}");`

The above code can't be executed in ASP.NET Core 3.0, no error is reported, and the custom error page is not executed. After the project is rolled back to version 2.2, everything is normal. How can I solve it?

**Comment by Tratcher** [comment] 2019-11-05 16:17
Duplicate of https://github.com/aspnet/AspNetCore/issues/13715, already fixed in 3.1.
Mitigation: https://github.com/aspnet/AspNetCore/issues/13715#issuecomment-528929683

**Closed by Tratcher** 2019-11-05 16:17 UTC
Labels: area-middleware
