### ISSUE TITLE
Multiple registered JWTBearerHandlers cause unwanted RefreshRequests

### ISSUE THREAD

**Issue by eliaslopezgt** [aspnet/AspNetCore#14397] opened 2019-09-24 21:18 UTC
### Describe the bug
When multiple JWTBearerHandlers are registered with their configuration defaults loaded from an `Authority` URI, the default value of `RefreshOnIssuerKeyNotFound ` is set to true.  This causes  unwanted `RefreshRequests` from the JWTBearerHandler that couldn't validate the Token. 

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Register two JWTBearerHandlers by using the `AddJwtBearer` extension method using only the `Authority` and `Audience` properties.
3. Test an endpoint with a token that can be validated with one of them but not the other.
4. Using fiddler or a similar tool, look at the traffic to the configuration endpoint of the BearerHandler that failed the validation.

### Expected behavior
This behavior is acceptable as long as there's only one `JWTBearerHandler`.
Having multiple `JWTBearerHandlers` results in unwanted traffic to the configuration endpoints.
This can be currently mitigated by:

1. Setting the `RefreshInterval` to something different than its default (30 seconds)
2. Setting `RefreshOnIssuerKeyNotFound` to false in all the `JWTBearerHandlers`

My proposed solution is to create an additional `OnSignatureValidationFailed` event that can be triggered before `Options.ConfigurationManager.RequestRefresh();` in `JwtBearerHandler.cs` 
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs

This with the purpose of allowing the caller to intercept the `RequestRefresh` and in this case, inject logic that can compare the `invalid token` audience and authority, with the audience and authority of `the handler`, if they are the same, then trigger the refresh. 

The only change to the JWTBearerHandler is the addition of the `OnSignatureValidationFailed` event. I have a PR ready but wanted to discuss if this could bring any value or not.

**Comment by blowdart** [comment] 2019-09-24 21:28
Closing as dupe of https://github.com/aspnet/AspNetCore/issues/13046

**Closed by blowdart** 2019-09-24 21:28 UTC
