### ISSUE TITLE
Ensure targeting pack dependency versions are pinned for patch builds.

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#8633] opened 2019-03-18 21:38 UTC
https://github.com/aspnet/AspNetCore/pull/8490#issuecomment-473559281

**Comment by Eilon** [comment] 2019-04-05 21:44
Needs to be done at ~RTM time, before we ship any patch. Might need to be done earlier if we do a patch prototype prior to RTM, which is a likely possibility.

**Comment by natemcmaster** [comment] 2019-07-22 17:45
@Pilchie this one affects servicing 3.0.x and would be good to review for RTM.

**Comment by anurse** [comment] 2019-08-05 20:29
If I'm understanding correctly, the main work here is to ensure the `deb` and `rpm` packages have a *fixed* dependency to `3.0.0` of the .NET Core targeting pack, right? Seems straightforward enough. We can't actually make that change until we ship though, since we *do* need to reference the active preview version as we're still shipping previews.

**Comment by dougbu** [comment] 2019-11-05 01:11
At this point, our incoming ref packages (from Extensions and core-setup) should both be pinned at 3.0.0. The remaining work before we close this issue is to stop building the AspNetCore targeting pack after 3.0.1 ships.

@JunTaoLuo please confirm

**Comment by JunTaoLuo** [comment] 2019-11-05 19:33
That is correct, we have pinned the ref pack version in the deb and rpm installers. However, there shouldn't be any work required to stop building the targeting pack since it's already conditional on 3.0.1: https://github.com/aspnet/AspNetCore/blob/release/3.0/Directory.Build.props#L93-L94.

**Comment by JunTaoLuo** [comment] 2019-11-05 19:45
Curious if any of this logic will be impacted by the 3.0.2 changes you're making @dougbu ?

**Comment by dougbu** [comment] 2019-11-05 19:56
Not really. I am however concerned about what will happen w/ the checked-in approach once we stop building the targeting pack. Will the infrastructure still build ref/ projects and reference them? Can we test today or tomorrow to make sure we're :ok:?

**Comment by JunTaoLuo** [comment] 2019-11-05 20:59
I'll try it out and report back.

**Comment by wtgodbe** [comment] 2019-11-25 23:45
@JunTaoLuo are you on this for 3.1.1 as well?

**Comment by JunTaoLuo** [comment] 2019-12-11 22:44
I think there's no longer any action to take here. We have updated the targeting pack dependencies to use the version of Microsoft.NETCore.App.Ref dependency: https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Installers/Debian/TargetingPack/debian_config.json.in#L33. The same is also true for 3.1 and master. Given that in 3.0 we have pinned the dependency at 3.0.0 (and 3.1.0 in 3.1) the dependency version will be correct if we ever need to service the targeting pack again.

**Comment by dougbu** [comment] 2019-12-11 23:47
Fine to close since we also confirmed the Microsoft.Internal.Extensions.Ref versions coming into AspNetCore are pinned.

**Closed** 2019-12-11 23:48 UTC
Labels: PRI: 1 - Required, area-platform, bug
