### ISSUE TITLE
.NET Razor components : System.InvalidOperationException: ComponentHub doesn't have an associated endpoint. 

### ISSUE THREAD

**Issue by asterinex** [aspnet/AspNetCore#8619] opened 2019-03-18 08:10 UTC
Hello All,

I have a problem running .Net Core 3 Razor Components application on my Computer (VS 2019 RC Locally IIS Express 10)
The application starts, but no events are triggered.
A click on the 'Click-me'-Button (Counter) throws following Exception : 

Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService: Information: Request starting HTTP/1.1 GET https://localhost:44312/_blazor?id=-aCKSIUuo3sQlQyYp2IIfg&_=1552896387899  
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher: Error: Failed to invoke hub method 'StartCircuit'.

System.InvalidOperationException: ComponentHub doesn't have an associated endpoint. Use 'app.UseRouting(routes => routes.MapComponentHub<App>("app"))' to register your hub.
   at Microsoft.AspNetCore.Components.Server.Circuits.DefaultCircuitFactory.ResolveComponentMetadata(HttpContext httpContext, IClientProxy client)
   at Microsoft.AspNetCore.Components.Server.Circuits.DefaultCircuitFactory.CreateCircuitHost(HttpContext httpContext, IClientProxy client, String uriAbsolute, String baseUriAbsolute)
   at Microsoft.AspNetCore.Components.Server.ComponentHub.StartCircuit(String uriAbsolute, String baseUriAbsolute)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamResponse, Boolean isStreamCall)

My Setup :
Windows 7, IIS Express 10,  .Net 3.0.100-preview3-010431
Visual Studio 2019, RC 16.0.0 RC2, Version 4.7.0.3062

How Can I solve this?  I need to develop locally on IIS 10 Express ?

Regards, 
Gert

**Comment by rynowak** [comment] 2019-03-18 16:29
> System.InvalidOperationException: ComponentHub doesn't have an associated endpoint. Use 'app.UseRouting(routes => routes.MapComponentHub("app"))' to register your hub.

Do you have something like that in your startup code?

**Comment by mkArtakMSFT** [comment] 2019-03-18 20:21
@asterinex, it's not clear whether the `MapComponentHub<App>("app")` call is in your original app, or in the newly created project only?

**Comment by asterinex** [comment] 2019-03-19 05:14
I have no original App. I just want to create my first project with .Net Core 3 Razor Components.
I have created the default template in Visual Studio RC.which uses the MapComponentHub.

This Github-Project gives me the same problem :
https://github.com/akorchev/razor.radzen.com
I can build and start the application, but no events are triggered.

**Comment by asterinex** [comment] 2019-03-19 12:34
I have upgraded the Windows 7 to Windows 10 (new install). Installed Visual Studio 2019 and .Net Core 3.0 SDK and it worked immediately.
I think the problem is related to Windows 7 ?

**Comment by mkArtakMSFT** [comment] 2019-03-19 16:13
Thanks @asterinex.
It sounds like SignalR has certain requirements from the OS, we we're not familiar with.
@anurse is this because of Windows7?

**Comment by mkArtakMSFT** [comment] 2019-03-21 15:54
@asterinex, did you run Kestrel when running on Windows 7 PC?

**Comment by asterinex** [comment] 2019-03-21 16:31
> @asterinex, did you run Kestrel when running on Windows 7 PC?

I don't know what Kestrel is. 
In Visual Studio 2019 RC  under Debug-options  'IIS Express'  was choosen.

**Comment by SteveSandersonMS** [comment] 2019-03-22 16:23
OK, then this is a duplicate of #6920, so closing.

@asterinex Because you're on Windows 7, IISExpress doesn't support WebSockets. And because of #6920, the app can't fall back to any alternative to WebSockets, so it all fails. A short-term workaround for you would be to launch directly in Kestrel instead of IISExpress by picking the following option:

![image](https://user-images.githubusercontent.com/1101362/54837653-2f08a300-4c84-11e9-8281-368936c57202.png)

(Replace "CarBuyer" with the name of your project)

**Closed by SteveSandersonMS** 2019-03-22 16:23 UTC
Labels: area-mvc, external, feature-Components

**Comment by mihaimyh** [comment] 2019-04-17 22:12
I have this issue too. 

I created a new `dotnet new razorcomponents` using command line since I don't have the template in VS2019 (Version 16.1.0 Preview 1).

When running the app using Kestrel and accessing it from my mobile phone browser it throws this exception:

`Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'StartCircuit'.
System.InvalidOperationException: ComponentHub doesn't have an associated endpoint. Use 'app.UseRouting(routes => routes.MapComponentHub<App>("app"))' to register your hub.`

In startup.cs I have:

```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting(routes =>
            {
                routes.MapRazorPages();
                routes.MapComponentHub<App>("app");
            });
        }
```
